### ISSUE TITLE
Reducing arrow file size when subsetting projects for specific cells?

### ISSUE THREAD

**Issue by ioansarr** [GreenleafLab/ArchR#100]
Hi guys,

Impressive work, this tool is amazing!

One suggestion for improvement/ question in case I am missing something obvious: I tried subsetting projects to a smaller subset of cells (through both subsetArchRProject() and subsetCells() followed by saving the new project to a new directory). In both cases the size of the copied arrow files is the same as with the original project. This can quickly get out of hand in terms of storage usage if one is trying to analyse multiple small subsets of a dataset consisting of many samples. This should be a common problem for people analysing highly heterogeneous datasets. Is there a way to subset the arrow files to only relevant cells for each project, thus only storing relevant information and saving up space?

An obvious get-around would be to perform the analysis for each subproject, extract relevant information (new embeddings, clusters) then remove the arrow files to release space. But that would go against the whole point of using the arrow files, i.e. reproducibility.

Once again, thanks for the great job!

**Comment by rcorces** [comment]
I think this is a reasonable feature request. @jgranja24 can correct me if I'm wrong but I believe there are a few problems with this. One problem is a trade off of speed vs storage space. If you want to subset the Arrow files when saving an ArchRProject, I think you would essentially need to re-create those Arrow files from scratch.

I think a reasonable solution would be to add a parameter to `saveArchRProject()` that allows for subsetting Arrow files during copying but @jgranja24 knows more about this than I do.

From a documentation standpoint - project subsetting documentation isnt in the manual yet but I'm working on it.

**Comment by ioansarr** [comment]
Thanks for the fast reply! 

At the moment even creating new arrow files with manually setting the validBarcodes parameter seems to result to similarly-sized arrow files. Seems like the size of the arrow file depends on the size of the associated fragments file. 

At the moment, the most viable solution for me is to subset the fragments files, index them again and recreate the arrow files for each subproject.

**Comment by jgranja24** [comment]
Yeah I understand the difficulties with something like this. I need to think a bit on this because its pretty complicated to write a function to properly address subsetting cells.

**Comment by jgranja24** [comment]
I should have a solution for this up and running later today, thank you for your patience.

**Comment by jgranja24** [comment]
This is now functional in the new master update. See `subsetArchRProject` and `saveArchRProject` for the `dropCells` argument. This will drop non cells in the project. I spent a while making sure this works. Closing this issue feel free to reopen if further issues.

**Comment by rcorces** [comment]
I think the current implementation of this could still be improved. My intuition is that most users would use this to subset an ArchRProject based on some biological question. For example, I wonder what it looks like when I only analyze T cells from my PBMC data. In this instance, some of the auxiliary files associated with the master ArchRProject are not necessarily relevant for the subsetted ArchRProject. For example, LSI iterations, group coverages etc. I would even venture to say that, in many cases, the only files that are relevant are the Arrow files when subsetting a project.

If you agree with this, I think the solution would be to have a boolean parameter `justArrows` that allows users to only copy the subsetted Arrow files. I can see this causing problems if the ArchRProject that gets copied for the subset expects to be able to find auxiliary information in folders such as group coverages etc. So this may not be a straightforward fix without wiping excess info from the ArchRProject.

**Comment by ioansarr** [comment]
@rcorces At least from my side, that was the initial motivation behind writing the post. Using the merged dataset to identify all cells that belong to a specific group, then starting the analysis from scratch focused on each group. In the end there is an easy solution for this outside the ArchR framework, which is to filter the fragment files for the relevant barcodes for each sample, reindex and make new arrow files for each group. So maybe you guys don't need to invest too much effort on this, especially if it ends up causing downstream problems with the ArchRProject structures.
