### ISSUE TITLE
createArrowFiles has encountered an error when using subset data

### ISSUE THREAD

**Issue by hukai916** [GreenleafLab/ArchR#1000]
createArrowFiles works fine with the example data: scATAC_BMMC_R1.fragments.tsv.gz, however, it complains when using subset data:

I first collected 10% sample from scATAC_BMMC_R1.fragments.tsv.gz with:
zcat scATAC_BMMC_R1.fragments.tsv.gz | awk 'NR%10 == 1' | gzip > subset.tsv.gz

Then,
createArrowFiles(inputFiles = "subset.tsv.gz", sampleNames = "subset")
It complains:
2021-08-24 22:12:01 : Batch Execution w/ safelapply!, 0 mins elapsed.
Attempting to index subset.tsv.gz as tabix..
2021-08-24 22:12:01 : createArrowFiles has encountered an error, checking if any ArrowFiles completed..
ArchR logging successful to : ArchRLogs/ArchR-createArrows-574811091d1c7-Date-2021-08-24_Time-22-12-00.log

**Comment by rcorces** [comment]
As indicated in the 10x genomics docs, fragment files are not gzipped, they are bgzipped.
https://support.10xgenomics.com/single-cell-atac/software/pipelines/latest/output/fragments

> The data is block-gzipped to allow indexing and to save disk space

**Comment by hukai916** [comment]
Thanks, it worked with bgzip. 
I suggest ArchR check the format of fragment file since fragment files can be converted from bam or from other platforms that may not necessarily be bgzipped.
