### ISSUE TITLE
batch correction

### ISSUE THREAD

**Issue by Brawni** [GreenleafLab/ArchR#101]
Hi there!

Thanks a lot for providing such an amazing tool for scATAC-seq analysis!! I just started analyzing my data following the tutorial. I have three samples perfumed by different labs and showing large differences in sequencing depth. I was previously aggregating the samples using cell ranger which normalise for sequencing depth and take it from there. Is it possible to do something like this with ArchR? Or should i input the aggregated fragment file?

Thanks!

**Comment by rcorces** [comment]
It sounds like youre asking about two things.
1) Normalization - normalization in ArchR is performed "as needed" on a per-function basis. For ex. `getMarkerFeatures()` has the parameter `normBy` which indicates the column in `cellColData` by which normalization that should be performed (i.e. "ReadsInTSS"). ArchR does not require any normalization prior to Arrow file creation so you should not aggregate your samples.

2) Batch correction is separate from normalization. Explicit batch correction in ArchR uses `Harmony` but there are other less heavy-handed approaches that can mitigate small batch effects, for example estimated LSI. These are discussed in the manual in the chapter on dimensionality reduction.

I will make a note to add information on normalization to the manual as it is currently lacking. Feel free to re-open this issue if this has not answered your question.
