### ISSUE TITLE
Error in removing doublets

### ISSUE THREAD

**Issue by beginner984** [GreenleafLab/ArchR#1011]
Hi

Sorry, I am trying to remove doublets but I am getting error

This is what I have done so far

```
inputFiles <- c('scATAC' = "atac_fragments.tsv.gz")

 ArrowFiles <- createArrowFiles(
     inputFiles = inputFiles,
     sampleNames = names(inputFiles),
     filterTSS = 4, #Dont set this too high because you can always increase later
     filterFrags = 1000, 
     addTileMat = TRUE,
     addGeneScoreMat = TRUE
   )

myproj <- ArchRProject(
    ArrowFiles = ArrowFiles, 
    outputDirectory = "HemeTutorial",
    copyArrows = TRUE #This is recommened so that if you modify the Arrow files you have an original copy for later usage.
)

doubScores <- addDoubletScores(
    input = myproj,
    k = 10, #Refers to how many cells near a "pseudo-doublet" to count.
    knnMethod = "UMAP", #Refers to the embedding to use for nearest neighbor search with doublet projection.
    LSIMethod = 1
  )

projHeme2 <- filterDoublets(myproj)
Error in value[[3L]](cond) : select Not Found in Colnames of cellColData:
Error: Problem with `mutate()` column `tmpNewCol123`.
ℹ `tmpNewCol123 = eval(parse(text = select[x]))`.
x object 'DoubletEnrichment' not found

```
I have re-installed the software from scratch but no difference 

Likely doubScores is not attaching to the project 

However I am not sure how to attach that properly

Please help me 

Thank you 

[ArchR-addDoubletScores-3d19193f28d9-Date-2021-08-31_Time-15-18-54.txt](https://github.com/GreenleafLab/ArchR/files/7084899/ArchR-addDoubletScores-3d19193f28d9-Date-2021-08-31_Time-15-18-54.txt)

**Comment by rcorces** [comment]
I would assume that this is related to your use of cellranger aggr output which is not an approved input to ArchR. Once you correct that, feel free to post again here if you continue to have this problem

**Comment by beginner984** [comment]
Hello

I have created this metadata file which address sample names corresponding to cell barcodes like this

```
> head(metadata)
X  sample   group
1 AAACAGCCAACAGGAT-1 sample1 control
2 AAACAGCCAAGATTCT-1 sample1 control
3 AAACAGCCAAGGTATA-1 sample1 control
4 AAACAGCCATAATTGC-1 sample1 control
5 AAACAGCCATCAATCG-1 sample1 control
6 AAACAGCCATCAGCAC-1 sample1 control
> dim(metadata)
[1] 26473     3
> unique(metadata$sample)
[1] "sample1" "sample2" "sample3" "sample4" "sample5" "sample6" "sample7" "sample8"
> 
  > unique(metadata$group)
[1] "control"  "survivor"
>

```

Now how I can add that to my project like I have had separate sample from the scratch?

Thank you for any help

**Comment by rcorces** [comment]
As I mentioned before, we do not support this type of input for ArchR. If you must use this, then getting it to work is up to you.
