### ISSUE TITLE
Installing ArchR

### ISSUE THREAD

**Issue by hahahah-single** [GreenleafLab/ArchR#1030]
I install ArchR with devtools::install_github("GreenleafLab/ArchR", ref="master", repos = BiocManager::repositories()) get this Note: 
(1)possible error in '.loadUWOT(embedding$params$uwotModel, ': unused argument (embedding$params$nc) and (2)Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  : storing paths of more than 100 bytes is not portable:
‘ArchR/.github/ISSUE_TEMPLATE/bug-error-report---no-usage-questions---feature-requests--use-discussions--.md’. 
Can I ignore it and what impact will this have?

**Comment by rcorces** [comment]
yes its fine
