### ISSUE TITLE
Footprinting.R line 504 minor error?

### ISSUE THREAD

**Issue by will-NYGC** [GreenleafLab/ArchR#1034]
Is line 504 in Footprinting.R correct? `errorList$biasMatNorm <- footMat`

Or is it meant to be `  errorList$biasMatNorm <- biasMat`?

So far as I can tell, it doesn't seem to have major effect on any core function, right?

**Comment by rcorces** [comment]
Thanks for posting. You are correct - this looks like a typo. Fortunately it  is just adding the wrong variable to the list for error reporting purposes and does not have any effects on downstream functionality. I've corrected this via https://github.com/GreenleafLab/ArchR/commit/87b2dfb8d4d478bec551e137cbe503c83dd6a4a6 in `release_1.0.2`

For reference:
https://github.com/GreenleafLab/ArchR/blob/2be1294eb1fbff364fb538d71f4f545ee4384d09/R/Footprinting.R#L504
