### ISSUE TITLE
Error in plotting a heatmap of peak-to-gene links

### ISSUE THREAD

**Issue by CSBioAzim** [GreenleafLab/ArchR#104]
Hi, 

I'm doing an integrated analysis of scRNA-seq and scATAC. Everything worked well, and I was able to plot browser tracks with peak-to-gene links. Unfortunately, when I want to plot a heatmap of peak-to-gene links, I get the following error:

```

> p <- plotPeak2GeneHeatmap(ArchRProj = projHeme5, groupBy = "Clusters2")
ArchR logging to : ArchRLogs/ArchR-plotPeak2GeneHeatmap-3d41e9eeaee-Date-2020-05-04_Time-17-33-56.log
If there is an issue, please report to github with logFile!
Error in !metadata(p2g)$seATAC : invalid argument type
```
I've attached the log file. I would be happy to get your feedback on it.

[ArchR-plotPeak2GeneHeatmap-3d41e9eeaee-Date-2020-05-04_Time-17-33-56.log](https://github.com/GreenleafLab/ArchR/files/4577764/ArchR-plotPeak2GeneHeatmap-3d41e9eeaee-Date-2020-05-04_Time-17-33-56.log)

**Comment by jgranja24** [comment]
this is now fixed in the dev branch. I will commit it sometime this week to master

`devtools::install_github(
"GreenleafLab/ArchR",
ref="dev_050120",
repos = BiocManager::repositories()
)`

Closing this issue. Feel free to reopen if you have further issues.

**Comment by CSBioAzim** [comment]
@jgranja24  thanks!
