### ISSUE TITLE
Subclustering a specific cell type after clustering?

### ISSUE THREAD

**Issue by CSBioAzim** [GreenleafLab/ArchR#105]
Hi, 
I do cluster my scATAC-seq data, and for downstream analysis, I want to only select specific cell type (let's say cell type A), and do subclassing and continue the rest of analysis with this subcluster. I was wondering how can I achieve this with ArchR.
I just checked that 
```
projHeme2 <- addClusters(
    input = projHeme2,
    reducedDims = "IterativeLSI",
    method = "Seurat",
    name = "Clusters",
    resolution = 0.8
)
```
does not have any option to specify any specific cell type.

Thanks!

**Comment by rcorces** [comment]
You should use the `subsetArchRProject()` function to obtain an ArchRProject corresponding to the cells you are interested in and then proceed as normal. This will be added to the documentation soon.

https://www.archrproject.com/reference/subsetArchRProject.html

**Comment by CSBioAzim** [comment]
@rcorces Thanks!

**Comment by sylestiel** [comment]
Hi, 
 If we wish to Subcluster **any one** of the clusters how should I proceed? Say there are 8 clusters and I want to subcluster C5 further. 
Can you provide the script for doing so.
Also would we have to go back and repeat the iterative LSI and clustering and embedding steps thereafter.
I could you more clarification on this topic.

Thanks!
