### ISSUE TITLE
fail to run with tutorial 

### ISSUE THREAD

**Issue by GouQiao** [GreenleafLab/ArchR#1051]
Hi,

I am just starting to learn ArchR for scATACseq.
I am using mac, and R version 4.1.1.
however, I could not successfully install ArchR by devtools at the begining(succeeded by downloading on git)
The codes I ran were totally same with tutorial.
But I stuck on making arrowfiles: 

ArrowFiles <- createArrowFiles(
  inputFiles = inputFiles,
  sampleNames = names(inputFiles),
  filterTSS = 4, #Dont set this too high because you can always increase later
  filterFrags = 1000, 
  addTileMat = TRUE,
  addGeneScoreMat = TRUE
)

- [ ] filterFrags is no longer a valid input. Please use minFrags! Setting filterFrags value to minFrags!
- [ ] filterTSS is no longer a valid input. Please use minTSS! Setting filterTSS value to minTSS!
- [ ] Using GeneAnnotation set by addArchRGenome(Hg19)!
- [ ] Using GeneAnnotation set by addArchRGenome(Hg19)!
- [ ] ArchR logging to : ArchRLogs/ArchR-createArrows-820c48d1257d-Date-2021-09-27_Time-12-20-37.log
- [ ] If there is an issue, please report to github with logFile!
- [ ] 2021-09-27 12:20:37 : Batch Execution w/ safelapply!, 0 mins elapsed.
- [ ] [E::hts_idx_push] Unsorted positions on sequence #2: 143625887 followed by 143626
- [ ] 2021-09-27 12:20:38 : createArrowFiles has encountered an error, checking if any ArrowFiles completed..
- [ ] ArchR logging successful to : ArchRLogs/ArchR-createArrows-820c48d1257d-Date-2021-09-27_Time-12-20-37.log
- [ ] Warning message:
- [ ] In mclapply(..., mc.cores = threads, mc.preschedule = preschedule) :
- [ ]   1 function calls resulted in an error

and when I checked ArrowFiles, I only have 2 data: 
> ArrowFiles
[1] "scATAC_PBMC_R1.arrow" "scATAC_BMMC_R1.arrow"

I think this is maybe due to environment for using ArchR.Do you know how to solve this?

**Comment by rcorces** [comment]
ArchR is not working on 4.1.1 right now. Use an earlier version of R (4.1.0 or earlier) until we figure out why.
https://github.com/GreenleafLab/ArchR/discussions/1044
