### ISSUE TITLE
ArchR Browser No Longer Working

### ISSUE THREAD

**Issue by agalianese** [GreenleafLab/ArchR#1052]
When I try to use 

```
ArchRBrowser(project)
```

it will load the browser, but when I click Plot gene, i get Error: argument is of length zero, no matter what gene I use. This occurs with grouping by cluster and sample. When going into the code, it seems that there was an issue with the formatting of region, as when I tried to run

```
region <- geneAnnotation$genes
region <- region[which(tolower(mcols(region)$symbol) %in% tolower(geneSymbol))]
region <- region[order(match(tolower(mcols(region)$symbol), tolower(geneSymbol)))]
print(region)
region <- resize(region, 1, "start")
strand(region) <- "*"
region <- .validGRanges(region)

print(region)
GRanges object with 1 range and 2 metadata columns:
      seqnames    ranges strand |     gene_id      symbol
         <Rle> <IRanges>  <Rle> | <character> <character>
  [1]     chr1   4409241      * |       19888         Rp1
  -------
  seqinfo: 21 sequences from mm10 genome

.scTracks(project, region) 
```

I get that the error that the data must be data frame, or other object coercible by `fortify()`, not a list. I then run 

```
.scTracks(project, data.frame(region))
```
Which gives the error incorrect time series parameters supplied.

I have previously used the ArchRBrowser with the same project, but lately I have the argument of length 0 error whenever I try to run it. Please let me know if there's anything I'm missing. Thanks!

**Comment by rcorces** [comment]
To the best of my knowledge, there have not been any code changes to any code related to the ArchRBrowser in a very long time. Which means that this is unlikely a bug in ArchR but rather a problem with your object. I'm not really sure I have any insight into the example you provide. perhaps you can provide a `traceback()` of the error.

**Comment by agalianese** [comment]
There's no traceback for the actual browser, but the .scTracks one is below

```> traceback()
6: hasTsp(x)
5: start.default(region)
4: start(region)
3: start(region)
2: seq(trunc(start(region)/tileSize), trunc(end(region)/tileSize) + 
       1)
1: .scTracks(GFPpos, data.frame(region))
```

**Comment by rcorces** [comment]
I dont have additional insight to this yet but I've heard of 1 other user having the same error which makes me think that its a package version issue with another package.

**Comment by rcorces** [comment]
@agalianese - are you still having this issue with the ArchRBrowser? Any idea if this is specific to a single project or perhaps to the environment? Are you able to recapitulate this with the tutorial data and code?

**Comment by JING202** [comment]
@rcorces I met the same problem. Do you have any idea to solve this issue?

**Comment by rcorces** [comment]
@JING202 - Please document what you have done, your error message, a log file, and whether you are able to recapitulate this error using the tutorial dataset. If so, please provide a reproducible example. I do not currently have any intuition as to what might be going wrong and will need much more information.

**Comment by JING202** [comment]
@rcorces Thanks for your quick response. 
When I tried,
ArchRBrowser(proj2)
In the browser window, I tried to check gene tracks. Then it showed error as below, "Warning: Error in if: argument is of length zero".  The log file was attached.
I tried to run "ArchRBrowser(proj2)" again, and got the same error. But if I firstly clicked on "Additional Params" to made some changes, and then clicked on "Plot Track", it worked. I don't know why.

[ArchR-ArchRBrowser-8f993c61aca7-Date-2021-11-23_Time-23-05-15.log](https://github.com/GreenleafLab/ArchR/files/7593466/ArchR-ArchRBrowser-8f993c61aca7-Date-2021-11-23_Time-23-05-15.log)

**Comment by artgolden** [comment]
I can confirm the behavior that JING202 has described.

**Comment by agalianese** [comment]
Hello, I have moved projects so I'm no longer using ArchR so I can't offer any help.

**Comment by rcorces** [comment]
@artgolden - Can you confirm that this happens on the tutorial dataset? And are you confirming the ability to get around this with the workaround that @JING202 suggested? I'm not able to recapitulate this behavior and it is likely some package incompatibility. We're working on a way to ensure this package incompatibility doesnt happen in the future.

**Comment by artgolden** [comment]
@rcorces Yes I did my first install of ArchR today, and I am using tutorial dataset. Yes, the workaround with clicking on "Additional Params" works.

**Comment by artgolden** [comment]
@rcorces  I have to add that I have additional problems with ArchR Browser of my own. I am going to file a proper issue, but I think I should also mention here.

With a clear run of tutorial code (just redid it) when running `ArchRBrowser(ArchRProj = proj) `  everything seems to run normally, but when I attempt to generate a plot, all tracks appear to be straight lines (attaching a screenshot).
![image](https://user-images.githubusercontent.com/3861476/144131970-1d2c2381-386e-437a-b9f0-0cfa54471dfa.png)
 

When running 
```
p <- plotBrowserTrack(
    ArchRProj = proj,
    groupBy = "Clusters",
    geneSymbol = "CD14",
    upstream = 50000,
    downstream = 50000
)
```
everything is fine and I get a plot same as in your tutorial.
![image](https://user-images.githubusercontent.com/3861476/144132230-e665ba85-d725-4a3c-af1a-17280e81b602.png)

I will try creating a clean anaconda repo and test there. If it does not help, I will file an issue with all possible log files.

Thanks a lot for help and quick responses!

**Comment by paupaiz** [comment]
> @rcorces Thanks for your quick response. When I tried, ArchRBrowser(proj2) In the browser window, I tried to check gene tracks. Then it showed error as below, "Warning: Error in if: argument is of length zero". The log file was attached. I tried to run "ArchRBrowser(proj2)" again, and got the same error. But if I firstly clicked on "Additional Params" to made some changes, and then clicked on "Plot Track", it worked. I don't know why.
> 
> [ArchR-ArchRBrowser-8f993c61aca7-Date-2021-11-23_Time-23-05-15.log](https://github.com/GreenleafLab/ArchR/files/7593466/ArchR-ArchRBrowser-8f993c61aca7-Date-2021-11-23_Time-23-05-15.log)

can confirm this works as well!

**Comment by kevinrue** [comment]
Just ran into this again today.

@paupaiz 's explanation is definitely worth an upvote as many users won't know that shiny doesn't run bits of code until the corresponding UI element needs to be displayed. As a result navigating to the "Additional Params" tab is required to create an object that is necessary for plot tracks.

I just had a brief look at the code, and the fix isn't as straightforward as I would have hoped, because it requires the output$Metadata to be created so that it can then be reused as as input:

https://github.com/GreenleafLab/ArchR/blob/master/R/ArchRBrowser.R#L337

The typical solution would be to create a reactiveValue that computes and stores the metadata, and then point to that reactive values from both the "Additional params" tab and the "Plot Tracks" UI elements, so that the shared metadata gets computed by whoever needs it first.
