### ISSUE TITLE
Change rownames of getTrajectory output

### ISSUE THREAD

**Issue by jpblich** [GreenleafLab/ArchR#1058]
Hi,

I would like to run correlateTrajectories on a peak trajectory matrix and a gene expression trajectory matrix, to correlate peak trajectories with trajectories of genes that they are linked to (identified by the addPeak2GeneLinks function).

correlateTrajectories requires names to be matched, so I want to replace the peak coordinates in the peak trajectory matrix with the names of genes that they are linked to. 

I obtain the peak trajectory matrix (trajPM)

trajPM  <- getTrajectory(ArchRProj = Multiproj, name = "Trajectory_1", useMatrix = "PeakMatrix", log2Norm = TRUE)

Peak to gene links (Peak_coordinates and corresponding Linked_genes) are stored in the dataframe p2g

First, I subset the peak trajectory matrix to only peaks that have linked genes:
nrow(trajPM) #246543 peaks
trajPM <- subset(trajPM, rownames(trajPM[, 1]) %in% p2g$Peak_coordinates)
nrow(trajPM) #1100 peaks

I then try to replace peak coordinates in the peak trajectory matrix with the corresponding linked gene names. From reading about the organisation of SummarizedExperiment objects, peak coordinates seem to be stored in both:
rownames(assays(trajPM)[1]$smoothMat)
rownames(rowData(trajPM)[1])

However, neither of these work when I try to change the rownames.
rownames(assays(trajPM, withDimnames=FALSE)[1]$smoothMat) <- p2g$Linked_genes
rownames(rowData(trajPM)[1]) <- p2g$Linked_genes

I've looked online a lot and am really struggling with this. Is it possible to change the rownames of a trajectory matrix? I'm new to bioinformatics, would be extremely grateful for any help here.
Many thanks,
J

**Comment by rcorces** [comment]
Sorry for the delayed reply. A few things to note:
1) Usage questions should be reported to Discussions. Only bugs and errors should be reported under Issues.
2) If you are going to report an Issue, please use the provided Issue Template

To answer your question, if you look at the code in `correlateTrajectories()` you'll see that what is actually being matched is the `name` column of the trajectory SummarizedExperiments. So the value that you need to change is actually in `rowData(traj_se)$name`
for example here:
https://github.com/GreenleafLab/ArchR/blob/968e4421ce7187a8ac7ea1cf6077412126876d5f/R/IntegrativeAnalysis.R#L5545

```
projHeme5 <- addPeak2GeneLinks(
  ArchRProj = projHeme5,
  reducedDims = "IterativeLSI"
)

trajectory <- c("Progenitor", "GMP", "Mono")

projHeme5 <- addTrajectory(
  ArchRProj = projHeme5, 
  name = "MyeloidU", 
  groupBy = "Clusters2",
  trajectory = trajectory, 
  embedding = "UMAP", 
  force = TRUE
)

traj_se <- getTrajectory(ArchRProj = projHeme5, name = "MyeloidU")

> traj_se
class: SummarizedExperiment 
dim: 23127 100 
metadata(1): Params
assays(2): smoothMat mat
rownames(23127): chr1:DDX11L1 chr1:WASH7P ... chrX:CLIC2 chrX:TMLHE
rowData names(6): seqnames start ... name idx
colnames(100): T.0_1 T.1_2 ... T.98_99 T.99_100
colData names(0):
> rowData(traj_se)
DataFrame with 23127 rows and 6 columns
                  seqnames     start       end  strand         name     idx
                     <Rle>   <array>   <array> <array>      <array> <array>
chr1:DDX11L1          chr1     11874     14409       1      DDX11L1       1
chr1:WASH7P           chr1     29961     14362       2       WASH7P       2
chr1:OR4F5            chr1     69091     70008       1        OR4F5       3
chr1:LOC729737        chr1    140566    134773       2    LOC729737       4
chr1:LOC100288069     chr1    714068    700245       2 LOC100288069       5
...                    ...       ...       ...     ...          ...     ...
chrX:BRCC3            chrX 154299695 154351349       1        BRCC3     906
chrX:VBP1             chrX 154444701 154468098       1         VBP1     907
chrX:RAB39B           chrX 154493852 154487526       2       RAB39B     908
chrX:CLIC2            chrX 154563986 154505500       2        CLIC2     909
chrX:TMLHE            chrX 154842622 154718673       2        TMLHE     910
```

**Comment by jpblich** [comment]
Brilliant it works, thank you!
