### ISSUE TITLE
disable plotting option in addReproduciblePeakSet

### ISSUE THREAD

**Issue by badoi** [GreenleafLab/ArchR#107]
`addReproduciblePeakSet` takes a while to run (which isn't the issue), and the last step is a nice plot! X11 forwarding is currently disabled on my cluster and the step fails because default is to plot to available device. It would be nice to either disable plotting, or provide `pdf` file name to have the plot be sent to. Currently, I pre-empt the failure for me by starting a pdf() device that does what I suggest. Warning that a plot would be made w/ the function call could also be good.

**Comment by jgranja24** [comment]
ok we can add a param like `plot = TRUE/FALSE`

**Comment by jgranja24** [comment]
This has now been committed to the dev branch which will be updated to master shortly.

**Comment by jgranja24** [comment]
This is now functional in the new master update. Closing this issue feel free to reopen if further issues.
