### ISSUE TITLE
documentation for making Arrows from Bamfiles for non-10x experiments.

### ISSUE THREAD

**Issue by badoi** [GreenleafLab/ArchR#108]
**Where is the problematic documentation?**
The explanation for loading in bamFiles from combinatorial indexing-type snATAC-seq files (e.g. sc-THS-seq from Preissl et al 2018, Lake et al 2017). 

1) Improvements can be to have sensible defaults for `bamFlag` parameter or examples like the `gsubExpression`. 
2) Clarifying that the `gsubExpression` is to remove non-barcode strings from the `bcTag`, rather than current documentation. 
3) You should create a new section in the user manual in Chapter 1 to walk through loading in bamFiles. Clarification on what kinds of preprocessing is required for the bamFile, e.g. does it need to be pre-filtered, PCR duplicate marked, etc. Sets of parameters for different styles of snATAC-seq out there (sci-ATAC-seq, scTHS-seq, etc).

**Comment by rcorces** [comment]
Thanks for the suggestion. We will add this in an upcoming release of the website. I will update and close this issue when that is live.

**Comment by rcorces** [comment]
I'm going to close this now to help tidy up issues. This will go into the next update but is not there yet.
