### ISSUE TITLE
manual chapter for projectBulkATAC functionality

### ISSUE THREAD

**Issue by badoi** [GreenleafLab/ArchR#109]
You should create a new section in the user manual in Chapter 15, integrative analysis to demonstrate the `projectBulkATAC()` function, underlying idea, and how this is a super awesome connection to available bulk data. Currently, I'm only able to gleam bits of what `projectBulkATAC()` does from the function manual page and pieces of the preprint. Looking forward to see this chapter/section. 

Awesome, thorough manual otherwise. 

-BaDoi

**Comment by rcorces** [comment]
Thanks for the suggestion. We will add this in an upcoming release of the website. I will update and close this issue when that is live.

**Comment by rcorces** [comment]
This will go into the next documentation update. Closing for now to help tidy up issues.
