### ISSUE TITLE
normalization of gene activity

### ISSUE THREAD

**Issue by Brawni** [GreenleafLab/ArchR#110]
Hi there,

Thanks again to provide such a great package to the community.
Is it possible to apply some kind of normalization to gene activity? I noticed that the function addGeneScoreMatrix() does not include a normalization argument. There is the argument of log2 normalizing in the plotEmbedding but i was looking to normalize based on read depth or TSS enirchment.

Thanks!

**Comment by jgranja24** [comment]
Hi thanks your using ArchR.

Gene Scores are automatically depth normalized ( see by default `scaleTo = 10000` ) prior to being stored in the Arrow File. 

Closing this issue and best of luck on your analysis!

**Comment by rcorces** [comment]
I have added this to the user manual for clarity.

> Gene scores are calculated for each Arrow file at the time of creation if the parameter `addGeneScoreMat` is set to `TRUE` - this is the default behavior. If you wish to change any of the default parameters for gene score calculation during Arrow file creation, you can use the `GeneScoreMatParams` parameter. By default, gene scores are depth normalized based on the `scaleTo` parameter. If you do not wish to add gene scores to your Arrow file at the time of creation, gene scores can be added to Arrow files at any time by using the `addGeneScoreMatrix()` function.

**Comment by Brawni** [comment]
I see, so scaleTo will do the job, sorry I missed that. However i see some inconsistencies between track plots and gene activity plots. For example the peak coverage for EPCAM for cluster 17 seems lower compared to others whereas its gene activity is one of the highest. I guess these two plots are difficult to compare but i wondered if this still looks ok to you.
![image](https://user-images.githubusercontent.com/58828216/81221810-510cd400-8fb1-11ea-9a24-a82241d78faf.png)
![image](https://user-images.githubusercontent.com/58828216/81221959-903b2500-8fb1-11ea-8d80-e304a97b838a.png)
![image](https://user-images.githubusercontent.com/58828216/81222014-a3e68b80-8fb1-11ea-8348-83cc2f9e3963.png)
