### ISSUE TITLE
nearstTSS in peakSet map to another chromosome

### ISSUE THREAD

**Issue by Zepeng-Mu** [GreenleafLab/ArchR#1122]
Hi, I'm using ArchR installed from v_1.0.2 branch. I noticed that the `nearestTSS` column in peakSet gives me something strange.

```
chr1_776608-777108     chr1       776608-777108      * |   6.02925                  0.284              0.095               3     C18._.PBMC-5-6-7-8           13869 RP11-206L10.11      Exonic     13869         BCL9L    0.5449         4         0
chr1_779802-780302     chr1       779802-780302      * |  34.05750                  0.710              0.544               3           C18._.RA-7-8           17063 RP11-206L10.11    Intronic     17063         BCL9L    0.5110         5         0
```
For instance, here are two peaks on chromosome 1 but the annotation of nearestTSS is to gene BCL9L, which is the chromosome 11. The nearestGene column appear to be right I think. This is just the output from `getPeakSet()`
Also previously,  nearestTSS contains something like "uc001obu.1", I think it's nicer now that it contains actual gene symbol.

Could this be due to usage of my own gene annotation for ArchR, but I don't think that's the problem.

Thanks!

**Comment by Zepeng-Mu** [comment]
Actually, maybe the problem is here:

https://github.com/GreenleafLab/ArchR/blob/b2f3d95171ea1d708ae1e39a980669091d02689f/R/ReproduciblePeakSet.R#L625-L632

`symbol[subjectHits(distPeaks)] ` should be `symbol[subjectHits(distTSS)] `?
Not sure when this is introduced though.

**Comment by rcorces** [comment]
Thanks for digging into this. This does look like a bug to me. 
I've made the suggested change in a new branch called `dev_distTSS` which branches off of `release_1.0.2`. If you have time, it would be great if you could test this branch to make sure it works as expected.

```
devtools::install_github("GreenleafLab/ArchR", ref="dev_distTSS", repos = BiocManager::repositories())
```

**Comment by Zepeng-Mu** [comment]
Yes, it works as expected now. Thanks so much!

**Comment by rcorces** [comment]
awesome. thanks for checking so quickly. I've now merged this into `release_1.0.2` via https://github.com/GreenleafLab/ArchR/pull/1141
