### ISSUE TITLE
Enrichment of peak to gene link in GWAS summary statistics and eQTLs

### ISSUE THREAD

**Issue by CSBioAzim** [GreenleafLab/ArchR#114]
I think it would be very useful to add a function to compute the enrichment of peak to gene links in GWAS summary statistics and eQTL data.

Thanks

**Comment by rcorces** [comment]
That is a relatively complex enrichment analysis to perform and we arent exactly GWAS/eQTL experts. ArchR enables custom enrichments using the hypergeometric test but I don't belive that this would be the recommended statistical test for the proposed analysis.
https://www.archrproject.com/bookdown/custom-enrichment.html

If you describe your use case in detail using the issue template, that will provide us with more information and allow us to make a more informed decision about whether to pursue your feature request.

**Comment by jgranja24** [comment]
This is a bit beyond the current scope of what we can support at the moment. Standardizing and bulletproofing an analysis like this is pretty complicated and in itself is a large challenge. One could argue a full package could be developed to handle this analysis. Im going to close this issue but we will keep it in mind for future development.
