### ISSUE TITLE
stri_split_regex error in createArrowFile or hmm...my custom genome is broken

### ISSUE THREAD

**Issue by dagarfield** [GreenleafLab/ArchR#1145]
I'm trying to create an Arrow file after doing some additional sequencing on a dataset and running during the creation of the arrow file (and after the creation of the temporary arrow file)

```
2021-11-08 06:34:10 : (earlyDev : 1 of 1) Adding Chromosome 245 of 246, 46.704 mins elapsed.

************************************************************
2021-11-08 06:34:11 : ERROR Found in .tmpToArrow for (earlyDev : 1 of 1) 
LogFile = ArchRLogs/ArchR-createArrows-7d8f3946c7a1-Date-2021-11-08_Time-05-47-28.log

<simpleError in stri_split_regex(string, pattern, n = n, simplify = simplify,     opts_regex = opts(pattern)): trying to get slot "values" from an object of a basic class ("character") with no slots>
```

Any ideas? The log file is attached. 

[ArchR-createArrows-7d8f3946c7a1-Date-2021-11-08_Time-05-47-28.log](https://github.com/GreenleafLab/ArchR/files/7494553/ArchR-createArrows-7d8f3946c7a1-Date-2021-11-08_Time-05-47-28.log)

By the way, on the off chance that this error was somehow self-inflicted while modifying the code for my weird custom genome, I installed the most recent version (from master), and now it appears that the custom genome option does not work at all. 

The previously working custom genome

```
> geneAnnoSpur5
List of length 3
names(3): genes exons TSS
```
and
```
> genomeAnnoSpur5
List of length 3
names(3): genome chromSizes blacklist
```

We then run the following (exactly as before)

```
ArrowFiles <- createArrowFiles(
    geneAnnotation = geneAnnoSpur5, 
    genomeAnnotation = genomeAnnoSpur5,
    inputFiles = inputFiles,
    sampleNames = names(filePaths),
    validBarcodes = validBarcodes,
    minTSS = minTSS, 
    minFrags = minFrags, 
    maxFrags = maxFrags,
    promoterRegion = promoterRegion,
    excludeChr = excludeChr,
    addTileMat = addTileMat,
    TileMatParams = TileMatParams,
    addGeneScoreMat = addGeneScoreMat,
    GeneScoreMatParams = GeneScoreMatParams,
    subThreading = FALSE #still not sure about this one
)
```

And then the sad trombone of a failed command:

```
Error in .getBSgenomeObjectFromInstalledPkgname(genome, load.only = load.only): Package BSgenome.Spurp.NCBI.Spur5 is not available.
  Please see the BSgenomeForge vignette in the BSgenome software package
  for how to forge a BSgenome data package for your organism of interest.
Traceback:

1. createArrowFiles(geneAnnotation = geneAnnoSpur5, genomeAnnotation = genomeAnnoSpur5, 
 .     inputFiles = inputFiles, sampleNames = names(filePaths), 
 .     validBarcodes = validBarcodes, minTSS = minTSS, minFrags = minFrags, 
 .     maxFrags = maxFrags, promoterRegion = promoterRegion, excludeChr = excludeChr, 
 .     addTileMat = addTileMat, TileMatParams = TileMatParams, addGeneScoreMat = addGeneScoreMat, 
 .     GeneScoreMatParams = GeneScoreMatParams, subThreading = FALSE)
2. .validGenomeAnnotation(genomeAnnotation)
3. validBSgenome(genomeAnnotation[[grep("genome", names(genomeAnnotation), 
 .     ignore.case = TRUE)]])
4. tryCatch({
 .     .requirePackage(genome)
 .     bsg <- eval(parse(text = genome))
 .     if (inherits(bsg, "BSgenome")) {
 .         return(bsg)
 .     }
 .     else {
 .         stop("genome is not a BSgenome valid class!")
 .     }
 . }, error = function(x) {
 .     BSgenome::getBSgenome(genome, masked = masked)
 . })
5. tryCatchList(expr, classes, parentenv, handlers)
6. tryCatchOne(expr, names, parentenv, handlers[[1L]])
7. value[[3L]](cond)
8. BSgenome::getBSgenome(genome, masked = masked)
9. .getBSgenomeObjectFromInstalledPkgname(genome, load.only = load.only)
10. stop(c("Package ", genome, " is not available.\n  ", wmsg("Please see the BSgenomeForge vignette in the BSgenome ", 
  .     "software package for how to forge a BSgenome data ", "package for your organism of interest.")))

```

Has something changed in the most recent version?

**Comment by dagarfield** [comment]
Oh, and this is already included in the script
```
options(ArchR.genome = "Spur5") 
addArchRChrPrefix(chrPrefix = FALSE)
```

**Comment by rcorces** [comment]
can you try this on `release_1.0.2` and let me know if you still have problems?

```devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.2", repos = BiocManager::repositories())```

**Comment by dagarfield** [comment]
Same error, alas. Here's the error again and the sessionInfo in case something stands out. Maybe something with the BSGenome version?

The error:
```
Error in .getBSgenomeObjectFromInstalledPkgname(genome, load.only = load.only): Package BSgenome.Spurp.NCBI.Spur5 is not available.
  Please see the BSgenomeForge vignette in the BSgenome software package
  for how to forge a BSgenome data package for your organism of interest.
Traceback:

1. createArrowFiles(geneAnnotation = geneAnnoSpur5, genomeAnnotation = genomeAnnoSpur5, 
 .     inputFiles = inputFiles[1], sampleNames = names(filePaths)[1], 
 .     validBarcodes = barcodes, minTSS = minTSS, minFrags = minFrags, 
 .     maxFrags = maxFrags, promoterRegion = promoterRegion, excludeChr = excludeChr, 
 .     addTileMat = addTileMat, TileMatParams = TileMatParams, addGeneScoreMat = addGeneScoreMat, 
 .     GeneScoreMatParams = GeneScoreMatParams, subThreading = FALSE)
2. .validGenomeAnnotation(genomeAnnotation)
3. validBSgenome(genomeAnnotation[[grep("genome", names(genomeAnnotation), 
 .     ignore.case = TRUE)]])
4. tryCatch({
 .     .requirePackage(genome)
 .     bsg <- eval(parse(text = genome))
 .     if (inherits(bsg, "BSgenome")) {
 .         return(bsg)
 .     }
 .     else {
 .         stop("genome is not a BSgenome valid class!")
 .     }
 . }, error = function(x) {
 .     BSgenome::getBSgenome(genome, masked = masked)
 . })
5. tryCatchList(expr, classes, parentenv, handlers)
6. tryCatchOne(expr, names, parentenv, handlers[[1L]])
7. value[[3L]](cond)
8. BSgenome::getBSgenome(genome, masked = masked)
9. .getBSgenomeObjectFromInstalledPkgname(genome, load.only = load.only)
10. stop(c("Package ", genome, " is not available.\n  ", wmsg("Please see the BSgenomeForge vignette in the BSgenome ", 
  .     "software package for how to forge a BSgenome data ", "package for your organism of interest.")))
```

Session Info:

```
R version 4.1.1 (2021-08-10)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /fast/work/users/dgarfie_m/miniconda3/envs/ArchR_2/lib/libopenblasp-r0.3.18.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
 [1] dplyr_1.0.7                 ArchR_1.0.2                
 [3] magrittr_2.0.1              rhdf5_2.38.0               
 [5] Matrix_1.3-4                data.table_1.14.2          
 [7] SummarizedExperiment_1.24.0 Biobase_2.54.0             
 [9] GenomicRanges_1.46.0        GenomeInfoDb_1.30.0        
[11] IRanges_2.28.0              S4Vectors_0.32.1           
[13] BiocGenerics_0.40.0         MatrixGenerics_1.6.0       
[15] matrixStats_0.61.0          ggplot2_3.3.5              

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.7               lattice_0.20-45          Rsamtools_2.10.0        
 [4] Biostrings_2.62.0        digest_0.6.28            utf8_1.2.2              
 [7] IRdisplay_1.0            R6_2.5.1                 repr_1.1.3              
[10] evaluate_0.14            pillar_1.6.4             zlibbioc_1.40.0         
[13] rlang_0.4.12             uuid_1.0-3               BiocParallel_1.28.0     
[16] readr_2.0.2              RCurl_1.98-1.5           bit_4.0.4               
[19] munsell_0.5.0            DelayedArray_0.20.0      rtracklayer_1.54.0      
[22] compiler_4.1.1           pkgconfig_2.0.3          base64enc_0.1-3         
[25] htmltools_0.5.2          tidyselect_1.1.1         tibble_3.1.6            
[28] GenomeInfoDbData_1.2.7   XML_3.99-0.8             fansi_0.5.0             
[31] crayon_1.4.2             tzdb_0.2.0               withr_2.4.2             
[34] GenomicAlignments_1.30.0 rhdf5filters_1.6.0       bitops_1.0-7            
[37] grid_4.1.1               jsonlite_1.7.2           gtable_0.3.0            
[40] lifecycle_1.0.1          scales_1.1.1             cli_3.1.0               
[43] vroom_1.5.5              XVector_0.34.0           ellipsis_0.3.2          
[46] generics_0.1.1           vctrs_0.3.8              IRkernel_1.2            
[49] rjson_0.2.20             restfulr_0.0.13          Rhdf5lib_1.16.0         
[52] tools_4.1.1              bit64_4.0.5              BSgenome_1.62.0         
[55] glue_1.5.0               purrr_0.3.4              hms_1.1.1               
[58] yaml_2.2.1               parallel_4.1.1           fastmap_1.1.0           
[61] colorspace_2.0-2         BiocManager_1.30.16      pbdZMQ_0.3-6            
[64] BiocIO_1.4.0            
```

**Comment by dagarfield** [comment]
Happy to upload/share the custom genome files if that helps.

**Comment by dagarfield** [comment]
Oyy... I think I forgot to reinstall my custom genome in the new R instance (conda...). 
Put the custom genome error on ice for the moment (though the first problem is still relevant)

**Comment by dagarfield** [comment]
And indeed, the second issue was solved with a proper installation of the custom BSGenome. But with that fixed, we're back to a similar, though not identical, error:

```
<simpleError in validObject(r): invalid class “dgTMatrix” object: lengths of slots i and j must match>
```

Error log attached:
[ArchR-createArrows-63401ce7ebd0-Date-2021-11-09_Time-00-01-47.log](https://github.com/GreenleafLab/ArchR/files/7501163/ArchR-createArrows-63401ce7ebd0-Date-2021-11-09_Time-00-01-47.log)

This feels a bit similar to [this issue](https://github.com/GreenleafLab/ArchR/issues/1014), but I'm puzzled as this same reference genome seems to have worked quite fine before. Suggestions on things I could check?

**Comment by rcorces** [comment]
Could this just be the same problems you had previously that we never addressed?
https://github.com/GreenleafLab/ArchR/issues/538#issuecomment-791285649

**Comment by dagarfield** [comment]
You know, it really might be. What's confusing to me is why it is that my earlier scripts/ArchR install isn't creating the project this time. (The previous issue seems to have involved the gene score matrix, while failure this round seems to be happening at the tile matrix generation step). Looking back, it looks like I made my first arrow files with Version 1.0, and now my versions are a copy of 1.01 (with modified code in places) and 1.02 (clean and fresh), so possibly something changed there? 

Lemme play around a bit with the genomeAnnotation objects today. I'll update this ticket as I go. Current plan is to repopulate the genomeAnnotation with all possible scaffolds and then do the trimming to gene-free and/or short scaffolds specifically in the transcript annotations and/or the exclude chromosome options.

**Comment by rcorces** [comment]
If it is different frag files this time, it could also be that (by chance) you have fragments that are extending past the ends of scaffolds in the new data and you didnt have this in the previous data.

**Comment by dagarfield** [comment]
I do have one of the original fragment files and it is throwing the same
error, but agree with the potential issue in general.

**Comment by dagarfield** [comment]
Alright, here's what we have. I did a little experiment using ArchR 1.0.2 and a fragment file that worked in the past (ArchR 1.0, a version I no longer have, alas).

1) If you try to create an ArchR file with all scaffolds (including Scaffolds with no genes on it), you get the previously reported error of `Chromosome NA not in ArrowFile!`. Solution is pretty simple -- remove the gene-free scaffolds from *both* your genome and gene annotations. 

2) If I try to construct an arrow file with just the 21 largest scaffolds (the ones that almost look like proper chromosome assemblies), we just sail through. Alas, many interesting genes reside on the smaller scaffolds, so it would be good to include them as I was apparently able to do before. 

3) If I try to construct ArchR projects with all scaffolds that contain genes, I get something that looks suspiciously like out of bounds errors for the creation of the Tile Matrix (the final arrow file actually briefly exists): 

```
Warning message in doTryCatch(return(expr), name, parentenv, handler):
“Skipping over fragments not within chromosome range on Chr:NW_022145570.1”
[1] "Bad1 (Start not greater than 0): "
IRanges object with 0 ranges and 1 metadata column:
       start       end     width |    RG
   <integer> <integer> <integer> | <Rle>
[1] "Bad2 (End greater than chromsome length): "
IRanges object with 3 ranges and 1 metadata column:
          start       end     width |                     RG
      <integer> <integer> <integer> |                  <Rle>
  [1]   4944448   4944709       262 | earlyDev#TGAGTCAAGTC..
  [2]   4944552   4944709       158 | earlyDev#CGGACCATCCT..
  [3]   4944570   4944709       140 | earlyDev#CAGTGTAAGGC..

************************************************************
2021-11-10 21:36:16 : ERROR Found in .addTileMat for earlyDev 
LogFile = ArchRLogs/ArchR-createArrows-69161df7fe84-Date-2021-11-10_Time-20-34-44.log

<simpleError in validObject(r): invalid class “dgTMatrix” object: lengths of slots i and j must match>

************************************************************


************************************************************
2021-11-10 21:36:16 : ERROR Found in .addTileMat for (earlyDev : 1 of 1) 
LogFile = ArchRLogs/ArchR-createArrows-69161df7fe84-Date-2021-11-10_Time-20-34-44.log

<simpleError in .logError(e, fn = ".addTileMat", info = sampleName, errorList = errorList,     logFile = logFile): Exiting See Error Above>

************************************************************
```

And this log file
[ArchR-createArrows-69161df7fe84-Date-2021-11-10_Time-20-34-44.log](https://github.com/GreenleafLab/ArchR/files/7521412/ArchR-createArrows-69161df7fe84-Date-2021-11-10_Time-20-34-44.log)

I've double checked that the genome reference and that used to construct the genome used by ArchR are the same (the lengths of my annotations match that seen in the BAM header). 

Any suggestions? If you can give me a tip on where to walk through the code (e.g. tile matrix creation), I'd be most grateful. I get the same error on other fragment files, and it seems to be this "Bad2" error. e.g. 

```
2021-11-10 23:52:48 : MaxCell_TileMatrix_12_NW_022145610.1, Class = integer

MaxCell_TileMatrix_12_NW_022145610.1: length = 1
[1] 10761



2021-11-10 23:52:49 : fragmentsBad1, Class = IRanges

fragmentsBad1: length = 0
IRanges object with 0 ranges and 1 metadata column:
       start       end     width |    RG
   <integer> <integer> <integer> | <Rle>



2021-11-10 23:52:49 : fragmentsBad2, Class = IRanges

fragmentsBad2: length = 1
IRanges object with 1 range and 1 metadata column:
          start       end     width |                     RG
      <integer> <integer> <integer> |                  <Rle>
  [1]  35917675  35917773        99 | 24hr#GGGTGTCAGAAGGGC..



************************************************************
2021-11-10 23:52:49 : ERROR Found in .addTileMat for 24hr 
LogFile = ArchRLogs/ArchR-createArrows-6e8d72b0ebe0-Date-2021-11-10_Time-22-54-36.log

<simpleError in validObject(r): invalid class “dgTMatrix” object: lengths of slots i and j must match>

Somehow the fragments runneth over?

```

**Comment by dagarfield** [comment]
Some additional context -- the first scaffold that throws errors is the first of the smaller scaffolds (basically those that didn't fit neatly into a chromosome). From the 10x BAM file:

```
@SQ	SN:NW_022145596.1	LN:33320444
@SQ	SN:NW_022145602.1	LN:30021120
@SQ	SN:NW_022145595.1	LN:29984350
@SQ	SN:NW_022145570.1	LN:4944709 ###[This guy is causing problems]
@SQ	SN:NW_022145575.1	LN:3300603
@SQ	SN:NW_022145566.1	LN:3042594
```

That first of the smaller guys is our issue (though curiously it seems to start with a warning):

```
Warning message in doTryCatch(return(expr), name, parentenv, handler):
“Skipping over fragments not within chromosome range on Chr:NW_022145570.1”
[1] "Bad1 (Start not greater than 0): "
IRanges object with 0 ranges and 1 metadata column:
       start       end     width |    RG
   <integer> <integer> <integer> | <Rle>
[1] "Bad2 (End greater than chromsome length): "
IRanges object with 3 ranges and 1 metadata column:
          start       end     width |                     RG
      <integer> <integer> <integer> |                  <Rle>
  [1]   4944448   4944709       262 | earlyDev#TGAGTCAAGTC..
  [2]   4944552   4944709       158 | earlyDev#CGGACCATCCT..
  [3]   4944570   4944709       140 | earlyDev#CAGTGTAAGGC..

************************************************************
2021-11-14 17:56:56 : ERROR Found in .addTileMat for earlyDev 
LogFile = ArchRLogs/ArchR-addTileMatrix-2ac23b1cef95-Date-2021-11-14_Time-17-55-06.log

<simpleError in validObject(r): invalid class “dgTMatrix” object: lengths of slots i and j must match>
```

Those fragments are indeed bumping into the end of the scaffold, but there doesn't seem to be any mismatch between the scaffold as seen by ArchR and the genome file uses for alignment (as reflected by the BAM file header snippet posted above). 

Here's our troublesome friend:

```
> genomeAnnoSpur5[["chromSizes"]][seqnames(genomeAnnoSpur5[["chromSizes"]]) == "NW_022145570.1",]
GRanges object with 1 range and 0 metadata columns:
            seqnames    ranges strand
               <Rle> <IRanges>  <Rle>
  [1] NW_022145570.1 1-4944709      *
  -------
  seqinfo: 246 sequences (1 circular) from an unspecified genome; no seqlengths

> library(BSgenome.Spurp.NCBI.Spur5)
> BSgenome.Spurp.NCBI.Spur5[["NW_022145570.1"]]
4944709-letter DNAString object
seq: AAATACATAAATCAATAAATAAATACATTACATAGA...CTCCCCCCCCCCCCCCACCCCCACTTTTCGTTTAAT
```

And a well behaved one:

```
> genomeAnnoSpur5[["chromSizes"]][seqnames(genomeAnnoSpur5[["chromSizes"]]) == "NW_022145595.1",]
GRanges object with 1 range and 0 metadata columns:
            seqnames     ranges strand
               <Rle>  <IRanges>  <Rle>
  [1] NW_022145595.1 1-29984350      *
  -------
  seqinfo: 246 sequences (1 circular) from an unspecified genome; no seqlengths

> BSgenome.Spurp.NCBI.Spur5[["NW_022145595.1"]]
29984350-letter DNAString object
seq: AATAACGGACGATACCATTATTTTTTAGGGGTGTTT...GGCTGCCGAGGAAGGGACGCGAGCCCGCGCCCGCCT
```

One possibility is that I'm not properly translating the size of the scaffolds/chromosomes into BSGenome entries or genomeAnnotation for the custom genome or there's some non-ideal indexing incompatibility here (Are things 0-indexed in ArchR)? Either way, insight would be appreciated.

**Comment by rcorces** [comment]
A few comments for now while I try to look into this.

1. You can install old versions of ArchR (starting with 1.0.0) using their release tags. https://github.com/GreenleafLab/ArchR/releases
`devtools::install_github("GreenleafLab/ArchR", ref="v1.0.0", repos = BiocManager::repositories())`

2. ArchR uses `GRanges` which are always 1-based. That being said, 0/1 based only affects the start of the fragment.

Your error is here:
https://github.com/GreenleafLab/ArchR/blob/4800d9ff7ecd6bc65364027d8cebfefe6510777d/R/MatrixTiles.R#L215

Its possible that this is a bug in ArchR. I think this expression should probably be `<=` instead of `<`.

I've made this change via https://github.com/GreenleafLab/ArchR/commit/9997f87c0b449224738e9f3245507424ce4f1887 in a new branch `dev_chrEnds` off of `release_1.0.2`. Can you test this? I dont think that changing this will have downstream consequences but would be good to hear from you once you have had a chance to test other downstream ArchR functions as well.

You can install via:
`devtools::install_github("GreenleafLab/ArchR", ref="dev_chrEnds", repos = BiocManager::repositories())`

**Comment by dagarfield** [comment]
I'll give both options a try today -- thanks! More soon.

**Comment by dagarfield** [comment]
SOLVED. The patch worked like a charm -- I'll keep pushing forward this version to see if it causes trouble downstream. 

For anyone still reading at home, don't for get to `library(parallel)` if you're working with R 4.1. Otherwise, your make arrow file will error out without proper error message on account of not being able to find mclapply (seems to have moved from base to parallel in 4.1).

**Comment by rcorces** [comment]
Re: the patch
Great! thanks for confirming, I've gone ahead and merged this branch into the `release_1.0.2` branch via https://github.com/GreenleafLab/ArchR/pull/1166. Please let me know if it causes problems downstream and I will look into it.

<hr>

Re:`parallel`

This had been bothering me for a while so I finally tracked it down. Description below.

In a recent update in Bioconductor, the `BiocGenerics` function stopped depending on and importing `parallel`. So in newer versions of Bioconductor, `parallel` no longer gets loaded alongside `BiocGenerics` and thus needed to be loaded separately. I've fixed this by adding a require statement when `mclapply` runs: https://github.com/GreenleafLab/ArchR/commit/0630ae09571734338520a16f801cc8a71a06d2f1

This has been fixed on `release_1.0.2`

see https://bioconductor.org/packages/release/bioc/html/BiocGenerics.html
vs 
https://bioconductor.org/packages/3.1/bioc/html/BiocGenerics.html
