### ISSUE TITLE
How to specify groups for differential peak to gene linkage?

### ISSUE THREAD

**Issue by CSBioAzim** [GreenleafLab/ArchR#116]
I have some confusion and some remarks regarding peak to gene linkage

i) What is your null model for computing the statistical significance of the association?
ii) Is it possible to limit the analysis for the differential peaks and differential genes between case and control? In other work, I would like to have the peak-gene link heatmap visualization for the peaks and genes that are differential between case and control. Exactly the same heatmap you have (rows the links, columns grouped by cell type), but only considered the peak-gene association for the differential peak and gene between the case and control for all cell types.
iii) It would be nice to show as legend the names of some of the genes for the gene heatmap, and top-ranking TFs for the peak matrix heatmap.

**Comment by jgranja24** [comment]
(1) The p-value is determined using a correlation test.

(2) You can further subset after the calculation. We did this in our previous work (Granja* et al 2019 Nature Biotechnology).

(3) This is a bit more complicated as there are thousands of genes that are present.

Best

Jeff

**Comment by CSBioAzim** [comment]
@jgranja24 thank you for the reply.
(2) You can further subset after the calculation. We did this in our previous work (Granja* et al 2019 Nature Biotechnology).
Is there any function that provides this possibility? 
Is it possible to add "usegroup" arugment to the addPeak2GeneLinks() function?
For now, it's not really clear how does it uses data to compute peak-gene correlation if I have multiple conditions in my analysis? Is it done separately for all conditions?
