### ISSUE TITLE
bugs in GroupCoverages.R

### ISSUE THREAD

**Issue by haibol2016** [GreenleafLab/ArchR#1164]
@rcorces 

lines 752-755 in [R/GroupCoverages.R](https://github.com/GreenleafLab/ArchR/blob/master/R/GroupCoverages.R)

```{r}
      if(x == 1) .logThis(iS, "InsertionSites", logFile = logFile)
      iS <- data.table(seqnames = allChr[x], start = iS - 1L, end = iS)
      if(x == 1) .logThis(iS, "InsertionSites-DT", logFile = logFile)
      data.table::fwrite(iS, out, sep = "\t", col.names = FALSE, append = TRUE)
```
should be changed as follows to avoid chromosomes without read coverage:

```{r}
      if (length(iS)> 0)
      {
        if(x == 1) .logThis(iS, "InsertionSites", logFile = logFile)
        iS <- data.table(seqnames = allChr[x], start = iS - 1L, end = iS)
        if(x == 1) .logThis(iS, "InsertionSites-DT", logFile = logFile)
        data.table::fwrite(iS, out, sep = "\t", col.names = FALSE, append = TRUE
      }
```

**Comment by rcorces** [comment]
Thanks for reporting. You are indeed correct though this was recently reported and has been fixed on the `release_1.0.2` branch already.
Original report - https://github.com/GreenleafLab/ArchR/issues/1025
Fix - https://github.com/GreenleafLab/ArchR/commit/96aa3a8c39119c8ad521f9b2002009e329d74a3e

If you dont think this fix addresses your concern, let me know and I will re-open this. Thanks again for contributing to ArchR!
