### ISSUE TITLE
correlateTrajectories(): useRanges=TRUE fails because the ranges1 and ranges2 objects no longer exist at time of logging

### ISSUE THREAD

**Issue by jpsmith5** [GreenleafLab/ArchR#1169]
https://github.com/GreenleafLab/ArchR/blob/968e4421ce7187a8ac7ea1cf6077412126876d5f/R/IntegrativeAnalysis.R#L497-L498

Quick fix is to simply move the `rm(ranges1)`, `rm(ranges2)` to just after the `.logThis` step

e.g.

```
correlateTrajectories(x, y, useRanges=TRUE)
ArchR logging to : ArchRLogs/ArchR-correlateTrajectories-afd1a1a9356-Date-2021-11-17_Time-10-25-34.log
If there is an issue, please report to github with logFile!
Error in .logThis(ranges1, "ranges1", logFile = logFile) :
  object 'ranges1' not found
```

**Comment by rcorces** [comment]
thanks for the efficient report.
Patched in `release_1.0.2` via https://github.com/GreenleafLab/ArchR/commit/560764a94c1cb117845cefd72f0089097a3e04b2
