### ISSUE TITLE
Legeneds for Pseudo-time heatmaps

### ISSUE THREAD

**Issue by CSBioAzim** [GreenleafLab/ArchR#117]
Pseudo-time heatmaps look great. I was wondering how do the legends are selected for some of the genomics regions to be displayed?
Is it also possible to automatically show/visualize  TFs whose motifs activity changes in pseudo-time in the peak-pseudo time heatmap?

**Comment by jgranja24** [comment]
> Pseudo-time heatmaps look great. I was wondering how do the legends are selected for some of the genomics regions to be displayed?

The legends should be the name of the matrix described.

> Is it also possible to automatically show/visualize TFs whose motifs activity changes in pseudo-time in the peak-pseudo time heatmap?

This is shown in the manual in detail.

**Comment by CSBioAzim** [comment]
Pseudo-time heatmaps look great. I was wondering how do the legends are selected for some of the genomics regions to be displayed?

The legends should be the name of the matrix described.

Thanks. but why only a subset of them are displayed. How can I control it?
