### ISSUE TITLE
Miss-spelling of Will's last name

### ISSUE THREAD

**Issue by brianpenghe** [GreenleafLab/ArchR#1176]
Hi guys,
Just a minor issue about the text on your manual website:
![image](https://user-images.githubusercontent.com/4110443/142778779-6e2f7f77-8db6-472b-8eb9-fc5e89223b3b.png)

The spelling of "Greenlead" suddenly made the lab Nature-unfriendly...

**Comment by rcorces** [comment]
someone beat you to the punch on this. its just been a while since we built a new version of the manual. Thanks for reporting though.
https://github.com/GreenleafLab/ArchR/issues/154
