### ISSUE TITLE
addGeneIntegrationMatrix error

### ISSUE THREAD

**Issue by brianpenghe** [GreenleafLab/ArchR#1179]
I was running `addGeneIntegrationMatrix` with this:
```
filtered <- addGeneIntegrationMatrix(
    ArchRProj = filtered, 
    useMatrix = "GeneScoreMatrix",
    matrixName = "GeneIntegrationMatrix",
    reducedDims = "IterativeLSI",
    seRNA = Fetal,
    addToArrow = TRUE,
    groupRNA = "new_celltype",
    nameCell = "predictedCell_Un",
    nameGroup = "predictedGroup_Un",
    nameScore = "predictedScore_Un"
)
```
But the program ended after 20+ minutes with the following error:
```
Error in .safelapply(seq_along(allSamples), function(y) { :
Error Found Iteration 1 :
        [1] "Error in .initializeMat(ArrowFile = ArrowFiles[sample], Group = matrixName,  : \n  Matrix Group Already Exists! Set force = TRUE to overwrite!\n"
        <simpleError in .initializeMat(ArrowFile = ArrowFiles[sample], Group = matrixName,     Class = "double", Units = "NormCounts", cellNames = colnames(sampleMat),     params = dfParams, featureDF = featureDF, force = force): Matrix Group Already Exists!
Error Found Iteration 2 :
        [1] "Error in .initializeMat(ArrowFile = ArrowFiles[sample], Group = matrixName,  : \n  Matrix Group Already Exists! Set force = TRUE to overwrite!\n"
        <simpleError in .initializeMat(ArrowFile = ArrowFiles[sample], Group = matrixName,     Class = "double", Units = "NormCounts", cellNames = colnames(sampleMat),     params = dfParams, featureDF = featureDF, force = force): Matrix Group Already Exists!
Error Found Iteration 3 :
        [1] "Error in .initializeMat(ArrowFile = ArrowFiles[sample], Group = matrixName,  : \n  Matrix Grou
In addition: There were 50 or more warnings (use warnings() to see the first 50)

```

When I set `addToArrow = FALSE` the error will be gone.
I tried re-running the command with force=TRUE and also tried naming the matrix to something else. But no luck.

Any ideas?

**Comment by rcorces** [comment]
Please always upload your log file.

I dont see how you could get this error if `force = TRUE`. `.initializeMat()` takes the `force` param here:
https://github.com/GreenleafLab/ArchR/blob/48dccf361bab6d9191a4d9b61e1317acfa71167c/R/RNAIntegration.R#L737-746

and then you only would get the message you show if `force = FALSE`
https://github.com/GreenleafLab/ArchR/blob/968e4421ce7187a8ac7ea1cf6077412126876d5f/R/ArrowWrite.R#L33-L40

You'll have to provide more information.

**Comment by brianpenghe** [comment]
I'm attaching the log file here. Thanks my man!
[ArchR-addGeneIntegrationMatrix-6a1353d96f2b-Date-2021-11-25_Time-21-03-56.log](https://github.com/GreenleafLab/ArchR/files/7605286/ArchR-addGeneIntegrationMatrix-6a1353d96f2b-Date-2021-11-25_Time-21-03-56.log)

**Comment by brianpenghe** [comment]
> Please always upload your log file.
> 
> I dont see how you could get this error if `force = TRUE`. `.initializeMat()` takes the `force` param here:
> 
> https://github.com/GreenleafLab/ArchR/blob/48dccf361bab6d9191a4d9b61e1317acfa71167c/R/RNAIntegration.R#L737-L746
> 
> and then you only would get the message you show if `force = FALSE`
> 
> https://github.com/GreenleafLab/ArchR/blob/968e4421ce7187a8ac7ea1cf6077412126876d5f/R/ArrowWrite.R#L33-L40
> 
> You'll have to provide more information.

using `force=TRUE` indeed worked! Thanks a lot!
