### ISSUE TITLE
Reduced dimensions not in computed reduceDims, Current ones are : IterativeLSI4

### ISSUE THREAD

**Issue by HeChao7021** [GreenleafLab/ArchR#1180]
When I perform addImputeWeights, the error comes as following:
projHeme2 <- addImputeWeights(projHeme2)
ArchR logging to : ArchRLogs/ArchR-addImputeWeights-b1ac2a4409d7-Date-2021-11-24_Time-12-03-52.log
If there is an issue, please report to github with logFile!
2021-11-24 12:03:53 : Computing Impute Weights Using Magic (Cell 2018), 0 mins elapsed.
Error in getReducedDims(ArchRProj, reducedDims = reducedDims, dimsToUse = dimsToUse,  : 
  Reduced dimensions not in computed reduceDims, Current ones are : IterativeLSI4

I also tried the solution in #202 , but failed. The version of ArchR is 1.0.1. Waiting for the response sincelery. Thank you！

**Comment by rcorces** [comment]
Your error is quite explicit. The default for the `reducedDims` parameter is `IterativeLSI`. You do not have a reducedDims object called `IterativeLSI` so you cannot simply use the default. You must provide `reducedDims = "IterativeLSI4"`
https://www.archrproject.com/reference/addImputeWeights.html

**Comment by HeChao7021** [comment]
> Your error is quite explicit. The default for the `reducedDims` parameter is `IterativeLSI`. You do not have a reducedDims object called `IterativeLSI` so you cannot simply use the default. You must provide `reducedDims = "IterativeLSI4"` https://www.archrproject.com/reference/addImputeWeights.html

Thank you for replying, but even when I specific the reducedDims to "IterativeLSI4", the error still existed.
> reducedDims = "IterativeLSI4"
> projHeme2 <- addImputeWeights(projHeme2)
ArchR logging to : ArchRLogs/ArchR-addImputeWeights-b1ac49271ed0-Date-2021-11-24_Time-13-31-10.log
If there is an issue, please report to github with logFile!
2021-11-24 13:31:11 : Computing Impute Weights Using Magic (Cell 2018), 0 mins elapsed.
Error in getReducedDims(ArchRProj, reducedDims = reducedDims, dimsToUse = dimsToUse,  : 
  Reduced dimensions not in computed reduceDims, Current ones are : IterativeLSI4

**Comment by HeChao7021** [comment]
> Your error is quite explicit. The default for the `reducedDims` parameter is `IterativeLSI`. You do not have a reducedDims object called `IterativeLSI` so you cannot simply use the default. You must provide `reducedDims = "IterativeLSI4"` https://www.archrproject.com/reference/addImputeWeights.html

Yes, when specific reduceDims = "IterativeLSI4", it go well. Thank you for replying
projHeme2 <- addImputeWeights(projHeme2, reducedDims = "IterativeLSI4")
