### ISSUE TITLE
Errors in using getMarkerFeatures

### ISSUE THREAD

**Issue by brianpenghe** [GreenleafLab/ArchR#1185]
**Attach your log file**

[ArchR-getMarkerFeatures-6a134be61b7c-Date-2021-11-25_Time-20-21-11.log](https://github.com/GreenleafLab/ArchR/files/7605155/ArchR-getMarkerFeatures-6a134be61b7c-Date-2021-11-25_Time-20-21-11.log)

I was trying to get marker peaks but ran into this error.
Previous Github Issues didn't provide any answer to this and the underlying causes might be different.

There's what I did:
```
> markersPeaks <- getMarkerFeatures(
+     ArchRProj = fetal_lung_clean, 
+     useMatrix = "PeakMatrix", 
+     groupBy = "cell_type",
+   bias = c("TSSEnrichment", "log10(nFrags)"),
+   testMethod = "wilcoxon"
+ )
ArchR logging to : ArchRLogs/ArchR-getMarkerFeatures-6a134be61b7c-Date-2021-11-25_Time-20-21-11.log
If there is an issue, please report to github with logFile!
2021-11-25 20:21:12 : Matching Known Biases, 0.015 mins elapsed.
Error in cor(estbgdP, obsbgdP) : incompatible dimensions
In addition: Warning messages:
1: In rbind(estbgd, obsbgd) :
  number of columns of result is not a multiple of vector length (arg 1)
2: In rbind(estbgdP, obsbgdP) :
  number of columns of result is not a multiple of vector length (arg 1)

> 
```
Any thoughts?

**Comment by brianpenghe** [comment]
I tried `useMatrix="GeneScoreMatrix"` and got the same error :(

**Comment by rcorces** [comment]
It sounds like from your other posting that this error was something sporadic. I am closing this but feel free to comment again here if this error persists

**Comment by brianpenghe** [comment]
I changed my threads into 1 but the error is still there :( 
I've attached my log file again
[ArchR-getMarkerFeatures-306545047632-Date-2021-11-30_Time-12-25-33.log](https://github.com/GreenleafLab/ArchR/files/7625686/ArchR-getMarkerFeatures-306545047632-Date-2021-11-30_Time-12-25-33.log)
.
```
> markersPeaks <- getMarkerFeatures(
+     ArchRProj = fetal_lung_clean, 
+     useMatrix = "PeakMatrix", 
+     groupBy = "cell_type",
+   bias = c("TSSEnrichment", "log10(nFrags)"),
+   testMethod = "wilcoxon"
+ )
ArchR logging to : ArchRLogs/ArchR-getMarkerFeatures-306545047632-Date-2021-11-30_Time-12-25-33.log
If there is an issue, please report to github with logFile!
2021-11-30 12:25:35 : Matching Known Biases, 0.016 mins elapsed.
Error in cor(estbgdP, obsbgdP) : incompatible dimensions
In addition: Warning messages:
1: In rbind(estbgd, obsbgd) :
  number of columns of result is not a multiple of vector length (arg 1)
2: In rbind(estbgdP, obsbgdP) :
  number of columns of result is not a multiple of vector length (arg 1)

```

**Comment by erebboah** [comment]
@brianpenghe I had this error today. In my case, I fixed it by removing special characters (+ and / ) from some of my celltype names. Underscores were fine. 

Log file before:
[ArchR-getMarkerFeatures-b1b4591bb8d1-Date-2022-02-15_Time-07-48-34.log](https://github.com/GreenleafLab/ArchR/files/8075944/ArchR-getMarkerFeatures-b1b4591bb8d1-Date-2022-02-15_Time-07-48-34.log)
Log file after: 
[ArchR-getMarkerFeatures-b1b44566f13c-Date-2022-02-15_Time-07-51-59.log](https://github.com/GreenleafLab/ArchR/files/8075951/ArchR-getMarkerFeatures-b1b44566f13c-Date-2022-02-15_Time-07-51-59.log)

**Comment by yxy92** [comment]
For my case, the error is fixed by converting  ''Immature Neuron" to  ''Immature_Neuron". So space and other special character probably not allowed, whereas '_' is fine.
