### ISSUE TITLE
getMatrixFromProject() error 

### ISSUE THREAD

**Issue by zhenzuo2** [GreenleafLab/ArchR#1188]
TileMatrix <- getMatrixFromProject(projretina2, useMatrix = "TileMatrix")

ArchR logging to : ArchRLogs/ArchR-getMatrixFromProject-107ca7c05a594-Date-2021-11-26_Time-11-27-17.log
If there is an issue, please report to github with logFile!
Error in .safelapply(seq_along(ArrowFiles), function(x) { :
Error Found Iteration 1 :
        [1] "Error in .getMatFromArrow(ArrowFile = ArrowFile, featureDF = featureDF,  : \n  Sparse Matrix in Arrow is Binarized! Set binarize = TRUE to use matrix!\n"
        <simpleError in .getMatFromArrow(ArrowFile = ArrowFile, featureDF = featureDF,     cellNames = cellNames, useMatrix = useMatrix, binarize = binarize,     useIndex = FALSE): Sparse Matrix in Arrow is Binarized! Set binarize = TRUE to use matrix!>
Error Found Iteration 2 :
        [1] "Error in .getMatFromArrow(ArrowFile = ArrowFile, featureDF = featureDF,  : \n  Sparse Matrix in Arrow is Binarized! Set binarize = TRUE to use matrix!\n"
        <simpleError in .getMatFromArrow(ArrowFile = ArrowFile, featureDF = featureDF,     cellNames = cellNames, useMatrix = useMatrix, binarize = binarize,     useIndex = FALSE): Sparse Matrix in Arrow is Binarized! Set binarize = TRUE to use matrix!>
Error Found Iteration 3 :
        [1] "Error in .getMatFromArrow(ArrowFile = ArrowFile, featureDF = featureDF,  : \n  Sparse Mat
In addition: Warning message:
In mclapply(..., mc.cores = threads, mc.preschedule = preschedule) :
  25 function calls resulted in an error

[ArchR-getMatrixFromProject-107ca727c7fd1-Date-2021-11-26_Time-11-05-49.log](https://github.com/GreenleafLab/ArchR/files/7610142/ArchR-getMatrixFromProject-107ca727c7fd1-Date-2021-11-26_Time-11-05-49.log)

**Comment by rcorces** [comment]
Your error is very explicit:

> [1] "Error in .getMatFromArrow(ArrowFile = ArrowFile, featureDF = featureDF, : \n Sparse Matrix in Arrow is Binarized! Set binarize = TRUE to use matrix!\n"

ArchR is asking you to change the `binarize` parameter. https://www.archrproject.com/reference/getMatrixFromProject.html

That being said, retrieval of a `TileMatrix` using `getMatrixFromProject()` is not advisable/possible as it will be returned in dense format and take up an incredible amount of memory.
