### ISSUE TITLE
Can not create group. Object with name 'KmerBias/Info' already exists

### ISSUE THREAD

**Issue by brianpenghe** [GreenleafLab/ArchR#1189]
I was running `addGroupCoverages` but got errors.

`fetal_lung_clean <- addGroupCoverages(ArchRProj = fetal_lung_clean, groupBy = "cell_type",force = TRUE)`

I got error messages ending with this:

```
2021-11-27 14:36:55 : Adding Kmer Bias to Coverage Files!, 15.901 mins elapsed.
chr1 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr2 chr20 chr21 chr22 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chrX chrY Can not create group. Object with name 'KmerBias' already exists.
Can not create group. Object with name 'KmerBias/Info' already exists.
Can not create group. Object with name 'KmerBias' already exists.
Can not create group. Object with name 'KmerBias/Info' already exists.
2021-11-27 14:52:21 : Finished Creation of Coverage Files!, 31.329 mins elapsed.
ArchR logging successful to : ArchRLogs/ArchR-addGroupCoverages-6a13700bfe87-Date-2021-11-27_Time-14-21-01.log
```

Any ideas?

**Comment by rcorces** [comment]
Please provide more information. Have you already created coverage files for this project using `groupBy = "cell_type"`.
In general, I'm going to be much less helpful without reproducible examples using the tutorial dataset.

**Comment by brianpenghe** [comment]
Yes I already created the coverage files. But I thought the `force=TRUE` asks the program to overwrite?
[ArchR-addGroupCoverages-6a13700bfe87-Date-2021-11-27_Time-14-21-01.log](https://github.com/GreenleafLab/ArchR/files/7621304/ArchR-addGroupCoverages-6a13700bfe87-Date-2021-11-27_Time-14-21-01.log)

I've attached my log file

**Comment by rcorces** [comment]
in this case, the kmer bias is not overwritten. I think the assumption was that there would be no need to recalculate this. Though I guess I can see a reason why one might find themselves in that situation. can you elaborate on why you are calculating it twice for the same cells? did you subset the project or something?

**Comment by brianpenghe** [comment]
> in this case, the kmer bias is not overwritten. I think the assumption was that there would be no need to recalculate this. Though I guess I can see a reason why one might find themselves in that situation. can you elaborate on why you are calculating it twice for the same cells? did you subset the project or something?

I filtered the object to remove unwanted clusters. But maybe "Can not create group" is more a warning than error?
What is the real error where I'm stuck is the [getMarkerFeatures](https://github.com/GreenleafLab/ArchR/issues/1185#issuecomment-982590454)  . Are they related?

**Comment by brianpenghe** [comment]
It should be a error during subsetting. Not sure where but strictly following the tutorial worked.
