### ISSUE TITLE
Function for ploting the heatmap of differentially expressed genes and scATAC gene score

### ISSUE THREAD

**Issue by CSBioAzim** [GreenleafLab/ArchR#119]
I would love to have the function to generate the heatmap of differentially expressed genes and differential scATAC gene scores. Something like plot 2.e in your manuscript.

Thanks

**Comment by rcorces** [comment]
Differential testing is described in the manual.
https://www.archrproject.com/bookdown/pairwise-testing-between-groups.html
Heatmaps can be plotted using many different R packages including `pheatmap`

**Comment by jgranja24** [comment]
Too add to this point markerHeatmap can create a heatmap.

**Comment by CSBioAzim** [comment]
@rcorces @jgranja24  Thanks for the reply. What you are describing for differential testing is very specific, and can not handle the case of differential testing for all cell types between normal and diseases at once to create the heatmap. One simple reason is that it needs to find the nearest neighbor cell in the same cell type. Given fact that you want to compute the logFC for disease vs. healthy, I couldn't find a way to specify that for each cell type or cluster it should use the most similar cells in the healthy condition. of course, you can limit your analysis for one cell type and specify your background cell type for that. 
but when you want to compute healthy vs diseases logFC, you have multiple cell types, and you need to have the flexibility to specify the background cell type for each cell type, and I'm not sure how is it possible with the current function that you are describing..

**Comment by jgranja24** [comment]
>  What you are describing for differential testing is very specific, and can not handle the case of differential testing for all cell types between normal and diseases at once to create the heatmap.

You can cbind seMarker (output of getMarkerFeatures) from multiple runs of the analysis. And then run plotMarkerHeatmap.
