### ISSUE TITLE
Can ArchR calculate gene score matrix only with peak counts matrix?

### ISSUE THREAD

**Issue by Telogen** [GreenleafLab/ArchR#1190]
Hi, I 'm trying to calculate gene score matrix using ArchR, but I do not have neither fragment file nor BAM file. I only have the peak counts matrix, and this matrix has already pass the quality control and peak calling. Can I calculate gene score matrix only with this peak counts matrix using ArchR? Thanks!

**Comment by rcorces** [comment]
Please note that Issues are for bugs and error reports. This is a usage question which belongs in Discussions. I am transferring this there.
