### ISSUE TITLE
Errors in using getMarkerFeatures

### ISSUE THREAD

**Issue by tongyt1225** [GreenleafLab/ArchR#1194]
hi, I get an error in using getMarkerFeatures as follow:
![截屏2021-11-30 上午10 09 05](https://user-images.githubusercontent.com/52367576/143973349-3d607017-2413-481e-9cf1-51ef18a94c38.png)
Thanks

**Comment by rcorces** [comment]
Thanks for using ArchR. Please pay attention to the instructions in the provided issue template when you open a new issue. You must upload your log file.

**Comment by tongyt1225** [comment]
sorry,this is log file: log fileArchR-getMarkerFeatures-4217f6efc10-Date-2021-12-01_Time-09-23-42.log
thanks

**Comment by tongyt1225** [comment]
sorry,this is log file, thanks
[ArchR-getMarkerFeatures-4217f6efc10-Date-2021-12-01_Time-09-23-42.log](https://github.com/GreenleafLab/ArchR/files/7629963/ArchR-getMarkerFeatures-4217f6efc10-Date-2021-12-01_Time-09-23-42.log)

**Comment by rcorces** [comment]
If you parse through your log file you will find:

```
<simpleError in .requirePackage("presto", installInfo = "devtools::install_github(\"immunogenomics/presto\")"): Required package : presto is not installed/found!
  Package Can Be Installed : devtools::install_github("immunogenomics/presto")>
```

It sounds like you might not have properly installed ArchR. The instructions on the home page. Perhaps this step didnt get run or didnt complete successfully:
![image](https://user-images.githubusercontent.com/10343046/144155584-d9f3f2fe-4863-4846-8b64-9eaeb3c58392.png)
