### ISSUE TITLE
ArchR Browser does not display peaks; release_1.0.2

### ISSUE THREAD

**Issue by artgolden** [GreenleafLab/ArchR#1206]
**Attach your log file**
[ArchRBrowser_brocken.log](https://github.com/GreenleafLab/ArchR/files/7637045/ArchRBrowser_brocken.log)

**Describe the bug**
With a clear run of tutorial code when running `ArchRBrowser(ArchRProj = proj) `everything seems to run normally, but when attempting to generate a plot, all tracks appear to be straight lines (attaching a screenshot).

When running

```
p <- plotBrowserTrack(
    ArchRProj = proj,
    groupBy = "Clusters",
    geneSymbol = "CD14",
    upstream = 50000,
    downstream = 50000
)
```
everything is fine and I get a plot same as in your tutorial.

**To Reproduce**
Clean install of release_1.0.2 branch with a tutorial dataset.

**I have created a Docker image that reproduces this issue** ([link to the image](https://drive.google.com/drive/folders/18gIequx1x3l-2Bh6ikrBTF--1LQ6wVuy?usp=sharing))! This docker image contains RStudio with ArchR and analysed tutorial dataset. In this image you can also observe the bug that was discussed here: https://github.com/GreenleafLab/ArchR/issues/1052#issuecomment-983032247_

To run the docker image: 
```docker load archr_release102_docker.tar```
create a `tmp/` directory in a directory where you will be running docker container from. Then run:
```docker run -e DISABLE_AUTH=true --rm -p 28787:8787 -v $(pwd)/tmp:/home/rstudio/tmp archr_release102```
Connect to Rstudio from the browser on `http://localhost:28787/` and run `testing_archr_docker.R` script

A Dockerfile if you would like to make this image yourself:
[Dockerfile.txt](https://github.com/GreenleafLab/ArchR/files/7637268/Dockerfile.txt)

**Expected behavior**
Peaks should be visible in the browser.
I have exactly the same docker image build with the master branch release_1.0.1 and there peaks are shown as expected in the browser.

**Screenshots**
![image](https://user-images.githubusercontent.com/3861476/144312815-a2668bec-e113-461c-bd1e-43504b48e4b6.png)

**Comment by rcorces** [comment]
thanks for the detailed post. when you say

> I have exactly the same docker image build with the master branch release_1.0.1 and there peaks are shown as expected in the browser.

Do you mean that all R package versions are the same in both containers and the only difference is ArchR `release_1.0.1` vs `release_1.0.2`?

**Comment by artgolden** [comment]
I am not sure. Let me elaborate:
The difference between two containers is in the two last steps of the build process. 
For release_1.0.2:
```
RUN R -e "devtools::install_github('GreenleafLab/ArchR', ref='release_1.0.2', repos = BiocManager::repositories())"
RUN R -e "ArchR::installExtraPackages()"
```
For release_1.0.1:
```
RUN R -e "devtools::install_github('GreenleafLab/ArchR', ref='master', repos = BiocManager::repositories())"
RUN R -e "ArchR::installExtraPackages()"
```
Given that `ArchR::installExtraPackages()` installs the same software between releases, then yes, the environments are identical.

Previously I have also created a clean conda environment for testing. I have created the environment and ran: 
```
devtools::install_github('GreenleafLab/ArchR', ref='master', repos = BiocManager::repositories())
ArchR::installExtraPackages()
```
Everything works fine and peaks are shown in the browser.

If I run `devtools::install_github('GreenleafLab/ArchR', ref='release_1.0.2', repos = BiocManager::repositories())` in the same conda environment. The browser stops showing the peaks. 
If I run `devtools::install_github('GreenleafLab/ArchR', ref='master', repos = BiocManager::repositories())` again, the issue disappears. 
I assume that the only difference between the working and buggy state of this conda environment is the different release versions.

**Comment by rcorces** [comment]
Thanks for all of the details. I can confirm that I am able to recapitulate this error. It stems from a change that I made in the `.bulkTracks()` function (https://github.com/GreenleafLab/ArchR/commit/8caa716086832c2560b867b6e4a0d1bab48716e1) when addressing this discussion post: https://github.com/GreenleafLab/ArchR/discussions/903
It turns out that change was not correct and I have now reverted it via https://github.com/GreenleafLab/ArchR/commit/63e7883586a013b9a9c264ddb19dea18d9287087

For posterity sake, I've updated the function parameter definition for `plotBrowserTrack()` to clarify how the ylim param should be used as this was the original confusion that caused me to make this mistake.

In my hands, the latest `release_1.0.2` works just fine. Thanks again for your efforts in addressing this issue! If for some reason, this doesnt fix your issue, please comment again below.

To install, run:
```
devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.2", repos = BiocManager::repositories())
```
Then restart your R session, reload the ArchR package, and give it a try.

**Comment by artgolden** [comment]
Great! Thanks for the quick maintenance!
It works for me with release_1.0.2 now.

**Comment by rcorces** [comment]
glad it works and thanks for your help in addressing this. It is easy to fix things when the bug reports are thorough. I wish everyone did the same.
