### ISSUE TITLE
getCoAccessibility peak index repeats in each chromosome?

### ISSUE THREAD

**Issue by Zepeng-Mu** [GreenleafLab/ArchR#1209]
Hi, I'm trying to get co-accessible peaks and use these for some downstream analysis.

```r
cA <- getCoAccessibility(
  ArchRProj = projCmb1,
  corCutOff = 0.5,
  resolution = 1,
  returnLoops = F
)

cAPeak <- metadata(cA)[[1]]
names(cAPeak) <- str_glue("{seqnames(cAPeak)}_{start(cAPeak)}-{end(cAPeak)}")
```
This is what I'm trying to do following the documentation. But `table(cAPeak$idx)` gives something like this:

```
1    2    3    4    5    6    7    8    9   10   11   12   13   14   15   16   17   18   19   20 
23   23   23   23   23   23   23   23   23   23   23   23   23   23   23   23   23   23   23   23
```
and so on...

This means that each "idx" appears 23 times, so each chromosome has it's own index numbering for the peaks. I'm wondering whether this is the intended behavior? In this case it's a bit confusing to extract peaks using "queryHits" and "subjectHits" without separating the chromosomes.

Thanks so much!

**Comment by rcorces** [comment]
Hi @Zepeng-Mu! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.

**Comment by Zepeng-Mu** [comment]
Actually, I think it's only the order of peaks matters now. I should not use `idx` column.
