### ISSUE TITLE
How to specify branching tranjectroy in pseudo time analysis?

### ISSUE THREAD

**Issue by CSBioAzim** [GreenleafLab/ArchR#121]
Pseudo time analysis looks great. I would be happy if you would clarify:

i) Why do you only retain top 5% of the cells based on their euclidian distance from cluster i mean center? Would be the cells that are far from the cluster center would also be interesting (maybe they represent different cellular states) ? 
ii) How can I specify the trajectory backbone if I have a branching event in my trajectory?

iii) How can I do differential trajectory analysis between diseases and control for the same cell types?

Thanks!

**Comment by jgranja24** [comment]
i) I think you may have misinterpreted because the top 95% of cells are retained.

ii) Make 2 separate trajectories for each branch.

iii) Specify in trajectory c("CellA_Control", "CellA_Disease"). You will have to do this for each case.
