### ISSUE TITLE
How the feature smoothing is done for scATAC for trajectory analysis?

### ISSUE THREAD

**Issue by CSBioAzim** [GreenleafLab/ArchR#122]
Pseudo time analysis looks great, but I had a hard time understanding which feature value is used for scATAC? Is it on low overlapping cells? 
Would it be possible to elaborate on this more?
"First, ArchR groups cells in small user-defined quantile increments (default = 1/100) across the cellular trajectory. ArchR then smooths this matrix per feature using a user-defined smoothing window (default = 9/100) using the data.table::frollmean function. ArchR then returns this smoothed pseudo-time x feature matrix as a SummarizedExperiment for downstream analyses"

**Comment by jgranja24** [comment]
Feature is a generic term for peak/genescore/etc. Its averaged within each cell group and smoothed as described.

**Comment by CSBioAzim** [comment]
@jgranja24, thanks for the clarification. But how does the cell groups are defined? How much is the size?
