### ISSUE TITLE
CoAccessibility error: No Chr Found in ArrowFiles!

### ISSUE THREAD

**Issue by concatenize** [GreenleafLab/ArchR#123]
I'm running a one-line command using the latest ArchR version (0.9.3).

    addCoAccessibility(projArch, reducedDims = "IterativeLSI")

This yields the following output and error:

```
ArchR logging to : ArchRLogs/ArchR-addCoAccessibility-e9e467544aaa-Date-2020-05-08_Time-07-51-28.log
If there is an issue, please report to github with logFile!
2020-05-08 07:51:28 : Computing KNN, 0.002 mins elapsed.
2020-05-08 07:51:28 : Identifying Non-Overlapping KNN pairs, 0.009 mins elapsed.
2020-05-08 07:51:36 : Identified 494 Groupings!, 0.133 mins elapsed.
Error in .availableChr(getArrowFiles(ArchRProj), subGroup = "PeakMatrix") : 
  No Chr Found in ArrowFiles!
```

I'm sorry to say it's confidential data, but is there a way I could extract at least a header for you to see? Here's the log. Thanks!

[ArchR-addCoAccessibility-e9e467544aaa-Date-2020-05-08_Time-07-51-28.log](https://github.com/GreenleafLab/ArchR/files/4598798/ArchR-addCoAccessibility-e9e467544aaa-Date-2020-05-08_Time-07-51-28.log)

**Expected behavior**

Co-accessibility information returned.

**Comment by jgranja24** [comment]
Have you added a peak matrix with `addReproduciblePeakSet` and `addPeakMatrix.` To check use `getPeakSet` and `getAvailableMatrices`. If so then i will further diagnose this problem.

**Comment by concatenize** [comment]
I have not. That's probably it. Thank you!

**Comment by jgranja24** [comment]
No worries we will update the error message to be more helpful.
