### ISSUE TITLE
getMarkerFeatures error

### ISSUE THREAD

**Issue by xcxtx8** [GreenleafLab/ArchR#124]
[ArchR-getMarkerFeatures-13aad3f6fdc1f-Date-2020-05-08_Time-12-43-36.log](https://github.com/GreenleafLab/ArchR/files/4601237/ArchR-getMarkerFeatures-13aad3f6fdc1f-Date-2020-05-08_Time-12-43-36.log)
**Describe the bug**
Hello, When I was trying to run GetMarkerFeatures, I got an error ArchR logging to : ArchRLogs/ArchR-getMarkerFeatures-13aad3f6fdc1f-Date-2020-05-08_Time-12-43-36.log
If there is an issue, please report to github with logFile!
2020-05-08 12:43:38 : Matching Known Biases, 0.004 mins elapsed.
Error in .safelapply(seq_along(matchObj[[1]]), function(x) { : 
Error Found Iteration 1 : 
	[1] "Error in .logError(e, fn = \".sparseMatWilcoxon\", info = seqnames[y], errorList = errorList,  : \n  Exiting See Error Above\n"
	<simpleError in .logError(e, fn = ".sparseMatWilcoxon", info = seqnames[y], errorList = errorList,     logFile = logFile): Exiting See Error Above>
Error Found Iteration 2 : 
	[1] "Error in .logError(e, fn = \".sparseMatWilcoxon\", info = seqnames[y], errorList = errorList,  : \n  Exiting See Error Above\n"
	<simpleError in .logError(e, fn = ".sparseMatWilcoxon", info = seqnames[y], errorList = errorList,     logFile = logFile): Exiting See Error Above>
Error Found Iteration 3 : 
	[1] "Error in .logError(e, fn = \".sparseMatWilcoxon\", info = seqnames[y], errorList = errorList,  : \n  Exiting See Error Above\n"
	<simpleError in .logError(e, fn = ".sparseMatWilcoxon", info = seqnames[y], errorList = errorList,     logFile = logFile): Exiting See Error Above>
Error Found Iteration 4 : 
	[1] "Error in .logError(e, fn =
In addition: Warning message:
In mclapply(..., mc.cores = threads, mc.preschedule = preschedule) :
  12 function calls resulted in an error

I tried to rerun on the tutorial dataset but still got the same error.

Could you help figure that out?

Thank you!!!

**Comment by jgranja24** [comment]
Hi

Thanks for using ArchR. The error says that the package presto is not installed. Try ArchR::installExtraPackages or the installation below. 

```

<simpleError in .requirePackage("presto", installInfo = "devtools::install_github(\"immunogenomics/presto\")"): Required package : presto is not installed/found!
  Package Can Be Installed : devtools::install_github("immunogenomics/presto")>

```

**Comment by rcorces** [comment]
Closing this. @xcxtx8, feel free to open this if you think your issue has not been addressed. I would encourage you to make sure all install instructions have been followed as the dependencies are complex for ArchR. https://www.archrproject.com/

**Comment by mk1209567** [comment]
I also met the same error and this solutions worked! 

Thanks.
