### ISSUE TITLE
Extracting and annotating specific part of the heatmaps

### ISSUE THREAD

**Issue by CSBioAzim** [GreenleafLab/ArchR#125]
Hi,

I'm looking away to extract specific patterns (specific block somewhere in the heatmap) from the heatmaps for downstream analysis. It would be nice if you would provide a way to do it. Is there an easy way to do it? For example, when one sees interesting patten in the heatmap, the first question is what's that? (row names, colnames. Having a function to extract user-defined pattern would increase the applicability of ArchR

![image](https://user-images.githubusercontent.com/15929793/81480734-6d9b4d00-91f9-11ea-8861-4e282340b709.png)

**Comment by jgranja24** [comment]
This is a duplicated issue of #130. Closing this issue.
