### ISSUE TITLE
Dataframe of Metadata

### ISSUE THREAD

**Issue by mossnicholas** [GreenleafLab/ArchR#126]
May have missed it somewhere in the documentation, but it doesn't appear to be possible to add a dataframe of metadata to a project. I'm working with a screen where each barcode is associated with a specific sgRNA capture, and would like to associate cells with their sgRNA and name of gene KO (which are defined in a dataframe with their barcodes). Would essentially merge metadata frame on cellNames (barcodes) in ArchR object. 

Thanks!

**Comment by rcorces** [comment]
I'm not sure I fully understand what you want to do but this seems like a use case that is handled perfectly by the built in metadata stored in `cellColData`. Any per-cell metadata that you want to use should be added to `cellColData`. There is also `sampleColData` which stores per-sample metadata. There really shouldnt be any need to add a separate data frame of metadata?

Example 3 in this page of the manual.
https://www.archrproject.com/bookdown/manipulating-an-archrproject.html

Please close the issue if this answers your question.
