### ISSUE TITLE
Accessing Individual Gene Scores

### ISSUE THREAD

**Issue by mossnicholas** [GreenleafLab/ArchR#127]
I'm interested in accessing individual genes scores, but didn't notice any way to do so in the documentation. Is there a way to access each raw gene score (23,000) for individual cells, once we have created the arrow files and their corresponding project? Would be useful to have to correlate with other specific analysis separate from clustering.

**Comment by rcorces** [comment]
Gene scores are stored in a special matrix called "GeneScoreMatrix" within each arrow file. Matrices are accessed from a project using `getMatrixFromProject()`. This returns a `SummarizedExperiment` which contains a sparse matrix of class `dgCMatrix` of the gene scores of each cell.
