### ISSUE TITLE
plotEmbedding using custom colors returns a grey umap

### ISSUE THREAD

**Issue by ksr2018** [GreenleafLab/ArchR#1278]
Hi, 
I want to use custom colors for my UMAP, but when I pass this custom color palette to pal in plotEmbedding, the UMAP is grey. If I leave out the pal option, the UMAP is plotted correctly in default colors. I have this issue with two different ArchR projects but I have not tried reproducing with the tutorial.
Not sure if I'm doing something wrong in generating the palette (it looks similar to an ArchR palette). I have attached my code, log file and screenshots of the umaps with and without custom colors. 
Your help in figuring this out is very much appreciated!

`test <- c("1" = "#000000", "2" ="#FF0000", "3"="#4682b4")`
`p6 <- plotEmbedding(ArchRProj = cms, colorBy = "cellColData", name = "Sample", embedding = "UMAP", pal = test)`
`p6`

<img width="857" alt="Screen Shot 2022-02-01 at 3 59 38 PM" src="https://user-images.githubusercontent.com/39506585/152071497-f0284999-418f-4785-a8e0-f534a389ec7d.png">

[ArchR-plotEmbedding-156f34a27c582-Date-2022-02-01_Time-15-49-08.log](https://github.com/GreenleafLab/ArchR/files/7982650/ArchR-plotEmbedding-156f34a27c582-Date-2022-02-01_Time-15-49-08.log)

**Comment by rcorces** [comment]
Hi @ksr2018! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.

**Comment by rcorces** [comment]
You're missing a step.

<html>
<body>


pal | A custom palette (see paletteDiscrete or ArchRPalettes) used to override discreteSet/continuousSet for coloring vector.
-- | --



</body>
</html>

The function documentation says the palette must come from `paletteDiscrete()`

The palette provided to `pal` is not merely one of the ones from `ArchRPalettes`. The palette has to have the correct names of the things you are plotting (Sample in your case, clusters in the example below).

```
proj <- getTestProject()
test <- c("C1" = "#000000", "C2" ="#FF0000", "C3"="#4682b4", "C4" = "#89288F", "C5" ="#F47D2B")
plotEmbedding(ArchRProj = proj, colorBy = "cellColData", name = "Clusters", embedding = "UMAP", pal = test)
```
![image](https://user-images.githubusercontent.com/10343046/152227934-f4903e20-b112-4b56-95a3-eb7d9b1e5133.png)

**Comment by ksr2018** [comment]
Ah I see. It works now. Thank you very much!
