### ISSUE TITLE
A question about addPeak2GeneLinks correlation

### ISSUE THREAD

**Issue by yangxueqianR** [GreenleafLab/ArchR#1283]
Hello, I would like to use the Correlation of Peak2Genelink to predict gene enhancers, so I would like to ask how this Correlation was obtained and what method was used. I looked at the addPeak2GeneLinks source code for a rowCorCpp function calculation correlation, but I did not find the rowCorCpp function description.

**Comment by rcorces** [comment]
Hi @yangxueqianR! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.

**Comment by yangxueqianR** [comment]
Thank you for your reply. I'am sorry. I'll go to the discussion board. I'll close this in a second
