### ISSUE TITLE
ArchR::getMarkerFeatures

### ISSUE THREAD

**Issue by Massimo-Petretich** [GreenleafLab/ArchR#1284]
Hi Rayan,

I have seen the notice that you're on parental leave. Congratulations, and, I am not expecting a response any time soon.

I have experienced a failure with ArchR::getMarkerFeatures. It may have to do with the dataset I am working on at the moment since I used this function successfully for another dataset I worked on in the past.

I went through the log file generated by the call but found nothing that prompts me in any obvious direction (I saw a post for a similar issue showing that 'presto' was not installed, which is an easy to spot and fix). In my case, I made sure that all the additional dependancies are installed correctly.

Also, in the cellColData DataFrame slot there are no NAs (which of course include the 'cell_type_' column I specified on the groupBy argumnent).

If you have an idea of what could have caused this failure, that would be very appreciated.

Thanks a lot in any case,
Massimo

> markers = ArchR::getMarkerFeatures(
    ArchRProj = x,
    useMatrix = "PeakMatrix",
    groupBy = "cell_type_",
    #bias = c("TSSEnrichment", "log10(nFrags)"),
    testMethod = "wilcoxon"
)
ArchR logging to : ArchRLogs/ArchR-getMarkerFeatures-8e797a746b35-Date-2022-02-09_Time-05-08-47.log
If there is an issue, please report to github with logFile!
2022-02-09 05:08:47 : Matching Known Biases, 0.004 mins elapsed.
2022-02-09 05:08:52 : Computing Pairwise Tests (1 of 5), 0.075 mins elapsed.
2022-02-09 05:08:52 : Computing Pairwise Tests (2 of 5), 0.075 mins elapsed.
2022-02-09 05:08:52 : Computing Pairwise Tests (3 of 5), 0.075 mins elapsed.
2022-02-09 05:08:52 : Computing Pairwise Tests (4 of 5), 0.075 mins elapsed.
2022-02-09 05:09:20 : Computing Pairwise Tests (5 of 5), 0.554 mins elapsed.
Error in .safelapply(seq_along(matchObj[[1]]), function(x) { :
Error Found Iteration 1 :
        [1] "Error in pairwiseDF$fdr[idxFilter] <- p.adjust(pairwiseDF$pval[idxFilter],  : \n  NAs are not allowed in subscripted assignments\n"
        <simpleError in pairwiseDF$fdr[idxFilter] <- p.adjust(pairwiseDF$pval[idxFilter],     method = "fdr"): NAs are not allowed in subscripted assignments>
Error Found Iteration 2 :
        [1] "Error in pairwiseDF$fdr[idxFilter] <- p.adjust(pairwiseDF$pval[idxFilter],  : \n  NAs are not allowed in subscripted assignments\n"
        <simpleError in pairwiseDF$fdr[idxFilter] <- p.adjust(pairwiseDF$pval[idxFilter],     method = "fdr"): NAs are not allowed in subscripted assignments>
Error Found Iteration 3 :
        [1] "Error in pairwiseDF$fdr[idxFilter] <- p.adjust(pairwiseDF$pval[idxFilter],  : \n  NAs are not allowed in subscripted assignments\n"
        <simpleError in pairwiseDF$fdr[idxFilter] <- p.adjust(pairwiseDF$pval[idxFilter],     method = "fdr"): NAs are not allowed in subscripted assignments>
Error Found Iteration 4 :
        [1] "Error
In addition: Warning message:
In mclapply(..., mc.cores = threads, mc.preschedule = preschedule) :
  5 function calls resulted in an error
[ArchR-getMarkerFeatures-8e797a746b35-Date-2022-02-09_Time-05-08-47.log](https://github.com/GreenleafLab/ArchR/files/8031804/ArchR-getMarkerFeatures-8e797a746b35-Date-2022-02-09_Time-05-08-47.log)

**Comment by rcorces** [comment]
Hi @Massimo-Petretich! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.

**Comment by Massimo-Petretich** [comment]
1) Yes, I looked to all of the issues featuring the function I am troubleshooting. None of the situations corresponds to the issue I encountered.
2) No, it works just fine with the provided dataset.
3) Yes, at the end of the post.

Thanks,
Massimo

**Comment by rcorces** [comment]
Have you tried the `release_1.0.2` branch? Similar errors were reported previously and fixed:
https://github.com/GreenleafLab/ArchR/issues/562
https://github.com/GreenleafLab/ArchR/issues/483

**Comment by Massimo-Petretich** [comment]
Thanks, it solved the problem.

Massimo
