### ISSUE TITLE
plotEmbedding() without labels?

### ISSUE THREAD

**Issue by shaka87** [GreenleafLab/ArchR#129]
I am trying to edit plots generated by plotEmbedding() in Illustrator. 
When I make a plot that shows for example clustering and save that using
plotPDF(), I am unable to remove the labels of the clusters within that plot 
(removing the text leaves holes and I don't see the points where the label was). 

Could you add a parameter that allows to turn off the labels within the plot
generated by plotEmbedding?
 
Thank you!

livius

**Comment by rcorces** [comment]
> I am trying to edit plots generated by plotEmbedding() in Illustrator.
When I make a plot that shows for example clustering and save that using
plotPDF(), I am unable to remove the labels of the clusters within that plot
(removing the text leaves holes and I don't see the points where the label was).

This should not be the case. These plots have complex clipping masks / groupings. If you remove the relevant clipping masks, then everything should be editable (except the points if you rasterized). The "holes" you are referring to presumably are the white halos around each cluster label.

> Could you add a parameter that allows to turn off the labels within the plot
generated by plotEmbedding?

This already exists. `plotEmbedding()` is a wrapper around `ArchR::ggPoint()`. The `...` in the parameter definition says "Additional parameters to pass to `ggPoint()` or `ggHex()`.". If you look at the parameters available to `ggPoint()` you will find the `labelMeans` paramter does exactly what you are looking for. Change this to `FALSE` to turn of cluster / group labels.

But again, your point above about illustrator should not be true.

**Comment by shaka87** [comment]
@rcorces - thank you for that answer. Maybe it might be useful to mention these two points 
(clipping masks and the parameters available to `ggPoint()`) in the ArchR tutorial.
