### ISSUE TITLE
HDF5 error: Object 'GeneScoreMatrix/chrX/x' does not exist in this HDF5 file.

### ISSUE THREAD

**Issue by rcorces** [GreenleafLab/ArchR#1290]
### Discussed in https://github.com/GreenleafLab/ArchR/discussions/1285

<div type='discussions-op-text'>

<sup>Originally posted by **bj-chen** February  9, 2022</sup>
Hi ArchR team,

I was trying to subset 5k cells from the original ArchR object which contains ~260K cells. However, I run into problems with the function getMarkerFeatures which gives the following error:

Error in .safelapply(seq_along(matchObj[[1]]), function(x) { : 
Error Found Iteration 3 : 
	[1] "Error in h5read(ArrowFile, paste0(useMatrix, \"/\", seqnamex, \"/x\")) : \n  Object 'GeneScoreMatrix/chrX/x' does not exist in this HDF5 file.\n"
	<simpleError in h5read(ArrowFile, paste0(useMatrix, "/", seqnamex, "/x")): Object 'GeneScoreMatrix/chrX/x' does not exist in this HDF5 file.>
Error Found Iteration 4 : 
	[1] "Error in h5read(ArrowFile, paste0(useMatrix, \"/\", seqnamex, \"/x\")) : \n  Object 'GeneScoreMatrix/chrX/x' does not exist in this HDF5 file.\n"
	<simpleError in h5read(ArrowFile, paste0(useMatrix, "/", seqnamex, "/x")): Object 'GeneScoreMatrix/chrX/x' does not exist in this HDF5 file.>
Calls: <Anonymous> ... getMarkerFeatures -> do.call -> <Anonymous> -> .safelapply
Execution halted

I attached the logfile and would really appreciate any help.

Thank you!

[ArchR-getMarkerFeatures-5f6e43f99ed2-Date-2022-02-10_Time-12-15-00.log](https://github.com/GreenleafLab/ArchR/files/8038281/ArchR-getMarkerFeatures-5f6e43f99ed2-Date-2022-02-10_Time-12-15-00.log)
</div>

**Comment by rcorces** [comment]
Hi @rcorces! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.

**Comment by rcorces** [comment]
@bj-chen - Its hard to know what is causing this. Maybe you did something weird in the subsetting and now you dont have any fragments on chromosome x? You can always manually inspect your HDF5 elements. If you want additional help, I think you need to provide far more context.

**Comment by bj-chen** [comment]
hi @rcorces, after excluding some samples with very few numbers of cells (1-10 cells per sample), the problem is now solved.
