### ISSUE TITLE
addIterativeLSI on GeneExpressionMatrix

### ISSUE THREAD

**Issue by Massimo-Petretich** [GreenleafLab/ArchR#1293]
Hi Jeff, Ryan,

I am trying to integrate a gex count matrix on an ArchR project with the purpose of generating peak to gene links.
Importantly, both the DNA and the RNA libraries come from a 10X multiome experiment (meaning that the each cell barcode can be univocally matched between the DNA and the RNA libraries). 
I have based my workflow on the tutorial provided at the link below (found from another post on issues).
https://greenleaflab.github.io/ArchR_2020/Ex-Analyze-Multiome.html

The dataset is composed of 4 different samples which were processed with cellranger count and further integrated with cellranger aggregate (which would make the dataset single sampled as far as ArchR is concerned, which is a very similar situation as the one described in the tutorial). I ensured that the sample name provided was the same at both arrow files generation and at import 10X feature matrix steps.

The workflow worked until ArchR::addGeneExpressionMatrix and failed at the addIterativeLSI step on the GeneExpressionMatrix.
I verified that the RNA count matrix and the depth col provided contained no NAs. Also I read carefully the documentation of the function and replaced 'variable' with 'Var' on the 'firstSelection' argument (the tutorial still mentions to specify 'variable', possibly this was changed in later ArchR releases, but anyway, the failure is the same in both cases).

In the log file I cannot see anything that suggests me an obvious explanation. Hopefully it may still provide some clues for the developers. Last, I am working with ArchR version 1.0.2 (not the master branch 1.0.1).

If you could think of any solution, even if it is a workaround I would really appreciate it. On a side note, as a workaround I also tried to perform the conventional scATAC-seq and scRNA-seq integration described in the full manual. In this case, I specified the constraint of interest with groupRNA and groupATAC arguments. It kind of works, but despite I specified this constraint, I get ~10% of the cells that are labeled in the wrong group. If you can think of a way to completely force this step not to assign cells to different groups, this could also be a viable solution for my problem.

I have read the few posts on issues regarding the multiome specific integration but haven't seen this specific issue. 

Best,
Massimo

x = addIterativeLSI(
    ArchRProj = x, 
    clusterParams = list(
      resolution = 0.2, 
      sampleCells = 10000,
      n.start = 10
    ),
    saveIterations = FALSE,
    useMatrix = "GeneExpressionMatrix", 
    depthCol = "Gex_nUMI",
    varFeatures = 2500,
    firstSelection = "Var",
    binarize = FALSE,
    name = "lsi_rna"
)

Checking Inputs...

ArchR logging to : ArchRLogs/ArchR-addIterativeLSI-9dfd6d7cc3ce-Date-2022-02-17_Time-09-29-34.log
If there is an issue, please report to github with logFile!

2022-02-17 09:29:34 : Computing Variability Across All Features, 0.001 mins elapsed.

2022-02-17 09:29:35 : Computing Variable Features, 0.022 mins elapsed.

###########
2022-02-17 09:29:36 : Running LSI (1 of 2) on Top Features, 0.036 mins elapsed.
###########

************************************************************
2022-02-17 09:29:36 : ERROR Found in .LSIPartialMatrix for  
LogFile = ArchRLogs/ArchR-addIterativeLSI-9dfd6d7cc3ce-Date-2022-02-17_Time-09-29-34.log

<simpleError in quantile.default(vals, probs = c(min(outlierQuantiles)/factor,     1 - ((1 - max(outlierQuantiles))/factor))): missing values and NaN's not allowed if 'na.rm' is FALSE>

************************************************************

Error in .logError(e, fn = ".LSIPartialMatrix", info = "", errorList = errorList, : Exiting See Error Above
Traceback:

1. addIterativeLSI(ArchRProj = x, clusterParams = list(resolution = 0.2, 
 .     sampleCells = 10000, n.start = 10), saveIterations = FALSE, 
 .     useMatrix = "GeneExpressionMatrix", depthCol = "Gex_nUMI", 
 .     varFeatures = 2500, firstSelection = "Var", binarize = FALSE, 
 .     name = "lsi_rna")
2. .LSIPartialMatrix(ArrowFiles = ArrowFiles, featureDF = topFeatures, 
 .     cellNames = cellNames, cellDepth = cellDepth, useMatrix = useMatrix, 
 .     sampleNames = getCellColData(ArchRProj)$Sample, LSIMethod = LSIMethod, 
 .     scaleTo = scaleTo, dimsToUse = dimsToUse, binarize = binarize, 
 .     outlierQuantiles = outlierQuantiles, sampleCells = if (j != 
 .         iterations) sampleCellsPre else sampleCellsFinal, projectAll = j == 
 .         iterations | projectCellsPre | sampleJ > sampleCellsPre, 
 .     threads = threads, useIndex = FALSE, seed = seed, tstart = tstart, 
 .     verbose = verbose, logFile = logFile)
3. tryCatch({
 .     if (is.null(sampleCells)) {
 .         .logDiffTime("Creating Partial Matrix", tstart, addHeader = FALSE, 
 .             verbose = verbose, logFile = logFile)
 .         mat <- .getPartialMatrix(ArrowFiles = ArrowFiles, featureDF = featureDF, 
 .             useMatrix = useMatrix, cellNames = cellNames, doSampleCells = FALSE, 
 .             threads = threads, verbose = FALSE, logFile = logFile)
 .         .logDiffTime("Computing LSI", tstart, addHeader = FALSE, 
 .             verbose = verbose, logFile = logFile)
 .         outLSI <- .computeLSI(mat = mat, LSIMethod = LSIMethod, 
 .             scaleTo = scaleTo, nDimensions = max(dimsToUse), 
 .             binarize = binarize, outlierQuantiles = outlierQuantiles, 
 .             verbose = FALSE, seed = seed, tstart = tstart, logFile = logFile)
 .         outLSI$LSIFeatures <- featureDF
 .         outLSI$corToDepth <- list(scaled = abs(cor(.scaleDims(outLSI[[1]]), 
 .             cellDepth[rownames(outLSI[[1]])]))[, 1], none = abs(cor(outLSI[[1]], 
 .             cellDepth[rownames(outLSI[[1]])]))[, 1])
 .     }
 .     else {
 .         sampledCellNames <- .sampleBySample(cellNames = cellNames, 
 .             sampleNames = sampleNames, cellDepth = cellDepth, 
 .             sampleCells = sampleCells, outlierQuantiles = outlierQuantiles, 
 .             factor = 2)
 .         .logDiffTime(sprintf("Sampling Cells (N = %s) for Estimated LSI", 
 .             length(sampledCellNames)), tstart, addHeader = FALSE, 
 .             verbose = verbose, logFile = logFile)
 .         .logDiffTime("Creating Sampled Partial Matrix", tstart, 
 .             addHeader = FALSE, verbose = verbose, logFile = logFile)
 .         o <- h5closeAll()
 .         if (!projectAll) {
 .             mat <- .getPartialMatrix(ArrowFiles = ArrowFiles, 
 .                 featureDF = featureDF, useMatrix = useMatrix, 
 .                 cellNames = sampledCellNames, doSampleCells = FALSE, 
 .                 threads = threads, verbose = FALSE, logFile = logFile)
 .             .logDiffTime("Computing Estimated LSI (projectAll = FALSE)", 
 .                 tstart, addHeader = FALSE, verbose = verbose, 
 .                 logFile = logFile)
 .             outLSI <- .computeLSI(mat = mat, LSIMethod = LSIMethod, 
 .                 scaleTo = scaleTo, nDimensions = max(dimsToUse), 
 .                 binarize = binarize, outlierQuantiles = outlierQuantiles, 
 .                 seed = seed, tstart = tstart, logFile = logFile)
 .             outLSI$LSIFeatures <- featureDF
 .             outLSI$corToDepth <- list(scaled = abs(cor(.scaleDims(outLSI[[1]]), 
 .                 cellDepth[rownames(outLSI[[1]])]))[, 1], none = abs(cor(outLSI[[1]], 
 .                 cellDepth[rownames(outLSI[[1]])]))[, 1])
 .         }
 .         else {
 .             tmpPath <- .tempfile(pattern = "tmp-LSI-PM")
 .             .logDiffTime(sprintf("Sampling Cells (N = %s) for Estimated LSI", 
 .                 length(sampledCellNames)), tstart, addHeader = FALSE, 
 .                 verbose = verbose, logFile = logFile)
 .             out <- .getPartialMatrix(ArrowFiles = ArrowFiles, 
 .                 featureDF = featureDF, useMatrix = useMatrix, 
 .                 cellNames = cellNames, doSampleCells = TRUE, 
 .                 sampledCellNames = sampledCellNames, tmpPath = tmpPath, 
 .                 useIndex = useIndex, threads = threads, verbose = FALSE, 
 .                 logFile = logFile)
 .             gc()
 .             .logDiffTime("Computing Estimated LSI (projectAll = TRUE)", 
 .                 tstart, addHeader = FALSE, verbose = verbose, 
 .                 logFile = logFile)
 .             outLSI <- .computeLSI(mat = out$mat, LSIMethod = LSIMethod, 
 .                 scaleTo = scaleTo, nDimensions = max(dimsToUse), 
 .                 binarize = binarize, outlierQuantiles = outlierQuantiles, 
 .                 seed = seed, tstart = tstart, logFile = logFile)
 .             tmpMatFiles <- out[[2]]
 .             rm(out)
 .             gc()
 .             threads2 <- 1
 .             .logDiffTime("Projecting Matrices with LSI-Projection (Granja* et al 2019)", 
 .                 tstart, addHeader = FALSE, verbose = verbose, 
 .                 logFile = logFile)
 .             pLSI <- .safelapply(seq_along(tmpMatFiles), function(x) {
 .                 .logDiffTime(sprintf("Projecting Matrix (%s of %s) with LSI-Projection", 
 .                   x, length(tmpMatFiles)), tstart, addHeader = FALSE, 
 .                   verbose = FALSE, logFile = logFile)
 .                 .projectLSI(mat = readRDS(tmpMatFiles[x]), LSI = outLSI, 
 .                   verbose = FALSE, tstart = tstart, logFile = logFile)
 .             }, threads = threads2) %>% Reduce("rbind", .)
 .             rmf <- file.remove(tmpMatFiles)
 .             outLSI$exlcude <- cellNames[which(cellNames %ni% 
 .                 rownames(pLSI))]
 .             outLSI$matSVD <- as.matrix(pLSI[cellNames[which(cellNames %in% 
 .                 rownames(pLSI))], ])
 .         }
 .         outLSI$LSIFeatures <- featureDF
 .         outLSI$corToDepth <- list(scaled = abs(cor(.scaleDims(outLSI[[1]]), 
 .             cellDepth[rownames(outLSI[[1]])]))[, 1], none = abs(cor(outLSI[[1]], 
 .             cellDepth[rownames(outLSI[[1]])]))[, 1])
 .     }
 .     outLSI
 . }, error = function(e) {
 .     errorList$outLSI <- if (exists("outLSI", inherits = FALSE)) 
 .         outLSI
 .     else "Error with outLSI!"
 .     errorList$matSVD <- if (exists("outLSI", inherits = FALSE)) 
 .         outLSI[[1]]
 .     else "Error with matSVD!"
 .     .logError(e, fn = ".LSIPartialMatrix", info = "", errorList = errorList, 
 .         logFile = logFile)
 . })
4. tryCatchList(expr, classes, parentenv, handlers)
5. tryCatchOne(expr, names, parentenv, handlers[[1L]])
6. value[[3L]](cond)
7. .logError(e, fn = ".LSIPartialMatrix", info = "", errorList = errorList, 
 .     logFile = logFile)
8. stop("Exiting See Error Above")

[ArchR-addIterativeLSI-9dfd15c05fa9-Date-2022-02-17_Time-09-28-58.log](https://github.com/GreenleafLab/ArchR/files/8089854/ArchR-addIterativeLSI-9dfd15c05fa9-Date-2022-02-17_Time-09-28-58.log)

**Comment by rcorces** [comment]
Hi @Massimo-Petretich! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.

**Comment by rcorces** [comment]
> The dataset is composed of 4 different samples which were processed with cellranger count and further integrated with cellranger aggregate

As far as I know, ArchR is not designed to handle input from cellranger aggr.

**Comment by Massimo-Petretich** [comment]
Hi,

Thank you for the comment. I understand what you are saying, and the fact that it is possible that this is the cause of the failure specifically at the level of RNA count matrix integration. 
The only thing I can add (which hopefully can be informative to you) is that I have been using ArchR in a few projects (including the one mentioned in this post) starting from a cellranger aggregate fragments file without any problem (except this specific case in which I needed to integrate the counts from the RNA libraries). Aggregate projects are just like single sample ones (just, the suffix is changed from -1 to -1/2/3/..., which never happened to me to be sufficient to confuse ArchR).

Best,
Massimo

**Comment by rcorces** [comment]
I see your point that it **should** work with aggr. I'm just not sure how all of the pieces of ArchR will work with aggr input. If you're saying that the integration has worked previously with aggr input, then I'm not entirely sure what the problem might be. We discourage use of aggr in general because ArchR performs parallel computation on Arrows and aggr reduces the number of Arrows available by combining samples unnecessarily.

I would try it without aggr and report back.

**Comment by Massimo-Petretich** [comment]
Hi, 

I have tried as suggested, on one of the individual samples without aggregation; in this case the addIterativeLSI proceeds without errors. 
I'll try to work without aggregation. 

Thanks for the valuable feedback.

Best,
Massimo
