### ISSUE TITLE
genomic coordinate of pdgfra gene

### ISSUE THREAD

**Issue by AnjaliC4** [GreenleafLab/ArchR#1295]
Hi, 

This is a minor detail: The hg38 genomic coordinate for pdgfra gene is chr4:54,229,127-54,298,245. However, in ArchR it seems to wrongly added in Hg38 genome. Could this be corrected please? Thanks.
<img width="941" alt="Screen Shot 2022-02-17 at 4 29 22 PM" src="https://user-images.githubusercontent.com/60046859/154573877-b5ac6c8a-8da0-40ca-88b2-5c8e808d66fd.png">

As a matter of fact, this coordinate does not match any of these either: 

<img width="907" alt="Screen Shot 2022-02-17 at 4 36 18 PM" src="https://user-images.githubusercontent.com/60046859/154574841-58277ace-2e07-4b67-8e85-291ea93ff3a5.png">

**Comment by rcorces** [comment]
Hi @AnjaliC4! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.

**Comment by rcorces** [comment]
ArchR does not have any role in specifying gene coordinates. We use BSGenome versions. If you dont like the gene coordinates used for the specific BSGenome that is associated with your project, you are welcome to forge your own gene annotation object.
