### ISSUE TITLE
How to get list of all featurs/marker genes that correspond to an specific block in the heatmap?

### ISSUE THREAD

**Issue by CSBioAzim** [GreenleafLab/ArchR#130]
I'm interested to get all maker names or at least the ones that show clear distinct patterns across different clusters. Is there any chance to get these markers? As an example in the heatmap below, I'm interested to know what is the name of the markers in the part that I'm highlighted with black line.

![image](https://user-images.githubusercontent.com/15929793/81574221-892a6300-9373-11ea-9d9f-6e8a2a661e28.png)

**Comment by jgranja24** [comment]
The marker summarized experiment output contains LFC and FDR amongst other things. To get the features you can use `returnMat=TRUE`.

**Comment by CSBioAzim** [comment]
@jgranja24 , thanks. The matrix is huge (2k rows). It's hard to spot specific part of the matrix that belong to specific block in the heatmap above.

**Comment by jgranja24** [comment]
You can use the LFC and FDR matrices in `seMarker` to identify which were related to which group.

**Comment by CSBioAzim** [comment]
@jgranja24 , thanks. Is there any way to plot only a specific part of the heatmap?

**Comment by jgranja24** [comment]
You would subset the heatmap and then have to use a heatmap plotting function such as pheatmap or ComplexHeatmp.

**Comment by CSBioAzim** [comment]
@jgranja24 thanks!
