### ISSUE TITLE
createArrowFiles Error

### ISSUE THREAD

**Issue by yangxueqianR** [GreenleafLab/ArchR#1302]
I hope to creating a zebrafish ArchRGenome, so I did it according to the tutorial, but I made a mistake when creating the arrow file,I don't know what the problem is, could you please tell me the reason for the error? Thank you very much.

Code:
```
> genomeAnnotation <- createGenomeAnnotation(genome = BSgenome.Drerio.UCSC.danRer11)
Getting genome..
Getting chromSizes..
Getting blacklist..
Blacklist not downloaded! Continuing without, be careful for downstream biases..

> geneAnnotation <- createGeneAnnotation(TxDb = TxDb.Drerio.UCSC.danRer11.refGene, OrgDb = org.Dr.eg.db)
Getting Genes..
  1835 genes were dropped because they have exons located on both strands
  of the same reference sequence or on more than one reference sequence,
  so cannot be represented by a single genomic range.
  Use 'single.strand.genes.only=FALSE' to get all the genes in a
  GRangesList object, or use suppressMessages() to suppress this message.
Determined Annotation Style = ENTREZID
Getting Exons..
Getting TSS..

> ArrowFiles <- createArrowFiles(
      inputFiles = files,
      sampleNames = names(files),
      minTSS = 4, 
      minFrags = 1000, 
      addTileMat = TRUE,
      addGeneScoreMat = TRUE,
      geneAnnotation = geneAnnotation,
      genomeAnnotation = genomeAnnotation
)
Found Gene Seqnames not in GenomeAnnotation chromSizes, Removing : chr1_KZ114838v1_alt,chr1_KZ114841v1_alt,chr1_KZ114846v1_alt,chr1_KZ114847v1_alt,chr1_KZ114998v1_alt,chr1_KZ115005v1_al...
ArchR logging to : ArchRLogs/ArchR-createArrows-2a212068c53-Date-2022-02-22_Time-14-43-18.log
If there is an issue, please report to github with logFile!
2022-02-22 14:43:19 : Batch Execution w/ safelapply!, 0 mins elapsed.
Attempting to index ./fragment/3.3hpf_1.fragments.tsv as tabix..
Attempting to index ./fragment/3.3hpf_2.fragments.tsv as tabix..
Attempting to index ./fragment/3.3hpf_3.fragments.tsv as tabix..
2022-02-22 14:43:20 : createArrowFiles has encountered an error, checking if any ArrowFiles completed..
ArchR logging successful to : ArchRLogs/ArchR-createArrows-2a212068c53-Date-2022-02-22_Time-14-43-18.log
Warning message:
In mclapply(..., mc.cores = threads, mc.preschedule = preschedule) :
  3 function calls resulted in an error
```

[ArchR-createArrows-2a212068c53-Date-2022-02-22_Time-14-43-18.log](https://github.com/GreenleafLab/ArchR/files/8114294/ArchR-createArrows-2a212068c53-Date-2022-02-22_Time-14-43-18.log)

**Comment by rcorces** [comment]
Hi @yangxueqianR! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.

**Comment by rcorces** [comment]
Unfortunately, non of the ArchR developers work with non-standard genomes. The genome you are showing has hundreds of what we would consider to be "non-standard" chromosomes. From your original (pre-edited) post, many of these chromosomes which exist in your TxDB object are on chromosomes that do not exist in your BSGenome object or chromSizes file. I imagine there is some incompatibility between the genome used for alignment and the custom genome you have created. You can search previous issues to try to find help but we dont have bandwidth to help users create their own custom genomes for their organism of interest.

**Comment by yangxueqianR** [comment]
Thank you for your reply. The non-standard genomes I created here are the same as the tutorials are downloaded from BiocManager.  Could it be that ArchR is not compatible with all the gene annotations and Genome annotations downloaded on BiocManager?

**Comment by rcorces** [comment]
No - other users have worked with non-standard genomes successfully. I'd encourage you to search the issue and discussion posts for relevant tips.

**Comment by yangxueqianR** [comment]
Ok, thank you very much for your reply. I'll try to search for it.

**Comment by hengbingao** [comment]
I have face the same problem? have you solved it?

**Comment by Melody-cell** [comment]
@rcorces , i have encountered the same problem,
can you guide me to the issue and discussion posts that other users have worked with non-standard genomes successfully, cause i didn't find it ?
Thanks a lot!
