### ISSUE TITLE
Retrieve k-means ordering from peak2GeneHeatmap

### ISSUE THREAD

**Issue by pthakore27** [GreenleafLab/ArchR#132]
I was following the explanation of plotting a heatmap of peak-to-gene links in Section 15.3 of the user manual and thought it would be great to be able to annotate the resulting heat map with genes or peaks of interest. Is there a way to retrieve the k-means ordering and/or cluster identity from calling the peak2GeneHeatmap function?

**Comment by jgranja24** [comment]
Hi @pthakore27,

There currently is no feature for this. It is a good suggestion, I can add it in the next day or so.

**Comment by pthakore27** [comment]
Thank you for both adding this and making such a great analysis tool!

**Comment by CSBioAzim** [comment]
@jgranja24 Is this feature already there?

**Comment by jgranja24** [comment]
This should now be available in master.

**Comment by CSBioAzim** [comment]
@jgranja24 , thanks!

**Comment by CSBioAzim** [comment]
@rcorces @jgranja24 I was wondering is it possible to get this matrix for the trajectory heatmap as well?
