### ISSUE TITLE
A small bug in .identifyReproduciblePeaks

### ISSUE THREAD

**Issue by xuzhougeng** [GreenleafLab/ArchR#1324]
Bug information:

```
************************************************************
2022-03-09 10:57:33 : ERROR Found in .identifyReproduciblePeaks for Rep. Peaks Group (1 of 11) : 
LogFile = ArchRLogs/ArchR-addReproduciblePeakSet-2360812a70248b-Date-2022-03-09_Time-10-56-04.log

<simpleError in resize(summits, extendSummits * 2 + 1, "center"): unused argument ("center")>

2022-03-09 10:57:33 : errorList, Class = list
```

This error is due to the R language's inability to properly pick the `resize` function for  `summits` object

I find the webshot also have a `resize` function, and apparently R use the resize function from webshot rather than resize from GenomicRanges.

It could be fixed to replace `resize` to  `GenomicRanges::resize` in  https://github.com/GreenleafLab/ArchR/blob/master/R/ReproduciblePeakSet.R

**Comment by rcorces** [comment]
Hi @xuzhougeng! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.

**Comment by rcorces** [comment]
Thanks for the pull request. There are a lot of other places where `resize()` is called outside of that code. I've fixed it in all of the locations where I found it.
