### ISSUE TITLE
Identifying differential cellular states using control scATAC landscape

### ISSUE THREAD

**Issue by CSBioAzim** [GreenleafLab/ArchR#134]
I was thinking that having the features that identify differential cellular states by projecting the case cells into the control scATAC landscape. This would be really amazing in differential analysis, trajectory, etc. Do you think you will have time to add this functionality?

**Comment by jgranja24** [comment]
This is beyond the scope at the moment of what we intended to support. We will consider this in the future. I am closing this issue for now, but we will consider this down the line.
