### ISSUE TITLE
Not actually a bug (just a question): Cells with no reads in any of the top 25k informative features.

### ISSUE THREAD

**Issue by dagarfield** [GreenleafLab/ArchR#1343]
I think ArchR's implementation of iterative LSI is the greatest thing since sliced bread for feature selection in an ATAC dataset. 
Looking through the code, I found something I don't quite understand in the ProjectLSI part of the code. 

The LSI itself is constructed using top features, which leads to the (probably rare) situation that a cell could be a valid cell but still not have any reads in the top, say, 25,000 most variable features. 

https://github.com/GreenleafLab/ArchR/blob/968e4421ce7187a8ac7ea1cf6077412126876d5f/R/IterativeLSI.R#L1269-L1273

This is probably sensible, but does it lead downstream to the possibility that valid cells don't get incorporated into the LSI projection (and thus fall out of downstream steps like UMAP and clustering)? 

This came up because I modified the code to better run on peak matrices. Support for my hackery is well outside the range of support, but curious if I am correct in this observation. Or if I've managed to fub up something.

**Comment by rcorces** [comment]
Hi @dagarfield! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.

**Comment by dagarfield** [comment]
Moving to discussion!
