### ISSUE TITLE
correlateMatrices with homer motif-matrix

### ISSUE THREAD

**Issue by pthakore27** [GreenleafLab/ArchR#135]
Hello, I was following the manual section 15.4 Identification of Positive TF-Regulators, using a motif matrix derived from the homer database. When I got to the step of calling correlateMatrices on the GeneScoreMatrix and my homer-derived motif_matrix, I received an error that no names matched between the two matrices. I believe this is because of the way homer motifs names are annotated (for ex. Atf2 = Atf2.bZIP_11). correlateMatrices seems to be able to parse underscores in TF names, but not "." characters. Could this be added as an option to allow for matches between homer motifs and gene names? 

Alternatively, I tried loading the homer-derived motif_matrix myself and reformatting the motif names in the rowData of the resulting Summarized Experiment, but I did not know how to load this modified motif matrix back into the ArchR project. Any guidance there would be appreciated! 

[ArchR-correlateMatrices-64e227d0b098-Date-2020-05-12_Time-18-08-32.log](https://github.com/GreenleafLab/ArchR/files/4618132/ArchR-correlateMatrices-64e227d0b098-Date-2020-05-12_Time-18-08-32.log)

**Comment by jgranja24** [comment]
This has been added to the dev branch with dot removal. Let me know if this helps. To install the dev branch -

devtools::install_github(
  "GreenleafLab/ArchR", 
  ref="dev_051120", 
  repos = BiocManager::repositories()
)

**Comment by rcorces** [comment]
@pthakore27 - please re-open if your issue persists.

**Comment by trinevd** [comment]
Hello. 
I have the same problem. 
I am using ArchR v. 1.0.2   , but I also tried to run the command after running devtools::install_github("GreenleafLab/ArchR", ref="master", repos = BiocManager::repositories())


Best,
Trine

**Comment by rcorces** [comment]
See the function documentation for `correlateMatrices()`. Specifically, the `removeFromName` params
https://github.com/GreenleafLab/ArchR/blob/968e4421ce7187a8ac7ea1cf6077412126876d5f/R/IntegrativeAnalysis.R#L14-17
