### ISSUE TITLE
'problem too large' error when calling the getMatrixFromProject() function

### ISSUE THREAD

**Issue by bj-chen** [GreenleafLab/ArchR#1353]
Dear ArchR team,

I recently encountered a 'problem too large' error when trying to extract the gene score matrix using the getMatrixFromProject() function. There are over 250K cells and over 90 clusters in my dataset. My code reads:

GeneScoreMatrix <- getMatrixFromProject(
  ArchRProj = someArchRProject,
  useMatrix = "GeneScoreMatrix")

I've attached the log file for your reference. Would really appreciate any advice on how to solve the problem. Thank you in advance.

With regards,
Bei Jun
[ArchR-getMatrixFromProject-28c275c722db-Date-2022-03-16_Time-15-03-54.log](https://github.com/GreenleafLab/ArchR/files/8329447/ArchR-getMatrixFromProject-28c275c722db-Date-2022-03-16_Time-15-03-54.log)

**Comment by rcorces** [comment]
Hi @bj-chen! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.

**Comment by rcorces** [comment]
addressed previously. Please search issues before posting.
https://github.com/GreenleafLab/ArchR/issues/650

**Comment by bj-chen** [comment]
@rcorces: my apologies for the repeated posting. Will definitely search addressed issues before posting next time. Thank you!
