### ISSUE TITLE
Full tutorial not available (link= 404 error no found) 

### ISSUE THREAD

**Issue by SaharBJ** [GreenleafLab/ArchR#1356]
Good day 

When I click on the link available in the quick tutorial page I am not able to access the full tutorial. I have been having issues with getting tutorial data and creating arrow files and would like to review the full tutorial to get a better understanding. 

Warmly
Sahar

**Comment by rcorces** [comment]
Hi @SaharBJ! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.

**Comment by SaharBJ** [comment]
Good day

1. Yes
2. Please see attached images. When trying the code provided here:
https://rdrr.io/github/GreenleafLab/ArchR/src/R/InputData.R#sym-getTutorialData
I received the output in the second image.
3. I have not managed to successfully create a log file.

Warmly
Sahar

**Comment by rcorces** [comment]
Thanks for pointing out that the link is broken. I will fix it in an upcoming release.
The full manual is here - https://www.archrproject.com/bookdown/index.html
