### ISSUE TITLE
Problem with normalization in MarkerFeatures

### ISSUE THREAD

**Issue by rcorces** [GreenleafLab/ArchR#1363]
### Discussed in https://github.com/GreenleafLab/ArchR/discussions/1362

<div type='discussions-op-text'>

<sup>Originally posted by **anastasiya-pendragon** March 31, 2022</sup>
Hello there! First of all, thank you so much for this amazing package! It makes analysis way easier, especially for beginners like me.

I've noticed something in the MarkerFeatures function, that seems wrong to me. It concerns normalization. 
https://github.com/GreenleafLab/ArchR/blob/506161d36d1457d4b3aba20918c0e4f622ae937e/R/MarkerFeatures.R#L206-L226
Specifically lines 223 and 224. As it is right now, it seems that if normBy is set to any character value and is not "none", the same normalization would be done, no matter what was specified as the desired normalization column. I tried to run it with different normBy parameters (without changing anything else) and the results are always the same. I would think that maybe these lines simply need to be replaced by 
```
normFactors <- getCellColData(ArchRProj, normBy, drop=FALSE)            
normFactors[,1] <- median(normFactors[,1]) / normFactors[,1]
```
Or maybe there has to be an additional check on what matrix and/or test is used. 

I checked both issues and discussions and the same code snippet was talked about here: https://github.com/GreenleafLab/ArchR/discussions/1168#discussioncomment-1662307, but in a different context, so I thought this might deserve a new discussion. 

If I'm misinterpreting or missing something in the code, please let me know. 
The code snippet is from the 1.0.2 branch but it is the same in previous versions. 

For now, my workaround has been to set ReadsInTSS to nFrags and normBy to null, and after the analysis undo the changes. 

Thank you for your time! 

Looking forward to hearing from you, 
Anastasiya</div>

**Comment by rcorces** [comment]
Hi @rcorces! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.

**Comment by anastasiya-pendragon** [comment]
Hello, thank you for the quick reply! The patch works as expected. 
Though I could only install it with ref="dev_normBy". Just to double-check: isn't master referencing the stable 1.0.1 version without the new commits to 1.0.2?

**Comment by rcorces** [comment]
sorry. copy-paste error. I fixed it in my original post.

**Comment by rcorces** [comment]
I've merged this into `release_1.0.2`. If anything else related comes up, feel free to post here.
https://github.com/GreenleafLab/ArchR/pull/1365
