### ISSUE TITLE
additional arguments for TFBSTools:getMatrixSet() in addMotifAnnotations()

### ISSUE THREAD

**Issue by LornaWessels** [GreenleafLab/ArchR#1367]
As asked by @rcorces I'm opening this issue following the JASPAR annotation discussion #1344:

The `TFBSTools::getMatrixSet()` function has the argument "name" which allows filtering of motif sets by the names of the TFs.
However, this is not possible with `addMotifAnnotations()` since the argument "name" is already used by ArchR for the name of the stored annotation.

https://github.com/GreenleafLab/ArchR/blob/968e4421ce7187a8ac7ea1cf6077412126876d5f/R/AnnotationPeaks.R#L259-L272

https://github.com/GreenleafLab/ArchR/blob/968e4421ce7187a8ac7ea1cf6077412126876d5f/R/AnnotationPeaks.R#L332-L337

As a work-around I extracted the PWMatrixList of the desired JASPAR TFs with TFBSTools and passed it to `addMotifAnnotations()` as motifPMWs.
But having this filtering by name option in the ArchR function would be super convenient. 

Best,
Lorna

**Comment by rcorces** [comment]
Hi @LornaWessels! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.

**Comment by rcorces** [comment]
I made this change on a new branch called `dev_annoName` via https://github.com/GreenleafLab/ArchR/commit/231f5eacd5fb5a25d7b20077fd28b9600b460257. I changed the `name` param to `annoName`.
Could you test this on your end and make sure it works for you?

You can install this branch via:
```
devtools::install_github("GreenleafLab/ArchR", ref="dev_annoName", repos = BiocManager::repositories())
```
Then restart R and reload ArchR

**Comment by LornaWessels** [comment]
Hi Ryan, 

I just ran a test. It works perfectly fine! 
Thank you very much!

**Comment by rcorces** [comment]
thanks for confirming. This has been merged into `release_1.0.2`
https://github.com/GreenleafLab/ArchR/pull/1369

**Comment by rcorces** [comment]
@NoemieL - The function references on the webpage are for ArchR v1.0.1 which is reflected in the upper left of the page header. These dont get updated until we commit a stable release which has not happened yet for the `release_1.0.2` branch. Once that does happen, the documentation on the function ref page will automatically update.

**Comment by NoemieL** [comment]
Ok perfect! And what about CISBP annotation? is annoName specific to JASPAR?

**Comment by rcorces** [comment]
In `release_1.0.2`, there is no longer a `name` param so that one can pass `name` to `TFBSTools::getMatrixSet`. This is only used when using JASPAR, which I have clarified via
https://github.com/GreenleafLab/ArchR/commit/7ead5412657ca1d21b5f874e2908c8d920e977cb

if you dont pass `annoName` then it will just use the default, which is why it works when you use `name` (which is ignored without JASPAR but also never used as the name of the motif annotation object in `release_1.0.2`).
