### ISSUE TITLE
Error computing coaccessibility in tutorial

### ISSUE THREAD

**Issue by concatenize** [GreenleafLab/ArchR#137]
When I make browser plots on the latest ArchR version, I get a partial plot, but the coaccessibility loops give "Error: discrete value supplied to continuous scale". When I look at the values, I see that all the correlations are TRUE instead of numeric. 

**Logs**

[ArchR-plotBrowserTrack-17ecb684fbab4-Date-2020-05-12_Time-17-07-49.log](https://github.com/GreenleafLab/ArchR/files/4618516/ArchR-plotBrowserTrack-17ecb684fbab4-Date-2020-05-12_Time-17-07-49.log)

[ArchR-addCoAccessibility-17ecb33c59398-Date-2020-05-12_Time-17-05-26.log](https://github.com/GreenleafLab/ArchR/files/4618519/ArchR-addCoAccessibility-17ecb33c59398-Date-2020-05-12_Time-17-05-26.log)

**To Reproduce**

This script should reproduce the bug.

[loops.R.txt](https://github.com/GreenleafLab/ArchR/files/4618534/loops.R.txt)

**Expected behavior**

Correlation values should be numeric, varied, and between -1 and 1. Loops should show up in the browser. Thank you!!

**Comment by jgranja24** [comment]
What is the output of 
`
metadata(projHeme1@peakSet)$CoAccessibility
`
Thanks

Jeff

**Comment by concatenize** [comment]
Thanks for the quick response! I get the following output:

```
DataFrame with 1546789 rows and 4 columns
        queryHits subjectHits seqnames correlation
        <integer>   <integer>    <Rle>   <logical>
1               1           2     chr1        TRUE
2               1           3     chr1        TRUE
3               2           1     chr1        TRUE
4               2           3     chr1        TRUE
5               2           4     chr1        TRUE
...           ...         ...      ...         ...
1546785    123495      123496     chrX        TRUE
1546786    123496      123494     chrX        TRUE
1546787    123496      123495     chrX        TRUE
1546788    123497      123498     chrX        TRUE
1546789    123498      123497     chrX        TRUE
```

**Comment by jgranja24** [comment]
awww ok thats weird im going to look into this

**Comment by jgranja24** [comment]
I just pushed a commit in the dev branch to better diagnose this problem. Can you install re-run and put the new log file here.

devtools::install_github(
"GreenleafLab/ArchR",
ref="dev_051120",
repos = BiocManager::repositories()
)

**Comment by concatenize** [comment]
If I load my previous object and only re-run `addCoAccessibility`, I have the same issue (log attached). I am running the whole script now from the start to see if it depends on e.g. peak calling.

[ArchR-addCoAccessibility-14bd620247405-Date-2020-05-13_Time-16-46-28.log](https://github.com/GreenleafLab/ArchR/files/4624616/ArchR-addCoAccessibility-14bd620247405-Date-2020-05-13_Time-16-46-28.log)

**Comment by concatenize** [comment]
Here are all the logs from a clean run with ArchR version `dev_051120`.

[ArchR-plotBrowserTrack-14bd67f6bd754-Date-2020-05-13_Time-17-29-24.log](https://github.com/GreenleafLab/ArchR/files/4624803/ArchR-plotBrowserTrack-14bd67f6bd754-Date-2020-05-13_Time-17-29-24.log)
[ArchR-plotBrowserTrack-14bd6388a4ba3-Date-2020-05-13_Time-17-29-18.log](https://github.com/GreenleafLab/ArchR/files/4624804/ArchR-plotBrowserTrack-14bd6388a4ba3-Date-2020-05-13_Time-17-29-18.log)
[ArchR-addCoAccessibility-14bd63ab8c4f3-Date-2020-05-13_Time-17-27-13.log](https://github.com/GreenleafLab/ArchR/files/4624805/ArchR-addCoAccessibility-14bd63ab8c4f3-Date-2020-05-13_Time-17-27-13.log)
[ArchR-addPeakMatrix-14bd6726e97ee-Date-2020-05-13_Time-17-24-10.log](https://github.com/GreenleafLab/ArchR/files/4624806/ArchR-addPeakMatrix-14bd6726e97ee-Date-2020-05-13_Time-17-24-10.log)
[ArchR-addIterativeLSI-14bd633b23ffe-Date-2020-05-13_Time-17-18-59.log](https://github.com/GreenleafLab/ArchR/files/4624807/ArchR-addIterativeLSI-14bd633b23ffe-Date-2020-05-13_Time-17-18-59.log)
[ArchR-addReproduciblePeakSet-14bd65502b4f4-Date-2020-05-13_Time-16-58-10.log](https://github.com/GreenleafLab/ArchR/files/4624808/ArchR-addReproduciblePeakSet-14bd65502b4f4-Date-2020-05-13_Time-16-58-10.log)
[ArchR-addGroupCoverages-14bd6393d04bf-Date-2020-05-13_Time-16-49-08.log](https://github.com/GreenleafLab/ArchR/files/4624809/ArchR-addGroupCoverages-14bd6393d04bf-Date-2020-05-13_Time-16-49-08.log)

**Comment by jgranja24** [comment]
Hmmm it looks like the correlation is the issue thanks for this info I will think of a way to test this.

**Comment by jgranja24** [comment]
Can you try the following -

```

set.seed(1)
mat1 <- matrix(rnorm(10000, 10), 100, 100)
mat2 <- matrix(rnorm(10000, 10), 100, 100)
corVals <- ArchR:::rowCorCpp(1:100, 1:100, mat1, mat2)
mean(corVals)
median(corVals)
sd(corVals)


```

**Comment by concatenize** [comment]
Yes -- here are the results.

```
> set.seed(1)
> mat1 <- matrix(rnorm(10000, 10), 100, 100)
> mat2 <- matrix(rnorm(10000, 10), 100, 100)
> corVals <- ArchR:::rowCorCpp(1:100, 1:100, mat1, mat2)
> mean(corVals)
[1] 0.002848388
> median(corVals)
[1] 0.00615962
> sd(corVals)
[1] 0.1050334
```

**Comment by jgranja24** [comment]
Sorry again for the delays. I have been trying to figure this out. Can you try again on the dev branch. I just added a few checks. Somehow your correlation function is becoming logical.
