### ISSUE TITLE
addGroupCoverage() error: Error in (function (..., threads = 1, preschedule = FALSE)  

### ISSUE THREAD

**Issue by sylestiel** [GreenleafLab/ArchR#1370]
> projSix2 <- addGroupCoverages(ArchRProj = projSix2, groupBy = "Clusters", force = TRUE)
ArchR logging to : ArchRLogs/ArchR-addGroupCoverages-17b9314a3a67f-Date-2022-04-02_Time-13-57-45.log
If there is an issue, please report to github with logFile!
2022-04-02 13:57:46 : Creating Coverage Files!, 0.017 mins elapsed.
2022-04-02 13:57:46 : Batch Execution w/ safelapply!, 0.017 mins elapsed.
Error in (function (..., threads = 1, preschedule = FALSE)  : 
Error Found Iteration 2 : 
	[1] "Error in .width_as_unnamed_integer(width) : \n  each range must have a non-negative width\n"
	<simpleError in .width_as_unnamed_integer(width): each range must have a non-negative width>
Error Found Iteration 4 : 
	[1] "Error in .width_as_unnamed_integer(width) : \n  each range must have a non-negative width\n"
	<simpleError in .width_as_unnamed_integer(width): each range must have a non-negative width>
Error Found Iteration 6 : 
	[1] "Error in .width_as_unnamed_integer(width) : \n  each range must have a non-negative width\n"
	<simpleError in .width_as_unnamed_integer(width): each range must have a non-negative width>
Error Found Iteration 7 : 
	[1] "Error in .width_as_unnamed_integer(width) : \n  each range must have a non-negative width\n"
	<simpleError in .width_as_unnamed_integer(width): each range must have a non-negative width>
Error Found Iteration 8 : 
	[1] "Error in .width_as_unnamed_integer(width) : \n  each range must have a non-ne
In addition: Warning message:
In mclapply(..., mc.cores = threads, mc.preschedule = preschedule) :
  7 function calls resulted in an error

> traceback()
5: stop(errorMsg)
4: (function (..., threads = 1, preschedule = FALSE) 
   {
       if (tolower(.Platform$OS.type) == "windows") {
           threads <- 1
       }
       if (threads > 1) {
           .requirePackage("parallel", source = "cran")
           o <- mclapply(..., mc.cores = threads, mc.preschedule = preschedule)
           errorMsg <- list()
           for (i in seq_along(o)) {
               if (inherits(o[[i]], "try-error")) {
                   capOut <- utils::capture.output(o[[i]])
                   capOut <- capOut[!grepl("attr\\(\\,|try-error", 
                     capOut)]
                   capOut <- head(capOut, 10)
                   capOut <- unlist(lapply(capOut, function(x) substr(x, 
                     1, 250)))
                   capOut <- paste0("\t", capOut)
                   errorMsg[[length(errorMsg) + 1]] <- paste0(c(paste0("Error Found Iteration ", 
                     i, " : "), capOut), "\n")
    ...
3: do.call(.safelapply, args)
2: .batchlapply(args)
1: addGroupCoverages(ArchRProj = projSix2, groupBy = "Clusters", 
       force = TRUE
[ArchR-addGroupCoverages-17b9314a3a67f-Date-2022-04-02_Time-13-57-45.log](https://github.com/GreenleafLab/ArchR/files/8403233/ArchR-addGroupCoverages-17b9314a3a67f-Date-2022-04-02_Time-13-57-45.log)
)

**Comment by rcorces** [comment]
Hi @sylestiel! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.

**Comment by rcorces** [comment]
Hard to know where this is coming from. The error is very explicit and comes from IRanges. Some width of one of your fragments must be negative. I would check your input fragment files to make sure that they dont have any fragments with a negative width. If that isnt true, then I would run `getFragmentsFromProject()` for each of your groups and check that those fragments dont have any negative widths.

**Comment by sylestiel** [comment]
I think one of my saved files got corrupted. It seems to be working now. Thanks!
