### ISSUE TITLE
Problem about creatArrowFiles

### ISSUE THREAD

**Issue by hahahah-single** [GreenleafLab/ArchR#1372]
When I use creatArrowFiles function I meet the warning The index file is older than the data file ：fragment.tsv.gz.tbi.I would like to ask what is the reason for this and can i ignore this？The reference genome is hg38

**Comment by rcorces** [comment]
Hi @hahahah-single! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.

**Comment by rcorces** [comment]
That is an odd error to get but the solution seems simple. Just delete the `fragment.tsv.gz.tbi` file and try again. ArchR will automatically index your fragment files if a tabix index is not found. I'm closing this for now but feel free to post again here if this doesnt solve your problem.

**Comment by ssusan6** [comment]
> That is an odd error to get but the solution seems simple. Just delete the `fragment.tsv.gz.tbi` file and try again. ArchR will automatically index your fragment files if a tabix index is not found. I'm closing this for now but feel free to post again here if this doesnt solve your problem.

Thanks for the fantastic package. I encountered the same warning when the time of downloading fragment.tsv.gz.tbi is earlier than the time of downloading fagment.tsv.gz. When I downloaded fragment.tsv.gz.tbi file later than fragment.tsv.gz file, the error solved.
