### ISSUE TITLE
Error in getTrajectory

### ISSUE THREAD

**Issue by aselewa** [GreenleafLab/ArchR#138]
Hi all,

I get the following error when trying to create a trajectory heatmap. I was able to run `addTrajectory()` without any issues. The only other analyses I have ran on this ArchR project is filtering doublets, iterativeLSI, umap/clustering. Thanks for your help.

```
trajGS  <- getTrajectory(ArchRProj = projOrganoids, name = "trajectory1", useMatrix = "GeneScoreMatrix", log2Norm = TRUE)
Creating Trajectory Group Matrix..
Smoothing...
Error in .validate_names(colnames, ans_colnames, "assay colnames()", "colData rownames()") : 
  assay colnames() must be NULL or identical to colData rownames()
```

**Comment by jgranja24** [comment]
I just pushed a commit in the dev branch to better diagnose this problem. Can you install re-run and let me know if it works. I havent added logging to this function as of yet.

devtools::install_github(
"GreenleafLab/ArchR",
ref="dev_051120",
repos = BiocManager::repositories()
)

**Comment by aselewa** [comment]
This resolved my issue. Thank you.

**Comment by aselewa** [comment]
Hi, I am reopening this because I have another similar error:

```
trajGS  <- getTrajectory(ArchRProj = projOrganoids, name = "trajectory1", useMatrix = "GeneIntegrationMatrix", log2Norm = TRUE)
Creating Trajectory Group Matrix..
Error in if (any(groupMat < 0)) { : missing value where TRUE/FALSE needed
```

I am trying to use the Gene Integration Matrix. I was able to do the integration using a Seurat object without any problems. I'd like to use the associated gene expression for pseudotime.

**Comment by jgranja24** [comment]
ok happy to look more into this, I may add logging to this function.

**Comment by aselewa** [comment]
Was able to fix this by setting the default assay in the Seurat object to "RNA". The problem was that the default assay is "SCT" which is the normalized RNA-seq. addIntegrationGeneMatrix() tries to normalize already normalized data, leading to NAs.
