### ISSUE TITLE
projectBulkATAC error incosistency found with matching LSI dimensions

### ISSUE THREAD

**Issue by cschmidl** [GreenleafLab/ArchR#1380]
Hello,

I encountered a problem with projectBulkATAC that I could NOT reproduce with the testdataset.

When I use projectBulkATAC on my data, the function runs through the bulk samples but then gives an error:
Error incosistency found with matching LSI dimensions to those used in addEmbedding
Returning with simulated reduced dimension coordinates...

This is the only thing the function returns
List of length 1
names(1): simulatedReducedDims

I attached the logfile and would appreciate your help a lot!

Thank you very much!

[ArchR-projectBulkATAC-a4b73087b2ac-Date-2022-04-07_Time-16-13-23.log](https://github.com/GreenleafLab/ArchR/files/8443782/ArchR-projectBulkATAC-a4b73087b2ac-Date-2022-04-07_Time-16-13-23.log)

**Comment by rcorces** [comment]
I cant tell if this is potentially related to your other post.

**Comment by rcorces** [comment]
I'm closing this since we are dealing with it on your other post https://github.com/GreenleafLab/ArchR/issues/1379
