### ISSUE TITLE
plotBrowserTrack()

### ISSUE THREAD

**Issue by woshiyangsi** [GreenleafLab/ArchR#1384]
Hello,
I encountered a problem with plotBrowserTrack() that I could not adjust width of ordinate.

![image](https://user-images.githubusercontent.com/54662832/163210272-f9b2a89a-b905-4070-8778-cc5ce5a6459a.png)

**Comment by rcorces** [comment]
Hi @woshiyangsi! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
If I'm interpreting your question correctly, you want to make the height of the bulk track shorter. this is controlled with the `sizes` parameter. Please note that the Issues section is reserved for bugs and error reports. If you wish to submit usage questions, use the Discussions section. If you think something is actually a bug, please provide a full and clear bug report.
