### ISSUE TITLE
Error not all cellNames found in partialMatrix

### ISSUE THREAD

**Issue by phoebe-yg** [GreenleafLab/ArchR#1389]
devtools::install_github("GreenleafLab/ArchR", ref="master", repos = BiocManager::repositories())

[ArchR-addIterativeLSI-dc1fda54c7-Date-2022-04-18_Time-09-26-08.log](https://github.com/GreenleafLab/ArchR/files/8507673/ArchR-addIterativeLSI-dc1fda54c7-Date-2022-04-18_Time-09-26-08.log)

**Describe the bug**
Under ArchR release 1.0.2, I ran the code below to do dimension reduction on GEX matrix from multiome assay. However, I ran into the error below. Based on the previous discussion, this bug should be fixed under release 1.0.2. But it doesn't work in my case.

```
***********************************************************
2022-04-18 12:35:11 : ERROR Found in .LSIPartialMatrix for  
LogFile = ArchRLogs/ArchR-addIterativeLSI-dc206cdd8e-Date-2022-04-18_Time-12-34-57.log

<simpleError in .getPartialMatrix(ArrowFiles = ArrowFiles, featureDF = featureDF,     useMatrix = useMatrix, cellNames = sampledCellNames, doSampleCells = FALSE,     threads = threads, verbose = FALSE, logFile = logFile): Error not all cellNames found in partialMatrix>

************************************************************
Error in .logError(e, fn = ".LSIPartialMatrix", info = "", errorList = errorList, : Exiting See Error Above

```
**To Reproduce**
Here's the commands
```
proj <- addIterativeLSI(
    ArchRProj = proj, 
    clusterParams = list(
      resolution = 0.2, 
      sampleCells = 10000,
      n.start = 10
    ),
    saveIterations = FALSE,
    useMatrix = "GeneExpressionMatrix", 
    depthCol = "Gex_nUMI",
    varFeatures = 2500,
    firstSelection = "variable",
    binarize = FALSE,
    name = "LSI_RNA",
    force = F
)

```
**Expected behavior**
This should do dimension reduction on RNA data.

**Comment by rcorces** [comment]
Hi @phoebe-yg! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by phoebe-yg** [comment]
Hi @rcorces, Thanks for your reply! To your points:

1. Yes! I have searched and read about the previous issue [here](https://github.com/GreenleafLab/ArchR/issues/638). The solution in the thread did not help.
2. I can't creare arrow file from the tutorial data in my environment. Here's the error:
```
************************************************************
2022-04-18 13:09:24 : ERROR Found in .tabixToTmp for (PBMC_10k : 1 of 1) 
LogFile = ArchRLogs/ArchR-createArrows-140c290d6f35-Date-2022-04-18_Time-13-09-23.log

<simpleError in H5Fcreate(file): HDF5. File accessibilty. Unable to open file.>

************************************************************
```

3. I linked my error file.

Thanks for looking into this!

**Comment by rcorces** [comment]
See https://github.com/GreenleafLab/ArchR/issues/1286 specifically https://github.com/GreenleafLab/ArchR/issues/1286#issuecomment-1076653137 and subsequent comments

**Comment by phoebe-yg** [comment]
Problem solved. Thank you!
