### ISSUE TITLE
getMarkerFeatures bias argument

### ISSUE THREAD

**Issue by Brawni** [GreenleafLab/ArchR#139]
Hi!

Thanks again for this great package!

I would like to run getMarkerFeatures using the chromvar deviations. It does run without problem but if i change the bias like the following it throws an error. 
```

> DAM <- getMarkerFeatures(
+     ArchRProj = archp, 
+     useMatrix = "MotifMatrix", 
+     groupBy = "Clusters",
+   bias = c("log10(nFrags)"),
+   testMethod = "wilcoxon"
+ )
ArchR logging to : ArchRLogs/ArchR-getMarkerFeatures-381c79426e4c-Date-2020-05-14_Time-04-12-22.log
If there is an issue, please report to github with logFile!
2020-05-14 04:12:23 : When accessing features from a matrix of class Sparse.Assays.Matrix it requires 1 seqname!
Continuing with first seqname 'deviations'!
If confused, try getSeqnames(ArchRProj, 'MotifMatrix'') to list out available seqnames for input!
2020-05-14 04:12:23 : Matching Known Biases, 0.002 mins elapsed.
Error in .validInput(input = data, name = "data", valid = c("dataframe",  : 
  Input value for 'data' is not a dataframe,matrix, (data = numeric) please supply valid input!
```
Thanks a lot!
[ArchR-getMarkerFeatures-381c79426e4c-Date-2020-05-14_Time-04-12-22.log](https://github.com/GreenleafLab/ArchR/files/4626038/ArchR-getMarkerFeatures-381c79426e4c-Date-2020-05-14_Time-04-12-22.log)

**Comment by jgranja24** [comment]
I think i fixed it in the dev version if you can try it out
```

devtools::install_github(
"GreenleafLab/ArchR",
ref="dev_051120",
repos = BiocManager::repositories()
)


```

Best

jeff

**Comment by Brawni** [comment]
Hi Jeff,

It generates another error now:

```
> DAM <- getMarkerFeatures(
+     ArchRProj = archp, 
+     useMatrix = "MotifMatrix", 
+     groupBy = "Clusters",
+   bias = "log10(nFrags)",
+   testMethod = "wilcoxon"
+ )
ArchR logging to : ArchRLogs/ArchR-getMarkerFeatures-3359269781a2-Date-2020-05-14_Time-13-53-59.log
If there is an issue, please report to github with logFile!
2020-05-14 13:54:00 : When accessing features from a matrix of class Sparse.Assays.Matrix it requires 1 seqname!
Continuing with first seqname 'deviations'!
If confused, try getSeqnames(ArchRProj, 'MotifMatrix'') to list out available seqnames for input!
2020-05-14 13:54:00 : Matching Known Biases, 0.002 mins elapsed.
Error in if (d2 == 0L) { : missing value where TRUE/FALSE needed
```
[ArchR-getMarkerFeatures-3359269781a2-Date-2020-05-14_Time-13-53-59.log](https://github.com/GreenleafLab/ArchR/files/4628828/ArchR-getMarkerFeatures-3359269781a2-Date-2020-05-14_Time-13-53-59.log)

Thanks!

**Comment by Meggie-MH** [comment]
Have trouble to run getMarkerFeatures:
[ArchR-getMarkerFeatures-8ee66a493518-Date-2020-07-03_Time-12-51-49.log](https://github.com/GreenleafLab/ArchR/files/4870726/ArchR-getMarkerFeatures-8ee66a493518-Date-2020-07-03_Time-12-51-49.log)
ArchR logging to : ArchRLogs/ArchR-getMarkerFeatures-8ee66a493518-Date-2020-07-03_Time-12-51-49.log
If there is an issue, please report to github with logFile!
2020-07-03 12:51:50 : Matching Known Biases, 0.003 mins elapsed.
Error in .safelapply(seq_along(matchObj[[1]]), function(x) { : 
Error Found Iteration 1 : 
	[1] "Error in .logError(e, fn = \".sparseMatWilcoxon\", info = seqnames[y], errorList = errorList,  : \n  Exiting See Error Above\n"
	<simpleError in .logError(e, fn = ".sparseMatWilcoxon", info = seqnames[y], errorList = errorList,     logFile = logFile): Exiting See Error Above>
Error Found Iteration 2 : 
	[1] "Error in .logError(e, fn = \".sparseMatWilcoxon\", info = seqnames[y], errorList = errorList,  : \n  Exiting See Error Above\n"
	<simpleError in .logError(e, fn = ".sparseMatWilcoxon", info = seqnames[y], errorList = errorList,     logFile = logFile): Exiting See Error Above>
Error Found Iteration 3 : 
	[1] "Error in .logError(e, fn = \".sparseMatWilcoxon\", info = seqnames[y], errorList = errorList,  : \n  Exiting See Error Above\n"
	<simpleError in .logError(e, fn = ".sparseMatWilcoxon", info = seqnames[y], errorList = errorList,     logFile = logFile): Exiting See Error Above>
Error Found Iteration 4 : 
	[1] "Error in .logError(e, fn =
In addition: Warning message:
In mclapply(..., mc.cores = threads, mc.preschedule = preschedule) :
  19 function calls resulted in an error

> sessionInfo()
R version 4.0.1 (2020-06-06)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.5

**Comment by rcorces** [comment]
@Meggie-MH  First - your issue appears unrelated to this open issue. Please create a separate issue unless you have reason to believe it is directly related.

Additionally, please read through your logfile before reporting errors. While I cant be 100% sure that this is the only problem, your log file repeatedly shows errors for not having a specific package installed. This raises other red flags that the installation wasnt completed properly.
```
2020-07-03 12:51:55 : ERROR Found in .sparseMatWilcoxon for chr1 
LogFile = ArchRLogs/ArchR-getMarkerFeatures-8ee66a493518-Date-2020-07-03_Time-12-51-49.log

<simpleError in .requirePackage("presto", installInfo = "devtools::install_github(\"immunogenomics/presto\")"): Required package : presto is not installed/found!
  Package Can Be Installed : devtools::install_github("immunogenomics/presto")>
```

Presto is installed via `ArchR::installExtraPackages()` so presumably this step did not complete with 100% success during original installation.

**Comment by jgranja24** [comment]
This is now fixed for 1d bias --

```

#New Release Branch
devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.0", repos = BiocManager::repositories())

library(ArchR)

#######################
# Old Result
#######################
proj <- getTestProject()
DAM <- getMarkerFeatures(
	ArchRProj = proj, 
	useMatrix = "MotifMatrix", 
	groupBy = "Clusters",
	bias = c("log10(nFrags)"),
	testMethod = "wilcoxon",
	useSeqnames = "z"
)

#Error in apply(m, 2, median) : dim(X) must have a positive length


#######################
# New Result
#######################
proj <- getTestProject()
DAM <- getMarkerFeatures(
	ArchRProj = proj, 
	useMatrix = "MotifMatrix", 
	groupBy = "Clusters",
	bias = c("log10(nFrags)"),
	testMethod = "wilcoxon",
	useSeqnames = "z"
)

# ArchR logging to : ArchRLogs/ArchR-getMarkerFeatures-3414407bd83-Date-2020-10-26_Time-13-46-23.log
# If there is an issue, please report to github with logFile!
# 2020-10-26 13:46:24 : Matching Known Biases, 0 mins elapsed.
# 2020-10-26 13:46:25 : Computing Pairwise Tests (1 of 5), 0.018 mins elapsed.
# 2020-10-26 13:46:25 : Computing Pairwise Tests (2 of 5), 0.018 mins elapsed.
# 2020-10-26 13:46:25 : Computing Pairwise Tests (3 of 5), 0.018 mins elapsed.
# 2020-10-26 13:46:25 : Computing Pairwise Tests (4 of 5), 0.019 mins elapsed.
# 2020-10-26 13:46:25 : Computing Pairwise Tests (5 of 5), 0.019 mins elapsed.
# ###########
# 2020-10-26 13:46:27 : Completed Pairwise Tests, 0.054 mins elapsed.
# ###########
# ArchR logging successful to : ArchRLogs/ArchR-getMarkerFeatures-3414407bd83-Date-2020-10-26_Time-13-46-23.log


```


Best

Jeff

**Comment by jgranja24** [comment]
Closing this issue, feel free to open new ones!
