### ISSUE TITLE
 getInputFiles() does not return with the fragment file

### ISSUE THREAD

**Issue by zahramesri** [GreenleafLab/ArchR#1399]
Hi,

The getInputFiles() does not return with the fragment file for further analysis. I have come across this [issue](https://github.com/GreenleafLab/ArchR/issues/87) and installed Fortran (gfortran) and XQuartz, but did not resolve the issue. Please let me know if you have any suggestions.

Here is the code:

> inputFiles  <- list.files("inputFile")
> inputFiles
[1] "fragments.tsv.gz"

> inputFiles  <- getInputFiles("inputFile")
> inputFiles
character(0)

Thank you,
Zahra

**Comment by rcorces** [comment]
Hi @zahramesri! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.
