### ISSUE TITLE
plotPeak2GeneHeatmap() doesn't generate cluster (`groupBy`) legend 

### ISSUE THREAD

**Issue by bj-chen** [GreenleafLab/ArchR#1401]
Hi ArchR team,

The `plotPeak2GeneHeatmap()` function I called doesn't generate cluster (`groupBy`) legend. In your tutorial, the ATAC and RNA z score legends are placed under the heatmap. In my `plotPeak2GeneHeatmap()` output they were placed next to the heatmap at the right size. However, the legend for clusters (`groupBy`) is missing. Could you please advise on how to solve the issue please? A screenshot of my heatmap is attached.
![Screenshot 2022-04-26 at 2 26 13 PM](https://user-images.githubusercontent.com/8231793/165236136-b799e738-caa7-4029-8b39-511ae5f6b920.png)

Thank you! 

With regards,
Bei Jun

**Comment by rcorces** [comment]
Hi @bj-chen! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
Have you tried expanding the printable area? Its possible that additional plot elements such as the legend are invisible because they exist outside of the designated size.

For example, `height = 20`

Its also possible that there have been changes to the `ComplexHeatmap` package since the documentation was created.
