### ISSUE TITLE
createArrowFiles does not recover enough number of single cells with fragments files input

### ISSUE THREAD

**Issue by yaxiliu-1996** [GreenleafLab/ArchR#1404]
I have an issue on createArrowFiles because the . When I give the validBarcodes parameter, I encountered the error: "createArrowFiles has encountered an error, checking if any ArrowFiles completed". The log file had no specific description of error.

**Attach your log file**
here is the log file. 
[ArchR-createArrows-86c3242dbdb9-Date-2022-04-27_Time-10-06-17.log](https://github.com/GreenleafLab/ArchR/files/8569787/ArchR-createArrows-86c3242dbdb9-Date-2022-04-27_Time-10-06-17.log)

**Describe the bug**
I have 7886 single cells (barcodes), but the ArrowFiles and ArchRProject only recovered 272 single cells. My input files are not originated from custom scATAC fragments files. I generated similar format of fragments files from my single-cell data which have the same columns as described in the cell-ranger website like following: 

chr1	852649	852709	TCTCCGGATATAGCCT-1	1
chr1	852981	853047	TCTCCGGATATAGCCT-1	1
chr1	948936	949002	TCTCCGGATATAGCCT-1	1
chr1	949237	949297	TCTCCGGATATAGCCT-1	1
chr1	950399	950459	TCTCCGGATATAGCCT-1	1
chr1	950856	950922	TCTCCGGATATAGCCT-1	1
chr1	985218	985284	TCTCCGGATATAGCCT-1	1
chr1	985479	985539	TCTCCGGATATAGCCT-1	1
chr1	1060792	1060858	TCTCCGGATATAGCCT-1	1
chr1	1061029	1061089	TCTCCGGATATAGCCT-1	1

**To Reproduce**
Run createArrowFiles() function with my input files here. I have 544 single cells in this fragments file. 
[N2.fragments.tsv.gz](https://github.com/GreenleafLab/ArchR/files/8570052/N2.fragments.tsv.gz)

**Expected behavior**
Correctly get the cell number after creating arrow files.

**Comment by rcorces** [comment]
Hi @yaxiliu-1996! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
A cursory look at your log file doesnt seem to have any errors? It seems to indicate that arrow files were created successfully.
Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.

**Comment by yaxiliu-1996** [comment]
Thanks for your nice reply!  I got exact results and did not encounter any error when using the tutorial code and dataset provided by ArchR. Thus, I uploaded a dataset of mine if you have any time to have a simple look. I am wondering if it is the case that my data is generated by single-cell ChIP-seq rather than 10x atac?

**Comment by rcorces** [comment]
1) ArchR is not designed for analysis of single-cell ChIP-seq data. We cannot provide support for this.
2) I have no issues generating an ArrowFile from your provided input file. The resulting number of cells is dependent on the filters you provide and clearly many of your cells are being removed based on those filters.

**Comment by yaxiliu-1996** [comment]
I got it. Thank you so much!
