### ISSUE TITLE
Plot embedding error: Computation failed in `stat_summary_hex()

### ISSUE THREAD

**Issue by SaharBJ** [GreenleafLab/ArchR#1406]
When I attempt the to embed plots following the ArchR tutorial I receive the following error: Computation failed in `stat_summary_hex()

Following the tutorial:
> p <- plotEmbedding(
+     ArchRProj = proj,
+     colorBy = "GeneScoreMatrix",
+     name = markerGenes,
+     embedding = "UMAP",
+     imputeWeights = getImputeWeights(proj)
+ )
Getting ImputeWeights
ArchR logging to : ArchRLogs/ArchR-plotEmbedding-d3cf195f0e3e-Date-2022-04-28_Time-12-32-32.log
If there is an issue, please report to github with logFile!
2022-04-28 12:32:34 : Getting Matrix Values...
1 2 3
Imputing Matrix
Plotting Embedding
1 2 3 4 5 6 7 8 9
ArchR logging successful to : ArchRLogs/ArchR-plotEmbedding-d3cf195f0e3e-Date-2022-04-28_Time-12-32-32.log
Warning messages:
1: Computation failed in `stat_summary_hex()`:

2: Computation failed in `stat_summary_hex()`:

3: Computation failed in `stat_summary_hex()`:

4: Computation failed in `stat_summary_hex()`:

5: Computation failed in `stat_summary_hex()`:

6: Computation failed in `stat_summary_hex()`:

7: Computation failed in `stat_summary_hex()`:

8: Computation failed in `stat_summary_hex()`:

9: Computation failed in `stat_summary_hex()`:

>
> p$CD14
Warning message:
Computation failed in `stat_summary_hex()`:

Please see log file attached. 
[ArchR-plotEmbedding-d3cf195f0e3e-Date-2022-04-28_Time-12-32-32.log](https://github.com/GreenleafLab/ArchR/files/8581959/ArchR-plotEmbedding-d3cf195f0e3e-Date-2022-04-28_Time-12-32-32.log)

**Comment by rcorces** [comment]
Hi @SaharBJ! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
Solved previously. Please search past issues before opening a new one.
https://github.com/GreenleafLab/ArchR/issues/1292
