### ISSUE TITLE
createArrowFiles has encountered an error, checking if any ArrowFiles completed.

### ISSUE THREAD

**Issue by lingkong966926** [GreenleafLab/ArchR#1407]
This is an issue template made by the developers of ArchR. You MUST follow these instructions.
When using createArrowFiles
Questions related to how to use ArchR or requests for new features should be posted in the Discussions forum (https://github.com/GreenleafLab/ArchR/discussions).

Before you submit this Bug Report please update ArchR to the latest stable version and make sure that this issue has not already been fixed in the latest release. ArchR is still in active development and we will fix problems as they arise. To update ArchR:

devtools::install_github("GreenleafLab/ArchR", ref="master", repos = BiocManager::repositories())

If your issue persists, then please submit this bug report.

PLEASE FILL OUT THE RELEVANT INFORMATION AND DELETE THE UNUSED PORTIONS OF THIS ISSUE TEMPLATE.

**Attach your log file**
ArchR has a built-in logging functionality for all complex functions. You MUST attach your log file (indicated in the console output) to this issue. Just drag and drop it here.

**Describe the bug**

**To Reproduce**
To help us optimally address your issue, please try to reproduce this issue using the tutorial hematopoiesis dataset and provide us the command(s) to reproduce your bug. Our first question to you will be "can you reproduce this with the tutorial dataset" so please do this.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Do not screenshot code or text but embed this in markdown using triple-backticks.

**Session Info**
If you do not have a log file because the function that caused the error does not produce one, please paste the output of "sessionInfo()" here.

**Additional context**

**Comment by rcorces** [comment]
Hi @lingkong966926! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by lingkong966926** [comment]
[
[ArchR-createArrows-261bf048f15021-Date-2022-04-28_Time-20-20-57.log](https://github.com/GreenleafLab/ArchR/files/8582661/ArchR-createArrows-261bf048f15021-Date-2022-04-28_Time-20-20-57.log)
](url)

**Comment by lingkong966926** [comment]
Can I use fragment.bed instead of fragment.tsv?

**Comment by rcorces** [comment]
no
