### ISSUE TITLE
There may be a bug in addGeneIntegrationMatrix 

### ISSUE THREAD

**Issue by hz1010** [GreenleafLab/ArchR#141]
Hello!
        Thanks for your great package! It really helps me a lot.
        Here is my problem While I use "addGeneIntegrationMatrix" in ArchR (version 0.9.4). I found a bug in  "addGeneIntegrationMatrix" function. In script "RNAIntegration.R" line 331, "outDir" should be "outDir1".
![33411db232a9f3de434ac726c4da69e](https://user-images.githubusercontent.com/47652056/81903469-635fc100-95f4-11ea-992b-19235d03882c.png)

**Comment by jgranja24** [comment]
Yup we caught this one earlier today. Its been updated in the dev version -
```

devtools::install_github(
"GreenleafLab/ArchR",
ref="dev_051120",
repos = BiocManager::repositories()
)

```

Closing this issue feel free to re-open if further issues.

Best

Jeff

**Comment by hz1010** [comment]
Dear Jeff
&nbsp; &nbsp; &nbsp; &nbsp; Thanks for your reply. My problem has been solved. It's very kind of you.&nbsp;
Best
Zheng




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jgranja24"<notifications@github.com&gt;; 
发送时间: 2020年5月14日(星期四) 下午3:45
收件人: "GreenleafLab/ArchR"<ArchR@noreply.github.com&gt;; 
抄送: "1074778157"<1074778157@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [GreenleafLab/ArchR] There may be a bug in addGeneIntegrationMatrix  (#141)





 
Yup we caught this one earlier today. Its been updated in the dev version -
  devtools::install_github( "GreenleafLab/ArchR", ref="dev_051120", repos = BiocManager::repositories() )  
Closing this issue feel free to re-open if further issues.
 
Best
 
Jeff
