### ISSUE TITLE
Should we remove all the cells with high doublet enrichment scores from downstream analysis?

### ISSUE THREAD

**Issue by seishin0125** [GreenleafLab/ArchR#142]
This would belong in Section 3.6 (or 2.2) of the user manual.

I tried to infer the doublet enrichment score of my scATAC sample as written in Chapter 2.2, and many of the cells were inferred as "putative doublet" like "CD34 BMMC" sample.
(The UMAP projection R^2 was 0.9954; Cells used in my own scATAC sample were labeled and sorted with specific cell type marker, therefore, I'm wondering why this R^2 ratio is such that high.)

In this condition, I investigated how many cells would be filtered as doublet by  filterDoublets() function.
・If default parameter (filterRatio=1) is used for filtering parameters, only around 4% total cells were removed and most of "putative doublet cells" were not removed. (This strategy is recommended in manual.)
・However, when doublet enrichment is used for filtering (cutScore=5, filterRatio=100), about a half of the cells were removed.

These results suggest that most of "putative doublets" with high doublet enrichment scores are not removed in default parameter. In such case, should I remove all the cells with high doublet enrichment score or keep them for downstream analysis (regard these cells would be true "intermediate" population)?

**Comment by jgranja24** [comment]
Hi @seishin0125,

The default params for filter doublets are `cutEnrich = 1, cutScore = -Inf, filterRatio = 1`. The cutScore refers to the -log10(pval) of the enrichment and we found this is a worse predictor than cutEnrich. However to answer your question further, binomial pvalues are extremely inflated like in motif enrichment when you see 10^-100 pvalues. Params for doublet filtering should be sensible and thats why the filter ratio is set to ensure that you dont over filter. If you plotted the distribution of cutEnrich or cutScore you would see a small population to the far right (putative doublets) and the rest of the cells to the left. The goal is to filter as many doublets as possible while not removing true singlets. Hope this helps.

**Comment by rcorces** [comment]
@seishin0125 - if this has not answered your question, please re-open the issue

**Comment by seishin0125** [comment]
I'm really sorry for late response,
I got the reason why so many cells showed high doublet enrichment scores.
Thank you so much for kind assistance!
