### ISSUE TITLE
Download link for Vierstra_Archetype_Motifs.rds does not work

### ISSUE THREAD

**Issue by NicolajIT** [GreenleafLab/ArchR#1424]
Hi,

I am trying to use Vierstra's motif archetypes in motif annotation. However, i am running version 1.0.1 and would prefer not to change versions at this point. Therefore i went into the code changes  you did (#1385 ) and found that you download the motifs from 
these links

https://jeffgranja.s3.amazonaws.com/ArchR/Annotations/Vierstra_Archetype_Motifs.rds (for archetypes) 

https://jeffgranja.s3.amazonaws.com/ArchR/Annotations/Vierstra_Individual_Motifs.rds (for individual)

**Now my problem is that the link for individual works. but for the archetypes do not work.** 
I was hoping the link could get updated. I want to download them myself and specify as custom motifs as suggested in #214 . 

Now to some praise, i really love the user-friendliness of ArchR with the thorough guide and everything, and that you take user-inputs so seriously. It's truly a joy to use ArchR. 

Best,
Nicolaj

**Comment by rcorces** [comment]
Hi @NicolajIT! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
Glad you are enjoying using ArchR!
The link you are using is out of date. I recently updated this because of a bug in the v2beta archetype motifs. the correct link is
https://jeffgranja.s3.amazonaws.com/ArchR/Annotations/Vierstra_Archetype_Motifs_v2.1.rds

as shown here
https://github.com/GreenleafLab/ArchR/blob/f2d5d0583e00167878e8d15ae02a016b423b9f3b/R/AnnotationPeaks.R#L453
