### ISSUE TITLE
output getMarkerFeatures showing only one group

### ISSUE THREAD

**Issue by NoemieL** [GreenleafLab/ArchR#1433]
Hi,
It is not the first time I am using getMarkerFeatures() but recently it is giving weird output. Before we could access the markers from the different groups analyzed while now only the useGroupe is available when using getMarkers(). It is also affecting the heatmap.

"'
>GeneTest_Sens_Res<- getMarkerFeatures(
  ArchRProj = MM_SenVsRes_peak2Gene, 
  useMatrix = "GeneIntegrationMatrix",
  groupBy = "Response",
  testMethod = "wilcoxon",
  bias = c("TSSEnrichment", "log10(nFrags)"),
  useGroups = "Res",
  bgdGroups = "Sens"
)

> GeneTest_Sens_Res
class: SummarizedExperiment 
dim: 18097 1 
metadata(2): MatchInfo Params
assays(7): Log2FC Mean ... AUC MeanBGD
rownames(18097): 1 2 ... 18096 18097
rowData names(6): seqnames start ... name idx
colnames(1): Res
colData names(0):

> getMarkers(GeneTest_Sens_Res, cutOff = "FDR <= 0.05 & Log2FC >= 1")
List of length 1
names(1): Res

>heatmapGS <- plotMarkerHeatmap(
seMarker = GeneTest_Sens_Res, 
cutOff = "FDR <= 0.05 & Log2FC >= 1", 
labelMarkers = B_plasma_gene,
transpose = TRUE
)
ArchR logging to : ArchRLogs/ArchR-plotMarkerHeatmap-4a6dd3c6ec39a-Date-2022-05-17_Time-18-50-56.log
If there is an issue, please report to github with logFile!
Error in plotMarkerHeatmap(seMarker = GeneTest_Sens_Res, cutOff = "FDR <= 0.05 & Log2FC >= 1",  : 
  Must use plotLog2FC = TRUE when ncol(seMarker) <= 2!
'"

It is working with plotLog2FC = TRUE, as mention but there is only the useGroup on the heatmap.

I am using the dev Version 1.0.2 with R 4.1.3. Do you have any idea of what is causing this issue?

Thanks

[ArchR-getMarkerFeatures-4a6dd46623471-Date-2022-05-17_Time-18-44-13.log](https://github.com/GreenleafLab/ArchR/files/8712408/ArchR-getMarkerFeatures-4a6dd46623471-Date-2022-05-17_Time-18-44-13.log)

**Comment by rcorces** [comment]
Hi @NoemieL! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by NoemieL** [comment]
1. Yes I did not fund
2. No there is an error when creating the arrows files #357 that I did not get with my data.
3. Yes

**Comment by rcorces** [comment]
I'm not sure I fully understand your question. `useGroups` limits the groups used for analysis. Therefore, if `useGroups = Res`, you will only get results for `Res`. If you want results for all groups, leave `useGroups = NULL`

Please close if this answers your issue.
