### ISSUE TITLE
addDoubletScores() - Cannot saveRDS because directory does not exist

### ISSUE THREAD

**Issue by danyama312** [GreenleafLab/ArchR#1436]
**Attach your log file**
[ArchR-addDoubletScores-261791a432c0e-Date-2022-05-18_Time-14-30-40.log](https://github.com/GreenleafLab/ArchR/files/8717202/ArchR-addDoubletScores-261791a432c0e-Date-2022-05-18_Time-14-30-40.log)

**Describe the bug**
When running addDoubletScores() on the tutorial data, I get the following code, I get an error message which I cannot seem to trouble shoot. Perhaps it's something to do with where I have my files saved? (Note that I am calling the object "doubScores2" since I am replicating this error message on tutorial data which first emerged on my own dataset).

```
doubScores2 <- addDoubletScores(
  input = ArrowFiles2,
  k = 10, #Refers to how many cells near a "pseudo-doublet" to count.
  knnMethod = "UMAP", #Refers to the embedding to use for nearest neighbor search with doublet projection.
  LSIMethod = 1,
)
```

> Error in .safeSaveRDS(summaryList, file.path(outDir, paste0(.sampleName(ArrowFile),  : 
>   Cannot saveRDS because directory does not exist (QualityControl/scATAC_BMMC_R1). File Path : QualityControl/scATAC_BMMC_R1/scATAC_BMMC_R1-Doublet-Summary.rds

Any help would be greatly appreciated, thanks!

**Comment by rcorces** [comment]
Hi @danyama312! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
well, if the directory _does_ exist, then R cant find it and your permissions are likely not properly set. This is not an ArchR error.
