### ISSUE TITLE
addGeneIntegrationMatrix error using seurat object

### ISSUE THREAD

**Issue by plbngl** [GreenleafLab/ArchR#1443]
Dear ArchR developers, I am having an error using the following command and I am not able to understand the problem, as I have successfully run the same commands on a different dataset as well as the tutorial.

apr <- addGeneIntegrationMatrix(
    ArchRProj = apr, 
    useMatrix = "GeneScoreMatrix",
    matrixName = "GeneIntegrationMatrix",
    reducedDims = "IterativeLSI", 
    seRNA = seRNA_beta, 
    addToArrow = TRUE, 
    groupRNA = "final_Subcluster", 
    nameCell = "predictedCell",
    nameGroup = "predictedGroup",
    nameScore = "predictedScore",
    force = T
)

where: seRNA_beta:

> An object of class Seurat 
> 36601 features across 2428 samples within 1 assay 
> Active assay: RNA (36601 features, 2000 variable features)
>  3 dimensional reductions calculated: pca, harmony, umap
> 

The error is the following:

> Error in as(x, "matrix")[, j, drop = drop]: subscript out of bounds
with traceback attached:
[traceback_message.txt](https://github.com/GreenleafLab/ArchR/files/8774323/traceback_message.txt)

This is the log file:
[ArchR-addGeneIntegrationMatrix-316cc2bc679f2-Date-2022-05-25_Time-12-15-57.log](https://github.com/GreenleafLab/ArchR/files/8774312/ArchR-addGeneIntegrationMatrix-316cc2bc679f2-Date-2022-05-25_Time-12-15-57.log)

I appreciate the help!
Best
Paola

##### Answers to questions:
1. If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved? **YES**
3. Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example. **No, tutorial code works fine**
4. Did you post your log file? If not, add it now. **YES**
5. Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post. **screenshot absent**

**Comment by rcorces** [comment]
Hi @plbngl! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
I dont have much insight here. My intuition is some issue with the RNA object or related to previous project subsetting.
Maybe try making a `SummarizedExperiment` object with the cell x gene matrix from your `Seurat` object.

**Comment by plbngl** [comment]
Thank you! It is probably a subsetting problem as I did subsetted the project using the command that is in the [manual](https://www.archrproject.com/bookdown/manipulating-an-archrproject.html) : `apr = apr[cellsToKeep , ]`, which gave me the expected result and I did downstream analysis. 
However if I now to `str(apr[getCellNames(apr),]` I have the error 
> Error in rD[[x]][[1]][cellsKeep, , drop = FALSE]: subscript out of bounds
similar to the geneintegrationMatrix error 

I do not understand why this problem and how to avoid it- thank you!

**Comment by rcorces** [comment]
Yes - that is almost certainly the project. I know the manual is in dire need of updating and we are working on it.
You can see the current draft text of the new section on project subsetting here:
https://github.com/GreenleafLab/ArchR_Website/blob/c5c5d5ae5022bb42cf379f1f4ad1ffecd672a309/bookdown/03_ArchRProject.Rmd#L106-L155

Long story short, over time we have come to realize that subsetting the project using `[ ]` is extremely dangerous and can very easily lead to the `ArchRProject` and ArrowFiles getting out of sync. You should go back to your original ArrowFiles and re-do the subsetting.

Please close if this answers your issue.

**Comment by plbngl** [comment]
Thank you for the info! Actually I was able to find the source of my problem in this post here: #717 
For some reason, the rownames of the reduced dimension are different than the one in the object, so I solved it by doing:
```
rd <- getReducedDims(apr, reducedDims = 'Harmony',   dimsToUse = 1:30)
length(rownames(rd))
length(apr$cellNames)
subcell = rownames(rd)[rownames(rd) %in% apr$cellNames]
aprB = subsetArchRProject(
      ArchRProj = apr,
      cells = rownames(rd),
      outputDirectory = "ArchRSubset",
      dropCells = TRUE,
      logFile = NULL,
      threads = getArchRThreads(),
      force = TRUE
)

```and then run the integration on the subsetted object.
I can close the issue, however, can you comment on why the reduced dimes have different cells?
Thanks!

**Comment by rcorces** [comment]
glad you found a solution. In short, subsetting using `[ ]` can make it so that your ArchRProject object and your ArrowFiles are out of sync. Because of this, we now only recommend the use of `subsetArchRProject()` which is designed to ensure that everything matches correctly.
