### ISSUE TITLE
Failed to create ArrowFiles. simpleError in doTryCatch(return(expr)

### ISSUE THREAD

**Issue by sunjiahe-hub** [GreenleafLab/ArchR#1446]
I've tried to solve the problem by searching the web and different versions, but to no avail, hope to get help.

**Describe the bug**
Failed to create ArrowFile for bam file, version used (1.02) error as shown in picture and log file
[ArchR-createArrows-792d7c3b6b71-Date-2022-05-27_Time-04-45-23.log](https://github.com/GreenleafLab/ArchR/files/8784015/ArchR-createArrows-792d7c3b6b71-Date-2022-05-27_Time-04-45-23.log)

`ArrowFiles <- createArrowFiles(
  inputFiles = inputFiles_single,
  minFrags = 1000,
  bcTag = "qname", 
  gsubExpression = ":.*",
  addTileMat = TRUE,
  addGeneScoreMat = FALSE, 
  force = TRUE
)
Using GeneAnnotation set by addArchRGenome(Mm9)!
Using GeneAnnotation set by addArchRGenome(Mm9)!
ArchR logging to : ArchRLogs/ArchR-createArrows-792d7c3b6b71-Date-2022-05-27_Time-04-45-23.log
If there is an issue, please report to github with logFile!
2022-05-27 04:45:24 : Batch Execution w/ safelapply!, 0 mins elapsed.
2022-05-27 04:45:24 : (BoneMarrow_62016 : 1 of 1) Reading In Fragments from inputFiles (readMethod = bam), 0 mins elapsed.
2022-05-27 04:45:24 : (BoneMarrow_62016 : 1 of 1) Tabix Bam To Temporary File, 0 mins elapsed.
2022-05-27 04:45:56 : (BoneMarrow_62016 : 1 of 1) Successful creation of Temporary File, 0.534 mins elapsed.

************************************************************
2022-05-27 04:45:56 : ERROR Found in .tmpToArrow for (BoneMarrow_62016 : 1 of 1) 
LogFile = ArchRLogs/ArchR-createArrows-792d7c3b6b71-Date-2022-05-27_Time-04-45-23.log

<simpleError in doTryCatch(return(expr), name, parentenv, handler): lazy-load database '/usr/local/lib/R/site-library/ArchR/R/ArchR.rdb' is corrupt>
  
************************************************************
  
2022-05-27 04:45:56 : createArrowFiles has encountered an error, checking if any ArrowFiles completed..
ArchR logging successful to : ArchRLogs/ArchR-createArrows-792d7c3b6b71-Date-2022-05-27_Time-04-45-23.log
Warning messages:
1: In doTryCatch(return(expr), name, parentenv, handler) :
restarting interrupted promise evaluation
2: In doTryCatch(return(expr), name, parentenv, handler) :
  internal error -3 in R_decompress1`

**Comment by rcorces** [comment]
Hi @sunjiahe-hub! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.
