### ISSUE TITLE
Issue with plotEmbedding with GeneExpressionMatrix

### ISSUE THREAD

**Issue by jmmuncie** [GreenleafLab/ArchR#1452]
Hi - I've encountered an issue using `plotEmbedding` with `GeneExpressionMatrix` to visualize expression of genes of interest in UMAP space on my dataset of integrated scATAC and scRNA data from a 10x Multiome experiment. The function works as expected for most of my genes of interest, but for a few examples, I get a blank plot, as seen below (with log file attached). 

<img width="423" alt="Screen Shot 2022-06-05 at 11 54 02 AM" src="https://user-images.githubusercontent.com/60235694/172066033-cbfc69c5-e9f5-43d9-a1c7-1d878b99aff1.png">

It seems that the genes that don't work have relatively few non-zero entries in the gene expression matrix, e.g. a few hundred out of 37,000+ cells. Is there a minimum number of non-zero entries required for the `plotEmbedding` function to work? Or do you think something else might be causing the issue here?

[ArchR-plotEmbedding-43a34d14939b-Date-2022-06-05_Time-11-49-04.log](https://github.com/GreenleafLab/ArchR/files/8840555/ArchR-plotEmbedding-43a34d14939b-Date-2022-06-05_Time-11-49-04.log)

**Comment by rcorces** [comment]
Hi @jmmuncie! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by jmmuncie** [comment]
Yes, that sounds like it should work. However, when I set `quantCut = NULL` as in the following:
```
plotEmbedding(
    ArchRProj = proj_Mef2c_v13_E9,
    colorBy = "GeneExpressionMatrix",
    name = "Sox17",
    embedding = "UMAP_Harmony_Combined",
    quantCut = NULL
)
```
I get an error message:
```
Plotting Embedding
1 Error in quantile.default(x, probs = c(lo, hi)) : 'probs' outside [0,1]
In addition: Warning messages:
1: In min(quantCut) : no non-missing arguments to min; returning Inf
2: In max(quantCut) : no non-missing arguments to max; returning -Inf
```
And `traceback()` yields this:
```
8: stop("'probs' outside [0,1]")
7: quantile.default(x, probs = c(lo, hi))
6: quantile(x, probs = c(lo, hi))
5: quantile(x, probs = c(lo, hi))
4: .quantileCut(plotParamsx$color, min(quantCut), max(quantCut))
3: FUN(X[[i]], ...)
2: lapply(seq_along(colorList), function(x) {
       if (getArchRVerbose()) 
           message(x, " ", appendLF = FALSE)
       plotParamsx <- .mergeParams(colorList[[x]], plotParams)
       if (plotParamsx$discrete) {
           plotParamsx$color <- paste0(plotParamsx$color)
       }
       if (!plotParamsx$discrete) {
           plotParamsx$color <- .quantileCut(plotParamsx$color, 
               min(quantCut), max(quantCut))
           plotParamsx$pal <- paletteContinuous(set = plotParamsx$continuousSet)
           if (!is.null(pal)) {
               plotParamsx$pal <- pal
           }
           if (is.null(plotAs)) {
               plotAs <- "hexplot"
           }
           if (!is.null(log2Norm)) {
               if (log2Norm) {
                   plotParamsx$color <- log2(plotParamsx$color + 
    ...
1: plotEmbedding(ArchRProj = proj_Mef2c_v13_E9, colorBy = "GeneExpressionMatrix", 
       name = "Sox17", embedding = "UMAP_Harmony_Combined", quantCut = NULL)
```

[ArchR-plotEmbedding-5e203dec417f-Date-2022-06-06_Time-10-31-28.log](https://github.com/GreenleafLab/ArchR/files/8846374/ArchR-plotEmbedding-5e203dec417f-Date-2022-06-06_Time-10-31-28.log)

**Comment by rcorces** [comment]
ok. that looks like a bug. I will look into that. in the mean time, I think `quantCut = c(0,1)` should do the same thing.

**Comment by rcorces** [comment]
After looking into this, I dont think your problem is related to `quantCut`. That part of the function should behave as expected because it has a built-in check to see if the upper-quant limit is 0 and if so it ignores that upper limit. I think you problem is more likely due to 1 of two things:
1) you havent set `plotAs` so it defaults to `hex` and creates an aggregate signal for all cells falling in that hex bin
or
2) Even if you try `plotAs = "points"` I cant remember how ArchR sets the order of points plotted but it probably is not smart enough to show the few hundred colored cells on top so they might get hidden behind a sea of grey points

I'll still fix the `quantCut = NULL` bug though

**Comment by rcorces** [comment]
I do not get an error with `quantCut = NULL`. Perhaps your ArchR install wasnt properly loaded after updating to the latest `release_1.0.2`.

Safest way to make sure is to install using devtools, then run:
```
#to unload a package and reload
detach("package:ArchR", unload=TRUE)
library(ArchR)
```

Here is what my output looks like
```
> p_PAX5 <- plotEmbedding(
+   ArchRProj = projHeme5,
+   colorBy = "GeneScoreMatrix",
+   name = c("PAX5"),
+   embedding = "UMAP",
+   quantCut = NULL,
+   imputeWeights = getImputeWeights(ArchRProj = projHeme5),
+   plotAs = "points"
+ )
Getting ImputeWeights
No imputeWeights found, returning NULL
ArchR logging to : ArchRLogs/ArchR-plotEmbedding-816a455eb4bdd-Date-2022-06-06_Time-12-51-07.log
If there is an issue, please report to github with logFile!
2022-06-06 12:51:09 : Getting Matrix Values...

Plotting Embedding
1 
ArchR logging successful to : ArchRLogs/ArchR-plotEmbedding-816a455eb4bdd-Date-2022-06-06_Time-12-51-07.log
```

**Comment by jmmuncie** [comment]
Yeah, that was all it was. Thanks again!
