### ISSUE TITLE
plotFootprints: ArchRProj can't be NULL

### ISSUE THREAD

**Issue by hukai916** [GreenleafLab/ArchR#1461]
This is a quick one.

In the plotFootprint() function, the ArchRProj is default to "NULL", however, the function requires ArchRProj to be a real ArchRProj object.

**Comment by rcorces** [comment]
Hi @hukai916! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
This is a feature not a bug. The default is `ArchRProj = NULL` and `NULL` is not an acceptable value because users must enter a proper `ArchRProject`. Otherwise, how would the function do any work?

**Comment by hukai916** [comment]
I was talking about this:
https://github.com/GreenleafLab/ArchR/blob/041882c7d123ab6288aa37fa33fa6add54ca833e/R/Footprinting.R#L405-L410

If `ArchRProj ` can not be `NULL`, the above lines are not necessary. Actually, it won't pass the check:
https://github.com/GreenleafLab/ArchR/blob/041882c7d123ab6288aa37fa33fa6add54ca833e/R/Footprinting.R#L377

Anyhow, like you pointed out, I can always manually copy/move the resulting plots.

**Comment by rcorces** [comment]
Thanks for using permalinks. Just to wrap this up, it turns out that I already fixed this on `release_1.0.2` last year in this commit
https://github.com/GreenleafLab/ArchR/commit/cd8baa379a169642cd8ba9f71272aea65f8d130e

Either way, I also updated the parameter definition via https://github.com/GreenleafLab/ArchR/commit/05a83440f3080ed1e39750b619b01e475b5e94a7

**Comment by hukai916** [comment]
Good to know, thanks!
