### ISSUE TITLE
getMarkerFeatures() all groups vs specific group

### ISSUE THREAD

**Issue by rcorces** [GreenleafLab/ArchR#1467]
### Discussed in https://github.com/GreenleafLab/ArchR/discussions/1448

<div type='discussions-op-text'>

<sup>Originally posted by **wuv21** June  2, 2022</sup>
Hi! Just a conceptual question regarding getMarkerFeatures() (and to make sure I'm understanding this function correctly):

I understand that getMarkerFeatures() as used below will return a list of markers that are unique to each group in the `groupBy` column data. If I understand correctly, the background group is set to all other cells not in the current group being examined.

```r
getMarkerFeatures(proj, groupBy = "myGroup")
```

However, if I run the below code instead - should I expect the same list of significant markers as compared to markers that are specific to Group_Level_1 from the above code? When I try it out on my data, I don't see the same list of significant markers. Any clarification on this would be greatly appreciated!

```r
getMarkerFeatures(proj, groupBy = "myGroup", useGroups = "Group_Level_1")
```

Thanks!</div>

**Comment by rcorces** [comment]
Hi @rcorces! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by wuv21** [comment]
#1409 by @anastasiya-pendragon might contain an elegant fix for this.

**Comment by rcorces** [comment]
@wuv21 
The changes suggested by @anastasiya-pendragon have now been implemented in the `dev` branch which will eventually be incorporated into a stable `release_1.0.3`. 
See https://github.com/GreenleafLab/ArchR/commit/23ef3cf1ab039b30aa9daf3112416c79fd32e9ac for incorporation
