### ISSUE TITLE
How to plot only a subset of cells/condition in the UMAP?

### ISSUE THREAD

**Issue by CSBioAzim** [GreenleafLab/ArchR#147]
I have cells from multiple conditions, and I would like only to visualize the embedding of a specific condition rather than all the samples in one UMAP plot.
Is there any easy way to do it? 
This also would be great for visulizing and doing condition specific trajectory analysis.

Thanks

**Comment by concatenize** [comment]
This is very similar to #146 . My workaround is to subset the UMAP manually:

    library(magrittr) 
    my_project@embeddings$UMAP$df %<>% extract(my_cells, )

**Comment by rcorces** [comment]
yes - see the thread for #146. Thank you @concatenize !
