### ISSUE TITLE
Remove peak coordinates in markerHeatmap

### ISSUE THREAD

**Issue by yuanlizhanshi** [GreenleafLab/ArchR#1472]
When i run the tutorial code.
`heatmapPeaks <- markerHeatmap(
  seMarker = markersPeaks, 
  cutOff = "FDR <= 0.1 & Log2FC >= 0.5",
  transpose = TRUE
)
draw(heatmapPeaks, heatmap_legend_side = "bot", annotation_legend_side = "bot")
`
The heatmap was different from the tutorial.
How to remove the peak coordinates of the heatmap.
![plot_zoom_png](https://user-images.githubusercontent.com/38498877/173531221-06d7a612-1ba3-4f26-ab24-42103aa29983.png)

**Comment by rcorces** [comment]
Hi @yuanlizhanshi! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
1. This does not belong in issues. Only errors or bug reports belong in issues. This is a usage question and belongs in discussions. In the future, if posted in the wrong location, your issue will be closed without response.
2. Please read the parameter definitions fully prior to posting. Your answer is contained in the parameter definitions:
https://www.archrproject.com/reference/plotMarkerHeatmap.html
