### ISSUE TITLE
Custom create motifannotaions error

### ISSUE THREAD

**Issue by yangxueqianR** [GreenleafLab/ArchR#1476]
Thank you for developing this handy software. 
  Now I'm having some problems running data. I want to do motif enrichment analysis on my Danio_rerio data. I downloaded and built the PWMList myself from CISBP and encountered an error when I ran the following code.
```R
proj = addMotifAnnotations(ArchRProj = proj,motifPWMs=PWMListMat)
ArchR logging to : ArchRLogs/ArchR-addMotifAnnotations-63a415f1d459-Date-2022-06-16_Time-12-08-28.log
If there is an issue, please report to github with logFile!
2022-06-16 12:08:39 : Gettting Motif Set, Species : , 0.19 mins elapsed.
	2022-06-16 12:17:05 : Finding Motif Positions with motifmatchr!, 8.63 mins elapsed.
Error in pwmType(pwm) : 
  Can't determine format of PWM -- should be numeric frequency summing to 1 or log or log2 odds ratio

```
  I checked the PWMList and his profileMatrix sum to 1, so do you have any good suggestions? Thank you very much.

**Attach your log file**
[ArchR-addMotifAnnotations-63a415f1d459-Date-2022-06-16_Time-12-08-28.log](https://github.com/GreenleafLab/ArchR/files/8915781/ArchR-addMotifAnnotations-63a415f1d459-Date-2022-06-16_Time-12-08-28.log)

**Comment by rcorces** [comment]
Hi @yangxueqianR! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
Your pwm object is failing this test in chromVar.
https://github.com/GreenleafLab/chromVAR/blob/0f27fcc8463d537d770f164a55f949701beb6add/R/pwm_dist.R#L1-L27

Perhaps you can troubleshoot to figure out why.

**Comment by yangxueqianR** [comment]
Ok, thank you very much for your reply. I found my problem, I adjusted my accuracy, and it wasn't all 1,but very close to 1.
ChromVar is strict about frequency, while the log or log2 will ignore difference less than 10^-5. So I tried to adjust my profileMatrix according to his code, divide it by bg and calculate the log, and it ran normally. Thank you very much for your help.

**Comment by rcorces** [comment]
Thanks for reporting back with what fixed your problem. Closing this issue.
