### ISSUE TITLE
plotMarkers error

### ISSUE THREAD

**Issue by meowll** [GreenleafLab/ArchR#1482]
Hello!

I got an error using the function plotMarkers inputting the markerTest object obtained from the getMarkerFeatures function. 

```
markerTest <- getMarkerFeatures(
  ArchRProj = proj, 
  useMatrix = "PeakMatrix",
  groupBy = "Clusters2",
  testMethod = "wilcoxon",
  bias = c("nFrags"),
  useGroups = c("X"),
  bgdGroups = c("Y", "Z")
)

pma <- plotMarkers(seMarker = markerTest, name = "X", cutOff = "FDR <= 0.1 & abs(Log2FC) >= 1", plotAs = "MA")
pma

Error in assays(seMarker[, name]) : could not find function "assays"
```
when checking markerTest

```
markerTest@assays
An object of class "SimpleAssays"
Slot "data":
List of length 7
names(7): Log2FC Mean FDR Pval MeanDiff AUC MeanBGD
```

Thanks for your help!

**Comment by rcorces** [comment]
Hi @meowll! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by meowll** [comment]
Hi,

apparently there was an issue with the package "SummarizedExperiment", after reinstalling it worked again!
