### ISSUE TITLE
Eorror with addIterativeLSI

### ISSUE THREAD

**Issue by MatsuSui** [GreenleafLab/ArchR#1485]
When I run the tutorial data "Hematopoiesis" with ArchR ,I encountered an error.

projHeme1 <- addIterativeLSI(
  ArchRProj = projHeme1,
  useMatrix = "TileMatrix", 
  name = "IterativeLSI")
<img width="886" alt="image" src="https://user-images.githubusercontent.com/102005180/175030827-40ac3cf6-9c7a-4b07-9d0c-116938950a36.png">

**Comment by rcorces** [comment]
Hi @MatsuSui! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
As my previous message indicated, there are certain requirements that must be met for issue posts to receive a reply. The above post does not include a log file and includes screenshots of text, so no response was provided.
