### ISSUE TITLE
differential co-accessibility analysis

### ISSUE THREAD

**Issue by Brawni** [GreenleafLab/ArchR#149]
Hello, 

I'm looking at the peak co-accessibility section and i was wondering whether you are planning to add functions to calculate differential peak co-accessibility?

Thanks a lot!

**Comment by rcorces** [comment]
Can you describe more what you mean by this? Co-accessibility requires variation across many cells. So presumably you have two different experiments (for ex. case vs control) that each have a wide enough variety of cells to individually calculate co-accessibility and you want to compare this co-accessibility across those two experiments. 

From a biological standpoint, I would hesitate to interpret such a result but maybe I'm not thinking about the problem correctly. Can you elaborate?

**Comment by Brawni** [comment]
Sorry if this wasn't clear, and to be honest I don't have a clear idea myself. What I had in mind is for example to compare the co-accessibility between two clusters of cells, rather than samples.  Perhaps this make more sense when looking at co-accessibility among peaks mapping to the same gene in two different clusters. It think it would also make for a more robust way to detect differential peaks?

**Comment by rcorces** [comment]
I see. I'm not sure this will work. @jgranja24 - thoughts?

**Comment by Brawni** [comment]
Following up on this...Doesnt it make more sense to run co-accessibility on a subset of cells (hopefully large enough) representing a cluster (or nearby clusters) on the UMAP space? If you run co-accessibility on the whole cell clusters don't you get higher correlation for pair of regions which are co-accessed in bigger clusters of cells while more specific interactions in smaller clusters will inevitably suffer from this?
From the original Trapnell paper they also seem to run Cicero on two subset of cells representing early and later timepoints on a pseudotime reconstruction.

Looking forward for enlightenment!

Thanks!

**Comment by jgranja24** [comment]
Hmm I normally view it as looking at variation across all cells. Its not unreasonable however to do it on a subset. If I were to add this feature, it wouldnt hold many runs rather you would have to access the links and save them elsewhere prior to re-running `addCoAccessibility` on a different subset. Sound fine?

**Comment by Brawni** [comment]
Hi Jeff,
Thanks for the reply. I have done this 'manually' subsetting the archR object and for each of them I recalculate the LSI space and call peaks before running co-accessibility (not sure if all these steps are needed). However Im not sure the approach works too well as it seems I'm loosing some of the peaks I see from the co-accessibility calculated on the whole object. I guess there are pros and cons doing this on the whole cells or on a subset. 
My initial suggestion was to further process the co-accessibility correlations to find differentially co-accessed peaks per cluster and this was an attempt to look at this. Does it make sense?

**Comment by jgranja24** [comment]
Ok I will add an option to do it on a subset.

**Comment by rojinsafavi** [comment]
Hi @jgranja24 , I was wondering if this feature is added now? I would like to have a separate blue panel for each cluster, so that I can see how the co-acce is changing in different clusters. I mentioned it here:
https://github.com/GreenleafLab/ArchR/issues/215

**Comment by jgranja24** [comment]
This feature is available in the dev branch as described. The option you are looking for is   `cellsToUse` which will run on a subset of cells. Then you can get the coaccessibility values from this run and do a different cluster etc. Then compare the results at the end.

Hope that helps,

Jeff

**Comment by Brawni** [comment]
Hi Jeff! That's awesome thanks!

**Comment by rojinsafavi** [comment]
Hi @jgranja24. I installed ArchR as follow:
devtools::install_github("GreenleafLab/ArchR", ref="dev_053120", repos = BiocManager::repositories())
and it was installed successfully. May I ask where should I use cellsToUse? in the addCoAccessibility? Since I'm not able to find this option

Thank you!

**Comment by rcorces** [comment]
@rojinsafavi - correct. This is an argument to `addCoAccessibility()`. You can see this parameter, and the parameter definition in the code on the dev branch here - https://github.com/GreenleafLab/ArchR/blob/c6e4e650d8fc4c43ba9d3e0e3baf9327f85517c0/R/IntegrativeAnalysis.R#L686

This parameter will eventually get incorporated into the function documentation once released to master.

**Comment by lsundaram** [comment]
is this functionality also added to the addpeak2gene links function ?

**Comment by rcorces** [comment]
This has not been implemented for `addPeak2GeneLinks()` but you can open a new issue for that feature request. makes sense to me.

**Comment by lsundaram** [comment]
Sure ! thank you!

**Comment by A-legac45** [comment]
> @rojinsafavi - correct. This is an argument to `addCoAccessibility()`. You can see this parameter, and the parameter definition in the code on the dev branch here -
> 
> https://github.com/GreenleafLab/ArchR/blob/c6e4e650d8fc4c43ba9d3e0e3baf9327f85517c0/R/IntegrativeAnalysis.R#L686
> 
> This parameter will eventually get incorporated into the function documentation once released to master.

Hello all @rcorces @rojinsafavi @Brawni @jgranja24 @lsundaram , 

I am wondering If I isolate cells from intemediary cluster and maturen A cluster. I could identify co accessible peaks related to development.  For this should I extract the cells by a subset of this two cluster an rerun LSI ... or can I just redo the co-accessibility calculation on this subset. Then, I could do the same for the  cells from the same intermediary cluster to mature B  cluster. Finally, could I compare the co accessibility between those to group in order to identify specific co accessible region arising to A or B maturation ?

Thank you, 

Best,
