### ISSUE TITLE
Error : Error in (function (cl, name, valueClass) : 'history' is not a slot in class "SummarizedExperiment"\n

### ISSUE THREAD

**Issue by ChrisTzaferis** [GreenleafLab/ArchR#1492]
[Marker_Genes_file.log](https://github.com/GreenleafLab/ArchR/files/8976526/Marker_Genes_file.log)

During the execution of function getMarkerFeatures(), using the last stable version of the package and the tutorial dataset, I get the following error: 
[1] "Error :   Error in (function (cl, name, valueClass) : 'history' is not a slot in class "SummarizedExperiment"\n 

This error is thrown when I try to run ArchR analysis through R shiny,  however I cannot reproduce the error, when I execute the same script without shiny. 

**Expected behavior**
Successful run without the error. 

If you have faced any similar situation with archR in Shiny, it would be helpful if you could share any possible solutions.

Thank you for your time!

**Comment by rcorces** [comment]
Hi @ChrisTzaferis! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
I dont have an answer for this. Sorry. Its not a use case that we would have explored. Feel free to report back if you figure out the cause and I'm happy to look for a patch. My bet would be some package incompatibility or something obscure like that.

**Comment by ChrisTzaferis** [comment]
Thank you for the quick reply! Probably yes, because it was working fine until R 4.0.5. 
I will post back, if I figure out the problem!

**Comment by ChrisTzaferis** [comment]
Hi @rcorces, I have figured out what caused the issue. In the line https://github.com/GreenleafLab/ArchR/blob/79953a93ae376a500e681aa3b5ba669af6bb58e1/R/MarkerFeatures.R#L90 if you change it to "S4Vectors::metadata(out)$Params <- args", as well as in line : https://github.com/GreenleafLab/ArchR/blob/79953a93ae376a500e681aa3b5ba669af6bb58e1/R/MarkerFeatures.R#L305 --> "S4Vectors::metadata(pse)$MatchInfo <- matchObj", everything works fine again in the rshiny environment.

**Comment by rcorces** [comment]
@ChrisTzaferis - thanks for reporting back. I've made that patch in the `dev_mrc` branch which will eventually get merged into an upcoming release. There are many other code chunks that would have a similar issue but I have gone through and fixed this systematically

**Comment by ChrisTzaferis** [comment]
@rcorces thank you very much!
