### ISSUE TITLE
multithreaded issue with identifyVarFeatures

### ISSUE THREAD

**Issue by BCYasser** [GreenleafLab/ArchR#150]
Hi everyone.

thanks a lot for this beautiful package.

[ArchR-addDoubletScores-4bdc9aeac30-Date-2020-05-18_Time-23-02-06.log](https://github.com/GreenleafLab/ArchR/files/4648092/ArchR-addDoubletScores-4bdc9aeac30-Date-2020-05-18_Time-23-02-06.log)

**Describe the bug**
in multithreaded mode the addDoubletScores function fails. tracking the error down led me to suspect that  identifyVarFeatures in the cause

**To Reproduce**
Set addArchRThreads(threads = 4) 

**Expected behavior**
addDoubletScores

**Screenshots**
same as in the log

Solution
going back to single thread solves the problem 

enhancement:
maybe a default setting for this function in single thread could help (I am not an expert).

thanks a lot

**Comment by rcorces** [comment]
Sorry for the delay in addressing this. We are getting sporadic reports of multi-threading being a problem. This seems to be system specific. Any details you can provide about the system you are using and its specifications would be helpful. We don't want to change the default but we would like to identify why multi-threading works in some instances but not others.

**Comment by BCYasser** [comment]
I have been runing ArchR on unbuntu 18.04 using Rstudio Version 1.1.456 (all installed in a conda environment). please let know if you need more specifics. I will be happy to help.

Note: since this I had this bug I have been running all the other functions in single threaded mode so I can't comment on other functions available in the ArchR package.

regards

**Comment by rcorces** [comment]
Thanks for the feedback! One thing you could try is to use the regular R terminal rather than RStudio. There are some odd issues with RStudio, particularly around multi-threading that we are still trying to work through. If you have a chance, you could try that to see if it allows multi-threading.
