### ISSUE TITLE
OutputDirectory cannot have a space

### ISSUE THREAD

**Issue by nls88** [GreenleafLab/ArchR#1505]
Using Windows, when I type the following:
`> doubScores <- addDoubletScores(
+     input = ArrowFiles,
+     k = 10, #Refers to how many cells near a "pseudo-doublet" to count.
+     knnMethod = "UMAP", 
+     LSIMethod = 1
+ )`
Error is '''Error in ArchRProject(ArrowFiles = ArrowFile, outputDirectory = tmpDir,  : 
  outputDirectory cannot have a space in the full path! Full path : C:\Users\inspiron 3910\Documents\tmp\tmp-1468ba475bf-Date-2022-07-13'''
I don't know what specificly what not have a space mean, and I also have a Arrow File already for this analysis. Does my storing disk lack space for tempDic or anything else?

**Comment by rcorces** [comment]
Hi @nls88! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
Sorry for the inconvenience but ArchR is not supported on Windows. We have tried to make this clear on the homepage - 
https://www.archrproject.com/
