### ISSUE TITLE
Label transfer output directory: variable not defined

### ISSUE THREAD

**Issue by concatenize** [GreenleafLab/ArchR#151]
Please forgive me for not giving a reprex, because I think this should be a quick, easy fix. CCA+MNN label transfer fails with `Error in file.path(outDir, "RNAIntegration") : object 'outDir' not found`. There's a couple of lines in `addGeneIntegrationMatrix` where you probably just forgot to update `outDir` to `outDir1`.

    outDir1 <- getOutputDirectory(ArchRProj)
    outDir2 <- file.path(outDir, "RNAIntegration")

**Comment by concatenize** [comment]
I can avoid this issue by downgrading to the last version I had installed. 

```
devtools::install_github(
"GreenleafLab/ArchR",
ref="dev_051120",
repos = BiocManager::repositories()
)
unloadNamespace("ArchR")
library("ArchR")
```

**Comment by lsundaram** [comment]
I had the same issue and i downgraded to the dev version to get the RNA integration working. However, when i downgraded to "dev_051120" version, i get a missing file error 

Warning message in mclapply(..., mc.cores = threads, mc.preschedule = preschedule):
“8 parallel function calls did not deliver results”
2020-05-20 22:30:06 : Block (1 of 8) : Plotting Joint UMAP, 8.072 mins elapsed.

Warning message in gzfile(file, "rb"):
“cannot open compressed file '/illumina/scratch/deep_learning/lsundaram/single_cell_datasets/cardiomyogenesis/cardio_all_differentiation_archr/RNAIntegration/GeneIntegrationMatrix/Save-Block1-JointCCA.rds', probable reason 'No such file or directory'”
2020-05-20 22:30:06 : Block (2 of 8) : Plotting Joint UMAP, 8.074 mins elapsed.

I have attached the full log here.
[ArchR-addGeneIntegrationMatrix-635e7e2a97d3-Date-2020-05-20_Time-22-21-32.log](https://github.com/GreenleafLab/ArchR/files/4664233/ArchR-addGeneIntegrationMatrix-635e7e2a97d3-Date-2020-05-20_Time-22-21-32.log)


Thank you for your time and help!

**Comment by jgranja24** [comment]
Can you try this again with the new master. Sorry I am a bit behind. I think the new master version should have this solved?

**Comment by concatenize** [comment]
I am still getting logical TRUE values with the new master. Here's the log. 

[ArchR-addCoAccessibility-bc1c4102b5ab-Date-2020-06-01_Time-08-53-04.log](https://github.com/GreenleafLab/ArchR/files/4711382/ArchR-addCoAccessibility-bc1c4102b5ab-Date-2020-06-01_Time-08-53-04.log)
.

**Comment by lsundaram** [comment]
I get the following error now. 

[ArchR-addGeneIntegrationMatrix-77ec3c7eb73f-Date-2020-06-01_Time-16-57-17.log](https://github.com/GreenleafLab/ArchR/files/4714971/ArchR-addGeneIntegrationMatrix-77ec3c7eb73f-Date-2020-06-01_Time-16-57-17.log)

**Comment by jgranja24** [comment]
Im confused on these comments to what they are directing to. Can you open a new issue with the specific bugs still occuring? Im closing this issue because the original problem is resolved i believe.

**Comment by concatenize** [comment]
Sorry, I had two threads going and got mixed up. I am fuzzy on the details now but I think you're right.
