### ISSUE TITLE
tutorial: unable to get doublet scores

### ISSUE THREAD

**Issue by akworkaccnt** [GreenleafLab/ArchR#1515]
[ArchR-addDoubletScores-5e946cec5ca-Date-2022-07-20_Time-21-40-02.log](https://github.com/GreenleafLab/ArchR/files/9154676/ArchR-addDoubletScores-5e946cec5ca-Date-2022-07-20_Time-21-40-02.log)

**Describe the bug**
Unable to get doublet scores using tutorial data (ERROR: $ operator is invalid for atomic vectors)

**To Reproduce**
In tutorial

**Expected behavior**
Get doublet scores

**Comment by rcorces** [comment]
Hi @akworkaccnt! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
The log file that ArchR outputs is the first place you should look to address issues. If you scan your logfile, the first error that you find will tell you exactly what your issue is.
