### ISSUE TITLE
Output bam

### ISSUE THREAD

**Issue by KeWXiong** [GreenleafLab/ArchR#1519]
Thanks for the contribution. Can I output the corresponding bam files after performing quality control and filtering using ArchR?

**Comment by rcorces** [comment]
Hi @KeWXiong! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
Please note that usage questions are meant to be posted in the Discussions forum, as clearly stated in the instructions when you attempt to open an issue.

No, bam file output is not currently possible in ArchR.
