### ISSUE TITLE
scRNA and scATAC integeration

### ISSUE THREAD

**Issue by rojinsafavi** [GreenleafLab/ArchR#152]
I am loosing 4 of the cluster labels when I do the scRNA and scATAC label transferring. I was wondering if there is a way to avoid this from happening?

**Comment by rcorces** [comment]
Please provide more information for us to help you address your issue. Ideally, recapitulate your error with the tutorial dataset.

**Comment by rojinsafavi** [comment]
Technically I am not getting any error. I am following the tutorial provided. I was using Signac before ArchR, and with their method, I was able to transfer all the labels (except one of them) from scRNA to scATAC. I was wondering if there are any parameters that you suggest to tweak in order to get all the labelings? I have to mention that I did the unconstrained transferring.

```
projHeme2 <- addIterativeLSI(
    ArchRProj = projHeme2,
    useMatrix = "TileMatrix", 
    name = "IterativeLSI50", 
    iterations = 3, 
    clusterParams = list( #See Seurat::FindClusters
        resolution = c(0.1, 0.2, 0.4), 
        sampleCells = 10000, 
        n.start = 50
    ), 
    varFeatures = 15000, 
    dimsToUse = 1:30
)

```
