### ISSUE TITLE
Error with creating ArrowFile

### ISSUE THREAD

**Issue by jshi7** [GreenleafLab/ArchR#1527]
[ArchR-createArrows-74357945f688-Date-2022-07-27_Time-16-27-19.log](https://github.com/GreenleafLab/ArchR/files/9204323/ArchR-createArrows-74357945f688-Date-2022-07-27_Time-16-27-19.log)

Hello,
I'm trying to create an ArrowFile and I keep getting this error:

<simpleError in validObject(r): invalid class “dgTMatrix” object: lengths of slots i and j must match>
I followed all the default tutorial parameters and only used one thread. I am using 10x fragments data. 

The tutorial dataset works fine but I'm not sure why I'm getting this error for my dataset. 

I saw this issue thread but already have v. 1.0.2 https://github.com/GreenleafLab/ArchR/issues/1145

**Comment by rcorces** [comment]
Hi @jshi7! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
I think this may be a bug. I'm not sure if this patch will fix it but could you try installing the `dev_matchID` branch and re-running?

Make sure to unload and reload ArchR like so:

```
devtools::install_github("GreenleafLab/ArchR", ref="dev_matchID", repos = BiocManager::repositories())
detach("package:ArchR", unload=TRUE)
library(ArchR)
```

Please report back on whether or not this works.

**Comment by jshi7** [comment]
Creating the arrowfile works now :) Thank you so much for your help!

**Comment by tanlongzhi** [comment]
Thank you @rcorces for the prompt fix! We really appreciated your kind help!

**Comment by rcorces** [comment]
This has been merged into the `dev` branch and will be incorporated into the next stable `release_1.0.3`

**Comment by jiangpuxuan** [comment]
> I think this may be a bug. I'm not sure if this patch will fix it but could you try installing the `dev_matchID` branch and re-running?
> 
> Make sure to unload and reload ArchR like so:
> 
> ```
> devtools::install_github("GreenleafLab/ArchR", ref="dev_matchID", repos = BiocManager::repositories())
> detach("package:ArchR", unload=TRUE)
> library(ArchR)
> ```
> 
> Please report back on whether or not this works.

Hi,
I am very glad to find this update, but installing `dev_match_ID` got error :
```
> devtools::install_github("GreenleafLab/ArchR", ref="dev_matchID", repos = BiocManager::repositories())
Downloading GitHub repo GreenleafLab/ArchR@dev_matchID
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/GreenleafLab/ArchR/tarball/dev_matchID'
````

**Comment by rcorces** [comment]
As stated in https://github.com/GreenleafLab/ArchR/issues/1527#issuecomment-1199567614 these changes were merged into the `dev` branch. `dev_matchID` was deleted after merge so it no longer exists
