### ISSUE TITLE
plotEnrichHeatmap n parameter not working?

### ISSUE THREAD

**Issue by brianpenghe** [GreenleafLab/ArchR#1528]
In the [tutorial](https://www.archrproject.com/bookdown/motif-enrichment-in-marker-peaks.html), Step 12.2,
`n` seems to be the number of top motifs per cell group to show, which is 7.
![image](https://user-images.githubusercontent.com/4110443/181794068-c9af9741-5ca6-467a-bacd-ddd8f61af5fd.png)
However, in the matrix, there are more than 7 motifs shown in the first cell group.
![image](https://user-images.githubusercontent.com/4110443/181794130-60664c73-08ce-4234-9fdc-300138756705.png)
Is there something wrong?

**Comment by rcorces** [comment]
Hi @brianpenghe! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
No I dont think anything is wrong. Its `n = 7` per cell type and the "extra" motifs you are referring to must come from other cell types but also have high activity in `CD4.M`. If you look at `NK` I imagine those "extra" motifs are the top 7 in `NK`.

**Comment by brianpenghe** [comment]
> No I dont think anything is wrong. Its `n = 7` per cell type and the "extra" motifs you are referring to must come from other cell types but also have high activity in `CD4.M`. If you look at `NK` I imagine those "extra" motifs are the top 7 in `NK`.

Ahh I see. So basically the motifs are reordered so the other cell types' motifs were moved up?
