### ISSUE TITLE
Harmony

### ISSUE THREAD

**Issue by rojinsafavi** [GreenleafLab/ArchR#153]
I just wanted to clarify this, when I am using Harmony does the groupBy option groups the samples based on something and performs batch correction for each group?

for example, my data looks like this:
batch1 batch2
1            1'
2            2'
3            3'
4            4'
5            5'

And I already know what group in batch 1 should align to what group in batch 2. So I prefer to do the bach correction by applying harmony to each group i.e. : (1,1'), (2,2') ...

Does the groupBy do that?

**Comment by rcorces** [comment]
No - that is not the purpose of `groupBy`. I will clarify the function parameter.

`addHarmony()` is really just a wrapper around `harmony::HarmonyMatrix()`. The value in `groupBy` is passed to the `vars_use` parameter in `HarmonyMatrix()`.

When run through ArchR, this parameter defines which variables to remove during batch correction.  Feel free to check out the harmony documentation for more information.

**Comment by rojinsafavi** [comment]
I think it would be nice if that could be added as a feature to the function. In my case, I would like to do the batch correct 5 groups (each independently).

Thank you very much!

**Comment by rcorces** [comment]
@jgranja24 - thoughts? If you think this is a reasonable feature request at this point in time, feel free to re-open the issue
