### ISSUE TITLE
[potential bug?] Can you justify why only human and mouse are supported by cisbp?

### ISSUE THREAD

**Issue by hukai916** [GreenleafLab/ArchR#1534]
Hi developers,

According to this snippet: https://github.com/GreenleafLab/ArchR/blob/79953a93ae376a500e681aa3b5ba669af6bb58e1/R/AnnotationPeaks.R#L427

If user choose to set `motifSet = "cisbp"`, only human and mouse are supported, but `cisbp` do have more species support.

**Comment by rcorces** [comment]
Hi @hukai916! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
My apologies for not replying to this sooner. The cisbp motif sets used in ArchR are obtained from the `chromVARmotifs` package and we have only curated motifs for human and mouse.

**Comment by hukai916** [comment]
Thanks for your reply! Can you clarify how the human and mouse motif sets are curated? Do you have an automated script to do that?

**Comment by rcorces** [comment]
The motifs are from the `chromVARmotifs` package. You're welcome to look at the documentation there
