### ISSUE TITLE
Bug in add background peaksets summarized experiment?

### ISSUE THREAD

**Issue by jindalk** [GreenleafLab/ArchR#1540]
I've tried to best fit this in the requested format. Happy to reproduce this on the heme dataset, but i think this one is fairly obvious.

**Describe the bug**
I was comparing the rowRanges in the backgroundPeaks summarized experiment object to the peak set in my ArchR object. While both were of the same length (354354), I noticed that the overlap was much lower, ~71k.

After a digging a little more, I noticed that while both GRanges have the same start and end coordinates for all 354354 entries, the order of chromosome names is switched up. 

Running seqnames on my archr object peakset:
```
seqnames(b4.atac@peakSet)
factor-Rle of length 354354 with 20 runs
  Lengths: 25856 28076 19820 21422 20982 20057 20226 18581 18876 18681 22580 14783 16642 14405 15292 12823 14202 12368 10485  8197
  Values : chr1  chr2  chr3  chr4  chr5  chr6  chr7  chr8  chr9  chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chrX 
Levels(20): chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chrX
```
Running seqnames on my background peakset:
```
factor-Rle of length 354354 with 20 runs
  Lengths: 25856 18681 22580 14783 16642 14405 15292 12823 14202 12368 10485 28076 19820 21422 20982 20057 20226 18581 18876  8197
  Values : chr1  chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr2  chr3  chr4  chr5  chr6  chr7  chr8  chr9  chrX 
Levels(20): chr1 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chrX
```

Comparing start and end coordinates (running these returns 0): 
```
sum(start(bg_peaks) - start(b4.atac@peakSet))
sum(end(bg_peaks) - end(b4.atac@peakSet))
```

Manually inspecting the coordinates where the mismatch should start confirms this:
```
> bg_peaks@rowRanges[c(25856:25857)]
GRanges object with 2 ranges and 8 metadata columns:
      seqnames              ranges strand |     value        GC bgdSumMean  bgdSumSd bgdGCMean   bgdGCSd bgdLengthMean bgdLengthSd
         <Rle>           <IRanges>  <Rle> | <numeric> <numeric>  <numeric> <numeric> <numeric> <numeric>     <numeric>   <numeric>
  [1]     chr1 195232485-195232985      * |     18382    0.4331   19555.70  2953.799     0.441     0.008           500           0
  [2]    chr10     3089232-3089732      * |      2333    0.4012    2249.32   297.843     0.397     0.007           500           0
  -------

> b4.atac@peakSet[c(25856:25857)]
GRanges object with 2 ranges and 13 metadata columns:
      seqnames              ranges strand |     score replicateScoreQuantile groupScoreQuantile Reproducibility        GroupReplicate distToGeneStart nearestGene
         <Rle>           <IRanges>  <Rle> | <numeric>              <numeric>          <numeric>       <numeric>           <character>       <integer> <character>
  C11     chr1 195232485-195232985      * |  16.82490                  0.939              0.887               5 C11._.B4D21-ATAC-r1-3           56019         Cr2
  C21     chr2     3089232-3089732      * |   5.29152                  0.296              0.191               2 C21._.B4D21-ATAC-r2-2           24741    Fam171a1
         peakType distToTSS  nearestTSS        GC       idx         N
      <character> <integer> <character> <numeric> <integer> <numeric>
  C11      Distal     56019  uc056ycp.1    0.4331     25856         0
  C21      Distal     24741  uc029qnv.1    0.4012         1         0
```

Not sure if this affects any downstream steps, but just wanted to bring this to you guys' attention. I'm running ArchR v1.0.2

**Comment by rcorces** [comment]
Hi @jindalk! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
Thanks for reporting. I dont believe this has any downstream effect but I've fixed it anyways via https://github.com/GreenleafLab/ArchR/commit/bd316ec49efb4a0dda9eb70e046eadded2d1558d on `dev`.

Looking at the code, I believe this "improper" ordering is introduced in the call to chromVAR.
