### ISSUE TITLE
error with GetMarkerFeatures after subsetting

### ISSUE THREAD

**Issue by yamihn** [GreenleafLab/ArchR#1547]
Hello, I subsetted my object and I performed the integration with scRNAseq, then I called the peaks, but, when I was trying to find the markers from peak matrix, I got this error:
>  markersPeaks_int <- getMarkerFeatures(
 ArchRProj = archr, 
useMatrix = "PeakMatrix", 
 groupBy = "predictedGroup",     #clusters found after integration
bias = c("TSSEnrichment", "log10(nFrags)"),
 testMethod = "wilcoxon"  )
ArchR logging to : ArchRLogs/ArchR-getMarkerFeatures-9a447e451dd-Date-2022-08-09_Time-14-21-49.log
If there is an issue, please report to github with logFile!
2022-08-09 14:40:42 : Matching Known Biases, 0.006 mins elapsed.
2022-08-09 14:40:43 : Found less than 100 cells for background matching, Lowering k to 0
Errore in nabor::knn(data = data, query = query, k = k, ...) : 
  Cloud has no points

[ArchR-getMarkerFeatures-9a446eeef2a-Date-2022-08-09_Time-14-21-49.log](https://github.com/GreenleafLab/ArchR/files/9290619/ArchR-getMarkerFeatures-9a446eeef2a-Date-2022-08-09_Time-14-21-49.log)

When I do the analysis with the whole archr object, it works fine

**Comment by rcorces** [comment]
Hi @yamihn! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
It looks like you have subsetted your project in such a way that some or many of the groups indicated by predictedGroup have fewer than 100 cells in them and this is causing failure.

**Comment by yamihn** [comment]
yes, I have subsetted the archr project removing half of cells in the way of retain only the ones in common with my scRNAseq object from Seurat. I saw that groups C12 and C13 are the problem, but in Seurat these groups are the smaller ones, and I don't them anyway. My idea is to remove this groups from getmarkersfeatures using the parameter useGroup=.

**Comment by rcorces** [comment]
you will also need to remove these problematic groups from the background groups via bgdGroups

**Comment by yamihn** [comment]
Ok, but if I only set useGroup, without setting the background, It Will perform a differential Analysis using only the group choosen? I don't want to compare specific clusters, I Need Just to find the markers of selected ones

**Comment by rcorces** [comment]
I was mistaken before. you only need to set useGroups. If you dont set bgdGroups, it will be set to the same groups as useGroups. The function will identify marker features for all of the groups in useGroups.
