### ISSUE TITLE
addGeneIntegrationMatrix can't find outDir

### ISSUE THREAD

**Issue by boberrey** [GreenleafLab/ArchR#155]
[ArchR-addGeneIntegrationMatrix-1e8af67341500-Date-2020-05-19_Time-14-54-46.log](https://github.com/GreenleafLab/ArchR/files/4653454/ArchR-addGeneIntegrationMatrix-1e8af67341500-Date-2020-05-19_Time-14-54-46.log)

**Describe the bug**

New problem where running addGeneintegrationMatrix fails, presumably because it can't find the output directory from the archr project: 

ArchR logging to : ArchRLogs/ArchR-addGeneIntegrationMatrix-1e8af67341500-Date-2020-05-19_Time-14-54-46.log
If there is an issue, please report to github with logFile!
2020-05-19 14:54:47 : Running Seurat's Integration Stuart* et al 2019, 0.025 mins elapsed.
2020-05-19 14:54:51 : Checking ATAC Input, 0.084 mins elapsed.
2020-05-19 14:54:51 : Checking RNA Input, 0.084 mins elapsed.
2020-05-19 14:54:54 : Creating Integration Blocks, 0.131 mins elapsed.
2020-05-19 14:54:54 : Prepping Interation Data, 0.134 mins elapsed.
Error in file.path(outDir, "RNAIntegration") : object 'outDir' not found

**Additional context**

Listing the output directory using:

atac_proj@projectMetadata$outputDirectory

or

getOutputDirectory(atac_proj)

works fine.

Thanks for your help!

**Comment by boberrey** [comment]
Saw a similar bug had already been reported

**Comment by xuzhougeng** [comment]
If I set the `outDir <- "HemeTutorial"` before running addGeneIntegraionMatrix, this function will work normally.

**Comment by jgranja24** [comment]
This shouldnt be necessary as this bug has been fixed now!

Best

Jeff
