### ISSUE TITLE
getMarkerFeatures() doing differentials on samples not specified in useGroups or bgdGroups

### ISSUE THREAD

**Issue by stran94** [GreenleafLab/ArchR#1551]
After using getMarkerFeatures() on the PeakMatrix and specifying useGroups and bgdGroups, I'm seeing upregulation and downregulation of peaks of different clusters. I pulled the differential peaks from the volcano/MA plot and cross referenced those peaks with the peakset. I am seeing peaks marked as upregulated from different clusters not named in useGroups/bgdGroups. What's going on here?

**Comment by rcorces** [comment]
I'm not sure what you mean by "peaks of different clusters" but if you are getting that information based on the name of the peak from the peak set, then that is not correct. Those annotations do not mean that the peak only was found in the specified cluster. Explained here:
https://www.archrproject.com/bookdown/calling-peaks-w-macs2.html#:~:text=To%20retrieve%20this,that%20peak%20call.
