### ISSUE TITLE
Errore in .getCoverageMetadata(ArchRProj = ArchRProj, groupBy = groupBy,  :    No Coverage Metadata found for : predictedGroup. Please run addGroupCoverages!

### ISSUE THREAD

**Issue by yamihn** [GreenleafLab/ArchR#1557]
Hello, after running addReproduciclePeakSet, it reports this error. I run addGroupCoverages using 

archr <- addGroupCoverages(ArchRProj = hope_sub,
                           minReplicates = 2,
                           maxReplicates = 18,
                           maxFragments = 75 * 10^6,
                           groupBy = "predictedGroup",
                           minCells = 20,
                           maxCells = 10000,
                           returnGroups = FALSE,
                           force = T)

and it works fine:
[ArchR-addGroupCoverages-de82988226a-Date-2022-08-12_Time-00-01-02.log](https://github.com/GreenleafLab/ArchR/files/9315359/ArchR-addGroupCoverages-de82988226a-Date-2022-08-12_Time-00-01-02.log)

but when I ran:
hope_sub <- addReproduciblePeakSet(
  ArchRProj = hope_sub, 
  groupBy = "predictedGroup", 
  pathToMacs2 = "/home/olga/miniconda3/bin/macs2",
  peaksPerCell = 2500,
  maxPeaks = 200000,
  minCells = 25,
  reproducibility = "2",
  force = T
)

it stopped with this message: 
Errore in .getCoverageMetadata(ArchRProj = ArchRProj, groupBy = groupBy,  :    No Coverage Metadata found for : predictedGroup. Please run addGroupCoverages!

[ArchR-addReproduciblePeakSet-de8132edf62-Date-2022-08-12_Time-11-30-21.log](https://github.com/GreenleafLab/ArchR/files/9315364/ArchR-addReproduciblePeakSet-de8132edf62-Date-2022-08-12_Time-11-30-21.log)
 any solutions? thank you

**Comment by rcorces** [comment]
Hi @yamihn! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by yamihn** [comment]
sorry, I solved the problem
