### ISSUE TITLE
Unique peak identifiers

### ISSUE THREAD

**Issue by rcw1** [GreenleafLab/ArchR#156]
Hello,

Thanks for this great package! I am trying to find a unique identifier for each peak so that I can identify which motifs are present in a particular peak (i.e. to link a given peak in the metadata of the 'peaks2gene@metadata$peakSet' object with the same peak in the 'motif.matches' object). In the peaks2gene object, there are idxATAC numbers, however these do not appear to map to unique idx numbers in the 'motif.matches' object.

Thanks for your help,

Rob

**Comment by jgranja24** [comment]
Hi @rcw1,

To do what you want here is a short guide -
```

#Add Info
proj <- addMotifAnnotations(proj, version = 1)
proj <- addPeak2GeneLinks(proj)

#Get P2G Info
p2geneDF <- metadata(proj@peakSet)$Peak2GeneLinks
pSet <- metadata(p2geneDF)$peakSet
names(pSet) <- paste(seqnames(pSet), start(pSet), end(pSet), sep = "_")

#Get MotifMatches Info
matches <- getMatches(proj)
rownames(matches) <- paste(seqnames(matches), start(matches), end(matches), sep = "_")

#Re-Order Matches to be the same order
matches <- matches[names(pSet)]

#Identify Matches in peak 123
colnames(matches)[which(assay(matches[123,]))]


```

Hope that helps

Jeff

**Comment by CSBioAzim** [comment]
@jgranja24 Sounds great. How can I identify the pick number from the pick2gene link heatmap?
This would be cool to narrow down motif analysis for the interesting peaks that we see on the heatmap.

**Comment by rcw1** [comment]
Jeff,

Thanks so much for your reply, and thanks for the guide. **I just want to confirm - in 'peak 123', does this number correspond to the same number in the column p2geneDF$idxATAC?** I ask because I'd like to make sure I'm capturing all peaks associated with a given gene, and I'm matching the genes to peaks using the p2geneDF$idxATAC and p2geneDF$idxRNA columns within the p2geneDF object.

Best,

Rob

**Comment by jgranja24** [comment]
Sorry for the delay, yes you are right to interpret it that way. Let me know if you have further issues.

**Comment by rcorces** [comment]
Closing

**Comment by yxiao832** [comment]
A follow-up question on this, how I can extract the corresponding gene names according to the idxRNA from p2geneDF?

Is the "idx" from "rowData(getMatrixFromProject(ArchRProj=proj,useMatrix = "GeneIntegrationMatrix"))" the same idx RNA in p2geneDF?

**Comment by yxiao832** [comment]
Now I think they are in metadata(p2geneDF).
