### ISSUE TITLE
Unable to install ArchR on my linux lab server

### ISSUE THREAD

**Issue by alifarhat40** [GreenleafLab/ArchR#1561]
### Discussed in https://github.com/GreenleafLab/ArchR/discussions/1560

<div type='discussions-op-text'>

<sup>Originally posted by **alifarhat40** August 12, 2022</sup>
My lab has a Ubuntu version 20.04.4 LTS (Focal Fossa) and I have spent this past week trying to install devtools to no avail. I tried so many things but cannot seem to install it. 
I even tried following these sudo tips among other tips but also failed. 
https://www.digitalocean.com/community/tutorials/how-to-install-r-packages-using-devtools-on-ubuntu-18-04

I also tried conda but that also failed:
https://anaconda.org/conda-forge/r-devtools

At this point I am unsure how to install ArchR for my scATAC-seq analysis. Has anyone faced something similar and can help me please?</div>

**Comment by rcorces** [comment]
Hi @alifarhat40! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
Sorry - I dont have any input here as this is not an ArchR-related problem but rather a devtools problem. Perhaps you will have better luck posting to a general forum or to a devtools-specific forum and including whatever error messages you are getting. 

However, you can install bundled releases of ArchR from source using the provided `tar.gz` files in the Releases section of our GitHub. For example, the latest `release_1.0.2` - https://github.com/GreenleafLab/ArchR/releases/tag/v1.0.2

Here are instructions - https://stackoverflow.com/questions/1474081/how-do-i-install-an-r-package-from-source

Good luck!
