### ISSUE TITLE
plotbrowsertrack error when setting the features

### ISSUE THREAD

**Issue by yamihn** [GreenleafLab/ArchR#1566]
hello, I'm encountering this error when plotting the browser track:
p <- plotBrowserTrack(
  ArchRProj = hope_sub_new,
   groupBy = "Clusters_kowt",
   features = head(markerList_C1_ko[[1]],1), 
 )
ArchR logging to : ArchRLogs/ArchR-plotBrowserTrack-f3c11afb3a-Date-2022-08-14_Time-14-12-28.log
If there is an issue, please report to github with logFile!
2022-08-14 14:12:28 : Validating Region, 0.002 mins elapsed.
Error in .validGRanges(region) : !is.null(gr) is not TRUE

This is the content of the feature:
head(markerList_C1_ko[[1]],1)
GRanges object with 1 range and 3 metadata columns:
      seqnames            ranges strand |    Log2FC         FDR  MeanDiff
         <Rle>         <IRanges>  <Rle> | <numeric>   <numeric> <numeric>
  [1]     chr6 30737888-30738388      * |   3.82764 4.50183e-75  0.245463

  seqinfo: 20 sequences from an unspecified genome; no seqlengths.

[ArchR-plotBrowserTrack-f3c64aad811-Date-2022-08-14_Time-14-22-26.log](https://github.com/GreenleafLab/ArchR/files/9333369/ArchR-plotBrowserTrack-f3c64aad811-Date-2022-08-14_Time-14-22-26.log)

**Comment by rcorces** [comment]
Hi @yamihn! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
Please try to troubleshoot your issues before posting. The error you received is extremely specific. You have not provided a region to be plotted to the `region` param.
