### ISSUE TITLE
Cannot pass "igraph" method to Seurat::FindClusters in addClusters

### ISSUE THREAD

**Issue by tiffanyformosa** [GreenleafLab/ArchR#1567]
I wanted to use the leidenalg option for Seurat::FindClusters in addClusters(), However, my dataset is 65,000 cells, which is too large to pass as a dense matrix. I would like to set the option for `method = "igraph"` in Seurat::FindClusters, which is a known workaround for large datasets. However since `method `is already a parameter of addClusters to select between Seurat and scran, this parameter is not accessible. Could a workaround be added?

My code is:

```wt_atlas <- addClusters(
    input = wt_atlas,
    reducedDims = "IterativeLSI",
    dimsToUse = dims,
    method = "Seurat",
    name = "Clusters",
    maxClusters = NULL,
    force = TRUE,
    knn = k,
    algorithm = 4, #this sets Seurat::FindClusters to leidenalg
    method = "igraph" #cannot pass this to FindClusters, since method is already a parameter
)
```
And the error message I get is:
```Error in addClusters(input = wt_atlas, reducedDims = "IterativeLSI", dimsToUse = dims, : formal argument "method" matched by multiple actual arguments```

Session Info: [addClusters_sessionInfo_2022-08-15.txt](https://github.com/GreenleafLab/ArchR/files/9346500/addClusters_sessionInfo_2022-08-15.txt)

**Comment by rcorces** [comment]
Hi @tiffanyformosa! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
I've added a new parameter to `addClusters()` called `FCmethod`. Whatever you pass to `FCmethod` will get passed as the `method` parameter for `addClusters`.

This has been implemented on the `dev_leidenalg` branch via https://github.com/GreenleafLab/ArchR/commit/6ce3e0afb4b91c061cc511f6effb0cdc29789920. Please test and report back. To install:

```
devtools::install_github("GreenleafLab/ArchR", ref="dev_leidenalg", repos = BiocManager::repositories())
detach("package:ArchR", unload=TRUE)
library(ArchR)
```

**Comment by tiffanyformosa** [comment]
I tested this on the example Hematopoeisis dataset and my own dataset, and it worked perfectly! Thanks so much!

**Comment by rcorces** [comment]
Thanks for confirming. These changes have been merged into the `dev` branch and will become a part of `release_1.0.3`
