### ISSUE TITLE
How to create arrow files for 10x output?

### ISSUE THREAD

**Issue by yojetsharma** [GreenleafLab/ArchR#1572]
Hi, I am new to scatac and so learning things from tutorials. I followed exactly as described in this link https://greenleaflab.github.io/ArchR_2020/Ex-Analyze-Multiome.html to load my 10x output file folder which contains the h5 file, fragments.tsv.gz and fragments.tsv.gz.tbi files. 
Heres the output:

> > library(ArchR)
> > setwd("/Users/yojetsharma/Desktop/2022/atac/")
> > inputFiles <- getInputFiles("ctrl")[1]
> > names(inputFiles) <- "ctrl"
> > ArrowFiles <- "ctrl.arrow"
> > proj <- ArchRProject(ArrowFiles)
> Using GeneAnnotation set by addArchRGenome(Hg19)!
> Using GeneAnnotation set by addArchRGenome(Hg19)!
> Validating Arrows...
> Error in ArchRProject(ArrowFiles) : Could not find ArrowFiles :
> ctrl.arrow

"atac" is my working directory and "ctrl" is my sub-directory that contains the 10x output as mentioned above.

**Comment by rcorces** [comment]
Hi @yojetsharma! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
Thats not correct. You havent made arrow files. I would recommend reading the full manual before trying to follow the multiome tutorial. Once you've done that, you can try following the in-progess update to the multiome tutorial which will be released soon. You can find it here:
https://github.com/GreenleafLab/ArchR_Website/blob/e2a84c8d355207f3a8a8510c5a16e1cdbefa28f5/bookdown/XX_MultiomicDataAnalysis.Rmd#L14
