### ISSUE TITLE
Seurat LSI module

### ISSUE THREAD

**Issue by rojinsafavi** [GreenleafLab/ArchR#158]
I was wondering if it's possible to have the regular LSI implemented for ArchR in addition to the iterative one? 

Seurat does the following:

```
pbmc <- RunTFIDF(pbmc)
pbmc <- FindTopFeatures(pbmc, min.cutoff = 'q0')
pbmc <- RunSVD(
  object = pbmc,
  assay = 'peaks',
  reduction.key = 'LSI_',
  reduction.name = 'lsi'
)

pbmc <- RunUMAP(object = pbmc, reduction = 'lsi', dims = 2:30)
pbmc <- FindNeighbors(object = pbmc, reduction = 'lsi', dims = 2:30)
pbmc <- FindClusters(object = pbmc, verbose = FALSE, algorithm = 3)
DimPlot(object = pbmc, label = TRUE) + NoLegend()
```
Thank you!

**Comment by rcorces** [comment]
I'm not sure what you mean by the "regular LSI" implementation. You can tune the number of iterations (and many other parameters) in `addIterativeLSI()` via the `iterations` parameter. Setting this to 1 makes it by definition not iterative.

Close if this answers your question

**Comment by rojinsafavi** [comment]
thanks!
