### ISSUE TITLE
Error in addPeak2GeneLinks with GeneExpressionMatrix

### ISSUE THREAD

**Issue by fe4960** [GreenleafLab/ArchR#1580]
I have searched previous Issues and found that this hasn't already been solved.

**Attach your log file**
[ArchR-addPeak2GeneLinks-3630ff2f038-Date-2022-08-22_Time-15-41-54.log](https://github.com/GreenleafLab/ArchR/files/9397604/ArchR-addPeak2GeneLinks-3630ff2f038-Date-2022-08-22_Time-15-41-54.log)

**Describe the bug**
I am analyzing the 17 multiome dataset with ArchR. I followed the work flow for analyzing multiome data at https://greenleaflab.github.io/ArchR_2020/Ex-Analyze-Multiome.html, and called the peaks with code from the tutorial. All work well. However, when I run addPeak2GeneLinks() with useMatrix="GeneExpressionMatrix", the error occurs. 

ArchR logging to : ArchRLogs/ArchR-addPeak2GeneLinks-3630ff2f038-Date-2022-08-22_Time-15-41-54.log
If there is an issue, please report to github with logFile!
2022-08-22 15:41:54 : Getting Available Matrices, 0.003 mins elapsed.
No predictionScore found. Continuing without predictionScore!
No predictionScore found. Continuing without predictionScore!
No predictionScore found. Continuing without predictionScore!
No predictionScore found. Continuing without predictionScore!
No predictionScore found. Continuing without predictionScore!
No predictionScore found. Continuing without predictionScore!
No predictionScore found. Continuing without predictionScore!
No predictionScore found. Continuing without predictionScore!
No predictionScore found. Continuing without predictionScore!
No predictionScore found. Continuing without predictionScore!
No predictionScore found. Continuing without predictionScore!
No predictionScore found. Continuing without predictionScore!
No predictionScore found. Continuing without predictionScore!
No predictionScore found. Continuing without predictionScore!
No predictionScore found. Continuing without predictionScore!
No predictionScore found. Continuing without predictionScore!
No predictionScore found. Continuing without predictionScore!
2022-08-22 15:42:13 : Filtered Low Prediction Score Cells (0 of 86926, 0), 0.009 mins elapsed.
2022-08-22 15:42:15 : Computing KNN, 0.036 mins elapsed.
2022-08-22 15:42:16 : Identifying Non-Overlapping KNN pairs, 0.048 mins elapsed.
2022-08-22 15:42:20 : Identified 498 Groupings!, 0.121 mins elapsed.
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘seqnames’ for signature ‘"NULL"’

**To Reproduce**
This is the command I used:
proj <- addPeak2GeneLinks(
  ArchRProj = proj,
  reducedDims = "LSI_Combined",
  useMatrix = "GeneExpressionMatrix",
  dimsToUse = 1:30,
  scaleDims = NULL,
  corCutOff = 0.75,
  k = 100,
  knnIteration = 500,
  overlapCutoff = 0.8,
  maxDist = 250000,
  scaleTo = 10^4,
  log2Norm = TRUE,
  predictionCutoff = 0.4,
  seed = 1,
  threads = max(floor(getArchRThreads()/2), 1),
  verbose = TRUE,
  logFile = createLogFile("addPeak2GeneLinks")
)

**Expected behavior**
I have used addPeak2GeneLinks with useMatrix="GeneIntegrationMatrix" to analyze other datasets, it works. I expect  addPeak2GeneLinks() with useMatrix="GeneExpressionMatrix" also works for the current merged multiome dataset.

**Additional context**
I have installed the latest "dev" version of ArchR, the error persists.

**Comment by rcorces** [comment]
Hi @fe4960! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
This is being handled here - https://github.com/GreenleafLab/ArchR/issues/1440
Just downgrade to `master` and you should be fine.
