### ISSUE TITLE
fraction of fragments overlapping called peaks in QC metrics

### ISSUE THREAD

**Issue by BCYasser** [GreenleafLab/ArchR#159]
Hi 

I would like to be able to plot the fraction of fragments overlapping called peaks vs number of fragments per cell (or barcode) 
I have found only reads in TSS or reads in promoter. I would like to have the number of reads in called peaks which gives an additional idea about the distribution of the 

this metric is used by 10x genomics in the Cellranger pipeline.

thanks

**Comment by jgranja24** [comment]
This is computed when you use `addPeakMatrix` it should return as `ReadsInPeaks` and `FRIP`. Alternatively you can use `addFeatureCounts` which will count each single cell in a region set. A peakSet has to be determined to be used as input in this case. 10x pipeline calls peaks and then does this.

**Comment by jgranja24** [comment]
Closing this issue feel free to open if you have further questions or issues.
