### ISSUE TITLE
weird plot using plotbrowsertrack

### ISSUE THREAD

**Issue by yamihn** [GreenleafLab/ArchR#1593]
Hi, my question is related to another, but I can't figure it out. When I want to see the coverage plot of a region, not the gene, just the region of interest, the plot is like this:

p_try <- plotBrowserTrack(
  ArchRProj = subset,
  groupBy = "Clusters_kowt",
  region =head(markerlist_d6_ko_wt[[1]],1),
  upstream = 1000000,
  downstream = 1000000)
grid::grid.newpage()
grid::grid.draw(p_try)

![plot](https://user-images.githubusercontent.com/109409803/187007001-b3138afe-b270-4ad7-b063-59cb9628f022.png)

the input of region is:
> head(markerlist_d6_ko_wt[[1]],1)
**GRanges object with 1 range and 3 metadata columns:
      seqnames            ranges strand |    Log2FC         FDR  MeanDiff
         <Rle>         <IRanges>  <Rle> | <numeric>   <numeric> <numeric>
  [1]     chr6 30737890-30738390      * |   4.00999 1.46549e-69  0.241886
  -------**
  seqinfo: 20 sequences from an unspecified genome; no seqlengths
But that I WANT Is to see the differences of peaks between conditions, for example like seurat plot does:
![de_ko_wt_d8_1](https://user-images.githubusercontent.com/109409803/187007094-e734f4c3-d16d-4494-b984-1e968e64eb96.png)

Could u help me? what I'm doing wrong?

**Comment by rcorces** [comment]
Hi @yamihn! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
I cant help without a reproducible example using the tutorial data. Will re-open if you are able to provide one.

**Comment by yamihn** [comment]
Okay, I will add a link of the related question  [#232](https://github.com/GreenleafLab/ArchR/issues/232) so maybe It can be helpful to give you an idea. The point Is, if you provide only the region without a genesymbol, this happens. Please give me a suggestion because I am stuck at this point but I Need these kind of plots

**Comment by rcorces** [comment]
Your question could be answered by carefully reading the function and parameter documentation. I cannot stress enough that we have limited time to reply to GitHub issues and questions that arise because end-users have not adequately read the extensive documentation that we provide only serve to slow further development of the tool by taking time a resources away.

**Please read the function documentation**
