### ISSUE TITLE
plotTSSEnrichment  bug 'frollmean' is not an exported object from 'namespace:data.table

### ISSUE THREAD

**Issue by BCYasser** [GreenleafLab/ArchR#160]
Hi there
**Attach your log file**
[ArchR-plotTSSEnrichment-7f532d8127bb-Date-2020-05-20_Time-19-54-54.log](https://github.com/GreenleafLab/ArchR/files/4659916/ArchR-plotTSSEnrichment-7f532d8127bb-Date-2020-05-20_Time-19-54-54.log)

**Describe the bug**
> > p1=plotTSSEnrichment(  ArchRProj = proj)
> ArchR logging to : ArchRLogs/ArchR-plotTSSEnrichment-7f532d8127bb-Date-2020-05-20_Time-19-54-54.log
> If there is an issue, please report to github with logFile!
> 2020-05-20 19:54:54 : SU006_Tumor_Pre Computing TSS (1 of 20)!, 0.013 mins elapsed.
> Error: 'frollmean' is not an exported object from 'namespace:data.table'.

**To Reproduce**
p1=plotTSSEnrichment(  ArchRProj = proj)

**Expected behavior**
plot

**Additional context**
I have 20 samples. could be too large??? no idea

** Attempts to fix it
recreate the said function `frollmean` from the source code and rerun the plotTSSEnrichment led to the same error.

please let me know what I should do 

cheers

**Comment by jgranja24** [comment]
This indicates your data.table package is out of date. As your version is from 2018. The current data.table package since 2019 has frollmean. You will solve your issue if you update data.table.

https://www.rdocumentation.org/packages/data.table/versions/1.12.8/topics/roll

https://cran.r-project.org/src/contrib/Archive/data.table/

**Comment by jgranja24** [comment]
Closing this issue feel free to open if you have further questions or issues.

**Comment by rcorces** [comment]
Can we update this as a version requirement in the DESCRIPTION file?

**Comment by BCYasser** [comment]
> Can we update this as a version requirement in the DESCRIPTION file?

would be good to add it to the requirements. 

updated data.table which solved the issue.

thanks a lot for the prompt answer
