### ISSUE TITLE
ERROR Found in .addGeneScoreMat TmpGS

### ISSUE THREAD

**Issue by mumu8910** [GreenleafLab/ArchR#1604]
Looking forward to your reply～

**Attach log file**
[ArchR-createArrows-9b433c970600-Date-2022-09-04_Time-10-29-35.log](https://github.com/GreenleafLab/ArchR/files/9483790/ArchR-createArrows-9b433c970600-Date-2022-09-04_Time-10-29-35.log)

**Describe the bug**
ERROR Found in .addGeneScoreMat TmpGS
<simpleError in h(simpleError(msg, call)): error in evaluating the argument 'subject' in selecting a method for function 'overlapsAny': unable to find an inherited method for function ‘ranges’ for signature ‘"NULL"’>

**To Reproduce**
I am trying to create a custom genome annotation (following chapter 1.5.1), but while the createArrowFiles step, the TileMatrix can be added but the GeneScoreMatrix failed.  
Using the command:
ArrowFiles <- createArrowFiles(
  inputFiles = inputFiles,
  sampleNames = names(inputFiles),
  geneAnnotation = geneAnnotation,
  genomeAnnotation = genomeAnnotation,
  filterTSS = 4,
  filterFrags = 1000,
  addTileMat = TRUE,
  addGeneScoreMat = TRUE
)

**Additional context**
I have checked the structure of 'geneAnnotation' and 'genomeAnnotation', but I think it's OK.
I use str() to see the structure and write it into the file below：
[genome.txt](https://github.com/GreenleafLab/ArchR/files/9483794/genome.txt)

**Comment by rcorces** [comment]
Hi @mumu8910! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by mumu8910** [comment]
In the tutorial code and dataset, the code works fine.

**Comment by mumu8910** [comment]
<img width="592" alt="屏幕快照 2022-09-05 下午3 01 08" src="https://user-images.githubusercontent.com/43924851/188384861-3cfa4ed0-eb73-4d5c-a519-0b875a812a92.png">

**Comment by rcorces** [comment]
Custom genomes are extremely hard to troubleshoot. The error looks like it is coming from a problem with the genes you've provided. Perhaps you have some genes on seqnames that dont exist in your genome annotation? Or perhaps you have genes located very close to the ends of your seqnames?

**Comment by mumu8910** [comment]
Thanks a lot! 
I’ll check the gene range carefully.

**Comment by mumu8910** [comment]
Thanks for your help :) 
After that, I run the source code and found when test genes pass by another gene promoter, the end of last gene is out of the range of chromosome due to the extansion. So I try to add this code into the source for limit the range and it worked~

**Comment by mumu8910** [comment]
/Users/muxiaohuan/Desktop/屏幕快照 2022-09-08 下午4.16.43.png

**Comment by mumu8910** [comment]
<img width="944" alt="屏幕快照 2022-09-08 下午4 16 43" src="https://user-images.githubusercontent.com/43924851/189072836-77e6c8c1-e9be-4a18-9674-75f36cef16b4.png">

**Comment by Melody-cell** [comment]
@mumu8910 hi,
 i've encountered the same issue, how did you fixed it?

**Comment by mumu8910** [comment]
Hi, since the species I'm analyzing is a non-model species, some genes are located at the ends of chromosomes. The gene range predicted by the original script extends beyond the terminal bases of the chromosomes. Therefore, I modified the script and set up a comparison to ensure that if the predicted range exceeds the chromosome boundaries, the chromosome end is used instead.

**Comment by mumu8910** [comment]
Hi, since the species I'm analyzing is a non-model species, some genes are located at the ends of chromosomes. The gene range predicted by the original script extends beyond the terminal bases of the chromosomes. Therefore, I modified the script and set up a comparison to ensure that if the predicted range exceeds the chromosome boundaries, the chromosome end is used instead.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年12月3日(星期二) 下午2:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [GreenleafLab/ArchR] ERROR Found in .addGeneScoreMat TmpGS (Issue #1604)














 
@mumu8910 hi,
 i've encountered the same issue, how did you fixed it?
