### ISSUE TITLE
arrow files I created can't be analyzed downstream  -multiple errors

### ISSUE THREAD

**Issue by kstriedinger** [GreenleafLab/ArchR#1606]
The arrow files created in examples work with the script from UC davis using ArChR, but the arrow files I create with my own data generate errors downstream. 
Log file attached.
ArchR has a built-in logging functionality fo
[ArchR-createArrows-653f94c154cc9-Date-2020-06-27_Time-18-56-30.log](https://github.com/GreenleafLab/ArchR/files/9507874/ArchR-createArrows-653f94c154cc9-Date-2020-06-27_Time-18-56-30.log)

**Describe the bug**
A clear and concise description of what the bug is :
-Error reading the  h5 arrowfile . Cannot open file. "File 'NA' does not exist"
-When trying to get doubles it says:
<img width="1470" alt="Screen Shot 2022-09-07 at 9 15 45 AM" src="https://user-images.githubusercontent.com/78504885/188928577-555eea8a-bbc7-4f14-a227-85abb6ed61e1.png">

Error in .logError(e, fn = "getPartialMatrix", info = prefix, errorList = errorList,  :

**Comment by rcorces** [comment]
Hi @kstriedinger! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by kstriedinger** [comment]
PLEASE FIND MY REPLY IN CAPS
1. If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved? YES, I TRIED THE FUNCTION "reformat fragment  files" BUT DIDN'T WORK.

3. Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example. NO
4. Did you post your log file? If not, add it now.  YES
5. Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
There is not sufficient information here to help. Please use the official ArchR manual rather than whatever script you have obtained from UC Davis. Also, as indicated in my previous reply, please do not paste screenshots.

If after reading the manual you still have issues, feel free to follow up here.

**Comment by kstriedinger** [comment]
can you please send the link to the manual?

**Comment by rcorces** [comment]
you can access all official documentation from our website. the manual is linked at the top.
https://www.archrproject.com/

**Comment by kstriedinger** [comment]
thanks, I'll go thru the manual. I appreciate you put all this together.
________________________________
