### ISSUE TITLE
Feature Footprinting: Footprinting in enhacer region

### ISSUE THREAD

**Issue by CSBioAzim** [GreenleafLab/ArchR#161]
I would like to perform footprinting in the enhancer region. 
I was wondering is there any function that gives the coordinate of the enhancers (either user annotated enhancer/refrence enhancers)?

**Comment by rcorces** [comment]
Identifying "enhancers" is not a built-in functionality of ArchR. Technically speaking, bonafide enhancers cannot be defined by ATAC-seq and some orthogonal data is required to know with confidence that a given chromatin accessible site acts as an enhancer.

However, you can annotate your peak set with any custom annotation using `addPeakAnnotations()`
https://www.archrproject.com/reference/addPeakAnnotations.html

We also provide easy peak annotation with curated sets of ENCODE ChIP-seq experiments via `addArchRAnnotations()`:
https://www.archrproject.com/reference/addArchRAnnotations.html
https://www.archrproject.com/bookdown/archr-enrichment.html

Once you define your regions of interest, you can follow the instructions here for footprinting:
https://www.archrproject.com/bookdown/feature-footprinting.html
