### ISSUE TITLE
Installing monocle3 for ArchR

### ISSUE THREAD

**Issue by dimurali93** [GreenleafLab/ArchR#1623]
Hi All, 

How do I install the current version of monocle3 for using in within ArchR?
I am able to install monocle3 only for R4.1.3, while ArchR is installing in R4.2. When i try to install monocle3 in the current environment where ArchR is running, installation fails due to errors with libgdal.

Thanks,
Divya

**Comment by rcorces** [comment]
Hi @dimurali93! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
ArchR does not require R v4.2.  It runs just fine on R v4.1.
