### ISSUE TITLE
getMarkerFeatures bug

### ISSUE THREAD

**Issue by rojinsafavi** [GreenleafLab/ArchR#163]
Sometimes I get the following error when I run the following code, not sure why:

markersGS <- getMarkerFeatures(
    ArchRProj = projHeme2, 
    useMatrix = "GeneScoreMatrix", 
    groupBy = "Clusters",
    bias = c("TSSEnrichment", "log10(nFrags)"),
    testMethod = "wilcoxon"
)

```
ArchR logging to : ArchRLogs/ArchR-getMarkerFeatures-23496ecd20b2-Date-2020-05-21_Time-11-17-47.log
If there is an issue, please report to github with logFile!

MatrixClass = Sparse.Double.Matrix

2020-05-21 11:17:48 : Matching Known Biases, 0.009 mins elapsed.

Warning message in mclapply(..., mc.cores = threads, mc.preschedule = preschedule):
“2 function calls resulted in an error”
```

[log.log](https://github.com/GreenleafLab/ArchR/files/4664112/log.log)

**Comment by rcorces** [comment]
I'm not sure if we have enough information to solve this. When you say that this happens sometimes, does that mean you can run the same command on the same input and you get the error some times but not others? Or does it reproducibly happen on some input and not reproducibly happen on other input?

My suspicion is that this is a multi-threading issue.

**Comment by rcorces** [comment]
@rojinsafavi - let us know if we can help further on this. if not, feel free to close.
