### ISSUE TITLE
differentially expressed genes

### ISSUE THREAD

**Issue by feanaros** [GreenleafLab/ArchR#1632]
Hi developers! Thank you for this wonderful package! a very basic question I have. Is it possible to find differentially expressed genes using  getmarkerfeatures?

 markersGS <- getMarkerFeatures(ArchRProj = archrproject,
                                useMatrix = "GeneIntegrationMatrix",
                                groupBy = "Clusters",
usegroups= "Red_KO",
bdgGroups= "Red_WT"
                                bias= c("TSSEnrichment", "log10(nFrags)"),
                                testMethod = "wilcoxon",
                                binarize = F, 
                                maxCells = 1000) 

 markerList_genes <- getMarkers(markersGS, cutOff = "FDR <= 0.05 & Log2FC >= 0.5") 
 The markerlist genes resulting contains empty rows and 9 column. Where I'm wrong? Thanks!!!!!
F

**Comment by rcorces** [comment]
Hi @feanaros! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
Please note that this is not an Issue, but a Discussion and should have been posted there.
Presumably, the filters you have set via `cutOff` result in zero pass-filter features.
