### ISSUE TITLE
plotTSSEnrichment bug: abnormal TSS profile when combining samples

### ISSUE THREAD

**Issue by NoemieL** [GreenleafLab/ArchR#165]
First of all, thank you for this great package and the manual.
Thanks in advance for your help.
 
**Attach your log file**
ArchR-plotTSSEnrichment-6de55e32d0-Date-2020-05-21_Time-14-10-29.log
ArchR-createArrows-6de54ea78abe-Date-2020-05-21_Time-13-33-27.log

**Describe the bug**
I am running for the first time two ATACseq fragments files on the same ArchR project with obtaining strange TSS profile for one of the samples. I performed them separately and both TSS profiles look normal. I also performed the analysis with another fragment file and the problem persists. I also reinstall ArchR but the results are still the same, same results are observed in both Mac and Windows machine. 
As suggested I also recapitulate this behaviour with the tutorial dataset and the problem persists. Please find attached the files related to the tutorial dataset.

**To Reproduce**
ArchR_demo.R

**Expected behavior**
a clear peak in the center and a smaller shoulder peak right-of-center for all samples

**Screenshots**
QC-Sample-FragSizes-TSSProfile.pdf

**Session Info**
ArchR_demo.R

**Comment by NoemieL** [comment]
Sorry here the associated files:

[ArchR-plotTSSEnrichment-6de55e32d0-Date-2020-05-21_Time-14-10-29.log](https://github.com/GreenleafLab/ArchR/files/4664658/ArchR-plotTSSEnrichment-6de55e32d0-Date-2020-05-21_Time-14-10-29.log)

[ArchR-createArrows-6de54ea78abe-Date-2020-05-21_Time-13-33-27.log](https://github.com/GreenleafLab/ArchR/files/4664659/ArchR-createArrows-6de54ea78abe-Date-2020-05-21_Time-13-33-27.log)

[ArchR_demo.R.zip](https://github.com/GreenleafLab/ArchR/files/4664674/ArchR_demo.R.zip)

[QC-Sample-FragSizes-TSSProfile.pdf](https://github.com/GreenleafLab/ArchR/files/4664661/QC-Sample-FragSizes-TSSProfile.pdf)

**Comment by jgranja24** [comment]
Ok im looking into this. I just ran your code and this is my result
[QC-Sample-FragSizes-TSSProfile.pdf](https://github.com/GreenleafLab/ArchR/files/4665219/QC-Sample-FragSizes-TSSProfile.pdf)

**Comment by NoemieL** [comment]
This is strange. Maybe I miss a package or something. Is you have any idea, please, let me know. ThanksNoémie Envoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : jgranja24 <notifications@github.com> Date : 21/05/2020  17:08  (GMT-07:00) À : GreenleafLab/ArchR <ArchR@noreply.github.com> Cc : NoemieL <leblay.noemie@wanadoo.fr>, Author <author@noreply.github.com> Objet : Re: [GreenleafLab/ArchR] plotTSSEnrichment bug: abnormal TSS profile when combining samples (#165) 
Ok im looking into this. I just ran your code and this is my result
QC-Sample-FragSizes-TSSProfile.pdf

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/GreenleafLab/ArchR/issues/165#issuecomment-632390304",
"url": "https://github.com/GreenleafLab/ArchR/issues/165#issuecomment-632390304",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by rcorces** [comment]
I'm not sure that we have too many suggestions on this.
It looks like you macOS version is a bit old. You could try updating that and updating your installations of `gfortran` and `XQuartz` as outlined on the ArchR installation instructions.
I dont think that either Jeff or I have tested ArchR extensively on R version 4 yet so you could also downgrade your R installation (for example to the 3.6 major version)

**Comment by jgranja24** [comment]
Have you tried threads = 1?

**Comment by NoemieL** [comment]
Thanks for the suggestion! I have the last version of both gfortran and XQuartz, and my MacOS is not so old (High Sierra 10.13.6). So as suggested I installed a older version of R (version 3.6.3) and it is working well now. For jgranja24, yes I tried both with 1 an 2 threads before sending you the problem.

**Comment by rcorces** [comment]
Thats very interesting. I'm glad it is working in R 3.6.3 and your plots look normal now. We will try to reproduce the issue with R 4.0.0.
