### ISSUE TITLE
Specification of S4vectors::metadata in IterativeLSI.R and MatrixDeviations.R

### ISSUE THREAD

**Issue by ChrisTzaferis** [GreenleafLab/ArchR#1652]
Related to a previous issue: https://github.com/GreenleafLab/ArchR/issues/1492 that was fixed through a patch by specifying S4vectors::metadata, could you please do the same for the files:  IterativeLSI.R and MatrixDeviations.R?
The errors occurring only in R/shiny environment are the following:

simpleError in (function (cl, name, valueClass): 'history’ is not a slot in class “DFrame”
"Error :   Error in (function (cl, name, valueClass) : ‘history’ is not a slot in class “GRanges”\n"

**Comment by rcorces** [comment]
Hi @ChrisTzaferis! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
I've gone through the entire code base and tried to correct this issue via https://github.com/GreenleafLab/ArchR/commit/90ab415a936e74e037ea5f6eea63e70759bf77af. I've done so on a branch named `dev_metadata`. I would appreciate it if you could test it and report back. If it looks good, this branch will be merged into `dev` for incorporation into the next stable release.

**Comment by rcorces** [comment]
done via https://github.com/GreenleafLab/ArchR/commit/d3aaba6610bd187241c764c9e52d8c022007b2de

**Comment by rcorces** [comment]
merged in `dev` via https://github.com/GreenleafLab/ArchR/pull/1655
Closing but comment below if you run into additional related issues.
