### ISSUE TITLE
ERROR in Computing Doublet Statistics

### ISSUE THREAD

**Issue by ZunpengLiu** [GreenleafLab/ArchR#1659]
Hello,
Thank you very much for developing the helpful tool!
When I run the addDoubletScores only one sample (1/300) got the errors as follows,
```
> doubScores <- addDoubletScores(
  input = ArrowFiles,
  k = 10, #Refers to how many cells near a "pseudo-doublet" to count.
  knnMethod = "UMAP", #Refers to the embedding to use for nearest neighbor search with doublet projection.
  LSIMethod = 1
)
ArchR logging to : ArchRLogs/ArchR-addDoubletScores-2f2bd69d6d66a-Date-2022-10-01_Time-01-07-45.log
If there is an issue, please report to github with logFile!
2022-10-01 01:07:46 : Batch Execution w/ safelapply!, 0 mins elapsed.
2022-10-01 01:07:46 : D19-122591 (1 of 1) :  Computing Doublet Statistics, 0 mins elapsed.

************************************************************
2022-10-01 01:07:52 : ERROR Found in .computeLSI for  
LogFile = ArchRLogs/ArchR-addDoubletScores-2f2bd69d6d66a-Date-2022-10-01_Time-01-07-45.log

<simpleError in irlba::irlba(mat, nDimensions, nDimensions): max(nu, nv) must be strictly less than min(nrow(A), ncol(A))>

************************************************************


************************************************************
2022-10-01 01:07:52 : ERROR Found in .LSIPartialMatrix for  
LogFile = ArchRLogs/ArchR-addDoubletScores-2f2bd69d6d66a-Date-2022-10-01_Time-01-07-45.log

<simpleError in .logError(e, fn = ".computeLSI", info = "", errorList = errorList,     logFile = logFile): Exiting See Error Above>

************************************************************


************************************************************
2022-10-01 01:07:52 : ERROR Found in addIterativeLSI for D19-122591 (1 of 1) :  
LogFile = ArchRLogs/ArchR-addDoubletScores-2f2bd69d6d66a-Date-2022-10-01_Time-01-07-45.log

<simpleError in .logError(e, fn = ".LSIPartialMatrix", info = "", errorList = errorList,     logFile = logFile): Exiting See Error Above>

************************************************************

Error in .logError(e, fn = "addIterativeLSI", info = prefix, errorList = list(ArrowFile = ArrowFile),  : 
  Exiting See Error Above
```

[ArchR-addDoubletScores-2379a6dcd475e-Date-2022-09-30_Time-12-54-49.log](https://github.com/GreenleafLab/ArchR_2020/files/9686448/ArchR-addDoubletScores-2379a6dcd475e-Date-2022-09-30_Time-12-54-49.log)

I have generated the arrow file several times and repeated the operation "Computing Doublet Statistics". However, I got the same error above.

Do you have suggestions about this?

Thank you!

Zunpeng

**Comment by rcorces** [comment]
Hi @ZunpengLiu! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by ZunpengLiu** [comment]
I tried to decrease the minTSS from 6 to 4 when I generated the Arrowfiles. And, the error is now solved.

**Comment by ZunpengLiu** [comment]
I tried to decrease the minTSS from 6 to 4 when I generated the Arrowfiles. And, the error is now solved.
