### ISSUE TITLE
sinto for some pre-ArchR-ing of BAM to Fragments

### ISSUE THREAD

**Issue by badoi** [GreenleafLab/ArchR#166]
Section 1.4 could point to the `sinto`[https://timoast.github.io/sinto/index.html] package to process mapped .bam files into 10x-esque fragments file. Seems Tim Stuart et al. have realized the 10x Fragments format could be a desirable format for non-10x scATAC-seq experiments to use turn-key solutions built for fragments input. I'm sure this would resolve some questions/concerns about pre-processing .bam files for input into arrow files (and provide some option for testing both versions of making arrow files).

**Comment by jgranja24** [comment]
ArchR can already take as input bam files. This is an unnecessary step and will result in a slower analysis. ArchR should be able to create an ArrowFile from bam faster than that tool can go from bam to fragments. We will add more documentation to using bam files but the usage is extremely efficient.

**Comment by jgranja24** [comment]
Closing this issue feel free to open if you have further questions or issues.

**Comment by badoi** [comment]
Good point!
