### ISSUE TITLE
installation of ArchR issues

### ISSUE THREAD

**Issue by lwh2dna** [GreenleafLab/ArchR#1691]
Hi,

I'm trying to install ArchR, but I have some dependency problems. I'm using a Mac, and I have installed GNU Fortran,  XQuartz and GNU Scientific Library (GSL). But when I run [devtools::install_github("GreenleafLab/ArchR", ref="master", repos = BiocManager::repositories())], it says 

"ERROR: dependencies ‘motifmatchr’, ‘chromVAR’, ‘Rsamtools’ are not available for package ‘ArchR’". 

Could you help to solve this problem, please? Thank you very much!

Best

**Comment by rcorces** [comment]
Hi @lwh2dna! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
try installing the packages that are mentioned (motifmatchr, chromVAR, Rsamtools)

**Comment by lwh2dna** [comment]
Thank you very much for your reply. The entire error message is below. Do you think it is the problem with the packages or some other problems?

* installing *source* package ‘Rhtslib’ ...
** using non-staged installation via StagedInstall field
** libs
cd "htslib-1.7" && make -f "/Library/Frameworks/R.framework/Resources/etc/Makeconf" -f "Makefile.Rhtslib"
Makefile.Rhtslib:131: warning: overriding commands for target `.c.o'
/Library/Frameworks/R.framework/Resources/etc/Makeconf:168: warning: ignoring old commands for target `.c.o'
clang -arch arm64 -falign-functions=64 -Wall -g -O2 -fpic -I. -I/opt/R/arm64/include -D_FILE_OFFSET_BITS=64 -c -o kfunc.o kfunc.c
clang -arch arm64 -falign-functions=64 -Wall -g -O2 -fpic -I. -I/opt/R/arm64/include -D_FILE_OFFSET_BITS=64 -c -o knetfile.o knetfile.c
clang -arch arm64 -falign-functions=64 -Wall -g -O2 -fpic -I. -I/opt/R/arm64/include -D_FILE_OFFSET_BITS=64 -c -o kstring.o kstring.c
clang -arch arm64 -falign-functions=64 -Wall -g -O2 -fpic -I. -I/opt/R/arm64/include -D_FILE_OFFSET_BITS=64 -c -o bcf_sr_sort.o bcf_sr_sort.c
clang -arch arm64 -falign-functions=64 -Wall -g -O2 -fpic -I. -I/opt/R/arm64/include -D_FILE_OFFSET_BITS=64 -c -o bgzf.o bgzf.c
bgzf.c:1026:16: warning: variable 'size' set but not used [-Wunused-but-set-variable]
    int count, size = 0, block_length, remaining;
               ^
1 warning generated.
clang -arch arm64 -falign-functions=64 -Wall -g -O2 -fpic -I. -I/opt/R/arm64/include -D_FILE_OFFSET_BITS=64 -c -o errmod.o errmod.c
clang -arch arm64 -falign-functions=64 -Wall -g -O2 -fpic -I. -I/opt/R/arm64/include -D_FILE_OFFSET_BITS=64 -c -o faidx.o faidx.c
clang -arch arm64 -falign-functions=64 -Wall -g -O2 -fpic -I. -I/opt/R/arm64/include -D_FILE_OFFSET_BITS=64 -c -o hfile.o hfile.c
clang -arch arm64 -falign-functions=64 -Wall -g -O2 -fpic -I. -I/opt/R/arm64/include -D_FILE_OFFSET_BITS=64 -c -o hfile_net.o hfile_net.c
echo '#define HTS_VERSION "1.7"' > version.h
clang -arch arm64 -falign-functions=64 -Wall -g -O2 -fpic -I. -I/opt/R/arm64/include -D_FILE_OFFSET_BITS=64 -c -o hts.o hts.c
clang -arch arm64 -falign-functions=64 -Wall -g -O2 -fpic -I. -I/opt/R/arm64/include -D_FILE_OFFSET_BITS=64 -c -o hts_os.o hts_os.c
clang -arch arm64 -falign-functions=64 -Wall -g -O2 -fpic -I. -I/opt/R/arm64/include -D_FILE_OFFSET_BITS=64 -c -o md5.o md5.c
clang -arch arm64 -falign-functions=64 -Wall -g -O2 -fpic -I. -I/opt/R/arm64/include -D_FILE_OFFSET_BITS=64 -c -o multipart.o multipart.c
clang -arch arm64 -falign-functions=64 -Wall -g -O2 -fpic -I. -I/opt/R/arm64/include -D_FILE_OFFSET_BITS=64 -c -o probaln.o probaln.c
clang -arch arm64 -falign-functions=64 -Wall -g -O2 -fpic -I. -I/opt/R/arm64/include -D_FILE_OFFSET_BITS=64 -c -o realn.o realn.c
clang -arch arm64 -falign-functions=64 -Wall -g -O2 -fpic -I. -I/opt/R/arm64/include -D_FILE_OFFSET_BITS=64 -c -o regidx.o regidx.c
clang -arch arm64 -falign-functions=64 -Wall -g -O2 -fpic -I. -I/opt/R/arm64/include -D_FILE_OFFSET_BITS=64 -c -o sam.o sam.c
clang -arch arm64 -falign-functions=64 -Wall -g -O2 -fpic -I. -I/opt/R/arm64/include -D_FILE_OFFSET_BITS=64 -c -o synced_bcf_reader.o synced_bcf_reader.c
clang -arch arm64 -falign-functions=64 -Wall -g -O2 -fpic -I. -I/opt/R/arm64/include -D_FILE_OFFSET_BITS=64 -c -o vcf_sweep.o vcf_sweep.c
clang -arch arm64 -falign-functions=64 -Wall -g -O2 -fpic -I. -I/opt/R/arm64/include -D_FILE_OFFSET_BITS=64 -c -o tbx.o tbx.c
clang -arch arm64 -falign-functions=64 -Wall -g -O2 -fpic -I. -I/opt/R/arm64/include -D_FILE_OFFSET_BITS=64 -c -o textutils.o textutils.c
clang -arch arm64 -falign-functions=64 -Wall -g -O2 -fpic -I. -I/opt/R/arm64/include -D_FILE_OFFSET_BITS=64 -c -o thread_pool.o thread_pool.c
clang -arch arm64 -falign-functions=64 -Wall -g -O2 -fpic -I. -I/opt/R/arm64/include -D_FILE_OFFSET_BITS=64 -c -o vcf.o vcf.c
vcf.c:641:14: warning: variable 'needs_sync' set but not used [-Wunused-but-set-variable]
    int len, needs_sync = 0, done = 0;
             ^
vcf.c:2826:50: warning: variable 'ret' set but not used [-Wunused-but-set-variable]
    int i, ndst_ori = dst->nhrec, need_sync = 0, ret = 0;
                                                 ^
2 warnings generated.
clang -arch arm64 -falign-functions=64 -Wall -g -O2 -fpic -I. -I/opt/R/arm64/include -D_FILE_OFFSET_BITS=64 -c -o vcfutils.o vcfutils.c
clang -arch arm64 -falign-functions=64 -Wall -g -O2 -fpic -I. -I/opt/R/arm64/include -D_FILE_OFFSET_BITS=64 -c -o cram/cram_codecs.o cram/cram_codecs.c
cram/cram_codecs.c:1268:19: warning: variable 'ntot' set but not used [-Wunused-but-set-variable]
    int nvals, i, ntot = 0, max_val = 0, min_val = INT_MAX, k;
                  ^
1 warning generated.
clang -arch arm64 -falign-functions=64 -Wall -g -O2 -fpic -I. -I/opt/R/arm64/include -D_FILE_OFFSET_BITS=64 -c -o cram/cram_decode.o cram/cram_decode.c
clang -arch arm64 -falign-functions=64 -Wall -g -O2 -fpic -I. -I/opt/R/arm64/include -D_FILE_OFFSET_BITS=64 -c -o cram/cram_encode.o cram/cram_encode.c
clang -arch arm64 -falign-functions=64 -Wall -g -O2 -fpic -I. -I/opt/R/arm64/include -D_FILE_OFFSET_BITS=64 -c -o cram/cram_external.o cram/cram_external.c
clang -arch arm64 -falign-functions=64 -Wall -g -O2 -fpic -I. -I/opt/R/arm64/include -D_FILE_OFFSET_BITS=64 -c -o cram/cram_index.o cram/cram_index.c
clang -arch arm64 -falign-functions=64 -Wall -g -O2 -fpic -I. -I/opt/R/arm64/include -D_FILE_OFFSET_BITS=64 -c -o cram/cram_io.o cram/cram_io.c
cram/cram_io.c:61:10: fatal error: 'lzma.h' file not found
#include <lzma.h>
         ^~~~~~~~
1 error generated.
make[1]: *** [cram/cram_io.o] Error 1
make: *** [htslib] Error 2
ERROR: compilation failed for package ‘Rhtslib’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/Rhtslib’
ERROR: dependency ‘Rhtslib’ is not available for package ‘Rsamtools’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/Rsamtools’
ERROR: dependency ‘Rsamtools’ is not available for package ‘GenomicAlignments’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/GenomicAlignments’
ERROR: dependencies ‘Rsamtools’, ‘GenomicAlignments’ are not available for package ‘rtracklayer’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/rtracklayer’
ERROR: dependencies ‘rtracklayer’, ‘GenomicAlignments’ are not available for package ‘CNEr’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/CNEr’
ERROR: dependencies ‘rtracklayer’, ‘Rsamtools’ are not available for package ‘BSgenome’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/BSgenome’
ERROR: dependencies ‘BSgenome’, ‘CNEr’, ‘rtracklayer’ are not available for package ‘TFBSTools’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/TFBSTools’
ERROR: dependencies ‘TFBSTools’, ‘Rsamtools’, ‘BSgenome’ are not available for package ‘chromVAR’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/chromVAR’
ERROR: dependencies ‘TFBSTools’, ‘BSgenome’, ‘Rsamtools’ are not available for package ‘motifmatchr’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/motifmatchr’

The downloaded source packages are in
	‘/private/var/folders/yy/8mfvh7xj77d4tbr83h0gsz980000gq/T/Rtmp1NyPtp/downloaded_packages’
✔  checking for file ‘/private/var/folders/yy/8mfvh7xj77d4tbr83h0gsz980000gq/T/Rtmp1NyPtp/remotes116f41babd684/GreenleafLab-ArchR-79953a9/DESCRIPTION’ ...
─  preparing ‘ArchR’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘ArchR_1.0.2.tar.gz’
   Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
     storing paths of more than 100 bytes is not portable:
     ‘ArchR/.github/ISSUE_TEMPLATE/bug-error-report---no-usage-questions---feature-requests--use-discussions--.md’
   
ERROR: dependencies ‘motifmatchr’, ‘chromVAR’, ‘Rsamtools’ are not available for package ‘ArchR’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/ArchR’
Warning messages:
1: In i.p(...) :
  installation of package ‘Rhtslib’ had non-zero exit status
2: In i.p(...) :
  installation of package ‘Rsamtools’ had non-zero exit status
3: In i.p(...) :
  installation of package ‘GenomicAlignments’ had non-zero exit status
4: In i.p(...) :
  installation of package ‘rtracklayer’ had non-zero exit status
5: In i.p(...) : installation of package ‘CNEr’ had non-zero exit status
6: In i.p(...) :
  installation of package ‘BSgenome’ had non-zero exit status
7: In i.p(...) :
  installation of package ‘TFBSTools’ had non-zero exit status
8: In i.p(...) :
  installation of package ‘chromVAR’ had non-zero exit status
9: In i.p(...) :
  installation of package ‘motifmatchr’ had non-zero exit status
10: In i.p(...) :
  installation of package ‘/var/folders/yy/8mfvh7xj77d4tbr83h0gsz980000gq/T//Rtmp1NyPtp/file116f44de672af/ArchR_1.0.2.tar.gz’ had non-zero exit status

**Comment by lwh2dna** [comment]
Could you provide some guidance on how to install motifmatchr, chromVAR, Rsamtools, please? Thank you very much!

**Comment by rcorces** [comment]
Sorry that you are having trouble installing ArchR's dependencies. Your best bet is to google the errors you receive or post on other generic forums for assistance in installing those dependencies as we do not maintain them.
