### ISSUE TITLE
plotPeak2GeneHeatmap error

### ISSUE THREAD

**Issue by wangmhan** [GreenleafLab/ArchR#1700]
[ArchR-plotPeak2GeneHeatmap-1761ee8fa18-Date-2022-10-27_Time-09-13-15.log](https://github.com/GreenleafLab/ArchR/files/9876635/ArchR-plotPeak2GeneHeatmap-1761ee8fa18-Date-2022-10-27_Time-09-13-15.log)

Hi, thank you for the amazing package. I used it a lot in my scATAC-seq data analysis.
But now when I tried to generate heatmap with previously saved ArchR projects, it gave me error like this: Error in do_one(nmeth) : NA/NaN/Inf in foreign function call (arg 1) 

I tried to plot plotPeak2GeneHeatmap with previously saved ArchR projects, some projects went well but others failed. I am confused.

Here is the code I used, also attached log file:
proj <- loadArchRProject(path=paste0("/s*/home/t*/w*/scATAC/identifyRE/limb_L21_mesenchyme"))
p2 <- plotPeak2GeneHeatmap(ArchRProj = proj, groupBy = "annotation",
                           corCutOff = 0.45,FDRCutOff = 1e-04, verbose = FALSE)
p2

I always use the same command to save ArchR project. Have no idea what's going wrong.

Thank you in advance!

**Comment by rcorces** [comment]
Hi @wangmhan! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
Maybe try re-adding your peak-to-gene links using `addPeak2GeneLinks()`. Then try plotting again

**Comment by wangmhan** [comment]
Hi, it works. Thanks a lot!
