### ISSUE TITLE
species of "addMotifAnnotations"

### ISSUE THREAD

**Issue by chen-zhan** [GreenleafLab/ArchR#1710]
### Discussed in https://github.com/GreenleafLab/ArchR/discussions/1709

<div type='discussions-op-text'>

<sup>Originally posted by **chen-zhan** November  1, 2022</sup>
Hi, I was confused when I use "addMotifAnnotations". I got same error.
`> proj <- addMotifAnnotations(ArchRProj = proj, motifSet = "cisbp", name = "Motif", species="drosophila melanogaster")

ArchR logging to : ArchRLogs/ArchR-addMotifAnnotations-421756ec692a-Date-2022-11-01_Time-10-14-54.log
If there is an issue, please report to github with logFile!
2022-11-01 10:15:06 : Getting Motif Set, Species : drosophila melanogaster, 0.166 mins elapsed.
Error in addMotifAnnotations(ArchRProj = proj, motifSet = "cisbp", name = "Motif",  :
  Species not recognized homo sapiens, mus musculus supported by CisBP!
`
We used the genome built by ourselves. So I don't know how run it
</div>

**Comment by rcorces** [comment]
Hi @chen-zhan! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
answered in #1709
