### ISSUE TITLE
Making doubScores and ArchRProject are same issue with outputDirectory cannot have a space in the full path

### ISSUE THREAD

**Issue by ZayaAyush** [GreenleafLab/ArchR#1713]
Thank you for your great job. I am starting to do ArchR analysis, but I have trouble running doubScores and ArchRProject functions.
Could you resolve these problems?
###Running below comment with error
doubScores <- addDoubletScores(
    input = ArrowFiles,
    k = 10, #Refers to how many cells near a "pseudo-doublet" to count.
    knnMethod = "UMAP", #Refers to the embedding to use for nearest neighbor search with doublet projection.
    LSIMethod = 1,
)
ArchR logging to : ArchRLogs/ArchR-addDoubletScores-1faf2fa0b6c2-Date-2022-11-02_Time-14-12-57.log
If there is an issue, please report to github with logFile!
2022-11-02 14:12:57 : Batch Execution w/ safelapply!, 0 mins elapsed.
2022-11-02 14:12:57 : IGF1_2_atac (1 of 2) :  Computing Doublet Statistics, 0 mins elapsed.
Error in ArchRProject(ArrowFiles = ArrowFile, outputDirectory = tmpDir,  : 
  outputDirectory cannot have a space in the full path! Full path : /Users/Documents/4_ATAC Multiomics analysis/ArchRanalysisofscATAC/All/tmp/tmp-1faf603e92fb-Date-2022-11-02_Time-14-12-57

###Running below comment with error
projATAC1 <- ArchRProject(
  ArrowFiles = ArrowFiles, 
  outputDirectory = "~/Documents/4_ATAC Multiomics analysis/ArchRanalysisofscATAC/All/ArchROut",
  copyArrows = TRUE #This is recommened so that if you modify the Arrow files you have an original copy for later usage.
)

Using GeneAnnotation set by addArchRGenome(Mm10)!
Using GeneAnnotation set by addArchRGenome(Mm10)!
Error in ArchRProject(ArrowFiles = ArrowFiles, outputDirectory = "~/Documents/4_ATAC Multiomics analysis/ArchRanalysisofscATAC/All",  : 
  outputDirectory cannot have a space in the path! Path : ~/Documents/4_ATAC Multiomics analysis/ArchRanalysisofscATAC/All

Any suggestions would be helpful! Thank you
Zaya
[ArchR-createArrows-1faf4999d531-Date-2022-11-02_Time-11-51-06.log](https://github.com/GreenleafLab/ArchR/files/9923138/ArchR-createArrows-1faf4999d531-Date-2022-11-02_Time-11-51-06.log)

**Comment by rcorces** [comment]
Hi @ZayaAyush! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
Please make sure to read carefully all errors reported. In your case, this is extremely specific.

```
outputDirectory cannot have a space in the path! Path : ~/Documents/4_ATAC Multiomics analysis/ArchRanalysisofscATAC/All
```
