### ISSUE TITLE
No peaks found for getMarkerFeatures

### ISSUE THREAD

**Issue by jamrute** [GreenleafLab/ArchR#1715]
Thank you for making this package.

I have generated Multiome data, annotated nuclei from RNA information, and called peaks with MACS2 on these clusters. When I use `getMarkerFeatures ` to find marker peaks across clusters I get very few peaks identified and I am unsure why this is the case. I have attached what my heatmap looks like as well as the peak call. Only one population has a lot of marker peaks while others have almost none. I have also attached the ATAC UMAP with the RNA cluster annotations.
[Peak-Call-Summary.pdf](https://github.com/GreenleafLab/ArchR/files/9924853/Peak-Call-Summary.pdf)
[Peak-Marker_noMax-Heatmap.pdf](https://github.com/GreenleafLab/ArchR/files/9924854/Peak-Marker_noMax-Heatmap.pdf)

Thank you for your help.

[Peak-Call-Summary.pdf](https://github.com/GreenleafLab/ArchR/files/9924856/Peak-Call-Summary.pdf)
[Peak-Marker_noMax-Heatmap.pdf](https://github.com/GreenleafLab/ArchR/files/9924857/Peak-Marker_noMax-Heatmap.pdf)
[Plot-UMAP_ATAC_HARMONY-Sample-Clusters_HAR-celltypeRNA-HAR.pdf](https://github.com/GreenleafLab/ArchR/files/9924858/Plot-UMAP_ATAC_HARMONY-Sample-Clusters_HAR-celltypeRNA-HAR.pdf)

**Comment by rcorces** [comment]
Hi @jamrute! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by jamrute** [comment]
Sorry, I will move to Discussions section!
