### ISSUE TITLE
To integrate skin scRNA and scATAC data in ArchR

### ISSUE THREAD

**Issue by ZayaAyush** [GreenleafLab/ArchR#1722]
Thank you for your great job. I have difficulty integrating my scATAC-seq  skin data into scRNA skin data in ArchR. It was annotated well SignacSatija (https://stuartlab.org/signac/articles/pbmc_multiomic.html). I couldn't find the detailed tutorial on how to generate from Seurat R object to RangedSummarizedExperiment object. 
scRNA object: Stroma
An object of class Seurat 
51216 features across 33765 samples within 3 assays 
Active assay: integrated (3000 features, 3000 variable features)
 2 other assays present: RNA, SCT
 2 dimensional reductions calculated: pca, umap

projATAC2 <- addGeneIntegrationMatrix(
ArchRProj = projATAC2,
useMatrix = "GeneScoreMatrix",
matrixName = "GeneIntegrationMatrix",
reducedDims = "IterativeLSI",
seRNA = Stroma,
addToArrow = FALSE,
groupRNA = "seurat_clusters",
nameCell = "predictedCell_Un",
nameGroup = "predictedGroup_Un",
nameScore = "predictedScore_Un"
)
p1 <- plotEmbedding(projATAC2, name = "predictedGroup_Un")
p2 <- plotEmbedding(projATAC2, name = "predictedScore_Un")
plotPDF(ggAlignPlots(p1, p2, type="h", draw=FALSE), width = 12, height = 6)

The integration didn't match at all, shall I skip the integration step? It is able to rename all clusters using top marker genes in scATAC ArchR data.
If I want to skip this part, the "Making Pseudo-bulk Replicates" part was required to define by scRNA-seq data (groupBy = "Clusters2").
Any suggestions would be helpful. Thank you
Zaya

**Comment by rcorces** [comment]
Hi @ZayaAyush! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.
