### ISSUE TITLE
Error in (function (filename = "Rplot%03d.png", width = 480, height = 480,  :    unable to start device 'png'

### ISSUE THREAD

**Issue by TauHHCC** [GreenleafLab/ArchR#1725]
Hi, when I using ArchR I met this error

> draw(heatmapPeaks, heatmap_legend_side = "bot", annotation_legend_side = "bot")

Error in (function (filename = "Rplot%03d.png", width = 480, height = 480,  : 
  unable to start device 'png'
In addition: Warning message:
In (function (filename = "Rplot%03d.png", width = 480, height = 480,  :
  cairo error 'invalid value (typically too big) for the size of the input (surface, pattern, etc.)'

Has some one got same error? And how do you solve this problem?

Best
![Screenshot_2022-11-07_15-17-18](https://user-images.githubusercontent.com/113095697/200333270-77dd6afe-e403-4dad-840a-07ab329c5cca.png)

**Comment by rcorces** [comment]
Hi @TauHHCC! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
Closing issue as initial questions were not answered.

**Comment by TauHHCC** [comment]
Hi Rcoces

Sorry for delay. It took me a bit of time. 
I have searched online, but didn't get a way to solve the problem.  

It looks it only happened when I try to plot heatmap of peaks. When I plot heatmap of marker genes, it was fine.

I have attached the log files for the step it gives issue. Please have a look.

Sorry, I'm not good at computer handling. 

[ArchR-plotMarkerHeatmap-233e511f793d-Date-2022-12-01_Time-10-17-55.log](https://github.com/GreenleafLab/ArchR/files/10131056/ArchR-plotMarkerHeatmap-233e511f793d-Date-2022-12-01_Time-10-17-55.log)

**Comment by TauHHCC** [comment]
Hi,
Problem solved by 
https://github.com/GreenleafLab/ArchR/issues/830
