### ISSUE TITLE
Incorrect blacklist overlap calculations in TileMatrix

### ISSUE THREAD

**Issue by bnprks** [GreenleafLab/ArchR#1741]
**Describe the bug**
ArchR's TileMatrix calculations try to zero-out tiles overlapping blacklist regions. The code sometimes gets the boundary wrong for which tiles overlap blacklist regions.

**To Reproduce**
The relevant code is at [MatrixTiles.R L245-L260](https://github.com/GreenleafLab/ArchR/blob/master/R/MatrixTiles.R#L245-L260)

Consider the second element in the hg38 blacklist:
```R
> genomeAnnoHg38$blacklist[2]
GRanges object with 1 range and 2 metadata columns:
      seqnames          ranges strand | Buenrostro    Encode
         <Rle>       <IRanges>  <Rle> |  <logical> <logical>
  [1]     chr1 5850088-5850571      * |       TRUE     FALSE
  -------
  seqinfo: 24 sequences from an unspecified genome; no seqlengths
```

We would expect this to overlap the 500bp tiles starting at coordinates 5850000 and 5850500. If we divide by 500 and add 1 to get the tile indexes, this translates to tile index 11701 and 11702. What we actually see with the ArchR code is:
```R
> tileSize <- 500
> tile2 <- floor(tileSize/2)
> blacklistz <- genomeAnnoHg38$blacklist[2]
> blacklistIdx <- unique(trunc(start(unlist(GenomicRanges::slidingWindows(blacklistz,tile2,tile2)))/tileSize) + 1)
> blacklistIdx
[1] 11701
```
Notice that the ArchR code only considers the start of the sliding windows for determining overlapping tiles, so it does not detect tiles that only overlap the end of the blacklist region

For 500bp tiles, this bug is equivalent to modifying the blacklist by setting widths according to the following formula:
```R
width(blacklist) <- ((width(blacklist) - 1) %/% 250) * 250 + 1
```

**Comment by rcorces** [comment]
Hi @bnprks! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
Thanks for reporting this. Though this hurts my brain a bit, I __think__ this solves the bug, effectively checking at both the start and end. Please let me know if you agree.
https://github.com/GreenleafLab/ArchR/commit/87daa9c193e0e181a83509bb12acbb88df246ec7

**Comment by bnprks** [comment]
I might suggest a slightly simpler logic to accomplish the same task:
```R
# Convert blacklist into "tile" coordinates (where each base represents a tile)
start(blacklistz) <- (start(blacklistz) %/% tileSize) + 1
end(blacklistz) <- (end(blacklistz) %/% tileSize) + 1
# Compute list of tiles within each blacklist region
blacklistIdx <- unlist(start(GenomicRanges::slidingWindows(blacklistz, 1, 1)))
```

I believe your linked code is also correct, though it's a bit harder to reason about in my opinion. 
I think the original code you were adapting was already a little overcomplicated for the task. (e.g. there's no reason for the `tile2` variable to exist)

**Comment by rcorces** [comment]
That does make more sense to me. The other method was painful to think about.
I've tested this on my end and it works fine. This has been merged into `dev`. Thanks again for reporting.
