### ISSUE TITLE
difference in Peak heights visualization in browser for same gene on plotting ! 

### ISSUE THREAD

**Issue by ankushs0128** [GreenleafLab/ArchR#1752]
Plotting ( and re-plotting)  peaks for same gene is showing a subtle differences in height for peaks . 
What could be the potential reason for this and How can this be fixed? 

 set.seed() is already implemented code 

![597D52E3-8AF0-47D4-B2DA-666028357D69](https://user-images.githubusercontent.com/32255128/203890462-80b47b32-7091-4be1-abc8-6b400f275319.jpeg)
 
Differences can be visualized here also for genes -  
https://cancell.medisin.uio.no/ShinyArchR.UiO/

Highly appreciate any information ! 
 
thanks in advance

**Comment by rcorces** [comment]
Hi @ankushs0128! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
Presumably this:
https://github.com/GreenleafLab/ArchR/issues/1555
Closing but feel free to comment here if this doesnt address your concern.
