### ISSUE TITLE
Issue with createArrowFiles - doesn't work for all inputFiles only a subset

### ISSUE THREAD

**Issue by rstaupe** [GreenleafLab/ArchR#177]
**Attach your log file**
[ArchR-createArrows-6ff34796fe73-Date-2020-05-27_Time-15-07-13.log](https://github.com/GreenleafLab/ArchR/files/4691541/ArchR-createArrows-6ff34796fe73-Date-2020-05-27_Time-15-07-13.log)

Hello,

I'm attempting to create Arrow files from a custom created genome. I've successfully created the geneAnnotation and genomeAnnotation. However, when I go to run createArrowFiles for my samples, only a subset of samples are successfully made into Arrow files. For the samples that fail, it seems that all the samples are encountering an error at the .addTileMat step of creating Arrow files. I'm unsure of what the exact issue seems to be and I could use some help troubleshooting this bug. 

My call to createArrowFiles is below:
ArrowFiles <- createArrowFiles(
  inputFiles = inputFiles,
  sampleNames = names(inputFiles),
  geneAnnotation = geneAnnotation,
  genomeAnnotation = genomeAnnotation,
  filterTSS = 4, #Dont set this too high because you can always increase later
  filterFrags = 1000, 
  addTileMat = TRUE,
  addGeneScoreMat = TRUE
)

If it helps, I'm running the development branch of ArchR (dev_051120) because of the issues in this post: https://github.com/GreenleafLab/ArchR/issues/112. 

Thanks for your help!

**Comment by jgranja24** [comment]
Sorry for the delay i am looking into whats going on. Seems like matrix creation the dimensions are off. I wonder if there are no frags detected...

**Comment by rstaupe** [comment]
No worries. Thanks for your help in addressing what's going on. 

If it helps, the cellranger output summary suggest that fragments are detected in all the samples for which the Arrow files are successfully and unsuccessfully being generated (10,699 median fragments per cell for BM-LN-1 which failed). It also seems to not be a sample/tisse/replicate issue as I have successful arrow files from each of the tissues, subjects, and replicates that I'm trying to generate arrow files from. 

Please let me know if you need any additional information from me that will be helpful in figuring out what's going on!

**Comment by rstaupe** [comment]
I wanted to leave some updates of things that I've tried to troubleshoot what's going on with no success.

1) I noticed that the samples that failed tended to group by a batch variable in the initial cellranger-atac mkfastq. I reran cellranger-atac mkfastq and cellranger-atac count to regenerate the fragment files. I then reran create ArrowFiles on all my newly re-ran samples and the same samples failed again. Note: all the samples pass cellranger alignments and counting as expected. 

2) I've decided to focus on two samples that are replicates from the same subject because one succeeds in making arrow files whereas the other doesn't. For these two samples, some of the other github issues stated that chr* needs to be at the front of each entry in the chromosome column of the fragments files so I appended chr onto the chromosome number in copies of my fragments files. I then reformatted the fragments files with reformatFragmentFiles() and ran createArrowFiles() with the below call:

ArrowFiles <- createArrowFiles(
  inputFiles = inputFiles,
  sampleNames = names(inputFiles),
  geneAnnotation = geneAnnotation, # this is a custom Rhesus genome annotation
  genomeAnnotation = genomeAnnotation, # this is a custom Rhesus genome
  filterTSS = 4, #Dont set this too high because you can always increase later
  filterFrags = 1000, 
  addTileMat = TRUE,
  addGeneScoreMat = TRUE
)

Which again failed with the same issues at the addTileMat step. Log here:
[ArchR-createArrows-507b65da887b-Date-2020-06-25_Time-19-59-28.log](https://github.com/GreenleafLab/ArchR/files/4838091/ArchR-createArrows-507b65da887b-Date-2020-06-25_Time-19-59-28.log)

However, if I run createArrowFiles with the same above call and set addTileMat = FALSE everything runs to completion and I get .arrow files as a result. 

From your earlier comments @jgranja24, I checked the fragments files that were used as input for fragments on each chromosome.  From the below results, it looks like there are fragments detected on each chromosome for both samples. * is the reformatted fragments files for each sample.

Sample 1 (successful sample)
$ zcat * | awk -F '\t' '{print $1}' |  uniq -c
25030076 chr1
11746698 chr10
13671896 chr11
11863507 chr12
10767594 chr13
13822566 chr14
11615942 chr15
10811559 chr16
7653849 chr17
6095173 chr18
10561158 chr19
18666269 chr2
9846083 chr20
18550031 chr3
16637672 chr4
15075341 chr5
16197972 chr6
18186192 chr7
13524812 chr8
13014366 chr9
6912652 chrX
 350164 chrY

Sample 2 (unsuccessful sample)
$ zcat  * |  awk -F '\t' '{print $1}' |  uniq -c
24902047 chr1
11592319 chr10
13718220 chr11
11704507 chr12
10742125 chr13
13742520 chr14
11641644 chr15
10885057 chr16
7569204 chr17
6088913 chr18
10680893 chr19
18260397 chr2
9677950 chr20
18508777 chr3
16775144 chr4
15073392 chr5
16086316 chr6
17756105 chr7
13168277 chr8
12919683 chr9
6944000 chrX
 342080 chrY

I'm not sure what else to try to figure out what's going on. I think it would be worth checking whether fragments exist for each chromosome in the filtered samples but I'm not sure how best to do this. Any thoughts on next steps to troubleshoot the addTileMatrix step?

Thanks again for your help!

**Comment by rstaupe** [comment]
I was finally able to successfully generate the .arrow files from my samples. Unfortunately, the solution was to re-align the samples using cellranger-atac to an older genome release. Now, all my samples are completing createArrowFiles() successfully. Not sure what the exact issue is between the genome releases. Thanks for your help! I'm going to close the issue.

**Comment by hisplan** [comment]
@rstaupe I'm having a similar issue at the `addTileMatrix` step. Which version of cellranger-atac are you using? And which genome release worked and not worked for you? Thanks!

**Comment by rstaupe** [comment]
@hisplan I'm using cellranger-atac v1.1.0 for doing the alignment/counting. For the genomes, I'm working with samples from Rhesus macaques and I've tried Mmul10 Ensembl v99 and Mmul10 Ensembl v100 which didn't work. Rolling back to the Mmul8 Ensembl v97 genome release and annotation solved the issues that I was having. However, it's still unclear to me why some of the samples completed arrow file creation successfully with the newest genome release whereas half of them did not. Hope this helps!

**Comment by yding9** [comment]
@rstaupe Hi, we're also working with samples from Rhesus macaques and observing the same/similar errors. I plan to roll back to the Mmul8 and give it a shot. Could you give us more detailed advise on this issue or any workaround you have developed? Any help is highly appreciated!
