### ISSUE TITLE
Cairo check shows Cairo is not functional

### ISSUE THREAD

**Issue by AntoniaChroni** [GreenleafLab/ArchR#1770]
WARNING : Cairo check shows Cairo is not functional.
          ggplot2 rasterization will not be available without Cario.
          This may cause issues editing plots with many thousands of points from single cells.
Warning message:
In (function (display = "", width, height, pointsize, gamma, bg,  :
  unable to open connection to X11 display ''

**Comment by rcorces** [comment]
Hi @AntoniaChroni! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
This is a warning and not an error. ArchR uses Cairo for plot rasterization. ArchR is telling you that Cairo isnt functional so it wont be able to rasterize plots. The solution is to install Cairo.
https://www.cairographics.org/

**Comment by AntoniaChroni** [comment]
I have Cairo installed. For some reason it doesn't load successfully every time that I load ArchR. 
Log out/log in again helps.

**Comment by rcorces** [comment]
Cairo is both a system library and an R library. But if it is sometimes working and sometimes not, then I imagine it is installed properly and there is some other issue on your system. However, this is not likely to be an issue with ArchR.
