### ISSUE TITLE
Integration with scRNA

### ISSUE THREAD

**Issue by AntoniaChroni** [GreenleafLab/ArchR#1771]
I have patient samples together with a control group. Batch effect is overwhelming even after harmonized the data.
This results to cell types belong to multiple clusters. When I try to integrate with scRNA I am getting the following issue, which I am guessing is related to exactly what I mentioned previously, i.e., having different cell types belonging to multiple clusters. What is your suggestion in these cases?

Error in addGeneIntegrationMatrix(ArchRProj = proj, useMatrix = "GeneScoreMatrix",  : 
  Missing 0 cells. Found 10849 overlapping cells from ArchRProj in groupList! Cannot have overlapping/missing cells in ATAC input, check 'groupList' argument!

**Comment by rcorces** [comment]
Hi @AntoniaChroni! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
Closing as the follow up requests (log file, tutorial success, etc) were not fulfilled.
