### ISSUE TITLE
Error with addTrajectory 

### ISSUE THREAD

**Issue by Ping-lin14** [GreenleafLab/ArchR#1788]
Hi

I have a problem, I can't run `addTrajectory` after embedding an AcrhR object using a UMAP generated by Seurat.

I add UMAP coordinates (UMAP_se) according to #455.
But  I can't run `addTrajectory`.
```
trajectory <- c("0hr", "24hr")
trajectory

projCD8 <- addTrajectory(
  ArchRProj = projCD8, 
  name = "CarTU", 
  groupBy = "Sample",
  trajectory = trajectory, 
  embedding = "UMAP_se", #UMAP_Combined
  force = TRUE
)
```
```
ArchR logging to : ArchRLogs/ArchR-addTrajectory-662f77d0195e8-Date-2022-12-28_Time-03-52-12.log
If there is an issue, please report to github with logFile!
Error in colMeans(matx) : 'x' must be an array of at least two dimensions
```
[ArchR-addTrajectory-602481b8c7ec6-Date-2022-12-30_Time-03-27-51.log](https://github.com/GreenleafLab/ArchR/files/10323642/ArchR-addTrajectory-602481b8c7ec6-Date-2022-12-30_Time-03-27-51.log)

I don't understand what this error means, can you explain?

**Comment by rcorces** [comment]
Hi @Ping-lin14! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
My initial thought is that whatever values are in the "Sample" column of your `cellColData` do not match to the values supplied in `trajectory` ("0hr", "24hr"). Ive added a check on `dev` to try to explicitly catch this but I'm not so confident that this is the only thing that is going on.

You could check this via
```
groupDF <- getCellColData(ArchRProj = ArchRProj, select = groupBy)
groupDF <- groupDF[groupDF[,1] %in% trajectory,,drop=FALSE]
sum(unique(groupDF[,1]) %in% trajectory)

x <- 1
groupsx <- rownames(groupDF)[groupDF[,1]==trajectory[x]]
length(groupsx)

x <- 2
groupsx <- rownames(groupDF)[groupDF[,1]==trajectory[x]]
length(groupsx)
```

**Comment by Ping-lin14** [comment]
I think it's not caused by `cellColData` mismatch.

```
> groupDF <- getCellColData(ArchRProj = projCD8, select = "Sample")
> groupDF <- groupDF[groupDF[,1] %in% trajectory,,drop=FALSE]
> sum(unique(groupDF[,1]) %in% trajectory)
[1] 2
> x <- 1
> groupsx <- rownames(groupDF)[groupDF[,1]==trajectory[x]]
> length(groupsx)
[1] 6594
> x <- 2
> groupsx <- rownames(groupDF)[groupDF[,1]==trajectory[x]]
> length(groupsx)
[1] 7665

> projCD8

           ___      .______        ______  __    __  .______      
          /   \     |   _  \      /      ||  |  |  | |   _  \     
         /  ^  \    |  |_)  |    |  ,----'|  |__|  | |  |_)  |    
        /  /_\  \   |      /     |  |     |   __   | |      /     
       /  _____  \  |  |\  \\___ |  `----.|  |  |  | |  |\  \\___.
      /__/     \__\ | _| `._____| \______||__|  |__| | _| `._____|
    
class: ArchRProject 
outputDirectory: /disk3/multiome/ASGCP_analysis/CART/ArchRSubset 
samples(2): 24hr 0hr
sampleColData names(1): ArrowFiles
cellColData names(28): Sample TSSEnrichment ... FRIP CarTU
numberOfCells(1): 14259
medianTSS(1): 16.926
medianFrags(1): 12826
```

**Comment by rcorces** [comment]
Sorry. I figured out the problem - it is a difference between `DataFrame()` and `data.frame()`. I've corrected the example in #455 to reflect this. The custom embedding should be a `data.frame` object, not a `DataFrame`. If you remake your custom embedding as a data.frame and re-add it to your project, this should work as expected.

Closing but feel free to comment again below if this doesnt fix your problem.

**Comment by Ping-lin14** [comment]
Hi @rcorces 

Embedding the `data.frame` object into my project still doesn't fix the error. However the error message changed to `Error in colMeans(matx) : 'x' must be numeric`.

[ArchR-addTrajectory-11d43e9de646-Date-2023-01-02_Time-07-23-42.log](https://github.com/GreenleafLab/ArchR/files/10331555/ArchR-addTrajectory-11d43e9de646-Date-2023-01-02_Time-07-23-42.log)

**Comment by rcorces** [comment]
I am nearly certain that the `data.frame` solution is correct. Perhaps you need to ensure that the values in the data.frame that you are adding as an embedding are of class numeric, for example using `as.numeric()`
