### ISSUE TITLE
Combining/merging multiple ArchRProjects

### ISSUE THREAD

**Issue by rojinsafavi** [GreenleafLab/ArchR#179]
I was wondering if there could be a way to combine multiple ArchRProjects? The main reason that I need such functionality is that I need to batch correct 5 pairs of fragments (independently with LSI or harmony) and then merge the results

Thanks!

**Comment by jgranja24** [comment]
There is no current way to do this type of analysis. I'd recommend analyzing them all and if you notice strong batch effect to run Harmony to reduce these biases. Hope that helps.

Best

Jeff

**Comment by rojinsafavi** [comment]
@jgranja24 Thanks for your advice. 

We have 2 batches, and in each batch contains 5 regions(5 different parts of the tissue that was sequenced. Therefore it makes more sense to batch correct each pair and not all of them together. 

To make it clear, 

batch 1    batch2
region1    region1
region2   region2  
region3   region3
region4   region4
region5   region5

What I need to do is batch correcting each pair independently, and then combine everything. This has been tried with Signac, and it gave a good result.

Would it be possible to do the batch correction on each pair independently and merging the result? I was thinking of something as follow:

```

1. create separate arrow files for each pair(5 total)
2.  ILS + harmony on each pair independently
3. create an arrow file containing all 10 fragments (combined_fragment)
4. combining ILS reduced dim  to the combined_fragment arrow object

```

**Comment by rojinsafavi** [comment]
Do you think this might be a feature that could be implemented in the near future?
I really like ArchR since it basically has all one needs for ATACseq analysis. It would be great if a feature like this could be implemented into ArchR :-)

**Comment by jgranja24** [comment]
I guess im a bit confused. Do your results look that batch confounded? Harmony has options for multiple confounders. Have you tried Harmony and the results look bad still? Id strongly suggest trying out harmony on all the samples.

It'd be helpful to see how much worse the result is to what you are expecting (in reference to signac). If you could either post the images here or send us an email at archr.devs@gmail.com to keep it more confidential. We'd be happy to implement what you are asking but need more information.

**Comment by rojinsafavi** [comment]
@jgranja24 Sure, I'll try to send you the results.
Meanwhile, you mentioned confounders. I looked at addHarmoney options, are you referring to groupby?

**Comment by jgranja24** [comment]
For now just use groupBy. Id add a column "Batch" to your ArchRProject saying batch1 and batch2 and then use `groupBy = "Batch"` for Harmony.

**Comment by jgranja24** [comment]
Any updates on this?

**Comment by Liang-BGI** [comment]
@jgranja24 hi, I want to merge ArchRProjects too because I have two techniques data. I need to filter the doublets respectively before I merging the data. Any advice for this？   

Thanks！

**Comment by jgranja24** [comment]
Hi @Liang-BGI,

Just run the data as usual and if you need to use "addHarmony" for batch effect correction.

I am closing this issue if you have more questions feel free to open a new issue!
