### ISSUE TITLE
LogFile error in getGroupBW

### ISSUE THREAD

**Issue by SaskiaFreytag** [GreenleafLab/ArchR#180]
I have been trying the recently added function getGroupBW. Unfortunately, I am getting the following error concerning a logFile. I have also attached the created logFile.
[ArchR-getGroupBW-1a8933a65058-Date-2020-05-28_Time-14-58-50.log](https://github.com/GreenleafLab/ArchR/files/4693885/ArchR-getGroupBW-1a8933a65058-Date-2020-05-28_Time-14-58-50.log)

Any help would be super appreciated. Thank you!

```
ArchR logging to : ArchRLogs/ArchR-getGroupBW-1a8933a65058-Date-2020-05-28_Time-14-58-50.log
If there is an issue, please report to github with logFile!
2020-05-28 14:59:20 : Astro_RL1784 (1 of 77) : Creating BigWig for Group, 0.489 mins elapsed.
Error in .logDiffTime(sprintf("%s (%s of %s) : Creating BigWig for Group",  :
  object 'logFile' not found
```

**Comment by jgranja24** [comment]
Thanks for the info i fixed this in the dev branch.

Best

Jeff

**Comment by rcorces** [comment]
Closing.
