### ISSUE TITLE
CRsparse_rowSums" not resolved from current namespace (Matrix)

### ISSUE THREAD

**Issue by dongdongdamowang** [GreenleafLab/ArchR#1804]
hi guys, I met some problems.
> projHeme5 <- addCoAccessibility(
+   ArchRProj = projHeme5,
+   reducedDims = "IterativeLSI"
+ )
ArchR logging to : ArchRLogs/ArchR-addCoAccessibility-36bc51e7bdfa4-Date-2023-01-10_Time-07-36-20.log
If there is an issue, please report to github with logFile!
2023-01-10 07:36:20 : Computing KNN, 0.002 mins elapsed.
2023-01-10 07:36:21 : Identifying Non-Overlapping KNN pairs, 0.02 mins elapsed.
2023-01-10 07:36:23 : Identified 500 Groupings!, 0.051 mins elapsed.
2023-01-10 07:36:27 : Computing Co-Accessibility chr1 (1 of 20), 0.119 mins elapsed.
Error in .Call("CRsparse_rowSums", x, na.rm, FALSE, sparseResult) : 
  "CRsparse_rowSums" not resolved from current namespace (Matrix)

I do not how to due it .  Could U give some advice ?  Best wishes!

**Comment by rcorces** [comment]
Hi @dongdongdamowang! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by dongdongdamowang** [comment]
[ArchR-addCoAccessibility-3d14e55a893408-Date-2022-12-30_Time-22-31-16.log](https://github.com/GreenleafLab/ArchR/files/10377750/ArchR-addCoAccessibility-3d14e55a893408-Date-2022-12-30_Time-22-31-16.log)
This is my log file

**Comment by rcorces** [comment]
This sounds like an environment issue. Try restarting your R session.
You can also try running `Matrix:::CRsparse_rowSums` and seeing what happens. should look like this:
```
> Matrix:::CRsparse_rowSums
$name
[1] "CRsparse_rowSums"

$address
<pointer: 0x55d0dd11a400>
attr(,"class")
[1] "RegisteredNativeSymbol"

$dll
DLL name: Matrix
Filename:
            /corces/home/rcorces/.cache/R/renv/cache/v5/R-4.2/x86_64-pc-linux-gnu/Matrix/1.5-3/4006dffe49958d2dd591c17e61e60591/Matrix/libs/Matrix.so
Dynamic lookup: FALSE

$numParameters
[1] 4

attr(,"class")
[1] "CallRoutine"      "NativeSymbolInfo"
> packageVersion("Matrix")
[1] ‘1.5.3’
```

**Comment by dongdongdamowang** [comment]
> 
Thanks^ ^
