### ISSUE TITLE
Hi,guys! I find a new problem!

### ISSUE THREAD

**Issue by dongdongdamowang** [GreenleafLab/ArchR#1811]
[ArchR-plotFootprints-3a81b7288da9fb-Date-2023-01-18_Time-09-37-39.log](https://github.com/GreenleafLab/ArchR/files/10441131/ArchR-plotFootprints-3a81b7288da9fb-Date-2023-01-18_Time-09-37-39.log)
This is my log file.
plotFootprints(
+   seFoot = seFoot,
+   ArchRProj = projHeme6, 
+   normMethod = "Subtract",
+   plotName = "Footprints-Subtract-Bias",
+   addDOC = FALSE,
+   smoothWindow = 5
+ )
ArchR logging to : ArchRLogs/ArchR-plotFootprints-3a81b72f966b0c-Date-2023-01-18_Time-09-54-12.log
If there is an issue, please report to github with logFile!
2023-01-18 09:54:12 : Plotting Footprint : Olig2_72 (1 of 3), 0.002 mins elapsed.
2023-01-18 09:54:13 : Plotting Footprint : Olig3_78 (2 of 3), 0.02 mins elapsed.
2023-01-18 09:54:15 : Plotting Footprint : Olig1_81 (3 of 3), 0.046 mins elapsed.
ArchR logging successful to : ArchRLogs/ArchR-plotFootprints-3a81b72f966b0c-Date-2023-01-18_Time-09-54-12.log
Warning messages:
1: `guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead. 
2: `guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead. 
3: `guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead. 
4: `guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead. 
5: `guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead. 
6: `guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead. 

It is my issue. It seems that it is ggplot2 is upgraded. What could I do ? Could U upgrade source code?

**Comment by rcorces** [comment]
Hi @dongdongdamowang! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
You are using an outdated version of ArchR (`v1.0.1`) This has been fixed already.
https://github.com/GreenleafLab/ArchR/commit/8345fc6a01995ded5debe09c9b6aef00a8db0345

**Comment by dongdongdamowang** [comment]
Thanks!
