### ISSUE TITLE
Custom Enrichment

### ISSUE THREAD

**Issue by ozturan** [GreenleafLab/ArchR#182]
Hi,

I have two different samples (treated/untreated). When I create an ArchRProject with both files at the same time, and try to calculate the enrichment scores (custom annotation) with my own .bed files, I am getting **a** heatmap. Is this heatmap a combination of both samples? How can I subset total ArchRProject by the sample? I tried to use (from the manual):

`idxSample <- BiocGenerics::which(projHeme1$Sample %in% "scATAC_BMMC_R1")`
`cellsSample <- projHeme1$cellNames[idxSample]`
`projHeme1[cellsSample, ]`

and then I calculated the enrichments. However I am getting the same heatmap for both of my samples. Should I create separate ArchRProjects for each sample? I also wanted to get a heatmap (treated vs. untreated) with my own annotations. Is that possible?

Thank you.

**Comment by rcorces** [comment]
I'm not sure if I understand your question correctly but I believe this is covered in the manual. I've edited your question to use "ArchRProject" (not ArrowProject) to avoid confusion.

The relevant section of the manual is here - https://www.archrproject.com/bookdown/archr-enrichment.html

This utilizes a `SummarizedExperiment` object called `markersPeaks` which was created in a previous Chapter here - https://www.archrproject.com/bookdown/identifying-marker-peaks-with-archr-1.html. the `getMarkerFeatures()` function uses the `groupBy` parameter which defines the groups for which marker features should be created. These groups will appear as rows in your heatmap. If you wanted to determine the enrichment of peaks in your different samples, you would provide the column in `cellColData` that distinguishes your treated vs untreated samples (presumably "Sample").

**Comment by ozturan** [comment]
Thanks for the answer. What if I wanted to get two heatmaps (for two samples) and in each heatmap, clusters calculated with Seurat?

**Comment by rcorces** [comment]
The answer to your question is indirectly contained in my previous answer. You get one heatmap per marker peak summarized experiment. If you want two heatmaps, you make two different summarized experiments using `getMarkerFeatures()`. You define what is presented in those heatmaps by changing what goes into the summarized experiment using `groupBy` in `getMarkerFeatures()`.

**Comment by ozturan** [comment]
I'm not sure. Of course, I can use two different summarized experiments. For the comparison purposes though, it doesn't make sense. I can't simply compare the two (different # of cells, sequencing depth). Is there any way for me two get two comparable heatmaps? 

Thank you.

**Comment by jgranja24** [comment]
Honestly for your analysis, I would create a Deviations Matrix `addDeviationsMatrix` and then compare the deviation score values across the clusters for both treatment. This is directly comparable while comparing enrichments will never be truly comparable.
