### ISSUE TITLE
<simpleError in validObject(r): invalid class “dgTMatrix” object: 'i' and 'j' slots do not have equal length>

### ISSUE THREAD

**Issue by yangqianq** [GreenleafLab/ArchR#1825]
Hi, 
    I have used the latest 1.0.2 version of Ar'ch'R, and the input file is fragment.gz. There is an error when creating Arrow file in some files.
   The data reported wrong is due to the fragment length exceeding the chromosome position, but I found that in the latest ArchR version, this fragment was judged and ignored. I don't know why this error is caused
**Describe the bug**
<simpleError in validObject(r): invalid class “dgTMatrix” object: 'i' and 'j' slots do not have equal length>

I think the error may be because the fragment length exceeds the length of the chromosome, because I verified that chr 12 is 124486764 in length,but the end position in the error message is 124486768. And I saw that the latest version of ArchR judged and ignored this  [[[[  which  is  warning("Skipping over fragments not within chromosome range on Chr:", chr) ]]]], so I don't understand the cause of this error. In addition, some of the data I use can successfully create Arrow files.
**To Reproduce**
This error does not appear in the tutorial data used.

**Expected behavior**
How do I modify and create the Arrow file

**Screenshots**
![c4386e51ee4b9222593956a4ab2aeb7](https://user-images.githubusercontent.com/81630311/215730711-b673fae9-7581-4957-a25c-c5d6f4f8d9d8.png)

**Comment by rcorces** [comment]
Hi @yangqianq! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
I'm not sure I understand your post. This bug was addressed previously in https://github.com/GreenleafLab/ArchR/issues/1527

This bug has been fixed on the current `dev` branch.
