### ISSUE TITLE
How to subset subtypes?

### ISSUE THREAD

**Issue by dongdongdamowang** [GreenleafLab/ArchR#1833]
Hi,guys!
I used archR but I do not   how to choose the one celltype to analysis more. Could U tell me how can I subset the subtype which I want in archR?

Thanks!

**Comment by rcorces** [comment]
Hi @dongdongdamowang! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
Not an issue. Usage questions should be posted to discussions.

You're looking for this
https://www.archrproject.com/reference/subsetArchRProject.html

**Comment by dongdongdamowang** [comment]
> Not an issue. Usage questions should be posted to discussions.
> 
> You're looking for this https://www.archrproject.com/reference/subsetArchRProject.html

Yes. I am sorry about that I did not find this step in Full Manual. Thanks!
