### ISSUE TITLE
Cannot install ArchR

### ISSUE THREAD

**Issue by jeromejh** [GreenleafLab/ArchR#1837]
I've been trying to install ArchR on my MacBook Pro (Ventura 13.2) but it doesn't work. My current R version is 4.2.2.

devtools::install_github("GreenleafLab/ArchR",ref="master",repos=BiocManager::repositories())
Downloading GitHub repo GreenleafLab/ArchR@master
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/GreenleafLab/ArchR/tarball/master' failed

Could anyone help me with this?

**Comment by rcorces** [comment]
Hi @jeromejh! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
One other user encountered this but did not post a solution. I imagine it is something with your R setup. I would first try the classic terminate R and restart. If that doesnt work then maybe try a clean install of R.

**Comment by rcorces** [comment]
Here is one possible solution
https://github.com/GreenleafLab/ArchR/discussions/895

**Comment by jeromejh** [comment]
Thank you so much. I was able to install the package.
