### ISSUE TITLE
The `size` parameter in  `plotEmbedding()`  cannot work.

### ISSUE THREAD

**Issue by jiangpuxuan** [GreenleafLab/ArchR#1841]
I run  `plotEmbedding()` to get the score of a gene in my dataset
Here is my code :
```
p1 <- plotEmbedding(
    ArchRProj = proj, 
    colorBy = "GeneScoreMatrix", 
    name = "mygene", 
    continuousSet = "horizonExtra",
    embedding = "Harmony_ATAC",
    imputeWeights = getImputeWeights(proj),
    size=0.4
)
p1
```
<img width="195" alt="1675867645837" src="https://user-images.githubusercontent.com/81287604/217563486-9cebb624-e36d-4424-8e9f-fbc6b43ffaa3.png">

I changed `size` but nothing happened. 

BTW, when I run the code below to display the `harmony` clustering, the `size` parameter worked:
```
plotEmbedding(
proj, 
colorBy = "cellColData", 
name = "ClustersHarmonyATAC.0.4", 
embedding = "Harmony_ATAC",  
size = 0.25)
```

**Comment by rcorces** [comment]
Please do not double post. I will respond in your Discussion post https://github.com/GreenleafLab/ArchR/discussions/1839
