### ISSUE TITLE
plotFootprints 

### ISSUE THREAD

**Issue by huangmiao1996** [GreenleafLab/ArchR#1850]
The full manual of ArchR 14.2 said "By default, these plots will be saved in the outputDirectory of the ArchRProject. If you requested to plot all motifs and returned this as a ggplot object, this ggplot object would be extremely large. An example of motif footprints from bias-subtracted analyses are shown below". However, I could not find the pictures or the outputDirectory. My ArchR version is 1.0.1. I hope that the developer could hepp me solve the question. Thank you!
<img width="793" alt="截屏2023-02-20 下午4 26 35" src="https://user-images.githubusercontent.com/110522446/220082764-f4887029-8d28-46e9-a89a-2ec9ea37cbb2.png">

**Comment by rcorces** [comment]
Hi @huangmiao1996! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by huangmiao1996** [comment]
Thank you! This question should be posted in the Discussion part.

**Comment by ZayaAyush** [comment]
I met the same issue! I looked all the discussion parts and can't find the solution. Could you help me to resolve this issue and give the detailed information?
I can not open the pdf file. 
[ArchR-plotFootprints-b9946b226912-Date-2023-09-02_Time-14-10-32.461337.log](https://github.com/GreenleafLab/ArchR/files/12504587/ArchR-plotFootprints-b9946b226912-Date-2023-09-02_Time-14-10-32.461337.log)

Thank you!

**Comment by rcorces** [comment]
https://github.com/GreenleafLab/ArchR/discussions/1851

**Comment by rcorces** [comment]
@ZayaAyush https://github.com/GreenleafLab/ArchR/discussions/1851
