### ISSUE TITLE
create Arrow Files Waiting Time Too long  

### ISSUE THREAD

**Issue by WangHaoPlan** [GreenleafLab/ArchR#1856]
hello Let me talk about my problem：
[ArchR-createArrows-387cd4858b7-Date-2023-02-24_Time-11-42-21.log](https://github.com/GreenleafLab/ArchR/files/10830179/ArchR-createArrows-387cd4858b7-Date-2023-02-24_Time-11-42-21.log)
I created myself geneAnnotation and genomeAnnotation for Non-model species ，when I create arrowsfile ,it let me waiting a long time,  But it's still not finished，tmp file also no renovate.
Can I use any method to build arrow files？I think Archr is a very good software !
thank you for answer my question.

**Comment by rcorces** [comment]
Hi @WangHaoPlan! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by WangHaoPlan** [comment]
Yes, I am so sorry to put it in this session. But thank you so much for your reply to my post.

**Comment by rcorces** [comment]
Apologies for not replying sooner. We do not have much experience with non-model organisms. Your log file does not indicate any error so I dont have any way of helping. My assumption is that you are encountering issues because your genome has >10,000 chromosomes. I could envision that this would cause issues with ArchR that havent been observed in more standard genomes. If you find a solution, please post it here.
