### ISSUE TITLE
Error in .getCoverageMetadata(ArchRProj = ArchRProj, groupBy = groupBy, : No Coverage Metadata found for : Leiden_Clusters. Please run addGroupCoverages! Traceback:

### ISSUE THREAD

**Issue by shaistamadad** [GreenleafLab/ArchR#1859]
Hi, 

Thanks very much for this great tool. I have been experiencing some issues with the peak calling step in ArchR. 
 I have run the addGroupCoverages step and I am able to see the the insertion coverage h5 files in the  GroupCoverages sub folder of my ArchR project. 

```
addGroupCoverages(
  ArchRProj = proj,
  groupBy = "Leiden_Clusters",
  useLabels = TRUE,
  minCells = 40,
  maxCells = 500,
  maxFragments = 25 * 10^6,
  minReplicates = 2,
  maxReplicates = 5,
  sampleRatio = 0.8,
  kmerLength = 6,
  threads = getArchRThreads(),
  returnGroups = FALSE,
  parallelParam = NULL,
  force = FALSE,
  verbose = TRUE,
  logFile = createLogFile("addGroupCoverages")
)
```
When I run the peak calling step 

```
proj <- addReproduciblePeakSet(
    ArchRProj = proj, 
    groupBy = "Leiden_Clusters", 
    peakMethod = "Macs2",
    pathToMacs2 = pathToMacs2
)

```

I get the following error:

```
Calling Peaks with Macs2

Error in .getCoverageMetadata(ArchRProj = ArchRProj, groupBy = groupBy, : No Coverage Metadata found for : Leiden_Clusters. Please run addGroupCoverages!
Traceback:

1. addReproduciblePeakSet(ArchRProj = proj, groupBy = "Leiden_Clusters", 
 .     peakMethod = "Macs2", pathToMacs2 = pathToMacs2)
2. .getCoverageMetadata(ArchRProj = ArchRProj, groupBy = groupBy, 
 .     minCells = minCells)
3. stop("No Coverage Metadata found for : ", groupBy, ". Please run addGroupCoverages!")
```

Since the coverage insertion h5 files exist, I don't understand why they are not getting recognised. I wonder  whether the group coverage file generation step does not generate coverage files for all my samples ( I have 57 samples in total and 360000 cells). Would the peak calling step not start at all if that's the case? 

[ArchR-addGroupCoverages-22bda61d31eb9-Date-2023-02-27_Time-18-31-02.log](https://github.com/GreenleafLab/ArchR/files/10851863/ArchR-addGroupCoverages-22bda61d31eb9-Date-2023-02-27_Time-18-31-02.log)

thanks so much for your help!

**Comment by rcorces** [comment]
Hi @shaistamadad! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
as shown in the manual, the output of `addGroupCoverages()` is meant to be stored back into your `ArchRProj` variable.

https://www.archrproject.com/bookdown/making-pseudo-bulk-replicates.html

```R
projHeme4 <- addGroupCoverages(ArchRProj = projHeme3, groupBy = "Clusters2")
```

Without this, your project doesnt know that `addGroupCoverages()` has been run.
