### ISSUE TITLE
How to subset peak matrix?

### ISSUE THREAD

**Issue by CSBioAzim** [GreenleafLab/ArchR#186]
I want to only do the statistical analysis to an only a specific set of peaks, for example, peaks that are only at enhancer or intronic regions. I was wondering is it possible to filter out the peak matrix and do the downstream analysis (differential peaks, etc) on filtered peak matrix?
Also, I think this would be a good feature to peak2gene heatmap as well. For example, I want only to plot the peak2gene heatmap for DEG and DE peaks.

**Comment by jgranja24** [comment]
My recommendation is to filter out the peaks you dont want to consider and then re-adjust the p-values. This would be a bit more challenging for peak2gene heatmap and I will consider it down the line. Closing this issue feel free to further re-open or add comments.

**Comment by CSBioAzim** [comment]
@jgranja24 Thanks for the feedbacks. This is what actually I'm asking. How can I modify the "PeakMatrix" matrix and overwrite it on ArchR object?

**Comment by jgranja24** [comment]
If you want to truly overwrite it - For example

```
proj@peakSet <- proj@peakSet[1:100]
proj <- addPeakMatrix(proj)
```

**Comment by CSBioAzim** [comment]
Yes, I also need to recompute the FDR as well!

**Comment by CSBioAzim** [comment]
@jgranja24 @rcorces I'm bit confused. Does peak2geneLink only plot cell type specific peak to gene links? is there any hack to filter out this for specific cell genes and peaks? I DE peaks and DEGs. Also lableing some of the marker genes and peaks in the heatmap would be very useful!
Thanks,
