### ISSUE TITLE
 ERROR Found in .addGeneScoreMat for (bladder : 1 of 1) 

### ISSUE THREAD

**Issue by houruiyan** [GreenleafLab/ArchR#1862]
[ArchR-createArrows-4a21a718c956-Date-2023-03-02_Time-20-59-19.log](https://github.com/GreenleafLab/ArchR/files/10872161/ArchR-createArrows-4a21a718c956-Date-2023-03-02_Time-20-59-19.log)

When I use `inputFiles='/storage/yhhuang/users/ruiyan/
(https://github.com/GreenleafLab/ArchR/files/10872143/ArchR-createArrows-4a21a718c956-Date-2023-03-02_Time-20-59-19.log)
15organ/SRR18_ATAC/fragments.sorted.tsv.gz'
ArrowFiles <- createArrowFiles(
  inputFiles = inputFiles,
  sampleNames = 'bladder',
  filterTSS = 4, #Dont set this too high because you can always increase later
  filterFrags = 1000, 
  addTileMat = TRUE,
  addGeneScoreMat = TRUE
)`
I cannot create a ArrowFiles. Even the demo data provided by you. It also produce this question. 
ERROR Found in .addGeneScoreMat for  

This bug is the same with https://github.com/GreenleafLab/ArchR/issues/317, but I cannot use its methods to solve it. I reinstall GenomicRanges package v1.42.0. It still cannot work.

 Could you help me, thank you!

**Comment by rcorces** [comment]
Hi @houruiyan! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
I do not have an intuition for why you would get this error.
As you mention you are getting this error on the tutorial dataset, this indicates that there is a problem with something on your end as the tutorial data and code have been run by hundreds of people successfully.

I would try:
1. Terminating your R session and starting from a completely fresh R session.
2. Installing the `dev` branch:

```R
devtools::install_github("GreenleafLab/ArchR", ref="dev", repos = BiocManager::repositories(), upgrade = "never")
#to unload a package and reload
detach("package:ArchR", unload=TRUE)
library(ArchR)
```

**Comment by houruiyan** [comment]
Thank you for your reply.
I try according to your guidence. But it still cannot work. Hope you can help me. Thank you very much!

[ArchR-createArrows-24fe255d4547b-Date-2023-03-03_Time-03-38-02.log](https://github.com/GreenleafLab/ArchR/files/10875271/ArchR-createArrows-24fe255d4547b-Date-2023-03-03_Time-03-38-02.log)

**Comment by rcorces** [comment]
Please send the log file from the tutorial data

**Comment by houruiyan** [comment]
Yes, the log file indeed is the tutorial data.
<img width="829" alt="image" src="https://user-images.githubusercontent.com/56068158/222540321-482bfcae-4a01-4b79-b829-c40f12e095f6.png">

**Comment by houruiyan** [comment]
sorry. I do not know the reason. Here is the latest log from tutorial data.
[ArchR-createArrows-260cd27aa63b1-Date-2023-03-03_Time-04-03-46.log](https://github.com/GreenleafLab/ArchR/files/10875429/ArchR-createArrows-260cd27aa63b1-Date-2023-03-03_Time-04-03-46.log)

**Comment by rcorces** [comment]
well, first things first, the tutorial data is in hg19. Please re-upload the log file after making that change.

**Comment by houruiyan** [comment]
Hi, thank you very much for your quick reply! ! 

Indeed, for the tutorial data, I used a wrong reference genome. When I use hg19. It works smoothly, which suggests that there is not the problem of package install. My fragement file may be have some problem. But I still do not know the root of question.

The fragment was built by my self. I use software to get the peak of TSS and I change it to the fragments file. 

The file located here. 
https://connecthkuhk-my.sharepoint.com/:u:/g/personal/ruiyan_connect_hku_hk/ETYgCWb_gU9CkkjxAwmHwucBPJj5wy03TDakJ5Oi7pmZwg?e=NeipnQ

The log file is that I send before. Could you help me to check it? Thank you very much!

**Comment by rcorces** [comment]
As this is not a problem with ArchR, I cannot offer additional support. We do not provide support for user-specific analyses. You'll have to figure out the issue with your data on your own.

**Comment by houruiyan** [comment]
Could you help me? Please,! I spent too much time on it and it still did not have any progress.

**Comment by rcorces** [comment]
I'm sorry if this is perceived as being rude but there is so much wrong with what is going on here and it is very frustrating as an open source software developer to deal with posts like this.

1. Please do not repeatedly post about the same thing across multiple issues asking for help. I very clearly stated that we do not have bandwidth to help users with their specific analyses.
2. As a perfect example of why point number 1 applies, you have asked for help with a file that is __very clearly__ not single-cell ATAC-seq data. You must be using ArchR for something other than its intended purpose but you did not mention this in your original posting and instead assumed that the issue was with the software. I do not know what your analytical goals are but the fragment file that you have manually created is clearly not correct and this is because you are trying to use the software in a way that it is not meant to be used.
