### ISSUE TITLE
Get strange results in GeneScore visualization

### ISSUE THREAD

**Issue by YangJAT** [GreenleafLab/ArchR#1868]
Hi @rcorces

I just follow your toturial to analyse the example data. I used the same code as you provided, and also did not change any parameters. However, after I run the codes in "7.5 Marker Genes Imputation with MAGIC", I get some very strange results, shown in the figure below. 

![图片](https://user-images.githubusercontent.com/70686083/223650255-254cbb60-7266-48cb-a189-54521adb8888.png)
This is my result

![图片](https://user-images.githubusercontent.com/70686083/223650418-2293f47a-4588-40da-801f-80d0fbacb819.png)
This is the right result from the tutorial

My result seems like to be affected by some nosiy. Could you give me some advice to solve this issue?

**Comment by rcorces** [comment]
Hi @YangJAT! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
Solved previously https://github.com/GreenleafLab/ArchR/issues/1731

This is a bug in `ggplot2_3.4.0`. `ggplot2_3.4.1` is now available so you should either upgrade or downgrade your `ggplot2` package.
