### ISSUE TITLE
chromVAR Deviation Score

### ISSUE THREAD

**Issue by ozturan** [GreenleafLab/ArchR#187]
Hi, 

I calculated a DeviationMatrix with my custom regions. Is there any way (any flag) to get the Z-scores between some range (0 and 1 e.g.) for all my custom regions since they obviously in different range? 

Thank you very much.

**Comment by rcorces** [comment]
I'm not sure this is the answer you are looking for but you can extract any matrix from the project using `getMatrixFromProject()` and then perform standard subset and manipulation actions on that matrix. Note that the `useSeqnames` parameter for a deviation matrix is expecting you to ask for the z-scores or deviations (not a chromosome). 

https://www.archrproject.com/reference/getMatrixFromProject.html

**Comment by ozturan** [comment]
Got it. Thank you.

**Comment by Yijia-Jiang** [comment]
Hi, useseqnames function seems no longer working in the latest version of archr. Can you tell us another to indicate z-scores or deviations?
