### ISSUE TITLE
IterativeLSI with large sample size 

### ISSUE THREAD

**Issue by Pengfei-Dong** [GreenleafLab/ArchR#1871]
Hi, 
I have encountered an error with IterativeLSI. 
"2023-03-09 19:04:36 : ERROR Found in .LSIPartialMatrix for  
LogFile = ArchRLogs/ArchR-addIterativeLSI-f7043b715d39-Date-2023-03-09_Time-17-26-43.log

<simpleError in .cbind2Csp(x, y): Cholmod error 'problem too large' at file ../Core/cholmod_sparse.c, line 89>

2023-03-09 19:04:36 : errorList, Class = list

errorList$: length = 1
                       
1 function (name)      
2 .Internal(args(name))"

The code I used 
"
myproj<- addIterativeLSI(
  ArchRProj =myproj
  useMatrix = "TileMatrix", 
  name = "IterativeLSI", 
  iterations = 2, 
  clusterParams = list( #See Seurat::FindClusters
    resolution = 0.1, 
    sampleCells = 10000, 
    n.start = 10
  ), 
  varFeatures = 25000, 
  dimsToUse = 1:30
)"
ArchR v1.0.2 R v4.0.2

I think it could be potentially due to the large cell amount of input . Please find the attached log file for more details. 

 
[ArchR-addIterativeLSI-f7043b715d39-Date-2023-03-09_Time-17-26-43.log](https://github.com/GreenleafLab/ArchR/files/10937592/ArchR-addIterativeLSI-f7043b715d39-Date-2023-03-09_Time-17-26-43.log)

**Comment by rcorces** [comment]
Hi @Pengfei-Dong! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
I've never seen this on `addIterativeLSI()` but yes it typically means there is a memory issue.
How many cells are in your dataset?

**Comment by Pengfei-Dong** [comment]
Thanks for your quick response, Ryan.
It's ~2.5 million cells. I requested 400GB of memory, and it only used 200 GB.
Best,
Pengfei
________________________________

**Comment by rcorces** [comment]
You could try using the `sampleCellsFinal` param. I would imagine that will take care of your problem
<html>
<body>


sampleCellsFinal | An integer specifying the number of cells to sample in order to perform a sub-sampled LSI in final iteration.
-- | --



</body>
</html>

**Comment by Pengfei-Dong** [comment]
Thanks a lot.
I have added parameters   projectCellsPre=TRUE,  sampleCellsFinal=5e5L.
However, I got a new error message
"Error in .logError(e, fn = ".LSIPartialMatrix", info = "", errorList = errorList,  :
  Exiting See Error Above
Calls: addIterativeLSI ... tryCatchList -> tryCatchOne -> <Anonymous> -> .logError
In addition: Warning message:
In sampleCells * table(sampleNames) : NAs produced by integer overflow
Execution halted"

The log file exceeded the size limit, so I trimmed the top 100335 lines and attached it here.
Best,
Pengfei
________________________________

**Comment by rcorces** [comment]
I'm not sure. The log file didnt come through so I cant assess.

**Comment by Pengfei-Dong** [comment]
I have attached a gzed log file here.
Best,
Pengfei
________________________________

**Comment by rcorces** [comment]
Hi @Pengfei-Dong - unfortunately, the log file isnt coming through. Perhaps you can email it to me at archr.devs@gmail.com or post a link (dropbox etc) here?

**Comment by Pengfei-Dong** [comment]
I'm sorry I forgot to mention that the arrow files were generated by ArchR V 1.0.1, it has a different error, so I switched to the new version, and meet this new error.

**Comment by Pengfei-Dong** [comment]
I have also tried to subset samples to test the pipeline with ArchR v1.0.2. Although without any error, the doubletscore step is taking forever and stopped at the first sample. The last line of the log file is 
" Simulating and Projecting Doublets, 2.876 mins elapsed."
I found when I used ArchR v1.0.1, this step runs successfully. 
I have tried multiple R versions, but all have the same problem. 
The code I used for doublet score. 
doubScores <- addDoubletScores(
  input = ArrowFiles,
  k = 10, #Refers to how many cells near a "pseudo-doublet" to count.
  knnMethod = "UMAP", #Refers to the embedding to use for nearest neighbor search with doublet projection.
  LSIMethod = 1
)

[ArchR-addDoubletScores-4829725f735fa-Date-2023-03-14_Time-17-18-15.log](https://github.com/GreenleafLab/ArchR/files/10973862/ArchR-addDoubletScores-4829725f735fa-Date-2023-03-14_Time-17-18-15.log)

**Comment by Pengfei-Dong** [comment]
> I have also tried to subset samples to test the pipeline with ArchR v1.0.2. Although without any error, the doubletscore step is taking forever and stopped at the first sample. The last line of the log file is " Simulating and Projecting Doublets, 2.876 mins elapsed." I found when I used ArchR v1.0.1, this step runs successfully. I have tried multiple R versions, but all have the same problem. The code I used for doublet score. doubScores <- addDoubletScores( input = ArrowFiles, k = 10, #Refers to how many cells near a "pseudo-doublet" to count. knnMethod = "UMAP", #Refers to the embedding to use for nearest neighbor search with doublet projection. LSIMethod = 1 )
> 
> [ArchR-addDoubletScores-4829725f735fa-Date-2023-03-14_Time-17-18-15.log](https://github.com/GreenleafLab/ArchR/files/10973862/ArchR-addDoubletScores-4829725f735fa-Date-2023-03-14_Time-17-18-15.log)

The problem was found with R/4.2.0 and 4.2.2. and it was solved when switching to R 4.1.0 with ArchR 1.0.2. 
However, the previous error (LSI) still not solved.

**Comment by rcorces** [comment]
There is a lot going on in your posts. There should not be any need to switch back and forth between ArchR versions or versions of R. It is however possible that your different versions of R have different versions of dependency packages which might cause different behavior.
Without a reproducible example, which is challenging in this case, I have only minimal ability to help. From the error in your Iterative LSI log file, its clear that there is an issue with subsampling cells during the final LSI iteration. But I cant tell why that might happen.

**Comment by Pengfei-Dong** [comment]
Thanks again for all your support. I really appreciate your help. 
 
I have gone through the code and found the problem is due to R integer limit. 
Basically, I used 2e5L for parameter sampleCellsFinal, and 5e5L*5000L will exceed the integer limit. 

https://github.com/GreenleafLab/ArchR/blob/master/R/IterativeLSI.R
line 736
sampleN <- ceiling(sampleCells * table(sampleNames) / length(sampleNames))
This problem could be easily solved by changing 5e5L to 5e5
or change the line to
sampleN <- ceiling(sampleCells/ length(sampleNames) * table(sampleNames) )

**Comment by Pengfei-Dong** [comment]
Exactly. Thanks!

**Comment by rcorces** [comment]
Fixed on `dev` via c0c28c1
