### ISSUE TITLE
Error in importing multiome data from the ENCODE project

### ISSUE THREAD

**Issue by dagarfield** [GreenleafLab/ArchR#1877]
Hi all,

I'm attempting to build an ArchR multiome representation from some published ENCODE multiome data. The fragment files import just fine, but the ENCODE RNA data does not come in HDF5 format. Rather, it is represented by

* barcodes.tsv.gz
* features.tsv.gz
* matrix.mtx.gz

Turning this into an HDF5 file is not issue, however the results aren't happy accessed by ArchR's native functions

```
Importing Feature Matrix 1 of 1
Error in (function (cl, name, valueClass)  : 
  assignment of an object of class “array” is not valid for @‘x’ in an object of class “dgTMatrix”; is(value, "numeric") is not TRUE
```

Fine, we import the data using DropletUtils::read10xCounts. 

> sce<-read10xCounts(RNA_dirs,sample.names = sampleNames)

But this isn't ideal either (see attached log file too)

```
> proj <- addGeneExpressionMatrix(input = proj, seRNA = sce)
ArchR logging to : ArchRLogs/ArchR-addGeneExpressionMatrix-7f3a5c81802d-Date-2023-03-13_Time-10-58-56.log
If there is an issue, please report to github with logFile!
Error in addGeneExpressionMatrix(input = proj, seRNA = sce) : 
  Detected less than 50% of seqnames for seRNA in chromSizes! Are you sure the seqnames of your seRNA are correct?!
```

Can you say a bit about what the imported SE/SCE should look like? An issue here is that chromosome information is not found in any of the files provided by ENCODE (though it is hg38 gene symbols), so I'm struggling a bit to figure out how to get these things to play along. 

[ArchR-addGeneExpressionMatrix-7f3a5dff406-Date-2023-03-13_Time-11-17-40.log](https://github.com/GreenleafLab/ArchR/files/10960590/ArchR-addGeneExpressionMatrix-7f3a5dff406-Date-2023-03-13_Time-11-17-40.log)

**Comment by rcorces** [comment]
Hi @dagarfield! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by dagarfield** [comment]
OK, made some progress on this by giving our imported SCE some proper rowRanges with horrifying code

```
library(EnsDb.Hsapiens.v86)
features = genes(EnsDb.Hsapiens.v86::EnsDb.Hsapiens.v86)
#take only features we have RNA for
features <- features[is.element(features$symbol,rownames(sce))]
#and then further subset to get only features on chromosomes in the ArchR project
seqlevels(features)<-paste("chr",seqlevels(features),sep="")
features<-features[is.element(as.character(seqnames(features)),seqlevels(getChromSizes(proj)))]
#then subset down the sce to just genes on those chromosomes
sce<-sce[is.element(rownames(sce),features$symbol),]
#and remove the duplicates because ENCODE is stupid and used redundant gene symbols instead of proper IDs
features <- features[!duplicated(features$symbol)]
features<-features[match(rownames(sce), features$symbol)]
##update rowData
df<-data.frame(gene_id = features$gene_id, gene_name = features$gene_name)
rowData(sce)<-DataFrame(data.frame(rowData(sce)) %>% left_join(x = ., y = df, by = c("Symbol" = "gene_name")))
rownames(sce)<-rowData(sce)$gene_id
rowRanges(sce)<-features
```

This is deeply inelegant, but gets us through the first issue...only to discover another

```
> proj <- addGeneExpressionMatrix(input = proj, seRNA = sce)
ArchR logging to : ArchRLogs/ArchR-addGeneExpressionMatrix-7f3a578b0852-Date-2023-03-13_Time-17-52-09.log
If there is an issue, please report to github with logFile!
2023-03-13 17:52:11 : Overlap w/ scATAC = 0.235
2023-03-13 17:52:11 : Warning! Not all cells in input exist in seRNA! This may cause downstream issues with functions that require information from all cells. For example, addIterativeLSI() will not work on this GeneExpressionMatrix! To remove these mis-matched cells, subset your ArchRProject using the subsetArchRProject() function to contain only cells present in seRNA and set 'strictMatch = TRUE'
2023-03-13 17:52:12 : Overlap Per Sample w/ scATAC : ENCSR194KHA=12437,ENCSR352RMS=6312,ENCSR548IRG=15316,ENCSR681OLJ=9725
Error in `assays<-`(`*tmp*`, withDimnames = withDimnames, ..., value = `*vtmp*`) : 
  please use 'assay(x, withDimnames=FALSE)) <- value' or 'assays(x, withDimnames=FALSE)) <- value' when the
  rownames or colnames of the supplied assay(s) are not identical to those of the receiving SingleCellExperiment
  object 'x'
```

Any ideas? Given that the program is identifying overlaps, I'm assuming the column names are not the issue, but possibly there remains some mismatch between the annotations of the ArchR object and our SCE? For example

```
> proj@geneAnnotation$genes
GRanges object with 25017 ranges and 2 metadata columns:
          seqnames            ranges strand |     gene_id       symbol
             <Rle>         <IRanges>  <Rle> | <character>  <character>
      [1]     chr1       69091-70008      + |       79501        OR4F5
      [2]     chr1     139790-140339      - |      729737    LOC729737
      [3]     chr1     585990-629010      - |   101928626 LOC101928626
      [4]     chr1     632325-632413      - |   102465432         <NA>
      [5]     chr1     817371-819837      + |      400728       FAM87B
```

And

```
> rowRanges(sce)
GRanges object with 36179 ranges and 6 metadata columns:
                  seqnames            ranges strand |         gene_id   gene_name           gene_biotype seq_coord_system
                     <Rle>         <IRanges>  <Rle> |     <character> <character>            <character>      <character>
  ENSG00000223972     chr1       11869-14409      + | ENSG00000223972     DDX11L1 transcribed_unproces..       chromosome
  ENSG00000227232     chr1       14404-29570      - | ENSG00000227232      WASH7P unprocessed_pseudogene       chromosome
  ENSG00000278267     chr1       17369-17436      - | ENSG00000278267   MIR6859-1                  miRNA       chromosome
  ENSG00000243485     chr1       29554-31109      + | ENSG00000243485   MIR1302-2                lincRNA       chromosome
  ENSG00000237613     chr1       34554-36081      - | ENSG00000237613     FAM138A                lincRNA       chromosome
```

Sorry to be a bother but, alas, it appears ENCODE is not being so helpful in the format of their released data (possible genotype protection/privacy issues)

[ArchR-addGeneExpressionMatrix-7f3a578b0852-Date-2023-03-13_Time-17-52-09.log](https://github.com/GreenleafLab/ArchR/files/10963156/ArchR-addGeneExpressionMatrix-7f3a578b0852-Date-2023-03-13_Time-17-52-09.log)

**Comment by rcorces** [comment]
Hi @dagarfield - lots of moving parts here. To re-summarize the underlying problem - ArchR basically cannot handle RNA input other than the filtered feature barcorde matrix h5 file. The good news is that we are working on better RNA and multiome support. No timeline, but we know this is a limitation.

I've done something similar to what you are trying to do, but in a very one-off setting. In my case, I wanted to run ambient RNA removal prior to importing into ArchR. To do it, I imported a "dummy" experiment and then used the structure of the imported object as a scaffold for the new data. In my case, that was a bit easier because the dummy experiment was just the pre-corrected data. But I feel like the same concept could apply for you?

```R
#import the RNA feature matrices into a SummarizedExperiment object
dummy_seRNA <- import10xFeatureMatrix(
  input = "/gladstone/corces/lab/users/smenon/PD_WGS/PD_mulitome_pilot/done_counts/PD_16-39_MTG_X002_S04_L007_B2_T1_P001/PD_16-39_MTG_X002_S04_L007_B2_T1_P001/outs/filtered_feature_bc_matrix.h5",
  names = "PD_16-39_MTG_X002_S04_L007_B2_T1_P001",
  strictMatch = TRUE
)

rna <- lapply(rnaFiles, function(x) {
  readRDS(x)
})
for(i in seq_along(rnaFiles)){
  colnames(rna[[i]]) <- paste0(names(rnaFiles)[i],"#",colnames(rna[[i]]))
}
rna <- cbind(rna[[1]],rna[[2]],rna[[3]])
rna <- rna[rownames(dummy_seRNA),]
seRNA <- SummarizedExperiment(assays = SimpleList("data" = rna), rowRanges = rowRanges(dummy_seRNA))
```

Do you think something similar can work for you?

**Comment by dagarfield** [comment]
Yeah, I'll give this a go -- we can just use another 10x hg38 alignment as the scaffold. 
Though it sounds like the underlying not-quite-integer nature of the data might also be an issue, so I'll be doing some rounding too :) Updates soon-ish.

**Comment by dagarfield** [comment]
Yes, this worked perfectly with a note, for anyone following at home, to remember that gene symbols are not unique. And so if the data you are pulling in is in symbols only (I'm looking at you, ENCODE), beware of duplications. Thanks!
