### ISSUE TITLE
  Positions for peakAnnotation not found

### ISSUE THREAD

**Issue by Brawni** [GreenleafLab/ArchR#188]
Hello,

saveArchRProject throws an error after adding following peak annotation to the ArchR object:

`proj <- addArchRAnnotations(ArchRProj = proj, collection = "EncodeTFBS")`

Saving the object:
```
 saveArchRProject(proj, load=T)
Saving ArchRProject...
Loading ArchRProject...
Error in loadArchRProject(path = outputDirectory) : 
  Positions for peakAnnotation do not exist in saved ArchRProject!
```

This is because there is no Position file saved for this collection:

```
proj@peakAnnotation@listData
$EncodeTFBS
$EncodeTFBS$Name
[1] "EncodeTFBS"

$EncodeTFBS$Positions
[1] "None"

$EncodeTFBS$Matches
[1] "HemeTutorial/Annotations/EncodeTFBS-Matches-In-Peaks.rds"

``` 

Reproduced this on the tutorial data too.

**Comment by schnappi-wkl** [comment]
Hi, Jeff,  relative path is more applicable to this module(loadArchRProject) than absolute path  at the points of user.
Best wishes!
Schnappi
