### ISSUE TITLE
Doing motif enrichment of differential using specific cluster peaks as background

### ISSUE THREAD

**Issue by lsundaram** [GreenleafLab/ArchR#189]
Hi, please let me know if there is an easy way to change the background peaks while calculating enrichments of motifs after differential peak calling using marker features. 
The current option are "all" or "bdg" ( which is the chromvar bdg peaks if i am not wrong) .

If i want to compare these differential peaks to a specific cluster's peaks, please let me know if there is an easy way to do with existing functions.

Thank you.

**Comment by jgranja24** [comment]
Hi @lsundaram,

I dont think I totally get what you are trying to do. One challenge with doing background peaks this ways is that the background set should contain the set of peaks you are testing or else the enrichment test is not valid. This is because a hypergeometric test test's the likelihood of the binding frequency relative to the background frequency and if its higher than the background this is null. 

Hope that helps

Jeff

**Comment by lsundaram** [comment]
Yep sorry what i meant was using the differential peaks vs its own cluster peak as the bdg

**Comment by jgranja24** [comment]
What do you mean by its own cluster peak?

**Comment by lsundaram** [comment]
Sorry for the lack of details. For example, We get marker peaks by doing C1 vs C2. Now to find the upregulated motifs in C1, we find the motif positions and then call peananno function with the background being "all" cells in the project or "bdg" cells of the proj. Instead, can we run it against all peaks in "C1". Please let me know if this is clear.

**Comment by lsundaram** [comment]
Yea makes sense . i take back the question sorry !  I will close this. On a related note, is there a way to extract all peaks for a cluster as a dataframe or SE in archr ?

**Comment by jgranja24** [comment]
No worries, happy to help. What do you mean by that you want the marker peaks?

**Comment by lsundaram** [comment]
I want all peaks from a cluster , Based on the cells in the clusters, if we called peaks on this cluster , that peaks that will be called .

**Comment by Brawni** [comment]
you can get the Granges object of the peaks called on each cluster with getPeakSet() function transform to data.frame and then grep your cluster of interest. 

```
peakset = getPeakSet (archp)
peakset = as.data.frame (peakset, row.names=NULL)
peakset = peakset[grep ('C1', peakset$GroupReplicate),]

```

**Comment by lsundaram** [comment]
Thank you for your suggestion . According to the docs that column 
"This peak set contains an annotation for the group from which each peak originated. However, these annotations do not inherently mean that the given peak was only called in that group, rather that the annotated group had the highest normalized significance for that peak call."

So i would like to know all peaks called in a cluster of cell irrespective of if that cluster had the highest significance or not

**Comment by rcorces** [comment]
Yes - @lsundaram is correct - this column does not signify that the peak is specific to that cluster.

You should have a folder in your `ArchRProject` directory called "PeakCalls". In this, there should be `GRanges` objects for each of the cell groupings on which you called peaks. I believe this is what you are looking for?

**Comment by lsundaram** [comment]
Yes thank you @rcorces .Closing the issue

**Comment by lsundaram** [comment]
It might be useful to add this info to the booklet @rcorces

**Comment by rcorces** [comment]
I'm doing a bit of revisionist history and deleting some of this thread to avoid future confusion. I will make a note to add this to the book.
