### ISSUE TITLE
Problem with import10xFeatureMatrix

### ISSUE THREAD

**Issue by eileen316** [GreenleafLab/ArchR#1894]
**I am getting the following error message. How should I fix it?**

> #Import scRNA
> seRNA <- import10xFeatureMatrix(
+   input = c("filtered_feature_bc_matrix.h5"),
+   names = c("H107DFCm")
+ )
Error in import10xFeatureMatrix(input = c("filtered_feature_bc_matrix.h5"),  : 
  Not all input file paths exist!
> seRNA <- import10xFeatureMatrix(
+   input = c("filtered_feature_bc_matrix.h5"),
+   names = c("H107DFCm")
+ )
Importing Feature Matrix 1 of 1
Re-ordering RNA matricies for consistency.
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'rep.int': error in evaluating the argument 'x' in selecting a method for function 'runValue': error in evaluating the argument 'x' in selecting a method for function 'seqnames': error in evaluating the argument 'x' in selecting a method for function 'sortSeqlevels': error in evaluating the argument 'x' in selecting a method for function 'seqlevels': unable to find an inherited method for function ‘seqinfo’ for signature ‘"SummarizedExperiment"’

**Comment by rcorces** [comment]
Hi @eileen316! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
Please provide as much information as possible when posting an error. I will address this here since it is an error and not in your other post (in Discussions).

Can you recapitulate your error using tutorial code and data? https://greenleaflab.github.io/ArchR_2020/Ex-Analyze-Multiome.html

If not, please provide a reproducible example if you would like help.

**Comment by eileen316** [comment]
**When I try using the example code with example data, it works.
When I use my sample, it doesn't work. 
Do I need to change something in my sample?
I can send you a example file to you. 
Can you give me a your e-mail address?
Below is the content of my log file**

                                                   / |
                                                 /    \
            .                                  /      |.
            \\\                              /        |.
              \\\                          /           `|.
                \\\                      /              |.
                  \                    /                |\
                  \\#####\           /                  ||
                ==###########>      /                   ||
                 \\##==......\    /                     ||
            ______ =       =|__ /__                     ||      \\\
        ,--' ,----`-,__ ___/'  --,-`-===================##========>
       \               '        ##_______ _____ ,--,__,=##,__   ///
        ,    __==    ___,-,__,--'#'  ==='      `-'    | ##,-/
        -,____,---'       \\####\\________________,--\\_##,/
           ___      .______        ______  __    __  .______
          /   \     |   _  \      /      ||  |  |  | |   _  \
         /  ^  \    |  |_)  |    |  ,----'|  |__|  | |  |_)  |
        /  /_\  \   |      /     |  |     |   __   | |      /
       /  _____  \  |  |\  \\___ |  `----.|  |  |  | |  |\  \\___.
      /__/     \__\ | _| `._____| \______||__|  |__| | _| `._____|

Setting default genome to Hg38.
Setting default number of Parallel threads to 10.
Using GeneAnnotation set by addArchRGenome(Hg38)!
Using GeneAnnotation set by addArchRGenome(Hg38)!
ArchR logging to : ArchRLogs/ArchR-createArrows-3486218e1299c-Date-2023-03-27_Time-16-39-38.log
If there is an issue, please report to github with logFile!
2023-03-27 16:39:39 : Batch Execution w/ safelapply!, 0 mins elapsed.
2023-03-27 16:39:39 : (H107DFCm : 1 of 1) Reading In Fragments from inputFiles (readMethod = tabix), 0.002 mins elapsed.
2023-03-27 16:39:39 : (H107DFCm : 1 of 1) Tabix Bed To Temporary File, 0.002 mins elapsed.
2023-03-27 16:40:15 : (H107DFCm : 1 of 1) Reading TabixFile 18 Percent, 0.603 mins elapsed.
2023-03-27 16:40:52 : (H107DFCm : 1 of 1) Reading TabixFile 35 Percent, 1.219 mins elapsed.
2023-03-27 16:41:22 : (H107DFCm : 1 of 1) Reading TabixFile 52 Percent, 1.718 mins elapsed.
2023-03-27 16:41:46 : (H107DFCm : 1 of 1) Reading TabixFile 70 Percent, 2.122 mins elapsed.
2023-03-27 16:42:04 : (H107DFCm : 1 of 1) Reading TabixFile 88 Percent, 2.417 mins elapsed.
2023-03-27 16:42:30 : (H107DFCm : 1 of 1) Successful creation of Temporary File, 2.851 mins elapsed.
2023-03-27 16:42:30 : (H107DFCm : 1 of 1) Creating ArrowFile From Temporary File, 2.851 mins elapsed.
2023-03-27 16:43:39 : (H107DFCm : 1 of 1) Successful creation of Arrow File, 3.996 mins elapsed.
2023-03-27 16:44:27 : (H107DFCm : 1 of 1) CellStats : Number of Cells Pass Filter = 1923 , 4.799 mins elapsed.
2023-03-27 16:44:27 : (H107DFCm : 1 of 1) CellStats : Median Frags = 10731 , 4.799 mins elapsed.
2023-03-27 16:44:27 : (H107DFCm : 1 of 1) CellStats : Median TSS Enrichment = 4.504 , 4.799 mins elapsed.
2023-03-27 16:44:33 : (H107DFCm : 1 of 1) Adding Additional Feature Counts!, 4.896 mins elapsed.
2023-03-27 16:44:49 : (H107DFCm : 1 of 1) Removing Fragments from Filtered Cells, 5.169 mins elapsed.
2023-03-27 16:44:49 : (H107DFCm : 1 of 1) Creating Filtered Arrow File, 5.169 mins elapsed.
2023-03-27 16:45:24 : (H107DFCm : 1 of 1) Finished Constructing Filtered Arrow File!, 5.76 mins elapsed.
2023-03-27 16:45:24 : (H107DFCm : 1 of 1) Adding TileMatrix!, 5.762 mins elapsed.
2023-03-27 16:46:56 : (H107DFCm : 1 of 1) Adding GeneScoreMatrix!, 7.291 mins elapsed.
2023-03-27 16:47:32 : (H107DFCm : 1 of 1) Finished Creating Arrow File, 7.882 mins elapsed.
ArchR logging successful to : ArchRLogs/ArchR-createArrows-3486218e1299c-Date-2023-03-27_Time-16-39-38.log
[1] "H107DFCm.arrow"
Using GeneAnnotation set by addArchRGenome(Hg38)!
Using GeneAnnotation set by addArchRGenome(Hg38)!
Validating Arrows...
Getting SampleNames...
1
Copying ArrowFiles to Ouptut Directory! If you want to save disk space set copyArrows = FALSE
1
Getting Cell Metadata...
1
Merging Cell Metadata...
Initializing ArchRProject...

                                                   / |
                                                 /    \
            .                                  /      |.
            \\\                              /        |.
              \\\                          /           `|.
                \\\                      /              |.
                  \                    /                |\
                  \\#####\           /                  ||
                ==###########>      /                   ||
                 \\##==......\    /                     ||
            ______ =       =|__ /__                     ||      \\\
        ,--' ,----`-,__ ___/'  --,-`-===================##========>
       \               '        ##_______ _____ ,--,__,=##,__   ///
        ,    __==    ___,-,__,--'#'  ==='      `-'    | ##,-/
        -,____,---'       \\####\\________________,--\\_##,/
           ___      .______        ______  __    __  .______
          /   \     |   _  \      /      ||  |  |  | |   _  \
         /  ^  \    |  |_)  |    |  ,----'|  |__|  | |  |_)  |
        /  /_\  \   |      /     |  |     |   __   | |      /
       /  _____  \  |  |\  \\___ |  `----.|  |  |  | |  |\  \\___.
      /__/     \__\ | _| `._____| \______||__|  |__| | _| `._____|

Importing Feature Matrix 1 of 1
Re-ordering RNA matricies for consistency.
Error in h(simpleError(msg, call)) :
  error in evaluating the argument 'x' in selecting a method for function 'rep.int': error in evaluating the argument 'x' in selecting a method for function 'runValue': error in evaluating the argument 'x' in selecting a method for function 'seqnames': error in evaluating the argument 'x' in selecting a method for function 'sortSeqlevels': error in evaluating the argument 'x' in selecting a method for function 'seqlevels': unable to find an inherited method for function ‘seqinfo’ for signature ‘"SummarizedExperiment"’
Calls: import10xFeatureMatrix ... seqlevels -> seqlevels -> seqlevels -> seqinfo -> <Anonymous>
Execution halted
