### ISSUE TITLE
Plot multiple trajectory splines in one umap

### ISSUE THREAD

**Issue by lsundaram** [GreenleafLab/ArchR#190]
Hi I am looking for plotting multiple individually computed splines of different trajectories in one umap . I am not sure if there is an easy hack to get an existing plot function to do , but my attempts to tweak plot trajectory did not work. Please let me know if you feel this is valid or if there is a easy way to do this. Thank you

**Comment by rcorces** [comment]
To my knowledge this does not exist as a feature. The easiest (manual) solution would be to plot multiple UMAPs, superimpose them in illustrator, and manually transfer the spline arrows. Obviously the coloration of cells/hexes does not make sense to include if using multiple spline arrows.

**Comment by lsundaram** [comment]
Got it thank you!
