### ISSUE TITLE
peak calling using NFR fragments

### ISSUE THREAD

**Issue by ivanferrreira** [GreenleafLab/ArchR#1909]
Hi,

I want to peak call on NFR fragments using the following functions:
proj <- addGroupCoverages(proj, maxFragmentLength=147)
proj <- addReproduciblePeakSet(proj)
proj <- addPeakMatrix(proj, maxFragmentLength=147, ceiling=10^9)

available through a modified version of archR advertised by the dpeer lab <https://github.com/dpeerlab/ArchR>

When trying to install though I'm getting:
Skipping install of 'ArchR' from a github remote, the SHA1 (79953a93) has not changed since last install.

Forcing to install from github results in:
  installation of package ‘.../tmp/RtmpM2couO/file28dbc3dd83145/ArchR_1.0.2.tar.gz’ had non-zero exit status

Can you help? I'm not sure how to get it otherwise.

Thanks
Ivan

**Comment by rcorces** [comment]
Hi @ivanferrreira! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
I would suggest asking whoever forked and maintains the repo you are trying to install. This isnt an ArchR issue.
