### ISSUE TITLE
Questions about differential peak analysis. getMarkerFeatures() with binomial, turns out error 'Binomial test requires binarization!'

### ISSUE THREAD

**Issue by hjh-air-cond** [GreenleafLab/ArchR#1912]
Hi! Just wanna ask 2 question about getMarkerFeatres() Function.

1st Question:
When I try to do the pairwise test with 'binomial' methos, it turns out an error:

```
ArchR logging to : ArchRLogs/ArchR-getMarkerFeatures-5ae03dbec673-Date-2023-04-06_Time-15-48-27.log
If there is an issue, please report to github with logFile!
2023-04-06 15:48:28 : Matching Known Biases, 0.004 mins elapsed.
2023-04-06 15:48:30 : Computing Pairwise Tests (1 of 1), 0.041 mins elapsed.
Error: Binomial test requires binarization!
```

And I didn't managed to find a solution among the published issues.

The log file is:
[ArchR-getMarkerFeatures-5ae03dbec673-Date-2023-04-06_Time-15-48-27.log](https://github.com/GreenleafLab/ArchR/files/11167891/ArchR-getMarkerFeatures-5ae03dbec673-Date-2023-04-06_Time-15-48-27.log)

2nd Question:
Also I want to ask the If I'm going to compare the diff-peak  between 2 conditions within 1 cell type(like T Cells), do I need to adjust the pipline ? Like make pseudobulk and call peaks on conditions:

```
SubProj <- OrgProj[OrgProj$CellType == 'T_Cells',]
SubProj <- addGroupCoverages(ArchRProj = SubProj, 
                                groupBy = "Treatment")
SubProj <- addReproduciblePeakSet(ArchRProj = SubProj, 
                               groupBy = "Treatment", 
                               pathToMacs2 = pathToMacs2 )
SubProj <- addPeakMatrix(SubProj)

markerTest <- getMarkerFeatures(
            ArchRProj = SubProj,
            useMatrix = "PeakMatrix",
            groupBy = "Treatment",
            testMethod = testMethod,
            bias = c("TSSEnrichment", "log10(nFrags)"),
            useGroups = 'A',
            bgdGroups = 'B'
        )
```

Cause I noticed that the example in the Documents is basically for comparing between different celltypes, I'm wondering is that ok for comparing between different conditions.

Thanks for all the help!

**Comment by rcorces** [comment]
Hi @hjh-air-cond! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by hjh-air-cond** [comment]
> Hi @hjh-air-cond! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues. **Before we help you, you must respond to the following questions** unless your original post already contained this information: **1.** If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved? **2.** Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example. **3.** Did you post your log file? If not, add it now. **4.** Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

1, I searched the issues but couldn't get useful informations.  I will be thankful and apologize if you can point out the relevent helpful issue.
2, I'm still working on the tutorial dataset to reproduce the bug.
3, Yes, there is the log file.
4,There is no screenshots.

Thanks again!

**Comment by rcorces** [comment]
Your error is quite explicit:
`Error: Binomial test requires binarization!`
You are using a matrix that is not binarized in a context where it is expected to be binarized (the binomial test).  Either change the testMethod or set the `binarize` param to TRUE depending on your specific application

I dont understand your second question. But I dont answer user-specific question on usage. You need to understand your own data and your own analysis and make informed decisions on how to use the software.
