### ISSUE TITLE
copy ArchR outputs to another computer, how to change the working directory sorted in ArchR objects.

### ISSUE THREAD

**Issue by Gavin-Yinld** [GreenleafLab/ArchR#1919]
Hello, I copy the ArchR output to another computer, while plotEmbedding function does not work due to the working directory sorted in ArchR object.

<simpleError in intI(j, n = x@Dim[2], dn[[2]], give.dn = FALSE): no 'dimnames[[.]]': cannot use character indexing>
[ArchR-plotEmbedding-6f082ce35ead-Date-2023-04-14_Time-15-42-09.log](https://github.com/GreenleafLab/ArchR/files/11230729/ArchR-plotEmbedding-6f082ce35ead-Date-2023-04-14_Time-15-42-09.log)

**Comment by rcorces** [comment]
Hi @Gavin-Yinld! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
You cannot simply copy a directory elsewhere in ArchR. This is never suggested in the documentation and is not a supported use case. If you want to do something similar, you must save your ArchR project using `saveArchRProject()` or `subsetArchRProject()`, then copy the entire output directory and re-load the ArchRProject using `loadArchRProject()`. This will update all directory structures.

**Comment by Gavin-Yinld** [comment]
Hi, 
Thank you very much for your reply!
I saved  ArchR project by "saveArchRProject(ArchRProj = projHeme5, outputDirectory = "output", load = FALSE)". Then, copy the entire output folder to my personal computer. And load this ArchR project by "loadArchRProject(path = "./output", force = TRUE, showLogo = TRUE)". While I still have this error when performed the analysis (plotEmbedding function). 
[ArchR-plotEmbedding-6d9c4db55393-Date-2023-04-15_Time-09-20-09.log](https://github.com/GreenleafLab/ArchR/files/11238026/ArchR-plotEmbedding-6d9c4db55393-Date-2023-04-15_Time-09-20-09.log)

**Comment by rcorces** [comment]
If you would like additional assistance, please create a reproducible example using the tutorial dataset.
