### ISSUE TITLE
getGroupSE function

### ISSUE THREAD

**Issue by npacalin** [GreenleafLab/ArchR#192]
I am trying to use getGroupSE() to obtain pseudo bulks for each cluster. For example:
```
groupSE <- getGroupSE(ArchRProj=proj, useMatrix="PeakMatrix", groupBy="Clusters")
```
However, I would like to make sure I am normalizing the pseudo bulks properly for downstream analysis.

Do you recommend normalizing using both the divideN and the scaleTo options? If those are both applied, would you say the bulk tracks are safe to use for downstream analysis or would they require some other kind of normalization? If more normalization would still be needed, what would you recommend? If you are using the scaleTo option, what value(s) do you recommend using?

Also, does getGroupSE() rely on the previous call to addGroupCoverages() and addReproduciblePeakSet(), or does it operate independently from their outputs? More specifically, does the groupBy option need to be given the same CellColData column for getGroupSE, as was given to addGroupCoverages and addReproduciblePeakSet? For example, do all 3 functions need to be called using groupBy="Clusters", or can you do this: 
```
proj <- addGroupCoverages(ArchRproj=proj, groupBy="Clusters" ...)
proj <- addReproduciblePeakSet(ArchRproj=proj, groupBy="Clusters" ...)
proj <- addPeakMatrix(ArchRproj=proj)

groupSE <- getGroupSE(groupBy="Clusters_2" ...)
```

Thank you!

**Comment by rcorces** [comment]
Closing. Feel free to re-open if needed.
