### ISSUE TITLE
addGeneIntegrationMatrix: Error in h5read(ArrowFile, paste0(subGroup, "/Info/FeatureDF"))

### ISSUE THREAD

**Issue by vikon72** [GreenleafLab/ArchR#1920]
**Describe the bug**
When I use addGeneIntegrationMatrix() function,it works well.But when I run follow code, I met the error as shown bellow.
```
getAvailableMatrices(proj_sub)
[1]"GeneIntegrationMatrix""GeneScoreMatrix""TileMatrix"
p4 <- plotEmbedding(
  ArchRProj = proj_sub,
  colorBy = "GeneIntegrationMatrix",
  name = markerGenes[,1],
  continuousSet = "horizonExtra",
  embedding = "UMAP",
  imputeWeights = getImputeWeights(proj_sub),
  size = 0.3
)
Getting ImputeWeights
ArchR logging to : ArchRLogs/ArchR-plotEmbedding-9a7a74ca6c60-Date-2023-04-14_Time-16-06-13.log
If there is an issue, please report to github with logFile!
2023-04-14 16:06:14 : Getting Matrix Values...
Error in h5read(ArrowFile, paste0(subGroup, "/Info/FeatureDF")) : 
  Object 'GeneIntegrationMatrix/Info/FeatureDF' does not exist in this HDF5 file.
```
Also, I met an another error when run addPeak2GeneLinks(), the error as shown bellow.
```
proj_sub <- addPeak2GeneLinks(
  ArchRProj = proj_sub,
  reducedDims = "IterativeLSI"
)
ArchR logging to : ArchRLogs/ArchR-addPeak2GeneLinks-28e376a2da62-Date-2023-04-14_Time-16-57-19.log
If there is an issue, please report to github with logFile!
2023-04-14 16:57:19 : Getting Available Matrices, 0.002 mins elapsed.
Error in h5read(ArrowFiles[x], paste0(useMatrix, "/Info/CellNames")) : 
  Object 'GeneIntegrationMatrix/Info/CellNames' does not exist in this HDF5 file.
```
[ArchR-plotEmbedding-9a7a32aa4fd7-Date-2023-04-14_Time-16-01-49.log](https://github.com/GreenleafLab/ArchR/files/11231206/ArchR-plotEmbedding-9a7a32aa4fd7-Date-2023-04-14_Time-16-01-49.log)
[ArchR-addPeak2GeneLinks-28e376a2da62-Date-2023-04-14_Time-16-57-19.log](https://github.com/GreenleafLab/ArchR/files/11231211/ArchR-addPeak2GeneLinks-28e376a2da62-Date-2023-04-14_Time-16-57-19.log)

**Comment by rcorces** [comment]
Hi @vikon72! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by vikon72** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by vikon72** [comment]
I solved this problem，It was Cause by scRNA data SeuratObject  format indeed.Just need to Convert the format by using as.SingleCellExperiment function in Seurat Package.
