### ISSUE TITLE
Error in getMatrixFromProject: "Error in H5Dread(h5dataset = h5dataset, h5spaceFile = h5spaceFile, h5spaceMem = h5spaceMem,  :"

### ISSUE THREAD

**Issue by YuZhengM** [GreenleafLab/ArchR#1921]
I noticed that when I used the getMatrixFromProject function, there was a problem about HDF5. The following is the detailed related content:

**Attach your log file**

[ArchR-getMatrixFromProject-1bfab75719cfea-Date-2023-04-14_Time-05-37-50.log](https://github.com/GreenleafLab/ArchR/files/11231568/ArchR-getMatrixFromProject-1bfab75719cfea-Date-2023-04-14_Time-05-37-50.log)

**Describe the bug/Browse code information**

```R
> 
> ......
> addArchRGenome("hg38")
> ......
> 
> # proj is a ArchRProject
> idxSample <- BiocGenerics::which(proj$Sample == name)
> cellsSample <- proj$cellNames[idxSample]
> proj_name <- proj[cellsSample, ]
> 
> # 得到 PeakMatrix
> proj_PeakMatrix <- getMatrixFromProject(
+     ArchRProj = proj_name,
+     useMatrix = "PeakMatrix",
+     threads = 1
+ )
> ArchR logging to : ArchRLogs/ArchR-getMatrixFromProject-1bfab75719cfea-Date-2023-04-14_Time-05-37-50.log
> If there is an issue, please report to github with logFile!
> Error in H5Dread(h5dataset = h5dataset, h5spaceFile = h5spaceFile, h5spaceMem = h5spaceMem,  :
>   HDF5. Dataset. Read failed.
> 错误: Error in h5checktype(). H5Identifier not valid.
> 
> 
```

By the way, I use the devtools::install_github("GreenleafLab/ArchR", ref="dev", repos = BiocManager::repositories()) command to install the ArchR package.

I have tried to add the `addArchRThreads(1)` and `addArchRLocking(locking = TRUE)` command before, but I still haven't resolved this issue.

I hope to get your answer, Thank you!

**Comment by rcorces** [comment]
Hi @YuZhengM! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
__Before we help you, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
```R
proj_name <- proj[cellsSample, ]
```
This is no longer an approved method for project subseting. You must use `subsetArchRProject()`
