### ISSUE TITLE
Bug in differential peak calling 

### ISSUE THREAD

**Issue by CSBioAzim** [GreenleafLab/ArchR#194]
I'm seeing some weird patterns in the MA plot of differential peaks calling. It looks that there is a bug in the function.
I've attached a plot where I highlighted the points where they need to be colored but still they are gray. Have a look inside of the circles!
It would be nice to have your explanation on it.
![Bug](https://user-images.githubusercontent.com/15929793/83670367-0aef6400-a5a1-11ea-9ebd-e7485c05f83a.jpg)
![MA_Test](https://user-images.githubusercontent.com/15929793/83704287-b7503b00-a5df-11ea-98be-64a23cc7de1d.jpg)
![PV_Test](https://user-images.githubusercontent.com/15929793/83704295-bfa87600-a5df-11ea-8945-5eba377eea33.jpg)

``

**Comment by jgranja24** [comment]
Have you looked at the FDR and LFC? Variability within a group are not conveyed in this plot.

**Comment by CSBioAzim** [comment]
@jgranja24 @rcorces , I update log2FC vs FDR plot as well. I'm wondering how does the p-value is computed for the differential peaks. Is it the only function of log FC or log FC and mean accessibility? If yes, then why some of the points that have high mean accessibility and high log FC are gray next to the red points with similar characteristics?

**Comment by rcorces** [comment]
I'm not sure I understand your question. Having a high average fold change does not necessarily mean that you will have a significant fold change. If the variance / standard deviation is also very high, you will not pass significance. Presumably this is why you see some points with a high fold change but not passing significance.

**Comment by CSBioAzim** [comment]
@rcorces , I completely agree. Is it possible: 
i) To incorporate covariates to the differential analysis (like age, sex, etc). Without regressing out the effect of covariates, the results might not be very accurate.
ii) Having p-value and also SD for each peak would be very helpful as well. Currently, your function does not output it.

**Comment by jgranja24** [comment]
i) This is currently a bit difficult to incorporate with the current set up. 

ii) I can add p-value, but SD is tricky because certain tests dont use this. I can add it for ttest

**Comment by jgranja24** [comment]
This is updated in the dev branch. Closing this issue.
