### ISSUE TITLE
addInterativeLSI - Error in clusterDF$clusters : $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by khsjh** [GreenleafLab/ArchR#1940]
I'm trying to run ArchR for tutorial.
But there are error messages, which would be related with Seurat.
When I ran ArchR tutorial in Iterative Latent Semantic Indexing (LSI), I got a error message. The code and messages are below.
```
> proj2_LSI <- addIterativeLSI(ArchRProj = proj2,
+                              useMatrix = "TileMatrix",
+                              name = "IterativeLSI",
+                              iterations = 2,
+                              clusterParams = list(resolution = c(0.2),
+                                                   sampleCells = 10000,
+                                                   n.start = 10),
+                              varFeatures = 25000,
+                              dimsToUse = 1:30)
```
output is 
```
Checking Inputs...
ArchR logging to : ArchRLogs/ArchR-addIterativeLSI-aa15b27afc4a8-Date-2023-04-28_Time-14-08-10.log
If there is an issue, please report to github with logFile!
2023-04-28 14:08:10 : Computing Total Across All Features, 0.004 mins elapsed.
2023-04-28 14:08:12 : Computing Top Features, 0.035 mins elapsed.
###########
2023-04-28 14:08:14 : Running LSI (1 of 2) on Top Features, 0.074 mins elapsed.
###########
2023-04-28 14:08:15 : Sampling Cells (N = 10001) for Estimated LSI, 0.075 mins elapsed.
2023-04-28 14:08:15 : Creating Sampled Partial Matrix, 0.075 mins elapsed.
2023-04-28 14:08:21 : Computing Estimated LSI (projectAll = FALSE), 0.183 mins elapsed.
2023-04-28 14:09:05 : Identifying Clusters, 0.923 mins elapsed.

************************************************************
2023-04-28 14:09:17 : ERROR Found in .LSICluster for  
LogFile = ArchRLogs/ArchR-addIterativeLSI-aa15b27afc4a8-Date-2023-04-28_Time-14-08-10.log

<simpleError in apply(., 1, which.max): dim(X) must have a positive length>

************************************************************

Error in clusterDF$clusters : $ operator is invalid for atomic vectors
```

How can I solve them?
My ArchR version is 1.0.2 and Seurat is 4.3.0

I attempted log file below
[ArchR-addIterativeLSI-aa15b27afc4a8-Date-2023-04-28_Time-14-08-10.log](https://github.com/GreenleafLab/ArchR/files/11350334/ArchR-addIterativeLSI-aa15b27afc4a8-Date-2023-04-28_Time-14-08-10.log)

**Comment by rcorces** [comment]
Hi @khsjh! Thanks for using ArchR! I am currently on vacation and will not be responding to any issues or discussion threads until 5/5.<br />
Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
It is worth noting that there are very few actual bugs in ArchR. If you are getting an error, it is probably something specific to your dataset, usage, or computational environment, all of which are extremely challenging to troubleshoot. As such, we require [reproducible examples](https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html) (preferably using the tutorial dataset) from users who want assistance. If you cannot reproduce your error, how will we be able to help?
Before going through the work of making a reproducible example, search the previous [Issues](https://github.com/GreenleafLab/ArchR/issues), [Discussions](https://github.com/GreenleafLab/ArchR/discussions), [function definitions](https://www.archrproject.com/reference/index.html), or the [ArchR manual](https://www.archrproject.com/bookdown/index.html) and you will likely find the answers you are looking for.
If your post does not contain a reproducible example, it is unlikely to receive a response.<br />
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by khsjh** [comment]
With reinstall Seurat and ArchR, when I copy and paste the tutorial code and run from first to here and the it worked
I don't know about what happened in the past, This problem is solved.
