### ISSUE TITLE
Log file does not report the Macs2 

### ISSUE THREAD

**Issue by havu73** [GreenleafLab/ArchR#1945]
Hi,

Thank you for creating ArchR. I have a question/bug report related to logging system (function [.logMessage](https://rdrr.io/github/GreenleafLab/ArchR/src/R/LoggerUtils.R). Details:
- I am using the function addReproduciblePeakSet --> call on .callSummitsMACS2 --> create cmd variable of the Macs2 command used to call peaks --> call [.logMessage](https://rdrr.io/github/GreenleafLab/ArchR/src/R/LoggerUtils.R) to report the command.

I am currently having trouble with this function (addReproduciblePeakSet), and I want to see what is the Macs2 command that ArchR used. However, I could NOT see   a single line of message ```Running Macs2 with Params : macs2 callpeak ...``` in my log 
[ArchR-addReproduciblePeakSet-9b6674eb532b-Date-2023-05-13_Time-22-33-43.log](https://github.com/GreenleafLab/ArchR/files/11471221/ArchR-addReproduciblePeakSet-9b6674eb532b-Date-2023-05-13_Time-22-33-43.log) file .

Can you diagnose the problem for me please? I saw some other issue report with correct log file for the function addReproduciblePeakSet, but I have not been able to figure out what exactly is wrong with my setup that the log file is not produced correctly. 

Thank you so much!

**Comment by rcorces** [comment]
Hi @havu73! Thanks for using ArchR! I am currently on vacation and will not be responding to any issues or discussion threads until 5/5.<br />
Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
It is worth noting that there are very few actual bugs in ArchR. If you are getting an error, it is probably something specific to your dataset, usage, or computational environment, all of which are extremely challenging to troubleshoot. As such, we require [reproducible examples](https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html) (preferably using the tutorial dataset) from users who want assistance. If you cannot reproduce your error, how will we be able to help?
Before going through the work of making a reproducible example, search the previous [Issues](https://github.com/GreenleafLab/ArchR/issues), [Discussions](https://github.com/GreenleafLab/ArchR/discussions), [function definitions](https://www.archrproject.com/reference/index.html), or the [ArchR manual](https://www.archrproject.com/bookdown/index.html) and you will likely find the answers you are looking for.
If your post does not contain a reproducible example, it is unlikely to receive a response.<br />
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.
__4.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by rcorces** [comment]
Please create a reproducible example using the tutorial dataset. If you are able to do that, please post again here and I will re-open this issue.
