### ISSUE TITLE
Bug in the plotPeak2GeneHeatmap function

### ISSUE THREAD

**Issue by CSBioAzim** [GreenleafLab/ArchR#195]
@rcorces @jgranja24  ArchR is a great package. But looks that there is still a bug in the "plotPeak2GeneHeatmap" function. I just installed the most recent version of theb package.  
Here is the output:

```
>p <- plotPeak2GeneHeatmap(ArchRProj = projHeme5, groupBy = "Clusters2")
ArchR logging to : ArchRLogs/ArchR-plotPeak2GeneHeatmap-5b3a58c321f9-Date-2020-06-06_Time-16-15-33.log
If there is an issue, please report to github with logFile!
2020-06-06 16:15:58 : Determining KNN Groups!, 0.142 mins elapsed.
2020-06-06 16:16:14 : Ordering Peak2Gene Links!, 0.396 mins elapsed.
2020-06-06 16:16:58 : Constructing ATAC Heatmap!, 1.129 mins elapsed.
Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  row names contain missing values
In addition: Warning message:
did not converge in 10 iterations 
> ?plotPeak2GeneHeatmap()
``` 
Moreover, when I want to the matrices for the gene-2-peak heatmap using:`
p <- plotPeak2GeneHeatmap(ArchRProj = projHeme5, groupBy = "Clusters2",returnMat=TRUE)`

It doesn't give me what I'm expecting. Essentially only contain correlation between gene and peak. No Z score of the RNA and ATAC matrices.

Thanks

**Comment by lsundaram** [comment]
I get the same issue as well.

**Comment by CSBioAzim** [comment]
@rcorces @jgranja24 Is there any update on this issue? 
The function simply doesn't work.

Thank you!

**Comment by lsundaram** [comment]
cD[colOrder,,drop=FALSE] could be  the problem step.
DataFrame with 500 rows and 1 column
                      groupBy
                  <character>
K1    Endocaridum_unidentifed
K2     Vasculatur_development
K3                Endocaridum


The kmeans has K1 K2 and so on rownames , the colOrder has K_1, K_2 and so on

**Comment by jgranja24** [comment]
I see the problem I think its now fixed in the dev branch. Thanks for the help!
