### ISSUE TITLE
Error: C stack usage  1095637066764 is too close to the limit

### ISSUE THREAD

**Issue by Sophiesze** [GreenleafLab/ArchR#196]
Hi GreenleafLab,

I try to subset my ArchRproj and reclustered it. However, it is wired that when I was running TSNE it reported `Error: C stack usage  1095637066764 is too close to the limit `  

Execution halted
 *** caught segfault ***
address (nil), cause 'unknown'

Traceback:
 1: .getClassesFromCache(Class)
 2: getClassDef(Class, where)
 3: getClass(class(x))
 4: envRefInferField(x, what, getClass(class(x)), selfEnv)
 5: x$.self$finalize
 6: (function (x) x$.self$finalize())(<environment>)
An irrecoverable exception occurred. R is aborting now ...

I ran it twice with the same result. It never happened before when I ran more cells with nonlinear reduction. I wonder it is because that ArchR is not supported reclustered or it is because of the Ubuntu system? 

Thanks in advance for your help.

Best,
Sophie

**Comment by Sophiesze** [comment]
I subsetted the ArchRproj after doing Embedding so my ArchRproj is already with LSI, Harmony, TSNE, UMAP. I did the reclustered with new names in the ArchRproj for examples like nLSI, nHarmony, nTSNE and nUMAP.

I wonder would it be better if I create a new ArchRproj without old embedding that I don't want? Does it need to subset the ArrowFile in order to create a new ArchRproj for downstream analysis? I might need to focus on the specific subset of the Cell. Is it possible to do it with ArchR and how to do it?

It is like the function in Seurat Package `CreateSeuratObject` and `GetAssayData`.

Thanks!

**Comment by rcorces** [comment]
This looks like an out of memory error to me. I would increase the available memory or decrease the number of threads you are using.

With respect to your second question, subsetting your ArchRProject can now subset the Arrow Files. Your question isnt very clear but your embeddings, dimenstionality reductions, etc are all named and retrieved by name. If you subset the ArchRProject and want to re-run dimenstionality reduction, that is not a problem - you just give it a new name or use the old name and set `force=TRUE`

**Comment by Sophiesze** [comment]
Thanks. I will try and run it again!
