### ISSUE TITLE
Error when indexing bam with createArrowFiles()

### ISSUE THREAD

**Issue by dgagler** [GreenleafLab/ArchR#1987]
**Attach your log file**
[ArchR-createArrows-643305bba49-Date-2023-07-06_Time-08-53-16.log](https://github.com/GreenleafLab/ArchR/files/11969682/ArchR-createArrows-643305bba49-Date-2023-07-06_Time-08-53-16.log)

**Describe the bug**
Hi all, I'm trying to analyze some scATAC data using fragment.tsv.gz files output by cellranger-arc-v2. When running createArrowFiles() with standard inputs as suggested by the tutorial, I'm receiving an error with an unclear log output. See log. In Rstudio, I'm receiving error text stating that the bam indexing failed, although this doesn't report in the log. See text/screenshot below. Most of my samples worked fine, as can be seen in the log. I've checked the fragment file and the reference genome checks out and it appears structurally identical to the fragment file of one of the successful samples. I'm unsure how to effectively troubleshoot this error at this point. Thanks in advance.

**To Reproduce**
Not applicable.

**Expected behavior**
Arrow files to be created.

**Screenshots**
```
2023-07-06 10:21:12 : (01-163_atac_fragments.tsv.gz : 6 of 8) Adding GeneScoreMatrix!, 87.937 mins elapsed.
2023-07-06 10:22:55 : (01-163_atac_fragments.tsv.gz : 6 of 8) Finished Creating Arrow File, 89.651 mins elapsed.
(ArchRLogs : 7 of 8) Determining Arrow Method to use!
Attempting to index ArchRLogs as bam...
Indexing of BAM file failed for ArchRLogs.
createArrowFiles has encountered an error, checking if any ArrowFiles completed..
2023-07-06 10:22:55 : 
ArchR logging successful to : ArchRLogs/ArchR-createArrows-643305bba49-Date-2023-07-06_Time-08-53-16.log
```

**Comment by rcorces** [comment]
Hi @dgagler! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
It is worth noting that there are very few actual bugs in ArchR. If you are getting an error, it is probably something specific to your dataset, usage, or computational environment, all of which are extremely challenging to troubleshoot. As such, we require [reproducible examples](https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html) (preferably using the tutorial dataset) from users who want assistance. If you cannot reproduce your error, we will not be able to help.
Before going through the work of making a reproducible example, search the previous [Issues](https://github.com/GreenleafLab/ArchR/issues), [Discussions](https://github.com/GreenleafLab/ArchR/discussions), [function definitions](https://www.archrproject.com/reference/index.html), or the [ArchR manual](https://www.archrproject.com/bookdown/index.html) and you will likely find the answers you are looking for.
If your post does not contain a reproducible example, it is unlikely to receive a response.<br />
__In addition to a reproducible example, you must do the following things before we help you, unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Did you post your log file? If not, add it now.
__3.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.
