### ISSUE TITLE
ArchRPRoj is NULL and there is no genome set with addArchRGenome!

### ISSUE THREAD

**Issue by tzhu-bio** [GreenleafLab/ArchR#199]
I have created custom genome with your guides.
![image](https://user-images.githubusercontent.com/54537420/84038015-eeed2780-a9d1-11ea-922b-c3412295f73e.png)
![image](https://user-images.githubusercontent.com/54537420/84038049-f7ddf900-a9d1-11ea-93f0-40057c97775e.png)
But the ArchR gave me an error when I was creating the Arrow file.
 
![image](https://user-images.githubusercontent.com/54537420/84038609-bac63680-a9d2-11ea-8b1a-3e318e968b2d.png)

**Comment by rcorces** [comment]
Have you tried following the instructions from the error? It says that you have not set a genome using the `addArchRGenome()` function?

**Comment by tzhu-bio** [comment]
> Have you tried following the instructions from the error? It says that you have not set a genome using the `addArchRGenome()` function?

Sorry, how to set a genome using the `addArchRGenome()` function?

**Comment by tzhu-bio** [comment]
> Have you tried following the instructions from the error? It says that you have not set a genome using the `addArchRGenome()` function?
Sorry, how to set a custom genome with the `addArchRGenome()` function?

**Comment by tzhu-bio** [comment]
> Have you tried following the instructions from the error? It says that you have not set a genome using the `addArchRGenome()` function?

Sorry, how to set a custom genome with the `addArchRGenome()` function?

**Comment by tzhu-bio** [comment]
> Sorry - I misread your issue. A custom genome is set by creating objects named `geneAnnotation` and `genomeAnnotation`. No need to use `addArchRGenome()`.

Thank you for your reply. I did not read the document carefully. Now my problem has been solved, but another problem has arisen.
https://github.com/GreenleafLab/ArchR/issues/203#issue-636235307

**Comment by yankiven** [comment]
i have the same error "getGeneAnnotation : ArchRPRoj is NULL and there is no genome set with addArchRGenome!", how to solve it

**Comment by yanlongli88** [comment]
> > Sorry - I misread your issue. A custom genome is set by creating objects named `geneAnnotation` and `genomeAnnotation`. No need to use `addArchRGenome()`.
> 
> Thank you for your reply. I did not read the document carefully. Now my problem has been solved, but another problem has arisen. [#203 (comment)](https://github.com/GreenleafLab/ArchR/issues/203#issue-636235307)

Hi , i meet the same problem as you , how did you solved it ,did i miss something?

**Comment by sSScMinghaoLi** [comment]
> > > Sorry - I misread your issue. A custom genome is set by creating objects named `geneAnnotation` and `genomeAnnotation`. No need to use `addArchRGenome()`.
> > 
> > 
> > Thank you for your reply. I did not read the document carefully. Now my problem has been solved, but another problem has arisen. [#203 (comment)](https://github.com/GreenleafLab/ArchR/issues/203#issue-636235307)
> 
> Hi , i meet the same problem as you , how did you solved it ,did i miss something?

This is the complete command：
createArrowFiles(
  inputFiles = NULL,
  sampleNames = [names](https://rdrr.io/r/base/names.html)(inputFiles),
  outputNames = sampleNames,
  validBarcodes = NULL,
  geneAnnotation = [getGeneAnnotation](https://www.archrproject.com/reference/getGeneAnnotation.html)(),
  genomeAnnotation = [getGenomeAnnotation](https://www.archrproject.com/reference/getGenomeAnnotation.html)(),
  minTSS = 4,
  minFrags = 1000,
  maxFrags = 1e+05,
  QCDir = "QualityControl",
  nucLength = 147,
  promoterRegion = [c](https://rdrr.io/r/base/c.html)(2000, 100),
  TSSParams = [list](https://rdrr.io/r/base/list.html)(),
  excludeChr = [c](https://rdrr.io/r/base/c.html)("chrM", "chrY"),
  nChunk = 5,
  bcTag = "qname",
  gsubExpression = NULL,
  bamFlag = NULL,
  offsetPlus = 4,
  offsetMinus = -5,
  addTileMat = TRUE,
  TileMatParams = [list](https://rdrr.io/r/base/list.html)(),
  addGeneScoreMat = TRUE,
  GeneScoreMatParams = [list](https://rdrr.io/r/base/list.html)(),
  force = FALSE,
  threads = [getArchRThreads](https://www.archrproject.com/reference/getArchRThreads.html)(),
  parallelParam = NULL,
  subThreading = TRUE,
  verbose = TRUE,
  cleanTmp = TRUE,
  logFile = [createLogFile](https://www.archrproject.com/reference/createLogFile.html)("createArrows"),
  filterFrags = NULL,
  filterTSS = NULL
)
You need to add the relevant command line to specify your GenomeAnnotation and GeneAnnotation.
