### ISSUE TITLE
Issue with pathToMacs2

### ISSUE THREAD

**Issue by spietrzak** [GreenleafLab/ArchR#200]
I have been working through the steps in the ArchR manual, and I have run into a problem with the Peak Calling using Macs2. I didn't have Macs2 already installed so I used Python3 to install it to my computer (Mac OS). However, when I try to either use the findMacs2 command or specify the path in the addReproduciblePeakSet command, I encounter errors.

For findMacs2(), I see the following output:
`> pathToMacs2 <- findMacs2()
Searching For MACS2..
Not Found in $PATH
Not Found with pip
Error in .checkPath(path2Bin, throwError = error) : 
  object 'error' not found`

For the addReproduciblePeakSet command, I see this output:
`> proj3 <- addReproduciblePeakSet(
+   ArchRProj = proj3, 
+   groupBy = "Clusters", 
+   pathToMacs2 = "~/MyPythonEnv/bin"
+ )
Error in system2(path, "callpeak -h", stdout = TRUE, stderr = TRUE) : 
  error in running command`

This was after updating to a more recent version of ArchR (0.9.5 from 0.9.3). Previously, the second command produced an error saying that the path that I had specified wasn't in my $PATH, even though I had added it to this. These new attempts after updating ArchR didn't produce any log files, but I have attached those from before the update for you. I am also attaching a screenshot of the folders in my $PATH which shows that the folder ~/MyPythonEnv/bin, which contains the Macs2 executable is, is a part of my $PATH.

Any advice would be greatly appreciated. Let me know if any additional information would be helpful.

<img width="572" alt="Screen Shot 2020-06-08 at 4 32 41 PM" src="https://user-images.githubusercontent.com/43301299/84082742-fc8cb800-a9a5-11ea-9518-f599180ffc39.png">

[ArchR-addReproduciblePeakSet-699c7288aeb7-Date-2020-06-08_Time-16-04-38.log](https://github.com/GreenleafLab/ArchR/files/4748728/ArchR-addReproduciblePeakSet-699c7288aeb7-Date-2020-06-08_Time-16-04-38.log)
[ArchR-addReproduciblePeakSet-699c7288aeb7-Date-2020-06-08_Time-16-04-38.log](https://github.com/GreenleafLab/ArchR/files/4748733/ArchR-addReproduciblePeakSet-699c7288aeb7-Date-2020-06-08_Time-16-04-38.log)

**Comment by rcorces** [comment]
The parameter `pathToMacs2` asks for the "full path to the MACS2 executable". You are both providing an abbreviated path (using "~") and the path to the folder containing MACS2 rather than the full path to the actual executable file. If you provide the ___full___ path all the way to the executable file it should work.

**Comment by spietrzak** [comment]
Thanks 
[ArchR-addReproduciblePeakSet-6eae20692928-Date-2020-06-08_Time-16-49-10.log](https://github.com/GreenleafLab/ArchR/files/4748839/ArchR-addReproduciblePeakSet-6eae20692928-Date-2020-06-08_Time-16-49-10.log)
Ryan.

I changed to the full path and it looks like it was initially running normally, but I encountered a different error. In the output, there were several lines where it was saying "No such file or directory" followed by several error messages:

`
> proj3 <- addReproduciblePeakSet(
+   ArchRProj = proj3, 
+   groupBy = "Clusters", 
+   pathToMacs2 = "/Users/stefanpietrzak/MyPythonEnv/bin/macs2"
+ )
ArchR logging to : ArchRLogs/ArchR-addReproduciblePeakSet-6eae20692928-Date-2020-06-08_Time-16-49-10.log
If there is an issue, please report to github with logFile!
2020-06-08 16:49:11 : Peak Calling Parameters!, 0.006 mins elapsed.
    Group nCells nCellsUsed nReplicates nMin nMax maxPeaks
C1     C1     65         60           2   40   40    30000
C2     C2    193        193           2   40  153    96500
C3     C3   1946        540           2   40  500   150000
C4     C4   2466        664           4   45  500   150000
C5     C5   1342       1286           5   73  480   150000
C6     C6    212        212           3   48   91   106000
C7     C7   4104       1581           5   64  500   150000
C8     C8   4921       1840           5   75  500   150000
C9     C9    551        527           3   44  292   150000
C10   C10   5434       1000           2  500  500   150000
C11   C11   2474       1000           2  500  500   150000
C12   C12   3216        847           2  347  500   150000
C13   C13    515        501           2  161  340   150000
C14   C14    490        477           2  209  268   150000
C15   C15   1091       1041           5   65  456   150000
C16   C16    366        320           5   55   78   150000
C17   C17   2814        601           3   46  500   150000
C18   C18   5672       1636           5   53  500   150000
C19   C19   2995       1179           4   42  500   150000
C20   C20   3869       2023           5  319  500   150000
C21   C21     46         42           2   26   28    21000
2020-06-08 16:49:11 : Batching Peak Calls!, 0.006 mins elapsed.
2020-06-08 16:49:11 : Batch Execution w/ safelapply!, 0 mins elapsed.
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
sh: /Users/stefanpietrzak/Documents/UW-Madison/Lab/Single: No such file or directory
2020-06-08 16:51:36 : Identifying Reproducible Peaks!, 2.428 mins elapsed.
Error in .safelapply(seq_along(outSummitList), function(i) { : 
Error Found Iteration 1 : 
	[1] "Error in .logError(e, fn = \".identifyReproduciblePeaks\", info = prefix,  : \n  Exiting See Error Above\n"
	<simpleError in .logError(e, fn = ".identifyReproduciblePeaks", info = prefix,     errorList = errorList, logFile = logFile): Exiting See Error Above>
Error Found Iteration 2 : 
	[1] "Error in .logError(e, fn = \".identifyReproduciblePeaks\", info = prefix,  : \n  Exiting See Error Above\n"
	<simpleError in .logError(e, fn = ".identifyReproduciblePeaks", info = prefix,     errorList = errorList, logFile = logFile): Exiting See Error Above>
Error Found Iteration 3 : 
	[1] "Error in .logError(e, fn = \".identifyReproduciblePeaks\", info = prefix,  : \n  Exiting See Error Above\n"
	<simpleError in .logError(e, fn = ".identifyReproduciblePeaks", info = prefix,     errorList = errorList, logFile = logFile): Exiting See Error Above>
Error Found Iteration 4 : 
	[1] "Error in .logError(e, fn = \".identifyReproduciblePeaks\", info = prefix,  : 
In addition: Warning message:
In mclapply(..., mc.cores = threads, mc.preschedule = preschedule) :;
  21 function calls resulted in an error
`
I'm not sure what the issue could be here. I have attached the associated log file for this

**Comment by spietrzak** [comment]
One thing I noticed in the log file is that it appears that for each cluster, it is trying to use an insertions.bed file in the "Outputs/PeakCalls/InsertionBeds/" folder, which is empty when I went into that folder. Were these supposed to be created in a previous step that I may have missed?

**Comment by rcorces** [comment]
Correct. I will update the documentation to make this more explicit. Peak calling is performed on group coverages which are created using `addGroupCoverages()`. Strongly recommend going through the full tutorial because these steps can be quite complicated.
https://www.archrproject.com/bookdown/making-pseudo-bulk-replicates.html

**Comment by spietrzak** [comment]
Thanks for your quick responses. I have performed the addGroupCoverages step, and it didn't produce any errors, yet I still don't see anything in the InsertionBeds folder. I tried again, but still no luck. The only step that I haven't performed is the integration with scRNA-seq in section 8 of the manual, but I didn't think that would effect these steps. I have attached the log file for this and a screenshot of the output in R. Do you have any thoughts on this? Thanks again for your all of your help.
[ArchR-addGroupCoverages-6eae580d11b7-Date-2020-06-08_Time-20-19-42.log](https://github.com/GreenleafLab/ArchR/files/4749390/ArchR-addGroupCoverages-6eae580d11b7-Date-2020-06-08_Time-20-19-42.log)
<img width="808" alt="Screen Shot 2020-06-08 at 8 46 37 PM" src="https://user-images.githubusercontent.com/43301299/84097119-37ecae00-a9c9-11ea-98fb-9b8695abbdb8.png">

**Comment by rcorces** [comment]
Sorry - I read your previous comment incorrectly. While `addGroupCoverages()` is a prerequisite for peak calling, it has nothing to do with the InsertionBeds folder.
The problem you are having is that one of your directories "Single Cell Project" has spaces in the name. We have encountered this error in other parts of ArchR. If it isnt too much of a hassle, I would re-run everything from a directory path that has no spaces. If that is too inconvenient, you could try saving your ArchRProject using `saveArchRProject()` to a new directory path that doesnt contain spaces but I'm not 100% sure how that will go.

@jgranja24 - flagging this as another "spaces in file/directory names" problem

**Comment by spietrzak** [comment]
Thanks.

I changed the name of the folder so that there are no spaces and tried moving the folder for the R-project to a different directory, but in each case, it says in the log file that the outputDirectory still has the original path with the folder with spaces in it. Do you know if there is a way to easily change this in the ArchR project object without starting over and making a new ArchRProject?

**Comment by rcorces** [comment]
The `outputDirectory` is stored in `proj@projectMetadata$outputDirectory`. You should be able to change the value of this:
```
proj@projectMetadata$outputDirectory <- "/New/Output/Directory"
```
you can validate that this worked by doing `getOutputDirectory(proj)`

**Comment by spietrzak** [comment]
Hi Ryan,

Thanks for all of your help in resolving my previous issues. I was able to go through the rest of the manual without issues. I do have an unrelated question regarding the marker genes/peaks for a particular group of cells. If I wanted a list of particular genes or peaks that are enriched or associated with a particular cluster, is there a way that I can export those marker lists as a table like an Excel spreadsheet. Similarly, is there a way to export the metadata to get a table that has the cells and their cluster number, sample label, etc., in 1 table?

**Comment by spietrzak** [comment]
I also have one additional question: In the section about defining cluster identity using scRNA-seq, it says that ArchR accepts Seurat objects as input. I tried to save my Seurat object as an .rds file using the command `saveRDS(cds, file = "seRNA.rds")` where cds is the name of the Seurat object, but when I try to load the file and get the available column names for this data, I see the following output:
<img width="623" alt="Screen Shot 2020-07-20 at 9 15 06 PM" src="https://user-images.githubusercontent.com/43301299/88005134-418c2a00-cace-11ea-8a8c-38ec64493226.png">
Is there a particular way that I should save my Seurat object before loading it to use in ArchR?
