### ISSUE TITLE
plotBrowserTrack()：cannot change the range of y-axis when plotting peak track

### ISSUE THREAD

**Issue by jinbufan** [GreenleafLab/ArchR#2004]
Hi, I recently used ArchR to analyse several samples, but when I try to plot marker peak track I found I was not able to change the y ranges which showed as 'Norm. ATAC Signal Range (0−0.16) by ReadsInTSS'. More important, I found that the track plot  pattern between marker peaks will change everytime when I re-plotting with same parameters, and the reason was y ranges changed each time. Please check the plot below circled by red rectangle.
So my question is how can I change the ranges of y-axis? I try to find the solution in the original code but I failed. I truly appreciate your time and effort in developing ArchR and contributing to the open-source community. Your expertise is invaluable, and I'm looking forward to a solution that could address my concern. Thank you!
![微信图片_20230819113824](https://github.com/GreenleafLab/ArchR/assets/142666057/535ec6a3-5370-48c3-81f1-7c50631df35b)

**Comment by rcorces** [comment]
Hi @jinbufan! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
It is worth noting that there are very few actual bugs in ArchR. If you are getting an error, it is probably something specific to your dataset, usage, or computational environment, all of which are extremely challenging to troubleshoot. As such, we require [reproducible examples](https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html) (preferably using the tutorial dataset) from users who want assistance. If you cannot reproduce your error, we will not be able to help.
Before going through the work of making a reproducible example, search the previous [Issues](https://github.com/GreenleafLab/ArchR/issues), [Discussions](https://github.com/GreenleafLab/ArchR/discussions), [function definitions](https://www.archrproject.com/reference/index.html), or the [ArchR manual](https://www.archrproject.com/bookdown/index.html) and you will likely find the answers you are looking for.
If your post does not contain a reproducible example, it is unlikely to receive a response.<br />
__In addition to a reproducible example, you must do the following things before we help you, unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Did you post your log file? If not, add it now.
__3.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by jinbufan** [comment]
Sorry and thank you for your reply! I will go to Discussion section to find help.
