### ISSUE TITLE
Is is possible to use getMarkerFeatures() on motifMatrix?

### ISSUE THREAD

**Issue by Sophiesze** [GreenleafLab/ArchR#201]
Hi GreenLeafLab,

When I read the paper you published on Nature Biotechnology - Massively parallel single-cell chromatin landscapes of human immune cell development and intratumoral T cell exhaustion, I noticed that Fig3b was a heatmap made by motif deviation. 

Thus I tried to use `getMarkerFeatures()` and `useMatrix="MotifMatrix"`after I `addDeviationsMatrix()`. I followed the manual book and try to draw heatmap but I got an error when I try to use `markerHeatmap()`. The error said: "No Makers Found!"

I wonder is it possible to calculate marker features directly using MotifMatrix rather than motif enrichment on the marker peaks and how to do it? 

Thank you so much!

Best,
Sophie

**Comment by Sophiesze** [comment]
Thanks, I looked at the #55  and  tried again using `getSeqnames(proj,useMatrix='MotifMatrix') 
` and it returned` Error in .validInput(input = ArchRProj, name = "ArchRProj", valid = "ArchRProject") : could not find function ".validInput"
`. So I tried getMarkerFeatures with `useSeqnames="deviations`. And it seemed to work well. 

What I don't understand is that I look at the markerList as tutorial using `getMarkers(markersMotif, cutOff = "FDR <= 0.01 & Log2FC >= 1.25")` there were markers both meet the above conditions. However when I use `markerHeatmap()`with the same cutoff and it returned no markers. It never happened when I use PeakMatrix or TileMatrix. I also checked the motif Enrichment according to MarkersPeaks using heatmap and motif deviation embedding on Umap, both looked like there were markers on different clusters.

Do I still need to update my ArchR package with `devtools::install_github("GreenleafLab/ArchR", auth_token = token, ref="dev_jg", repos = BiocManager::repositories())`? I have already using Version 0.9.4.

I posted the screenshots below. Thank you so much.

<img width="632" alt="截屏2020-06-11 上午11 14 08" src="https://user-images.githubusercontent.com/53801318/84341027-b9645c00-abd4-11ea-8016-423bf9968886.png">


<img width="676" alt="截屏2020-06-11 上午10 58 29" src="https://user-images.githubusercontent.com/53801318/84340128-8caf4500-abd2-11ea-8091-3a476c7d846c.png">

<img width="808" alt="截屏2020-06-11 上午10 54 45" src="https://user-images.githubusercontent.com/53801318/84339939-1ca0bf00-abd2-11ea-84d3-36d34824f244.png">

**Comment by jgranja24** [comment]
Hi @Sophiesze,

Deviations from chromVAR is not a counts based measure. When creating a markermotif heatmap you should not use Log2FC as these values can be negative. Try "FDR <= 0.01" or "FDR <= 0.01 & MeanDiff >= 0.1". 

Hope that helps

Jeff

**Comment by Sophiesze** [comment]
Thanks for your help. It works well now.
