### ISSUE TITLE
Gene Seqnames not in GenomeAnnotation chromSizes

### ISSUE THREAD

**Issue by HaixJiang** [GreenleafLab/ArchR#2020]
Hi Ryan,
I am working on chicken scATAC data. 
I used the GTF file and the FASTA file provided by Ensemble to build custom BSgenome and TXDB following the archR steps separately.All these processes were executed as required.Although my arrow file was successfully created, but I lost information for four chromosomes.An error occurred while creating the arrow file.The attached file is the logfile.
Please answer my questions amidst your busy schedule!

```
Found Gene Seqnames not in GenomeAnnotation chromSizes, Removing : chr39,W,Z,MT
Found Exon Seqnames not in GenomeAnnotation chromSizes, Removing : chr39,W,Z,MT
Found TSS Seqnames not in GenomeAnnotation chromSizes, Removing : chr39,W,Z,MT
ArchR logging to : ArchRLogs/ArchR-createArrows-5843f37618da3-Date-2023-09-13_Time-06-34-07.68
If there is an issue, please report to github with logFile!
2023-09-13 06:34:07.747149 : Batch Execution w/ safelapply!, 0 mins elapsed.
Attempting to index /storage2/JHX_69/snATAC666/shiyan3/LC666_fragments.tsv.gz as tabix..
2023-09-13 06:35:20.800236 : (LC6663 : 1 of 1) Reading In Fragments from inputFiles (readMethod = tabix), 1.218 mins elapsed.
2023-09-13 06:35:20.807989 : (LC6663 : 1 of 1) Tabix Bed To Temporary File, 1.218 mins elapsed.
...
2023-09-13 06:48:09.780504 : (LC6663 : 1 of 1) Adding GeneScoreMatrix!, 14.034 mins elapsed.
2023-09-13 06:50:01.424695 : (LC6663 : 1 of 1) Finished Creating Arrow File, 15.895 mins elapsed.
ArchR logging successful to : ArchRLogs/ArchR-createArrows-5843f37618da3-Date-2023-09-13_Time-06-34-07.682515.log

```

[ArchR-createArrows-5843f37618da3-Date-2023-09-13_Time-06-34-07.682515.log](https://github.com/GreenleafLab/ArchR/files/12596584/ArchR-createArrows-5843f37618da3-Date-2023-09-13_Time-06-34-07.682515.log)

**Comment by rcorces** [comment]
Hi @HaixJiang! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
It is worth noting that there are very few actual bugs in ArchR. If you are getting an error, it is probably something specific to your dataset, usage, or computational environment, all of which are extremely challenging to troubleshoot. As such, we require [reproducible examples](https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html) (preferably using the tutorial dataset) from users who want assistance. If you cannot reproduce your error, we will not be able to help.
Before going through the work of making a reproducible example, search the previous [Issues](https://github.com/GreenleafLab/ArchR/issues), [Discussions](https://github.com/GreenleafLab/ArchR/discussions), [function definitions](https://www.archrproject.com/reference/index.html), or the [ArchR manual](https://www.archrproject.com/bookdown/index.html) and you will likely find the answers you are looking for.
If your post does not contain a reproducible example, it is unlikely to receive a response.<br />
__In addition to a reproducible example, you must do the following things before we help you, unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Did you post your log file? If not, add it now.
__3.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by HaixJiang** [comment]
> 嗨！感谢您使用 ArchR！请确保您的帖子属于“问题”部分。只有错误和错误报告属于“问题”部分。使用问题和功能请求应发布在“讨论”部分，而不是[“](https://github.com/GreenleafLab/ArchR/discussions)问题”中。值得注意的是，ArchR 中实际的错误很少。如果遇到错误，则可能是特定于数据集、使用情况或计算环境的内容，所有这些问题都非常难以进行故障排除。因此，我们需要需要帮助的用户提供[可重现的示例](https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html)（最好使用教程数据集）。如果您无法重现错误，我们将无法提供帮助。在完成制作可重现示例的工作之前，请搜索之前[的问题](https://github.com/GreenleafLab/ArchR/issues)、[讨论](https://github.com/GreenleafLab/ArchR/discussions)、[函数定义](https://www.archrproject.com/reference/index.html)或 [ArchR 手册](https://www.archrproject.com/bookdown/index.html)，您可能会找到所需的答案。如果您的帖子不包含可重现的示例，则不太可能收到回复。 除了可重现的示例之外，__In，您必须在我们帮助您之前执行以下操作，除非您的原始帖子已经包含此信息： **1.** 如果您遇到错误，您是否已经搜索了以前的问题以确保此问题尚未解决？ **2.** 您是否发布了日志文件？如果没有，请立即添加。 **3.**删除任何包含文本的屏幕截图，而是使用markdown的代码块语法（连续三个反引号）复制并粘贴文本。您可以通过编辑原始帖子来执行此操作。

I went back and reviewed createGenomeAnnotation and BSgenome. It became evident that this process only loaded chromosomes 1-38, while in the BSgenome, it includes chr39, W, Z, and MT completely. How can I address this issue? I am looking forward to your prompt response!

```
genomeAnnotation <- createGenomeAnnotation(genome = BSgenome.Gallus.GRCg7b.v109,filter = TRUE)
Getting genome..
Attempting to infer chromSizes..
Attempting to infer blacklist..
Blacklist not downloaded! Continuing without, be careful for downstream biases..
> genomeAnnotation
List of length 3
names(3): genome chromSizes blacklist
> genomeAnnotation$chromSizes
GRanges object with 38 ranges and 0 metadata columns:
       seqnames      ranges strand
          <Rle>   <IRanges>  <Rle>
   [1]     chr1 1-196449156      *
   [2]     chr2 1-149539284      *
   [3]     chr3 1-110642502      *
   [4]     chr4  1-90861225      *
   [5]     chr5  1-59506338      *
   ...      ...         ...    ...
  [34]    chr34   1-3469343      *
  [35]    chr35    1-554126      *
  [36]    chr36    1-358375      *
  [37]    chr37    1-157853      *
  [38]    chr38    1-667312      *
  -------
  seqinfo: 38 sequences from an unspecified genome
> genomeAnnotation$genome
[1] "BSgenome.Gallus.GRCg7b.v109"
>
> BSgenome.Gallus.GRCg7b.v109
| BSgenome object for Chicken
| - organism: Gallus gallus
| - provider: Ensembl
| - genome: galGal7b109
| - release date: Dec. 2022
| - 214 sequence(s):
|     chr1              chr2              chr3              chr4
|     chr5              chr6              chr7              chr8
|     chr9              chr10             chr11             chr12
|     chr13             chr14             chr15             chr16
|     chr17             chr18             chr19             chr20
|     ...               ...               ...               ...
|     JAENSK010000659.1 JAENSK010000660.1 JAENSK010000661.1 JAENSK010000662.1
|     JAENSK010000663.1 JAENSK010000664.1 JAENSK010000665.1 JAENSK010000666.1
|     JAENSK010000667.1 JAENSK010000668.1 JAENSK010000669.1 JAENSK010000670.1
|     JAENSK010000671.1 JAENSK010000672.1 JAENSK010000673.1 JAENSK010000674.1
|     JAENSK010000675.1 JAENSK010000676.1
|
| Tips: call 'seqnames()' on the object to get all the sequence names, call
| 'seqinfo()' to get the full sequence info, use the '$' or '[[' operator to
| access a given sequence, see '?BSgenome' for more information.
> seqinfo(BSgenome.Gallus.GRCg7b.v109)
Seqinfo object with 214 sequences (1 circular) from galGal7b109 genome:
  seqnames          seqlengths isCircular      genome
  chr1               196449156      FALSE galGal7b109
  chr2               149539284      FALSE galGal7b109
  chr3               110642502      FALSE galGal7b109
  chr4                90861225      FALSE galGal7b109
  chr5                59506338      FALSE galGal7b109
  ...                      ...        ...         ...
  JAENSK010000672.1       2948      FALSE galGal7b109
  JAENSK010000673.1       2415      FALSE galGal7b109
  JAENSK010000674.1       2044      FALSE galGal7b109
  JAENSK010000675.1       1713      FALSE galGal7b109
  JAENSK010000676.1       1437      FALSE galGal7b109
>

```

**Comment by MoritzTh** [comment]
Hi @HaixJiang, did you find a solution? I am having the same problem.
