### ISSUE TITLE
use PBMC but only 28 cells are obtained from fragments.tsv.zg

### ISSUE THREAD

**Issue by Alpha-LiCan** [GreenleafLab/ArchR#2024]
```
library(ArchR)
set.seed(1)
addArchRThreads(threads = 90) 
addArchRGenome("hg38")
input = as.character('data/atac_v1_pbmc_10k_fragments.tsv.gz')
names(input) = 'atac_v1_pbmc_10k_fragments'
ArrowFiles <- createArrowFiles(
  inputFiles = input,
  sampleNames = names(input),
  minTSS = 4, #Dont set this too high because you can always increase later
  minFrags = 1000, 
  addTileMat = TRUE,
  addGeneScoreMat = FALSE
)
proj <- ArchRProject(
  ArrowFiles = ArrowFiles, 
  outputDirectory = "PBMC",
  copyArrows = TRUE #This is recommened so that you maintain an unaltered copy for later usage.
)
proj
```

class: ArchRProject 
outputDirectory: /nfs/public/wxz/Consensus_peak_v2/archr/PBMC 
samples(1): atac_v1_pbmc_10k_fragments
sampleColData names(1): ArrowFiles
cellColData names(13): Sample TSSEnrichment ... nDiFrags BlacklistRatio
numberOfCells(1): 28
medianTSS(1): 4.3645
medianFrags(1): 1377.5

**Comment by rcorces** [comment]
Hi @Alpha-LiCan! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
It is worth noting that there are very few actual bugs in ArchR. If you are getting an error, it is probably something specific to your dataset, usage, or computational environment, all of which are extremely challenging to troubleshoot. As such, we require [reproducible examples](https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html) (preferably using the tutorial dataset) from users who want assistance. If you cannot reproduce your error, we will not be able to help.
Before going through the work of making a reproducible example, search the previous [Issues](https://github.com/GreenleafLab/ArchR/issues), [Discussions](https://github.com/GreenleafLab/ArchR/discussions), [function definitions](https://www.archrproject.com/reference/index.html), or the [ArchR manual](https://www.archrproject.com/bookdown/index.html) and you will likely find the answers you are looking for.
If your post does not contain a reproducible example, it is unlikely to receive a response.<br />
__In addition to a reproducible example, you must do the following things before we help you, unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Did you post your log file? If not, add it now.
__3.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by Alpha-LiCan** [comment]
and if I run this

doubScores <- addDoubletScores(
  input = ArrowFiles,
  k = 10, #Refers to how many cells near a "pseudo-doublet" to count.
  knnMethod = "UMAP", #Refers to the embedding to use for nearest neighbor search.
  LSIMethod = 1
)

it will bug again

***********************************************************
2023-09-18 23:18:52.971371 : ERROR Found in .computeLSI for  
LogFile = ArchRLogs/ArchR-addDoubletScores-37a8ce23adf102-Date-2023-09-18_Time-23-18-44.411688.log

<simpleError in irlba::irlba(mat, nDimensions, nDimensions): max(nu, nv) must be strictly less than min(nrow(A), ncol(A))>

************************************************************


************************************************************
2023-09-18 23:18:53.025826 : ERROR Found in .LSIPartialMatrix for  
LogFile = ArchRLogs/ArchR-addDoubletScores-37a8ce23adf102-Date-2023-09-18_Time-23-18-44.411688.log

<simpleError in .logError(e, fn = ".computeLSI", info = "", errorList = errorList,     logFile = logFile): Exiting See Error Above>

************************************************************


************************************************************
2023-09-18 23:18:53.03133 : ERROR Found in addIterativeLSI for atac_v1_pbmc_10k_fragments (1 of 1) :  
LogFile = ArchRLogs/ArchR-addDoubletScores-37a8ce23adf102-Date-2023-09-18_Time-23-18-44.411688.log

<simpleError in .logError(e, fn = ".LSIPartialMatrix", info = "", errorList = errorList,     logFile = logFile): Exiting See Error Above>

************************************************************

Error in .logError(e, fn = "addIterativeLSI", info = prefix, errorList = list(ArrowFile = ArrowFile), : Exiting See Error Above
Traceback:

1. addDoubletScores(input = ArrowFiles, k = 10, knnMethod = "UMAP", 
 .     LSIMethod = 1)
2. .batchlapply(args, sequential = TRUE)
3. do.call(.safelapply, args)
4. (function (..., threads = 1, preschedule = FALSE) 
 . {
 .     if (tolower(.Platform$OS.type) == "windows") {
 .         threads <- 1
 .     }
 .     if (threads > 1) {
 .         .requirePackage("parallel", source = "cran")
 .         o <- mclapply(..., mc.cores = threads, mc.preschedule = preschedule)
 .         errorMsg <- list()
 .         for (i in seq_along(o)) {
 .             if (inherits(o[[i]], "try-error")) {
 .                 capOut <- utils::capture.output(o[[i]])
 .                 capOut <- capOut[!grepl("attr\\(\\,|try-error", 
 .                   capOut)]
 .                 capOut <- head(capOut, 10)
 .                 capOut <- unlist(lapply(capOut, function(x) substr(x, 
 .                   1, 250)))
 .                 capOut <- paste0("\t", capOut)
 .                 errorMsg[[length(errorMsg) + 1]] <- paste0(c(paste0("Error Found Iteration ", 
 .                   i, " : "), capOut), "\n")
 .             }
 .         }
 .         if (length(errorMsg) != 0) {
 .             errorMsg <- unlist(errorMsg)
 .             errorMsg <- head(errorMsg, 50)
 .             errorMsg[1] <- paste0("\n", errorMsg[1])
 .             stop(errorMsg)
 .         }
 .     }
 .     else {
 .         o <- lapply(...)
 .     }
 .     o
 . })(useMatrix = "TileMatrix", k = 10, nTrials = 5, dimsToUse = 1:30, 
 .     LSIMethod = 1, scaleDims = FALSE, corCutOff = 0.75, knnMethod = "UMAP", 
 .     UMAPParams = list(n_neighbors = 40, min_dist = 0.4, metric = "euclidean", 
 .         verbose = FALSE), LSIParams = list(outlierQuantiles = NULL, 
 .         filterBias = FALSE), outDir = "QualityControl", threads = 1, 
 .     force = FALSE, verbose = TRUE, logFile = "ArchRLogs/ArchR-addDoubletScores-37a8ce23adf102-Date-2023-09-18_Time-23-18-44.411688.log", 
 .     ArrowFiles = "atac_v1_pbmc_10k_fragments.arrow", X = 1L, 
 .     FUN = function (i = NULL, ArrowFiles = NULL, useMatrix = "TileMatrix", 
 .         allCells = NULL, UMAPParams = list(), LSIParams = list(), 
 .         nTrials = 5, dimsToUse = 1:30, corCutOff = 0.75, LSIMethod = 1, 
 .         sampleCells = NULL, scaleDims = FALSE, k = 10, nSample = 1000, 
 .         knnMethod = "UMAP", outDir = "QualityControl", force = FALSE, 
 .         subThreads = 1, verbose = TRUE, tstart = NULL, logFile = NULL) 
 .     {
 .         if (is.null(tstart)) {
 .             tstart <- Sys.time()
 .         }
 .         ArrowFile <- ArrowFiles[i]
 .         sampleName <- .sampleName(ArrowFile)
 .         outDir <- file.path(outDir, sampleName)
 .         dir.create(outDir, showWarnings = FALSE)
 .         prefix <- sprintf("%s (%s of %s) : ", sampleName, i, 
 .             length(ArrowFiles))
 .         .logDiffTime(sprintf("%s Computing Doublet Statistics", 
 .             prefix), tstart, addHeader = FALSE, verbose = verbose, 
 .             logFile = logFile)
 .         tmpDir <- .tempfile()
 .         dir.create(tmpDir)
 .         proj <- suppressMessages(ArchRProject(ArrowFiles = ArrowFile, 
 .             outputDirectory = tmpDir, copyArrows = FALSE, showLogo = FALSE, 
 .             geneAnnotation = .nullGeneAnnotation(), genomeAnnotation = .nullGenomeAnnotation()))
 .         if (is.null(allCells)) {
 .             proj@cellColData <- proj@cellColData[.availableCells(ArrowFile, 
 .                 useMatrix), ]
 .         }
 .         else {
 .             proj@cellColData <- proj@cellColData[which(rownames(proj@cellColData) %in% 
 .                 allCells), ]
 .         }
 .         .logDiffTime("Running IterativeLSI", tstart, addHeader = FALSE, 
 .             verbose = FALSE, logFile = logFile)
 .         LSIParams$ArchRProj <- proj
 .         LSIParams$saveIterations <- FALSE
 .         LSIParams$useMatrix <- useMatrix
 .         LSIParams$LSIMethod <- LSIMethod
 .         LSIParams$dimsToUse <- dimsToUse
 .         LSIParams$scaleDims <- scaleDims
 .         LSIParams$corCutOff <- corCutOff
 .         LSIParams$threads <- subThreads
 .         LSIParams$verbose <- FALSE
 .         LSIParams$force <- TRUE
 .         LSIParams$logFile <- logFile
 .         proj <- tryCatch({
 .             do.call(addIterativeLSI, LSIParams)
 .         }, error = function(e) {
 .             .logError(e, fn = "addIterativeLSI", info = prefix, 
 .                 errorList = list(ArrowFile = ArrowFile), logFile = logFile)
 .         })
 .         .logDiffTime("Constructing Partial Matrix for Projection", 
 .             tstart, addHeader = FALSE, verbose = FALSE, logFile = logFile)
 .         LSI <- getReducedDims(ArchRProj = proj, reducedDims = "IterativeLSI", 
 .             corCutOff = corCutOff, dimsToUse = dimsToUse, scaleDims = scaleDims, 
 .             returnMatrix = FALSE)
 .         .logThis(LSI, name = paste0(prefix, "LSI Result"), logFile = logFile)
 .         LSIDims <- seq_len(ncol(LSI[[1]]))
 .         if (length(LSIDims) < 2) {
 .             .logMessage("Reduced LSI Dims below 2 dimensions, please increase dimsToUse or increase corCutOff!")
 .             stop("Reduced LSI Dims below 2 dimensions, please increase dimsToUse or increase corCutOff!")
 .         }
 .         featureDF <- LSI$LSIFeatures
 .         mat <- tryCatch({
 .             .getPartialMatrix(ArrowFiles = getArrowFiles(proj), 
 .                 featureDF = featureDF, threads = subThreads, 
 .                 cellNames = rownames(getCellColData(proj)), doSampleCells = FALSE, 
 .                 verbose = FALSE)
 .         }, error = function(e) {
 .             errorList <- list(ArrowFiles = getArrowFiles(proj), 
 .                 featureDF = featureDF, threads = subThreads, 
 .                 cellNames = rownames(getCellColData(proj)), doSampleCells = FALSE, 
 .                 verbose = FALSE)
 .             .logError(e, fn = "getPartialMatrix", info = prefix, 
 .                 errorList = errorList, logFile = logFile)
 .         })
 .         cellNames <- rownames(getCellColData(proj))
 .         .logDiffTime("Running LSI UMAP", tstart, addHeader = FALSE, 
 .             verbose = FALSE, logFile = logFile)
 .         set.seed(1)
 .         UMAPParams <- .mergeParams(UMAPParams, list(n_neighbors = 40, 
 .             min_dist = 0.4, metric = "euclidean", verbose = FALSE))
 .         UMAPParams$X <- LSI$matSVD
 .         UMAPParams$ret_nn <- TRUE
 .         UMAPParams$ret_model <- TRUE
 .         UMAPParams$n_threads <- subThreads
 .         .logThis(UMAPParams, name = paste0(prefix, "UMAP Params"), 
 .             logFile = logFile)
 .         uwotUmap <- tryCatch({
 .             do.call(uwot::umap, UMAPParams)
 .         }, error = function(e) {
 .             errorList <- UMAPParams
 .             .logError(e, fn = "uwot::umap", info = prefix, errorList = errorList, 
 .                 logFile = logFile)
 .         })
 .         .logDiffTime("Simulating and Projecting Doublets", tstart, 
 .             addHeader = FALSE, verbose = FALSE, logFile = logFile)
 .         simDoubletsSave <- tryCatch({
 .             .simulateProjectDoublets(mat = mat, LSI = LSI, sampleRatio1 = c(1/2), 
 .                 sampleRatio2 = c(1/2), nTrials = nTrials * max(floor(nCells(proj)/nSample), 
 .                   1), nSample = nSample, k = k, uwotUmap = uwotUmap, 
 .                 seed = 1, force = force, threads = subThreads, 
 .                 logFile = logFile, prefix = prefix)
 .         }, error = function(e) {
 .             errorList <- list(mat = mat, LSI = LSI, sampleRatio1 = c(1/2), 
 .                 sampleRatio2 = c(1/2), nTrials = nTrials * max(floor(nCells(proj)/nSample), 
 .                   1), nSample = nSample, k = k, uwotUmap = uwotUmap, 
 .                 seed = 1, force = force, threads = subThreads, 
 .                 logFile = logFile, prefix = prefix)
 .             .logError(e, fn = ".simulateProjectDoublets", info = prefix, 
 .                 errorList = errorList, logFile = logFile)
 .         })
 .         if (tolower(knnMethod) == "lsi") {
 .             simDoublets <- SimpleList(doubletUMAP = simDoubletsSave$doubletUMAP, 
 .                 doubletScore = simDoubletsSave$doubletScoreLSI, 
 .                 doubletEnrich = simDoubletsSave$doubletEnrichLSI)
 .         }
 .         else {
 .             simDoublets <- SimpleList(doubletUMAP = simDoubletsSave$doubletUMAP, 
 .                 doubletScore = simDoubletsSave$doubletScoreUMAP, 
 .                 doubletEnrich = simDoubletsSave$doubletEnrichUMAP)
 .         }
 .         .logThis(simDoublets, name = paste0(prefix, "SimulationResults"), 
 .             logFile = logFile)
 .         pal <- c("grey", "#FB8861FF", "#B63679FF", "#51127CFF", 
 .             "#000004FF")
 .         df <- data.frame(row.names = rownames(LSI$matSVD), uwotUmap[[1]], 
 .             type = "experiment")
 .         df[, "score"] <- 0
 .         df[, "enrichment"] <- 0
 .         df[names(simDoublets$doubletScore), "score"] <- simDoublets$doubletScore
 .         df[names(simDoublets$doubletScore), "enrichment"] <- simDoublets$doubletEnrich
 .         doubUMAP <- simDoublets$doubletUMAP
 .         dfDoub <- data.frame(row.names = paste0("doublet_", seq_len(nrow(doubUMAP))), 
 .             .getDensity(doubUMAP[, 1], doubUMAP[, 2]), type = "simulated_doublet")
 .         dfDoub <- dfDoub[order(dfDoub$density), , drop = FALSE]
 .         dfDoub$color <- dfDoub$density
 .         .logThis(df, name = paste0(prefix, "Sample UMAP"), logFile = logFile)
 .         .logThis(dfDoub, name = paste0(prefix, "Simulated Doublet UMAP"), 
 .             logFile = logFile)
 .         summaryList <- SimpleList(originalDataUMAP = df, simulatedDoubletUMAP = dfDoub, 
 .             doubletResults = simDoubletsSave)
 .         .safeSaveRDS(summaryList, file.path(outDir, paste0(.sampleName(ArrowFile), 
 .             "-Doublet-Summary.rds")))
 .         rm(simDoubletsSave)
 .         tmpFile <- .tempfile()
 .         o <- tryCatch({
 .             pdf(file.path(outDir, paste0(.sampleName(ArrowFile), 
 .                 "-Doublet-Summary.pdf")), width = 6, height = 6)
 .             xlim <- range(df$X1) %>% extendrange(f = 0.05)
 .             ylim <- range(df$X2) %>% extendrange(f = 0.05)
 .             pdensity <- ggplot() + .geom_point_rast2(data = df, 
 .                 aes(x = X1, y = X2), color = "lightgrey", size = 0.5) + 
 .                 .geom_point_rast2(data = dfDoub, aes(x = x, y = y, 
 .                   colour = color), size = 0.5) + scale_colour_gradientn(colors = pal) + 
 .                 xlab("UMAP Dimension 1") + ylab("UMAP Dimension 2") + 
 .                 labs(color = "Simulated Doublet Density") + guides(fill = "none") + 
 .                 theme_ArchR(baseSize = 10) + theme(axis.text.x = element_blank(), 
 .                 axis.ticks.x = element_blank(), axis.text.y = element_blank(), 
 .                 axis.ticks.y = element_blank()) + coord_equal(ratio = diff(xlim)/diff(ylim), 
 .                 xlim = xlim, ylim = ylim, expand = FALSE) + ggtitle("Simulated and LSI-Projected Density Overlayed") + 
 .                 theme(legend.direction = "horizontal", legend.box.background = element_rect(color = NA))
 .             pscore <- ggPoint(x = df[, 1], y = df[, 2], color = .quantileCut(df$score, 
 .                 0, 0.95), xlim = xlim, ylim = ylim, discrete = FALSE, 
 .                 size = 0.5, xlab = "UMAP Dimension 1", ylab = "UMAP Dimension 2", 
 .                 pal = pal, title = "Doublet Scores -log10(P-adj.)", 
 .                 colorTitle = "Doublet Scores -log10(P-adj.)", 
 .                 rastr = TRUE, baseSize = 10) + theme(axis.text.x = element_blank(), 
 .                 axis.ticks.x = element_blank(), axis.text.y = element_blank(), 
 .                 axis.ticks.y = element_blank())
 .             penrich <- ggPoint(x = df[, 1], y = df[, 2], color = .quantileCut(df$enrichment, 
 .                 0, 0.95), xlim = xlim, ylim = ylim, discrete = FALSE, 
 .                 size = 0.5, xlab = "UMAP Dimension 1", ylab = "UMAP Dimension 2", 
 .                 pal = pal, title = "Simulated Doublet Enrichment over Expectation", 
 .                 colorTitle = "Doublet Enrichment", rastr = TRUE, 
 .                 baseSize = 10) + theme(axis.text.x = element_blank(), 
 .                 axis.ticks.x = element_blank(), axis.text.y = element_blank(), 
 .                 axis.ticks.y = element_blank())
 .             .fixPlotSize(penrich, plotWidth = 6, plotHeight = 6)
 .             grid::grid.newpage()
 .             .fixPlotSize(pscore, plotWidth = 6, plotHeight = 6)
 .             grid::grid.newpage()
 .             .fixPlotSize(pdensity, plotWidth = 6, plotHeight = 6)
 .             dev.off()
 .         }, error = function(e) {
 .             errorList <- list(df = df, dfDoub = dfDoub)
 .             .logError(e, fn = "ggplot", info = prefix, errorList = errorList, 
 .                 logFile = logFile, throwError = FALSE)
 .         })
 .         allCells <- .availableCells(ArrowFile, passQC = FALSE)
 .         allDoubletScores <- rep(-1, length(allCells))
 .         names(allDoubletScores) <- allCells
 .         allDoubletScores[names(simDoublets$doubletScore)] <- simDoublets$doubletScore
 .         allDoubletEnrichment <- rep(-1, length(allCells))
 .         names(allDoubletEnrichment) <- allCells
 .         allDoubletEnrichment[names(simDoublets$doubletEnrich)] <- simDoublets$doubletEnrich
 .         o <- h5closeAll()
 .         h5write(allDoubletScores, file = ArrowFile, "Metadata/DoubletScore")
 .         h5write(allDoubletEnrichment, file = ArrowFile, "Metadata/DoubletEnrichment")
 .         o <- h5closeAll()
 .         out <- SimpleList(doubletScore = simDoublets$doubletScore, 
 .             doubletEnrich = simDoublets$doubletEnrich)
 .         return(out)
 .     }, tstart = structure(1695050324.48479, class = c("POSIXct", 
 .     "POSIXt")), subThreads = 90L)
5. lapply(...)
6. FUN(X[[i]], ...)
7. tryCatch({
 .     do.call(addIterativeLSI, LSIParams)
 . }, error = function(e) {
 .     .logError(e, fn = "addIterativeLSI", info = prefix, errorList = list(ArrowFile = ArrowFile), 
 .         logFile = logFile)
 . })
8. tryCatchList(expr, classes, parentenv, handlers)
9. tryCatchOne(expr, names, parentenv, handlers[[1L]])
10. value[[3L]](cond)
11. .logError(e, fn = "addIterativeLSI", info = prefix, errorList = list(ArrowFile = ArrowFile), 
  .     logFile = logFile)
12. stop("Exiting See Error Above")

**Comment by Alpha-LiCan** [comment]
I must say, this package is undoubtedly the most abysmal one I have ever encountered. Your previous response barely made a dent in solving the issue at hand. I sincerely hope that your upcoming reply will be more satisfactory.

**Comment by Alpha-LiCan** [comment]
this is where I download the fragments

https://cf.10xgenomics.com/samples/cell-atac/1.0.1/atac_v1_pbmc_10k/atac_v1_pbmc_10k_fragments.tsv.gz

**Comment by Alpha-LiCan** [comment]
thank you so much for that
