### ISSUE TITLE
Project multiple motif/gene on one UMAP

### ISSUE THREAD

**Issue by miaomiaotao9** [GreenleafLab/ArchR#206]
May I ask is there any way to plot multiple identified motif/gene on one plot. 
For example, I have identified several motifs or a family, which are enriched in one cluster, and I hope to combine them together then make a plot on one UMAP. 

Thank you very much and ArchR is a fantastic tool for ATAC-seq analysis.

**Comment by jgranja24** [comment]
Hi @miaomiaotao9,

Thanks for the words about ArchR. I dont quite understand what you are asking. I think that you are asking if there is a way to summarize multiple values for plotting in a UMAP? Unfortunately there is no simple way to do this sort of analysis. You could import the matrix and plot this using `ggPoint` in ArchR.

Hope that helps

Jeff

**Comment by miaomiaotao9** [comment]
Hi Jeff,

Thank you very much. It really helps.

Hongyan
