### ISSUE TITLE
Error Report - an errorcreateArrowFiles has encountered an error

### ISSUE THREAD

**Issue by wbszhu** [GreenleafLab/ArchR#2065]
Hi,
I meet the problem. and i can't find out the reason.

**R version**
```
              _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          3.2                         
year           2023                        
month          10                          
day            31                          
svn rev        85441                       
language       R                           
version.string R version 4.3.2 (2023-10-31)
nickname       Eye Holes   
```
**ArchR version**
```
ArchR : Version 1.0.2
For more information see our website : www.ArchRProject.com
If you encounter a bug please report : https://github.com/GreenleafLab/ArchR/issues
Loading Required Packages...
	Loading Package : grid v4.3.2
	Loading Package : gridExtra v2.3
	Loading Package : gtools v3.9.4
	Loading Package : gtable v0.3.4
	Loading Package : ggplot2 v3.4.4
	Loading Package : magrittr v2.0.3
	Loading Package : plyr v1.8.9
	Loading Package : stringr v1.5.1
	Loading Package : data.table v1.14.8
	Loading Package : matrixStats v1.1.0
	Loading Package : S4Vectors v0.40.1
	Loading Package : GenomicRanges v1.54.1
	Loading Package : BiocGenerics v0.48.1
	Loading Package : Matrix v1.6.1.1
	Loading Package : Rcpp v1.0.11
	Loading Package : SummarizedExperiment v1.32.0
	Loading Package : rhdf5 v2.46.0
Setting default number of Parallel threads to 36.
```
**error info**

```
> library("ArchR")
> # Create Arrow Files
> samplenames <- c("180-1","180-2")
> inputfiles <- c("/data/00.data/LW_scATAC-seq/LW-180d-Hypophysis-1.filter.1.fragment.flted.2.tsv.gz",
+                  "/data/00.data/LW_scATAC-seq/LW-180d-Hypophysis-2-2.filter.1.fragment.flted.2.tsv.gz")
> 
> arrowFiles <- createArrowFiles(
+   inputFiles = inputfiles,
+   sampleNames = samplenames,
+   geneAnnotation = geneAnnotation, # Adding gene annotation here
+   genomeAnnotation=genomeAnnotation,
+   minTSS = 4,
+   minFrags = 1000,
+   addTileMat = TRUE,
+   addGeneScoreMat = TRUE,
+   excludeChr = c("chrMT", "chrY", "chrX")
+ )
```
```
Found Gene Seqnames not in GenomeAnnotation chromSizes, Removing : chrMT
Found Exon Seqnames not in GenomeAnnotation chromSizes, Removing : chrMT
Found TSS Seqnames not in GenomeAnnotation chromSizes, Removing : chrMT
ArchR logging to : ArchRLogs/ArchR-createArrows-16575886e1d-Date-2023-11-27_Time-10-54-53.811601.log
If there is an issue, please report to github with logFile!
Cleaning Temporary Files
2023-11-27 10:54:54.015164 : Batch Execution w/ safelapply!, 0 mins elapsed.
Warning: 2 function calls resulted in an errorcreateArrowFiles has encountered an error, checking if any ArrowFiles completed..
2023-11-27 10:58:16.052628 : 
ArchR logging successful to : ArchRLogs/ArchR-createArrows-16575886e1d-Date-2023-11-27_Time-10-54-53.811601.log
```
```
> arrowFiles
character(0)
```
**Here is log file and R markdown notebook.**
[ArchR-createArrows-16575886e1d-Date-2023-11-27_Time-10-54-53.811601.log](https://github.com/GreenleafLab/ArchR/files/13473636/ArchR-createArrows-16575886e1d-Date-2023-11-27_Time-10-54-53.811601.log)

thanks for your help.

**Comment by rcorces** [comment]
Hi @wbszhu! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
It is worth noting that there are very few actual bugs in ArchR. If you are getting an error, it is probably something specific to your dataset, usage, or computational environment, all of which are extremely challenging to troubleshoot. As such, we require [reproducible examples](https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html) (preferably using the tutorial dataset) from users who want assistance. If you cannot reproduce your error, we will not be able to help.
Before going through the work of making a reproducible example, search the previous [Issues](https://github.com/GreenleafLab/ArchR/issues), [Discussions](https://github.com/GreenleafLab/ArchR/discussions), [function definitions](https://www.archrproject.com/reference/index.html), or the [ArchR manual](https://www.archrproject.com/bookdown/index.html) and you will likely find the answers you are looking for.
If your post does not contain a reproducible example, it is unlikely to receive a response.<br />
__In addition to a reproducible example, you must do the following things before we help you, unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Did you post your log file? If not, add it now.
__3.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by nleroy917** [comment]
HI @wbszhu , I see you closed this issue. I was having the same problem just today - how did you resolve this?

**Comment by wbszhu** [comment]
Hi, @nleroy917, I tried running the example data provided by ArchR and testing out the ArchR package. It turns out that my genome which build by myself is'nt correct. I am using the genome from **BSgenome.Sscrofa.UCSC.susScr11**, and everything seems ok.
