### ISSUE TITLE
Error reducedDims not available

### ISSUE THREAD

**Issue by siyunw** [GreenleafLab/ArchR#207]
"Error in addClusters(input = proj, reducedDims = "IterativeLSI"): Error reducedDims not available!
Traceback:

1. addClusters(input = proj, reducedDims = "IterativeLSI")
2. stop("Error reducedDims not available!")"
When running "proj <- addClusters(input = proj, reducedDims = "IterativeLSI")"

**Attach my log file**
[ArchR-addClusters-3f0151d3ead2-Date-2020-06-11_Time-19-29-31.log](https://github.com/GreenleafLab/ArchR/files/4766948/ArchR-addClusters-3f0151d3ead2-Date-2020-06-11_Time-19-29-31.log)

**Describe the bug**
Finished Running IterativeLSI, 5.117 mins elapsed but reducedDims not available.

I have loaded 
library("Seurat")
#if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
#BiocManager::install("monocle")
library("monocle")

**Expected behavior**
Could you please let me know if I am missing some package or further steps to get past this step?

**Screenshots**

<img width="960" alt="screenshot" src="https://user-images.githubusercontent.com/14063363/84432126-3990be80-abe1-11ea-9f6a-6d354770bad5.png">

**Comment by lsundaram** [comment]
I think this was because the umap step was not run before. 
This goes away when thats done.

**Comment by djp123123** [comment]
i guess reducedDims name need to be as same as the name in IterativeLSI dimensionality reduction

**Comment by Jyoung-0108** [comment]
i encountered the same problem and found that it was due to the spelling issue.
you can check it by:
projHeme2@reducedDims
and it turned out to be "iterativeLSI" instead of "IterativeLSI" as default. So the first letter should be lower-case.
