### ISSUE TITLE
Error in import10xFeatureMatrix(input = c("/Volumes/BKUP2/rheMac10_LBN/628/outs/filtered_feature_bc_matrix.h5", :

### ISSUE THREAD

**Issue by sylestiel** [GreenleafLab/ArchR#2079]
Hi @rcorces ,
Trying to integrate 3 multiome datasets. Having problems with running the import10xFeatureMatrix command:
 seRNA <- import10xFeatureMatrix(
    input = c("filePATH/rheMac10_LBN/628/outs/filtered_feature_bc_matrix.h5", "filePATH/rheMac10_LBN/623/outs/filtered_feature_bc_matrix.h5","filePATH/rheMac10_LBN/627/outs/filtered_feature_bc_matrix.h5"),names = c("L105", "L108", "L129"),strictMatch = TRUE
)
Importing Feature Matrix 1 of 3
Importing Feature Matrix 2 of 3
Importing Feature Matrix 3 of 3
Re-ordering RNA matricies for consistency.
Merging individual RNA objects...

Merging L108
### Error in import10xFeatureMatrix(input = c("/Volumes/BKUP2/rheMac10_LBN/628/outs/filtered_feature_bc_matrix.h5",  : 
  Error - rownames (genes) of individual RNA objects are not equivalent.

[ArchR-createArrows-1649b689979d6-Date-2023-11-21_Time-10-19-22.383064.log](https://github.com/GreenleafLab/ArchR/files/13428720/ArchR-createArrows-1649b689979d6-Date-2023-11-21_Time-10-19-22.383064.log).

Any suggestion would be much appreciated!
Thanks!

_Originally posted by @sylestiel in https://github.com/GreenleafLab/ArchR/discussions/2058_

**Comment by rcorces** [comment]
Hi @sylestiel! Thanks for using ArchR! Please make sure that your post belongs in the Issues section. Only bugs and error reports belong in the Issues section. Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br />
It is worth noting that there are very few actual bugs in ArchR. If you are getting an error, it is probably something specific to your dataset, usage, or computational environment, all of which are extremely challenging to troubleshoot. As such, we require [reproducible examples](https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html) (preferably using the tutorial dataset) from users who want assistance. If you cannot reproduce your error, we will not be able to help.
Before going through the work of making a reproducible example, search the previous [Issues](https://github.com/GreenleafLab/ArchR/issues), [Discussions](https://github.com/GreenleafLab/ArchR/discussions), [function definitions](https://www.archrproject.com/reference/index.html), or the [ArchR manual](https://www.archrproject.com/bookdown/index.html) and you will likely find the answers you are looking for.
If your post does not contain a reproducible example, it is unlikely to receive a response.<br />
__In addition to a reproducible example, you must do the following things before we help you, unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Did you post your log file? If not, add it now.
__3.__ Remove any screenshots that contain text and instead copy and paste the text using markdown's codeblock syntax (three consecutive backticks). You can do this by editing your original post.

**Comment by sylestiel** [comment]
The function import10xFeatureMatrix is working only with 1 sample. Gives an error with multiple samples.
