### ISSUE TITLE
GeneScoreMatrix without rownames

### ISSUE THREAD

**Issue by Sophiesze** [GreenleafLab/ArchR#208]
Hi GreenLeafLab,

I was trying to use SingleR package with a public dataset to annotate clusters. I use getMatrixFromProject() to get the GeneScoreMatrix. However when I try to use SingleR and it reported that there are no row names.

<img width="702" alt="截屏2020-06-14 下午4 20 21" src="https://user-images.githubusercontent.com/53801318/84588794-d27f3e00-ae5c-11ea-8780-68767afb5d45.png">

Then I try to figure out the structure of the GeneMatrix.
<img width="1109" alt="截屏2020-06-14 下午3 58 15" src="https://user-images.githubusercontent.com/53801318/84588571-225d0580-ae5b-11ea-8190-ce39131d3b35.png">
<img width="429" alt="截屏2020-06-14 下午4 10 11" src="https://user-images.githubusercontent.com/53801318/84588600-694afb00-ae5b-11ea-9c49-662afdc0289e.png">
And it seems like there is NULL in the dimnames.

I also try to get the GeneMatrix out, but it seemed impossible.
<img width="553" alt="截屏2020-06-14 下午4 24 36" src="https://user-images.githubusercontent.com/53801318/84588615-8bdd1400-ae5b-11ea-879e-b2788cf8cdfd.png">

I am just wondering would it be possible to get the ''real'' GeneMatrix (rownames=genes, colnames=cells) out from the ArchRProj which would be really good for interoperability between different packages? And also it would be really useful if I want to use Pheatmap to draw a different kind of heatmap.

I hope I explained it clearly. Thank you so much.

Best,
Sophie

**Comment by Carota-1** [comment]
Hi，I also met a similar issue. Have you solved it?

**Comment by suragnair** [comment]
`archr_gene_score = getMatrixFromProject(archr_proj, "GeneScoreMatrix"`
 and then `rowData(archr_gene_score)$name` gives the gene names.

**Comment by chaiepi** [comment]
Hi，I met a similar issue.
I want to get the gene x cell Gene Score Matrix, and I ran the following command:
gene_score_matrix <- getMatrixFromProject(dna, useMatrix = "GeneScoreMatrix")
assays(gene_score_matrix)$GeneScoreMatrix
rowData(gene_score_matrix)

The Matrix returned by assays(gene_score_matrix)$GeneScoreMatrix has row names that are not gene names but numerical identifiers. The DataFrame returned by rowData(gene_score_matrix) also has numerical identifiers as row names. Are these numerical identifiers corresponding? If they are corresponding, I can directly assign the gene names to the row names of the Matrix returned by GeneScoreMatrix.
