### ISSUE TITLE
addTileMatrix function produces error

### ISSUE THREAD

**Issue by dgorkin** [GreenleafLab/ArchR#211]
**Attach your log file**
https://www.dropbox.com/s/yfe14hccghc47ro/ArchR-addTileMatrix-1ea86b858d78-Date-2020-06-14_Time-13-00-37.log?dl=0

**Describe the bug**
The "addTileMatrix" functions returns an error "Error in FUN(X[[i]], ...): unused argument (chromSizes = new("GRanges..." (full error message [here](https://www.dropbox.com/s/staezljmisuka9k/output_with_error.txt?dl=0))

**To Reproduce**
library(ArchR)
addArchRGenome("hg19")
inputFiles <- getTutorialData("Hematopoiesis")
ArrowFiles <- createArrowFiles(
  inputFiles = inputFiles,
  sampleNames = names(inputFiles),
  filterTSS = 4, #Dont set this too high because you can always increase later
  filterFrags = 1000, 
  addTileMat = TRUE,
  addGeneScoreMat = TRUE
)
projHeme1 <- ArchRProject(
  ArrowFiles = ArrowFiles, 
  outputDirectory = "HemeTutorial",
  copyArrows = TRUE #This is recommened so that if you modify the Arrow files you have an original copy for later usage.
)

# try add tile matrix
set.tileSize <- 500
set.binarize <- TRUE
current.proj.temp <- projHeme1
current.proj.temp <- addTileMatrix(
    input = current.proj.temp,
    tileSize = set.tileSize,
    binarize = set.binarize,
    force = TRUE)

**Expected behavior**
I expected this function to overwrite the existing tile matrices, eventually allowing me to change the tile size if desired.

**Comment by jgranja24** [comment]
I think this is now fixed in the dev branch. Thanks for the info!
