### ISSUE TITLE
Error: addDoubletScores about ggplot2

### ISSUE THREAD

**Issue by yuyuyuto001** [GreenleafLab/ArchR#2123]
Hey team.
Thank you for making such a useful package.

**Attach log files
ArchR has built-in logging capabilities for complex functions. A log file (which will appear in the console output) must be attached to this issue. Drag and drop it here.
[ArchR-addDoubletScores-1b70395bc576-Date-2024-02-29_Time-09-57-38.155893.log](https://github.com/GreenleafLab/ArchR/files/14441560/ArchR-addDoubletScores-1b70395bc576-Date-2024-02-29_Time-09-57-38.155893.log)

**Bug Description**.
When I use the addDoubletScores function, I get the following error.

```
> doubScores <- addDoubletScores(
+   input = ArrowFiles,
+   k = 10, #Refers to how many cells near a "pseudo-doublet" to count.
+   knnMethod = "UMAP", #Refers to the embedding to use for nearest neighbor search.
+   LSIMethod = 1
+ )
ArchR logging to : ArchRLogs/ArchR-addDoubletScores-1b70395bc576-Date-2024-02-29_Time-09-57-38.155893.log
If there is an issue, please report to github with logFile!
2024-02-29 09:57:38.221589 : Batch Execution w/ safelapply!, 0 mins elapsed.
2024-02-29 09:57:38.231848 : scATAC_BMMC_R1 (1 of 3) :  Computing Doublet Statistics, 0 mins elapsed.
Warning: Data is of class matrix. Coercing to dgCMatrix.
Found more than one class "dist" in cache; using the first, from namespace 'BiocGenerics'
Also defined by ‘spam’
Found more than one class "dist" in cache; using the first, from namespace 'BiocGenerics'
Also defined by ‘spam’
scATAC_BMMC_R1 (1 of 3) : UMAP Projection R^2 = 0.97882

************************************************************
2024-02-29 10:00:00.474936 : ERROR Found in ggplot for scATAC_BMMC_R1 (1 of 3) :  
LogFile = ArchRLogs/ArchR-addDoubletScores-1b70395bc576-Date-2024-02-29_Time-09-57-38.155893.log

<simpleError in g$grobs[[legend]]: no such index at level 2
>

************************************************************

2024-02-29 10:00:00.507234 : scATAC_CD34_BMMC_R1 (2 of 3) :  Computing Doublet Statistics, 2.371 mins elapsed.
Warning: Data is of class matrix. Coercing to dgCMatrix.
Found more than one class "dist" in cache; using the first, from namespace 'BiocGenerics'
Also defined by ‘spam’
Found more than one class "dist" in cache; using the first, from namespace 'BiocGenerics'
Also defined by ‘spam’
scATAC_CD34_BMMC_R1 (2 of 3) : UMAP Projection R^2 = 0.99203

************************************************************
2024-02-29 10:01:55.924854 : ERROR Found in ggplot for scATAC_CD34_BMMC_R1 (2 of 3) :  
LogFile = ArchRLogs/ArchR-addDoubletScores-1b70395bc576-Date-2024-02-29_Time-09-57-38.155893.log

<simpleError in g$grobs[[legend]]: no such index at level 2
>

************************************************************

2024-02-29 10:01:55.957149 : scATAC_PBMC_R1 (3 of 3) :  Computing Doublet Statistics, 4.296 mins elapsed.
Warning: Data is of class matrix. Coercing to dgCMatrix.
Found more than one class "dist" in cache; using the first, from namespace 'BiocGenerics'
Also defined by ‘spam’
Found more than one class "dist" in cache; using the first, from namespace 'BiocGenerics'
Also defined by ‘spam’
scATAC_PBMC_R1 (3 of 3) : UMAP Projection R^2 = 0.96012

************************************************************
2024-02-29 10:03:56.628193 : ERROR Found in ggplot for scATAC_PBMC_R1 (3 of 3) :  
LogFile = ArchRLogs/ArchR-addDoubletScores-1b70395bc576-Date-2024-02-29_Time-09-57-38.155893.log

<simpleError in g$grobs[[legend]]: no such index at level 2
>

************************************************************

ArchR logging successful to : ArchRLogs/ArchR-addDoubletScores-1b70395bc576-Date-2024-02-29_Time-09-57-38.155893.log
```

**How to reproduce
I can reproduce it with the tutorial dataset, and the above code is tutorial's.

**Additional Context**.
I reinstalled ArchR and ggplot2, and tried to restart R and R studio several times, but the problem wasn't solved.
Could you help me to solve this error?
Thanks in advance!

**Comment by rcorces** [comment]
Hi @yuyuyuto001! Thanks for using ArchR! Lately, it has been very challenging for me to keep up with maintenance of this package and all of my other 
responsibilities as a PI. I have not been responding to issue posts and I have not been pushing updates to the software. We are actively searching to hire
a computational biologist to continue to develop and maintain ArchR and related tools. If you know someone who might be a good fit, please let us know!
In the meantime, your issue will likely go without a reply. Most issues with ArchR right not relate to compatibility. Try reverting to R 4.1 and Bioconductor 3.15.
Newer versions of Seurat and Matrix also are causing issues. Sorry for not being able to provide active support for this package at this time.

**Comment by juliabelk** [comment]
For me, downgrading specifically ggplot fixed this. This worked for me:
`conda install conda-forge::r-ggplot2=3.3`
I think its an error with ggplot2 3.5.0

**Comment by EllenvdL** [comment]
@juliabelk For me downgrading ggplot2 does not fix the problem, as I get the following error: 
```
Error: package or namespace load failed for ‘Seurat’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace ‘ggplot2’ 3.3.0 is already loaded, but >= 3.4.0 is required
```
Do you also have a different version of Seurat?
