### ISSUE TITLE
Added Flexibility when Extracting Reads for Arrow from Bam

### ISSUE THREAD

**Issue by gregtbooth** [GreenleafLab/ArchR#213]
I noticed that when creating an Arrow file from a .bam I was loosing a lot of reads (and cells passing filters), compared to my own processing.  

I found that I could recover a lot of these reads by using: 
createArrowFiles( bamFlag = list(isMinusStrand = NA))
which should consider reads aligning to either strand

However, "isMinusStrand = FALSE"  is hardcoded, even when you supply your own bamFlag parameters, so I had to manually edit the ".bamToTmp" function to get it to accept the argument. 
This is a simple fix (just comment out the parameter assignment) , but is there an obvious reason  why we shouldn't allow reads from the minus strand?

**Comment by jgranja24** [comment]
Hi @gregtbooth,

This was originally an implementation by Alicia Schep in chromVAR -

```
bamToFragments <- function(bamfile, paired) {
  if (paired) {
    scanned <- scanBam(bamfile, 
                       param = 
                         ScanBamParam(flag = 
                                        scanBamFlag(isMinusStrand = FALSE, 
                                                    isProperPair = TRUE),
                                      what = c("rname", "pos", "isize")))[[1]]
    scanned_left <- GRanges(seqnames = scanned$rname, 
                            IRanges(start = scanned$pos, 
                                    width = 1), strand = "+")
    scanned_right <- GRanges(seqnames = scanned$rname, 
                             IRanges(start = scanned$pos + 
                                       abs(scanned$isize) - 1, width = 1),
                             strand = "-")
    out <- left_right_to_grglist(scanned_left, scanned_right)
  } else {
    scanned <- scanBam(bamfile,
                       param = ScanBamParam(what = c("rname", 
                                                     "pos", 
                                                     "strand", 
                                                     "qwidth")))[[1]]
    out <- GRanges(seqnames = scanned$rname, 
                   IRanges(start = ifelse(scanned$strand == "-", 
                                          scanned$pos + scanned$qwidth - 1, 
                                          scanned$pos),
                           width = 1))
  }
  return(out)
  
}
```

To my recollection get paired end fragments we read the + strand reads and the isize gives us the other fragment end. If you change this parameter how are you recovering the "fragments". How many reads are you losing? 

Best

Jeff

**Comment by gregtbooth** [comment]
It looks like I loose half of my reads when I use the default bamFlag arguments. 

From the same bam file I ran the following (with and without the bamFlag arguments). 

`ArrowFiles <- createArrowFiles(
  inputFiles = inputFiles,
  sampleNames = names(inputFiles),
  filterTSS = 0, 
  filterFrags = 0, 
  minFrags = 0,
  bcTag = "qname",
  gsubExpression = ":.*", #If BamFile : Cell Barcode is everything after ":"
  bamFlag = list(isMinusStrand = NA, isProperPair = TRUE),
  addTileMat = TRUE,
  addGeneScoreMat = TRUE,
  force = TRUE
)
`

When I use "isMinusStrand = NA", the sum of the nFrags column is ~2x compared with "isMinusStrand = FALSE" .  

Note that to use "isMinusStrand = NA", I use trace(ArchR:::.bamToTmp, edit=TRUE) to comment out the hardcoded setting.

**Comment by jgranja24** [comment]
Are you sure these are fragments? A fragment is 2 read pairs (2 Tn5 insertion points see below), meaning that the paired-end reads correspond to 1 fragment. This is why we read in the plus strand and then the minus strand is the isize distance downstream. If you remove that flag my guess is you are double counting reads.

![image](https://user-images.githubusercontent.com/25017655/84702215-1cbef880-af0b-11ea-9064-ccc3651323a1.png)

Hope that helps

Jeff

**Comment by gregtbooth** [comment]
Hmm, here are the fragment distributions from the two runs.  I feel like if it were simply a result of separately considering the R1 and R2 the sizes would be much smaller in the modified run.  Here they look pretty similar.  
isMinusStrand = FALSE: (default)
<img width="377" alt="Screen Shot 2020-06-15 at 2 01 51 PM" src="https://user-images.githubusercontent.com/12872842/84705855-e71d0e00-af10-11ea-8d4e-29d54ebb59ea.png">

isMinusStrand = NA: 
<img width="403" alt="Screen Shot 2020-06-15 at 2 03 41 PM" src="https://user-images.githubusercontent.com/12872842/84705957-0fa50800-af11-11ea-9d3c-a63965d59ba1.png">

The way I was thinking about it was that, since the transposase isn't directional, you could have the following possible valid pairs: 
Pair orientation: F1R2
Pair orientation: F2R1

I don't know for sure, but I thought that using isMinusStrand = FALSE might eliminate the second possibility (since Read1 would be on the minus strand). 

Thanks again for your work, the package is great btw. 
-Greg

**Comment by jgranja24** [comment]
Hi Greg,

> Hmm, here are the fragment distributions from the two runs. I feel like if it were simply a result of separately considering the R1 and R2 the sizes would be much smaller in the modified run. Here they look pretty similar.

They would look similar because the "widths" will be double counted. What about TSS enrichment? I imagine the NA way makes them worse because they are extensions of the read pairs.

Can you also show the results of `samtools flagstat` on your bam file.

Best

Jeff

**Comment by gregtbooth** [comment]
Here are the TSS enrichment score plots (all cells).
Default: 
<img width="349" alt="Screen Shot 2020-06-15 at 5 07 09 PM" src="https://user-images.githubusercontent.com/12872842/84717506-d7aabe80-af2a-11ea-8534-20262f6c9076.png">
 
isMinusStrand = NA:
<img width="363" alt="Screen Shot 2020-06-15 at 5 07 50 PM" src="https://user-images.githubusercontent.com/12872842/84717525-e5604400-af2a-11ea-9ba1-f1d1327569f9.png">

Here's a look at the samtools flagstat for the bam file I'm using :
210915972 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
210915972 + 0 mapped (100.00% : N/A)
210915972 + 0 paired in sequencing
105457986 + 0 read1
105457986 + 0 read2
210915972 + 0 properly paired (100.00% : N/A)
210915972 + 0 with itself and mate mapped
0 + 0 singletons (0.00% : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)

Note that by this point in our pipeline we've filtered out low quality and unpaired reads etc.

**Comment by jgranja24** [comment]
Hi Greg,

> 105457986 + 0 read1
> 105457986 + 0 read2

This indicates you have ~106M read pairs and thus the above is correct with isMinusStrand = FALSE yielding 103M fragments. Im pretty positive here that the setup in ArchR is correct from this.

Hope that helps,

Jeff

**Comment by gregtbooth** [comment]
Yeah that does seem consistent.  Thanks for working through it with me.

- Greg
