### ISSUE TITLE
addGroupCoverages error

### ISSUE THREAD

**Issue by pennycuda** [GreenleafLab/ArchR#2144]
Hi! I am a developer for HuBMAP Consortium and we use ArchR for our [ATAC-seq pipeline](https://github.com/hubmapconsortium/sc-atac-seq-pipeline). I am [currently updating](https://github.com/hubmapconsortium/sc-atac-seq-pipeline/tree/pennycuda/archr-steps) that pipeline to split our ArchR analysis into two steps due to only needing some of the outputs in another one of our pipelines. During testing, I am getting the following error during the `addGroupCoverages` step and I'm not sure why:
`Error in eval(parse(text = genome)) : 
  object 'BSgenome.Hsapiens.UCSC.hg38' not found
Calls: addGroupCoverages -> .addKmerBiasToCoverage -> eval -> eval
Execution halted`

I updated to the latest version of ArchR in my branch, tried multiple different datasets to test on, and I am still getting this error. Is there anything I could do differently? Attached is the addGroupCoverages ArchR log and the output log for that entire second ArchR step in the pipeline. I'll also point to specific files in the repo that run the ArchR analysis. Thank you in advance for any help.

[ArchR-addGroupCoverages-17b901953-Date-2024-03-30_Time-22-58-32.log](https://github.com/GreenleafLab/ArchR/files/14813674/ArchR-addGroupCoverages-17b901953-Date-2024-03-30_Time-22-58-32.log)

[mar30step2.txt](https://github.com/GreenleafLab/ArchR/files/14813675/mar30step2.txt)

[Step 1 of our ArchR analysis](https://github.com/hubmapconsortium/sc-atac-seq-pipeline/blob/pennycuda/archr-steps/bin/run_ArchR_analysis_pt1.R)

[Step 2 where this is occurring](https://github.com/hubmapconsortium/sc-atac-seq-pipeline/blob/pennycuda/archr-steps/bin/run_ArchR_analysis_pt2.R)

[CWL file that runs the whole pipeline](https://github.com/hubmapconsortium/sc-atac-seq-pipeline/blob/pennycuda/archr-steps/sc_atac_seq_prep_process_analyze.cwl)

**Comment by rcorces** [comment]
Hi @pennycuda! Thanks for using ArchR! Lately, it has been very challenging for me to keep up with maintenance of this package and all of my other 
responsibilities as a PI. I have not been responding to issue posts and I have not been pushing updates to the software. We are actively searching to hire
a computational biologist to continue to develop and maintain ArchR and related tools. If you know someone who might be a good fit, please let us know!
In the meantime, your issue will likely go without a reply. Most issues with ArchR right not relate to compatibility. Try reverting to R 4.1 and Bioconductor 3.15.
Newer versions of Seurat and Matrix also are causing issues. Sorry for not being able to provide active support for this package at this time.

**Comment by pennycuda** [comment]
I think I fixed this by loading the `BSgenome.Hsapiens.UCSC.hg38` library at the top of the second ArchR step file. This wasn't needed previously, so it's a little weird.
