### ISSUE TITLE
co-accessibility for each cluster

### ISSUE THREAD

**Issue by rojinsafavi** [GreenleafLab/ArchR#215]
Hello,

I was wondering if there is a way to look at the co-accessibility for each cluster independently? for example
in the following image, I would like to have an independent blue panel for each cluster
![image](https://user-images.githubusercontent.com/19545198/84950801-4c553880-b0a4-11ea-9a64-29c16ad845ea.png)

**Comment by rcorces** [comment]
Thanks @rojinsafavi - this is related to #149 feel free to read the discussion there and if you think it is sufficiently related then you can cross-post there and close this issue
