### ISSUE TITLE
simpleError: No fragments found!

### ISSUE THREAD

**Issue by butnaro** [GreenleafLab/ArchR#219]
I had used the ArchR package on the same file straight out of 10X cellRanger, and it worked perfectly. 
After is had used the same fragment files for with snaptools pre-snap 
I had gzip the fragment.tsv file back afterwards and all left at the same folders.

when running the

input.file.list = "fragments.tsv.gz"
sample.name.ls = "Donor1_UT"

ArrowFiles <- createArrowFiles(
  inputFiles = input.file.list,
  sampleNames = sample.name.ls,
  filterTSS = 4, #Dont set this too high because you can always increase later
  filterFrags = 1000, 
  addTileMat = TRUE,
  addGeneScoreMat = TRUE
)

This the log i get

Using GeneAnnotation set by addArchRGenome(Hg38)! Using GeneAnnotation set by addArchRGenome(Hg38)! ArchR logging to : ArchRLogs/ArchR-createArrows-1f0a3f3409ee-Date-2020-06-20_Time-08-58-55.log If there is an issue, please report to github with logFile! 2020-06-20 08:58:55 : Batch Execution w/ safelapply!, 0 mins elapsed. 2020-06-20 08:58:55 : (Donor1_UT : 1 of 1) Reading In Fragments from inputFiles (readMethod = tabix), 0 mins elapsed. 2020-06-20 08:58:55 : (Donor1_UT : 1 of 1) Tabix Bed To Temporary File, 0 mins elapsed.  ************************************************************ 2020-06-20 08:59:00 : ERROR Found in .tabixToTmp for (Donor1_UT : 1 of 1)  LogFile = ArchRLogs/ArchR-createArrows-1f0a3f3409ee-Date-2020-06-20_Time-08-58-55.log  <simpleError: No fragments found! >  ************************************************************  2020-06-20 08:59:00 : createArrowFiles has encountered an error, checking if any ArrowFiles completed.. ArchR logging successful to : ArchRLogs/ArchR-createArrows-1f0a3f3409ee-Date-2020-06-20_Time-08-58-55.log
--
 
> | >
>

i looked over the sample file and my fragment files and structurally, looks similar. is there something that snaptools do to the fragment file which makes it problematic for the createArrowFiles() function?

**Comment by jgranja24** [comment]
Can you try `reformatFragmentFiles` to reformat it could be that thye are not propery bgzipped. Additionally can you share the first few lines of your fragment file?

**Comment by butnaro** [comment]
Will try the reformatFragmentFiles() ASAP.
first 10 lines of a fragment file 

ofer@functionalgenomics:/data/projects/Ahituv_OYB_scATAC_16_donors/DONE/Donor2/outs$ zcat fragments.tsv.gz | head -n 10
chr1    9977    10079   ACTTTCAGTAAGTCTC-1      1
chr1    10011   10351   TAGCGGCTCGCACCGA-1      1
chr1    10013   10143   AATGCCATCCCAGCAG-1      2
chr1    10013   10437   TGCATGACATCCCTCA-1      1
chr1    10024   10120   TCAGCTCGTAGTAACA-1      1
chr1    10024   10137   TTGAGTGCACCACAGC-1      1
chr1    10024   10169   TCAGTTTCAAAGCTGG-1      1
chr1    10025   10144   AGCGTATCAACATAAG-1      1
chr1    10025   10197   TCTCTGGAGAGCTGTG-1      1
chr1    10030   10120   CCTTAATGTGGTGGTA-1      3

**Comment by butnaro** [comment]
I had re run the cellranger-atac count and attempted to run the createArrowFiles() on the "fresh" fragment files + i re installed all ArchR packages.
See attached log:
[ArchR-createArrows-5ecf75560db9-Date-2020-06-24_Time-08-49-31.log](https://github.com/GreenleafLab/ArchR/files/4826557/ArchR-createArrows-5ecf75560db9-Date-2020-06-24_Time-08-49-31.log)

**Comment by butnaro** [comment]
Running the reformatFragmentFiles() function on a snaptools handled file yielded  a fragment-Reformat.tsv.gz.
The same issue resulted. 
Also, see attached log
Thanks for your help
[ArchR-createArrows-5ecf5843c758-Date-2020-06-24_Time-09-04-03.log](https://github.com/GreenleafLab/ArchR/files/4826636/ArchR-createArrows-5ecf5843c758-Date-2020-06-24_Time-09-04-03.log)

**Comment by jgranja24** [comment]
I see the issue Im looking into it. It has to do with a matching issue that is a generics problem i think.

**Comment by jgranja24** [comment]
Does the following show an output if you type it into your R console

`XVector::match`

> standardGeneric for "match" defined from package "BiocGenerics"
> 
> function (x, table, nomatch = NA_integer_, incomparables = NULL, 
>     ...) 
> standardGeneric("match")
> <bytecode: 0x3330510>
> <environment: 0x3336740>
> Methods may be defined for arguments: x, table
> Use  showMethods("match")  for currently available ones.

**Comment by butnaro** [comment]
Yes. same output

> Does the following show an output if you type it into your R console
> 
> `XVector::match`
> 
> > standardGeneric for "match" defined from package "BiocGenerics"
> > function (x, table, nomatch = NA_integer_, incomparables = NULL,
> > ...)
> > standardGeneric("match")
> > <bytecode: 0x3330510>
> > <environment: 0x3336740>
> > Methods may be defined for arguments: x, table
> > Use  showMethods("match")  for currently available ones.

**Comment by butnaro** [comment]
Running the reformatFragmentFiles() function on a snaptools handled file yielded a fragment-Reformat.tsv.gz.
And it worked. 
So I will summarize:
1. Snaptools pre-snap changes the read files in a way that made them incompatible with ArchR
2. reformatFragmentFiles() reformat the fragment.tsv.gz to yield fragment-Reformat.tsv.gz. 
3. remove the old fragment.tsv.gz from the outs/ folder (creates some clash) 
4. no change was done to the .tbi file
5. additionally prior to doing all of that ... remove the ArchR package completly and reinstall plus update Seurat

**Comment by rcorces** [comment]
Thanks for following up and for providing the fix that worked for you. Closing this now.
