### ISSUE TITLE
add geneIntegrationMatrix from same-cell expression-chromatin assays

### ISSUE THREAD

**Issue by badoi** [GreenleafLab/ArchR#220]
I have SNARE-Seq2 data with matrix of gene x nuclei expression matrix of same cells being processed through ArchR. I would like to directly add the expression matrix to the open chromatin data. Currently, addGeneIntegrationMatrix() assumes the datasets are unlinked (probably b/c same cell assays are so rare). 

Would it be possible to have an adder function for generic matrix to add the expression matrix directly (e.g. `addCustomMatrix`)? or extend `addGeneIntegrationMatrix` for cell types with matched barcodes. 

Thanks, 

-BaDoi

**Comment by jgranja24** [comment]
This is something we want to add in the near future with a function like 
`addGeneExpressionMatrix` but have not had the time yet to do so. I will
update here when its implemented. 

Hope that helps

Jeff

**Comment by badoi** [comment]
Hi Jeff, yes that sounds like an excellent idea. I'll test it out on my end when you've added it to the dev branch.

**Comment by jgranja24** [comment]
Sorry for the delayed response.. This is now available in the new release version

`
devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.0", repos = BiocManager::repositories())
`

We show a brief tutorial here -

[https://greenleaflab.github.io/ArchR_2020/Ex-Analyze-Multiome.html](https://greenleaflab.github.io/ArchR_2020/Ex-Analyze-Multiome.html)

**Comment by jgranja24** [comment]
Closing this issue. Feel free to open new ones!
