### ISSUE TITLE
No heatmap drawn if only one contrast.

### ISSUE THREAD

**Issue by koenvandenberge** [GreenleafLab/ArchR#223]
Whenever only a single contrast is assessed using `getMarkerFeatures` (e.g. treatment vs control), then there will be no heatmap drawn. 
The same code works if a variable is selected that has more than 2 levels.
I am working with `ArchR_0.9.5`.

```
markerRes <- getMarkerFeatures(
    ArchRProj = proj, 
    useMatrix = "GeneScoreMatrix", 
    groupBy = "hbcInj",
    bias = c("TSSEnrichment", "log10(nFrags)"),
    testMethod = "wilcoxon",
  verbose = FALSE)

markerList <- getMarkers(markerRes, cutOff = "FDR <= 0.01 & Log2FC >= 1.25")
heatmapMarkers <- plotMarkerHeatmap(
  seMarker = markerRes, 
  labelMarkers = markers,
  cutOff = "FDR <= 0.01 & Log2FC >= 1.25", 
  transpose = TRUE
)
ComplexHeatmap::draw(heatmapMarkers, heatmap_legend_side = "bot", annotation_legend_side = "bot")
```

**Comment by rcorces** [comment]
Sorry for the extensive delay in addressing this.
For comparing two groups, you would follow the instructions here:
https://www.archrproject.com/bookdown/pairwise-testing-between-groups.html

Pairwise testing is a special case for getMarkerFeatures.

However, @jgranja24 I feel like this should minimally output an error.

**Comment by jgranja24** [comment]
Hi @koenvandenberge,

This is now a little clearer in the new release branch. Using the argument plotLog2FC will help!

```
#New Release Branch
devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.0", repos = BiocManager::repositories())

library(ArchR)
proj <- getTestProject()
proj$Clusters2 <- ifelse(proj$Clusters %in% c("C1"), "C1", "C0") 
table(proj$Clusters2)
#   C0   C1 
# 1258  959 
markerRes <- getMarkerFeatures(
    ArchRProj = proj, 
    useMatrix = "GeneScoreMatrix", 
    groupBy = "Clusters2",
    bias = c("TSSEnrichment", "log10(nFrags)"),
    testMethod = "wilcoxon",
    verbose = FALSE
)
markerList <- getMarkers(markerRes, cutOff = "FDR <= 0.01 & Log2FC >= 1.25")

#2-Factors
heatmapMarkers <- plotMarkerHeatmap(
  seMarker = markerRes, 
  plotLog2FC = TRUE,
  labelMarkers = markerList[[1]]$name,
  cutOff = "FDR <= 0.01 & Log2FC >= 1.25", 
  transpose = TRUE
)
plotPDF(heatmapMarkers)

#1-Factor
heatmapMarkers <- plotMarkerHeatmap(
  seMarker = markerRes[,1], 
  plotLog2FC = TRUE,
  labelMarkers = markerList[[1]]$name,
  cutOff = "FDR <= 0.01 & abs(Log2FC) >= 1.25", 
  transpose = TRUE
)
plotPDF(heatmapMarkers)

```

Result1
<img width="832" alt="Screen Shot 2020-10-26 at 2 58 53 PM" src="https://user-images.githubusercontent.com/25017655/97233333-07e95000-179c-11eb-8e58-dd677a3be06d.png">

Result2
<img width="849" alt="Screen Shot 2020-10-26 at 2 58 48 PM" src="https://user-images.githubusercontent.com/25017655/97233340-0a4baa00-179c-11eb-864d-518860ab818b.png">

**Comment by jgranja24** [comment]
Closing this issue. Feel free to open new ones!
