### ISSUE TITLE
Issues with ArchR calling MACS2 from WSL in Windows Environment

### ISSUE THREAD

**Issue by joeyQX** [GreenleafLab/ArchR#2231]
escription:
I'm trying to run ArchR's peak calling functionality on Windows using MACS2 installed in WSL. While MACS2 is successfully installed and running in WSL (confirmed with `macs2 --version`), ArchR fails to locate and execute it from the R/RStudio environment.

Current Setup:
- Windows 10/11
- R/RStudio running on Windows
- MACS2 installed in WSL (Ubuntu)
- ArchR project loaded with peakSet = NULL

What I've tried:
1. Setting MACS2 path in R:
pathToMacs2 <- "wsl macs2"
pathToMacs2 <- "/usr/local/bin/macs2"
pathToMacs2 <- "wsl.exe macs2"
#return all not found

Confirming MACS2 installation in WSL:
bash:
which macs2  # returns /usr/local/bin/macs2
macs2 --version  # works correctly

**Comment by rcorces** [comment]
Hi @joeyQX! Thanks for using ArchR! Lately, it has been very challenging for me to keep up with maintenance of this package and all of my other 
responsibilities as a PI. I have not been responding to issue posts and I have not been pushing updates to the software. We are actively searching to hire
a computational biologist to continue to develop and maintain ArchR and related tools. If you know someone who might be a good fit, please let us know!
In the meantime, your issue will likely go without a reply. Most issues with ArchR right not relate to compatibility. Try reverting to R 4.1 and Bioconductor 3.15.
Newer versions of Seurat and Matrix also are causing issues. Sorry for not being able to provide active support for this package at this time.

**Comment by joeyQX** [comment]
> Hi @joeyQX! Thanks for using ArchR! Lately, it has been very challenging for me to keep up with maintenance of this package and all of my other responsibilities as a PI. I have not been responding to issue posts and I have not been pushing updates to the software. We are actively searching to hire a computational biologist to continue to develop and maintain ArchR and related tools. If you know someone who might be a good fit, please let us know! In the meantime, your issue will likely go without a reply. Most issues with ArchR right not relate to compatibility. Try reverting to R 4.1 and Bioconductor 3.15. Newer versions of Seurat and Matrix also are causing issues. Sorry for not being able to provide active support for this package at this time.

Thanks, hope your future reply!

**Comment by immanuelazn** [comment]
Hi joey, pretty sure this is a nuanced question on how $PATH is set, and where it happens with respect to when you execute your wsl command from windows. 
Have you tried this as a test from R?
`system("wsl /usr/local/bin/macs2")`

**Comment by immanuelazn** [comment]
Hi joey, are you still having issues with ArchR?

**Comment by joeyQX** [comment]
> Hi joey, are you still having issues with ArchR?

it seems MACS2 can run but with a new question:

proj <- addReproduciblePeakSet(
+   ArchRProj = proj,
+   groupBy = "ATAC_clusters",
+   pathToMacs2 = pathToMacs2,
+   force = TRUE
+ )
ArchR logging to : ArchRLogs\ArchR-addReproduciblePeakSet-5ca06a5724e1-Date-2024-11-29_Time-10-48-27.55436.log
If there is an issue, please report to github with logFile!
2024-11-29 10:48:27.631469 : Peak Calling Parameters!, 0.001 mins elapsed.
    Group nCells nCellsUsed nReplicates nMin nMax maxPeaks
C1     C1   4976        540           2   40  500   150000
C2     C2   2189        540           2   40  500   150000
C3     C3   2450        540           2   40  500   150000
C4     C4   2115        540           2   40  500   150000
C5     C5    526        526           2  224  302   150000
C6     C6   4053       1000           2  500  500   150000
C7     C7    527        527           2   40  487   150000
C8     C8   1060        558           2   58  500   150000
C9     C9   1101        959           2  459  500   150000
C10   C10   1640        540           2   40  500   150000
C11   C11    262        262           2   40  222   131000
C12   C12    298        298           2  127  171   149000
C13   C13   1087        784           2  284  500   150000
C14   C14    517        517           2   87  430   150000
C15   C15    360        360           2  115  245   150000
C16   C16   1004        651           2  151  500   150000
C17   C17   1103        700           2  200  500   150000
2024-11-29 10:48:27.637425 : Batching Peak Calls!, 0.001 mins elapsed.
2024-11-29 10:48:27.642742 : Batch Execution w/ safelapply!, 0 mins elapsed.
2024-11-29 10:48:27.643881 : Group 1 of 34, Calling Peaks with MACS2!, 0 mins elapsed.
错误于data.table::fread(summitsFile, select = c(1, 2, 3, 5)): 
  文件 'E:\molecular_data\scENDO_scOVAR_2020-1.0.1\scATAC-seq_Processing_Scripts\HGSOC_Cohort\Proj_BeforeIntegration/PeakCalls/InsertionBeds/C1._.Rep1-1_summits.bed' 不存在, 或不可读. getwd()=='E:/molecular_data/scENDO_scOVAR_2020-1.0.1/scATAC-seq_Processing_Scripts/HGSOC_Cohort'
  
  The same with "https://github.com/GreenleafLab/ArchR/issues/239", but i can't solve it even i tried the solutions mentioned before such as reinstalled the numpy.

**Comment by immanuelazn** [comment]
Hi Joey, thanks again for trying to use ArchR. It seems like this is a separate issue, so please create an issue describing how I can reproduce this. Thanks!
