### ISSUE TITLE
subsetting is incomplete

### ISSUE THREAD

**Issue by BCYasser** [GreenleafLab/ArchR#225]
Hi 

I am having a lot of trouble analyzing subsets of the ArchRproject object.

I have noticed that the embeddings aren't subsetted which causes a problem during plotting (the plotting returns an Error related to the fact that the number of embedding available isn't matching the number of cells).

which requires eigher to subset the embedding (I used grepl) or recomputing the  UMAP embedding (which is not ideal because I want to keep the previous embedding, so I can follow my clusters around)

Also, I have noticed that the weights aren't subsetted either.

is it possible to get a subsetted object which contain the truncated dataframes of each slots? so we don't have to refill those slots

thanks

**Comment by JohnGenome** [comment]
subsetArchRProject

**Comment by jgranja24** [comment]
Sorry for the delays,

This is now implemented to be much more fluent --

```
#New Release Branch
devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.0", repos = BiocManager::repositories())

#Get Test Project
proj <- getTestProject()
a <- proj[proj$Clusters != "C1", ]
dim(proj@reducedDims[[1]][[1]])
#[1] 2217    30
dim(a@reducedDims[[1]][[1]])
#[1] 1258    30
dim(proj@embeddings[[1]][[1]])
#[1] 2217    2
dim(a@embeddings[[1]][[1]])
#[1] 1258    2
p1 <- plotEmbedding(proj, name="Clusters")
p2 <- plotEmbedding(a, name="Clusters")
plotPDF(ggAlignPlots(p1, p2, type="h",draw=FALSE))

```

<img width="905" alt="Screen Shot 2020-10-26 at 2 04 23 PM" src="https://user-images.githubusercontent.com/25017655/97228585-601c5400-1794-11eb-8699-67ed46040d9c.png">

**Comment by jgranja24** [comment]
ImputeWeights will not be kept now when the project is subsetted as well. This is because its a cell x cell matrix of weights that are no longer valid once subsetted.

**Comment by jgranja24** [comment]
I am closing this issue. Feel free to open new ones!
