### ISSUE TITLE
Error when creating Arrow file

### ISSUE THREAD

**Issue by yding9** [GreenleafLab/ArchR#226]
Hi,

I was not able to generate the Arrow file with my own data. I am attaching the log file here. Any suggestion is highly appreciated!

[ArchR-createArrows-653f94c154cc9-Date-2020-06-27_Time-18-56-30.log](https://github.com/GreenleafLab/ArchR/files/4841550/ArchR-createArrows-653f94c154cc9-Date-2020-06-27_Time-18-56-30.log)

**Comment by rcorces** [comment]
It looks like your fragment file is not in the expected format. you can try the `reformatFragmentFiles()` function. If that doesnt work, then you can paste the first lines of your fragment file here.

**Comment by yding9** [comment]
Thank you so much for your help! The reformatFragmentFiles( ) function solved the issue.
