### ISSUE TITLE
Individual (single cell) pofile of genome accessibility with browser tracks

### ISSUE THREAD

**Issue by KyleFerchen** [GreenleafLab/ArchR#228]
Many papers show heatmaps with rows for individaul cells and the number of reads at a given genomic loci for accessibility in ATAC-Seq.

Can an option be provided in plotting tracks of the aggregate atac-seq peaks to also plot a heatmap of the individual cells?

**Comment by rcorces** [comment]
Thanks for this suggestion. This is on our list of features to add. We are prioritizing getting things stable for now so I wouldnt expect this update for a bit but we are working on it.

**Comment by jgranja24** [comment]
Hi @kwells4,

This is now available in the new release branch! Only for `plotBrowserTrack`. Im not sure if I want to add it to the ArchRBrowser at this moment.

Best

Jeff

```
#New Release Branch
devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.0", repos = BiocManager::repositories())

library(ArchR)
proj <- getTestProject()
p <- ArchR::plotBrowserTrack(
	ArchRProj = proj,
    plotSummary = c("bulkTrack", "scTrack", "featureTrack", "loopTrack", "geneTrack"),
    sizes = c(8, 8, 1.5, 3, 4),
	groupBy = "Clusters", 
	geneSymbol = "CD247", 
	upstream = 100000, 
	scCellsMax = 100,
	downstream = 100000
)
plotPDF(p)

```

<img width="904" alt="Screen Shot 2020-10-27 at 7 52 26 PM" src="https://user-images.githubusercontent.com/25017655/97385017-17e15c80-188e-11eb-9349-c47243e244b6.png">

**Comment by jgranja24** [comment]
I am closing this issue. Feel free to open new issues!

**Comment by rcorces** [comment]
> Im not sure if I want to add it to the ArchRBrowser at this moment.

I agree - no need for this feature in the ArchRBrowser, at least not right now.

**Comment by KyleFerchen** [comment]
> Hi @kwells4,
> 
> This is now available in the new release branch! Only for `plotBrowserTrack`. Im not sure if I want to add it to the ArchRBrowser at this moment.
> 
> Best
> 
> Jeff
> 
> ```
> #New Release Branch
> devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.0", repos = BiocManager::repositories())
> 
> library(ArchR)
> proj <- getTestProject()
> p <- ArchR::plotBrowserTrack(
> 	ArchRProj = proj,
>     plotSummary = c("bulkTrack", "scTrack", "featureTrack", "loopTrack", "geneTrack"),
>     sizes = c(8, 8, 1.5, 3, 4),
> 	groupBy = "Clusters", 
> 	geneSymbol = "CD247", 
> 	upstream = 100000, 
> 	scCellsMax = 100,
> 	downstream = 100000
> )
> plotPDF(p)
> ```
> 
> <img alt="Screen Shot 2020-10-27 at 7 52 26 PM" width="904" src="https://user-images.githubusercontent.com/25017655/97385017-17e15c80-188e-11eb-9349-c47243e244b6.png">

That's awesome! I like that it gets closer to showing the coaccessibility at the single-cell level
