### ISSUE TITLE
What are nMonoFrags, nMultiFrags, nDiFrags, and nFrags

### ISSUE THREAD

**Issue by Puriney** [GreenleafLab/ArchR#230]
Hello ArchR team,
I was wondering what does the nMonoFrags, nMultiFrags, nDiFrags, and nFrags mean? For example, does nMonoFrags means the number of fragments falling into mononucleosome region which is determined by the fragment length (~200bp)?

<img width="652" alt="Screen Shot 2020-06-29 at 3 18 52 PM" src="https://user-images.githubusercontent.com/1233372/86051860-b7dfc400-ba1b-11ea-9af3-2b613e235df8.png">

[Paper source: From reads to insight: a hitchhiker’s guide to ATAC-seq data analysis](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-020-1929-3)

Does the nFrags means the sum of nMonoFrags, nMultiFrags, nDiFrags? 

Where is the number of fragments possibly fall into the nucleosome free regions?

**Comment by jgranja24** [comment]
nMono = number of fragments less than 147 bp 
nDi = number of fragments between 147 bp and 294 bp
nMulti = number of fragments greater than 294 bp

related to the `nucLength = 147` argument in `createArrow`
