### ISSUE TITLE
support 10x peak-by-cell matrix for input file

### ISSUE THREAD

**Issue by huidongchen** [GreenleafLab/ArchR#231]
Is there a way in ArchR to take as input 10x filtered peak by cell matrix?

**Comment by rcorces** [comment]
This is not currently supported. We dont recommend using this because those peak calls are not cell type-specific (they are called on the merged pseudobulk).

**Comment by huidongchen** [comment]
Or more generally speaking, given a features-by-cells matrix (the features can be either tiles (bins) or a pre-defined set of cell type-specific peaks, is there any plan to support it in the future? I think it will be very useful and make the whole ArchR analysis more flexible.

**Comment by rcorces** [comment]
The way you've described this, it doesn't really fit within the ArchR workflow. ArchRProjects are a lot more than a cell by peak matrix and almost all downstream ArchR functions leverage Arrow files and project metadata. So if you only input a cells x peak matrix, ArchR wont be able to do any downstream computing. 

The correct way to do what you would like to do is to perform the standard ArchR workflow to create Arrow files and then provide ArchR with your desired peak set to create a cells x peak matrix within ArchR. To do this, you would use the `addPeakSet()` function - https://www.archrproject.com/reference/addPeakSet.html

**Comment by huidongchen** [comment]
Thanks for the explanation! This is really helpful!
