### ISSUE TITLE
How can i get & export GeneScoreMatrix or GeneIntegrationMatrix for later use? I cannot get the matrix in a explicit way.

### ISSUE THREAD

**Issue by JohnGenome** [GreenleafLab/ArchR#233]
Hi, GeneScoreMatrix can be created by createArrowFiles function, and GeneIntegrationMatrix can be created by addGeneIntegrationMatrix funtion. The problem is that I know the matrix exists and the plots work well, but I cannot get the matrix in a explicit way. I wonder if there is a fuction that I can get & export GeneScoreMatrix or GeneIntegrationMatrix for later use.

**Comment by JohnGenome** [comment]
Sincerely looking forward to your feedback, which will help me a lot, 3Q!!

**Comment by rcorces** [comment]
I believe you are looking for the `getMatrixFromProject()` function:
https://www.archrproject.com/reference/getMatrixFromProject.html

re-open if necessary
