### ISSUE TITLE
addGeneIntegrationMatrix error when "Getting GeneScoreMatrix"

### ISSUE THREAD

**Issue by wangmhan** [GreenleafLab/ArchR#237]
Hi, 

when I run addGeneIntegrationMatrix, it end up with error: Error in `rownames<-`(`*tmp*`, value = value[[1L]]) : 
  invalid rownames length
[ArchR-addGeneIntegrationMatrix-6b1d1cc3a7a1-Date-2020-07-06_Time-15-06-38.log](https://github.com/GreenleafLab/ArchR/files/4879117/ArchR-addGeneIntegrationMatrix-6b1d1cc3a7a1-Date-2020-07-06_Time-15-06-38.log)

packageVersion("ArchR")
[1] '0.9.5'
packageVersion("Seurat")
[1] '3.1.5.9003'

Please let me know if you have any suggestions to fix it. Thanks!

**Comment by vimarin** [comment]
Hi,

for me it got resolved installing the presto package
install.packages("remotes")
remotes::install_github("immunogenomics/presto")

**Comment by wangmhan** [comment]
Thank you for the reply.

I solved the problem by changing to consistent gene name. Previously my
geneScoreMatrix used geneName, while my scRNA data used geneID.

**Comment by jgranja24** [comment]
Seems like this was a naming issue which was resolved by the user. Thanks for the information! Closing this issue. Feel free to  open new issues! Additionally in the new release branch i have added better messaging to check this!


```
  #Check Gene Names And Seurat RowNames
  geneDF <- .getFeatureDF(getArrowFiles(ArchRProj), useMatrix)
  sumOverlap <- sum(unique(geneDF$name) %in% unique(rownames(seuratRNA)))
  if(sumOverlap < 5){
    stop("Error not enough overlaps (",sumOverlap,") between gene names from gene scores (ArchR) and rna matrix (seRNA)!")
  }
  .logDiffTime(paste0("Found ", sumOverlap, " overlapping gene names from gene scores and rna matrix!"), tstart, verbose = TRUE, logFile = logFile)
```
