### ISSUE TITLE
Errors in using getMarkerFeatures

### ISSUE THREAD

**Issue by sa95078** [GreenleafLab/ArchR#238]
When using getMarkerFeatures, I am getting the following error message: 
Error in cor(estbgdP, obsbgdP) : incompatible dimensions
In addition: Warning messages:
1: In rbind(estbgd, obsbgd) :
  number of columns of result is not a multiple of vector length (arg 1)
2: In rbind(estbgdP, obsbgdP) :
  number of columns of result is not a multiple of vector length (arg 1)

this the end of the log file: 
2020-07-06 20:34:21 : MatrixClass = Sparse.Double.Matrix
2020-07-06 20:34:21 : Matching Known Biases, 0.003 mins elapsed.

This happened after I renamed cell cluster identity and use the new cluster ID. When I used the original cluster ID (groupBy = "Clusters" it worked fine.  

Thank you, 

James

**Comment by sa95078** [comment]
I solved the problem by changing the cluster ID to characters from factors. Thanks,

**Comment by brianpenghe** [comment]
> I solved the problem by changing the cluster ID to characters from factors. Thanks,

I have the same problem though my cluster ID is already in characters class. Any ideas???

**Comment by brianpenghe** [comment]
Interestingly the errors were gone when using Jupyter Notebook. That's strange.

**Comment by qdong2023** [comment]
@brianpenghe Have you saved this problem? I still encountered the same issue. Any suggestions?
> markersPeaks <- getMarkerFeatures(
+     ArchRProj = projmulti_match, 
+     useMatrix = "PeakMatrix", 
+     groupBy = "cell_annotation",
+     bias = c("TSSEnrichment", "log10(nFrags)"),
+     testMethod = "wilcoxon")
ArchR logging to : ArchRLogs/ArchR-getMarkerFeatures-1239618b28ac0-Date-2023-07-13_Time-16-18-47.log
If there is an issue, please report to github with logFile!
2023-07-13 16:18:47 : Matching Known Biases, 0.006 mins elapsed.
Error in cor(estbgdP, obsbgdP) : incompatible dimensions
In addition: Warning messages:
1: In rbind(estbgd, obsbgd) :
  number of columns of result is not a multiple of vector length (arg 1)
2: In rbind(estbgdP, obsbgdP) :
  number of columns of result is not a multiple of vector length (arg 1)
> class(projmulti_match$cell_annotation)
[1] "character"
[ArchR-getMarkerFeatures-1239618b28ac0-Date-2023-07-13_Time-16-18-47.log](https://github.com/GreenleafLab/ArchR/files/12045092/ArchR-getMarkerFeatures-1239618b28ac0-Date-2023-07-13_Time-16-18-47.log)

**Comment by CCCCCCheryl** [comment]
the problem still remain like the following shows
> markersPeaks <- getMarkerFeatures(
+   ArchRProj = proj.macs2, 
+   useMatrix = "PeakMatrix", 
+   groupBy = "response",
+   #bias = c("TSSEnrichment", "log10(nFrags)"),
+   testMethod = "wilcoxon"
+ )
ArchR logging to : ArchRLogs/ArchR-getMarkerFeatures-99196ed40b42-Date-2023-10-08_Time-23-57-28.log
If there is an issue, please report to github with logFile!
2023-10-08 23:57:28 : Matching Known Biases, 0.005 mins elapsed.
Error in cor(estbgdP, obsbgdP) : incompatible dimensions
In addition: Warning messages:
1: In rbind(estbgd, obsbgd) :
  number of columns of result is not a multiple of vector length (arg 1)
2: In rbind(estbgdP, obsbgdP) :
  number of columns of result is not a multiple of vector length (arg 1)

  any suggestions??

**Comment by shycheng** [comment]
> the problem still remain like the following shows
> 
> > markersPeaks <- getMarkerFeatures(
> 
> * ArchRProj = proj.macs2,
> * useMatrix = "PeakMatrix",
> * groupBy = "response",
> * #bias = c("TSSEnrichment", "log10(nFrags)"),
> * testMethod = "wilcoxon"
> * )
>   ArchR logging to : ArchRLogs/ArchR-getMarkerFeatures-99196ed40b42-Date-2023-10-08_Time-23-57-28.log
>   If there is an issue, please report to github with logFile!
>   2023-10-08 23:57:28 : Matching Known Biases, 0.005 mins elapsed.
>   Error in cor(estbgdP, obsbgdP) : incompatible dimensions
>   In addition: Warning messages:
>   1: In rbind(estbgd, obsbgd) :
>   number of columns of result is not a multiple of vector length (arg 1)
>   2: In rbind(estbgdP, obsbgdP) :
>   number of columns of result is not a multiple of vector length (arg 1)
>   any suggestions??

One possible reason is that there are too few cells in some groups. After filtering the group less than 20 cells, it works.
