### ISSUE TITLE
How to get Seurat object after clustering?

### ISSUE THREAD

**Issue by haowenz** [GreenleafLab/ArchR#241]
Hi,

I am new to R and ArchR. Could you tell me how to get the Seurat object after I run "addClusters()"?

Thanks,
Haowen

**Comment by jgranja24** [comment]
Sorry for the delay - What do you mean by Seurat object? addClusters uses the reducedDims and creates an empty Seurat Object and then runs FindClusters from Seurat. If you want the reducedDims you can try `getReducedDims`. Maybe I am misunderstanding, but am happy to help!
