### ISSUE TITLE
createArrowFiles stuck

### ISSUE THREAD

**Issue by asmagen** [GreenleafLab/ArchR#250]
Running the official ArchR [tutorial](https://www.archrproject.com/bookdown/creating-arrow-files.html) with the example data keeps getting stuck at createArrowFiles at "Batch Execution w/ safelapply!" after a few minutes and after some arrow files appear to be generated.
```
> ArrowFiles <- createArrowFiles(
+   inputFiles = inputFiles,
+   sampleNames = names(inputFiles),
+   filterTSS = 4,
+   filterFrags = 1000, 
+   addTileMat = TRUE,
+   addGeneScoreMat = TRUE
+ )
Using GeneAnnotation set by addArchRGenome(Hg19)!
Using GeneAnnotation set by addArchRGenome(Hg19)!
ArchR logging to : ArchRLogs/ArchR-createArrows-f2c513b20076-Date-2020-07-19_Time-17-57-08.log
If there is an issue, please report to github with logFile!
2020-07-19 17:57:08 : Batch Execution w/ safelapply!, 0 mins elapsed.
```
The QC plot scATAC_BMMC_R1-Fragment_Size_Distribution is being generated successfully but scATAC_BMMC_R1-TSS_by_Unique_Frags doesn't, so it's something between them.
I've let it run for at least 5 hours without the status changing after it gets to the last 'Plotting TSS Enrichment Scores', then I restarted the process but it didn't work (but then I didn't wait for that long).

I've set the arrow file names manually to see if the next steps can work but loading the files appear to fail:
```
> ArrowFiles = c("scATAC_BMMC_R1.arrow","scATAC_CD34_BMMC_R1.arrow","scATAC_PBMC_R1.arrow")
> ArrowFiles
[1] "scATAC_BMMC_R1.arrow"      "scATAC_CD34_BMMC_R1.arrow" "scATAC_PBMC_R1.arrow"     
> projHeme1 <- ArchRProject(
+   ArrowFiles = ArrowFiles, 
+   outputDirectory = "HemeTutorial",
+   copyArrows = TRUE #This is recommened so that if you modify the Arrow files you have an original copy for later usage.
+ )
Using GeneAnnotation set by addArchRGenome(Hg19)!
Using GeneAnnotation set by addArchRGenome(Hg19)!
Validating Arrows...
Getting SampleNames...

Copying ArrowFiles to Ouptut Directory! If you want to save disk space set copyArrows = FALSE
1 2 3 
Getting Cell Metadata...
Error in .safelapply(seq_along(ArrowFiles), function(x) { : 
Error Found Iteration 1 : 
	[1] "Error in h5ls(ArrowFile) : HDF5. Object header. Can't open object.\n"
	<simpleError in h5ls(ArrowFile): HDF5. Object header. Can't open object.>
Error Found Iteration 2 : 
	[1] "Error in h5ls(ArrowFile) : HDF5. Object header. Can't open object.\n"
	<simpleError in h5ls(ArrowFile): HDF5. Object header. Can't open object.>
Error Found Iteration 3 : 
	[1] "Error in h5ls(ArrowFile) : HDF5. Object header. Can't open object.\n"
	<simpleError in h5ls(ArrowFile): HDF5. Object header. Can't open object.>
In addition: Warning message:
In mclapply(..., mc.cores = threads, mc.preschedule = preschedule) :
  3 function calls resulted in an error
```

@rcorces @jgranja24 @archrdevs How can I resolve that?

Thank you!

[ArchR-createArrows-f2c513b20076-Date-2020-07-19_Time-17-57-08.log](https://github.com/GreenleafLab/ArchR/files/4944756/ArchR-createArrows-f2c513b20076-Date-2020-07-19_Time-17-57-08.log)
[ArchR-createArrows-f2c579a80bef-Date-2020-07-19_Time-08-41-57.log](https://github.com/GreenleafLab/ArchR/files/4944757/ArchR-createArrows-f2c579a80bef-Date-2020-07-19_Time-08-41-57.log)

**Comment by rcorces** [comment]
Sorry for the delay in our response. @asmagen - have you fixed this issue? Have you tried setting threads = 1?

**Comment by jgranja24** [comment]
Hi @asmagen, I am closing this issue. If you have additional problems please open a fresh issue! Happy analysis!
