### ISSUE TITLE
Error in getMarkerFeatures

### ISSUE THREAD

**Issue by synlee** [GreenleafLab/ArchR#251]
Hi, 

I've got this error while running getMarkerFeatures using PeakMatrix. This error especially occurs after subsetting ArchR object.
Do you have any ideas why I am getting this error? 
Error in .safelapply(seq_along(matchObj[[1]]), function(x) { : 
Error Found Iteration 1 : 
	[1] "Error in intI(j, n = x@Dim[2], dn[[2]], give.dn = FALSE) : \n  invalid character indexing\n"
	<simpleError in intI(j, n = x@Dim[2], dn[[2]], give.dn = FALSE): invalid character indexing>
Error Found Iteration 2 : 
	[1] "Error in intI(j, n = x@Dim[2], dn[[2]], give.dn = FALSE) : \n  invalid character indexing\n"
	<simpleError in intI(j, n = x@Dim[2], dn[[2]], give.dn = FALSE): invalid character indexing>
Error Found Iteration 3 : 
	[1] "Error in intI(j, n = x@Dim[2], dn[[2]], give.dn = FALSE) : \n  invalid character indexing\n"
	<simpleError in intI(j, n = x@Dim[2], dn[[2]], give.dn = FALSE): invalid character indexing>
Error Found Iteration 4 : 
	[1] "Error in intI(j, n = x@Dim[2], dn[[2]], give.dn = FALSE) : \n  invalid character indexing\n"
	<simpleError in intI(j, n = x@Dim[2], dn[[2]], give.dn = FALSE): invalid character indexing>
Error Found Iteration 5 : 
	[1] "Error in intI(j, n = x@Dim[2], dn[[2]], give.dn = FALSE) : \n  invalid chara
In addition: Warning message:
In mclapply(..., mc.cores = threads, mc.preschedule = preschedule) :
  13 function calls resulted in an error

Thanks for your help in advance!

**Comment by SunKeYong** [comment]
I've got the same error

**Comment by jgranja24** [comment]
Hi @raphaela2018 and @SunKeYong,

Can you try this in the new release branch. Substantial error handling has been done to this function.

`devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.0", repos = BiocManager::repositories())
`
Thanks!!

Jeff

**Comment by raphaela2018** [comment]
Hi Jeff,

I tried the new release branch and still got the same error with "getMarkerFeatures". Any other suggestions? 

Thanks for your help!

**Comment by rcorces** [comment]
can you upload the new log?

**Comment by raphaela2018** [comment]
Yes here is the new log. 

[ArchR-getMarkerFeatures-71f61812a8f9-Date-2020-11-12_Time-21-46-01.log](https://github.com/GreenleafLab/ArchR/files/5538255/ArchR-getMarkerFeatures-71f61812a8f9-Date-2020-11-12_Time-21-46-01.log)

**Comment by markphillippebworth** [comment]
Hey, I've found the same issue, and it depends on the groups use. I have one comparison work, and then others not work at all.

ArchR logging to : ArchRLogs/ArchR-getMarkerFeatures-c733c1478e9-Date-2021-01-04_Time-05-21-58.log
If there is an issue, please report to github with logFile!
2021-01-04 05:21:58 : Matching Known Biases, 0.001 mins elapsed.
2021-01-04 05:22:03 : Computing Pairwise Tests (1 of 1), 0.083 mins elapsed.
Error in intI(j, n = x@Dim[2], dn[[2]], give.dn = FALSE) : 
  invalid character indexing

Same dataset, same groups (just different useGroups and bgdGroups).

ArchR logging to : ArchRLogs/ArchR-getMarkerFeatures-c733ad6d8bf-Date-2021-01-04_Time-05-28-14.log
If there is an issue, please report to github with logFile!
2021-01-04 05:28:14 : Matching Known Biases, 0.001 mins elapsed.
2021-01-04 05:28:19 : Computing Pairwise Tests (1 of 1), 0.083 mins elapsed.
###########
2021-01-04 05:29:13 : Completed Pairwise Tests, 0.98 mins elapsed.
###########
ArchR logging successful to : ArchRLogs/ArchR-getMarkerFeatures-c733ad6d8bf-Date-2021-01-04_Time-05-28-14.log

**Comment by rcorces** [comment]
@markphillippebworth - Can you:

1) Confirm you are on the latest ArchR Version
2) Upload the log files for the failed and successful run
3) Show us what your different `useGroups` look like (using `unique()` for ex)

**Comment by markphillippebworth** [comment]
I'm running ArchR 1.0.1. 

Table of cells for each group:

                 female_Old_Healthy_NK    female_Old_Healthy_NK Proliferating 
                                 12038                                    279 
      female_Old_Healthy_NK_CD56bright                 female_Old_Infected_NK 
                                  1479                                   9350 
  female_Old_Infected_NK Proliferating      female_Old_Infected_NK_CD56bright 
                                   188                                    984 
               female_Young_Healthy_NK  female_Young_Healthy_NK Proliferating 
                                  6117                                     84 
    female_Young_Healthy_NK_CD56bright               female_Young_Infected_NK 
                                   669                                   7214 
female_Young_Infected_NK Proliferating    female_Young_Infected_NK_CD56bright 
                                   194                                    802 
                   male_Old_Healthy_NK      male_Old_Healthy_NK Proliferating 
                                 19805                                    290 
        male_Old_Healthy_NK_CD56bright                   male_Old_Infected_NK 
                                  1177                                  11921 
    male_Old_Infected_NK Proliferating        male_Old_Infected_NK_CD56bright 
                                   241                                    737 
                 male_Young_Healthy_NK    male_Young_Healthy_NK Proliferating 
                                  8802                                    168 
      male_Young_Healthy_NK_CD56bright                 male_Young_Infected_NK 
                                   564                                  10478 
  male_Young_Infected_NK Proliferating      male_Young_Infected_NK_CD56bright 
                                   243                                    614 

 male_Old_Healthy_NK vs male_old_Infected_NK works.
Others do not. 

SessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 10 (buster)
Matrix products: default
BLAS:   /usr/local/lib/R/lib/libRblas.so

**Comment by rcorces** [comment]
I'm not sure what to make of this. Maybe @jgranja24 has insight.

**Comment by markphillippebworth** [comment]
I think that makes sense. I was able to get around the issue by regenerating the ArchR project from scratch, so whatever mismatch there was disappeared.

**Comment by jgranja24** [comment]
Sorry, Im not following this error. These are using character cell names which are derived from the project. Maybe im being silly but there shouldnt be any reason cell names should be present in the ArchRProject that arent within the sub arrow files?

However, i added the following sanity check in the function now. So maybe if someone else has this issue itll be more obvious to me whats happening internally.

```
  if(!all(cellNames %in% colnames(mat))){
    .logThis(cellNames, "cellNames supplied", logFile = logFile)
    .logThis(colnames(mat), "cellNames from matrix", logFile = logFile)
    stop("Error not all cellNames found in partialMatrix")
  }
```

Best

Jeff

**Comment by rargelaguet** [comment]
For example, n my case, I was testing differential accessibility using three different QC thresholds. As far as I understood, the "standard" workflow would be to create and save three independent ArchR project, right? For a large data set, this takes huge amounts of disk. It is more convenient to have a single project where I can dynamically change the cells being used for the downstream analysis. I do this by subsetting the ArchR project with the cells that I need for that specific analysis. However, the function above retrieves all cells from the ArrowFiles, instead of the ones I am using in the subsetted ArchR project. Does this make sense or I am being naive here?
