### ISSUE TITLE
plotFragmentSizes and plotTSSEnrichment groupBy option

### ISSUE THREAD

**Issue by mitsiask** [GreenleafLab/ArchR#253]
Greetings,
fantastic package and very thorough documentation.

At the moment, as I get it, plotFragmentSizes function uses the "Sample" column in order to split the cells to groups, and finally plot the fragment sizes distribution as shown in the section 3.4 in the documentation.

It would be nice if you could add the "groupBy" option in the plotFragmentSizes function, as it would be easier to plot the fragment sizes per cluster, or condition, or any other column is available in the object.
The same could be applicable in the plotTSSEnrichment function.

Thanks

**Comment by jgranja24** [comment]
I agree and I will try to improve these in the near future

best

Jeff

**Comment by jgranja24** [comment]
Hi @mitsiask,

I now added this feature to plotFragmentSizes and plotTSSEnrichment --

```
#New Release Branch
devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.0", repos = BiocManager::repositories())

library(ArchR)
proj <- getTestProject()

p <- plotTSSEnrichment(ArchRProj = proj, groupBy = "Clusters")
plotPDF(p)

p <- plotFragmentSizes(ArchRProj = proj, groupBy = "Clusters")
plotPDF(p)
```

<img width="824" alt="Screen Shot 2020-10-28 at 3 36 27 PM" src="https://user-images.githubusercontent.com/25017655/97504040-63017b00-1933-11eb-855b-bf5abe00d38b.png">


<img width="761" alt="Screen Shot 2020-10-28 at 3 36 24 PM" src="https://user-images.githubusercontent.com/25017655/97504049-672d9880-1933-11eb-97a9-df75a525bcd3.png">

**Comment by jgranja24** [comment]
Closing this issue, feel free to open more issues.
