### ISSUE TITLE
Order peak set the same way between `getPeakSet` and `getMarkerFeatures`

### ISSUE THREAD

**Issue by concatenize** [GreenleafLab/ArchR#254]
My PI recently asked to what degree we have differentially expressed peaks that are distal rather than at or near the gene body. To answer this, I needed to grab the TSS distance and peak type from the `getPeakSet` output and merge it with the cluster marker peaks from `getMarkerFeatures`. Putting them in the same order is one easy way to do this, and seems generally useful to protect any user who assumes the order is preserved. I'm not sure where in the code it fits best, but it is easy to do as follows:

```
chromosome_order = getPeakSet(e11_e12) %>% seqnames %>% levels
new_order = with( rowData(marker_peaks), order(seqnames %>% as.character %>% factor(levels = chromosome_order), idx) )
marker_peaks = marker_peaks[new_order, ]
```

**Comment by jgranja24** [comment]
I normally do something like this - 

```
peakSet <- getPeakSet(e11_e12)
names(peakSet) <- paste(seqnames(peakSet), start(peakSet), end(peakSet), sep="_")

rownames(marker_peaks) <- paste(rowData(marker_peaks)$seqnames, rowData(marker_peaks)$start, rowData(marker_peaks)$end, sep="_")

marker_peaks <- marker_peaks[names(peakSet),]

```

Hope that helps 

Jeff

**Comment by concatenize** [comment]
Yes, that works! Thank you!
