### ISSUE TITLE
How to download feature matrices (e.g. MotifMatrix) from ArchR project

### ISSUE THREAD

**Issue by seishin0125** [GreenleafLab/ArchR#255]
I'm thinking of drawing violin plots of motif deviations for each cluster calculated in Chapter13.1.

In order to make such kinds of plots, I tried to extract feature matrices like MotifMatrix from ArchR Project, however, I couldn't locate where such kind of matrices are stored.

Could you teach me how to download feature matrices from ArchR Project?

**Comment by jgranja24** [comment]
Please see`getMatrixFromProject(useMatrix="MotifMatrix")` alternatively plotGroups can help you with this as suggested.

Best

Jeff

**Comment by seishin0125** [comment]
I could download the matrices. Thank you so much for your kind help!
