### ISSUE TITLE
Read in fragment using scanTabix then error creatingArrowFiles

### ISSUE THREAD

**Issue by jasonsaunderswilliams** [GreenleafLab/ArchR#256]
Hi,

I read in my fragments.tsv.gz file using scanTabix:

```
CS001Arch <- scanTabix("/data/Jason/ATAC-Seq/CELLRANGER_scATAC/1_4303Swansea_CS001/ArchR/fragments.tsv.gz")
CS001Arch
```

Then I use the following code to create an arrow file:

```
ArrowFiles <- createArrowFiles(
  inputFiles = CS001Arch,
  sampleNames = CS001,
  filterTSS = 4, #Dont set this too high because you can always increase later
  filterFrags = 1000, 
  addTileMat = TRUE,
  addGeneScoreMat = TRUE
)

```

I get the following error:

```
Error in .validInput(input = inputFiles, name = "inputFiles", valid = c("character")) : Input value for 'inputFiles' is not a character, (inputFiles = list) please supply valid input!
```

Am I reading in my fragment file incorrectly? I assumed it was scanTabix like scanBam for BAMs?

Best wishes,

Jason

**Comment by rcorces** [comment]
This is not how fragment files are handled in ArchR. The input to `createArrowFiles()` is the path to the fragment file. This is detailed in the manual. https://www.archrproject.com/bookdown/creating-arrow-files.html

I'd recommend going through the tutorial before trying things on your own data.

**Comment by jasonsaunderswilliams** [comment]
Hi rcorces. I have followed the tutorial. I put all my fragment files and indices in the same folder. 
I then use 
```
inputFiles <- "pathtofragmentsdirectory"
```

Then I use 

```
ArrowFiles <- createArrowFiles(
  inputFiles = inputFiles,
  sampleNames = names(inputFiles),
  filterTSS = 4, #Dont set this too high because you can always increase later
  filterFrags = 1000, 
  addTileMat = TRUE,
  addGeneScoreMat = TRUE
)
```
But I get this error:

```Error in .validInput(input = sampleNames, name = "sampleNames", valid = c("character")) : Input value for 'sampleNames' is not a character, (sampleNames = NULL) please supply valid input!```

I'm not clear on how to read in fragment files to create an arrow file. The tutorial is just doing this from what I can see?

Sorry if I am missing something obvious.

Best,

Jason

**Comment by rcorces** [comment]
This is what `inputFiles` is supposed to look like (as per the tutorial)
![image](https://user-images.githubusercontent.com/10343046/88813798-37bd9300-d16e-11ea-8964-ad1551bbc860.png)

It is not a path to the directory but rather a named vector where the names are your desired sample names and the values are the path to each fragment file.

**Comment by jasonsaunderswilliams** [comment]
I see.

Something like this:

```inputFiles <- c('CS001' = "/data/Jason/ATAC-Seq/CELLRANGER_scATAC/1_4303Swansea_CS001/ArchR/fragments.tsv.gz", '10XN' = "/data/Jason/ATAC-Seq/CELLRANGER_scATAC/1_4303Swansea_CS001/ArchR/atac_pbmc_5k_nextgem_fragments.tsv.gz")
```

**Comment by lyuguol** [comment]
> Hi,
> 
> I read in my fragments.tsv.gz file using scanTabix:
> 
> ```
> CS001Arch <- scanTabix("/data/Jason/ATAC-Seq/CELLRANGER_scATAC/1_4303Swansea_CS001/ArchR/fragments.tsv.gz")
> CS001Arch
> ```
> 
> Then I use the following code to create an arrow file:
> 
> ```
> ArrowFiles <- createArrowFiles(
>   inputFiles = CS001Arch,
>   sampleNames = CS001,
>   filterTSS = 4, #Dont set this too high because you can always increase later
>   filterFrags = 1000, 
>   addTileMat = TRUE,
>   addGeneScoreMat = TRUE
> )
> ```
> 
> I get the following error:
> 
> ```
> Error in .validInput(input = inputFiles, name = "inputFiles", valid = c("character")) : Input value for 'inputFiles' is not a character, (inputFiles = list) please supply valid input!
> ```
> 
> Am I reading in my fragment file incorrectly? I assumed it was scanTabix like scanBam for BAMs?
> 
> Best wishes,
> 
> Jason


@jasonsaunderswilliams 

Hello Jason,

I ran into the same error as yours.

Did you manage to read in your 'inputFiles'?

My files are stored in my MacOS as this: "/Users/High-throughput NGS/Single cell ATAC-seq/data/fragments.tsv.gz".

I read in the data like this.....
> inputFiles <- c("/Users/High-throughput NGS/Single cell ATAC-seq/data/fragments.tsv.gz")
> ArrowFiles <- createArrowFiles(inputFiles = inputFiles, sampleNames = names(inputFiles), filterFrags = 1000, filterTSS = 4, addTileMat = TRUE, addGeneScoreMat = TRUE)

Error in .validInput(input = sampleNames, name = "sampleNames", valid = c("character")) : 
  Input value for 'sampleNames' is not a character, (sampleNames = NULL) please supply valid input!

Could you show me how to read in it as 'inputFiles', and then use this 'inputFiles' to createArrowFiles?

Many thanks in advance!
All the best,
Guoliang

**Comment by rcorces** [comment]
@lyuguol - as the error points to, your `inputFiles` variable has no names attribute. `names(inputFiles)` is empty.

**Comment by lyuguol** [comment]
> @lyuguol - as the error points to, your `inputFiles` variable has no names attribute. `names(inputFiles)` is empty.

@rcorces Many thanks for the quick reply. Could you show me how to read in my data (10XGenomics scATAC-seq)? Thank you.

**Comment by lyuguol** [comment]
> @lyuguol - as the error points to, your `inputFiles` variable has no names attribute. `names(inputFiles)` is empty.

@rcorces Finally, by modifying this code:
>inputFiles <- c('CS001' = "/data/Jason/ATAC-Seq/CELLRANGER_scATAC/1_4303Swansea_CS001/ArchR/fragments.tsv.gz", '10XN' = "/data/Jason/ATAC-Seq/CELLRANGER_scATAC/1_4303Swansea_CS001/ArchR/atac_pbmc_5k_nextgem_fragments.tsv.gz")

into 

>inputFiles <- c('scATAC' = "/Users/High-throughput NGS/Single cell ATAC-seq/data/fragments.tsv.gz")

I managed to read in the data and create the arrow files.

Sorry for the inconvenience.

Best,

Guoliang

**Comment by KuroToaster** [comment]
@lyuguol 
Hello Guoliang, 
I know that it has been a while. But how do you input 2 files into a single file and make two of them to be the input to create arrow files? 

Thank you so much in advance. 

Best,

Hailin Liang
