### ISSUE TITLE
Barcodes of doublets

### ISSUE THREAD

**Issue by aysouid** [GreenleafLab/ArchR#258]
Can I extract the barcodes of the doublets that are filtered via `filterDoublets(ArchRProj = proj)`? Also, same question but for the barcodes that were filtered in the `createArrowFiles` step. 

Thanks for the great package!

**Comment by rcorces** [comment]
Sorry for the delay in our response.
This is possible, in a way. When you create your Arrow files, the default is to throw out information corresponding to cells that dont pass QC. But if you set the parameter `removeFilteredCells` to `FALSE`, it will keep all of the cells and the column `PassQC` in `cellColData` should reflect which cells passed the QC filters that you set in `createArrowFiles`

To get the barcodes of the cells filtered by `filterDoublets()`, you can just do this before actually running `filterDoublets()` and look for cells that meet the criteria that you will use to filter (ie. the values for the `cutEnrich` and `cutScore` parameters)
