### ISSUE TITLE
Seurat dependency failure

### ISSUE THREAD

**Issue by asmagen** [GreenleafLab/ArchR#259]
Is there a way to circumvent the dependency on Seurat clustering? It's suffering from many reported issues causing R to crash, and I was unable to resolve that yet after trying all the suggestions online.

Thanks

**Comment by rcorces** [comment]
You can also cluster with `scran`. See final section here:
https://www.archrproject.com/bookdown/clustering-using-seurats-findclusters-function.html

Re-open if this doesnt answer your question.

**Comment by asmagen** [comment]
But what about addIterativeLSI Seurat clustering dependency?
```
projHeme1 <- addIterativeLSI(
  ArchRProj = projHeme1,
  useMatrix = "TileMatrix", 
  name = "IterativeLSI", 
  iterations = 2, 
  clusterParams = list( #See Seurat::FindClusters
    resolution = c(0.2), 
    sampleCells = 10000, 
    n.start = 10
  ), 
  varFeatures = 25000, 
  dimsToUse = 1:30
)
```
