### ISSUE TITLE
Seurat dependency failure in addIterativeLSI

### ISSUE THREAD

**Issue by asmagen** [GreenleafLab/ArchR#261]
I got an answer about using Scran clustering instead of Seurat in addClusters, but it fails with the following error. Can you advise please? And what about addIterativeLSI without using Seurat?

```
> projHeme1 <- addClusters(
+   input = projHeme1,
+   reducedDims = "IterativeLSI",
+   method = "scran",
+   name = "ScranClusters",
+   k = 15
+ )
ArchR logging to : ArchRLogs/ArchR-addClusters-ef9664ca176d-Date-2020-07-24_Time-08-51-57.log
If there is an issue, please report to github with logFile!
Error in addClusters(input = projHeme1, reducedDims = "IterativeLSI",  : 
  Error reducedDims not available!
```
@rcorces
[ArchR-createArrows-f2c56d6d6f73-Date-2020-07-19_Time-18-15-58.log](https://github.com/GreenleafLab/ArchR/files/4971990/ArchR-createArrows-f2c56d6d6f73-Date-2020-07-19_Time-18-15-58.log)

**Comment by rcorces** [comment]
Sorry for the delay in our response.
Currently, I believe Iterative LSI in ArchR is hardcoded to use Seurat. The error you are getting is because you are trying to pass a reducedDims object that doesnt exist.

**Comment by jgranja24** [comment]
You can pass the same params for `addClusters` to addIterativeLSI.

See ---

```
#New Release Branch
devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.0", repos = BiocManager::repositories())

library(ArchR)
proj <- getTestProject()
proj <- addIterativeLSI(
	ArchRProj = proj,
	name = "IterativeLSI_Scran",
	clusterParams = list(
		method = "scran",
		k = 15
	),
	varFeatures = 100000,
	force = TRUE
)
proj <- addClusters(
  input = proj,
  reducedDims = "IterativeLSI_Scran",
  method = "scran",
  name = "ScranClusters",
  k = 15,
  force = TRUE
)
proj <- addClusters(
  input = proj,
  reducedDims = "IterativeLSI_Scran",
  method = "Seurat",
  name = "SeuratClusters",
  k = 15,
  force = TRUE
)
proj <- addUMAP(proj, reducedDims = "IterativeLSI_Scran", force = TRUE)
p1 <- plotEmbedding(proj, name = "ScranClusters")
p2 <- plotEmbedding(proj, name = "SeuratClusters")
plotPDF(ggAlignPlots(p1,p2,type="h",draw=FALSE))
```

<img width="899" alt="Screen Shot 2020-10-26 at 7 21 12 PM" src="https://user-images.githubusercontent.com/25017655/97249134-7c35ea80-17c0-11eb-8e74-ae638f1e0735.png">

**Comment by jgranja24** [comment]
Closing this issue, feel free to open new issues!
