### ISSUE TITLE
Can i export bigwig file for each cluster?

### ISSUE THREAD

**Issue by JohnGenome** [GreenleafLab/ArchR#262]
Hi, the package is very powerful and helps me a lot. But i met a problem that i want to upload my chromatin accessibility tracks to UCSC Genome Browser, while i don't know how to get bigwig file on the basis of ArchR analysis.
I wonder if there is a more convenient way than extracting reads from the very beginning fastq file.
Thanks!

**Comment by JohnGenome** [comment]
'_ArchR also enables direct export of group normalized bigwig files using “export.bw” from Rtracklayer that can be directly used in conventional genome browsers._'
Plus, is there any function for this aim from pre-printed paper?

**Comment by rcorces** [comment]
Sorry for the delay in our response. This is a duplicate issue of #54 
The function you are looking for is `getGroupBW()`
