### ISSUE TITLE
Error in irlba with tutorial data

### ISSUE THREAD

**Issue by gregszetoAI** [GreenleafLab/ArchR#263]
Hello, 

Trying to run the tutorial dataset, but hitting this issue for the doublet step: <simpleError in irlba::irlba(mat, nDimensions, nDimensions): max(nu, nv) must be strictly less than min(nrow(A), ncol(A))>

Any help would be appreciated. See attached log file.

[ArchR-addDoubletScores-5857e9b864a-Date-2020-07-27_Time-19-25-46.log](https://github.com/GreenleafLab/ArchR/files/4984066/ArchR-addDoubletScores-5857e9b864a-Date-2020-07-27_Time-19-25-46.log)

**Comment by jgranja24** [comment]
From your log file it says you have a total of 10 cells for this sample. Can you provide the code you have ran up until this point and additionally  the output of the following --

```
proj <- ArchRProject(ArrowFiles)
table(proj$Sample)
median(proj$TSSEnrichment)
median(proj$nFrags)
```

<img width="838" alt="Screen Shot 2020-10-26 at 3 41 21 PM" src="https://user-images.githubusercontent.com/25017655/97236160-b47a0080-17a1-11eb-88be-3e031c0c83a3.png">


Thanks

Jeff

**Comment by gregszetoAI** [comment]
Sorry I worked with archr a lot more (with real data!) and love it! I am no longer concerned with this issue.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
