### ISSUE TITLE
could not find function "createGeneAnnotation"

### ISSUE THREAD

**Issue by kzxkzx** [GreenleafLab/ArchR#264]
Sorry to bother, I want to create a custom ArchRGenome, I get the erro "could not find function "createGeneAnnotation" when I run commond "geneAnnotation <-createGeneAnnotation(TxDb=TxDb.Drerio.UCSC.danRer11.refGene,OrgDb = org.Dr.eg.db)",any suggestion?The version of bioconductor is 3.7

**Comment by rcorces** [comment]
This sounds like you do not have ArchR properly installed and loaded.
