### ISSUE TITLE
peak to gene

### ISSUE THREAD

**Issue by rojinsafavi** [GreenleafLab/ArchR#265]
Is it possible to output the peak -> gene connection? I'd like to know what peaks have contributed to genesecore matrix for each gene.

**Comment by rcorces** [comment]
Sorry for the delay in responding. We have a lot on our plates at the moment.
I'm not sure exactly what you mean. You can, of course, use `addPeak2GeneLinks()` to identify peak-to-gene links. However, these are not used for creating a genescore matrix. Gene scores are created from the tile matrix.

So perhaps what you want is the contribution of each tile to the gene score of a specific gene? If so, that is not currently supported. This seems like a reasonable request, though in practice this is not going to identify interesting "peaks". Using the default gene score functions, most of the gene score signal comes from the promoter and gene body or very proximal peaks, all of which you could assess by eye using tracks.

I'm going to close this for now but feel free to re-open if you think that this hasn't answered your question.
