### ISSUE TITLE
createArrowFiles ignores one fragment file? Empty QC folder

### ISSUE THREAD

**Issue by jasonsaunderswilliams** [GreenleafLab/ArchR#266]
Hi,

I am successfully creating ArrowFiles using the following chunks:

```

inputFiles <- c('CS001' = "/data/Jason/ATAC-Seq/CELLRANGER_scATAC/1_4303Swansea_CS001/ArchR/fragments.tsv.gz",
                '10XN' = "/data/Jason/ATAC-Seq/CELLRANGER_scATAC/1_4303Swansea_CS001/ArchR/atac_pbmc_5k_nextgem_fragments.tsv.gz")
inputFiles

```

```
ArrowFiles <- createArrowFiles(
  inputFiles = inputFiles,
  sampleNames = names(inputFiles),
  filterTSS = 4, #Dont set this too high because you can always increase later
  filterFrags = 1000, 
  addTileMat = TRUE,
  addGeneScoreMat = TRUE,
  QCDir = "/data/Jason/ATAC-Seq/CELLRANGER_scATAC/1_4303Swansea_CS001/ArchR/"
)

```

The fragment distribution for `10XN` is present in the per sample QC folder. The `CS001` QC folder is empty.

What is even more bizarre is the fact that only one arrow file is created

```
ArrowFiles

[1] "CS001.arrow"
```

When I continue to create an ArchR Project:

```
projCS001 <- ArchRProject(
  ArrowFiles = ArrowFiles, 
  outputDirectory = "/data/Jason/ATAC-Seq/CELLRANGER_scATAC/1_4303Swansea_CS001/ArchR/",
  copyArrows = TRUE #This is recommened so that if you modify the Arrow files you have an original copy for later usage.
)
```

```> projCS001

           ___      .______        ______  __    __  .______      
          /   \     |   _  \      /      ||  |  |  | |   _  \     
         /  ^  \    |  |_)  |    |  ,----'|  |__|  | |  |_)  |    
        /  /_\  \   |      /     |  |     |   __   | |      /     
       /  _____  \  |  |\  \\___ |  `----.|  |  |  | |  |\  \\___.
      /__/     \__\ | _| `._____| \______||__|  |__| | _| `._____|
    
class: ArchRProject 
outputDirectory: /data/Jason/ATAC-Seq/CELLRANGER_scATAC/1_4303Swansea_CS001/ArchR 
samples(1): CS001
sampleColData names(1): ArrowFiles
cellColData names(15): Sample TSSEnrichment ... DoubletEnrichment BlacklistRatio
numberOfCells(1): 1923
medianTSS(1): 10.413
medianFrags(1): 4105
> 

```

There is only one sample in my project as expected, as there is only one arrow file. 

I processed both files from bams using sinto:

https://timoast.github.io/sinto/scatac.html

When I inspected the resulting fragment files they look fine:

```
(base) jason@RBGO-Server2:/data/Jason/ATAC-Seq/CELLRANGER_scATAC/1_4303Swansea_CS001$ gzip -dc /data/Jason/ATAC-Seq/CELLRANGER_scATAC/1_4303Swansea_CS001/ArchR/postsorted_fragments.sort.bed.gz | head
chr1	10096	10279	TCAGTCCGTCATCAAC-1	1
chr1	10156	10186	GAGGATGGTAGCGGTA-1	1
chr1	10157	10185	ACTGCGGCAGCAACAG-1	1
chr1	13960	13991	TCTAGTTCAAAGGAAG-1	1
chr1	16221	16248	TAGGAGGGTCCTTCAC-1	2
chr1	17113	17500	CATTGGACATAGAATG-1	6
chr1	17113	17501	GCTGAGCCATCGAGTT-1	2
chr1	17297	17502	CTTCTAAGTGGCCTCA-1	2
chr1	17369	17508	AAAGGATCAGTTGGAG-1	3
chr1	17483	17547	CAGCCTTAGTGAGCTG-1	1
(base) jason@RBGO-Server2:/data/Jason/ATAC-Seq/CELLRANGER_scATAC/1_4303Swansea_CS001$ gzip -dc /data/Jason/ATAC-Seq/CELLRANGER_scATAC/1_4303Swansea_CS001/ArchR/pbmc_5k_possorted_bam.sort.bed.gz | head
chr1	10066	10198	CTCTCAGTCCGGGCAT-1	2
chr1	10071	10279	CAGGGCTTCTTTCGAT-1	1
chr1	10073	10186	GCCTAGGCAGTGCTCG-1	1
chr1	10073	10333	ACTAACGCAGATGGCA-1	1
chr1	10085	10284	ATTTGTCCAATGCCAT-1	1
chr1	10090	10536	CCGTACTTCTGGCCAG-1	1
chr1	10096	10315	TAACTTCGTTTCGATG-1	1
chr1	10096	10543	TGAGCCGGTTAGGCTT-1	1
chr1	10097	10285	CCTGCTAAGTCCAGAG-1	1
chr1	10097	10346	CACCTTGCACACATGT-1	1

```

Best wishes,

Jason

**Comment by smorabit** [comment]
Hi Jason, I had the same problem as you with one of my fragment files getting ignored, but I was able to resolve it by running ArchR's `reformatFragmentFiles` function. 

I ran it like this
`reformatFragmentFiles(sample_file)`
where `sample_file` is the path to the gzipped fragments file. This function makes a new fragments file in the same directory called  `fragments-Reformat.tsv.gz`.

While I was satisfied that this worked for me I had no idea why it worked... All of my samples were processed the same way (using cellranger atac), so I don't know why only one of them needed to be reformatted. Additionally, SnapATAC had no problems with this fragments file. Maybe the maintainers could shed some light?

**Comment by rcorces** [comment]
We haven't encountered this issue with our own data and most users are hesitant to share sample data files. If you can provide an example file, we might be able to figure this out. Even better if it is small in size.

**Comment by smorabit** [comment]
Yeah I think that unfortunately I am hesitant to send the fragments file since it is yet to be published data.

**Comment by rcorces** [comment]
Makes sense. This is already on my to-do list to add to the documentation. I'm closing this for now. Anyone having similar issues and willing to pass along fragment files can feel free to reopen.
Otherwise, users having this problem should run the `reformatFragmentFiles()` function.
