### ISSUE TITLE
Methods for objective QC thresholding? 

### ISSUE THREAD

**Issue by RegnerM2015** [GreenleafLab/ArchR#268]
Hi @jgranja24,

**Describe the problem that your feature request would address.**
The density plots of TSS enrichment versus log10(fragments) are very visually appealing and helpful for QC (identifying cellular barcodes from non-cellular barcodes). However, this visual inspection of the plot is subjective and it would be more robust to have an objective strategy for determining the appropriate TSS enrichment and log10(fragments) cutoffs. 

**Describe the solution you'd like**
I know MAD is a common technique for outlier detection, but sometimes there is just not much variability on the low end of the given variable. For example, I have a dataset where the MAD TSS enrichment value is 6.94, but there are no outliers on the low end of this variable:
Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  0.000   1.089   5.891   6.007  10.007  31.825 

**Describe alternatives you've considered**
Would there be any other strategies for outlier detection using these two QC metrics? (TSS enrichment and log10(fragments)

I have also considered a k-means approach using the barcode embeddings in this TSS versus log10(fragment) space. Please see the attached plots. This seemed like a good idea theoretically, but did not work well in practice. 
![TSS_v_Frags](https://user-images.githubusercontent.com/54336249/89108909-a1f26400-d40a-11ea-93a9-9f667859666e.png)
![K_means](https://user-images.githubusercontent.com/54336249/89108910-a3bc2780-d40a-11ea-870f-c34552d37d07.png)

*Note that these plots use all barcodes from the 10x Cell Ranger fragments.tsv.gz file (see the code below):
`ArrowFiles <- createArrowFiles(
  inputFiles = inputFiles,
  sampleNames = "SampleX",
  filterTSS = 0, 
  filterFrags = 0, 
  addTileMat = T,
  addGeneScoreMat = F
)
`

**Additional context**
Please feel free to suggest any other ideas. Thanks in advance!

**Comment by rcorces** [comment]
We have not been able to come up with a robust and sensitive automatic threshold that we feel confident in. Depending on the input material, sequencing depth, etc, these plots can vary widely. We're happy to look at and consider implementations of auto-thresholds but we dont have plans to implement this ourselves.
