### ISSUE TITLE
Error in (function (filename = "Rplot%03d.png", width = 480, height = 480,  :

### ISSUE THREAD

**Issue by liaoshengyou** [GreenleafLab/ArchR#269]
I was run 

> heatmapGS <- plotMarkerHeatmap(seMarker = markersGS, labelMarkers = markerGenes, transpose = TRUE, cutOff = "FDR <= 0.01 & Log2FC >= 1.25", )
> ComplexHeatmap::draw(heatmapGS, heatmap_legend_side = "bot", annotation_legend_side = "bot")

when i want to draw a figure with this heatmapGS object i get a errror log(win10 64 bit) with:

> Error in (function (filename = "Rplot%03d.png", width = 480, height = 480,  : 
>   无法启动png()装置
> 此外: Warning messages:
> 1: In (function (filename = "Rplot%03d.png", width = 480, height = 480,  :
>   无法打开'C:\Users\ADMINI~1\AppData\Local\Temp\RtmpiindKR\.heatmap_body_Column Z-Scores
> 819 features
> GeneScoreMatrix_1_126346b7e29c8.png'文本写入
> 2: In (function (filename = "Rplot%03d.png", width = 480, height = 480,  :
>   opening device failed

I check it and resolve this problem show:
>heatmapGS@name
[1] **"Column Z-Scores\n819 features\nGeneScoreMatrix"**   #  bug in windows,
 
the name in windows has a bug, i chage it with below:
>heatmapGS@name = "n819features_nGeneScoreMatrix"

then i draw this fig and resolve this problem.

Can you fix this name with normal ?

**Comment by rcorces** [comment]
Thanks for reporting. Unfortunately, we dont have the bandwidth to actively support windows at the moment. We will keep this in mind if we are able to do so in the future.
