### ISSUE TITLE
raw coverage on plotBrowserTrack

### ISSUE THREAD

**Issue by Brawni** [GreenleafLab/ArchR#270]
Hi, 

Would it be possible to plot raw coverages in plotBrowserTrack ? Currently the argument normMethod force you to specify a metadata column for normalization.

Thank you!

**Comment by rcorces** [comment]
I agree that it would be nice to have an explicit option for no normalization. In the mean time, you can create a column in `cellColData` and make all the values the same to avoid performing any normalization.

**Comment by Brawni** [comment]
yes that worked, thanks!

**Comment by rcorces** [comment]
@jgranja24 - do you think we should implement a more intuitive option for this? For example, `normMethod = NULL`?

**Comment by jgranja24** [comment]
This is now available in the new release branch `normMethod="None"`

To install -

`devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.0", repos = BiocManager::repositories())
`

I am closing this issue feel free to open any issues you have in the future!

Best

Jeff

**Comment by Brawni** [comment]
Hi Jeff!

There is a typo in the plotBrowserTrack function in the release_1.0 branch at line 1184 is "normMetho" instead of "normMethod".

Thank you!
