### ISSUE TITLE
 Error in .validate_Vector_vertical_slots(x) :  could not find function ".validate_Vector_vertical_slots"

### ISSUE THREAD

**Issue by ldorozco** [GreenleafLab/ArchR#271]
I get an error when running  Motif and Feature Enrichment with ArchR. I am using R version 4. The package S4Vectors is installed, but I still get the error:

proj <- addMotifAnnotations(ArchRProj = proj, motifSet = "cisbp", name = "Motif")
OR
proj <- addMotifAnnotations(ArchRProj = proj, motifSet = "JASPAR2020", name = "Motif")

Error in .validate_Vector_vertical_slots(x) :  could not find function ".validate_Vector_vertical_slots"

[ArchR-addMotifAnnotations-3202776e525-Date-2020-08-04_Time-10-57-14.log](https://github.com/GreenleafLab/ArchR/files/5025301/ArchR-addMotifAnnotations-3202776e525-Date-2020-08-04_Time-10-57-14.log)

**Comment by ldorozco** [comment]
I was able to solve this issue by installing ArchR from Bioconductor 3.11 instead of 3.12. I no longer get the error message in this install.

**Comment by rcorces** [comment]
There are issues with R version 4 that we have not addressed. We do not recommend using version 4 with ArchR at this time.

**Comment by rargelaguet** [comment]
Hello, 
I get the same error. Is archR still not functional with R>=4?

**Comment by Zepeng-Mu** [comment]
This error message seems to come from TFBSTools. I updated to R4.0.3 and it works, but I had the same message using R4.0.0. See [this issue](https://github.com/ge11232002/TFBSTools/issues/26)
