### ISSUE TITLE
plotMarkerHeatmap: nLabel argument not utilized

### ISSUE THREAD

**Issue by rcorces** [GreenleafLab/ArchR#273]
In the `plotMarkerHeatmap()` function, the parameter `nLabel` has no effect. It is not used in the downstream code as far as I can tell.
https://github.com/GreenleafLab/ArchR/blob/ddcaae4a6093685875052219141e5ea41030fc55/R/MarkerFeatures.R#L809

**Comment by jgranja24** [comment]
This is now functional --

```
library(ArchR)
proj <- getTestProject()
seGenes <- getMarkerFeatures(proj, useMatrix="GeneScoreMatrix", groupBy = "Clusters")
plotPDF(plotMarkerHeatmap(seGenes, nLabel = 2))
plotPDF(plotMarkerHeatmap(seGenes, nLabel = 15))
```

<img width="819" alt="Screen Shot 2020-10-26 at 7 10 31 PM" src="https://user-images.githubusercontent.com/25017655/97248467-1a28b580-17bf-11eb-8cc6-c0c3621fff7c.png">

<img width="788" alt="Screen Shot 2020-10-26 at 7 10 36 PM" src="https://user-images.githubusercontent.com/25017655/97248476-201e9680-17bf-11eb-833d-9d62b4ae56d7.png">

**Comment by jgranja24** [comment]
Closing this issue.
