### ISSUE TITLE
Jackstraw methods for determining the optimal number of SVD components

### ISSUE THREAD

**Issue by RegnerM2015** [GreenleafLab/ArchR#274]
Hi @rcorces and @jgranja24 

**Describe the problem that your feature request would address.**

I have a question relating to #120. I would like to try out a JackStraw approach after `addIterativeLSI()`. 

If I were to perform this, would it be more appropriate to not scale the SVD components? For example, I would set scaleDims = FALSE:

`proj.1 <- addIterativeLSI(
  ArchRProj = proj,
  useMatrix = "TileMatrix", 
  scaleDims = FALSE,
  name = "IterativeLSI", 
  iterations = 1, 
  clusterParams = list( #See Seurat::FindClusters
    resolution = c(0.2), 
    sampleCells = 10000, 
    n.start = 10
  ), 
  varFeatures = 25000, 
  dimsToUse = 1:50
)`

Would the same solution work if one were to make a scree/Elbow plot (to show the variance for each SVD component)?

**Comment by jgranja24** [comment]
Sorry for the delay, 

I believe you would need the percent explained from the LSI components and then I would still scale the components
or else you will observe batch effects.

To get the percent explained I think this may help 

[https://stats.stackexchange.com/questions/171539/percentage-of-variation-in-each-column-explained-by-each-svd-mode](https://stats.stackexchange.com/questions/171539/percentage-of-variation-in-each-column-explained-by-each-svd-mode
)
Best

Jeff
