### ISSUE TITLE
Writing FindTransferAnchors output to working directory 

### ISSUE THREAD

**Issue by RegnerM2015** [GreenleafLab/ArchR#275]
Hi @jgranja24 and @rcorces, 

**Describe the problem that your feature request would address.**
Users may wish to analyze the anchors, or pairs of cells across RNA and ATAC assays. The Seurat `FindTransferAnchors()` function runs within the `addGeneIntegrationMatrix()` function. The RNA-ATAC cell pairs can be accessed like so:

```
anchors <- FindTransferAnchors(
  reference = ref,
  query = query
)
head(anchors@anchors)
```

**Describe the solution you'd like**

It would awesome if the `addGeneIntegrationMatrix` function wrote the anchorset output into the working directory. This would be the modification to the source code for the `addGeneIntegrationMatrix` function: 

##############################################################################################
    #3. Transfer Anchors  
############################################################################################## 
.logDiffTime(sprintf("%s Seurat FindTransferAnchors", prefix), tstart, verbose = verbose, logFile = logFile)
transferAnchors <- .retryCatch({ #This sometimes can crash in mclapply so we can just add a re-run parameter
             gc()
             Seurat::FindTransferAnchors(
             reference = subRNA, 
             query = seuratATAC, 
             reduction = reduction, 
             features = genesUse,
             verbose = FALSE,
             ...
      )
      saveRDS(transferAnchors,"./anchorset.rds")`
}

**Comment by RegnerM2015** [comment]
Hi @jgranja24  and @rcorces,

I somehow missed the predictedCell column in the metadata of the ArchR project after `AddGeneIntegrationMatrix`.

This column will give the scRNA-seq cell barcode that is closest to the corresponding scATAC cell. Is this information derived from the Seurat anchor information? If so, my request to write the anchor set out to the working directory will not be necessary.

**Comment by jgranja24** [comment]
Yes @RegnerM2015 the nearest cell is derived from the Seurat anchor information. Okay I will close the issue! If you have any more issues feel free to open a new issue!
