### ISSUE TITLE
"No fragments found" error when run createArrowFiles() function using the bam file as input.

### ISSUE THREAD

**Issue by singletrips** [GreenleafLab/ArchR#281]
![image](https://user-images.githubusercontent.com/31929730/90052951-d89c6a00-dca7-11ea-8c76-e300facedecd.png)

**Comment by rcorces** [comment]
Please provide a detailed description, the commands used, and a minimal example of how we can reproduce the problem. Your bug report does not have any information that would enable us to help you.
I'm closing this issue but you can re-open it when you are ready to provide the required information.
