### ISSUE TITLE
fail in addMotifAnnotations in a custom reference

### ISSUE THREAD

**Issue by Liyuanwang89** [GreenleafLab/ArchR#284]
Hi,
 I'm working on analyze the primary ovary scATAC by ArchR in pig. As I followed the tutorial manual, I failed in addMotifAnnotations. At first, I tried it as below 

_> ovary5 <- addMotifAnnotations(ArchRProj = ovary5, motifSet = "cisbp", name = "Motif")
ArchR logging to : ArchRLogs/ArchR-addMotifAnnotations-7eb94805cf80-Date-2020-08-14_Time-17-09-41.log
If there is an issue, please report to github with logFile!
2020-08-14 17:09:48 : Gettting Motif Set, Species : , 0.101 mins elapsed.
Error in if (tolower(species) == "mus musculus") { :
  argument is of length zero_

After a time of many trials, I changed it into this

_> ovary5 <- addMotifAnnotations(ArchRProj = ovary5, motifSet = "JASPAR2020", name = "Motif", species = getGenome(ArchRProj = ovary5))
ArchR logging to : ArchRLogs/ArchR-addMotifAnnotations-7eb917310d96-Date-2020-08-14_Time-17-11-35.log
If there is an issue, please report to github with logFile!
2020-08-14 17:11:39 : Gettting Motif Set, Species : BSgenome.Sscrofa.UCSC.susScr11, 0.055 mins elapsed.
2020-08-14 17:11:42 : Finding Motif Positions with motifmatchr!, 0.095 mins elapsed.
Error in motif_mats[[x]] : subscript out of bounds
In addition: Warning message:
In .get_IDlist_by_query(x, opts) :
  Warning: Zero matrices returned with current critera_

It seems a little better but I still have no idea how to go on this time. There should be something wrong in _Creating Motif Overlap Matrix_. Help psl.

**Comment by Liyuanwang89** [comment]
Any help?

**Comment by jgranja24** [comment]
Sorry for the delay... I dont think you are using the species correctly. I think what you want is ---

`ovary5 <- addMotifAnnotations(ArchRProj = ovary5, motifSet = "JASPAR2020", name = "Motif", species = "Sus scrofa")`

However I dont think the species you are looking for exists in JASPAR database 

see [http://jaspar.genereg.net/search?q=Sus&collection=all&tax_group=all&tax_id=all&type=all&class=all&family=all&version=all](http://jaspar.genereg.net/search?q=Sus&collection=all&tax_group=all&tax_id=all&type=all&class=all&family=all&version=all)

**Comment by Liyuanwang89** [comment]
Thanks for your reply, it's true that the species I used here was sus scrofa. Now I had fixed it as
integ1 <- addMotifAnnotations(ArchRProj = integ1, motifSet = "encode", name = "Motif", species = getGenome(ArchRProj = integ1))
And now I had added the motif annotation successfully.
Thanks for your reply again.
Best wishes.

Liyuan Wang （Mr. , Ph.D ）
王力圆   博士
Post doctor
博士后

Agricultural Genomics Institute at Shenzhen, Chinese Academy of Agricultural Sciences

中国农业科学院深圳农业基因组研究所

No.7 Pengfei Road, Dapeng New District, Shenzhen 518120,China

深圳市大鹏新区鹏飞路7号，518120

电话：185-1815-3609

Tel: +86-18518153609

邮箱：liyuanwang<mailto:jerrylee_bio@126.com>89@hotmail.com

E-mail: liyuanwang<mailto:jerrylee_bio@126.com>89@hotmail.com

________________________________
发件人: jgranja24 <notifications@github.com>
发送时间: 2020年10月27日 14:13
收件人: GreenleafLab/ArchR <ArchR@noreply.github.com>
抄送: Liyuanwang89 <liyuanwang89@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [GreenleafLab/ArchR] fail in addMotifAnnotations in a custom reference (#284)


Sorry for the delay... I dont think you are using the species correctly. I think what you want is ---

ovary5 <- addMotifAnnotations(ArchRProj = ovary5, motifSet = "JASPAR2020", name = "Motif", species = "Sus scrofa")

However I dont think the species you are looking for exists in JASPAR database

see http://jaspar.genereg.net/search?q=Sus&collection=all&tax_group=all&tax_id=all&type=all&class=all&family=all&version=all

―
