### ISSUE TITLE
Different R2 values in different sample

### ISSUE THREAD

**Issue by Dragonlongzhilin** [GreenleafLab/ArchR#285]
In the manual, If these R2 values are much lower (i.e. less than 0.9), this often indicates that the cells within the Arrow file have very little heterogeneity. I have 4 samples, 2 of which have R values greater than 0.9, but the other two have R values less than 0.9. How should I remove doublet?

**Comment by jgranja24** [comment]
The scores will be NA in the samples that are lower R2 and thus you can use filterDoublets as normal.

Hope this helps!

Jeff

**Comment by jgranja24** [comment]
I am closing this issue feel free to open a new issue if you have further troubles!
Good luck with the analysis
