### ISSUE TITLE
Extracting bigWig/bedGraph

### ISSUE THREAD

**Issue by mehrankr** [GreenleafLab/ArchR#286]
Hello,

I was wondering to ask if it would be possible to either expand the documentation on how to manually access the accessibility signal as visualized by ArchRBrowser and plotBrowserTrack, or alternative provide a function to extract bedGraph/bigWig for specific regions.

As amazing as the ArchRBrowser and plotBrowserTrack, I often need to make my own visualizations and I'm sure a lot of people would appreciate such features.

All the best,
Mehran

**Comment by rcorces** [comment]
It sounds like you are looking for the `getGroupBW()` function. The documentation for this function hasnt been added but it was introduced in response to #54 

Fair warning that some users are reporting normalization issues with the function and we are still working on it from #216

Adding this documentation is already on the to-do list so I'm closing this for now but feel free to re-open if you think the above function isnt what you need.
