### ISSUE TITLE
Bone Marrow cells analysis not reproducible

### ISSUE THREAD

**Issue by nikostrasan** [GreenleafLab/ArchR#287]
I am trying to reproduce the analysis show in your paper (as shown in Fig2(a-d)), however, after tweaking the parameters several 
times, I still get different results, 

**Could you please share with me the parameters you used to run the analysis with addIterativeLSI() and addClusters()?**

After creating ArrowFiles and ArchPoject file, I use the following to obtain the embedding profiles:
#Dimensionality reduction
#LSI calculation
projBM2 <- **addIterativeLSI**(
    ArchRProj = projBM2,
    useMatrix = "TileMatrix", 
    name = "IterativeLSI", 
    **iterations = 2, 
    clusterParams = list( #See Seurat::FindClusters
        resolution = c(0.3), 
        sampleCells = 10000, 
        n.start = 10), 
    varFeatures = 25000, 
    dimsToUse = 1:30,
    force=TRUE)**

#batcheffect correction
projBM2 <- addHarmony(
    ArchRProj = projBM2,
    reducedDims = "IterativeLSI",
    name = "Harmony",
    groupBy = "Sample",
    force=TRUE)

#clustering
projBM2 <- addClusters(
    input = projBM2,
    reducedDims = "IterativeLSI",
    **method = "Seurat",
    name = "Clusters",
    resolution = 0.7,
    force=TRUE)**
head(projBM2$Clusters)
table(projBM2$Clusters)
cM <- confusionMatrix(paste0(projBM2$Clusters), paste0(projBM2$Sample))
cM
library(pheatmap)
pdf("./BM_Clusters.pdf")
cM <- cM / Matrix::rowSums(cM)
p <- pheatmap::pheatmap(
    mat = as.matrix(cM), 
    color = paletteContinuous("whiteBlue"), 
    border_color = "black")
p
dev.off()

#single-cell embeddings 
projBM2 <- addUMAP(
    ArchRProj = projBM2, 
    reducedDims = "IterativeLSI", 
    name = "UMAP", 
    nNeighbors = 30, 
    minDist = 0.5, 
    metric = "cosine",
    force=TRUE)

pdf('projBM2_embedding_scATAC.pdf')
plotEmbedding(ArchRProj = projBM2, colorBy = "cellColData", name = "Sample", embedding = "UMAP")
dev.off()

#UMAP embedding plot
library(patchwork)
p1 <- plotEmbedding(ArchRProj = projBM2, colorBy = "cellColData", name = "Sample", embedding = "UMAP")
p2 <- plotEmbedding(ArchRProj = projBM2, colorBy = "cellColData", name = "Clusters", embedding = "UMAP")
print(p1 + p2)
ggsave("Plot-UMAP-projBM2-Clusters.pdf")

#UMAP after harmony
projBM2 <- addUMAP(
    ArchRProj = projBM2, 
    reducedDims = "Harmony", 
    name = "UMAPHarmony", 
    nNeighbors = 30, 
    minDist = 0.5, 
    metric = "cosine",
    force=TRUE)

#UMAP after harmony
p3 <- plotEmbedding(ArchRProj = projBM2, colorBy = "cellColData", name = "Sample", embedding = "UMAPHarmony")
p4 <- plotEmbedding(ArchRProj = projBM2, colorBy = "cellColData", name = "Clusters", embedding = "UMAPHarmony")
ggAlignPlots(p3, p4, type = "h")
plotPDF(p1,p2,p3,p4, name = "Plot-UMAP2Harmony-projBM2-Clusters.pdf", ArchRProj = projBM2, addDOC = FALSE, width = 5, height = 5)

[Plot-UMAP2Harmony-projBM2-Clusters.pdf](https://github.com/GreenleafLab/ArchR/files/5096934/Plot-UMAP2Harmony-projBM2-Clusters.pdf)

**Comment by rcorces** [comment]
My understanding is that iterative LSI is non-deterministic. Even if you run with exactly the same parameters, you will not get exactly the same result as in the publication. This is outlined in [the manual](https://www.archrproject.com/bookdown/iterative-latent-semantic-indexing-lsi.html).

The UMAP that you provided looks very similar to the one in the paper.

@jgranja24 - We dont have the code for analyzing the BM dataset on the publication page. Maybe you can add this?

**Comment by nikostrasan** [comment]
Indeed the first 2 plots look very similar to the ones provided in the paper. 
However, after Harmony normalization with the parameters from the tutorial, UMAP plots seem very odd (populations are segregated based on the sample). 
It would be very helpful if you could share the code.
Thanks in advance

**Comment by jgranja24** [comment]
Hi @nikostrasan,

Sorry for the delays (crazy times):

The code is available at the publication site. See below -

**For all steps look here**
[https://github.com/GreenleafLab/ArchR_2020/tree/master/ArchR_Benchmarking/BMMC-30k/ArchR](https://github.com/GreenleafLab/ArchR_2020/tree/master/ArchR_Benchmarking/BMMC-30k/ArchR
)

**Dimensionality reduction**
Heme_Small_Rep1-ArchR-3-ReduceDimsNoDoub.html

**Embedding**
Heme_Small_Rep1-ArchR-5-EmbeddingNoDoub.html

To download repository -
[https://github.com/GreenleafLab/ArchR_2020/archive/master.zip](https://github.com/GreenleafLab/ArchR_2020/archive/master.zip
)
Best

Jeff

**Comment by jgranja24** [comment]
Basically  the analysis is -

```
1. Dimensionality reduction
proj <- addIterativeLSI(
  ArchRProj = proj,
  varFeatures = 25000,
  sampleCellsFinal = NULL,
  saveIterations = FALSE,
  force = TRUE
)

2. Clusters
proj <- addClusters(proj, filterBias = TRUE)

3. UMAP
proj <- addUMAP(proj)

```

**Comment by rcorces** [comment]
@nikostrasan - Closing this. Feel free to post again if you need anything else and we can reopen.
