### ISSUE TITLE
Error message when running addGeneIntegrationMatrix()

### ISSUE THREAD

**Issue by chent5** [GreenleafLab/ArchR#288]
Thanks a lot for developing this package.

I ran addGeneIntegrationMatrix() function taking a Seurat object (seRNA) as input.
# Below is the code I used:
projHeme2 <- addGeneIntegrationMatrix(
  ArchRProj = projHeme2, 
  useMatrix = "GeneScoreMatrix",
  matrixName = "GeneIntegrationMatrix",
  reducedDims = "IterativeLSI",
  seRNA = seRNA,
  addToArrow = FALSE,
  groupRNA = "CRID",
  nameCell = "predictedCell_Un",
  nameGroup = "predictedGroup_Un",
  nameScore = "predictedScore_Un"
)

I got the error messages below:
ArchR logging to : ArchRLogs/ArchR-addGeneIntegrationMatrix-3957e79179719-Date-2020-08-19_Time-13-01-55.log
If there is an issue, please report to github with logFile!
2020-08-19 13:01:55 : Running Seurat's Integration Stuart* et al 2019, 0.006 mins elapsed.
2020-08-19 13:01:55 : Checking ATAC Input, 0.014 mins elapsed.
2020-08-19 13:01:55 : Checking RNA Input, 0.014 mins elapsed.
Error: Cannot add a different number of cells than already present
Error during wrapup: no slot of name "assay.orig" for this object of class "Assay"

What do these errors mean? Are there anything wrong with the code or the Seurat object? Thank you so much!

**Comment by jgranja24** [comment]
Can you supply the log file please. Thanks!

**Comment by liaoshengyou** [comment]
I also get this error message. like this:
If there is an issue, please report to github with logFile!
2020-11-18 08:16:30 : Running Seurat's Integration Stuart* et al 2019, 0.004 mins elapsed.
Warning: The following arguments are not used: drop
2020-11-18 08:16:32 : Checking ATAC Input, 0.035 mins elapsed.
2020-11-18 08:16:32 : Checking RNA Input, 0.035 mins elapsed.
Error: Cannot add a different number of cells than already present



Then I Read this addGeneIntegrationMatrix function,  and I resolve this in below:
add a code between this 2 line:

  seuratRNA <- seuratRNA[, unique(cellRNA)]
  **DefaultAssay(seuratRNA) <- "RNA"**
  seuratRNA <- NormalizeData(object = seuratRNA, verbose = FALSE)

**Comment by cswoboda** [comment]
Hello,

I know this issue is old, but the error might be due to an older seurat object version. I have had this error happen in Seurat when trying to use view() on my seurat objects that were made before 3.2. The assay.orig value isnt really useful for much, and is NULL in most cases. If you just run seurat@assays[["RNA"]]@assay.orig <- NULL it may fix the problem.
