### ISSUE TITLE
getMarkerFeatures error, possibly due to no markers.

### ISSUE THREAD

**Issue by koenvandenberge** [GreenleafLab/ArchR#289]
Before you submit this issue please update ArchR to the latest version and make sure that this issue has not already been fixed in the latest release. ArchR is in *beta* and we will fix problems as they arise. To update ArchR:

devtools::install_github("GreenleafLab/ArchR", ref="master", repos = BiocManager::repositories())

If your issue persists, then please submit this bug report.

PLEASE FILL OUT THE RELEVANT INFORMATION AND DELETE THE UNUSED PORTIONS OF THIS ISSUE TEMPLATE.

**Attach your log file**
ArchR has a built-in logging functionality for all complex functions. You MUST attach your log file (indicated in the console output) to this issue. Just drag and drop it here.
[ArchR-getMarkerFeatures-2103c7cb6f1-Date-2020-08-20_Time-21-05-55.log](https://github.com/GreenleafLab/ArchR/files/5106743/ArchR-getMarkerFeatures-2103c7cb6f1-Date-2020-08-20_Time-21-05-55.log)

**Describe the bug**
I am running `GetMarkerFeatures` on a dataset where some groups have low cell numbers (~100) which may possibly lead to no (robust) markers. Running the code 
```
markerPeaks_subHybrid <- getMarkerFeatures(
    ArchRProj = archProj, 
    useMatrix = "PeakMatrix", 
    groupBy = "predAnn",
    bias = c("TSSEnrichment", "log10(nFrags)"),
    testMethod = "wilcoxon")
```
provides the error
```
ArchR logging to : ArchRLogs/ArchR-getMarkerFeatures-2103c7cb6f1-Date-2020-08-20_Time-21-05-55.log
If there is an issue, please report to github with logFile!
MatrixClass = Sparse.Integer.Matrix
2020-08-20 21:05:56 : Matching Known Biases, 0.004 mins elapsed.
1 function calls resulted in an errorError in .safelapply(seq_along(matchObj[[1]]), function(x) { : 
Error Found Iteration 4 : 
	[1] "Error in `rownames<-`(`*tmp*`, value = c(\"f1\", \"f2\", \"f3\", \"f4\", \"f5\",  : \n  attempt to set 'rownames' on an object with no dimensions\n"
	<simpleError in `rownames<-`(`*tmp*`, value = c("f1", "f2", "f3", "f4", "f5", "f6", "f7", "f8", "f9", "f10", "f11", "f12", "f13", "f14", "f15", "f16", "f17", "f18", "f19", "f20", "f21", "f22", "f23", "f24", "f25", "f26", "f27", "f28", "f29", "f30", "
```
When I pick a cell classification with more cells per group, it runs fine.

**To Reproduce**
I'm able to reproduce this error using the tutorial data with artificial clusters:

```
library(ArchR)
inputFiles <- getTutorialData("Hematopoiesis")
addArchRGenome("hg19")
ArrowFiles <- createArrowFiles(
  inputFiles = inputFiles,
  sampleNames = names(inputFiles),
  filterTSS = 4, #Dont set this too high because you can always increase later
  filterFrags = 1000, 
  addTileMat = TRUE,
  addGeneScoreMat = TRUE
)

projHeme1 <- ArchRProject(
  ArrowFiles = ArrowFiles, 
  outputDirectory = "HemeTutorial",
  copyArrows = TRUE #This is recommened so that if you modify the Arrow files you have an original copy for later usage.
)

set.seed(2)
cl <- sample(1:6, size=nCells(projHeme1), replace=TRUE)
cl[1:3] <- 7
table(cl)
projHeme1@cellColData$cl <- cl

markersGS <- getMarkerFeatures(
  ArchRProj = projHeme1, 
  useMatrix = "GeneScoreMatrix", 
  groupBy = "cl",
  bias = c("TSSEnrichment", "log10(nFrags)"),
  testMethod = "wilcoxon"
)
```

**Expected behavior**
Even if there are no found markers for a given cell population, other markers should still be returned.

**Comment by xiangrong7** [comment]
I got same error ...

**Comment by jgranja24** [comment]
Sorry for the delays....

Can you try this with the new dev version? I belive I fixed it but it would be helpful if you could test it out!

devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.0", repos = BiocManager::repositories())

Please make sure to close your session after installation reopen and call the function using ArchR::getMarkerFeatures if loading an Rdata object

**Comment by jgranja24** [comment]
I am closing this issue as it seems to be resolved in the release branch reported by others. Feel free to reopen, comment or open new issues!
