### ISSUE TITLE
cluster-level integration

### ISSUE THREAD

**Issue by suminwei2772** [GreenleafLab/ArchR#293]
Hi,
I am looking for an ArchR feature that allows for cluster-level integration of scATAC-seq with scRNA-seq. I understand currently ArchR tries to assign each cell in scATAC-seq to a cell in scRNA-seq. Would it be possible to introduce a feature to first aggregate cells from each cluster, and assign each aggregate cluster profile in scATAC-seq to an aggregated scRNA-seq profile for each scRNA-seq cluster?
Lisa

**Comment by jgranja24** [comment]
Hi @suminwei2772,

I wouldnt recommend doing this type of integration because it forces you to merge cells and then relate clusters versus doing this at the single cell level. Nevertheless if you want to do this type of analyses Id do it like so -

```
library(ArchR)

load("Chapter-08-scRNA_Labeling.Rdata")

#Get Gene Scores
seGS <- getGroupSE(ArchRProj=projHeme3, useMatrix="GeneScoreMatrix", groupBy="Clusters2", scaleTo = 10000)
rownames(seGS) <- rowData(seGS)$name

#Get scRNA
if(!file.exists("scRNA-Hematopoiesis-Granja-2019.rds")){
    download.file(
        url = "https://jeffgranja.s3.amazonaws.com/ArchR/TestData/scRNA-Hematopoiesis-Granja-2019.rds",
        destfile = "scRNA-Hematopoiesis-Granja-2019.rds"
    )
}
seRNA <- readRDS("scRNA-Hematopoiesis-Granja-2019.rds")
matRNA <- ArchR:::.groupMeans(mat=assay(seRNA), groups=colData(seRNA)$BioClassification, sparse=TRUE)

#Get Same Organized Matrix
geneIntersect <- intersect(rownames(matRNA), rowData(seGS)$name)
matRNA <- matRNA[geneIntersect, ]
matGS <- assay(seGS)[geneIntersect, ]

#Normalize
matRNA <- t(t(matRNA) / colSums(matRNA)) * 10000
matGS <- t(t(matGS) / colSums(matGS)) * 10000

#Compute top variable genes
varGS <- head(order(matrixStats::rowVars(log2(matGS+1)), decreasing=TRUE), 2500)
varRNA <- head(order(matrixStats::rowVars(log2(matRNA+1)), decreasing=TRUE), 2500)
varGenes <- unique(sort(c(varGS, varRNA)))

#Correlations
corDF <- lapply(seq_len(ncol(matRNA)), function(x){
	df <- data.frame(cor(matGS[varGenes, ], matRNA[varGenes, x], method = "spearman"))
	df
}) %>% Reduce("cbind", .)
colnames(corDF) <- paste0("RNA.",colnames(matRNA))
rownames(corDF) <- paste0("ATAC.",rownames(corDF))

#Row Normalize
scaledDF <- ArchR:::.rowScale(as.matrix(corDF))

pdf("Heatmap.pdf")
pheatmap::pheatmap(scaledDF[[1]], color = paletteContinuous("horizonExtra"), border_color = "black")
dev.off()
```

This is the heatmap as you can see its an ok analysis but not as precise.

[Heatmap.pdf](https://github.com/GreenleafLab/ArchR/files/5381763/Heatmap.pdf)

Hope this helps

Jeff

**Comment by jgranja24** [comment]
Im closing this issue (trying to get issues down for new release). 
Feel free to re-open any other issues you may have.  Good luck
in your anlaysis!

Best

Jeff
