### ISSUE TITLE
createArrowFiles Error

### ISSUE THREAD

**Issue by spietrzak** [GreenleafLab/ArchR#294]
I have used ArchR successfully in the past, but I ran into an error after I tried to modify the input fragments file. We have tried to downsize some of our samples so that each one has a more equal number of barcodes (cells). The new files should be in the same tsv.gz format as the original files and are also named similarly (i.e. sample_name.fragments.tsv.gz). ArchR seems to recognize it when defining the input files, but I run into an error when I try to create the Arrow files, as it doesn't seem to find any barcodes in the file. Here is the code and output that I see:

<img width="788" alt="Screen Shot 2020-08-26 at 11 51 21 AM" src="https://user-images.githubusercontent.com/43301299/91332969-8d4b8680-e792-11ea-9234-6e840af1dabb.png">

I am also attaching the ArchR log file as well. When I unzip the fragments file and open in Excel, it looks exactly like the unmodified files that I used previously in ArchR that were successful. Let me know if you need any additional information from me. 
[ArchR-createArrows-dde01b0bca59-Date-2020-08-26_Time-11-32-59.log](https://github.com/GreenleafLab/ArchR/files/5131236/ArchR-createArrows-dde01b0bca59-Date-2020-08-26_Time-11-32-59.log)

**Comment by rcorces** [comment]
I'm not sure we have enough information to diagnose the problem. It seems like something must have changed when you trimmed your original input files.
You can try using the `reformatFragmentFiles()` function to see if that fixes whatever formatting problem has been introduced.

**Comment by spietrzak** [comment]
Thanks for your feedback Ryan. That function was able to format my fragments file so that it can now be ready by ArchR. I was able to create an Arrow file for this test sample and run it through some of the subsequent steps. Thanks for your help.

**Comment by rcorces** [comment]
Glad this worked. I'll flag this to add to the documentation.
