### ISSUE TITLE
Reclustering a single cluster into a set of clusters of specified number

### ISSUE THREAD

**Issue by hugokitano** [GreenleafLab/ArchR#298]
I guess this is a two-part question: I have eight clusters, and I believe that one cluster is made up of naive T cells, containing both cd4 and cd8 cells. Is it possible to recluster this cluster into exactly two new clusters, keeping all the other clusters as well? Thank you!

**Comment by rcorces** [comment]
I do not think this is currently possible in ArchR. I'm also not sure if it is possible in similar scRNA-seq packages for RNA data. If you have an example of how this is done elsewhere, we might be able to implement it.

I think if I were posed with this problem, I would create a new ArchR project with only the subset of cells I was interested in, then cluster them separately and identify the cell labels for the two different sub clusters. I would then go back to the original project, create a new column in cellColData, and annotate the corresponding subcluster. But there are analytical caveats to this that would have to be made clear in the presentation.
