### ISSUE TITLE
addGeneScoreMatrix fails with ArrowFile inputs

### ISSUE THREAD

**Issue by bnprks** [GreenleafLab/ArchR#300]
addGeneScore matrix has parameter validation error when `input` is given as a character vector of ArrowFiles. This is because `blacklist = getBlacklist(input)` throws a validation error when `input` is a character vector. Perhaps changing the default to something along the lines of `blacklist=if(is.character(input)) {getBlacklist()} else {getBlacklist(input)}` would be more user friendly

**Comment by jgranja24** [comment]
Yeah I agree Ill update getBlacklist to return null if input is character.

**Comment by jgranja24** [comment]
This is now updated. Thanks for the help, I am closing this issue.

```
getBlacklist <- function(ArchRProj = NULL){
  if(is.character(ArchRProj)){
    ArchRProj <- NULL
  }
  .validInput(input = ArchRProj, name = "ArchRProj", valid = c("ArchRProject","null"))
  if(is.null(ArchRProj)){
    genomeAnnotation <- getArchRGenome(genomeAnnotation = TRUE)
    if(!is.null(genomeAnnotation)){
      return(genomeAnnotation$blacklist)
    }
    stop("getBlacklist : ArchRPRoj is NULL and there is no genome set with addArchRGenome!")
  }
  .validInput(input = ArchRProj, name = "ArchRProj", valid = "ArchRProject")
  return(ArchRProj@genomeAnnotation$blacklist)
}
```
