### ISSUE TITLE
createArrowFiles fails with demultiplexed fragments

### ISSUE THREAD

**Issue by ivanferrreira** [GreenleafLab/ArchR#302]
Hi,

I have multiple samples that were sequenced in 8 separate runs, I demultiplexed the fragments file and merged/sorted, and then imported into ArchR. But as soon as that sort of input is used createArrowFiles encounters an error; I noticed that even gunzipping the tutorial file creates the same error message, so archR is struggling to read anything but tsv.gz files:

e.g.:
>test
>"scATAC_BMMC_R1.fragments.tsv" 

> test <- createArrowFiles(
>+   inputFiles = test,
>+   sampleNames = names(tests_tests),
>+   filterTSS = 4, #Dont set this too high because you can always increase later
>+   filterFrags = 1000,
>+   addTileMat = TRUE,
>+   addGeneScoreMat = TRUE
>+ )

Using GeneAnnotation set by addArchRGenome(Hg19)!
Using GeneAnnotation set by addArchRGenome(Hg19)!
ArchR logging to : ArchRLogs/ArchR-createArrows-406c33c8ca17-Date-2020-09-08_Time-20-03-17.log
If there is an issue, please report to github with logFile!
2020-09-08 20:03:17 : Batch Execution w/ safelapply!, 0 mins elapsed.
Attempting to index ~/HemeFragments/scATAC_BMMC_R1.fragments.tsv as tabix..
2020-09-08 20:03:17 : **createArrowFiles has encountered an error**, checking if any ArrowFiles completed..
ArchR logging successful to : ArchRLogs/ArchR-createArrows-406c33c8ca17-Date-2020-09-08_Time-20-03-17.log

Do you know how to fix that issue for customised fragment files?

Cheers,
Ivan

**Comment by jgranja24** [comment]
Hi Ivan,

Try the `reformatFragmentFiles` function. They have to be bgzipped for tabix. Its incredibly misleading from 10x because there .gz = .bgz and i guess i havent helped much either...

**Comment by ivanferrreira** [comment]
Totally misleading from 10x, but you guys did a terrific pipeline! 
Thank you, this works perfectly!

cheers
