### ISSUE TITLE
getMarkerFeatures error, possibly due to very few cells in some groups

### ISSUE THREAD

**Issue by yding9** [GreenleafLab/ArchR#303]
**Attach your log file**
ArchR has a built-in logging functionality for all complex functions. You MUST attach your log file (indicated in the console output) to this issue. Just drag and drop it here.
[ArchR-getMarkerFeatures-338ef7da057bf-Date-2020-09-08_Time-16-27-58.log](https://github.com/GreenleafLab/ArchR/files/5191879/ArchR-getMarkerFeatures-338ef7da057bf-Date-2020-09-08_Time-16-27-58.log)

**Describe the bug**
I am running getMarkerFeatures using the PeakMatrix on a dataset where some groups have low cell numbers (4 - 60) which may possibly lead to no robust markers. 

When I run addGroupCoverages and adReproduciblePeakSet functions, I set minCells = 1. No errors running the following addGroupCoverages and adReproduciblePeakSet functions:
projInh <- addGroupCoverages(ArchRProj = projInh, groupBy = "predictedGroup_Un_celltype", minCells = 1, force = TRUE)
pathToMacs2 <- findMacs2()
projInh <- addReproduciblePeakSet(
  ArchRProj = projInh, 
  groupBy = "predictedGroup_Un_celltype",
  minCells = 1,
  pathToMacs2 = pathToMacs2,
  force = TRUE
)

I get error messages when running the following code:
markersPeaks <- getMarkerFeatures(
  ArchRProj = projInh, 
  useMatrix = "PeakMatrix", 
  groupBy = "predictedGroup_Un_celltype",
  bias = c("TSSEnrichment", "log10(nFrags)"),
  testMethod = "wilcoxon"
)

Error in .safelapply(seq_along(matchObj[[1]]), function(x) { :
Error Found Iteration 17 :
        [1] "Error in `rownames<-`(`*tmp*`, value = c(\"f1\", \"f2\", \"f3\", \"f4\", \"f5\",  : \n  attempt to set 'rownames' on an object with no dimensions\n"
        <simpleError in `rownames<-`(`*tmp*`, value = c("f1", "f2", "f3", "f4", "f5", "f6", "f7", "f8", "f9", "f10", "f11", "f12", "f13", "f14", "f15", "f16", "f17", "f18", "f19", "f20", "f21", "f22", "f23", "f24", "f25", "f26", "f27", "f28", "f29", "f30", "
In addition: Warning message:
In mclapply(..., mc.cores = threads, mc.preschedule = preschedule) :
  1 function calls resulted in an error

**Expected behavior**
When I use another cell classification with more cells per group, it runs fines. I notice another ArchR user also reports a similar issue. Hope this function can be functional even if there are no found markers for some given cell populations.

**Comment by Meggie-MH** [comment]
I ran into the same error message after I subset the date. Wonder if it's true that there is a limit of minCell for using getMarkerFeatures. It works just fine at the beginning when there are 10X more cells. Thanks!

**Comment by yding9** [comment]
After reading some of the source code, I came up with a naive thought. The bug should come from the hidden testMarkerSC function (rownames(scMaty) <- rownames(featureDFY)). It seems like when we have fewer cells the hidden function matchBiasCellGroups would return an empty object. And when this empty object is used to pull out the partial peak matrix we get an empty matrix. The error message comes when we try to assign the row names of the feature data frame to the empty matrix. 

I don't know if my judgment is correct or not. Hope the authors could fix this soon! Thanks a lot!

**Comment by jgranja24** [comment]
Can you try this with the new dev version? I belive I fixed it but it would be helpful if you could test it out!

`devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.0", repos = BiocManager::repositories())
`

Please make sure to close your session after installation reopen and call the function using ArchR::getMarkerFeatures if loading an Rdata object

**Comment by yding9** [comment]
Thank you so much @jgranja24 ! I tested on the same dataset and it worked! Will let you know if I have problems going forward.

**Comment by yding9** [comment]
After installation of the new dev version, I met problems when I created arrow files (running the createArrowFiles function) and added doublet scores (running the addDoubletScores function). I believe the problem is more related to the plotting module and I'm not able to open TSS_by_Unique_Frags.pdf and Doublet-Summary.pdf. Not sure if the plotting error would influence the downstream analysis.

ArrowFiles <- createArrowFiles(
  inputFiles = fragments.files,
  sampleNames = names(fragments.files),
  filterTSS = 1,
  filterFrags = 1000, 
  addTileMat = TRUE,
  addGeneScoreMat = TRUE
)

doubScores <- addDoubletScores(
  input = ArrowFiles,
  k = 10, #Refers to how many cells near a "pseudo-doublet" to count.
  knnMethod = "UMAP", #Refers to the embedding to use for nearest neighbor search with doublet projection.
  LSIMethod = 1
)

Warning: Ignoring unknown parameters: size
2020-10-16 15:33:55 : Continuing through after error ggplot for TSS by Frags, 52.011 mins elapsed.

H19.30.004.MEC.ATAC.001.001 (1 of 4) : UMAP Projection R^2 = 0.92185
Warning: Ignoring unknown parameters: size
Warning: Ignoring unknown parameters: size
Warning: Ignoring unknown parameters: size
Warning: Ignoring unknown parameters: size

************************************************************
2020-10-16 17:51:21 : ERROR Found in ggplot for H19.30.004.MEC.ATAC.001.001 (1 of 4) :
LogFile = ArchRLogs/ArchR-addDoubletScores-4e8b22007b0f4-Date-2020-10-16_Time-17-41-31.log

<simpleError in check.length(gparname): 'gpar' element 'fontsize' must not be length 0>


Thank you so much for checking this! 

[ArchR-createArrows-4e8b27313571f-Date-2020-10-16_Time-14-41-53.log](https://github.com/GreenleafLab/ArchR/files/5394893/ArchR-createArrows-4e8b27313571f-Date-2020-10-16_Time-14-41-53.log)
[ArchR-addDoubletScores-4e8b22007b0f4-Date-2020-10-16_Time-17-41-31.log](https://github.com/GreenleafLab/ArchR/files/5394894/ArchR-addDoubletScores-4e8b22007b0f4-Date-2020-10-16_Time-17-41-31.log)

**Comment by jgranja24** [comment]
Can you reinstall and retry this with the release brach. I just re-updated a function. Hopefully that helps!

**Comment by rcorces** [comment]
@yding9 - in the future, please create a new issue given that your second problem was unrelated to your first.

**Comment by yding9** [comment]
Thank you both @rcorces @jgranja24! Will open a new issue going forward.
