### ISSUE TITLE
Heatmap of peak-to-gene links but using ATAC-seq-only co-accessibility

### ISSUE THREAD

**Issue by liaojinyue** [GreenleafLab/ArchR#304]
Hi, 

Thanks for this wonderful tool. 

We only have scATAC-seq data and would like to have a figure similar to the plotPeak2GeneHeatmap. I understand that plotPeak2GeneHeatmap requires predicted mRNA expression from scRNA-seq data. I'm wondering if we can perform similar analysis using GeneScore from scATAC-seq data.

Thanks,
Jason

**Comment by rcorces** [comment]
I dont think this would work. The logic seems circular. You derive the GeneScore from local accessibility and then ask if the local accessibility is correlated to the GeneScore. You could certainly plot a heatmap of ATAC-seq signal at peaks found through co-accessibility analysis but this does not sound like what you are looking for.

**Comment by liaojinyue** [comment]
That makes sense. Thanks.
Jason
