### ISSUE TITLE
Subsetting an ArchRProject using list of specific barcodes

### ISSUE THREAD

**Issue by tsslab** [GreenleafLab/ArchR#305]
Do not use this form to report a bug in ArchR Instead, use the "Bug report" option.

PLEASE FILL OUT THE RELEVANT INFORMATION AND DELETE THE UNUSED PORTIONS OF THIS ISSUE TEMPLATE.

**Describe the problem that your feature request would address.**
We ran several samples in a single channel on the 10X scATAC-seq platform and have used genetic demultiplexing to produce specific lists of barcodes associated with each sample. Can we use specific barcode lists to subset ArchRProject containing all sequenced samples and produce individual projects containing cells from individual samples only?

**Comment by rcorces** [comment]
I think the correct way to do this would be to use the `validBarcodes()` parameter in the `createArrowFiles()` function. This will create an arrow file just from the barcodes of interest. Feel free to close this issue if this solution works for you.

**Comment by jgranja24** [comment]
You can also use subsetArchRProject with cells 

```
subsetArchRProject <- function(
  ArchRProj = NULL,
  **cells = CELLSTOSUBSET**,
  outputDirectory = "ArchRSubset",
  dropCells = TRUE,
  logFile = NULL,
  threads = getArchRThreads()
)
```

Closing this issue, feel free to re-open if this is not what you were hoping for.
