### ISSUE TITLE
pdf of UMAP has large point size

### ISSUE THREAD

**Issue by atimms** [GreenleafLab/ArchR#306]
**Describe the bug**
When printing a UMAP to PDF sometime the point size is really large (as in the attached file). I've tried changing point size, resolution and size of the PDF and this doesn't make any changes. The reason I consider this a bug is because I can run the same command and get different output. 
code used:
p1 <- plotEmbedding(proj1, colorBy = "cellColData", name = "Clusters3")
plotPDF(p1, name = "UMAP_clusters_atac.pdf", ArchRProj = proj1, addDOC = FALSE, width = 5, height = 5)

**Expected behavior**
Smaller point size for each cell so can easily distinguish more cells in the umap.

**Screenshots**
here's the PDF with large point size
[UMAP_clusters_atac.pdf](https://github.com/GreenleafLab/ArchR/files/5196368/UMAP_clusters_atac.pdf)

**Attach your log file**
[ArchR-plotEmbedding-10bd3558b1bae-Date-2020-09-09_Time-08-45-38.log](https://github.com/GreenleafLab/ArchR/files/5196370/ArchR-plotEmbedding-10bd3558b1bae-Date-2020-09-09_Time-08-45-38.log)

**Comment by rcorces** [comment]
Sorry if I'm misinterpreting your question.
Have you tried changing the `size` attribute in `plotEmbedding()`? This is supposed to change the size of the points on the plot.

**Comment by atimms** [comment]
I have changed the point size in plotEmbedding and get make the points larger but not smaller.

**Comment by rcorces** [comment]
Can you try setting `rastr = FALSE` in `plotEmbedding()` and then try changing the point size? I think I've experienced a similar issue before related to rasterization but this may have been in a much earlier version of ArchR.

**Comment by atimms** [comment]
that worked, thanks for your help.

Andrew

**Comment by rcorces** [comment]
@jgranja24 - I tried to parse through the code for this but my interpretation might not be correct. Is it possible that the `default_aes` settings here are over-writing the point size in some instances? https://github.com/GreenleafLab/ArchR/blob/020757998cd87abb0414991b59b8424958679be0/R/GgplotUtils.R#L993

**Comment by jgranja24** [comment]
I removed the default aes, hopefully this helps. Also I think size when rastering is smaller than when not. Try to adjust the size param with rastr = TRUE to get your wanted size. Closing this issue, feel free to re-open if you feel this is not solved.

`devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.0", repos = BiocManager::repositories())
`
