### ISSUE TITLE
Subsetted Arrow Files not retaining changes

### ISSUE THREAD

**Issue by Seandelao** [GreenleafLab/ArchR#310]
Hello, 

Thank you for the fantastic package; as someone who has little to no scATAC experience I find it very easy to use and follow! 

I am trying to combine multiple scATAC Seq data sets. I have performed filtering based on TSS, nFrags and doublets for each data set separately, then subsetted my cell type (clusters) of interest. I now want to take each of these ArrowFiles and create a new ArchR project with the subsetted ArrowFiles, so I have saved my individual data sets with the following command: 

saveArchRProject(ArchRProj = Proj, outputDirectory = NewDir, dropCells = TRUE), 

where nNewDir is a new folder separate from where the original ArrowFile is. When looking size of the newly created ArrowFile, I can see that it is significantly smaller than the original file. However, when I now load these files into a new ArchR project, utilizing the directory to the subsetted ArrowFiles, it returns a project consisting of the same amount of cells in the original, unfiltered/unsubsetted file. 

Any idea what might be happening here? Alternatively, is there a way to filter individual ArrowFiles from a combined ArchR project containing multiple samples (ArrowFiles) with different parameters (i.e. TSS cutoff of 7 in sample 1, cutoff 9 in ArrowFile 2, etc.)? I am using the following command for the individual datasets: 

idxPass <- which(Prof$TSSEnrichment >= 8)
cellsPass <- Prof$cellNames[idxPass]
Prof[cellsPass, ]

Thank you!

**Comment by Seandelao** [comment]
I have also used subsetArchRProject() and got the same result.

**Comment by bnprks** [comment]
I have also seen this behavior, I believe it is because ArchR only subsets the data matrices, but does not subset the list of cells in the file's metadata. Ideally this could get fixed in ArchR's subsetting code, but as a workaround you can manually call `subsetCells` after loading the project, while only passing the list of cells you want to keep.

**Comment by jgranja24** [comment]
Sorry about this I am working on fixing this right now.

**Comment by jgranja24** [comment]
This should be fixed now https://github.com/GreenleafLab/ArchR/issues/409
