### ISSUE TITLE
Warning before overwriting data in `subsetArchRProject`

### ISSUE THREAD

**Issue by bnprks** [GreenleafLab/ArchR#311]
Calling `subsetArchRProject` will overwrite files in the output directory if there is already an ArchR project stored there. In my case, I forgot to provide the `outputDirectory`, so then quickly ended up with subset projects overwriting each other.

I'd suggest requiring an argument like `force=TRUE` when there is an existing project in `outputDirectory`. 

Overall, it may even be better to stop providing a default value for `outputDirectory` in both `subsetArchRProject` and the `ArchRProject` constructor so it is obvious to users where their project is being stored on disk

**Comment by rcorces** [comment]
This is a good suggestion. Thanks @bnprks

**Comment by jgranja24** [comment]
I added this to the release version -

```
  if(dir.exists(outputDirectory)){
    if(!force){
      stop("outputDirectory exists! Please set force = TRUE to overwrite existing directory!")
    }
  }
```

To install
`devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.0", repos = BiocManager::repositories())
`

I am closing this issue feel free to open a new issue if this does not work.

**Comment by rcorces** [comment]
Might be good to make that message more explicit by including: "forcing overwrite will overwrite any existing ArchRProject in the outputDirectory" or something.
