### ISSUE TITLE
Visualizing matched RNA coverage in plotBrowserTrack()

### ISSUE THREAD

**Issue by RegnerM2015** [GreenleafLab/ArchR#313]
I think it would be beneficial to visualize RNA coverage in the `plotBrowserTrack()` function which now plots coverage for ATAC fragments. Would it be possible to implement something like this in ArchR? This procedure would be similar to deepTools: https://deeptools.readthedocs.io/en/develop/. deepTools essentially converts any BAM file to bigWig for visualization. 

Perhaps it may be more straightforward to plot RNA coverage using deepTools directly. Would there be any specific normalization parameters that would better line up with the normalized coverage used in ArchR's `plotBrowserTrack()`? 

![image](https://user-images.githubusercontent.com/54336249/93108487-d780a300-f680-11ea-9644-20a777e04dd1.png)
Credits: Bioinformatics Facility at the Max Planck Institute for Immunobiology and Epigenetics, Freiburg.

**Comment by rcorces** [comment]
If implemented, it would seem to me that the appropriate solution would be to enable user-supplied bigwigs by adding another option to `plotSummary` (e.g. "userTrack") but this does seem a bit complex to control for all of the crazy things that end-users will try to do I think enabling plotting of *linked* RNA coverage would be more straightforward but I'm not sure if that is what you are asking for.

**Comment by RegnerM2015** [comment]
Hi @rcorces,

I now realize the issue title was poorly worded. 

Yes, that is exactly what I mean! I think it would be helpful to plot the linked RNA coverage to supplement the ATAC coverage information.  It is a bit unorthodox, but I have seen some papers that show coverage tracks for their matched bulk RNA/ATAC-seq. 

Could you point me in the right direction for documentation on `plotSummary/userTrack`? I am having difficulty finding in the User Manual.

**Comment by rcorces** [comment]
Sorry - the "userTrack" doesnt exist - I was suggesting this as a generalizeable solution for users providing their own bigwig. currently, the linked RNA feature you are requesting does not exist in ArchR but I will leave this request open and we will do our best to address it.

**Comment by RegnerM2015** [comment]
Great! Thanks for considering my request and thank you for developing such a cool single-cell software package!

**Comment by jgranja24** [comment]
Matched RNA is now available in the release version see below!

```
#New Release Branch
devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.0", repos = BiocManager::repositories())

library(ArchR)
proj <- getTestProject()
p <- plotBrowserTrack(
	ArchRProj = proj,
    plotSummary = c("bulkTrack", "scTrack", "featureTrack", "loopTrack", "geneTrack"),
    sizes = c(8, 8, 1.5, 3, 4),
	groupBy = "Clusters", 
	geneSymbol = "CD247", 
	useMatrix = NULL,
	upstream = 100000, 
	scCellsMax = 100,
	downstream = 100000
)
plotPDF(p, width = 8, height = 8)

p <- plotBrowserTrack(
	ArchRProj = proj,
    plotSummary = c("bulkTrack", "scTrack", "featureTrack", "loopTrack", "geneTrack"),
    sizes = c(8, 8, 1.5, 3, 4),
	groupBy = "Clusters", 
	geneSymbol = "CD247", 
	useMatrix = "GeneScoreMatrix",
	upstream = 100000, 
	scCellsMax = 100,
	downstream = 100000
)
plotPDF(p, width = 8, height = 8)

if(!file.exists("scRNA-Hematopoiesis-Granja-2019.rds")){
    download.file(
        url = "https://jeffgranja.s3.amazonaws.com/ArchR/TestData/scRNA-Hematopoiesis-Granja-2019.rds",
        destfile = "scRNA-Hematopoiesis-Granja-2019.rds"
    )
}

seRNA <- readRDS("scRNA-Hematopoiesis-Granja-2019.rds")

proj <- addGeneIntegrationMatrix(
    ArchRProj = proj, 
    useMatrix = "GeneScoreMatrix",
    matrixName = "GeneIntegrationMatrix",
    reducedDims = "IterativeLSI",
    seRNA = seRNA,
    addToArrow = TRUE,
    verbose = FALSE,
    groupRNA = "BioClassification",
    nameCell = "predictedCell",
    nameGroup = "predictedGroup",
    nameScore = "predictedScore",
    force = TRUE
)

p <- plotBrowserTrack(
	ArchRProj = proj,
    plotSummary = c("bulkTrack", "scTrack", "featureTrack", "loopTrack", "geneTrack"),
    sizes = c(8, 8, 1.5, 3, 4),
	groupBy = "Clusters", 
	geneSymbol = "CD247", 
	useMatrix = "GeneIntegrationMatrix",
	upstream = 100000, 
	scCellsMax = 100,
	downstream = 100000
)
plotPDF(p, width = 8, height = 8)

```

<img width="899" alt="Screen Shot 2020-10-27 at 9 52 19 PM" src="https://user-images.githubusercontent.com/25017655/97392401-ede46600-189e-11eb-9eff-1cc1d78cd967.png">


<img width="902" alt="Screen Shot 2020-10-27 at 9 52 25 PM" src="https://user-images.githubusercontent.com/25017655/97392410-f0df5680-189e-11eb-9d13-d2ab043f6e7c.png">


<img width="884" alt="Screen Shot 2020-10-27 at 9 52 31 PM" src="https://user-images.githubusercontent.com/25017655/97392418-f50b7400-189e-11eb-8ce7-a3414849412c.png">

**Comment by jgranja24** [comment]
I am closing this issue, feel free to open a new issue or further comment on this issue!
