### ISSUE TITLE
Error Could not identify keytype for annotation format!

### ISSUE THREAD

**Issue by gjcveenstra** [GreenleafLab/ArchR#318]
I am trying to get a custom reference to work with ArchR. I generated BSgenome, TxDb, OrgDb objects. 
I got an error in createGeneAnnotation: 
**Error in createGeneAnnotation(TxDb = xt_TxDb, OrgDb = xt_OrgDb) :
  Could not identify keytype for annotation format!**

The keytypes in TxDb seem to be normal
> keytypes(xt_TxDb)
[1] "CDSID"    "CDSNAME"  "EXONID"   "EXONNAME" "GENEID"   "TXID"     "TXNAME"

What is the offending issue? 

Code:
> library(ArchR)
> addArchRThreads(threads = 16)
> addArchRChrPrefix(chrPrefix = FALSE)

> library(BSgenome.Xtropicalis.Xenbase.xt9m3)
> genomeAnnotation <- createGenomeAnnotation(genome = BSgenome.Xtropicalis.Xenbase.xt9m3)

> library(AnnotationDbi)
> xt_TxDb <- loadDb("/home/gertjanv/genomes/xt9_0_m3/bioconductor/TxDb.Xtropicalis.Xenbase.xt9m3")

> library(org.Xtropicalis.eg.db)
> xt_OrgDb <- org.Xtropicalis.eg.db

> geneAnnotation <- createGeneAnnotation(TxDb = xt_TxDb, OrgDb = xt_OrgDb)
Getting Genes..
Error in createGeneAnnotation(TxDb = xt_TxDb, OrgDb = xt_OrgDb) :
  Could not identify keytype for annotation format!

**Comment by rcorces** [comment]
We dont have a lot of experience working with custom genomes so it would help us if you troubleshoot this on your end.
Could you try manually stepping through the code for `createGeneAnnotation()` and see exactly where the problem occurs? The problem is occuring in this section - https://github.com/GreenleafLab/ArchR/blob/5f855d7b7ff3f57eb0d28f312c5ea5d373d27ebd/R/AnnotationGenome.R#L114

probably in one of the calls to `mapIds`?

**Comment by gjcveenstra** [comment]
Thank you for your quick response.

Indeed, neither call to mapIds works, they both (ENTREZID and ENSEMBL) throw an error:
>genes <- GenomicFeatures::genes(xt_TxDb)
>AnnotationDbi::mapIds(xt_OrgDb, keys = mcols(genes)$gene_id, column = "SYMBOL", keytype = "ENTREZID", multiVals = "first")
Error in .testForValidKeys(x, keys, keytype, fks) :
  None of the keys entered are valid keys for 'ENTREZID'. Please use the keys method to see a listing of valid arguments.

Same for ENSEMBL.
As a result, isEntrez and isEnsembl are both FALSE, resulting in the error message **Could not identify keytype for annotation format!**

The ENTREZIDs seem valid (I checked some of them; see code below). 

I have a couple of questions:
* Is mapIds statement meant to match the ENTREZIDs to the gene_ids in TxDb genes based on the gene symbols present in both (mcols(genes)$gene_id from TxDb and SYMBOL from OrgDb)? Some but the gene symbols, but not all of them can be matched between TxDb and OrgDb (see code below). If it is gene symbol matching, does this mean that all of them should match, otherwise it will throw an error?
* Would it be possible to continue with ArchR, even if integration with genome and annotation resources at Ensembl or NCBI is absent? Now it just throws an error and stops.

#===============
#Gene symbols in TxDb
> head(mcols(genes)$gene_id)
[1] "42Sp43"               "42Sp50"               "6330408a02rik-like.1"
[4] "6330408a02rik-like.2" "AK6"                  "ATP6"
> tail(mcols(genes)$gene_id)
[1] "zw10"      "zwilch"    "zxdc"      "zyg11b"    "zzef1"     "zzz3-like"

#Gene symbols in OrgDb, some match, some don't
> head(keys(xt_OrgDb, keytype="SYMBOL"))
[1] "1a11"          "42Sp43"        "42Sp50"        "9030611n15rik"
[5] "ATP6"          "ATP8"
> tail(keys(xt_OrgDb, keytype="SYMBOL"))
[1] "zwilch" "zxdc"   "zyg11b" "zyx"    "zzef1"  "zzz3"

#These are valid ENTREZIDs
> head(keys(xt_OrgDb,keytype="ENTREZID"))
[1] "100036593" "100036594" "100036595" "100036596" "100036597" "100036598"

**Comment by rcorces** [comment]
I think this speaks to a larger issue with custom genomes. We enabled custom genomes because enough users were interested, but since we dont have experience outside of human and mouse we have trouble anticipating all of the different problems that people will encounter.
Flagging @jgranja24 to address this but his response wont be swift as he is working on other aspects of ArchR.

**Comment by gjcveenstra** [comment]
I looked further into this, and have a **question / potential feature request for ArchR**:
* For custom genomes, is it possible to forego integration with NCBI / Ensembl annotation resources, without a requirement for `OrgDb`, and just pass a valid `BSgenome` and `TxDb`  to ArchR? A lot of the functionality may just depend on having a genome and gene annotation (without linking the genes to other databases).

Reason for asking is that many folks who work with less common organisms, use resources which are not (yet) at NCBI / Ensembl (home-made, consortia etc.). So it is not uncommon to have a perfectly valid GFF3 file along with a good genome, but without Entrez or Ensemble IDs to link the genes to other resources. Most of the functionality of ArchR may not depend on these other resources, is that correct?

Another reason is that the tools to generate a `TxDb` and `OrgDb` are a bit quirky (see below). In the end I found another version of the genome and gene annotation (not the one I intended to use), for which I got it working in the end:

For use with ArchR, `TxDb` should contain either an Entrez ID (NCBI) or Ensembl ID, to fill a `gene_id` field as meta data for genes. 
The GFF3 file should contain this as an attribute in field 9.
In principle, the `dbxrefTag` parameter in the call to `makeTxDbFromGFF` can be used to control which identifier is passed as `gene_id` to `TxDb`. Default seems to be the `Name` attribute (not documented), which according to GFF3 standards should be a common name of the feature, in other words a gene symbol, not the Entrez ID. Using `dbxrefTag` would solve this supposedly. For example:

>xt_TxDb <- makeTxDbFromGFF("/home/gertjanv/genomes/xt10_0/XENTR_10.0_GCF.gff3", format="auto", organism="Xenopus tropicalis", chrominfo = df_chrominfo, dbxrefTag = "GeneID")

However, it passes the `GeneID:` string with the actual Entrez ID to `gene_id`, which causes it to not match the actual ID (which is  a number). It looks like this:

>genes(xt_TxDb)
GRanges object with 28779 ranges and 1 metadata column:
                   seqnames              ranges strand |          gene_id
                      <Rle>           <IRanges>  <Rle> |      <character>
  GeneID:100036593     Chr2   86432435-86447834      + | GeneID:100036593
  GeneID:100036594     Chr3 102561834-102580957      - | GeneID:100036594

There are several potential solutions:
* manipulate the `TxDb`, remove "GeneID:" from all fields (Genes, transcripts etc.)
* manipulate the GFF3, to contain the Entrez ID in the field 9 `Name=` attribute

**Comment by rcorces** [comment]
There are a lot of downstream functionalities of ArchR that depend on the OrgDb and TxDb annotations - mostly around gene-based analyses. We need to have some consistent framework to enforce and the chosen one makes the most sense for the vast majority of users.

I think the most plausible solution is to try to cobble together better documentation that makes the requirements clear for creating non-standard genome annotations to use with ArchR. But our current thinking is that this is an edge case and that 99% of users are in human or mouse. We have a lot of functionality (not to mention other bugs) that we are busy trying to fix and the harsh reality is that it will take some time for this to rise to top of the importance list.

What we do welcome is input from users of non-standard genomes to help us improve the documentation so your comments are very helpful. Hope that makes sense.

**Comment by gjcveenstra** [comment]
Just for clarification: Of course one needs gene annotation for ATAC analyses. In the case of ArchR, my understanding is that you get the relevant coordinates out of TxDb.

So my comment only referred to the need for. If OrgDb could be made optional, that would be much help to research on non-human/mouse organisms.

But I understand where you are coming from, and I appreciate the time and effort you spend on making tools useful for others.

Best wishes. GJ

**Comment by rcorces** [comment]
@jgranja24 knows better than I do all of the places where OrgDb info might be used. I'll let him comment on that particular point.

**Comment by abbeythorpe** [comment]
I just came across the same error while trying to use ArchR for arabidopsis. I ended up being able to use the orgDb and TxDb I started with by identifying the orgDb keytype that matched the TxDb gene_id and then using "annostyle" to point it to that column instead of Entrez or Ensembl. annostyle wasn't in the ArchR documentation but I noticed it in the source code.

```
>head(keys(org.At.tair.db, keytype = "ENTREZID"))
[1] "839580" "839569" "839321" "839574" "839579" "839341"
```

```
>genes(TxDb.Athalian.BioMart.plantsmart28)
GRanges object with 33602 ranges and 1 metadata column:
            seqnames        ranges strand |     gene_id
               <Rle>     <IRanges> <Rle> | <character>
  AT1G01010        1     3631-5899      + |   AT1G01010
  AT1G01020        1     5928-8737     - |   AT1G01020
  AT1G01030        1   11649-13714       - |   AT1G01030
  AT1G01040        1   23146-31227       + |   AT1G01040
```

These didn't match. But I looked through the orgDb keytypes and found this:

```
>head(keys(org.At.tair.db, keytype = "TAIR"))
[1] "AT1G01010" "AT1G01020" "AT1G01030" "AT1G01040" "AT1G01050"
"AT1G01050"
```
I changed the call to createGeneAnnotation to use "TAIR" instead of defaulting to Entrez:
`geneAnnotation <- createGeneAnnotation(TxDb = TxDb.Athaliana.BioMart.plantsmart28, OrgDb = org.At.tair.db, annoStyle = "TAIR")`

My createArrowFiles() call is still running but it seems like this worked so far.

**Comment by 304243504** [comment]
@abbeythorpe How do you fix that? I came in the same problem
