### ISSUE TITLE
Computing pvalue for Peak2Gene links and Co-accessibility 

### ISSUE THREAD

**Issue by RegnerM2015** [GreenleafLab/ArchR#320]
Hi @rcorces and @jgranja24 ,

I would like to be able to compute the null distribution of correlation values in Peak2Gene links and co-accessibility analysis. For every peak-gene pair, you would sample 100 background peaks matched for GC content and fragment count and correlate each with the gene of interest. 

I was looking at the source code for Peak2Gene linkage analysis:

```
.logDiffTime(main="Computing Correlations", t1=tstart, verbose=verbose, logFile=logFile)
  o$Correlation <- rowCorCpp(as.integer(o$A), as.integer(o$B), assay(seATAC), assay(seRNA))
  o$VarAssayA <- .getQuantiles(matrixStats::rowVars(assay(seATAC)))[o$A]
  o$VarAssayB <- .getQuantiles(matrixStats::rowVars(assay(seRNA)))[o$B]
  o$TStat <- (o$Correlation / sqrt((1-o$Correlation^2)/(ncol(seATAC)-2))) #T-statistic P-value
  o$Pval <- 2*pt(-abs(o$TStat), ncol(seATAC) - 2)
  o$FDR <- p.adjust(o$Pval, method = "fdr")
  #o$EmpPval <- 2*pnorm(-abs(((o$Correlation - mean(nullCor[[2]])) / sd(nullCor[[2]]))))
  #o$EmpFDR <- p.adjust(o$EmpPval, method = "fdr")
```

It looks like the empirical FDR is commented out in the source code. 

I think it would be awesome to add an argument to addPeak2GeneLinks that allows the user to compute the null correlation and empirical pvalue. 

Thanks for your hard work and commitment to developing ArchR!

**Comment by jgranja24** [comment]
Hi @RegnerM2015 yeah I wasn't getting the best results when doing the other method. I can enable it in the next release.

**Comment by jgranja24** [comment]
I just added a param to `addEmpiricalPval` to `addPeak2GeneLinks` in the new release version.

**Comment by rcorces** [comment]
@RegnerM2015 - if this provides a suitable solution for your suggestion, feel free to close.

**Comment by RegnerM2015** [comment]
I have one more question before closing, are the background peaks used in this calculation matched for GC content and accessibility?

**Comment by jgranja24** [comment]
The background correlations are correlating peaks to genes not on the same chromosome. Its not a super sophisticated model. However, statistics with this type of analysis are really challenging. I strongly suggest using cutoffs based on variance and correlation. Being a higher variance and correlation suggests that this link is not random noise. If you come up with something better I am happy to implement it.

**Comment by RegnerM2015** [comment]
Thanks! I will take this into consideration.

**Comment by jgranja24** [comment]
I additionally just added the tstat correlation test to addCoAcessibility. Hopefully that helps.
