### ISSUE TITLE
Error creating pseudoBulk replicates

### ISSUE THREAD

**Issue by yankiven** [GreenleafLab/ArchR#322]
Hello developer:  

I built my own genome locally,I have successfully run the tools until I have to create pseudo bulk profiles.  
my genome info and error info(**chr01 Error in BSgenome[[availableChr[x]]] : no such sequence**) is as below:
================================================================
```
> genomeAnnotation$chromSizes
GRanges object with 12 ranges and 0 metadata columns:
       seqnames     ranges strand
          <Rle>  <IRanges>  <Rle>
   [1]    chr01 1-43270923      *
   [2]    chr02 1-35937250      *
   [3]    chr03 1-36413819      *
   [4]    chr04 1-35502694      *
   [5]    chr05 1-29958434      *
   ...      ...        ...    ...
   [8]    chr08 1-28443022      *
   [9]    chr09 1-23012720      *
  [10]    chr10 1-23207287      *
  [11]    chr11 1-29021106      *
  [12]    chr12 1-27531856      *
  -------
  seqinfo: 12 sequences from an unspecified genome; no seqlengthsv
```
================================================================
```
> projHeme3 <- addGroupCoverages(ArchRProj = myproJ1, 
+                                groupBy = "Clusters")
ArchR logging to : ArchRLogs\ArchR-addGroupCoverages-4b747efc7f-Date-2020-09-24_Time-16-43-23.log
If there is an issue, please report to github with logFile!
2020-09-24 16:43:23 : Creating Coverage Files!, 0.014 mins elapsed.
2020-09-24 16:43:23 : Batch Execution w/ safelapply!, 0.014 mins elapsed.
2020-09-24 16:43:23 : Group C1._.Rep1 (1 of 4) : Creating Group Coverage File : C1._.Rep1.insertions.coverage.h5, 0.014 mins elapsed.
2020-09-24 16:43:31 : Group C1._.Rep2 (2 of 4) : Creating Group Coverage File : C1._.Rep2.insertions.coverage.h5, 0.144 mins elapsed.
2020-09-24 16:43:38 : Group C2._.Rep1 (3 of 4) : Creating Group Coverage File : C2._.Rep1.insertions.coverage.h5, 0.247 mins elapsed.
2020-09-24 16:43:45 : Group C2._.Rep2 (4 of 4) : Creating Group Coverage File : C2._.Rep2.insertions.coverage.h5, 0.369 mins elapsed.
2020-09-24 16:43:51 : Adding Kmer Bias to Coverage Files!, 0.473 mins elapsed.
chr01 Error in BSgenome[[availableChr[x]]] : no such sequence
```

**Comment by rcorces** [comment]
If you think the solution that you found might help other users, feel free to post it here.

**Comment by yankiven** [comment]
The cause of this error is my own.  If you are constructing a **Custom** genome and this problem also occurs, you can first check your genome information.
- for example
```
eval(parse(text = "BSgenome.Mmusculus.yourCustom.mm10"))
```
Chromosome name in the outputs, 
```
Mouse genome:
# organism: Mus musculus (Mouse)
# provider: UCSC
# provider version: mm10
# release date: Dec. 2011
# release name: Genome Reference Consortium GRCm38
# 66 sequences:
#   chr1                 chr2                 chr3                
#   chr4                 chr5                 chr6                
#   chr7                 chr8                 chr9                
#   chr10                chr11                chr12               
#   chr13                chr14                chr15               
#   ...                  ...                  ...                 
#   chrUn_GL456372       chrUn_GL456378       chrUn_GL456379      
#   chrUn_GL456381       chrUn_GL456382       chrUn_GL456383      
#   chrUn_GL456385       chrUn_GL456387       chrUn_GL456389      
#   chrUn_GL456390       chrUn_GL456392       chrUn_GL456393      
#   chrUn_GL456394       chrUn_GL456396       chrUn_JH584304      
# (use 'seqnames()' to see all the sequence names, use the '$' or '[[' operator
# to access a given sequence)
```
 If your chromosome name is chr01, but the chromosome name in your BSgenome is chr1, then this error will be reported

**Comment by chen-zhan** [comment]
> The cause of this error is my own. If you are constructing a **Custom** genome and this problem also occurs, you can first check your genome information.
> 
> * for example
> 
> ```
> eval(parse(text = "BSgenome.Mmusculus.yourCustom.mm10"))
> ```
> 
> Chromosome name in the outputs,
> 
> ```
> Mouse genome:
> # organism: Mus musculus (Mouse)
> # provider: UCSC
> # provider version: mm10
> # release date: Dec. 2011
> # release name: Genome Reference Consortium GRCm38
> # 66 sequences:
> #   chr1                 chr2                 chr3                
> #   chr4                 chr5                 chr6                
> #   chr7                 chr8                 chr9                
> #   chr10                chr11                chr12               
> #   chr13                chr14                chr15               
> #   ...                  ...                  ...                 
> #   chrUn_GL456372       chrUn_GL456378       chrUn_GL456379      
> #   chrUn_GL456381       chrUn_GL456382       chrUn_GL456383      
> #   chrUn_GL456385       chrUn_GL456387       chrUn_GL456389      
> #   chrUn_GL456390       chrUn_GL456392       chrUn_GL456393      
> #   chrUn_GL456394       chrUn_GL456396       chrUn_JH584304      
> # (use 'seqnames()' to see all the sequence names, use the '$' or '[[' operator
> # to access a given sequence)
> ```
> 
> If your chromosome name is chr01, but the chromosome name in your BSgenome is chr1, then this error will be reported

Hi, how do you to solve this question. Do you updata the genomeAnnotation or remake the arrow file?

**Comment by danli349** [comment]
@chen-zhan @wenkaiyan-kevin @rcorces 
Hello :
I also meet this error when I call `addGroupCoverages(ArchRProj = projHeme3, groupBy = "Clusters")`.
The chromosome names in my ArchR project are "NCBI" style, they all don't have `chr` in the beginning. 
How can I add `chr` to the chromosome names in my ArchR project?
Thanks a lot
