### ISSUE TITLE
dimension using in addIterativeLSI

### ISSUE THREAD

**Issue by Dragonlongzhilin** [GreenleafLab/ArchR#323]
In the singular value decomposition (SVD)  method,  1st dimension is correlated with the depth of cell reads. I read the document of ArchR and found the param of "dimsToUse" is set 1:30. If I used the function of "addIterativeLSI" to reduce dimension, should I change the value to 2:30?

**Comment by jgranja24** [comment]
Sorry for the delayed response (crazy times) -

We designed ArchR to handle this issue so you dont need to do anything. We agree that we should add a little extra documentation in the book tutorial.

see `corCutOff` in functions such as `addUMAP` which tests how correlated each dimension is to the depth of cell reads. Only in extreme cases is this filtration needed as this rarely is above 0.75 unless the data is super homogenous.

Hope this is helpful!

**Comment by jgranja24** [comment]
I am closing this issue, If you have any more issues feel free to open another issue! Hope your analysis goes well!
