### ISSUE TITLE
Changing the row order on motif enrichment heat maps?

### ISSUE THREAD

**Issue by edt711** [GreenleafLab/ArchR#329]
Hi ArchR team,

Thank you for putting together such an awesome program!! When making heat maps of motif enrichments, is there any way to manually set/change the order of the rows (which correspond to the clusters/cell types)? I know that you can set `binaryClusterRows = FALSE` in `plotEnrichHeatmap`, but then it just defaults to an alphabetical order. Is there a way to specify the order in which the clusters appear on the heat map, either through an ArchR command or via ComplexHeatmap?

Thanks,
Eric

**Comment by rcorces** [comment]
To the best of my knowledge this is not yet possible but is a good suggestion. I've added the enhancement label and we will look into it.

**Comment by edt711** [comment]
Awesome, thank you so much!
