### ISSUE TITLE
How to creat a psuedo bulk peak profile for each smaple in each cluster?

### ISSUE THREAD

**Issue by CSBioAzim** [GreenleafLab/ArchR#335]
Hi,

I'm analyzing multiple samples across different conditions using Archer. I would like to create a bulk peak accessibility profile for each sample (aggregate all the cells in each sample for each cluster).
How can I do this in Archer?

**Comment by rcorces** [comment]
Depends on what you mean by "bulk peak accessibility profile". Please clarify.

**Comment by jgranja24** [comment]
Yeah if you want aggregated matrices see `getGroupSE`

**Comment by jgranja24** [comment]
Im closing this assuming `getGroupSE` which creates a bulk accessibility profile for peaks, deviations, gene scores works.
