### ISSUE TITLE
Allow additional user-supplied feature tracks in plotBrowserTrack

### ISSUE THREAD

**Issue by j-andrews7** [GreenleafLab/ArchR#337]
**Describe the problem that your feature request would address.**
Often, plotting publicly available or custom browser tracks are very useful for providing context surrounding the ATAC-seq data, e.g. ChIP-seq peaks, etc. Currently, the only way to do this with ArchR is to export the pseudobulks as bigwigs (#47, #46, #54 ) and visualize in an external browser.

**Describe the solution you'd like**
The ability to add simple BED files/additional granges objects to an ArchR project and include them in the `plotBrowserTrack` output would be both wildly convenient and likely very popular. This is touched upon in #313 for bigwigs. Allowing multiple `featureTrack`s in `plotSummary` and corresponding feature sets fed to `features` is likely the most straightforward implementation from the user perspective.

**Describe alternatives you've considered**
As mentioned in #313, an alternative is to make a new type of track (`userTrack`) that is more flexible on inputs, though @rcorces rightfully mentions that could get pretty complex to maintain/implement.

**Comment by jgranja24** [comment]
Im a little confused what you mean here. You can use as input a list of GRanges for visualization into features.

For example :
`features = GRangesList(TrackA = GRanges, TrackB = GRanges)`

I think this is what you are desiring?

**Comment by j-andrews7** [comment]
Oh, that does seem likely. Is this documented anywhere? I'll give it a test later today.

**Comment by jgranja24** [comment]
Hi @j-andrews7,

Has your issue been resolved?

Best

Jeff

**Comment by j-andrews7** [comment]
Yes, sorry. This works well. Is there any way to set the order of how the peaksets are plotted? I'm not really sure how that's determined, but changing the order of the `GRangesList` doesn't seem to affect it.

**Comment by jgranja24** [comment]
Its just a standard ggplot factor ordering but I now made it where the order is based on the list order. 

i.e

`featureO$name <- factor(paste0(featureO$name), levels=names(featureList))`

This update will be present in the release branch

`devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.0", repos = BiocManager::repositories())
`
PS whenever dealing with factor ordering consider adding a numeric prior to your string ie 1.ClusterA, 2.ClusterB.

Best

Jeff

**Comment by j-andrews7** [comment]
Excellent, thanks. Where possible, I don't like using the numeric prefixes, as it messes with the aesthetic and means additional editing after the fact. 

Closing this, thanks for the quick answers.

**Comment by jgranja24** [comment]
No worries I just do this whenever packages dont have the flexibility or i am lazy and just will deal with it in AI.

Best

Jeff
