### ISSUE TITLE
Very minor: Typo in addDoubletScores() error

### ISSUE THREAD

**Issue by hypercompetent** [GreenleafLab/ArchR#339]
I just spotted this when working with a super-small test dataset:

contniue -> continue

https://github.com/GreenleafLab/ArchR/blob/02aa9202857807e63037a6abd4472d0b65eebfad/R/DoubletsScores.R#L614

Cheers,
-Lucas

**Comment by jgranja24** [comment]
Fixed this in the new release version! Thanks!
