### ISSUE TITLE
Returning loops as a GR object?

### ISSUE THREAD

**Issue by ivanferrreira** [GreenleafLab/ArchR#341]
Hello,

I'm trying to get the loop information from the peak2gene linkages so that they can be used to properly annotate the differentially accessible distal peaks (instead of using the nearestGene annotation from the PeakMatrix) - is there an easy way to do so? 

I tried using getPeak2GeneLinks, which gives the scores but not the associated promoters.

Thanks,
Ivan

**Comment by jgranja24** [comment]
Hi @ivanferrreira,

Has your issue been resolved? 

Best

Jeff

**Comment by ivanferrreira** [comment]
Hi,

Thanks for your help! returnLoops allow me to extract the coordinates of the interacting peaks, but I had to annotate the coordinates of each of these associations to get the gene annotations back. 

Issue resolved - will just leave here a suggestion to return the gene annotations (nearestGene) for peaks annotated as promoters, making it much easier to identify the annotations of distal peaks interacting with such promoters. 

All the best,
Ivan
