### ISSUE TITLE
Unable to incorporate "ENCODETFBS" using addArchRAnnotations(ArchRProj = proj, collection = "EncodeTFBS")) while using mm10 ref genome

### ISSUE THREAD

**Issue by jeremybjelajac** [GreenleafLab/ArchR#342]
Before you submit this issue please update ArchR to the latest version and make sure that this issue has not already been fixed in the latest release. ArchR is in *beta* and we will fix problems as they arise. To update ArchR:

devtools::install_github("GreenleafLab/ArchR", ref="master", repos = BiocManager::repositories())

If your issue persists, then please submit this bug report.

PLEASE FILL OUT THE RELEVANT INFORMATION AND DELETE THE UNUSED PORTIONS OF THIS ISSUE TEMPLATE.

**Attach your log file**
ArchR has a built-in logging functionality for all complex functions. You MUST attach your log file (indicated in the console output) to this issue. Just drag and drop it here.

[ArchR-addArchRAnnotations-27230b70888-Date-2020-10-14_Time-12-04-31.log](https://github.com/GreenleafLab/ArchR/files/5380336/ArchR-addArchRAnnotations-27230b70888-Date-2020-10-14_Time-12-04-31.log)

**Describe the bug**
I have run into a slight issue during my analysis when attempting to use addArchRannotations() to integrate TF binding motifs into my ArchR project (using mm10 as my reference, which seems to be the issue). 

I attempted to utilize "EncodeTFBS" as my collection to annotate my project, but I was met with the error below, which seems to indicate that EncodeTFBS is not usable with ArchR projects that utilize mm10 as a reference genome. Have you seen this issue before/do you have a recommendation for an alternative collection to use?

>proj_peaks_withAnnotation <- addArchRAnnotations(ArchRProj = proj_peaks, collection = "EncodeTFBS") 

ArchR logging to : ArchRLogs/ArchR-addArchRAnnotations-2724e6d6f9e-Date-2020-10-14_Time-11-04-06.logIf there is an issue, please report to github with logFile!Error in addArchRAnnotations(ArchRProj = proj_peaks) :   ArchR mm10 annotations not yet supported! Try LOLA for now!

**To Reproduce**
I could not reproduce with the tutorial because I used a different reference genome

**Expected behavior**
 I expected this function to create a binarized representation of the overlap between all marker peaks and all ENCODE TFBS.

**Screenshots**
<img width="802" alt="Screen Shot 2020-10-14 at 12 07 32 PM" src="https://user-images.githubusercontent.com/72887219/96034067-d96f8a80-0e15-11eb-8bc8-46f56d1cf50a.png">

**Session Info**
N/A

**Additional context**
N/A

**Comment by jgranja24** [comment]
Hi @jeremybjelajac,

If you look further at the param descriptions -
```
#' @param db A string indicating the database or a path to a database to use for peak annotation. Options include ArchR,
#' LOLA, and a valid path to a file of class `ArchRAnno`.
#' @param collection A string indicating which collection within the database to collect for annotation. 
#' For ArchR, options are "ATAC", "EncodeTFBS", "CistromeTFBS", or "Codex".
#' For LOLA, options include "EncodeTFBS" "CistromeTFBS", "CistromeEpigenome", "Codex", or "SheffieldDnase".
#' If supplying a custom `ArchRAnno` file please select a valid collection from within that database.
```

All you need to do i believe is the following -

`proj_peaks_withAnnotation <- addArchRAnnotations(ArchRProj = proj_peaks, db = "Lola", collection = "EncodeTFBS")
`

Best

Jeff

**Comment by jgranja24** [comment]
I agree this is confusing because ArchR annotations are only for hg19 and hg38 I believe. While they include EncodeTFBS, so does LOLA which has annotations for mm9 and mm10. ArchR annotations are just a copy of LOLA annotations for these annotation sets so using directly LOLA will solve your problem.

**Comment by IqRaZaFaR16** [comment]
Merged.proj2  <- addArchRAnnotations(ArchRProj = Merged.proj2, db = "LOLA", collection = "EncodeTFBS")
ArchR logging to : ArchRLogs/ArchR-addArchRAnnotations-1aaf5515fa3423-Date-2024-12-05_Time-15-51-06.915774.log
If there is an issue, please report to github with logFile!
Error in H5Fopen(file, flags = flags, fapl = fapl, native = native) :
  HDF5. File accessibility. Unable to open file.
>

**Comment by immanuelazn** [comment]
Hi @IqRaZaFaR16, please refer to my previous answer to you where you had a separate issue.  Additionally, please refrain from adding non-related comments to these issues, as it is helpful for other users to be able to see focused threads.  If you cannot find an issue related to the one you are facing, please create a new issue.  Thanks!

**Comment by IqRaZaFaR16** [comment]
Hello sorry for disturbing you again i have installed ArchR version 1.0.3 and also change my seurat and seuratobject verson but encountry file while 

Merged.proj2 <- addArchRAnnotations(ArchRProj= Merged.proj2, db="LOLA",collection="EncodeTFBS")

even i have installed library(LOLA) also unable multthreadng while creating arrow files

#############################filter low quality & generate arrow files############################

ArrowFiles <- createArrowFiles(

  inputFiles = frag.files,

  sampleNames = c("E18.2", "P0.2", "P3.2", "P6.2"),

  minTSS = 4,

  minFrags = 1000,

  addTileMat = TRUE,

  addGeneScoreMat = TRUE,   # Ensure this is set to TRUE

  excludeChr = c("chrM"),

  force = TRUE,

  subThreading = FALSE       # Disable multithreading

)




Please guide me how i can fix it. 





-----Original Messages-----
From:"Immanuel Abdi" ***@***.***>
Send time:Thursday, 12/05/2024 16:36:27
To: GreenleafLab/ArchR ***@***.***>
Cc: IqRaZaFaR16 ***@***.***>, Mention ***@***.***>
Subject: Re: [GreenleafLab/ArchR] Unable to incorporate "ENCODETFBS" using addArchRAnnotations(ArchRProj = proj, collection = "EncodeTFBS")) while using mm10 ref genome (#342)






Hi @IqRaZaFaR16, please refer to my previous answer to you where you had a separate issue. Additionally, please refrain from adding non-related comments to these issues, as it is helpful for other users to be able to see focused threads. If you cannot find an issue related to the one you are facing, please create a new issue. Thanks!
