### ISSUE TITLE
bam input

### ISSUE THREAD

**Issue by rojinsafavi** [GreenleafLab/ArchR#343]
Hello,

I am working with a non 10X ATAC dataset, and I was wondering if ArchR is capable of taking the bam files as input?

Thank you!

**Comment by rcorces** [comment]
This isnt super-well documented (we're working on it). But yes, `createArrowFiles()` can take BAM as input - check the param options. This issue might also help https://github.com/GreenleafLab/ArchR/issues/292

Close if this answers your question

**Comment by jgranja24** [comment]
Hi @rojinsafavi,

Are you still having difficulties?

**Comment by rojinsafavi** [comment]
Actually yes. So I am using a bam file generated from paired-seq tech. And it seems that reads are single-ended. And it seems that ArchR is no able to obtain fragments


```
Using GeneAnnotation set by addArchRGenome(Mm10)!

Using GeneAnnotation set by addArchRGenome(Mm10)!

ArchR logging to : ArchRLogs/ArchR-createArrows-3c29554455edf-Date-2020-10-20_Time-16-42-03.log
If there is an issue, please report to github with logFile!

Cleaning Temporary Files

2020-10-20 16:42:04 : Batch Execution w/ safelapply!, 0 mins elapsed.

(VIB_1 : 1 of 1) Determining Arrow Method to use!

2020-10-20 16:42:04 : (VIB_1 : 1 of 1) Reading In Fragments from inputFiles (readMethod = bam), 0.003 mins elapsed.

2020-10-20 16:42:04 : (VIB_1 : 1 of 1) Tabix Bam To Temporary File, 0.003 mins elapsed.

2020-10-20 16:42:16 : (VIB_1 : 1 of 1) Reading BamFile 10 Percent, 0.199 mins elapsed.

2020-10-20 16:42:26 : (VIB_1 : 1 of 1) Reading BamFile 19 Percent, 0.356 mins elapsed.

2020-10-20 16:42:36 : (VIB_1 : 1 of 1) Reading BamFile 29 Percent, 0.524 mins elapsed.

2020-10-20 16:42:44 : (VIB_1 : 1 of 1) Reading BamFile 38 Percent, 0.668 mins elapsed.

2020-10-20 16:42:53 : (VIB_1 : 1 of 1) Reading BamFile 48 Percent, 0.819 mins elapsed.

2020-10-20 16:43:02 : (VIB_1 : 1 of 1) Reading BamFile 57 Percent, 0.969 mins elapsed.

2020-10-20 16:43:10 : (VIB_1 : 1 of 1) Reading BamFile 67 Percent, 1.099 mins elapsed.

2020-10-20 16:43:17 : (VIB_1 : 1 of 1) Reading BamFile 76 Percent, 1.21 mins elapsed.

2020-10-20 16:43:23 : (VIB_1 : 1 of 1) Reading BamFile 86 Percent, 1.313 mins elapsed.

2020-10-20 16:43:28 : (VIB_1 : 1 of 1) Reading BamFile 95 Percent, 1.395 mins elapsed.

No fragments found!


************************************************************
2020-10-20 16:43:30 : ERROR Found in .bamToTmp for (VIB_1 : 1 of 1) 
LogFile = ArchRLogs/ArchR-createArrows-3c29554455edf-Date-2020-10-20_Time-16-42-03.log

<simpleError: 
>

************************************************************

createArrowFiles has encountered an error, checking if any ArrowFiles completed..

2020-10-20 16:43:30 : 

ArchR logging successful to : ArchRLogs/ArchR-createArrows-3c29554455edf-Date-2020-10-20_Time-16-42-03.log

Error in ArrowFiles[1] <- createArrowFiles(inputFiles = inputBam[1], sampleNames = names(inputBam)[1], : object 'ArrowFiles' not found
Traceback:


```

**Comment by jgranja24** [comment]
Umm what kind of tech? ATAC-seq is **always** paired-end.

**Comment by rojinsafavi** [comment]
[ArchR-createArrows-3c29554455edf-Date-2020-10-20_Time-16-42-03.log](https://github.com/GreenleafLab/ArchR/files/5412307/ArchR-createArrows-3c29554455edf-Date-2020-10-20_Time-16-42-03.log)
 I attached the log file. The data is from 

this is the paper that I'm using its data :
https://www.nature.com/articles/s41594-019-0323-x

and this is what they  said regarding the dataset
"As you can see in Fig.1a and Methods section, Paired-seq used Read2 for cellular barcodes and only Read1 is used for mapping to the genome, so the bam file is single-ended read alignments file"

And I assume that means a single-ended sequencing?

**Comment by jgranja24** [comment]
Hi @rojinsafavi,

Ive been looking into this and ultimately this is not something I can support at this time. This is extremely challenging to account for such a custom analysis (see below). The bams contain both ATAC and RNA data. We support the new 10x multiome kit, but this is much more involved compared to that.  

Reads were first mapped to a reference genome with STAR (version: 2.6.0a61), with the mouse GRCm38 genome. Duplicates were removed based on the mapped position and UMI. For Paired-seq from adult mouse cerebral cortex, we used BC #1 for the identification for the origin of samples: BC #1-01 to 04 and BC #1-05 to 08 to label the two replicates. For Paired-seq from archived mouse fetal forebrain, we also used BC #1 for the identification of the origin of samples: BC #1-01 and 02 for the two replicates of E12.5 forebrain, and BC #01-03 and 04 for the two replicates of E16.5 forebrain. Libraries were sequenced to a 30−70% duplication level. Low-coverage nuclei were removed from further analysis. We used different criteria for libraries of different depths (detailed information in Supplementary Table 3).

Sorry

Jeff

**Comment by jgranja24** [comment]
My suggestion is to figure out how to extract the relevant reads into R (See things like GenomicAlignments and Rsamtools) and save a simple fragments file for input as ArchR. If you can get the reads with cell barcodes into a GRanges object I am happy to help from there. Beyond that, I dont think I can help with too much else. I am closing this issue, if you get the fragments into R and need help making a correct fragments file please open a new issue and I'd be happy to help.

Best

Jeff
