### ISSUE TITLE
ERROR Found in .fastTSSCounts

### ISSUE THREAD

**Issue by Sophiesze** [GreenleafLab/ArchR#344]
Hi GreenLeafLab,
I try to use 9 of my 10x data to run ArchR. One of my samples encountered `ERROR Found in .fastTSSCounts for`.
However, when I tried to input this sample seperately. There wasn't any bug reported. 

Would it be possible for you to look into this? 
Thank you so much.

Sophie

[ArchR-createArrows-56ca25a28024-Date-2020-10-15_Time-11-31-04.log](https://github.com/GreenleafLab/ArchR/files/5383295/ArchR-createArrows-56ca25a28024-Date-2020-10-15_Time-11-31-04.log)
[ArchR-createArrows-4a6c1005e66a-Date-2020-10-15_Time-11-02-19.log](https://github.com/GreenleafLab/ArchR/files/5383296/ArchR-createArrows-4a6c1005e66a-Date-2020-10-15_Time-11-02-19.log)

**Comment by rcorces** [comment]
I havent seen this one before. What if you just use two samples? Does it still happen? If so, try setting `threads = 1` to see if this is an issue with parallelization.

**Comment by jgranja24** [comment]
My guess is that you might have had a job crash which can kinda be sporadic with mclapply unfortunately. My guess is everything is fine besides that. I would look at the TSS by fragments plots. If they look fine then go for it!

Hope that helps

**Comment by Sophiesze** [comment]
Thank you so much!
I tried two samples without errors. I ended up creating Arrowfiles by splitting the samples and then merged into one when I create the ArchRproj.
