### ISSUE TITLE
library(ArchR) hangs after setting default threads

### ISSUE THREAD

**Issue by asmagen** [GreenleafLab/ArchR#353]
Hello,

I'm unable to run ArchR since the initial library call is already setting an arbitrary number of threads that's too high for my system configuration and therefore it's getting stuck for a long while until it fails and crashes.
```
library(ArchR)

Loading required package: BiocParallel

Attaching package: ‘DelayedArray’

The following objects are masked from ‘package:matrixStats’:

    colMaxs, colMins, colRanges, rowMaxs, rowMins, rowRanges

The following objects are masked from ‘package:base’:

    aperm, apply

Loading required package: data.table
data.table 1.12.2 using 8 threads (see ?getDTthreads).  Latest news: r-datatable.com

Attaching package: ‘data.table’

The following object is masked from ‘package:SummarizedExperiment’:

    shift

The following object is masked from ‘package:GenomicRanges’:

    shift

The following object is masked from ‘package:IRanges’:

    shift

The following objects are masked from ‘package:S4Vectors’:

    first, second

Loading required package: Matrix

Attaching package: ‘Matrix’

The following object is masked from ‘package:S4Vectors’:

    expand

Loading required package: rhdf5
Loading required package: magrittr

                                                   / |
                                                 /    \
            .                                  /      |.
            \\\                              /        |.
              \\\                          /           `|.
                \\\                      /              |.
                  \                    /                |\
                  \\#####\           /                  ||
                ==###########>      /                   ||
                 \\##==......\    /                     ||
            ______ =       =|__ /__                     ||      \\\
        ,--' ,----`-,__ ___/'  --,-`-===================##========>
       \               '        ##_______ _____ ,--,__,=##,__   ///
        ,    __==    ___,-,__,--'#'  ==='      `-'    | ##,-/
        -,____,---'       \\####\\________________,--\\_##,/
           ___      .______        ______  __    __  .______      
          /   \     |   _  \      /      ||  |  |  | |   _  \     
         /  ^  \    |  |_)  |    |  ,----'|  |__|  | |  |_)  |    
        /  /_\  \   |      /     |  |     |   __   | |      /     
       /  _____  \  |  |\  \\___ |  `----.|  |  |  | |  |\  \\___.
      /__/     \__\ | _| `._____| \______||__|  |__| | _| `._____|
    
ArchR : Version 0.9.5
For more information see our website : www.ArchRProject.com
If you encounter a bug please report : https://github.com/GreenleafLab/ArchR/issues
Setting default number of Parallel threads to 24.
```

How can this be resolved?

Thank you

**Comment by rcorces** [comment]
I think that is unlikely the cause of the problem. At least the act of setting the cores doesn't **use** multiple cores. Its just setting an environment variable. I suspect there is something else going on here but I guess it is possible that I'm missing something.
This is the relevant code for what is happening when the number of threads is set:
https://github.com/GreenleafLab/ArchR/blob/020757998cd87abb0414991b59b8424958679be0/R/GlobalDefaults.R#L248

And this is the relevant code for what is happening when you do `library(ArchR)`.
https://github.com/GreenleafLab/ArchR/blob/020757998cd87abb0414991b59b8424958679be0/R/GlobalDefaults.R#L14

You can test what might be hanging by running the following commands (without running `library(ArchR)`)
Test threads:
`ArchR::addArchRThreads(4)`
Test Cairo:
ArchR:::.checkCairo()

My guess would be that the Cairo test is causing your problem?

**Comment by asmagen** [comment]
That’s correct, the Cairo tests is stuck although the package is installed and is functional. What can be done about it?


On Oct 20, 2020, at 10:26 AM, Ryan Corces <notifications@github.com> wrote:






USE CAUTION: External Message.






I think that is unlikely the cause of the problem. At least the act of setting the cores doesn't
use multiple cores. Its just setting an environment variable. I suspect there is something else going on here but I guess it is possible that I'm missing something.
This is the relevant code for what is happening when the number of threads is set:
https://github.com/GreenleafLab/ArchR/blob/020757998cd87abb0414991b59b8424958679be0/R/GlobalDefaults.R#L248
And this is the relevant code for what is happening when you do 
library(ArchR).
https://github.com/GreenleafLab/ArchR/blob/020757998cd87abb0414991b59b8424958679be0/R/GlobalDefaults.R#L14
You can test what might be hanging by running the following commands (without running
library(ArchR))
Test threads:
ArchR::addArchRThreads(4)
Test Cairo:
ArchR:::.checkCairo()
My guess would be that the Cairo test is causing your problem?
—
You are receiving this because you authored the thread.
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.

**Comment by rcorces** [comment]
I have a feeling that Cairo is not functional.

What happens when you type:
```
Cairo::Cairo(type='raster')
dev.off()
```
This is the part that it is hanging on but perhaps it will give you some useful output.

**Comment by asmagen** [comment]
When I try to run the Cairo test manually it does work:




> ArchR::addArchRThreads(4)

Setting default number of Parallel threads to 4.

> Cairo::Cairo(type = "raster")

> dev.off()

null device 

          1 




And curiously after running that, the original test and package loading works...


On Oct 20, 2020, at 10:26 AM, Ryan Corces <notifications@github.com> wrote:






USE CAUTION: External Message.






I think that is unlikely the cause of the problem. At least the act of setting the cores doesn't
use multiple cores. Its just setting an environment variable. I suspect there is something else going on here but I guess it is possible that I'm missing something.
This is the relevant code for what is happening when the number of threads is set:
https://github.com/GreenleafLab/ArchR/blob/020757998cd87abb0414991b59b8424958679be0/R/GlobalDefaults.R#L248
And this is the relevant code for what is happening when you do 
library(ArchR).
https://github.com/GreenleafLab/ArchR/blob/020757998cd87abb0414991b59b8424958679be0/R/GlobalDefaults.R#L14
You can test what might be hanging by running the following commands (without running
library(ArchR))
Test threads:
ArchR::addArchRThreads(4)
Test Cairo:
ArchR:::.checkCairo()
My guess would be that the Cairo test is causing your problem?
—
You are receiving this because you authored the thread.
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.

**Comment by rcorces** [comment]
what if you run the whole try-catch statement? does it hang?
```
  tryCatch({
    Cairo::Cairo(type='raster')
    dev.off()
    TRUE
  }, error = function(e){
    FALSE
  })
```

**Comment by rcorces** [comment]
sorry. didnt see your original statement 

> And curiously after running that, the original test and package loading works...

Maybe try restarting R and making sure that the `library(ArchR)` command runs ok  in a fresh session? No idea why this behavior would happen though.

**Comment by asmagen** [comment]
It ran okay


Is it possible it has something to do with using or not using unix screen on the server while setting up an interactive job?



On Oct 20, 2020, at 11:16 AM, Ryan Corces <notifications@github.com> wrote:






USE CAUTION: External Message.






what if you run the whole try-catch statement? does it hang?
  tryCatch({
    Cairo::Cairo(type='raster')
    dev.off()
    TRUE
  }, error = function(e){
    FALSE
  })

—
You are receiving this because you authored the thread.
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.

**Comment by asmagen** [comment]
I logged out of everything in that server and entered again and now it works normally. Still setting up 24 threads but it doesn’t hang. Odd behavior.


On Oct 20, 2020, at 11:18 AM, Ryan Corces <notifications@github.com> wrote:






USE CAUTION: External Message.






sorry. didnt see your original statement

And curiously after running that, the original test and package loading works...

Maybe try restarting R and making sure that the library(ArchR) command runs ok in a fresh session? No idea why this behavior would happen though.
—
You are receiving this because you authored the thread.
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
