### ISSUE TITLE
Identification of positive TF regulator

### ISSUE THREAD

**Issue by yxiao832** [GreenleafLab/ArchR#354]
Hi,
I have a question regarding Step15.4. 

The example here is to analyze positive correlation of TF expression and motif across all cell groups. Now I want to analyze the enriched motif sets I identified in cell groupA (by pair-wise comparison between cell groupA vs cell groupB) whether has positive correlation to its RNA expression in cell groupA.

Should I do the following?
Step1 get deviation z score only between Cell groupA and cell groupB
Step2 run "correlateMatrices" using the motif matrix and gene integration matrix only containing the cells from cell groupA and B

Other steps just follow your original instruction

Or I can just subset my Archr object using cells of interest and do exactly what you have in Step15.4.

Thank you,
Yang

**Comment by jgranja24** [comment]
I believe if you just subset it should work ie

```
corGIM_MM <- correlateMatrices(
    ArchRProj = projHeme5[,c(groupA, groupB),
    useMatrix1 = "GeneIntegrationMatrix",
    useMatrix2 = "MotifMatrix",
    reducedDims = "IterativeLSI"
)
```

Best

Jeff

**Comment by yxiao832** [comment]
Thanks! I subsetted the ArchRProj and did everything using the instruction. That worked! 

This command 
" lapply(seq_len(ncol(seZ)), function(x){
  rowMaxs(assay(seZ) - assay(seZ)[,x])
}) %>% Reduce("cbind", .) %>% rowMaxs" 

seems can be simplified to rowMaxs(assay(seZ)) - rowMins(assay(seZ)) to get Max delta   - or maybe I misunderstood your function

Yang
