### ISSUE TITLE
Get GeneScoreMatrix

### ISSUE THREAD

**Issue by asmagen** [GreenleafLab/ArchR#355]
How do I get the GeneScoreMatrix? I see only internal functions such as getFeatureDF that may have the right functionality but it's not exported.

Thanks

**Comment by jgranja24** [comment]
`getMatrixFromProject(ArchRProj, "GeneScoreMatrix")`

best

jeff

**Comment by jgranja24** [comment]
Closing this issue. Feel free to open new ones!
