### ISSUE TITLE
Footprinting Plot documentation

### ISSUE THREAD

**Issue by gbloeb** [GreenleafLab/ArchR#356]
**Where is the problematic documentation?**
The explanation of footprints in Section 14.2 of the user manual

**Describe what is unclear or confusing**
I do not understand what the "Tn5-Bias Normalized Insertions" (bottom plot) is showing.  What is being used to normalize here?  Why do these graphs tend to show overlapping curves for each cell type (in contrast to the top plots)?

**Comment by jgranja24** [comment]
It just the expected Tn5 bias from a hexamer model. It is normalized so the flanks = 1. The expected bias is similar for each sample since it is based on Tn5 and not scATAC-seq data.

**Comment by jgranja24** [comment]
Closing this issue. Feel free to open new ones!
