### ISSUE TITLE
problem with aggregated cellranger output

### ISSUE THREAD

**Issue by wfma** [GreenleafLab/ArchR#359]
Hi!

I am working thru the tutorial and also trying to apply it directly to my own dataset. I have a ds that contains 44 samples that were aggregated using the cellranger-aggr function. Despite being able to run the tutorial to generate my arrow files using the PMBC data, I am unable to do so with my own data and the log is cryptic:

**Attach your log file**
[ArchR-createArrows-2e1531755c119-Date-2020-10-23_Time-14-32-04.log](https://github.com/GreenleafLab/ArchR/files/5431194/ArchR-createArrows-2e1531755c119-Date-2020-10-23_Time-14-32-04.log)

**Describe the bug**
It doesnt tell me what the error is, it seems to be a problem with choosing a method?

**To Reproduce**
```
#### library and pkg installation ####
# tutorial https://www.archrproject.com/articles/Articles/tutorial.html#creating-arrow-files
# devtools::install_github("GreenleafLab/ArchR", ref="master", repos = BiocManager::repositories())
# run the install extra pkg once!
# ArchR::installExtraPackages()

library(ArchR) 
addArchRThreads(threads = 1) # this can be run if you have parallel threads on your local machine

#### data loading ####
inputFiles <- getTutorialData("Hematopoiesis") # get tutorial data
inputFiles
addArchRGenome("hg19") #hg38 or mm10 are available

ArrowFiles <- createArrowFiles(
  inputFiles = inputFiles,
  sampleNames = names(inputFiles),
  filterTSS = 1, #Dont set this too high because you can always increase later
  filterFrags = 1000, 
  addTileMat = TRUE,
  addGeneScoreMat = TRUE
)

```

I also tried changing the reference genome (we used Hg38) but it produced the same error.

**Screenshots**
I compared our dataset with the sample dataset for formatting and didnt see anything obvious.

![Xnip2020-10-23_13-57-34](https://user-images.githubusercontent.com/23326773/97041006-d3c42400-153c-11eb-85c2-4c49cb4127b2.jpg)

**Comment by jgranja24** [comment]
Can you try` reformatFragmentFiles` there are subtleties associated with being a **tabix** fragment file. That would be my first guess!

Let me know if that works!

Best

Jeff

**Comment by jgranja24** [comment]
I will also say that you may be better off using the 44 individual fragment files prior to cell ranger aggr. Doublet calling will be much more difficult if you do not split this by sample. Also, ArchR is better designed to work with 44 fragment files than the merged 1 in speed and memory!

**Comment by wfma** [comment]
Hi Jeff thank you so much for the quick reply- I will try the aforementioned troubleshooting. I have another question- is there a function for me to export my data (as seurat/singlecellexperiment etc.) later on as a combined dataset? I am hoping to test out several scRNA-integration tools (e.g. LIGER) in addition to running archR's built in.

Thanks,
Wei

**Comment by jgranja24** [comment]
Hi @wfma, yeah there are export functions like getMatrixFromProject that export a SummarizedExperiment.

**Comment by wfma** [comment]
really truly appreciate all the help jeff!
