### ISSUE TITLE
Projecting different data set onto an existing UMAP?

### ISSUE THREAD

**Issue by jogiles** [GreenleafLab/ArchR#360]
Hello!

Is it possible to use the predictive capability of UMAP? I would like to project a different data set onto an existing UMAP from an ArchR project. 

Thank you! Josephine

**Comment by rcorces** [comment]
This is definitely in the works and may already be available but it is not documented. @jgranja24 can provide more info.

**Comment by jgranja24** [comment]
Hi @jogiles,

This is something we are hoping to have out in the near future. Sorry I cant offer a more precise timeline!
