### ISSUE TITLE
Is it possible to add scRNA-seq from the same cells as the scATAC-seq?

### ISSUE THREAD

**Issue by jogiles** [GreenleafLab/ArchR#361]
Hello!

I am interested in using ArchR to analyze the new 10x multiomic assay. Do you have a suggested way to do this? Can ArchR take normalized data from a Seurat object? Can the AddPeak2GeneLinks() take the barcode information into account?

Thank you! Josephine

**Comment by rcorces** [comment]
We are in the process of getting the documentation for this together but this feature does currently exist in the upcoming release. You can see an example of how to do this here:
https://greenleaflab.github.io/ArchR_2020/Ex-Analyze-Multiome.html

The release can be installed via:
`devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.0", repos = BiocManager::repositories())`

I am closing this but feel free to post again if this doesnt answer your questions.

**Comment by jogiles** [comment]
@rcorces This is great!  
Two (maybe) quick questions: 
1) Can "GeneExpressionMatrix" be used in the integrated analysis: addPeak2GeneLinks() and correlateMatrices()? 
2) I know there is not full documentation yet -- but, could you briefly explain how addCombinedDims() works?

**Comment by rcorces** [comment]
1 - yes. should be fine.
2 - Probably not. addCombinedDims uses information from both RNA and ATAC to create a single dimensionality reduction.. The ATAC and RNA LSI reductions are equally weighted.

**Comment by jgranja24** [comment]
We are still messing around with different ways to combine dimensionality reductions as well.

**Comment by jgranja24** [comment]
Now you can visualize your scRNA with scATAC!

see https://github.com/GreenleafLab/ArchR/issues/313 for more details ---

<img width="884" alt="Screen Shot 2020-10-27 at 9 52 31 PM" src="https://user-images.githubusercontent.com/25017655/97392857-17ea5800-18a0-11eb-8d08-d109048a6e35.png">

**Comment by jgranja24** [comment]
Hi @jogiles,

ArchR expects scRNA to be unnormalized still at this time. We are planning to add Seurat wrappers for scRNA analyses soon. addPeak2GeneLinks should still work as usual i believe.

**Comment by jogiles** [comment]
Awesome! Thank you for the update :)

**Comment by jgranja24** [comment]
Hi @jogiles, I am closing this issue since majority of what you are looking at has been addressed. We will be adding more multimodal updates soon so stay tuned. If you have any other issues please open them!

Best

Jeff

**Comment by jogiles** [comment]
Thank you @jgranja24! Looking forward to trying out the new features as they develop :) Josephine
