### ISSUE TITLE
createArrowFiles function

### ISSUE THREAD

**Issue by sylestiel** [GreenleafLab/ArchR#362]
<img width="981" alt="Screen Shot 2020-10-26 at 10 25 27 AM" src="https://user-images.githubusercontent.com/64283689/97192134-9f877800-1775-11eb-84d1-706aaedfffa6.png">

Can you help me decipher the error message?

Thanks!

**Comment by jgranja24** [comment]
Hi @sylestiel this seems to be similar to [https://github.com/GreenleafLab/ArchR/issues/248]( https://github.com/GreenleafLab/ArchR/issues/248). Can you provide the log file associated. 

Thanks!

Jeff

**Comment by jgranja24** [comment]
Also, can you retry with `subThreading = FALSE`?

**Comment by sylestiel** [comment]
Hi Jeff,

Somehow I got past the error. I restarted it today and it did not spit out an error. 

Thank you!
