### ISSUE TITLE
Trouble with subsetting all cells within a cluster or several clusters in an ArchR project 

### ISSUE THREAD

**Issue by jeremybjelajac** [GreenleafLab/ArchR#363]
I was hoping to subset clusters of my ArchR project and reanalyze the smaller dataset/integrate it with an scRNAseq dataset I have for a smaller batch of clusters, but am a little unsure on how to do this.

My ArchR project consists of 11 unique clusters (C1-C11) and I wanted to 1) isolate C1, C2, C3 2) utilize all the cells within C1, C2, C3 to re-cluster and create new embeddings from that. 

Any assistance would be greatly appreciated.

**Comment by rcorces** [comment]
You are looking for the `subsetArchRProject()` function. https://www.archrproject.com/reference/subsetArchRProject.html
In your case, you need to figure out the cell names for the cells that fall within your clusters and provide those to the function. This page of the manual provides enough context to get you there - https://www.archrproject.com/bookdown/manipulating-an-archrproject.html

Please close if this answers your question

**Comment by jeremybjelajac** [comment]
Thanks for the reply, Unfortunately I ran it on my project and received the following error:

Copying ArchRProject to new outputDirectory : /ATACseq/CD45scATACseq/Subset-data
Copying Arrow Files...
Error in .safelapply(seq_along(inArrows), function(x) { : 
Error Found Iteration 1 : 
	[1] "Error in h5read(ArrowFile, paste0(subGroup, \"/Info/CellNames\")) : \n  Object 'MotifMatrix/Info/CellNames' does not exist in this HDF5 file.\n"
	<simpleError in h5read(ArrowFile, paste0(subGroup, "/Info/CellNames")): Object 'MotifMatrix/Info/CellNames' does not exist in this HDF5 file.>
Error Found Iteration 2 : 
	[1] "Error in h5read(ArrowFile, paste0(subGroup, \"/Info/CellNames\")) : \n  Object 'MotifMatrix/Info/CellNames' does not exist in this HDF5 file.\n"
	<simpleError in h5read(ArrowFile, paste0(subGroup, "/Info/CellNames")): Object 'MotifMatrix/Info/CellNames' does not exist in this HDF5 file.>
In addition: Warning message:
In mclapply(..., mc.cores = threads, mc.preschedule = preschedule) :
  2 function calls resulted in an error

Any input on this?

**Comment by rcorces** [comment]
Without more context of what commands you actually ran, it is difficult to provide much feedback. I would recommend that you run through the manual if you havent done so already to make sure that you are using the functions as expected. you can also try updating to the newest development version of ArchR in case you are stumbling into issues that have already been addressed.

To install:
`devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.0", repos = BiocManager::repositories())`

**Comment by jgranja24** [comment]
This error has been resolved in the release branch see https://github.com/GreenleafLab/ArchR/issues/212

**Comment by jgranja24** [comment]
Closing this issue if you have more issues please report it to #212. Feel free to open additional issues!
