### ISSUE TITLE
Issue generated by addReproduciblePeakSet

### ISSUE THREAD

**Issue by honghh2018** [GreenleafLab/ArchR#364]
Hi @all,
     Thanks for develop the great tools,
      here i get a wired question, when i run ArchR on step addReproduciblePeakSet,
      The error showing below:
       ArchR logging to : ArchRLogs/ArchR-addReproduciblePeakSet-3096b2577a4cd-Date-2020-10-27_Time-16-58-48.log
If there is an issue, please report to github with logFile!
Error in .getCoverageMetadata(ArchRProj = ArchRProj, groupBy = groupBy,  : 
  No Coverage Metadata found for : Clusters
     The whole code lie below:
       library(ArchR)
setwd(wd)
addArchRThreads(threads = 16); addArchRGenome("mm10")
F1 = createArrowFiles(
  inputFiles = './F1_outs/fragments.tsv.gz',  sampleNames = 'F1',  outputNames = 'F1',  filterTSS = 4, # 
  filterFrags = 500,  addTileMat = TRUE,  addGeneScoreMat = TRUE )

H1 = createArrowFiles(
  inputFiles = './H1_outs/fragments.tsv.gz',  sampleNames = 'H1',  outputNames = 'H1',  filterTSS = 4, # 
  filterFrags = 500,  addTileMat = TRUE,  addGeneScoreMat = TRUE )
# create archr project
projHeme1 <- ArchRProject(
  ArrowFiles = c('./F1.arrow','./H1.arrow'), ###
  outputDirectory = "twosample",  copyArrows = TRUE #This is recommened so that if you modify the Arrow files you have an original copy for later usage.
)
# projHeme1
#
# paste0("Memory Size = ", round(object.size(projHeme1) / 10^6, 3), " MB")
# View(getCellColData(projHeme1,select=c('ReadsInTSS')))
# 绘制TSS
p1 <- plotGroups(  ArchRProj = projHeme1,  groupBy = "Sample",  colorBy = "cellColData",  
				   name = "TSSEnrichment",  plotAs = "ridges" )
# p1
png("TSS.png",width = 1000,height = 1000)
plot(p1)
dev.off()
##
p2 <- plotTSSEnrichment(ArchRProj = projHeme1)
png("TSS1.png",width = 1000,height = 1000)
plot(p2)
dev.off()
###
pdf("QC-Sample-FragSizes-TSSProfile.pdf",width = 1000,height = 1000)
plotPDF(p1, p2, name = "QC-Sample-FragSizes-TSSProfile.pdf", ArchRProj = projHeme1, addDOC = FALSE, width = 5, height = 5)
dev.off()
# 
saveArchRProject(ArchRProj = projHeme1, outputDirectory = "Save-ProjHeme1", load = FALSE)
# 
# 
# projHeme2 <- filterDoublets(projHeme1)

# 
projHeme2<-projHeme1
projHeme2 <- addIterativeLSI(  ArchRProj = projHeme2,  useMatrix = "TileMatrix",   name = "IterativeLSI",   iterations = 2, 
  clusterParams = list(resolution = c(0.2),sampleCells = 10000, n.start = 10  ), #See Seurat::FindClusters
  varFeatures = 25000,   dimsToUse = 1:30  )
# 4.4 
projHeme2 <- addHarmony( ArchRProj = projHeme2,  reducedDims = "IterativeLSI",  name = "Harmony",  groupBy = "Sample")
projHeme2@reducedDims$Harmony
# 5.1 
projHeme2 <- addClusters(  input = projHeme2,  reducedDims = "IterativeLSI",  method = "Seurat",  name = "Clusters",  resolution = 0.8 )
# 
head(projHeme2$Clusters); table(projHeme2$Clusters)
# 
cM <- confusionMatrix(paste0(projHeme2$Clusters), paste0(projHeme2$Sample))
cM <- cM / Matrix::rowSums(cM)

png("heatmap.png",width = 1000,height = 1000)
pheatmap::pheatmap(  mat = as.matrix(cM), color = paletteContinuous("whiteBlue"), border_color = "black")
dev.off()

# 
projHeme2 <- addUMAP( ArchRProj = projHeme2,reducedDims = "IterativeLSI",name = "UMAP",nNeighbors = 30, minDist = 0.5, metric = "cosine" )
p1 <- plotEmbedding(ArchRProj = projHeme2, colorBy = "cellColData", name = "Sample", embedding = "UMAP")
p2 <- plotEmbedding(ArchRProj = projHeme2, colorBy = "cellColData", name = "Clusters", embedding = "UMAP")

ggAlignPlots(p1, p2, type = "h")
pdf("Plot-UMAP-Sample-Clusters.pdf",width = 1000,height = 1000)
plotPDF(p1,p2, name = "Plot-UMAP-Sample-Clusters.pdf", ArchRProj = projHeme2, addDOC = FALSE, width = 5, height = 5)
dev.off()
# 6.2 t-Stocastic Neighbor Embedding (t-SNE)
projHeme2 <- addTSNE(ArchRProj = projHeme2, reducedDims = "IterativeLSI", name = "TSNE", perplexity = 30 )
p1 <- plotEmbedding(ArchRProj = projHeme2, colorBy = "cellColData", name = "Sample", embedding = "TSNE")
p2 <- plotEmbedding(ArchRProj = projHeme2, colorBy = "cellColData", name = "Clusters", embedding = "TSNE")
ggAlignPlots(p1, p2, type = "h")
pdf("Plot-TSNE-Sample-Clusters.pdf",width = 1000,height = 1000)
plotPDF(p1,p2, name = "Plot-TSNE-Sample-Clusters.pdf", ArchRProj = projHeme2, addDOC = FALSE, width = 5, height = 5)
dev.off()
# 6.3 Harmony
projHeme2 <- addUMAP( ArchRProj = projHeme2, reducedDims = "Harmony", name = "UMAPHarmony", nNeighbors = 30, minDist = 0.5, metric = "cosine")
p3 <- plotEmbedding(ArchRProj = projHeme2, colorBy = "cellColData", name = "Sample", embedding = "UMAPHarmony")
p4 <- plotEmbedding(ArchRProj = projHeme2, colorBy = "cellColData", name = "Clusters", embedding = "UMAPHarmony")
ggAlignPlots(p3, p4, type = "h")
pdf("Plot-UMAP2Harmony-Sample-Clusters.pdf",width = 1000,height = 1000)
plotPDF(p3,p4, name = "Plot-UMAP2Harmony-Sample-Clusters.pdf", ArchRProj = projHeme2, addDOC = FALSE, width = 5, height = 5)
dev.off()
#
markersGS <- getMarkerFeatures(  ArchRProj = projHeme2,useMatrix = "GeneScoreMatrix", groupBy = "Clusters",bias = c("TSSEnrichment", "log10(nFrags)"),testMethod = "wilcoxon")

markerList <- getMarkers(markersGS, cutOff = "FDR <= 0.01 & Log2FC >= 1.25")
markerList$C6

markerGenes  <- c(  "Star",   "Klk1b21",   "Klk1b24",   "Klk1b27" )

heatmapGS <- markerHeatmap( seMarker = markersGS, cutOff = "FDR <= 0.01 & Log2FC >= 1.25", labelMarkers = markerGenes, transpose = TRUE)
png("heatmap_mark.png",width = 1000,height = 1000)
ComplexHeatmap::draw(heatmapGS, heatmap_legend_side = "bot", annotation_legend_side = "bot")
dev.off()
#
markerGenes  <- c("Star", "Klk1b21", "Klk1b24", "Klk1b27")

p <- plotEmbedding( ArchRProj = projHeme2, colorBy = "GeneScoreMatrix", name = markerGenes, embedding = "UMAP",quantCut = c(0.01, 0.95),imputeWeights = NULL)
png("UMAP_mark.png",width = 1000,height = 1000)
p$Star
dev.off()
# 
p2 <- lapply(p, function(x){
  x + guides(color = FALSE, fill = FALSE) + 
    theme_ArchR(baseSize = 6.5) +
    theme(plot.margin = unit(c(0, 0, 0, 0), "cm")) +
    theme(
      axis.text.x=element_blank(), 
      axis.ticks.x=element_blank(), 
      axis.text.y=element_blank(), 
      axis.ticks.y=element_blank()
    )
})
p1<-do.call(cowplot::plot_grid, c(list(ncol = 3),p2))
png("UMAP_mark_all.png",width = 1500,height = 1500)
print(p1)
dev.off()

#
projHeme2 <- addImputeWeights(projHeme2)
markerGenes  <- c( "Star", "Klk1b21", "Klk1b24", "Klk1b27")

p <- plotEmbedding(ArchRProj = projHeme2, colorBy = "GeneScoreMatrix", name = markerGenes, embedding = "UMAP",imputeWeights = getImputeWeights(projHeme2))

png("UMAP_mark_magic.png",width = 1500,height = 1500)
plot(p1)
dev.off()
# 7.6 plotting Track
markerGenes  <- c("Star", "Klk1b21", "Klk1b24", "Klk1b27")
p <- plotBrowserTrack(ArchRProj = projHeme2, groupBy = "Clusters", geneSymbol = markerGenes, upstream = 50000,downstream = 50000)
png("track_mark_magic.png",width = 1500,height = 1500)
grid::grid.newpage()
grid::grid.draw(p$Star)
dev.off()

# 
pathToMacs2 <- "/home/honghh/miniconda3/envs/ATAC/bin/macs2"
### addReproduciblePeakSet()
saveRDS(projHeme2,"projHeme2.rds")
projHeme4 <- addReproduciblePeakSet( ArchRProj = projHeme2, groupBy = "Clusters", pathToMacs2 = pathToMacs2)

## 10.3identify Peaks w/TileMatrix
projHemeTmp <- addReproduciblePeakSet(
    ArchRProj = projHeme4, 
    groupBy = "Clusters",
    peakMethod = "Tiles",
    method = "p"
)
## MACS2
length(subsetByOverlaps(getPeakSet(projHeme4), getPeakSet(projHemeTmp))) / length(getPeakSet(projHeme4))
## TileMatrix
length(subsetByOverlaps(getPeakSet(projHemeTmp), getPeakSet(projHeme4))) / length(getPeakSet(projHemeTmp))
length(subsetByOverlaps(resize(getPeakSet(projHeme4), 1000, "center"), getPeakSet(projHemeTmp))) / length(getPeakSet(projHeme4))
length(subsetByOverlaps(getPeakSet(projHemeTmp), resize(getPeakSet(projHeme4), 1000, "center"))) / length(getPeakSet(projHemeTmp))
## 10.4 adding Peak matrix
saveArchRProject(ArchRProj = projHeme4, outputDirectory = "Save-ProjHeme4", load = FALSE)
projHeme5 <- addPeakMatrix(projHeme4)
getAvailableMatrices(projHeme5)

## 11.1: 使用ArchR鉴定标记Peak
table(projHeme5$Cluster2)
markersPeaks <- getMarkerFeatures(
    ArchRProj = projHeme5, 
    useMatrix = "PeakMatrix", 
    groupBy = "Clusters2",
  bias = c("TSSEnrichment", "log10(nFrags)"),
  testMethod = "wilcoxon"
)

markerList_df <- getMarkers(markersPeaks, cutOff = "FDR <= 0.01 & Log2FC >= 1")
markerList_df
markerList_GR <- getMarkers(markersPeaks, cutOff = "FDR <= 0.01 & Log2FC >= 1", returnGR = TRUE)
markerList_GR

## 11.2.1 Marker Peak Heatmap
heatmapPeaks <- markerHeatmap( seMarker = markersPeaks, cutOff = "FDR <= 0.1 & Log2FC >= 0.5",transpose = TRUE)

p <- plotPDF(heatmapPeaks, name = "Peak-Marker-Heatmap", width = 8, height = 6, ArchRProj = projHeme5, addDOC = FALSE)
png("11_mark_peak_heatmap.png",width = 1500,height = 1500)
p
dev.off()
png("11_mark_peak_heatmap.png",width = 1500,height = 1500)
plotPDF(heatmapPeaks, name = "Peak-Marker-Heatmap", width = 8, height = 6, ArchRProj = projHeme5, addDOC = FALSE)
dev.off()

### 11.2.2 Marker Peak MA and volcano
pma <- markerPlot(seMarker = markersPeaks, name = "Erythroid", cutOff = "FDR <= 0.1 & Log2FC >= 1", plotAs = "MA")
png("11_pma.png",width = 1500,height = 1500)
pma
dev.off()
pv <- markerPlot(seMarker = markersPeaks, name = "Erythroid", cutOff = "FDR <= 0.1 & Log2FC >= 1", plotAs = "Volcano")
png("11_volcano.png",width = 1500,height = 1500)
pv
dev.off()
##
## 12.1 differential peak motif enrichment
projHeme5 <- addMotifAnnotations(ArchRProj = projHeme5, motifSet = "cisbp", name = "Motif")
motifsUp <- peakAnnoEnrichment(
    seMarker = markerTest,
    ArchRProj = projHeme5,
    peakAnnotation = "Motif",
    cutOff = "FDR <= 0.1 & Log2FC >= 0.5"
  )
  
df <- data.frame(TF = rownames(motifsUp), mlog10Padj = assay(motifsUp)[,1])
df <- df[order(df$mlog10Padj, decreasing = TRUE),]
df$rank <- seq_len(nrow(df))
ggUp <- ggplot(df, aes(rank, mlog10Padj, color = mlog10Padj)) + 
  geom_point(size = 1) +
  ggrepel::geom_label_repel(
        data = df[rev(seq_len(30)), ], aes(x = rank, y = mlog10Padj, label = TF), 
        size = 1.5,
        nudge_x = 2,
        color = "black"
  ) + theme_ArchR() + 
  ylab("-log10(P-adj) Motif Enrichment") + 
  xlab("Rank Sorted TFs Enriched") +
  scale_color_gradientn(colors = paletteContinuous(set = "comet"))
ggsave(ggUp,filename = "./12_ggUP.png")

motifsDo <- peakAnnoEnrichment(
    seMarker = markerTest,
    ArchRProj = projHeme5,
    peakAnnotation = "Motif",
    cutOff = "FDR <= 0.1 & Log2FC <= -0.5"
  )
df <- data.frame(TF = rownames(motifsDo), mlog10Padj = assay(motifsDo)[,1])
df <- df[order(df$mlog10Padj, decreasing = TRUE),]
df$rank <- seq_len(nrow(df))
ggDo <- ggplot(df, aes(rank, mlog10Padj, color = mlog10Padj)) + 
  geom_point(size = 1) +
  ggrepel::geom_label_repel(
        data = df[rev(seq_len(30)), ], aes(x = rank, y = mlog10Padj, label = TF), 
        size = 1.5,
        nudge_x = 2,
        color = "black"
  ) + theme_ArchR() + 
  ylab("-log10(FDR) Motif Enrichment") +
  xlab("Rank Sorted TFs Enriched") +
  scale_color_gradientn(colors = paletteContinuous(set = "comet"))
ggsave(ggDo,filename = "./12_ggDo.png")
### 12.2 mark Peak's motif enrichment
enrichMotifs <- peakAnnoEnrichment(
    seMarker = markersPeaks,
    ArchRProj = projHeme5,
    peakAnnotation = "Motif",
    cutOff = "FDR <= 0.1 & Log2FC >= 0.5"
  )

heatmapEM <- plotEnrichHeatmap(enrichMotifs, n = 7, transpose = TRUE)
png("12.2_heatmap.png",width = 1500,height = 1500)
ComplexHeatmap::draw(heatmapEM, heatmap_legend_side = "bot", annotation_legend_side = "bot")
dev.off()

## 12.3.1 Encode TF binding
projHeme5 <- addArchRAnnotations(ArchRProj = projHeme5, collection = "EncodeTFBS")
enrichEncode <- peakAnnoEnrichment(
    seMarker = markersPeaks,
    ArchRProj = projHeme5,
    peakAnnotation = "EncodeTFBS",
    cutOff = "FDR <= 0.1 & Log2FC >= 0.5"
  )
  heatmapEncode <- plotEnrichHeatmap(enrichEncode, n = 7, transpose = TRUE)
  png("12.3_heatmap.png",width = 1500,height = 1500)
  ComplexHeatmap::draw(heatmapEncode, heatmap_legend_side = "bot", annotation_legend_side = "bot")
  dev.off()
 saveRDS(projHeme5, "projHeme5.RDS)
 how can i solve this question and how can i analysis differential peak between control and treat
 Best, 
hanhuihong

**Comment by rcorces** [comment]
It looks like you missed the `addGroupCoverages()` step which is required before calling peaks?
https://www.archrproject.com/bookdown/making-pseudo-bulk-replicates.html

**Comment by jgranja24** [comment]
This error --

ArchR logging to : ArchRLogs/ArchR-addReproduciblePeakSet-3096b2577a4cd-Date-2020-10-27_Time-16-58-48.log
If there is an issue, please report to github with logFile!
Error in .getCoverageMetadata(ArchRProj = ArchRProj, groupBy = groupBy, :
No Coverage Metadata found for : Clusters

Is because like @rcorces said you did not `addGroupCoverages` prior to peakCalling.

Run --
```
projHeme2 <- addGroupCoverages( ArchRProj = projHeme2, groupBy = "Clusters")
projHeme4 <- addReproduciblePeakSet( ArchRProj = projHeme2, groupBy = "Clusters", pathToMacs2 = pathToMacs2)
```

This is highlighted
[https://www.archrproject.com/bookdown/making-pseudo-bulk-replicates.html
](https://www.archrproject.com/bookdown/making-pseudo-bulk-replicates.html
)

**Comment by honghh2018** [comment]
It work for me. 
Thanks @rcorces @jgranja24 for the urgent reply.
