### ISSUE TITLE
cannot set scaleTo to  NULL in getTrajectory function (release 1.0.0)

### ISSUE THREAD

**Issue by lzj1769** [GreenleafLab/ArchR#370]
Hi,

I am using this package for my data, and I would like to generate a trajectory heatmap with motif matrix as input.

When I try to set scaleTo to NULL, I got an error message:

> > trajMM1 <- getTrajectory(ArchRProj = proj, 
>                           name = "Myofib1", 
>                           useMatrix = "MotifMatrix", 
>                           log2Norm = FALSE,
>                           scaleTo = NULL)
> Error in .validInput(input = scaleTo, name = "scaleTo", valid = c("numeric")) : 
>   Input value for 'scaleTo' is not a numeric, (scaleTo = NULL) please supply valid input!

In the document, it says Setting this to NULLwill prevent any normalization and should be done in certain circumstances (for ex. if you are using a "MotifMatrix"). But in the function, there are no such codes.

thanks and best,
Li

**Comment by jgranja24** [comment]
I just updated --

```
  .validInput(input = scaleTo, name = "scaleTo", valid = c("numeric"))
```

To --

```
  .validInput(input = scaleTo, name = "scaleTo", valid = c("numeric", "null"))
```

To test --

```
#New Release Branch
devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.0", repos = BiocManager::repositories())

library(ArchR)
proj <- getTestProject()
proj <- addTrajectory(proj, trajectory = c("C1", "C2", "C3", "C4"))
proj <- getTrajectory(proj, scaleTo = NULL)
# Creating Trajectory Group Matrix..
# Smoothing...
```

**Comment by jgranja24** [comment]
Closing this issue, feel free to open new issues!

**Comment by lzj1769** [comment]
awesome, thanks

**Comment by jgranja24** [comment]
Also I think ArchR just handles this internally for motif matrix since its positive and negative --

 ```
 #Scale
  if(!is.null(scaleTo)){
    if(any(groupMat < 0)){
      message("Some values are below 0, this could be a DeviationsMatrix in which scaleTo should be set = NULL.\nContinuing without depth normalization!")
    }else{
      groupMat <- t(t(groupMat) / colSums(groupMat)) * scaleTo
    }
  }
```

But I am happy you caught this!

**Comment by lzj1769** [comment]
Hi @jgranja24 

I found a similar issue from plotTrajectory, where I cannot set quantCut to NULL because:
`.validInput(input = quantCut, name = "quantCut", valid = c("numeric"))`

I have to set it to c(0, 1) to not use quantile threshold.

best,
Li

**Comment by jgranja24** [comment]
This has been updated in the release_1.0.0 branch for when quantCut is NULL it will just set it to c(0,1) like you did.

Closing this issue, thanks for the help!

Jeff
