### ISSUE TITLE
Mapping peaks to genes rules

### ISSUE THREAD

**Issue by Brawni** [GreenleafLab/ArchR#371]
Hello!

I think it would be useful to have some control on the peak annotation when mapping to genes. For example map peaks to overlapping genes even though the gene start is farther than a second one. As it is now, as far as I understood, it seems that the gene association is taken care of automatically by mapping to the nearest gene start within the addReproduciblePeakSet function. 
Adding an argument to the function or better making another function dedicated to this (so you could change peak annotation without re-running the peak caller) would be cool. 

Thanks!

**Comment by jgranja24** [comment]
Hi @Brawni, I am not sure what you want to do here. You can always run `getPeakSet` change the annotation and the `addPeakSet`? There aren't any functions I believe that utilize nearest genes?

**Comment by jgranja24** [comment]
I think that anything beyond simple mapping would be something a user can toy around with alternative methods/softwares and reimport that into the ArchRProject.

I am closing this issue, however feel free to further comment or open new issues!

**Comment by Brawni** [comment]
I see, yes I guess that works too, thanks!
