### ISSUE TITLE
Getting insertion count matrix per peak

### ISSUE THREAD

**Issue by ivanferrreira** [GreenleafLab/ArchR#372]
Hi,

Is there an easy way to get counts per peaks for cells grouped by their identity? 
Something like what addGroupCoverages calculates, but I am not sure how to extract that in the format of a peak set containing counts per sample for each genomic coordinate. 

Thanks,
Ivan

**Comment by rcorces** [comment]
`getGroupSE()`
https://www.archrproject.com/reference/getGroupSE.html

please close if this answers your question.

**Comment by jgranja24** [comment]
Closing this issue, feel free to open new ones.
