### ISSUE TITLE
How to validate/QC RNA and ATAC integration

### ISSUE THREAD

**Issue by jeremybjelajac** [GreenleafLab/ArchR#373]
**Describe the problem that your feature request would address.**
I have really enjoyed utilizing ArchR to analyze scATAC and merged scRNAseq data. However, I find myself questioning how much I can trust my merged ATAC and RNA datasets following integration. I have read the full manual and I can comprehend how ArchR attempts to match cells from the RNA data on to the ATAC map. Additionally, it seems as though if certain clusters from the RNA dataset do not significantly match, they are not carried forward to the merged dataset, which is great (and please correct me if I misstate anything), but I do feel somewhat uncertain about how good my integrated data set is.

**Describe the solution you'd like**
 I was curious if there was any thought as to there being some kind of metric to score or rate RNA and ATAC integration, such that if someone, for example, were to integrate RNAseq data from a macrophage population onto an ATAC dataset from various T cell populations, it would receive an output "integration score" much lower than if an RNAseq sample from the same T cell populations was used. 

**Describe alternatives you've considered**
I have read over Github issue #94 and I think displaying both RNA and ATAC cell clusters on the same UMAP is a great addition! However, I feel as though while useful, this map also needs some kind of analytic to accompany it or specific way to interpret it in order for users to have confidence in their integrated data.

Also, thank you to all the devs working on this program! Very impressive work.

**Additional context**
I have attached copy of my personal merged data for reference
<img width="982" alt="Screen Shot 2020-10-28 at 3 33 27 PM" src="https://user-images.githubusercontent.com/72887219/97503796-f1293180-1932-11eb-851f-13f380dfbb46.png">

**Comment by jgranja24** [comment]
This exists in the `nameScore` column from Seurat. The integrated CCA plot to be honest is difficult to interpret when the heterogeneity isnt super strong. ArchR merely provides a simplistic framework for using Seurat integration efficiently and fluidly. If you have more questions about the Seurat aspect Id consider asking them and if you want more information to extract with ArchR from that let us know.

See Below --

```
devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.0", repos = BiocManager::repositories())

library(ArchR)
proj <- getTestProject()

if(!file.exists("scRNA-Hematopoiesis-Granja-2019.rds")){
    download.file(
        url = "https://jeffgranja.s3.amazonaws.com/ArchR/TestData/scRNA-Hematopoiesis-Granja-2019.rds",
        destfile = "scRNA-Hematopoiesis-Granja-2019.rds"
    )
}

seRNA <- readRDS("scRNA-Hematopoiesis-Granja-2019.rds")

proj <- addGeneIntegrationMatrix(
    ArchRProj = proj, 
    useMatrix = "GeneScoreMatrix",
    matrixName = "GeneIntegrationMatrix",
    reducedDims = "IterativeLSI",
    seRNA = seRNA,
    addToArrow = TRUE,
    verbose = FALSE,
    groupRNA = "BioClassification",
    nameCell = "predictedCell",
    nameGroup = "predictedGroup",
    nameScore = "predictedScore",
    force = TRUE
)

p1 <- plotEmbedding(proj, name = "predictedGroup")
p2 <- plotEmbedding(proj, name = "predictedScore")
plotPDF(ggAlignPlots(p1, p2, type="h", draw=FALSE), width = 12, height = 6)
```

<img width="887" alt="Screen Shot 2020-10-28 at 4 09 40 PM" src="https://user-images.githubusercontent.com/25017655/97506461-33a13d00-1938-11eb-9224-316054fd97d0.png">

**Comment by jeremybjelajac** [comment]
This was super helpful, thank you so much!

**Comment by jeremybjelajac** [comment]
Do you typically use the predicted score as a loose cut-off for judging integration efficiency? And by that standard, clusters 17 and 24 are appropriately matched? Apologies for any misunderstanding.

I will definitely inquire with the Seurat team as well.

**Comment by jgranja24** [comment]
Well these all are somewhat well matched the scores are specifically low in this case where subsets are defined because the test data is **SUPER** downsampled. 17 and 24 B cells and NK cells are the most accurate is the correct understanding. This is because the RNA data set is hematopoiesis and the ATAC is PBMCs. 

Hope that helps

Jeff

**Comment by jeremybjelajac** [comment]
Awesome, that makes total sense. Thanks!
