### ISSUE TITLE
get gene summary by group

### ISSUE THREAD

**Issue by atimms** [GreenleafLab/ArchR#374]
I would like to get a summary of the GeneScoreMatrix by a label, so the Genescore for each of the defined clusters. I couldn't see a way to do that, is it possible.

Thanks for your help.

Andrew

**Comment by jgranja24** [comment]
Hi @atimms,

Do you mean like `getGroupSE`?

To get the average gene scores for each cluster try --

`seGS <- getGroupSE(ArchRProj, useMatrix = "GeneScoreMatrix", groupBy = "Clusters")
`

**Comment by atimms** [comment]
Perfect,

Thanks for the quick response.

Andrew

**Comment by atimms** [comment]
I can get the gene/cluster matrix, but instead of gene name I have the names f1...f24919. I see the gene names are in the object, seGS but can't see how to access.

Thanks for your help.

Andrew

**Comment by jgranja24** [comment]
`rowData(seGS)$name` should do the trick.

**Comment by jgranja24** [comment]
Closing this issue, feel free to open new ones.

**Comment by dagarfield** [comment]
I would make a note though, that the SE exported by this function has its rows in a different order than the rows of the per-cell `PeakMatrix` (and the rows output by `getPeakSet`). This is kind of a weird functionality and while it can be re-ordered using a combination of chromosome name and `idx`, it isn't ideal behavior.
