### ISSUE TITLE
Substitutions for $colData(seRNA)$BioClassification

### ISSUE THREAD

**Issue by sylestiel** [GreenleafLab/ArchR#382]
Hi, 

 When using a Seurat object as opposed to a  Ranged Summarized Experiment for the Integration step what can we substitute for colData and $Bioclassification in the following step

#RNA get cells in these categories
rnaTNK <- colnames(seRNA)[grep(cTNK, colData(seRNA)$BioClassification)]
head(rnaTNK)

Alternatively, would you recommend the conversion to ranged summarized experiment?

Thank you!

**Comment by rcorces** [comment]
this is merely an example and the variables you are talking about are user-provided variables that are being used to subset to specific groups of cells. what you would use would depend entirely on your application and you may not do all of the steps in the manual.
