### ISSUE TITLE
Is it possible to modify the matrix in ArchR or add external matrices to the project

### ISSUE THREAD

**Issue by qingnanl** [GreenleafLab/ArchR#388]
Hi Developers,

Thanks for the great package. It is very smooth and versatile.

One thing I found is that I don't know how to modify the matrix generated by ArchR and store it back in the project or add external matrices to the project. For example, I might need to do some preprocessing such as batch correction or other normalization on the GeneScoreMatrix with other software and send it back to the ArchR project for downstream analysis. Is that possible or did I missed it in your tutorial?

Many thanks,

qingnanl

**Comment by rcorces** [comment]
As far as I know, this capability does not exist. It also seems difficult to implement. The matrices are actually stored in the Arrow files which complicates things. This does seem like it would be useful but @jgranja24 would have to weigh in on how difficult this would be to implement.

**Comment by qingnanl** [comment]
> As far as I know, this capability does not exist. It also seems difficult to implement. The matrices are actually stored in the Arrow files which complicates things. This does seem like it would be useful but @jgranja24 would have to weigh in on how difficult this would be to implement.

Thanks for the reply. I would still recommend you consider this possibility. I think for all the steps, you have put quite a state of the art methods in it, but it could be inevitable that some methods perform better than each other in a different context, and it is certainly impractical for you to get all of them implemented. 

I am also reading your code regarding "addGeneScoreMatrix" or adding other matrices add see whether it is possible to get something from it. Seems not easy for me lol. Anyway thanks again for the reply. The work is beautiful.

**Comment by rcorces** [comment]
What exactly is the downstream use case here? Do you want to display this new information as a UMAP, with cells colored by some updated value? If so, you can just add a new column to `cellColData` using values computed outside of ArchR. If you want a matrix to work natively with other ArchR functions, then that seems like a more difficult feature request that wont be implemented any time soon.

**Comment by qingnanl** [comment]
> What exactly is the downstream use case here? Do you want to display this new information as a UMAP, with cells colored by some updated value? If so, you can just add a new column to `cellColData` using values computed outside of ArchR. If you want a matrix to work natively with other ArchR functions, then that seems like a more difficult feature request that wont be implemented any time soon.

For example, what about batch correction on the gene score? Harmony is a good one but I won't say it is the best in all cases, plus it does not correct for the expression level itself. It might be useful for giving better RNA-ATAC integration and also gene-peak linking.

**Comment by xiaosuyu1997** [comment]
That is exactly a feature I'm looking for during my reproduction of someone else's work. I'm trying to import a Cicero gene activity score matrix into ArchR_project for downstream integration and label transfer analysis, and to give this matrix a customized name.
