### ISSUE TITLE
Does the Call Peak function depend upon the Pseudobulk replicate generation?

### ISSUE THREAD

**Issue by sylestiel** [GreenleafLab/ArchR#389]
Hi, 

 I'm in the process of working my way throught the full manual of ArchR. I was wondering if generation of PseudoBulk Replicates is a prerequisite  to Calling Peaks using ArchR. Also can I direct the function call 
group.by= Clusters
as opposed to 
group.by =Clusters2 (Labeling scATAC-seq clusters with scRNA-seq information).
What are the pros and cons of using Clusters vs. Clusters2

Thanks!

**Comment by rcorces** [comment]
1) Pseudobulk generation is a prerequisite for peak calling
2) The cell groupings that you use will affect the peaks that you get. In the tutorial, we refined our cluster identification using RNA information to create "Clusters2". In reality, these clustering schemes are extremely similar (shown below) with the exception of the monocyte cluster. What is "better" will depend on your application.

Clusters
![image](https://user-images.githubusercontent.com/10343046/97934657-25ce2c00-1d2b-11eb-9448-ff10a4b08b27.png)

Clusters2
![image](https://user-images.githubusercontent.com/10343046/97934679-354d7500-1d2b-11eb-87e8-9545bff1b6de.png)

**Comment by sylestiel** [comment]
Thank you!!
