### ISSUE TITLE
Filtering cells before feature selection/clustering

### ISSUE THREAD

**Issue by asmagen** [GreenleafLab/ArchR#390]
Hello,

How can I exclude exclude cells from the feature selection and clustering analysis? Ideally performing initial clustering to identify clusters representing contaminants and then removing them from a second iteration of the analysis focused on the other cells.

I tried looking at the strategy in filter doublets to see if I can use that code to do the filtering on other cells (non doublets), but it's not clear to me if that's going to work. Hopefully you have a dedicated function for that. But in the context of doublets, is the doublet filter function working? It doesn't end up doing anything when I run it and the code appears to potentially have an issue with the %in% clause:
`ArchRProj@cellColData <- ArchRProj@cellColData[rownames(ArchRProj@cellColData) %ni% cellsFilter,,drop=FALSE]`

Thank you

**Comment by rcorces** [comment]
https://www.archrproject.com/reference/subsetArchRProject.html

**Comment by rcorces** [comment]
also `%ni%` is a custom function which provides the opposite of `%in%`. Please close if this answers your questions.
