### ISSUE TITLE
Upper threshold on # fragments

### ISSUE THREAD

**Issue by asmagen** [GreenleafLab/ArchR#391]
Hello,

In the QC filtering function there's a way to filter the low # fragment cells but not specifically select for cells with an intermediate # of fragments (above the failed cells and below the very highly enriched ones).
How can I focus on such cells for dedicated analysis?

Thank you

**Comment by rcorces** [comment]
You can either use the `subsetArchRProject` function which I recommended for your other issue or you can see the various ways to manipulate ArchR projects outlined in the manual. https://www.archrproject.com/bookdown/manipulating-an-archrproject.html
