### ISSUE TITLE
plotEmbedding with split.by support

### ISSUE THREAD

**Issue by mzhibo** [GreenleafLab/ArchR#394]
**Describe the problem that your feature request would address.**
A common analysis that is performed but not currently supported is split view of the plotEmbeddings, for example, by Samples. 

**Describe the solution you'd like**
A feature similar to the split.by feature in Seruat's FeaturePlot function would be great for side to side comparison between samples. This is do-able using subsetted arrowobjects, but it is not very convenient to keep adjust the x and y at the same range limits.

**Comment by rcorces** [comment]
Sorry for the delay. I dont think this requires a separate function. I think you can just use normal subsetting on the `ArchRProject` object that you pass to `plotEmbedding()`

For ex - 
```
idxSample <- BiocGenerics::which(projHeme1$Sample %in% "scATAC_BMMC_R1")
cellsSample <- projHeme1$cellNames[idxSample]
plotEmbedding(projHeme1[cellsSample, ], ....)
```

You can plot arbitrary subsets of cells like this. Feel free to post again if this doesnt work for you and I'll reopen the issue

**Comment by laiyiwei** [comment]
**I was encuntering this error when I tried to do the same thing:**

Error in plotEmbedding(ArchRProj = proj colorBy = "GeneScoreMatrix", highlightCells = c(rownames(proj)[proj$group ==  :
  Not all cells in embedding are present in ArchRProject!

I guess this error was generated by subseting, which the embedding of the project was not subset properly.
