### ISSUE TITLE
chunk_size error when running createArrowFiles with large number of scaffolds

### ISSUE THREAD

**Issue by angleYuan** [GreenleafLab/ArchR#395]
**Describe the bug**
I work with the sea lamprey, whose latest genome assembly still contains more than 1400 scaffolds. It seemed that the large number of scaffolds gave me the following error when I ran createArrowFiles.

<simpleError in if (chunk_size > 2^32 - 1) {    root_dim <- floor(((2^32 - 1)/H5Tget_size(dtype))^(1/length(chunk)))    chunk[chunk > root_dim] = root_dim    message("Current chunk settings will exceed HDF5's 4GB limit.\n",         "Automatically adjusting them to: ", paste(chunk, collapse = " x "),         "\nYou may wish to set these to more appropriate values using the 'chunk' argument.")}: missing value where TRUE/FALSE needed>

If I only extracted the fragments that mapped to the 86 major scaffolds (which makes up 87% of the genome), I was able to bypass this error. Therefore I believe it is the big number of scaffolds that caused the problem. I tried setting nchunk=10 or 1 when running createArrowFiles but still got the same error. 

**Expected behavior**
As I hope I don't have to throw up more than 10% of the genome, I would really appreciate a solution that allows me to keep all/most of the scaffolds.  I probably will work with some other more fragmented genomes in the future so in general the option of running ArchR with large number of scaffords will be really helpful. If this is about HDF5 chunk size, it is possible to allow us tweak some HDF5-related setting when running createArrowFiles?

**Attach your log file**
I attached all my log files with different nchunk setting but the same error. Any suggestions will be very welcome! Thank you.
[thread1_chunk1_ArchR-createArrows-8621448bb669-Date-2020-11-03_Time-21-26-05.log](https://github.com/GreenleafLab/ArchR/files/5487085/thread1_chunk1_ArchR-createArrows-8621448bb669-Date-2020-11-03_Time-21-26-05.log)
[thread1_chunk5_ArchR-createArrows-4958571b3ac1-Date-2020-11-03_Time-20-47-56.log](https://github.com/GreenleafLab/ArchR/files/5487086/thread1_chunk5_ArchR-createArrows-4958571b3ac1-Date-2020-11-03_Time-20-47-56.log)
[thread1_chunk10_ArchR-createArrows-4958320fdadb-Date-2020-11-03_Time-22-23-04.log](https://github.com/GreenleafLab/ArchR/files/5487088/thread1_chunk10_ArchR-createArrows-4958320fdadb-Date-2020-11-03_Time-22-23-04.log)

**Comment by angleYuan** [comment]
Hi @rcorces @jgranja24, I figured out the problem. It was not due to chunk_size error, instead, it was because some of my scaffolds were so tiny that only one or only a few fragments mapped to them and all the mapped fragments were filtered out in cell quality check ("bcpass"). So for these scaffolds, the"fragments" become an empty dataset and create errors in h5 write. I submitted a pull request to accommodate this type of tiny scaffolds. Please have a look when you have time.

**Comment by jgranja24** [comment]
Sorry for the delay, Ill take a look in the next day or so!

**Comment by jgranja24** [comment]
Thanks for the info and sorry for the delays -- your version has been implemented as below in createArrows --
```

          if(lengthRG == 0){
          
            .logMessage(msg = paste0(prefix, " detected 0 Fragments in cells passing filtering threshold for ", chr), logFile = logFile)
          
            o <- h5createGroup(outArrow, paste0("Fragments/",chr))
            o <- .suppressAll(h5createDataset(outArrow, chrPos, storage.mode = "integer", dims = c(0, 2), level = 0))
            o <- .suppressAll(h5createDataset(outArrow, chrRGLengths, storage.mode = "integer", dims = c(0, 1), level = 0))
            o <- .suppressAll(h5createDataset(outArrow, chrRGValues, storage.mode = "character", dims = c(0, 1), level = 0, 
                    size = 10)
            
          }else{

            o <- h5createGroup(outArrow, paste0("Fragments/",chr))
            o <- .suppressAll(h5createDataset(outArrow, chrPos, storage.mode = "integer", dims = c(length(fragments), 2), level = 0))
            o <- .suppressAll(h5createDataset(outArrow, chrRGLengths, storage.mode = "integer", dims = c(lengthRG, 1), level = 0))
            o <- .suppressAll(h5createDataset(outArrow, chrRGValues, storage.mode = "character", dims = c(lengthRG, 1), level = 0, 
                    size = max(nchar(mcols(fragments)$RG@values)) + 1))
            
            o <- h5write(obj = cbind(start(fragments),width(fragments)), file = outArrow, name = chrPos)
            o <- h5write(obj = mcols(fragments)$RG@lengths, file = outArrow, name = chrRGLengths)
            o <- h5write(obj = mcols(fragments)$RG@values, file = outArrow, name = chrRGValues)
          }
```

and 


```

          if(lengthRG == 0){
                   
            #HDF5 Write
            o <- .suppressAll(h5createDataset(tmpChrFile, chrPos, storage.mode = "integer", dims = c(0, 2), level = 0))
            o <- .suppressAll(h5createDataset(tmpChrFile, chrRGLengths, storage.mode = "integer", dims = c(0, 1), level = 0))
            o <- .suppressAll(h5createDataset(tmpChrFile, chrRGValues, storage.mode = "character", dims = c(0, 1), level = 0, 
                    size = 10)

          }else{
           
            #HDF5 Write
            o <- .suppressAll(h5createDataset(tmpChrFile, chrPos, storage.mode = "integer", dims = c(length(fragments), 2), level = 0))
            o <- .suppressAll(h5createDataset(tmpChrFile, chrRGLengths, storage.mode = "integer", dims = c(lengthRG, 1), level = 0))
            o <- .suppressAll(h5createDataset(tmpChrFile, chrRGValues, storage.mode = "character", dims = c(lengthRG, 1), level = 0, 
                    size = max(nchar(mcols(fragments)$RG@values)) + 1))

            o <- h5write(obj = cbind(start(fragments),width(fragments)), file = tmpChrFile, name = chrPos)
            o <- h5write(obj = mcols(fragments)$RG@lengths, file = tmpChrFile, name = chrRGLengths)
            o <- h5write(obj = mcols(fragments)$RG@values, file = tmpChrFile, name = chrRGValues)
          }


```

**Comment by dagarfield** [comment]
I ran smack into the same error -- presumably this is not yet pushed to the master (v1.0) branch?

**Comment by rcorces** [comment]
This should be available on the dev branch:
devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.1", repos = BiocManager::repositories())

**Comment by Ruthwang123** [comment]
Thank you so much for your help. 
And I wonder if it's normal for these bad fragments to exist, because I'm a little worried about the alignment error which may influence other fragments that seem to be normal. In this fragment files，I have about 181M fragments in total and seven fragments of chr4 go wrong. 

@rcorces
