### ISSUE TITLE
Visualizing feature enrichment in plotEmbedding()

### ISSUE THREAD

**Issue by mzhibo** [GreenleafLab/ArchR#399]
Do not use this form to report a bug in ArchR! Instead, use the "Bug report" option.

PLEASE FILL OUT THE RELEVANT INFORMATION AND DELETE THE UNUSED PORTIONS OF THIS ISSUE TEMPLATE.

**Describe the problem that your feature request would address.**
A common analysis I do is checking the enrichment of signature regions on the UMAP/tSNE embedding. Currently the tutorial shows a good way of checking the summarized cluster average enrichment of signature regions. I have not find a convenient way of visualizing the the enrichment of the signature region in each cell.

**Describe the solution you'd like**
add an entry in the project object for the signatureSet-cell enrichment matrix so that we can conveniently visualize it using plotEmbedding()

**Describe alternatives you've considered**
allow custom addition of featureSets-cell matrix to the arrow file.

**Additional context**

**Comment by rcorces** [comment]
Sorry @mzhibo - somehow this issue fell through the cracks. I believe this has already been implemented using the `addModuleScore()` function though the documentation is still in progress.

https://www.archrproject.com/reference/addModuleScore.html

Demonstrated in #308 

Closing but let me know if this doesnt answer your question and sorry that this issue got lost.
