### ISSUE TITLE
grepExclude in plotTrajectoryHeatmap

### ISSUE THREAD

**Issue by atimms** [GreenleafLab/ArchR#400]
**Attach your log file**
ArchR has a built-in logging functionality for all complex functions. You MUST attach your log file (indicated in the console output) to this issue. Just drag and drop it here.
[ArchR-plotTrajectoryHeatmap-106cd6906cac0-Date-2020-11-04_Time-14-46-45.log](https://github.com/GreenleafLab/ArchR/files/5490863/ArchR-plotTrajectoryHeatmap-106cd6906cac0-Date-2020-11-04_Time-14-46-45.log)

**Describe the bug**
I'm trying to plot  trajectory heatmaps using plotTrajectoryHeatmap which is working well. However I want to remove the antisense gene so tried using grepExclude to remove them:

p2n <- plotTrajectoryHeatmap(trajGSM,  pal = paletteContinuous(set = "horizonExtra"), grepExclude = '-AS1')

I also tried implicitly adding in the genenames, but both ways I get the same plot.

Am i using the option incorrectly?

In addition I also wanted to remove anti-sense transcript from a Integrative pseudo-time analyses, so remove the gene and associated motif, would you mind suggesting a way to do that.

Thanks for your time.

Andrew

**Comment by biojiangke** [comment]
In addition to "grepExclude", the "labelMarkers", "labelRows" and "useSeqnames" all seem to be not working. However, "labelTop" option is working properly.

**Comment by jgranja24** [comment]
Hi @atimms this looks like a clearcut bug on my end.

I added this to the new release_1.0.1 branch.

```

  if(!is.null(grepExclude)){
    idxExclude <- grep(grepExclude, rownames(mat))
    if(length(idxExclude) > 0){
      mat <- mat[-grep(grepExclude, rownames(mat)), , drop = FALSE]
    }
  }


```

I just need to test it real quick and hopefully this solves your issue!
