### ISSUE TITLE
ArchR 1.0.0: Error in addGeneExpressionMatrix(): object 'se' not found

### ISSUE THREAD

**Issue by hypercompetent** [GreenleafLab/ArchR#402]
**Attach your log file**

[ArchR-addGeneExpressionMatrix-788e60750ffb-Date-2020-11-05_Time-18-51-46.log](https://github.com/GreenleafLab/ArchR/files/5496349/ArchR-addGeneExpressionMatrix-788e60750ffb-Date-2020-11-05_Time-18-51-46.log)

**Describe the bug**
When running `addGeneExpressionMatrix()`, ArchR is able to identify an overlap with scATAC and overlapping barcodes, then hits an error, reporting:
```
Error in assay(se) : object 'se' not found
```
This looks like it may come from MatrixGeneExpression.R, where `se` should be `seRNA` to match the rest of the function: 
https://github.com/GreenleafLab/ArchR/blob/2f022a448d8248a0f9afb33419bcbaeafe7731c0/R/MatrixGeneExpression.R#L76

**Screenshots**
![image](https://user-images.githubusercontent.com/6867922/98284373-e172a400-1f55-11eb-8ac7-398949dc8b5f.png)

Thanks! Looking forward to trying out the integration in ArchR!

Cheers,
-Lucas

**Comment by jgranja24** [comment]
Sorry about that this is now fixed in master! Thanks!!!
