### ISSUE TITLE
filter peaks by cells

### ISSUE THREAD

**Issue by Brawni** [GreenleafLab/ArchR#403]
Hi! 

Thanks once again for the great package and your help!
I subset the peak matrix extracted with getPeakMatrix(archPrj, 'PeakMatrix',, binarised=TRUE) and noticing that when I filter out peaks recurring in less than 1% of cells my list of peaks is much smaller than the one I get by importing the reproducible peak bed file in the PeakCalls folder for that cluster (~30k peaks vs ~100k). I can't seem to find any argument in the addReproduciblePeakSet() function for filtering peak regions with few fragments across cells. 
Does it make sense to filter out peak region represented only in a few cells per cluster or am I missing something?

Thank you!

**Comment by rcorces** [comment]
I'm not sure I 100% follow your question. Feel free to clarify if this answer does not help.
For clarity - I think the function you meant to refer to was `getMatrixFromProject()`?
When you say "peaks recurring in less than 1% of cells" you mean that less than 1% of cells have any insertion event in the given peak, right? 
The reproducible peak set is created based off of pseudobulk replicates. In this context, reproducibility means that the peak is called in multiple pseudobulk replicates. We dont typically filter peaks based off fragments in single cells. If you wanted to have more stringent per-cluster peak calls, you would change the `reproducibility` parameter in the `addReproduciblePeakSet()` function.

**Comment by Brawni** [comment]
I see! Yes I meant that function sorry! Yes that's what I meant....and now I can see how it makes more sense to control reproducibility at pseudo-bulk level.

Thanks!
