### ISSUE TITLE
Is it possible to filter bins in ArchR?

### ISSUE THREAD

**Issue by Ariel-TC** [GreenleafLab/ArchR#404]
Hi developers,
Thanks for your fantastic tool, it's versatile and powerful. 
One thing confused me is that could I modify the TileMatrix the ArchR generated? I mean can I filter some bins in TileMatrix to suit my data? I noticed that the only way to access TileMatrix is through `getMatrixFromProject` and I haven't figure out if there exists some approach to modify it like assignment or else directly. 
Thanks again for your brilliant work and hope for your answer!

**Comment by rcorces** [comment]
Currently, we dont provide methods for users to manipulate matrices like this. The matrices are stored in the Arrow files and manipulating them is not straightforward. For this reason, we let you export the matrix and play with it outside of ArchR.

I'm not sure exactly what you want to do with the TileMatrix. If you want to ignore certain tiles, you could always create a custom genome annotation and use an updated blacklist that blacklists those regions. This would exclude them from downstream operations based on the tile matrix.

I'm going to close this but feel free to post again if you'd like me to reopen it.

**Comment by Ariel-TC** [comment]
Thanks for your reply.
