### ISSUE TITLE
Single-cell tracks and bulk tracks not in the same order

### ISSUE THREAD

**Issue by MagpiePKU** [GreenleafLab/ArchR#406]
Hi @jgranja24 

Thank you for adding in the single cell fragment plot feature which is extremely handy. 

<img width="904" alt="Screen Shot 2020-10-27 at 7 52 26 PM" src="https://user-images.githubusercontent.com/25017655/97385017-17e15c80-188e-11eb-9349-c47243e244b6.png">

_Originally posted by @jgranja24 in https://github.com/GreenleafLab/ArchR/issues/228#issuecomment-717662407_

We tried the feature and there is a little bit of problem that rows are not sorted in the similar order. For example, in the following figure:

![image](https://user-images.githubusercontent.com/7695551/98417618-41835a80-20bc-11eb-9be3-f98f39781d3c.png)

The peaks are not arranged in the same order as the cells. In fact, the peaks followed the order given in 'useGroups' but the cells seems like to order like in natural character order. Could we modify that? Thanks a lot again. 

PS We wonder if we could insert some additional layer like multiple co-accessibility maps one-by-one in the bottom. 

Best,
Yi

**Comment by rcorces** [comment]
I'm adding the bug label to this. The panels in these plots should get ordered properly.

**Comment by jgranja24** [comment]
This is fixed -- 

```

devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.1", repos = BiocManager::repositories())

library(ArchR)
proj <- getTestProject()
proj$DummyClusters <- ArchR:::.splitEvery(proj$cellNames, 150) %>%
	{rep(seq_along(.), unlist(lapply(., length)))} %>%
		paste0("Cluster",.)

p <- plotBrowserTrack(proj, geneSymbol = "CD8A", groupBy = "DummyClusters", 
	plotSummary = c("bulkTrack", "scTrack", "geneTrack"), sizes = c(5,5,1))
plotPDF(p, file = "TestTrack")

```



<img width="883" alt="Screen Shot 2021-01-24 at 7 24 02 PM" src="https://user-images.githubusercontent.com/25017655/105657644-b96e4f00-5e79-11eb-8fb7-134569482cd6.png">
