### ISSUE TITLE
reproduciblePeaks.gr.rds files not organized into grouping sub-folders

### ISSUE THREAD

**Issue by Brawni** [GreenleafLab/ArchR#407]
Hello again,

It seems that the reproduciblePeaks.gr.rds files are not saved within sub-folders corresponding to the grouping factor like for insertion.coverage.h5 files. So if you run addReproduciblePeaks for two clustering groupings they get mixed up in the PeakCalls folder. 

Thank you

**Comment by rcorces** [comment]
This folder hierarchy issue has been addressed in the `dev` branch and will be incorporated in the upcoming stable `release_1.0.3`.
via https://github.com/GreenleafLab/ArchR/pull/1516/commits/bd77c78e9f333d8e97d0143359652d000697f14f
