### ISSUE TITLE
addClusters errr

### ISSUE THREAD

**Issue by yankiven** [GreenleafLab/ArchR#411]
Hello autor:
       I have 5000 cells, when i use `addClusters` function for clustering, i add the three parameters , `testBias = TRUE, filterBias = TRUE, biasClusters = 0.01` , for filtering cluster which contain cell number less than 50. In the clustering result, it is still have cluster less than 50. so why?

---
my code :
proj3 <- addClusters(input = proj2,
                         reducedDims = "IterativeLSI",
                         method = "Seurat",
                         name = "Clusters",
                         resolution = 1.0,
                         testBias = TRUE,
                         filterBias = TRUE,
                         biasClusters = 0.01,
                         force = TRUE)

**Comment by jgranja24** [comment]
```
#' @param biasClusters A numeric value between 0 and 1 indicating that clusters that are smaller than the specified proportion of total cells are
#' to be checked for bias. This should be set close to 0. We recommend a default of 0.01 which specifies clusters below 1 percent of the total cells.
```

This just tests if clusters less than or equal to 50 cells are biased i.e.  is it significantly enriched for cells based on the `biasCol` parameter. 

The parameter you are looking for is

```
#' @param nOutlier The minimum number of cells required for a group of cells to be called as a cluster. If a group of cells does not reach
#' this threshold, then the cells will be considered outliers and assigned to nearby clusters.
```

**Comment by jgranja24** [comment]
Closing this issue, feel free to open additional issues.
