### ISSUE TITLE
Best approach when using hashtagged cells?

### ISSUE THREAD

**Issue by koefoeden** [GreenleafLab/ArchR#414]
Hi!

Thanks for making such a brilliant package! I was wondering what approach you would recommend when using data from hashtagged cells (cell hashing using ASAP-seq that allows sample-multiplexing on the 10x lane)? The issue is that the sample-metadata column derived from the single fragment file cannot be overwritten (I suppose due to the way the data is stored in arrow-files), so assigning new sample labels for the cells after import does not seem feasible - and correct sample labels seem to be important for some of the downstream analyses. Would the best option be to split the fragment-files accordingly before? Or is there perhaps a better way after import, where cells have already been determined, making it easier to perform the sample-labelling?

Thank you!
Thomas

**Comment by rcorces** [comment]
You could do this before making Arrow files as you suggest. Alternatively, if you know how the 10x barcodes associate with your samples, then you can add an additional column to `cellColData` to track this. ArchR currently does not provide any native implementations to handle hashing. If you have an idea for how we could provide a universal implementation for hashing, feel free to suggest it.

**Comment by jgranja24** [comment]
You can use the `validBarcodes` in createArrows if you know which. The simplest suggestion is to do what @rcorces suggests. Just create an ArchRProject add to the `cellColData` and then you `subsetArchRProject`. This is probably the easiest procedure.

**Comment by jgranja24** [comment]
Please let us know if you have further questions by commenting/opening a new issue. I am closing this issue for now and hope your analysis goes as you hope!
