### ISSUE TITLE
How to avoid the loss of resolution in clustering  when Integrating with scRNA seq data

### ISSUE THREAD

**Issue by sylestiel** [GreenleafLab/ArchR#419]
<img width="969" alt="Screen Shot 2020-11-13 at 11 37 42 AM" src="https://user-images.githubusercontent.com/64283689/99103102-ac450200-25a4-11eb-9ffb-19473bcfdfd1.png">

1) I would like to **retain the cluster resolution from Constrained Integration** (predictedGroup_Co) because the step
labelNew <- colnames(cM)[apply(cM, 1, which.max)]
labelNew

is resulting in loss of clusters going from 10 to 5 upon remapping clusters.

2) I'm not clear on how the recategorization of clusters ("need to reclassify these new cluster labels to make a simpler categorization system") is working? Are we basing it on the post- or pre-integration scRNA-seq clusters?

 Thanks!

**Comment by rcorces** [comment]
This part of the tutorial is for illustrative purposes only. You should identify clusters however best fits your analysis.
