### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by hisplan** [GreenleafLab/ArchR#423]
Hi,

I saw the `release_1.0.0` branch merged into the `master` branch, but the latest release tag is still `v0.9.1-beta`. Would you please properly release a tag so that we can just work with the tag, rather than clone the repo, which could potentially include unwanted commits, causing irreproducibility?

Thanks!

**Comment by rcorces** [comment]
this is on our radar. we are working on it. Its worth noting that ArchR is still in beta. we will provide a stable release tag soon.
