### ISSUE TITLE
Change or set order of coverage panels in plotBrowserTrack()

### ISSUE THREAD

**Issue by RegnerM2015** [GreenleafLab/ArchR#427]
**Describe the problem that your feature request would address.**
I would like to manually set the order of browser coverage tracks in plotBrowserTrack(). I can specificy which group configuration with the groupBy parameter, but I would like to change the default order of these labels in BrowserTrack. 

**Describe the solution you'd like**
Can you suggest a method to change the order of the "identities" or cluster levels?

**Comment by jgranja24** [comment]
I will try to think of the best way to do this.

**Comment by shaka87** [comment]
You can get this to work with an ugly hack: rename the clusters so that their names are preceeded by numbers that indicate your desired order. For example 3_C1, 2_C2, 1_C3 for ordering them as C3, C2, C1.
