### ISSUE TITLE
Turning off pseudo-bulk replicates

### ISSUE THREAD

**Issue by aselewa** [GreenleafLab/ArchR#429]
Hi,

Forgive me if this has been asked before, but is there anywhere in the documentation that describes how to get a single pseudo-bulk insertion bed per cell-type and call macs 2on it? We dont have many cells and we'd like to call macs2 on all cells to increase coverage and thus power.

Thanks!

**Comment by rcorces** [comment]
Not the perfect solution yet but you can use `getFragmentsFromArrow()` and then merge the fragment files yourself and convert them into insertion beds.
https://www.archrproject.com/reference/getFragmentsFromArrow.html

The other alternative is to get a bigwig and call peaks on that using `getGroupBW()` but we havent documented that function yet.

**Comment by aselewa** [comment]
Ok thanks. I have a related question: I did my own differential accessibility analysis with edegR. Is there a way for me to add these to ArchR for downstream analysis? Thanks!

**Comment by rcorces** [comment]
No this is not currently possible (and also shouldnt be necessary given the capabilities of ArchR).

**Comment by aselewa** [comment]
ok thanks for your help :)
