### ISSUE TITLE
Error: Cannot have overlapping/missing cells in ATAC input, check 'groupList' argument!

### ISSUE THREAD

**Issue by sylestiel** [GreenleafLab/ArchR#432]
[ArchR-addGeneIntegrationMatrix-bbc5e0dc852-Date-2020-11-21_Time-00-15-10.log](https://github.com/GreenleafLab/ArchR/files/5577115/ArchR-addGeneIntegrationMatrix-bbc5e0dc852-Date-2020-11-21_Time-00-15-10.log)

proj2 <- addGeneIntegrationMatrix(
+     ArchRProj = proj2, 
+     useMatrix = "GeneScoreMatrix",
+     matrixName = "GeneIntegrationMatrix",
+     reducedDims = "IterativeLSI",
+     seRNA = seRNA,
+     addToArrow = FALSE, 
+     groupList = groupList,
+     groupRNA = "new.cluster.names",
+     nameCell = "predictedCell_Co",
+     nameGroup = "predictedGroup_Co",
+     nameScore = "predictedScore_Co"
+ )
ArchR logging to : ArchRLogs/ArchR-addGeneIntegrationMatrix-bbc52ada86b3-Date-2020-11-21_Time-00-15-20.log
If there is an issue, please report to github with logFile!
2020-11-21 00:15:20 : Running Seurat's Integration Stuart* et al 2019, 0.001 mins elapsed.
2020-11-21 00:15:20 : Checking ATAC Input, 0.004 mins elapsed.
Error in addGeneIntegrationMatrix(ArchRProj = proj2, useMatrix = "GeneScoreMatrix",  : 
  Missing 0 cells. Found 4901 overlapping cells from ArchRProj in groupList! Cannot have overlapping/missing cells in ATAC input, check 'groupList' argument!

**Comment by jgranja24** [comment]
Do you have overlapping cells in your groupList? I cant tell from this information. I would suggest seeing the tutorial!

**Comment by sylestiel** [comment]
Closing it for now. Will revisit if problem persists.  Thanks!
