### ISSUE TITLE
Encountered NaNs When using markerHeatmap() with motifMatrix

### ISSUE THREAD

**Issue by Sophiesze** [GreenleafLab/ArchR#441]
Hi GreenleafLab,

I was trying to draw a heatmap with motifmatrix and I encountered this issue. 

The log file was attached. Thank you in advance for you help!

Best,
Sophie

`markersMotif <- getMarkerFeatures(
     ArchRProj = proj,
     useMatrix = "MotifMatrix",
     groupBy = args$groupby,
     bias = c("TSSEnrichment", "log10(nFrags)"),
     testMethod = "wilcoxon",
     useSeqnames="deviations"
 )`

`heatmapMotif <- markerHeatmap(
  seMarker = markersMotif,
  cutOff = "FDR <= 0.01",
  transpose = TRUE
  #labelMarkers = motifs
  #log2Norm=F
)`

`plotPDF(heatmapMotif, name = "Motifdeviation-Marker-Heatmap", width = 8, height = 6, ArchRProj = proj, addDOC = FALSE)`

[ArchR-plotMarkerHeatmap-44285a00ebcb-Date-2020-11-27_Time-17-18-48.log](https://github.com/GreenleafLab/ArchR/files/5607793/ArchR-plotMarkerHeatmap-44285a00ebcb-Date-2020-11-27_Time-17-18-48.log)

<img width="870" alt="截屏2020-11-27 下午8 13 05" src="https://user-images.githubusercontent.com/53801318/100448240-f7a2f880-30ec-11eb-9815-bef45ab3dd09.png">

**Comment by rcorces** [comment]
> subscript out of bounds

This is your error. Presumably you are trying to access an element that does not exist in the matrix.

**Comment by Sophiesze** [comment]
Here is my code to print the motifmatrix heatmap, I was confused about the meaning of subscript out of bounds. Was it wrong because of the cutoff? Thank you.

![image](https://user-images.githubusercontent.com/53801318/100492333-f235c480-3165-11eb-80c2-6e5817aba936.png)

**Comment by rcorces** [comment]
I'm not able to reproduce this error with the tutorial dataset. It must be something related to your input SE and the cutoffs you have chosen. I would manually inspect the SE.
In the future, it is helpful if you do not paste screenshots of your commands but actually paste the text inside of code blocks. This lets us copy and paste from your issue rather than re-typing everything.

**Comment by Sophiesze** [comment]
I tried again. The reason might be the cutoff. It works now. Thank you so much!
