### ISSUE TITLE
There are more genes in scRNA-Seq data than in gene annotations of ArchR

### ISSUE THREAD

**Issue by LiYangSDU** [GreenleafLab/ArchR#443]
Sometimes, there are more than 30000 genes in the scRNA-Seq data, however, only 25017 genes are saved in the gene annotation of hg38.

How to deal with this situation? Should I filter genes in the scRNA-Seq data according to the gene annotation in ArchR?

**Comment by jgranja24** [comment]
ArchR uses only nuclear protein coding genes, while scRNA includes genes that are mitochondrial, ribosomal, non-coding, etc. These genes are not super informative for majority of analyses. You can always build a genome from hg38 including these if you wish.

Hope that helps

Jeff
