### ISSUE TITLE
Is there anyway to filter TSS and frags with different criteria among different samples

### ISSUE THREAD

**Issue by jin978347005** [GreenleafLab/ArchR#444]
Hi,

I have several samples with different ages and treatment, which have different patterns for the unique fragments and TSS enrichment plot, so I want to use different criteria for different samples. Is it possible to do this?

Thanks

**Comment by rcorces** [comment]
Run `createArrowFiles()` separately for each sample, using a different threshold. Then group them into an ArchRProject as normal. Please close this issue if this answers your question.
