### ISSUE TITLE
Extract peaks per cluster 

### ISSUE THREAD

**Issue by Seandelao** [GreenleafLab/ArchR#445]
Hello, 

I am trying to look at enrichment of overlap between SNPs and accessible peaks in my clusters/cell types. How can I extract my accessible peaks on a per cluster basis, so that I can look at enrichment in each cell type separately? Would it be like: 

1. Call peaks on full dataset with Macs2
2. Subset for each cell type
3. Extract peaks from each subsetted ArchR projects as .bed file

or 

1. Subset for each cell type
2. Call peaks on subsetted dataset with Macs2
3. Extract peaks from each subsetted ArchR projects as .bed file

Would option 2 then not allow me to do the all of the downstream analysis (since my original dataset will be spilt int multiple projects)? 

Thank you!

**Comment by rcorces** [comment]
Have you looked in the "PeakCalls" directory of your `ArchRProject`? That will contain summit calls for each sample and a list of reproducible peaks from each cell grouping used in `addReproduciblePeakSet()`

Please close this issue if that answers your question

**Comment by Seandelao** [comment]
@rcorces Got it! So the file I should get the peaks from is the 'X0-reproduciblePeaks.gr.rds' file?

**Comment by rcorces** [comment]
correct. those will be `GRanges` objects containing "reproducible" peaks from each of the groups indicated by the `groupBy` parameter and based on the `reproducibility` parameter passed to `addReproduciblePeakSet()`

**Comment by Seandelao** [comment]
@rcorces thanks!

**Comment by Seandelao** [comment]
@rcorces should the peaks taken from the "reproduciblePeaks.gr.rds" file match exactly with the aggregated peaks after adding the peaks matrix? I am noticing that if I do: 

``
celltype_0_peaks = readRDS("/Users/seandelao/Desktop/proj/PeakCalls/X0-reproduciblePeaks.gr.rds")
p <- plotBrowserTrack(
  ArchRProj = proj, 
  groupBy = "predictedGroup_Un", 
  geneSymbol = "GAPDH", 
  upstream = 100000,
  downstream = 100000,
  features = GRangesList(TrackA = getPeakSet(proj), TrackB = celltype_0_peaks))
grid::grid.newpage()
grid::grid.draw(p$`GAPDH`)
``

the peaks from the "celltype_0_peaks" don't quite line up with the peaks from "getPeakSet(proj)"; any reason this might be?

Thanks!

**Comment by Seandelao** [comment]
![Screen Shot 2020-12-13 at 11 36 57 PM](https://user-images.githubusercontent.com/32523142/102053185-2af7af80-3d9c-11eb-9288-8c7cda3a1c06.png)
Here is an example of what I mean, where you can see some of the peaks from the "celltype_0_peaks" in blue don't quite match up with the red peaks from "getPeakSet(proj)"

**Comment by rcorces** [comment]
This is expected. You should read this page for a description of how the iterative overlap procedure creates the final peak set.
https://www.archrproject.com/bookdown/the-iterative-overlap-peak-merging-procedure.html

The part that is not explained there (and I will add during the next documentation update) is that first we make peak sets per group using iterative overlap. Then we take all groups and make a union peak set again using iterative overlap.

Close if this answers your question.

**Comment by Larrycpan** [comment]
> This is expected. You should read this page for a description of how the iterative overlap procedure creates the final peak set. https://www.archrproject.com/bookdown/the-iterative-overlap-peak-merging-procedure.html
> 
> The part that is not explained there (and I will add during the next documentation update) is that first we make peak sets per group using iterative overlap. Then we take all groups and make a union peak set again using iterative overlap.
> 
> Close if this answers your question.

Thanks for your reply. But I am wondering which peak set is more correct? gr.rds or the peakset after using the function `addPeakMatrix`?

**Comment by simonmfr** [comment]
Same question, would appreciate a reply!
