### ISSUE TITLE
naming peakSet / peakMatrix

### ISSUE THREAD

**Issue by Brawni** [GreenleafLab/ArchR#449]
Hello again!

I was wondering whether it would be possible to assign names to peakSets and peakMatrices when they are generated similarly to passing the name argument in the `addDeviationMatrix` function  so that if you add another peakSet later with force=TRUE you could still come back to the previous one with `addPeakSet` by specifying the name of that peakSet. Ideally that would also load the relative peakMatrix when available. Do you think it makes sense?

Thanks for your great support!

**Comment by rcorces** [comment]
This would require a bit of a re-work on how peaksets are managed. But I dont think you are alone in wanting the ability to work with multiple peak sets. I think this is worth considering.

**Comment by jgranja24** [comment]
Hi @Brawni, I am not sure it would be easy to maintain multiple peak sets at this time. I would simply just name the deviations matrix with a naming scheme for you. You can save your peakSets and easily use `addPeakSet` to replace this. Also you can use `addFeatureMatrix(ceiling = 4)` (these are the same parameters as `addPeakMatrix`) to make the peak matrix. Sorry that this isnt super easy but I do think that naming conventions would be your best bet!

Best

Jeff
