### ISSUE TITLE
Making Pseudo-bulk Replicates:  addGroupCoverages  error

### ISSUE THREAD

**Issue by coffeeCowLu** [GreenleafLab/ArchR#450]
ArchR_1.0.0
projHeme3 <- addGroupCoverages(ArchRProj = projHeme2, groupBy = "Clusters")
[ArchR-addGroupCoverages-55b36555ee385-Date-2020-12-04_Time-09-16-50.log](https://github.com/GreenleafLab/ArchR/files/5640145/ArchR-addGroupCoverages-55b36555ee385-Date-2020-12-04_Time-09-16-50.log)

**addArchRThreads(12)::**
...
020-12-04 09:03:05 : Group C17._.Other (70 of 70) : Creating Group Coverage File : C17._.Other.insertions.coverage.h5, 6.314 mins elapsed.
2020-12-04 09:04:26 : Adding Kmer Bias to Coverage Files!, 7.663 mins elapsed.
Warning in mclapply(..., mc.cores = threads, mc.preschedule = preschedule) :
  70 function calls resulted in an error

Error in .safelapply(seq_along(ArrowFiles), function(x) { (archr_dev_pip.R#474): 
Error Found Iteration 1 : 
	[1] "Error in H5Fopen(file, \"H5F_ACC_RDONLY\", native = native) : \n  HDF5. File accessibilty. Unable to open file.\n"
	<simpleError in H5Fopen(file, "H5F_ACC_RDONLY", native = native):HDF5. File accessibilty. Unable to open file.>
Error Found Iteration 2 : 
...

**addArchRThreads(1)::**
...
2020-12-04 09:51:56 : Group C17._.Other (70 of 70) : Creating Group Coverage File : C17._.Other.insertions.coverage.h5, 35.098 mins elapsed.
2020-12-04 09:53:02 : Adding Kmer Bias to Coverage Files!, 36.193 mins elapsed.

Error in H5Fopen(file, "H5F_ACC_RDONLY", native = native) (archr_dev_pip.R#476): HDF5. File accessibilty. Unable to open file.
Show stack trace

**> sessionInfo()**
R version 3.6.3 (2020-02-29)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

**code:**
    h5disableFileLocking()
    .logDiffTime(sprintf("Creating Coverage Files!"), tstart,
        addHeader = FALSE)
    batchOut <- .batchlapply(args)
    coverageFiles <- lapply(seq_along(batchOut), function(x) batchOut[[x]]$covFile) %>%
        unlist
    nCells <- lapply(seq_along(batchOut), function(x) batchOut[[x]]$nCells) %>%
        unlist
    nFragments <- lapply(seq_along(batchOut), function(x) batchOut[[x]]$nFragments) %>%
        unlist
    **h5enableFileLocking()**
    coverageMetadata <- DataFrame(Group = stringr::str_split(names(unlistGroups),
        pattern = "\\._.", simplify = TRUE)[, 1], Name = names(unlistGroups),
        File = coverageFiles, nCells = nCells, nInsertions = nFragments *
            2)
    .logDiffTime(sprintf("Adding Kmer Bias to Coverage Files!"),
        tstart, addHeader = FALSE)
    o <- .**addKmerBiasToCoverage**(coverageMetadata = coverageMetadata,
        genome = getGenome(ArchRProj), kmerLength = kmerLength,
        threads = threads, verbose = FALSE, logFile = logFile)
    **ArchRProj**@projectMetadata$GroupCoverages[[groupBy]] <- SimpleList(Params = Params,
        coverageMetadata = coverageMetadata)
    .logDiffTime(sprintf("Finished Creation of Coverage Files!"),
        tstart, addHeader = FALSE)
    .endLogging(logFile = logFile)

There may be something wrong with the code, how can I solve it?

**Comment by rcorces** [comment]
I'm not sure if this applies to this specific instance but these HDF5 errors seems to be sporadic and environment specific. Have you run into any hdf5 errors in other parts of ArchR?

**Comment by coffeeCowLu** [comment]
@rcorces In other parts i use command(Sys.setenv(HDF5_USE_FILE_LOCKING = "FALSE") or h5disableFileLocking()) to solve it, but  this time not funciton.

I noticed that the hdf5 file (h5enableFileLocking()) was locked when I called this function.
 Can I comment out that line of command?

**Comment by rcorces** [comment]
You can try. @jgranja24 knows this stuff better than I do.

**Comment by jgranja24** [comment]
Errr why would you want it to be FALSE? If its false you cant parallel write to the same file at the same time. Setting the threads = 1 is the only way to ensure this doesnt happen?

**Comment by coffeeCowLu** [comment]
@rcorces thank you very much. @jgranja24  
if not FALSE,  An error  (HDF5 File accessibilty. Unable to open file) will be reported while reading the saved RDS file.

**Comment by coffeeCowLu** [comment]
@jgranja24 
@jgranja24 
I feel to add command h5disableFileLocking() before
ArchRProj@projectMetadata$GroupCoverages[[groupBy]] <- SimpleList(Params = Params, coverageMetadata = coverageMetadata)
may solve the problem in the addGroupCoverages function.

But I'm not sure if it makes sense.

**Comment by jgranja24** [comment]
I see what you are referring to now. I think you are correct and I should have put it lower.

I updated the release_1.0.1 branch ---

`devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.1", repos = BiocManager::repositories())
`

This is the fix similar to your suggestion?


```

  #Disable Hdf5 File Locking
  h5disableFileLocking()

  #Batch Apply
  .logDiffTime(sprintf("Creating Coverage Files!"), tstart, addHeader = FALSE)
  batchOut <- .batchlapply(args)
  coverageFiles <- lapply(seq_along(batchOut),function(x) batchOut[[x]]$covFile) %>% unlist
  nCells <- lapply(seq_along(batchOut),function(x) batchOut[[x]]$nCells) %>% unlist
  nFragments <- lapply(seq_along(batchOut),function(x) batchOut[[x]]$nFragments) %>% unlist

  #Add To Project
  coverageMetadata <- DataFrame(
    Group = stringr::str_split(names(unlistGroups), pattern = "\\._.", simplify=TRUE)[,1],
    Name = names(unlistGroups), 
    File = coverageFiles,
    nCells = nCells,
    nInsertions = nFragments * 2
  )

  #####################################################
  # Compute Kmer Bias for each coverage file!
  #####################################################
  .logDiffTime(sprintf("Adding Kmer Bias to Coverage Files!"), tstart, addHeader = FALSE)
  o <- .addKmerBiasToCoverage(
    coverageMetadata = coverageMetadata, 
    genome = getGenome(ArchRProj), 
    kmerLength = kmerLength, 
    threads = threads,
    verbose = FALSE,
    logFile = logFile
  )

  ArchRProj@projectMetadata$GroupCoverages[[groupBy]] <- SimpleList(Params = Params, coverageMetadata = coverageMetadata)

  #Enable Hdf5 File Locking
  h5enableFileLocking()


```

**Comment by coffeeCowLu** [comment]
@jgranja24 
you are right, 
if the middle function body no longer contains h5enableFileLocking() between commd h5disableFileLocking()
and h5enableFileLocking().

**Comment by l-magnificence** [comment]
In ArchR 1.0.1, when I run addGroupCoverages(ArchRProj = proj1_select, groupBy = "name"), it occurs 
```
ArchR logging to : ArchRLogs/ArchR-addGroupCoverages-f52442be8a8e-Date-2021-09-09_Time-23-41-21.log
If there is an issue, please report to github with logFile!
2021-09-09 23:41:33 : Creating Coverage Files!, 0.19 mins elapsed.
2021-09-09 23:41:33 : Batch Execution w/ safelapply!, 0.19 mins elapsed.
Error in (function (..., threads = 1, preschedule = FALSE)  : 
Error Found Iteration 1 : 
	[1] "Error in H5Fopen(file, flags = flags, fapl = fapl, native = native) : \n  HDF5. File accessibility. Unable to open file.\n"
	<simpleError in H5Fopen(file, flags = flags, fapl = fapl, native = native): HDF5. File accessibility. Unable to open file.>
Error Found Iteration 2 : 
	[1] "Error in H5Fopen(file, flags = flags, fapl = fapl, native = native) : \n  HDF5. File accessibility. Unable to open file.\n"
	<simpleError in H5Fopen(file, flags = flags, fapl = fapl, native = native): HDF5. File accessibility. Unable to open file.>
```
When I set threads =1, it work fine but need much time
I don't  know how to run it in multi threads?

**Comment by will-NYGC** [comment]
I'm having this same problem. Recently just updated to 1.0.1 and is the first time I'm seeing this error. Tried recreating my arrow files in case they were corrupted but did not fix. Does work with threads=1.
