### ISSUE TITLE
createArrowFiles() failed with tutorial data

### ISSUE THREAD

**Issue by weichen123hahah** [GreenleafLab/ArchR#452]
Hello! 
I use R4.0.2 under CentOS release 6.9 to following the tutorial，but I meet a error，I don't konw how to solve the problem
![image](https://user-images.githubusercontent.com/38218230/101239281-57b72180-3721-11eb-99fe-e2ba13982270.png)
![image](https://user-images.githubusercontent.com/38218230/101239291-66053d80-3721-11eb-8f8c-93520abdf718.png)

**Comment by rcorces** [comment]
I've never seen this error before. When you say "following the tutorial" do you mean using the tutorial data or following the steps of the tutorial on your own data?
My first advice is to switch to R version 3.6.* instead of 4.* because we are still working through issues related to R version 4.
