### ISSUE TITLE
Can I transfer the results of integrative clustering on scRNA-Seq and scATAC-Seq into ArchR

### ISSUE THREAD

**Issue by LiYangSDU** [GreenleafLab/ArchR#455]
Do not use this form to report a bug in ArchR! Instead, use the "Bug report" option.

PLEASE FILL OUT THE RELEVANT INFORMATION AND DELETE THE UNUSED PORTIONS OF THIS ISSUE TEMPLATE.

**Describe the problem that your feature request would address.**
For example, I have simultaneously clustered cells in matched scRNA-Seq and scATAC-Seq into cell clusters. I want to use ArchR for downstream analyses based on the dimensions and clusters. 

**Describe the solution you'd like**
I think ArchR could have such a function, that is, admit users transfer the cell clusters and dimensions into ArchR, maybe in Seurat object.

**Comment by rcorces** [comment]
Apologies for the delay in reply.
This is currently possible but is a manual process.

To import cell clusters, you just need to add a new column to `cellColData` containing your new cluster annotations. You will need to match based on the cell name which may or may not be consistently stored in your Seurat analysis so this is something to be careful of.

To import embedding coordinates (which I think is what you want to do?) you would do something like this. You create a new dataframe in the exact format shown below, importing dimension 1 and 2 of your embedding. You then add this to the `embeddings` present in your project. 
```
df <- DataFrame(row.names=proj2$cellNames, "custom#UMAP1" = colData2$UMAP1, "custom#UMAP2" =  colData2$UMAP2, check.names = FALSE)
proj2@embeddings$customUMAP <- SimpleList(df = df, params = list())
```

If this answers your question, please feel free to close this issue. If not, let me know.
