### ISSUE TITLE
what's the difference between GeneScoreMatrix and GeneIntegrationMatrix?

### ISSUE THREAD

**Issue by Dragonlongzhilin** [GreenleafLab/ArchR#456]
After integrating the scATAC and scRNA-seq by ArchR, I found a new matrix - GeneIntegrationMatrix. But I don't know what the different compared to GeneScoreMatrix.

**Comment by rcorces** [comment]
This information should be clear from the manual. https://www.archrproject.com/bookdown/index.html

In the future, please use the provided issue templates to submit an issue. In the case of documentation, this forces you to tell us where you have looked to find this information, which often results in you finding the information if it already exists. I'm closing this. If you are unable to find the information that you look for, please open a new issue and use the provided template.
