### ISSUE TITLE
Adding scCITEseq data to ArchRproject

### ISSUE THREAD

**Issue by NoemieL** [GreenleafLab/ArchR#458]
Hello, 
I have both scCITEseq and scATACseq data. I know how to add scRNAseq data to my ArchR project but I wandering to know if there is a way to put the information regarding the surface cell protein data present in the scCITEseq either separately from the scRNAseq data extracted from scCITEseq or either both at the same time.
I saw in your paper from Nat Biotech from december 2019, you performed analysis with both scCITEseq and scRNAseq but It was not done with ArchR and I don't know how to include it to my ArchR project.

Thank you very much in advances

Noemie

**Comment by rcorces** [comment]
I dont believe there is an easy way to do this just yet. I'm going to change your issue label to enhancement. Will try to make this possible in a future release.

**Comment by jgranja24** [comment]
The predicted cell label is present in the ArchRProject. At the moment there is no real functionality, however you can get the predicted RNA cell and get the UMAPs and use the `ggHex` or `ggPoint` function. I dont believe we did much besides something like that in the NBT paper. If you have more specific usage Id be happy to hear about it.
