### ISSUE TITLE
How to plot gene labels in P2G links Heatmaps and geom points in Volcano plots?

### ISSUE THREAD

**Issue by sylestiel** [GreenleafLab/ArchR#459]
@jgranja24 

While plotting ATAC and RNA heatmaps based on Kmeans in the peak-to-genes heatmaps how can i get it to display the gene names?

### When I write to csv I still cannot figure out which gene belongs to which Kmeans? 
Is there some way to get at that information?

Similarly, I would like the significant TF geom points to render with labels. 
Can you kindly suggest the script for each of these.

Many thanks!!

**Comment by rohitrrj** [comment]
@sylestiel: I am trying this too, can you post the solution.

**Comment by sylestiel** [comment]
@rohitrrj @rcorces 
I have to figure out how to fine the features corresponding to the k-means yet.
Sorry!
