### ISSUE TITLE
Motif Analysis

### ISSUE THREAD

**Issue by e-arslan** [GreenleafLab/ArchR#460]
What is the reason to get a slightly different TF ranking on motif analysis when I run the code at different times? 

Here are the steps before TF ranking at different runs:
1. loadArchRProject
2. addGroupCoverages
3. addReproduciblePeakSet
4. addPeakMatrix
5. addMotifAnnotations
6. getMarkerFeatures
7. peakAnnoEnrichment

**Comment by rcorces** [comment]
I believe what you are seeing is a result of randomization during the `addGroupCoverages()` function. This function creates pseudo-bulked replicates based on the parameters that you designate and there is randomization involved in how groups of cells are selected. The results *should* be very similar albeit not identical though.

Please close this issue if this has answered your question.

**Comment by e-arslan** [comment]
thanks for the answer.
