### ISSUE TITLE
peak annotation

### ISSUE THREAD

**Issue by Dragonlongzhilin** [GreenleafLab/ArchR#462]
I found the ratio of peak type in peakSet matrix was different with ChIPSeeker result, especific ratio of promoter.
addReproduciblePeakSet result
![image](https://user-images.githubusercontent.com/33304280/101850660-2a40fc80-3b95-11eb-9ca0-070732f83e2f.png)
annotate the peak using ChipSeeker.
![image](https://user-images.githubusercontent.com/33304280/101893466-c1cb3d00-3bdf-11eb-9cbc-f2b5f40352f6.png)

Can I use the other tool to annotate the peak? 
Could you provide more or specific annotation information in ArchR?

**Comment by jgranja24** [comment]
The annotation isnt used besides for labeling purposes. Feel free to use ChIPseeker if thats what you want. 
ArchR has an option for promoter region `promoterRegion = c(2000, 100)`. This also depends on the gene annotation file as well. 

Hope that helps

Jeff
