### ISSUE TITLE
addPeak2GeneLinks with multiome data

### ISSUE THREAD

**Issue by graciegordon** [GreenleafLab/ArchR#463]
Hello,

I've been trying some of the multiome functionality in ArchR, I've generally had good results, but have run into an issue with addPeak2GeneLinks(). In issue #361 it is suggested that this function should work with multiome data, but it seems as though the function relies on a PredictionScore value that is generated by the addGeneIntegrationMatrix() function, which doesn't seem relevant to multiome data. This behavior is consistent when using the 10x PBMC dataset, as well as datasets that have been produced in house. It also persists on master as well as the release_1.0.1. 

Picking up from the end of the multiome example code provided [here](https://greenleaflab.github.io/ArchR_2020/Ex-Analyze-Multiome.html) I ran the following code.

```
pathToMacs2 <- findMacs2()

proj <- addGroupCoverages(ArchRProj = proj, groupBy = "Clusters")

proj <- addReproduciblePeakSet(
    ArchRProj = proj, 
    groupBy = "Clusters", 
    pathToMacs2 = pathToMacs2
)

proj<-addPeakMatrix(
  ArchRProj = proj,
  ceiling = 4,
  binarize = FALSE,
  verbose = TRUE,
  threads = getArchRThreads(),
  parallelParam = NULL,
  force = TRUE,
  logFile = createLogFile("addPeakMatrix")
)


proj <- addPeak2GeneLinks(
  ArchRProj = proj,
  reducedDims = "LSI_Combined",
  useMatrix = "GeneExpressionMatrix",
  dimsToUse = 1:30,
  scaleDims = NULL,
  corCutOff = 0.75,
  k = 100,
  knnIteration = 500,
  overlapCutoff = 0.8,
  maxDist = 250000,
  scaleTo = 10^4,
  log2Norm = TRUE,
  predictionCutoff = 0.4,
  seed = 1,
  threads = max(floor(getArchRThreads()/2), 1),
  verbose = TRUE,
  logFile = createLogFile("addPeak2GeneLinks")
)
```

This failed with the following trace:
<img width="722" alt="Screen Shot 2020-12-11 at 12 53 24 PM" src="https://user-images.githubusercontent.com/32146875/101954039-4605cc00-3bb0-11eb-8ab1-b23fcd81ef20.png">

Here is my logfile: [ArchR-addPeak2GeneLinks-26491f6474ff-Date-2020-12-11_Time-11-40-22.log](https://github.com/GreenleafLab/ArchR/files/5681528/ArchR-addPeak2GeneLinks-26491f6474ff-Date-2020-12-11_Time-11-40-22.log)

**Comment by rcorces** [comment]
Thanks for reporting this. We're still working on solidifying the multiome workflows. @jgranja24 would be the one to answer this question.

**Comment by jgranja24** [comment]
I just added a fix in 1.0.1

```
  dfAll <- .safelapply(seq_along(ArrowFiles), function(x){
    cNx <- paste0(names(ArrowFiles)[x], "#", h5read(ArrowFiles[x], paste0(useMatrix, "/Info/CellNames")))
    pSx <- tryCatch({
      h5read(ArrowFiles[x], paste0(useMatrix, "/Info/predictionScore"))
    }, error = function(e){
      message("No predictionScore found. Continuing without predictionScore!")
      rep(9999999, length(cNx))
    })
    DataFrame(
      cellNames = cNx,
      predictionScore = pSx
    )
  }, threads = threads) %>% Reduce("rbind", .)
```

To install 

`devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.1", repos = BiocManager::repositories())
`

Please let me know if this works!

Best

Jeff

**Comment by graciegordon** [comment]
That fixed it, thank you! I also confirmed that the downstream plotting functionality works with the fix.

Best,
Gracie

**Comment by markphillippebworth** [comment]
hey! I'm trying to install version 1.0.1 to fix this issue. Unfortunately, I can't install from devtools.

installing to /home/markphillip_pebworth/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-ArchR/00new/ArchR/libs
** R
Error in parse(outFile) : 
  /tmp/RtmpI4JEty/R.INSTALL9fd6973cc31/ArchR/R/GlobalDefaults.R:50:10: unexpected symbol
49:     }
50:   },erro r
             ^
ERROR: unable to collate and parse R files for package ‘ArchR’
* removing ‘/home/markphillip_pebworth/R/x86_64-pc-linux-gnu-library/3.6/ArchR’
Error: Failed to install 'ArchR' from GitHub:
  (converted from warning) installation of package ‘/tmp/Rtmpe2EM5z/file9656028338c/ArchR_1.0.1.tar.gz’ had non-zer
o exit status

This stackoverflow question illustrates what might be causing the issue, and I'm not finding anyway to fix it on this side.
https://stackoverflow.com/questions/56471638/error-unable-to-collate-and-parse-r-files-for-package-upload-to-cran

**Comment by rcorces** [comment]
this was probably a bug generated from recent commits. I think from this typo:
https://github.com/GreenleafLab/ArchR/blob/753f63b3028827b714df1f8a51c4bacbf0545fbc/R/GlobalDefaults.R#L50

This should now be fixed.

**Comment by madi4** [comment]
Hello,

I am trying to install version 1.0.1 as well to fix the issue with addPeak2GeneLinks and encountered a similar issue to the mentioned by markphillippebworth:

installing to /home/adi/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-ArchR/00new/ArchR/libs
** R
Error in parse(outFile) : 
  /tmp/RtmpG0rNfm/R.INSTALLa6b7465f723a/ArchR/R/CreateArrow.R:1944:11: unexpected '}'
1943:             
1944:           }
                ^
ERROR: unable to collate and parse R files for package ‘ArchR’
* removing ‘/home/adi/R/x86_64-pc-linux-gnu-library/3.6/ArchR’
* restoring previous ‘/home/adi/R/x86_64-pc-linux-gnu-library/3.6/ArchR’
Error: Failed to install 'ArchR' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmpyrW68r/file541024c0f155/ArchR_1.0.1.tar.gz’ had non-zero exit status

I tried a few things but with no success on my end.
Would appreciate your assistance,
Adi

**Comment by rcorces** [comment]
@madi4 - this is a typo introduced in a recent commit. It should be fixed now. let us know

@jgranja24 - I fixed this just now in https://github.com/GreenleafLab/ArchR/commit/7a1d4fc950f4b9a78ec74280be3236284cc28b9e

**Comment by markphillippebworth** [comment]
It works for me now. Thank you!

**Comment by madi4** [comment]
@rcorces It works for me as well, thank you very much!
