### ISSUE TITLE
normalization method used in the plotBrowserTrack()

### ISSUE THREAD

**Issue by yankiven** [GreenleafLab/ArchR#466]
Hello autho：
Can you explain the details of the normalization method used in the plotBrowserTrack() function?

**Comment by rcorces** [comment]
The normalization method is based on a column in `cellColData` which is provided as an argument to the `normMethod` parameter:

> The name of the column in cellColData by which normalization should be performed. The recommended and default value is "ReadsInTSS" which simultaneously normalizes tracks based on sequencing depth and sample data quality.
