### ISSUE TITLE
Add custom colours?

### ISSUE THREAD

**Issue by MRogne007** [GreenleafLab/ArchR#468]
Hi Developers,

Is it possible for me to add custom colours ty my ArchR UMAPs, heat maps ect?

Kindest Regards
Marie

**Comment by rcorces** [comment]
From the function doc for `plotEmbedding()` and the `pal` param:

> A custom palette (see paletteDiscrete or ArchRPalettes) used to override discreteSet/continuousSet for coloring vector.

You can pass any user defined palette to this argument though you should format is like the palettes already present in `ArchRPalettes` as a named vector with the names being numbers. These numbers define the order in which the colors of the palette would be used if called as a discrete set. This allows you to use the most distinct colors first.

```
> test1 <- ArchRPalettes$stallion
> plotEmbedding(ArchRProj = projTest, embedding = "UMAP", colorBy = "cellColData", name = "Sample", pal = test1)
```

Please close if this answers your question.

**Comment by MRogne007** [comment]
Thank you for clarifying and quick reply!
