### ISSUE TITLE
addMotifAnnotations

### ISSUE THREAD

**Issue by rojinsafavi** [GreenleafLab/ArchR#469]
Is it possible to run addMotifAnnotations on tilematrix instead of peakmatrix?

**Comment by rcorces** [comment]
well, you could create a tiled `GRanges` object and replace your peakset with it using `addPeakSet()` but I dont think that would be recommended.

I'm not sure what the goal of getting motif annotations on the tilematrix would be? Maybe you have a particular tile that you are interested in and it doesnt come up in the peak set? Seems like if you want to know the locations of motifs genome wide there are ways to do that outside of ArchR so maybe you have another use case in mind.
