### ISSUE TITLE
Fixinging ATAC signal Range for a given marker in different samples

### ISSUE THREAD

**Issue by sylestiel** [GreenleafLab/ArchR#474]
Is there a way to keep the **Normalized ATAC signal range  in Coverage Plots** the same for samples processed separately in Arch R. The goal being to make a fair comparison between the different samples. This is in addition to keeping the cor cutoff the same.
Alternatively, does ArchR allow Merged analysis of samples representing different conditions or treatments.

Thank you!

**Comment by rcorces** [comment]
I'm not sure that I fully understand your question so let me know if this helps. Theoretically, if you use the same parameters (especially the `normMethod`) for plotting, then I think the tracks should be essentially comparable across projects. But I dont know that I would do this. 

> Alternatively, does ArchR allow Merged analysis of samples representing different conditions or treatments.

ArchR does **not** allow merging of samples from different ArchRProject objects if that is what you are asking. You can "merge" different samples/clusters/conditions within the same ArchRProject by creating new columns in `cellColData` and using the `groupBy` parameter to point to that column.

Please close this issue if this answers your question.

**Comment by sylestiel** [comment]
With regard to the second option:

How do I create new columns in cellColData?
At which point would I do so?
Do i read in the samples sequentially?
How many replicates per condition are allowed?

Need a few more pointers since I'm not familiar with scripting.

**Comment by rcorces** [comment]
I think you may have misinterpreted my response.

`cellColData` is essentially a dataframe of information where columns are metadata and rows are individual cells. For example "Samples" and "Clusters" are columns in `cellColData`. You can group your cells aribtrarily by creating new columns in `cellColData` and passing that column to the `groupBy` parameter which exists in a variety of functions. If this is not clear, you should read/re-read the manual.

You can add columns to `cellColData` by standard R manipulations or by using the `addCellColData()` function:
https://www.archrproject.com/reference/addCellColData.html

This is detailed here:
https://www.archrproject.com/bookdown/manipulating-an-archrproject.html

**Comment by sylestiel** [comment]
Thank you!
