### ISSUE TITLE
negative value in PWM in analysis the TF enrichment

### ISSUE THREAD

**Issue by Dragonlongzhilin** [GreenleafLab/ArchR#476]
When using the ChromVAR (function: addMotifAnnotations(motifSet = "cisbp"), addDeviationsMatrix), I found that there are many negative value in the PWM matrix (TFBSTools::Matrix(getPeakAnnotation(projRenal, "Motif")$motifs)). I don't know why? 
in this case, I can't plot the figure using seqLogo function, like this:
![image](https://user-images.githubusercontent.com/33304280/102713438-351d2f00-4303-11eb-96b7-7f68add0d9ae.png)

**Comment by jgranja24** [comment]
Hi @Dragonlongzhilin,

I think you are confused about a PWM.

A PWM is a log2 weight matrix -- https://en.wikipedia.org/wiki/Position_weight_matrix.

To convert a PWM to a probability matrix -- 

```

PWMatrixToProbMatrix <- function(x){
	if (class(x) != "PWMatrix") stop("x must be a TFBSTools::PWMatrix object")
	(2^as(x, "matrix"))*TFBSTools::bg(x)/sum(TFBSTools::bg(x))
}
```
