### ISSUE TITLE
Is running of co-accessibility and peak-to-gene links interdependant?

### ISSUE THREAD

**Issue by sylestiel** [GreenleafLab/ArchR#477]
1) Do we need to match the resolution parameter on the two analyses?

2) Does decreasing the resolution in co-accessibility step reduce the number of P2G links identified?

Thanks!

**Comment by rcorces** [comment]
The difference between co-accessibility and peak-to-gene links is well spelled out in the manual (at least in my opinion). If you have questions on documentation (and generally for any issue) please use the issue templates that we have set up. In your case, this would ask you where you have looked in the manual and where you think the documentation should belong, which may have prompted you to find your own answer.

https://www.archrproject.com/bookdown/co-accessibility-with-archr.html
https://www.archrproject.com/bookdown/peak2genelinkage-with-archr.html

If you dont find your answer in one of those locations, feel free to open a new issue using the proper issue template.

**Comment by sylestiel** [comment]
I'm not seeing a change in gene-to-peak links when I changed the resolution from 10,000 to 1000. Hence my question.

Wondering if I was doing something wrong.
