### ISSUE TITLE
Error in addBgdPeaks: different row counts implied by arguments

### ISSUE THREAD

**Issue by rargelaguet** [GreenleafLab/ArchR#484]
Hello,

I manually added peak annotations using:
```
peaks.dt <- fread(".../E8.5_peaks_archR_macs2.bed") %>%
  setnames(c("chr","start","end")) %>%
  .[,id:=sprintf("%s:%s-%s",chr,start,end)]

peaks.granges <- makeGRangesFromDataFrame(peaks.dt, keep.extra.columns = T)
ArchRProject.filt <- addPeakSet(ArchRProject.filt, peaks.granges)
```

which works fine and `getPeakSet(ArchRProject.filt)` returns the expected output:
```
GRanges object with 192320 ranges and 2 metadata columns:
           seqnames              ranges strand |                     id       idx
              <Rle>           <IRanges>  <Rle> |            <character> <integer>
       [1]     chr1     3062675-3063275      * |   chr1:3062675-3063275         1
       [2]     chr1     3191054-3191654      * |   chr1:3191054-3191654         2
```

But when running the `addBgdPeaks` function as follows:

```
ArchRProject.filt <- addBgdPeaks(
  ArchRProject.filt,
  nIterations = 50,
  w = 0.1,
  binSize = 50,
  method = "chromVAR",
  seed = 42
)
```

 I do get an error and I can't figure out why. There doesn't seem to be a log file for this
```
Identifying Background Peaks!
Error in DataFrame(bias = rS$GC, start = rS$start, end = rS$end) : 
  different row counts implied by arguments
```

Thanks for your help.
Ricard

**Comment by rcorces** [comment]
Hi @rargelaguet 

I believe this is the same problem reported in #448 
The `addPeakSet()` function in ArchR_1.0.0 does not recompute the GC content. This has been updated in 1.0.1 but I believe from your log on your other post that you are using 1.0.0

You can either upgrade to 1.0.1 which is still in dev or use the function shown in #448 . Of course, you will have to re-add the peak set with the new function.

Hopefully that solution works for you. I'm closing this issue under the assumption that it will but if not, just comment again and I'll re-open.

**Comment by rargelaguet** [comment]
That works Ryan, thank you.
