### ISSUE TITLE
features argument in addGeneIntegrationMatrix

### ISSUE THREAD

**Issue by SaskiaFreytag** [GreenleafLab/ArchR#488]
Hi,

I have been trying to using with features addGeneIntegrationMatrix with features specified (forwarded to Seurat::TransferData). Unfortunately this runs into an error. I believe the features argument is specified multiple times in the function. Would you be able to fix this?

I have attached the log files.

[ArchR-addGeneIntegrationMatrix-7162d18252c-Date-2021-01-12_Time-13-38-19.log](https://github.com/GreenleafLab/ArchR/files/5800016/ArchR-addGeneIntegrationMatrix-7162d18252c-Date-2021-01-12_Time-13-38-19.log)

Thank you,

Saskia

**Comment by SaskiaFreytag** [comment]
It seems the log file does not report the full error message that I am getting in my R console. So here is the message being reported:
`2021-01-12 13:42:12 : Block (4 of 4) : Seurat FindTransferAnchors, 2.738 mins elapsed.
<simpleError in Seurat::FindTransferAnchors(reference = subRNA, query = seuratATAC,     reduction = reduction, features = genesUse, verbose = FALSE,     ...): formal argument "features" matched by multiple actual arguments>
<simpleError in Seurat::FindTransferAnchors(reference = subRNA, query = seuratATAC,     reduction = reduction, features = genesUse, verbose = FALSE,     ...): formal argument "features" matched by multiple actual arguments>
Error in .safelapply(seq_along(blockList), function(i) { :
Error Found Iteration 1 :
        [1] "Error in .retryCatch({ : \n"
        <simpleError in .retryCatch({    gc()    Seurat::FindTransferAnchors(reference = subRNA, query = seuratATAC,         reduction = reduction, features = genesUse, verbose = FALSE,         ...)}, maxAttempts = 2, logFile = logFile): >
Error Found Iteration 2 :
        [1] "Error in .retryCatch({ : \n"
        <simpleError in .retryCatch({    gc()    Seurat::FindTransferAnchors(reference = subRNA, query = seuratATAC,         reduction = reduction, features = genesUse, verbose = FALSE,         ...)}, maxAttempts = 2, logFile = logFile): >
Error Found Iteration 3 :
        [1] "Error in .retryCatch({ : \n"
        <simpleError in .retryCatch({    gc()    Seurat::FindTransferAnchors(reference = subRNA, query = seuratATAC,         reduction = reduction, features = genesUse, verbose = FALSE,         ...)}, maxAttempts = 2, logFile = logFile): >
Error Found Iteration 4 :
        [1] "Error in .retryCatch({ : \n"
        <simpleError in .retryCatch({    gc()
In addition: Warning message:
In mclapply(..., mc.cores = threads, mc.preschedule = preschedule) :
  4 function calls resulted in an error`

**Comment by rcorces** [comment]
> I believe the features argument is specified multiple times in the function. Would you be able to fix this?

I'm not sure I understand this but feel free to explain more in depth. Can you reproduce your error with the tutorial data? This looks like it might be a parallelization issue? Have you tried `threads = 1`?

**Comment by SaskiaFreytag** [comment]
The same error happens in the tutorial dataset. It also happens when I set the threads=1. I have attached the log files.
[ArchR-addGeneIntegrationMatrix-d6b95e5dc68c-Date-2021-01-13_Time-11-00-30.log](https://github.com/GreenleafLab/ArchR/files/5806176/ArchR-addGeneIntegrationMatrix-d6b95e5dc68c-Date-2021-01-13_Time-11-00-30.log)
[ArchR-addGeneIntegrationMatrix-d6b948fed17f-Date-2021-01-13_Time-11-08-24.log](https://github.com/GreenleafLab/ArchR/files/5806178/ArchR-addGeneIntegrationMatrix-d6b948fed17f-Date-2021-01-13_Time-11-08-24.log)

**Comment by rcorces** [comment]
I understand your original post now. Currently, you cannot include `features` as an additional argument to this function via the `...` because this function is (by default) using the most variable genes.
https://github.com/GreenleafLab/ArchR/blob/2f022a448d8248a0f9afb33419bcbaeafe7731c0/R/RNAIntegration.R#L441
So because you are trying to separately specify the `features`, this argument is being passed to `Seurat::findTransferAnchors()` twice.

I'm changing your issue label to "enhancement". It seems reasonable to me to want to be able to control the set of features though I would imagine that the default behavior of using the most variable genes should cover most use cases.

Can you describe why you want to manually specify the features used in `Seurat::findTransferAnchors()` and why the default isnt sufficient?

Flagging @jgranja24 for comments on this request.

**Comment by SaskiaFreytag** [comment]
I think my rational for using specific features was mainly to see how the behaviour would change.  We have done a lot of work in identifying variable features in the scRNA-seq and I wanted to see whether just using these would meaningfully change results.

**Comment by jgranja24** [comment]
Hi @SaskiaFreytag this is now a feature in the release 1.0.1 branch

https://github.com/GreenleafLab/ArchR/blob/release_1.0.1/R/RNAIntegration.R

`
devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.1", repos = BiocManager::repositories())
`

**Comment by dzc971101** [comment]
一样的问题，查了很多资料，最后将seruat和seruatobject降级v4后解决
