### ISSUE TITLE
How are biases matched acrossed distribution of groups in `getMarkerFeatures()`

### ISSUE THREAD

**Issue by wusuowei60** [GreenleafLab/ArchR#490]
In the ArchR publication **ArchR Methods – Marker Peak Identification with Annotation Enrichment** part, it says
 > Additionally, when selecting these bias-matched cells ArchR will match the distribution of the other user-defined groups. For example, if there were 4 equally represented clusters, ArchR will match the biases for a cluster to the remaining 3 clusters while selecting cells from the remaining 3 groups equally...

What does this mean? How are the biases *matched*?

The documentation corresponding to `getMarkerFeatures()` in Section 7.2 only says it rescales biases and picks nearest out-of-cluster cell for each cell.

Did I get it wrong or the documentation missed this part?

I have noticed related comments in the source code, but I am not an R expert and cannot tell what operations are applied. Looking forward to help.

**Comment by rcorces** [comment]
I'm not sure I know how to explain this better than what is already present in Section 7.2.
You tell ArchR which parameters to match and it finds background cells that are as closely matched as possible for those parameters.

**Comment by wusuowei60** [comment]
Okay then that is clear for me. Thank you~
