### ISSUE TITLE
getVarDeviations

### ISSUE THREAD

**Issue by rojinsafavi** [GreenleafLab/ArchR#496]
It would be nice if we could show specific motifs on the variation plot instead of the first N motifs :)

`plotVarDev <- getVarDeviations(projHeme5, name = "MotifMatrix", plot = TRUE)`

**Comment by rcorces** [comment]
Thanks for the suggestion. I think our intention was that you would set `plot = FALSE`, manually retrieve the data that you want from the returned data frame, and plot it manually using `ggplot`. Please close if this works for what you need.
