### ISSUE TITLE
error in addUMAP in R 4.0.3

### ISSUE THREAD

**Issue by NinaJiangL** [GreenleafLab/ArchR#497]
hi all, 
I still have an error when trying to use addUMAP this function. I couldnt installed uwot 0.1.8 it said permission denied and I still had the error when tring run addUMAP :Error in model$nn_index$save(nn_tmpfname) : attempt to apply non-function. my R is 4.0.2 

Any ideas how it work? 
Thanks

**Comment by rcorces** [comment]
The fix to this is posted in #424 
To fix this error, install the development version of ArchR and restart R / reload ArchR

`devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.1", repos = BiocManager::repositories())`
