### ISSUE TITLE
subsetArchRProject copying only Arrow files

### ISSUE THREAD

**Issue by Brawni** [GreenleafLab/ArchR#506]
Hello ArchR folks!

The function subsetArchRProject copies all the folders and files from the main ArchR project folder to the new subset one. This to me seems unnecessary as you often don't need many of the files from the main project. 
Would it be possible to add an argument to the function to copy only the arrow files in the new folder? 
Also by keeping the reproduciblePeaks files from main project you would incur in this > https://github.com/GreenleafLab/ArchR/issues/407

Thanks a lot!

**Comment by jgranja24** [comment]
Yeah I will try to add something like this. Sorry for the delays!
