### ISSUE TITLE
Error using getPositions

### ISSUE THREAD

**Issue by ccruizm** [GreenleafLab/ArchR#510]
Good day!

I am having an error when using `getPositions`. I do not understand where the problem might be since I added successfully all motif annotations to the object and could plot them (e.g., `plotGroups` `plotEmbedding`) 

```
Error in normalizeDoubleBracketSubscript(i, x, exact = exact, allow.NA = TRUE, : subscript is out of bounds
Traceback:

1. getPositions(projdipg)
2. ArchRProj@peakAnnotation[[name]]
3. ArchRProj@peakAnnotation[[name]]
4. getListElement(x, i, ...)
5. getListElement(x, i, ...)
6. getListElement(x@listData, i, exact = exact)
7. getListElement(x@listData, i, exact = exact)
8. normalizeDoubleBracketSubscript(i, x, exact = exact, allow.NA = TRUE, 
 .     allow.nomatch = TRUE)
9. stop("subscript is out of bounds")
```
Thanks in advance!

**Comment by rcorces** [comment]
Can you recapitulate this error with the tutorial dataset? If yes, please provide the code to do so.

**Comment by jgranja24** [comment]
Hi @ccruizm, can you please share the full code you used?

**Comment by ccruizm** [comment]
I could run the tutorial data and had no problems with other datasets. Most of the time I see I am having a problem when subsetting the ArchR project. Sometimes there are functions that do not work properly but the issues are not reproducible every time. Sorry for that. I will try to see whether there is an issue in the env where I have R installed. 

Thanks for the quick response and the great maintenance of this package!

**Comment by rcorces** [comment]
Sorry you're having issues with subsetting. We are actively fixing some known bugs in subsetting but also hope to make subsetting more stable in the future.
