### ISSUE TITLE
Ordering of markers in Heatmap

### ISSUE THREAD

**Issue by sylestiel** [GreenleafLab/ArchR#511]
Hi,

 For the plotMarkerHeatmap() function how can I control the order in which the transposed Markers appear in the Heatmap?

Thanks

**Comment by rcorces** [comment]
this sounds like a duplicate of #329
I'm going to close this but if you dont think it is a duplicate, just comment why and I'll re-open.

I dont think this is possible at the moment.

**Comment by rcorces** [comment]
I know it isnt a direct duplicate, but i think that you could post over there to keep issues tidy for us.

**Comment by sylestiel** [comment]
Point taken!

Setting binaryClusterRows = FALSE,  clusterCols = FALSE helped to some degree.
