### ISSUE TITLE
Not Valid Collection in ArchRAnno Database

### ISSUE THREAD

**Issue by jindalk** [GreenleafLab/ArchR#516]
[ArchR-addArchRAnnotations-c8613ddc2be3-Date-2021-01-27_Time-13-01-57.log](https://github.com/GreenleafLab/ArchR/files/5882447/ArchR-addArchRAnnotations-c8613ddc2be3-Date-2021-01-27_Time-13-01-57.log)

I tried to add ATAC peak collection to my mm10 project using:

`proj_lsk4 <- addArchRAnnotations2(ArchRProj = proj_lsk4, db = "LOLA", collection = "ATAC")`

and got the following error:

`Not Valid Collection in ArchRAnno Database!`

However, this works fine with EncodeTFBS

**Comment by rcorces** [comment]
In the future, please make sure to use the issue templates provided. This information is pretty explicit in the function parameter documentation and you might have found this if following the issue template. The error is also quite explicit.

```
A string indicating which collection within the database to collect for annotation. For ArchR, options are "ATAC", "EncodeTFBS", "CistromeTFBS", or "Codex". For LOLA, options include "EncodeTFBS" "CistromeTFBS", "CistromeEpigenome", "Codex", or "SheffieldDnase". If supplying a custom ArchRAnno file please select a valid collection from within that database.
```
