### ISSUE TITLE
Does ChromVAR use the reference genome sequence or sequence from raw ATAC reads? 

### ISSUE THREAD

**Issue by RegnerM2015** [GreenleafLab/ArchR#517]
Hi @rcorces and @jgranja24 and @AliciaSchep 

**Where is the problematic documentation?**
Section 13.1 (ChromVAR)

**Describe what is unclear or confusing**
Is it possible for ChromVar to account for mutations/variants in DNA sequence? To my understanding, ChromVAR uses the default reference genome (or default ArchR genome in this context). It is unclear in this section regarding what sequence is used (reference genome or raw scATAC-seq reads). 

### If this is an issue with documentation that is absent/missing:

**Describe what material you feel should be explained**
Is it possible to swap in a new custom ArchR genome for the purpose of running ChromVAR? This custom genome would include single-nucleotide variants and indels present in the sample. 

**Where do you think this documentation would belong?**
This option or discussion could be highlighted in section 13. Or give a warning to users saying that the ChromVAR analysis assumes the reference genome sequence.

**Comment by rcorces** [comment]
I dont know the answer to this with certainty but I do not believe that chromVAR has this capability. It is an interesting idea but I imagine outside of the scope of what we would be able to implement right now. But I'll let the others correct me if I'm wrong.

**Comment by jgranja24** [comment]
Hi @RegnerM2015, chromVAR cannot due this unfortunately. Unfortunately its not something we can implement either because ArchR doesnt work with the raw sequence from the bam files. Sorry, analyses with variants is a bit more sophisticated and user specific for ArchR at this time!
