### ISSUE TITLE
downstream analysis after Harmony

### ISSUE THREAD

**Issue by Brawni** [GreenleafLab/ArchR#519]
Hello folks! 

This is more of a question rather than a documentation request but I cant seem to find an answer on the web. Is it ok to use groupings from the harmonized reduced space for downstream group coverage generation > peak calling and marker feature identification or is better to stick with the clustering on the IterativeLSI space for downstream analysis? My worry is that the harmonized clusters may contain more intra-variability in the higher-dimension features space hampering marker detection. 

Looking forward for your inputs.

Thanks!

**Comment by rcorces** [comment]
If I'm understanding your question correctly, then the answer is yes. After Harmony reduction, you would re-call clusters and use these clusters in all downstream analyses.

**Comment by rcorces** [comment]
Closing. Feel free to comment here if you need this reopened
