### ISSUE TITLE
DotPlots

### ISSUE THREAD

**Issue by sylestiel** [GreenleafLab/ArchR#523]
Is generating DotPlots supported?

**Comment by rcorces** [comment]
you mean like `ggPoint()`? This is a wrapper around ggplot that helps make dot plots in ArchR

https://www.archrproject.com/reference/ggPoint.html

Please close if this answers your question

**Comment by rcorces** [comment]
Sorry, now I know what you mean by Dot Plot. No - ArchR does not provide any functions to generate these plots and I dont think we have any major need to implement this given that other packages do it pretty well. You can always use other packages to interact with ArchR's data. It might just take a little digging.
