### ISSUE TITLE
obtaining cell specific reads

### ISSUE THREAD

**Issue by rojinsafavi** [GreenleafLab/ArchR#525]
Hello!
How can I get the cell type-specific regions? for example, I would like to obtain reads that fall into progenitor cell type in the browser track?

![image](https://user-images.githubusercontent.com/19545198/106924985-80797a00-66c4-11eb-8f9f-13b75a7acfed.png)

**Comment by rcorces** [comment]
If you look in the `PeakCalls` directory, you will find files that contain peak calls for each of your cell groupings (`*-reproduciblePeaks.gr.rds`).

You said "cell type-specific" which might imply peaks present in one cell type but NOT other cell types. This you would do using `getMarkerFeatures()`.

You also said you wanted the reads that fall within those peaks. That is less straightforward but it wasnt clear if you really wanted to extract the reads in the peaks.

**Comment by rojinsafavi** [comment]
Thanks, @rcorces 
I saw those files.  So if I understood it correctly, each *-reproduciblePeaks.gr.rds file is used to make the browser track?

**Comment by rcorces** [comment]
Which browser track? the peak call tracks or the coverage tracks?

**Comment by rojinsafavi** [comment]
@rcorces the coverage track

**Comment by rojinsafavi** [comment]
Basically, I would like to be able to extract cell-type specific coverage matrix.

**Comment by rcorces** [comment]
I think I need more details on what you really want. `getGroupBW()` will give you bigwig (coverage) files for an individual group. The `TileMatrix` provides binned genome-wide coverage and the `PeakMatrix` provides peak coverage. Is any of those what you're looking for?
