### ISSUE TITLE
Umap labels

### ISSUE THREAD

**Issue by sylestiel** [GreenleafLab/ArchR#526]
How can I remove the cluster labels from the Umap after integration

**Comment by rcorces** [comment]
This is controlled through the pass through variables to `ggPoint()`. The parameter `labelMeans` can be set to `FALSE` in the `plotEmbedding()` function and it will get passed as an argument to `ggPoint()`.

https://www.archrproject.com/reference/ggPoint.html

Please close if this answers your question

**Comment by sylestiel** [comment]
Thanks!!!

**Comment by brianpenghe** [comment]
Thanks!

**Comment by qdong2023** [comment]
I found some labels are overlapped on UMAP , but the labels size didn't change using baseSize(). I wonder how adjust this?

**Comment by dgagler** [comment]
@qdong2023 you can use the ```labelSize``` parameter
