### ISSUE TITLE
plotBrowserTrack - group by multiple variables?

### ISSUE THREAD

**Issue by agriswold76** [GreenleafLab/ArchR#528]
In an ArchR project with several samples - is it possible to create browser tracks for individual clusters for each individual sample? If groupBy Cluster seems to combine all samples to create track. If groupBy sample seems to combine all clusters for each sample. I'd be interested in creating a plot for "Cluster 1 in Sample 1" "Cluster 1 in Sample2" for example.

**Comment by rcorces** [comment]
Just add a new column to `cellColData` that defines the specific grouping you would like and use this in `groupBy`
https://www.archrproject.com/reference/addCellColData.html

Please close if this answers your question.

**Comment by agriswold76** [comment]
perfect - thanks!
