### ISSUE TITLE
Error with addGeneExpressionMatrix

### ISSUE THREAD

**Issue by sylestiel** [GreenleafLab/ArchR#533]
<img width="840" alt="Screen Shot 2021-02-11 at 4 16 00 PM" src="https://user-images.githubusercontent.com/64283689/107705545-82bf7380-6c84-11eb-93cf-194460766032.png">
[ArchR-addGeneExpressionMatrix-b89d48e52328-Date-2021-02-11_Time-16-14-52.log](https://github.com/GreenleafLab/ArchR/files/5968735/ArchR-addGeneExpressionMatrix-b89d48e52328-Date-2021-02-11_Time-16-14-52.log)

**Comment by jgranja24** [comment]
Sorry this is a bug from the old ArchR version I need to push 1.0.1! Try it again after installing the new version --

`devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.0", repos = BiocManager::repositories())
`

**Comment by sylestiel** [comment]
did you mean ref="release_1.0.1"

**Comment by rcorces** [comment]
yes

**Comment by jgranja24** [comment]
Oh shoot sorry my bad! yeah I will push out the new release this weekend!

**Comment by sylestiel** [comment]
okay. Thanks!
