### ISSUE TITLE
Attach a X-axis/bar of Pseudo-time value/cell cluster color bar on the top of the plotTrajectoryHeatmap 

### ISSUE THREAD

**Issue by willey2020** [GreenleafLab/ArchR#534]
Hello! Thanks again for this great package!

**Describe the problem that your feature request would address.**

The plotTrajectoryHeatmap function is very cool.
The y axis of the current plots(TF motif,Gene score, RNA) is very clear. However, it is better to get an accurate sense about which time point, a feature(motif,gene,RNA) is showing up/down, maybe through a more detailed x-axis or color bar, for example, the pseudo-time x axis or the pesudotime/cell cluster color bars, on the top of the trajectory heatmap. 
 
**Describe the solution you'd like**
Is there any way to attach a x-axis that shows pesudotime value according to the heatmap,like below or on the top of the heatmap? Then, we can get a sense of exactly when a TF/RNA/gene score is upregulated/downregulated.

**Describe alternatives you've considered**
If there is another way, that shows the matched color the pesudotime value (dark blue, purple to yellow, showed in manual 16.1.1) in a horizontal color bar plot, and matching the trajectory heatmap x-axis, then it will be much more clear.  

Or if there is a way to shows the cell cluster color bar together matching the x-axis, it will be great!

For these two alternative solutions, I attached two reference plots, examples from single-cell RNA-seq study. Just for examples only. For the second example, their cell type/stage colors showing on the top of the heatmap are a similar analogy to cell cluster color. 

**Additional context**
After searching in the issues, not sure if a similar feature request was posted before. 
Thank you so much and again this is a great and amazing package!

![Screenshot 2021-02-14 085109](https://user-images.githubusercontent.com/72377061/107883144-fa1e1e80-6ea1-11eb-9cef-f6311093dc87.png)
![Screenshot 2021-02-14 084132](https://user-images.githubusercontent.com/72377061/107882881-a52dd880-6ea0-11eb-84a7-20a26e3aac3c.png)

**Comment by rcorces** [comment]
I dont think this is currently possible but seems reasonable. Feature requests have piled up so I wouldnt expect this to be addressed soon though.

**Comment by willey2020** [comment]
Thank you!! Totally understand! Thanks again for this great package!
