### ISSUE TITLE
Label Transfer and Annotation using Multiomic data

### ISSUE THREAD

**Issue by sylestiel** [GreenleafLab/ArchR#536]
When analyzing the 10X Multiomic data using ArchR what are the steps involved in annotating the clusters?

Since the multi-omic data contains both ATAC + RNA information what steps would replace  detection of anchors, label transfer, and predicted i.d. assignment?

By the way, the new version of ArchR is running smoothly.

**Comment by rcorces** [comment]
Hi @sylestiel - are you referring to specific sections of the manual like this:
https://www.archrproject.com/bookdown/labeling-scatac-seq-clusters-with-scrna-seq-information.html

The manual is a guide for how to use ArchR, not necessarily a guide for how to perform all analyses. Its up to the individual user to decide which steps are necessary and useful for their particular application. In the case of multiome data, some of the steps will naturally be different.

Hope that helps. Closing this for now but feel free to comment again if this doesnt address your question.

**Comment by sylestiel** [comment]
Yes that is what I'm referring to.  So is there some way of adapting that to the Multiomic assay?

**Comment by rcorces** [comment]
I'm not sure I understand what you mean. Label transfer is not relevant for multiome data in the same way it is for the matched data used in the tutorial. If you read through the multiome tutorial (https://greenleaflab.github.io/ArchR_2020/Ex-Analyze-Multiome.html) it shows you how to call clusters in RNA space and in ATAC space and these cluster definitions are added to `cellColData`. So you dont need to do any label transfer.

**Comment by sylestiel** [comment]
I want to annotate the clusters.  Just trying to figure out how to do so.

**Comment by rcorces** [comment]
Typically we annotate clusters using gene scores or gene expression for known marker genes
