### ISSUE TITLE
addGeneIntegrationMatrix closest cells and the similarity matric

### ISSUE THREAD

**Issue by rojinsafavi** [GreenleafLab/ArchR#541]
Hello!
I was wondering if it's possible to have the list of the closest cells to each ATACseq cell upon integration (plus the corresponding similarity matrix) as a possible output?

**Comment by rcorces** [comment]
Hi @rojinsafavi - you should be able to retrieve this information from `cellColData` after you perform the integration. That process should add a bunch of columns with names that start with "predicted" like this:

```
> colnames(proj@cellColData)
 [1] "Sample"            "TSSEnrichment"     "ReadsInTSS"        "ReadsInPromoter"  
 [5] "ReadsInBlacklist"  "PromoterRatio"     "PassQC"            "NucleosomeRatio"  
 [9] "nMultiFrags"       "nMonoFrags"        "nFrags"            "nDiFrags"         
[13] "DoubletScore"      "DoubletEnrichment" "BlacklistRatio"    "Clusters"         
[17] "predictedCell_Un"  "predictedGroup_Un" "predictedScore_Un" "predictedCell_Co" 
[21] "predictedGroup_Co" "predictedScore_Co" "predictedCell"     "predictedGroup"   
[25] "predictedScore"    "Clusters2"    
```

The "predictedCell" columns tell you the cellular barcode of the cell that it mapped to.
Please close if this answers your question

**Comment by rojinsafavi** [comment]
Hi @rcorces 
That's not my exact question. I know that the most similar cell is in the predictedCell_*, but I wanted to see if it's possible to retrieve a similarity score for all the cells?
an output such as a matrix filled with the similarity metric:

ATACcells x RNAcells
                 RNA-cell-1 RNA-cell-2 RNA-cell-4
atac cell 1      0.4          0.5                 0.2
atac cell 2      0.2          0.5                 0.2
atac cell 3      0.4          0.5                 0.2
atac cell 4      0.3          0.5                 0.2

**Comment by rcorces** [comment]
I see. Sorry I originally thought you were looking for "predictedScore". Do you know if this information is returned by `Seurat::FindTransferAnchors()`?

**Comment by jgranja24** [comment]
Hi @rojinsafavi, I dont think an output like that is possible because the best case scenario is you get a NN index object between the two assays. I'd have to take alook at Seurat more but this seems like an output that could blow up memory.
