### ISSUE TITLE
Bias options when running getMarkerFeatures using the GeneExpressionMatrix

### ISSUE THREAD

**Issue by sylestiel** [GreenleafLab/ArchR#543]
If I were to run getMarkerFeatures() using the GeneExpressionMatrix what do I put down for bias?

For the GeneScoreMatrix it is bias = c("TSSEnrichment", "log10(nFrags)").

Please let me know if it is okay to use GeneExpressioMatrix with this function call.

Thanks!

**Comment by jgranja24** [comment]
Hi @sylestiel, those biases are focused towards the scATAC aspect. I'd imagine they will work for the most part. I'd imagine doing like -

bias = c("TSSEnrichment", "log10(Gex_nUMI)")

instead. This accounts for quality (TSS) and read depth. Hope that helps!

**Comment by sylestiel** [comment]
Awesome!  Thanks!
