### ISSUE TITLE
Is it possible to add DoubletScores after creating an ArchRProject?

### ISSUE THREAD

**Issue by Jiangyuan-Liu** [GreenleafLab/ArchR#545]
ArchR : Version 1.0.1
I tried to run DoubletScores(), and input is an ArchRProject object. I got the following error message. Could you help me to figure it out? Thanks.

```
> doubScores <- addDoubletScores(
+     input = projArch,
+     k = 10, #Refers to how many cells near a "pseudo-doublet" to count.
+     knnMethod = "UMAP", #Refers to the embedding to use for nearest neighbor search with doublet projection.
+     LSIMethod = 1
+ )
ArchR logging to : ArchRLogs/ArchR-addDoubletScores-784555dd64d-Date-2021-02-23_Time-11-27-24.log
If there is an issue, please report to github with logFile!
2021-02-23 11:27:24 : Batch Execution w/ safelapply!, 0 mins elapsed.
2021-02-23 11:27:24 : e11_5rep1 (1 of 4) :  Computing Doublet Statistics, 0.003 mins elapsed.
Error in ArchRProject(ArrowFiles = ArrowFile, outputDirectory = tmpDir,  : 
  outputDirectory cannot have a space in the full path! Full path : 
```

**Comment by rcorces** [comment]
> `Error in ArchRProject(ArrowFiles = ArrowFile, outputDirectory = tmpDir,  : 
  outputDirectory cannot have a space in the full path! Full path : 

This sounds like a pretty explicit error. Did you include a space in your "outputDirectory" parameter when creating your ArchRProject? If you are working in Windows, please note that ArchR is not supported on Windows and we are updating the website to reflect this.

**Comment by Jiangyuan-Liu** [comment]
I found that the output of getOutputDirectory(projArch) is different from the "! Full path " from the error message.

**Comment by Jiangyuan-Liu** [comment]
Because I am using Dropbox, there are spaces in the full path. Any suggestions?
Error in ArchRProject(ArrowFiles = ArrowFile, outputDirectory = tmpDir,  : 
  outputDirectory cannot have a space in the full path! Full path : /Users/jiangyuanliu/Dropbox (

**Comment by Jiangyuan-Liu** [comment]
Can I change the outputDirectory to a symbolink that links to a path that contains spaces?

**Comment by rcorces** [comment]
You cannot use a directory that has a space so you will have to use a different directory.
