### ISSUE TITLE
Problems with custom ArchRGenome

### ISSUE THREAD

**Issue by Jason-bot-stack** [GreenleafLab/ArchR#551]
Helo! The species I studied is pig, there is no BSgenome object, how can I create it? Is ArchR only suitable for species research with BSgenome information?

**Comment by rcorces** [comment]
Thanks for using ArchR! Please use the issue templates when posting issues and note that this is not a "bug" and would be more properly handled under the "documentation" template

That being said, I do believe there are BSgenome objects for pig. Googling "BSgenome pig" points to:
http://www.bioconductor.org/packages/release/data/annotation/html/BSgenome.Sscrofa.UCSC.susScr11.html

**Comment by Jason-bot-stack** [comment]
Thank you very much!



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GreenleafLab/ArchR"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月26日(星期五) 晚上11:06
收件人:&nbsp;"GreenleafLab/ArchR"<ArchR@noreply.github.com&gt;;
抄送:&nbsp;"肖燕园"<1578174865@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [GreenleafLab/ArchR] Problems with custom ArchRGenome (#551)





 
Thanks for using ArchR! Please use the issue templates when posting issues and note that this is not a "bug" and would be more properly handled under the "documentation" template
 
That being said, I do believe there are BSgenome objects for pig. Googling "BSgenome pig" points to:
 http://www.bioconductor.org/packages/release/data/annotation/html/BSgenome.Sscrofa.UCSC.susScr11.html
