### ISSUE TITLE
motifposition

### ISSUE THREAD

**Issue by rojinsafavi** [GreenleafLab/ArchR#555]
I was wondering if you could clarify what the last column corresponds
<img width="607" alt="Screen Shot 2021-02-26 at 3 29 32 PM" src="https://user-images.githubusercontent.com/19545198/109366152-8556c700-7847-11eb-8a91-4afed99785ab.png">
 to?

**Comment by rcorces** [comment]
Presumably those are peak regions where the motif is present and the score represents the peak score ("score-per-million"). This is somewhat described in section 10.1.6 and also in the methods section of our original publication of iterative overlap peak merging (Corces & Granja Science 2018).
I've made a note to add a little more to the documentation on this. Feel free to comment again if this didnt answer your question and i will reopen.

**Comment by rojinsafavi** [comment]
Just to clarify, the score represents the score of the motif correct?
