### ISSUE TITLE
addGeneIntegrationMatrix error

### ISSUE THREAD

**Issue by dataMaster-Kris** [GreenleafLab/ArchR#556]
I am running ArchR (v1.0.1, date: 2020-11-23, development version that I installed in January) and Seurat (v3.2.3). I am trying to do unconstrained integration but getting the following error.

```
Error in .safelapply(seq_along(blockList), function(i) { : 
Error Found Iteration 1 : 
        [1] "Error in `[<-`(`*tmp*`, which(reference.ids == possible.ids[i]), i, value = 1) : \n  subscript out of bounds\n"
        <simpleError in `[<-`(`*tmp*`, which(reference.ids == possible.ids[i]), i, value = 1): subscript out of bounds>
Error Found Iteration 2 : 
        [1] "Error in `[<-`(`*tmp*`, which(reference.ids == possible.ids[i]), i, value = 1) : \n  subscript out of bounds\n"
        <simpleError in `[<-`(`*tmp*`, which(reference.ids == possible.ids[i]), i, value = 1): subscript out of bounds>
Error Found Iteration 3 : 
        [1] "Error in `[<-`(`*tmp*`, which(reference.ids == possible.ids[i]), i, value = 1) : \n  subscript out of bounds\n"
        <simpleError in `[<-`(`*tmp*`, which(reference.ids == possible.ids[i]), i, value = 1): subscript out of bounds>
Error Found Iteration 4 : 
        [1] "Error in `[<-`(`*tmp*`, which(reference.ids == possible.ids[i]), i, value = 1) : \n  subscript out of bounds\n"
        <simpleError in `[<-`(`*tmp*`, which(reference.ids == possible.ids[i]
Calls: addGeneIntegrationMatrix -> %>% -> Reduce -> .safelapply
In addition: Warning message:
In mclapply(..., mc.cores = threads, mc.preschedule = preschedule) :
  5 function calls resulted in an error
Execution halted 
```

Based on the suggestions in [this issue](https://github.com/GreenleafLab/ArchR/issues/174), I tried changing the number of threads but the issue didn't resolve. Any suggestions? I have attached the ArchR log file.

[ArchR-addGeneIntegrationMatrix-9f4a41d7fe79-Date-2021-02-26_Time-22-29-00.log](https://github.com/GreenleafLab/ArchR/files/6055923/ArchR-addGeneIntegrationMatrix-9f4a41d7fe79-Date-2021-02-26_Time-22-29-00.log)

**Comment by dataMaster-Kris** [comment]
I figured it out. The error was due to the row names in the metadata slot of the Seurat object not being in the same order as the column names in the count matrix.

**Comment by rcorces** [comment]
@jgranja24 - Maybe we should add a specific check for this to catch this error in a more elegant way?

**Comment by dataMaster-Kris** [comment]
I wan't very thorough in checking what was causing the error. It may also have been that the meta data slot of my Seurat object didn't have rownames at all. Thought I'd let you know.

**Comment by sunjiahe0502** [comment]
### Error in H5Fopen(file)

Hello, I look forward to your guidance. According to the official tutorial, when I created projHeme3, I reported "Error in H5Fopen(file)"：

The running code is as follows:
`projHeme3 <- addGeneIntegrationMatrix(
 ArchRProj = projHeme2, 
 useMatrix = "GeneScoreMatrix",
 matrixName = "GeneIntegrationMatrix",
 reducedDims = "IterativeLSI",
 seRNA = seRNA,
 addToArrow = TRUE,
 force= TRUE,
 groupList = groupList,
 groupRNA = "BioClassification",
 nameCell = "predictedCell",
 nameGroup = "predictedGroup",
 nameScore = "predictedScore"
`
The  error is as follows：
`2021-09-01 06:45:48 : Transferring Data to ArrowFiles, 5.032 mins elapsed. 
Error in .safelapply(seq_along(allSamples), function(y) { :  
Error Found Iteration 2 :  	
[1] "Error in H5Fopen(file) : HDF5. File accessibility. Unable to open file.\n" 	
<simpleError in H5Fopen(file): HDF5. File accessibility. Unable to open file.> Error Found Iteration 3 :  	
[1] "Error in H5Fopen(file) : HDF5. File accessibility. Unable to open file.\n" 	
<simpleError in H5Fopen(file): HDF5. File accessibility. Unable to open file.> 
In addition: Warning message: 
In mclapply(..., mc.cores = threads, mc.preschedule = preschedule) :   2 function calls resulted in an error
`

The  log file is as follows：
[ArchR-addGeneIntegrationMatrix-12d46466dba-Date-2021-09-01_Time-06-40-32.log](https://github.com/GreenleafLab/ArchR/files/7088889/ArchR-addGeneIntegrationMatrix-12d46466dba-Date-2021-09-01_Time-06-40-32.log)

**Comment by sunjiahe0502** [comment]
2021-09-01 06:45:48 : Transferring Data to ArrowFiles, 5.032 mins elapsed.
Error in .safelapply(seq_along(allSamples), function(y) { : 
Error Found Iteration 2 : 
	[1] "Error in H5Fopen(file) : HDF5. File accessibility. Unable to open file.\n"
	<simpleError in H5Fopen(file): HDF5. File accessibility. Unable to open file.>
Error Found Iteration 3 : 
	[1] "Error in H5Fopen(file) : HDF5. File accessibility. Unable to open file.\n"
	<simpleError in H5Fopen(file): HDF5. File accessibility. Unable to open file.>
In addition: Warning message:
In mclapply(..., mc.cores = threads, mc.preschedule = preschedule) :
  2 function calls resulted in an error

**Comment by LMBei3353** [comment]
Hello, I have encountered the same error. How did you solve it at last
