### ISSUE TITLE
Use 10X data to create arrow files

### ISSUE THREAD

**Issue by Ping-lin14** [GreenleafLab/ArchR#565]
Hi

When I use 10X data to create an arrow file, I receive the following error
`<simpleError in H5Fcreate(file): HDF5. File accessibilty. Unable to open file.`
My code:
```
library(ArchR)
set.seed(1)

addArchRThreads(threads = 4)
inputFiles <- 'C:/Users/ping/Desktop/ATAC/S3234T/fragments.tsv.gz'
inputFiles

addArchRGenome("hg38")

ArrowFiles <- createArrowFiles(
  inputFiles = inputFiles,
  sampleNames = inputFiles,
  filterTSS = 4, #Dont set this too high because you can always increase later
  filterFrags = 1000, 
  addTileMat = TRUE,
  addGeneScoreMat = TRUE
) 
```

What did i do wrong?

**Comment by rcorces** [comment]
Sorry you're having trouble. Unfortunately, ArchR is not supported on Windows at this time and we cannot answer issues from Windows users due to limited bandwidth.
