### ISSUE TITLE
Custom CallPeaks

### ISSUE THREAD

**Issue by NinaJiangL** [GreenleafLab/ArchR#568]
Hi, I was wondering is there an easy way to select the peaks only in the promoter region (+-500bp of TSS) of a certain gene? instead of showing all the peaks across all the cell-types ?
can I just adjust the parameters when using with Macs2 by using ArchR and show in the GRange object with promoter region only ?

 e.g. addReproduciblePeakSet()  and getPeakSet()
<img width="485" alt="Screen Shot 2021-03-04 at 4 07 31 PM" src="https://user-images.githubusercontent.com/18588687/109931422-cd706080-7d03-11eb-907c-b8460d916d2b.png">

Here is another question: if I have a bed output from MACS2 with all the peaks and regions , and now I want to check whether these peaks fall into enhancer or promoter region of the gene. can I import this bed file with peaks to ArchR, or I need to use MACS2 and get the bed file labelled with enhancer/promoter genome annotations first then import into R? (like #487, import a peak matrix)

Also, I am not quite sure what is the formate of peak matrix ? Can I import the bed file of peak getting from MACS2?

Thanks

**Comment by rcorces** [comment]
You can add whatever peak set you want in lieu of calling `addReproduciblePeakSet()` by using the `addPeakSet()` function:
https://www.archrproject.com/reference/addPeakSet.html
The rest is up to you.

You can create a new peak set from the reproducible peak set if you want by filtering based on some of the metadata in the GRanges object (for ex `distToTSS`) and then adding this new peak set to your project using `addPeakSet()`

```
> colnames(mcols(getPeakSet(proj)))
 [1] "score"                  "replicateScoreQuantile" "groupScoreQuantile"     "Reproducibility"        "GroupReplicate"        
 [6] "distToGeneStart"        "nearestGene"            "peakType"               "distToTSS"              "nearestTSS"            
[11] "GC"                     "idx"      
```
