### ISSUE TITLE
Writing results to file

### ISSUE THREAD

**Issue by sylestiel** [GreenleafLab/ArchR#585]
Hi, 
 
With reference to Chapter 11.3 in the full ArchR manual and the script:
markerTest <- getMarkerFeatures(
  ArchRProj = proj5, 
  useMatrix = "PeakMatrix",
  groupBy = "Clusters",
  testMethod = "wilcoxon",
  bias = c("TSSEnrichment", "log10(nFrags)"),
  useGroups = "C1",
  bgdGroups = "C5"
)

When I try to write the **output from different comparisons to file they seem the same.**
b <- as.data.frame(markerTest@elementMetadata)
fwrite(b, file = "filePATH/fileNAME.csv")

Can you help me catch the problem?  I want to find the features that are upregulated and downregulated in the paired comparisons.

**Comment by rcorces** [comment]
I'm not sure I understand your question. Please provide a reproducible example from the tutorial data.

Also, please not that we have just switched to using GitHub Discussions to field usage questions and feature requests.

**Comment by rcorces** [comment]
`markerTest` is a summarized experiment object with multiple assays and the peak info in `rowData`. You can identify the features that you are interested in and then subset the SummarizedExperiment to those rows.
