### ISSUE TITLE
Error using addGeneExpressionMatrix

### ISSUE THREAD

**Issue by ldorozco** [GreenleafLab/ArchR#595]
Hello,
Thank you for creating this tool, it is extremely  useful. And, congratulations on your recent publication.
I keep getting this error when I try to add gene expression from a multi-omics project. I am not sure what is causing it, or how to fix it. It doesn't seem that I can specify "withDimnames=FALSE" from the addGeneExpressionMatrix function. Can you help? 
My log file is attached.

My code:

`proj <- addGeneExpressionMatrix(input = proj, seRNA = seRNA, force = TRUE)`

```
The error I get:
Error in `assays<-`(`*tmp*`, withDimnames = withDimnames, ..., value = `*vtmp*`) :
  please use 'assay(x, withDimnames=FALSE)) <- value' or 'assays(x,
withDimnames=FALSE)) <- value' when the dimnames on the supplied
assay(s) are not identical to the dimnames on SingleCellExperiment
object 'x'

```
[ArchR-addGeneExpressionMatrix-185053f0f7f0-Date-2021-03-05_Time-19-05-00.log](https://github.com/GreenleafLab/ArchR/files/6094590/ArchR-addGeneExpressionMatrix-185053f0f7f0-Date-2021-03-05_Time-19-05-00.log)

**Comment by rcorces** [comment]
If I had to guess, I'd say that your `seRNA` is not properly formatted.
Your logfile indicates that it is stored as a `SingleCellExperiment` instead of a `RangedSummarizedExperiment`. The dimensions of these objects are quite different:

Your seRNA - 
```
class: SingleCellExperiment 
dim: 6 37463 
metadata(3): GDBAssayMetadata relationships .internal
assays(1): counts
rownames(6): ENSG00000223972 ENSG00000227232 ... ENSG00000284332
  ENSG00000237613
rowData names(7): ID aliases ... symbol desc
colnames(37463): SAM24395490#AAACAGCCAAACTAAG-1
  SAM24395490#AAACAGCCAACCGCCA-1 ... SAM24395840#TTTGTTGGTTATCCTA-1
  SAM24395840#TTTGTTGGTTCCATTA-1
colData names(9): Sample Barcode ... Condition Batch
```

Tutorial seRNA - 
```
## class: RangedSummarizedExperiment 
## dim: 36578 11909 
## metadata(0):
## assays(1): counts
## rownames(36578): MIR1302-2HG FAM138A ... AC007325.4 AC007325.2
## rowData names(5): feature_type genome id interval name
## colnames(11909): PBMC_10k#AAACAGCCAAGGAATC-1
##   PBMC_10k#AAACAGCCAATCCCTT-1 ... PBMC_10k#TTTGTTGGTTGGTTAG-1
##   PBMC_10k#TTTGTTGGTTTGCAGA-1
## colData names(0):
```

**Comment by jgranja24** [comment]
Hi @ldorozco can you just convert your singleCellExperiment?
```

library(ArchR)
library(SingleCellExperiment)

#Get Test seRNA
if(!file.exists("scRNA-Hematopoiesis-Granja-2019.rds")){
    download.file(
        url = "https://jeffgranja.s3.amazonaws.com/ArchR/TestData/scRNA-Hematopoiesis-Granja-2019.rds",
        destfile = "scRNA-Hematopoiesis-Granja-2019.rds"
    )
}
seRNA <- readRDS("scRNA-Hematopoiesis-Granja-2019.rds")
seRNA
# > seRNA
# class: RangedSummarizedExperiment 
# dim: 20287 35582 
# metadata(0):
# assays(1): counts
# rownames(20287): FAM138A OR4F5 ... S100B PRMT2
# rowData names(3): gene_name gene_id exonLength
# colnames(35582): CD34_32_R5:AAACCTGAGTATCGAA-1
#   CD34_32_R5:AAACCTGAGTCGTTTG-1 ...
#   BMMC_10x_GREENLEAF_REP2:TTTGTTGCATGTGTCA-1
#   BMMC_10x_GREENLEAF_REP2:TTTGTTGCATTGAAAG-1
# colData names(10): Group nUMI_pre ... BioClassification Barcode

scRNA <- as(seRNA, "SingleCellExperiment")
# class: SingleCellExperiment 
# dim: 20287 35582 
# metadata(0):
# assays(1): counts
# rownames(20287): FAM138A OR4F5 ... S100B PRMT2
# rowData names(3): gene_name gene_id exonLength
# colnames(35582): CD34_32_R5:AAACCTGAGTATCGAA-1
#   CD34_32_R5:AAACCTGAGTCGTTTG-1 ...
#   BMMC_10x_GREENLEAF_REP2:TTTGTTGCATGTGTCA-1
#   BMMC_10x_GREENLEAF_REP2:TTTGTTGCATTGAAAG-1
# colData names(10): Group nUMI_pre ... BioClassification Barcode
# reducedDimNames(0):
# altExpNames(0):

seRNA2 <- as(scRNA, "SummarizedExperiment")
# class: SummarizedExperiment 
# dim: 20287 35582 
# metadata(0):
# assays(1): counts
# rownames: NULL
# rowData names(0):
# colnames(35582): CD34_32_R5:AAACCTGAGTATCGAA-1
#   CD34_32_R5:AAACCTGAGTCGTTTG-1 ...
#   BMMC_10x_GREENLEAF_REP2:TTTGTTGCATGTGTCA-1
#   BMMC_10x_GREENLEAF_REP2:TTTGTTGCATTGAAAG-1
# colData names(10): Group nUMI_pre ... BioClassification Barcode

```

**Comment by ldorozco** [comment]
Thank you for your replies. I was not able to solve this by supplying my own seRNA, no matter how much I tried to format it. However, I was able to load the expression data as follows:
`seRNA <- import10xFeatureMatrix(
  input = c("/path/SAM1/outs/filtered_feature_bc_matrix.h5",  "/path/SAM2/outs/filtered_feature_bc_matrix.h5", "/path/SAM3/outs/filtered_feature_bc_matrix.h5"  ), names = c("SAM1", "SAM2", "SAM3")   )

seRNAcombined<- cbind( assay(seRNA[[1]]), assay(seRNA[[2]]), assay(seRNA[[3]])  )

seRNA2<-SummarizedExperiment(assays=list(counts=seRNAcombined), rowRanges=annot )  # where annot is my custom annotation Granges object

proj <- addGeneExpressionMatrix(input = proj, seRNA = seRNA2, force = TRUE, threads=1)`
