### ISSUE TITLE
maxDist argument in addCoAccessibility

### ISSUE THREAD

**Issue by Brawni** [GreenleafLab/ArchR#597]
Hello!

The maxDist argument in `addCoAccessibility` reads as: 
"The maximum allowable distance in basepairs between two peaks to consider for co-accessibility".
In the code this distance is used to resize the width of the region around each peak which are then overlapped with peak summits so shouldn't it be multiplied by 2?
https://github.com/GreenleafLab/ArchR/blob/a3c444db870aefa07b7f172e22d5610237b09bf6/R/IntegrativeAnalysis.R#L763

Thanks!

**Comment by rcorces** [comment]
I **think** the code is correct? But let me know if this logic is wrong.

If you take a single bp summit and resize it to `maxDist`, this means that the new window will be:

```
                     peakSummit
|------1/2 maxDist ------||------1/2 maxDist ------|
```

If you try to overlap two such peaks, they will each contribute `1/2 maxDist` from their center so the total distance would be `maxDist`. Right?

**Comment by Brawni** [comment]
Hi Ryan thanks for your quick reply!
Yes that would work but in the code the overlap is computed between a set of resized peaks using maxDist and a set of peaks resized to 1:
```
  #Create Ranges
  peakSummits <- resize(peakSet, 1, "center")
  peakWindows <- resize(peakSummits, maxDist, "center")

  #Create Pairwise Things to Test
  o <- DataFrame(findOverlaps(peakSummits, peakWindows, ignore.strand = TRUE))
  o <- o[o[,1] != o[,2],]

```
So I think this way the max distance between two peaks is in facts maxDist /2

**Comment by jgranja24** [comment]
Hi @Brawni,

I believe you are correct this should read similar to what you are saying. I believe that this was a documentation issue which I think is better solved if we just handle it more appropriately as below.. I fixed this for release_1.0.2.  

` 
peakWindows <- resize(peakSummits, 2*maxDist + 1, "center")
`

Best

Jeff
