### ISSUE TITLE
Something about Data format exporting and operation on matrix

### ISSUE THREAD

**Issue by jefferyUstc** [GreenleafLab/ArchR#600]
Hi, I have gone through the paper and docs these days and great work! And I have some questions in my utilization on my own data analysis when using ArchR. 

1. are there any utility interfaces to export h5ad or Seurat formats? 
2. or instead, how can i get access to the matrixs in `getAvailableMatrices(proj)` .  i hope i can export and import custom matrix.

thank you so much!

**Comment by rcorces** [comment]
Please note that only bugs in the software should be reported using "Issues". All other questions and feature requests should be directed to the "Discussions" page on GitHub - https://github.com/GreenleafLab/ArchR/discussions

This is stated in the issue template instructions:
![image](https://user-images.githubusercontent.com/10343046/110341357-1879c480-7fdf-11eb-8bc5-91151addc898.png)

I am closing this and you are welcome to open it in Discussions.
