### ISSUE TITLE
Error in quantile.default(corGSM_MM$maxDelta, 0.75)::    missing values and NaN's not allowed if 'na.rm' is FALSE

### ISSUE THREAD

**Issue by sylestiel** [GreenleafLab/ArchR#604]
Problem encountered when running scripts from Chapter15.4.2 Step 2. Identify Correlated TF Motifs and TF Gene Score/Expression on  Multiomic ATAC+GEX data.

Screen shot or error:

<img width="1049" alt="Screen Shot 2021-03-08 at 2 29 59 PM" src="https://user-images.githubusercontent.com/64283689/110378573-5bf22400-801b-11eb-9ee5-fa4a6c2e01af.png">

ArchR Log:
[ArchR-correlateMatrices-5997523071c7-Date-2021-03-08_Time-14-28-13.log](https://github.com/GreenleafLab/ArchR/files/6103980/ArchR-correlateMatrices-5997523071c7-Date-2021-03-08_Time-14-28-13.log)

Session Info:
<img width="1011" alt="Screen Shot 2021-03-08 at 2 35 35 PM" src="https://user-images.githubusercontent.com/64283689/110378746-922fa380-801b-11eb-9de1-fe111918bd96.png">

**Comment by ldorozco** [comment]
I ran into a similar error message for a different step analyzing multi-omics data, and the following filter fixed that error. It might work for you. It is from the "Ex-Analyze-Multiome" tutorial:

proj <- proj[ !is.na(proj$Gex_nUMI)]

**Comment by sylestiel** [comment]
Fixed by setting na.rm=TRUE
