### ISSUE TITLE
Monocle3 output directory not being created - Error in pdf(path, width = 6, height = 6, useDingbats = FALSE) : 

### ISSUE THREAD

**Issue by sylestiel** [GreenleafLab/ArchR#605]
Attempting to run the new trajectory html
https://greenleaflab.github.io/ArchR_2020/Ex-Analyze-Trajectory.html

Ran into following error:
<img width="1018" alt="Screen Shot 2021-03-08 at 3 14 17 PM" src="https://user-images.githubusercontent.com/64283689/110382800-0587e400-8021-11eb-9a03-2a7fe15239a3.png">
<img width="1025" alt="Screen Shot 2021-03-08 at 3 19 36 PM" src="https://user-images.githubusercontent.com/64283689/110383322-b8584200-8021-11eb-959b-8035556a1579.png">

**Comment by sylestiel** [comment]
@rcorces @jgranja24 

Still waiting on some input to run the new trajectory html. Cannot get past the error encountered in the first step.

**Comment by rcorces** [comment]
Sorry for not replying sooner but this does not appear to be an ArchR problem. Your error is with a non ArchR function (https://www.rdocumentation.org/packages/grDevices/versions/3.6.2/topics/pdf) and the error you are receiving does not look like something related to ArchR. Feel free to use some other plotting device.

**Comment by cschmidl** [comment]
For me the problem was fixed by creating the Monocole3 directory in the path myself...

**Comment by markphillippebworth** [comment]
I was able to fix the problem that way too. Looks like ArchR's wrapper doesn't make the Monocole3 folder.

**Comment by rcorces** [comment]
This was fixed via https://github.com/GreenleafLab/ArchR/commit/44a0d27840d4e11a6ee04bd9f26f01761b1ff017 on `dev` and will be incorporated into the next release.
