### ISSUE TITLE
Interpretation of ArchRBroswer of Peak to gene list  

### ISSUE THREAD

**Issue by NinaJiangL** [GreenleafLab/ArchR#614]
Hi,
Could you provide more detail for how to interpretate this peak to gene Track ? especially for the bottom part of Genes which showed in red and blue? what is the different color stand for ? 
![image](https://user-images.githubusercontent.com/18588687/110808154-b19a2b00-82be-11eb-91b5-4a032d7804e0.png)
and for the position and size of the gene , are they accurate?

**Comment by rcorces** [comment]
Hi @NinaJiangL - Please note that we no longer are accepting questions or feature requests as issues. This is stated clearly when you try to submit a new issue:
![image](https://user-images.githubusercontent.com/10343046/110809946-3131e680-823a-11eb-9deb-0d245bd5a318.png)

and again in the issue template:

![image](https://user-images.githubusercontent.com/10343046/110810043-4444b680-823a-11eb-974e-025d7b5cc1d1.png)

I am closing this issue but you may open a Discussions thread in the Q&A section.
