### ISSUE TITLE
ArchBrowser Plots keep changing even when the parameters are kept constant

### ISSUE THREAD

**Issue by Kaivalyamolugu** [GreenleafLab/ArchR#626]
Hello, 

I am trying make some plots using ArchR browser for my samples. The plots keep changing each time I hit "Plot track" even though I keep all the parameters constant. Any idea why this is happening?

Attached are two such plots that look different with same parameters. Thank you!
![image](https://user-images.githubusercontent.com/43280402/111040099-31c3ac00-83f7-11eb-9e28-eceeda15e61a.png)
![image](https://user-images.githubusercontent.com/43280402/111040105-3b4d1400-83f7-11eb-990a-7d2f2b5912cd.png)

**Comment by Kaivalyamolugu** [comment]
Hello, 

Thanks for checking. This is true even for -250 to 250 kb window (see attached plots). So I'm not sure how to proceed. 

![image](https://user-images.githubusercontent.com/43280402/111359381-6e8edd80-8659-11eb-821d-b88faaae9d71.png)
![image](https://user-images.githubusercontent.com/43280402/111359429-7f3f5380-8659-11eb-8f16-8d0c43905d78.png)

**Comment by rcorces** [comment]
True - It is more subtle zoomed out so I hadnt noticed.
@jgranja24 - any idea?

**Comment by jgranja24** [comment]
This is just a seeding in the random cells being generated. Set a seed prior to running and you will get the same answer--

```
library(ArchR)

proj <- getTestProject()

set.seed(1)
p1 <- plotBrowserTrack(
	ArchRProj = proj,
	groupBy = "Clusters",
	geneSymbol = "CD8A",
	upstream = 5000,
	downstream = 5000
)

set.seed(1)
p2 <- plotBrowserTrack(
	ArchRProj = proj,
	groupBy = "Clusters",
	geneSymbol = "CD8A",
	upstream = 5000,
	downstream = 5000
)

plotPDF(p1, p2, name = "TestTrack")
```

Not using a seed --

<img width="865" alt="Screen Shot 2021-04-04 at 8 48 23 PM" src="https://user-images.githubusercontent.com/25017655/113535043-32c7a380-9587-11eb-8d44-04b9abbbb050.png">
<img width="872" alt="Screen Shot 2021-04-04 at 8 48 17 PM" src="https://user-images.githubusercontent.com/25017655/113535046-34916700-9587-11eb-9ffd-e5a8349ba50a.png">

Using a seed --

<img width="847" alt="Screen Shot 2021-04-04 at 8 48 30 PM" src="https://user-images.githubusercontent.com/25017655/113535059-3b1fde80-9587-11eb-860a-88c8c4d4957f.png">

<img width="851" alt="Screen Shot 2021-04-04 at 8 48 35 PM" src="https://user-images.githubusercontent.com/25017655/113535057-39eeb180-9587-11eb-9105-f35f44659109.png">
