### ISSUE TITLE
addTileMatrix error

### ISSUE THREAD

**Issue by boconnell89** [GreenleafLab/ArchR#634]
**Attach your log file**
[ArchR-addTileMatrix-377fddef4f88-Date-2021-03-20_Time-14-30-46.log](https://github.com/GreenleafLab/ArchR/files/6176471/ArchR-addTileMatrix-377fddef4f88-Date-2021-03-20_Time-14-30-46.log)

**Describe the bug**
ArchR throws an error when adding a tile matrix.
The error appears to be:
```
2021-03-20 14:33:35 : ERROR Found in .addTileMat for MouseBrain_sciATAC
LogFile = ArchRLogs/ArchR-addTileMatrix-377fddef4f88-Date-2021-03-20_Time-14-30-46.log

<simpleError in Matrix::sparseMatrix(i = c(trunc(start(fragments)/tileSize),     trunc(end(fragments)/tileSize)) + 1, j = as.vector(c(matchID,     matchID)), x = rep(1, 2 * length(fragments)), dims = c(nTiles,     length(cellNames))): all(dims >= dims.min) is not TRUE>
```

**To Reproduce**
This does not seem to be an error on the hematopoesis dataset. But it shows up regardless of what settings I tried when creating ArrowFiles. The data are in a sci-ATAC bam file.

**Expected behavior**
I expected to get a TileMatrix?

**Additional context**
Not sure if this matters, but the file was previously filtered, so there should be no 0-counts cell-IDs, and also it's ~200k cells if that matters.

**Comment by rcorces** [comment]
can you show a few lines of your bam file and the exact commands you are using?

**Comment by boconnell89** [comment]
Sure!
Bam file:
```
TCAACGAGAATATATCAACTTCGCCTACGATAGCTG:3305220395#0       16      chr1    3000031 10      51M     *       0       0       AGAGTTGGAATTAGGTCTTCTTTGAAGGTCTGGTAGAACTCTGCATTAAAC  FFFFFFFF:FFFFFF,FFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFF:F,     NM:i:0  MD:Z:51 AS:i:51 XS:i:46
AGTCTTAATTAACGACCGAGGATAGGCCGAACTATG:75960779.2#0       99      chr1    3000038 44      51M     =       3000181 194     GAATTAGGTCTTCTTTGAAGGTCTGGTAGAACTCTGCATTAAACCCATCTG  F:FFF,F:F:,FF:FF:FFFF:FFFFFFF:,FFFFFFFFF,FFFFF,:FFF     NM:i:0  MD:Z:51 AS:i:51 XS:i:46
AATACCTGATTCGGAAGTGTCAGTACAACCAGCATG:491549498.2#0      163     chr1    3000073 40      51M     =       3000131 109     GCATTAAACCCATCTGGTCCTGGGCTTTTTTTTTTTTTTTTTTTTTTTTTT  FFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFF,FF:F:FFFFFFF:FFFFF     NM:i:0  MD:Z:51 AS:i:51 XS:i:51
GAGATTCCGTCGTACGCGGCGTAAGATCAATATCGA:1625286981.2#0     163     chr1    3000073 40      40M11S  =       3000257 235     GCATTAAACCCATATGGTCCTGGGATTTTTGTTTTTTTTTATTTTATATTT  F,:F:FFFF,FF,,,F:FFFF,,,,,F,F,,:,,F:,,:,,,FFF,:FF:,     NM:i:3  MD:Z:13C10C5T9  AS:i:25 XS:i:32
TTATAGCTGGAGGCGGCGGCCAGACTGGACTTATGG:1526599844.2#0     163     chr1    3000073 40      51M     =       3000279 257     GCATTAAACCCATCTGGTCCTGGGCTTTTTTTTTTTTTTTTTTTTTTTTTT  FFFF:FF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:F:F:FFFFFFFF     NM:i:0  MD:Z:51 AS:i:51 XS:i:51
GTAAGGCCTCGTAACGGTGTTAATTCTGACGCGACC:648347875.2#0      163     chr1    3000083 36      40M11S  =       3000137 105     CATCTGGTCCTGGGCTTTTTTTTTTTTTTTTTTTTTTTTTGGTTGGGAGAA  FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFF,F,F:F,,,,     NM:i:0  MD:Z:40 AS:i:40 XS:i:50
ACGGACCTCAATCTCAATGTCAGTACATCCTTGGAG:1097930711#0       0       chr1    3000089 19      45M6S   *       0       0       CTCCTGGGCTTTTTTTTTTTTTTTTTTTTTTTTTTGGGTGGGAGAATAAAA  F,FFFFFFFFF,:FFF:FFFFFFFF,FF:F:FF:,F:F,,,,:,,:,F,,F     NM:i:1  MD:Z:0G44       AS:i:44 XS:i:40
AATACCTGATTCGGAAGTGTCAGTACAACCAGCATG:491549498.2#0      83      chr1    3000131 60      51M     =       3000073 -109    AGACTATTGATGACTGCCTCTATTTCTTTAGGGGAAATGGGACTTTTAGTC  FFFFFFFFFFFFFFFF:FFFFFFFFFFFFF:FFFFFF:FFFF:FFFFFF:F     NM:i:0  MD:Z:51 AS:i:51 XS:i:44 XA:Z:chr18,+11380302,7S44M,0;chr2,-10682243,42M9S,0;chr3,+13997724,9S42M,0;
CTAATATGAGATCTTGGTGCCAGACTACCATAATAA:2062388738#0       0       chr1    3000134 35      51M     *       0       0       CTATTGATGACTGCCTCTATTTCTTTAGGGGAAATGGGACTTTTAGTCCAT  FFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFF,FFFFFFFF,FFFFFFFFF     NM:i:0  MD:Z:51 AS:i:51 XS:i:41 XA:Z:chr18,-11380302,10S41M,0;
TCAACGAGCAGCGTCCAAGTTAATTCCCTAGACGAG:3409504482#0       0       chr1    3000136 42      51M     *       0       0       ATTGATGACTGCCTCTATTTCTTTAGGGGAAATGGGACTTTTAGTCCATGA  FFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFF     NM:i:0  MD:Z:51 AS:i:51 XS:i:39
```
Command for ArrowFile:
```
ArrowFiles <- createArrowFiles( inputFiles ="201115_MouseBrain.mm10.merged.bbrd.q10.filt.bam",
                                 sampleNames = "MouseBrain_sciATAC",
                                 minTSS = 3.0,
                                 minFrags = 0,
                                 maxFrags = 1000000000000,
                                 addTileMat = FALSE,
                                 addGeneScoreMat = TRUE,
                                 gsubExpression= ":.*")
```
Commands leading to addTileMatrix:
```
proj <- ArchRProject(ArrowFiles=ArrowFiles,outputDirectory="ArchR_test",copyArrows=TRUE)
proj<-addTileMatrix(input=proj, force=TRUE)
```

**Comment by rcorces** [comment]
My intuition is that more is needed for your bam file to be properly read. `createArrowFiles()` has a few parameters specifically for bam file input. I desperately need to add this to the documentation but just havent had time.
See `bcTag` and `bamFlag` for starters. 

For example:

```
ArrowBam10x <- createArrowFiles(
  inputFiles = bamfile_10x,
  sampleNames = "bam10x",
  minTSS = 4, #Dont set this too high because you can always increase later
  minFrags = 1000, 
  addTileMat = FALSE,
  addGeneScoreMat = FALSE,
  bcTag = "CB",
  bamFlag = list(isMinusStrand = FALSE, isProperPair = TRUE, isDuplicate = FALSE),
  force = TRUE
)
```

#106 #292 might be helpful as well if you havent seen them already

**Comment by boconnell89** [comment]
OK, I tried running with the bamFlag set.  My read names start with the barcode, so according to the reference I'm using the gsubExpression, instead of setting a bcTag:

>**gsubExpression** | A regular expression used to clean up the barcode tag string read in from a bam file. For example, if the barcode is appended to the readname or qname field like for the mouse atlas data from Cusanovic* and Hill* et al. (2018), the gsubExpression would be ":.*". This would retrieve the string after the colon as the barcode.

so the whole command was:
```
 ArrowFiles <- createArrowFiles( inputFiles ="201115_MouseBrain.mm10.merged.bbrd.q10.filt.bam",
                                                    sampleNames = "MouseBrain_sciATACv2",
                                                    minTSS=3,
                                                    minFrags=1000,
                                                    addTileMat=FALSE,
                                                    addGeneScoreMat=FALSE,
                                                    gsubExpression= ":.*",
                                                    bamFlag=list(isMinusStrand=FALSE, isProperPair=TRUE),
                                                    force =TRUE
                                                    )
```

Based on the log file, it seems to be correctly detecting the cell barcodes:

```
2021-03-20 19:19:04 : (MouseBrain_sciATACv2 : 1 of 1) .bamToTmp Fragments-Chunk-(1 of 105)-chr1:1-39094394, Class = data.frame
(MouseBrain_sciATACv2 : 1 of 1) .bamToTmp Fragments-Chunk-(1 of 105)-chr1:1-39094394: nRows = 9176884, nCols = 3
     start     end                                   RG
1: 3000042 3000226 AGTCTTAATTAACGACCGAGGATAGGCCGAACTATG
2: 3000077 3000176 AATACCTGATTCGGAAGTGTCAGTACAACCAGCATG
3: 3000077 3000302 GAGATTCCGTCGTACGCGGCGTAAGATCAATATCGA
4: 3000077 3000324 TTATAGCTGGAGGCGGCGGCCAGACTGGACTTATGG
5: 3000087 3000182 GTAAGGCCTCGTAACGGTGTTAATTCTGACGCGACC
6: 3000226 3000401 GTTCCGTAGGAAGTTATAGCCTCGGTGCTGATAATT
```
It was also able to make a gene score matrix, so it seems like the MM10 gene set is working correctly. Based on the addTileMatrix log, it gets through at least Chr1 and 2 before failing on Chr3 with the following error:
```
 testProject <-addTileMatrix(input = testProject, threads=32, force=TRUE)
ArchR logging to : ArchRLogs/ArchR-addTileMatrix-377fd582c59e5-Date-2021-03-20_Time-19-48-44.log
If there is an issue, please report to github with logFile!
2021-03-20 19:48:47 : Batch Execution w/ safelapply!, 0 mins elapsed.
Can not create group. Object with name 'TileMatrix' already exists.
2021-03-20 19:49:02 : Adding TileMatrix to MouseBrain_sciATACv2 for Chr (1 of 20)!, 0.246 mins elapsed.
2021-03-20 19:50:11 : Adding TileMatrix to MouseBrain_sciATACv2 for Chr (2 of 20)!, 1.392 mins elapsed.
2021-03-20 19:51:16 : Adding TileMatrix to MouseBrain_sciATACv2 for Chr (3 of 20)!, 2.486 mins elapsed.

************************************************************
2021-03-20 19:51:31 : ERROR Found in .addTileMat for MouseBrain_sciATACv2
LogFile = ArchRLogs/ArchR-addTileMatrix-377fd582c59e5-Date-2021-03-20_Time-19-48-44.log

<simpleError in Matrix::sparseMatrix(i = c(trunc(start(fragments)/tileSize),     trunc(end(fragments)/tileSize)) + 1, j = as.vector(c(matchID,     matchID)), x = rep(1, 2 * length(fragments)), dims = c(nTiles,     length(cellNames))): all(dims >= dims.min) is not TRUE>

************************************************************

Error in .logError(e, fn = ".addTileMat", info = sampleName, errorList = errorList,  :
  Exiting See Error Above
```

Is there a way to filter for insert length as mentioned in #106 , or is that check implemented directly in `createArrowFiles`?

**Comment by rcorces** [comment]
The filtering for insert fragment length is now done automatically in `createArrowFiles()` so no need to worry about that. 

Are you sure that you have the correct genome builds applied? This issue ran into a similar problem due to a mismatch in genomes being used:
https://github.com/GreenleafLab/ArchR/issues/307

Is it possible that the genome used to align the data is not mm10?

**Comment by boconnell89** [comment]
According to the sam file header, it's mapped to mm10.  I also tried it with another mouse library mapped to the same reference, and had the same issue (except it crashed on chr 4 instead of 3 this time).

```
************************************************************
2021-03-22 09:37:39 : ERROR Found in .addTileMat for 201221_MouseBrain_scATAC 
LogFile = ArchRLogs/ArchR-addTileMatrix-377fd2c377b0a-Date-2021-03-22_Time-09-35-00.log

<simpleError in Matrix::sparseMatrix(i = c(trunc(start(fragments)/tileSize),     trunc(end(fragments)/tileSize)) + 1, j = as.vector(c(matchID,     matchID)), x = rep(1, 2 * length(fragments)), dims = c(nTiles,     length(cellNames))): all(dims >= dims.min) is not TRUE>

2021-03-22 09:37:39 : errorList, Class = list

errorList$ArrowFile: length = 1
                                                                                                     201221_MouseBrain_scATAC 
"/home/groups/adey_lab/projects/201221_ArchRTest/ArrowFiles/201221_MouseBrain_scATAC.arrow" 


errorList$chromLengths: length = 20
     chr1      chr2      chr3      chr4      chr5      chr6 
195471971 182113224 160039680 156508116 151834684 149736546 


errorList$chr: length = 1
     chr4 
156508116 


errorList$mat: length = 1
[1] "mat"



************************************************************
```

I'm going to try and run another library that was from human, mapped to hg38, and see if that has the same error.

Do you think it's worth converting to a fragment file?

**Comment by rcorces** [comment]
You can try converting to a fragment file but full disclosure I'm not really sure how 10x is creating their fragment files and I cannot recapitulate the exact behavior. I started an issue around this here: https://github.com/GreenleafLab/ArchR/issues/589

I'm sorry I dont have an answer for you on the errors with your BAM file - I almost never work with BAM files as input so @jgranja24 would be the one to help here though it might be hard to pin him down.

**Comment by boconnell89** [comment]
This seems to not be a problem for a human library constructed by the same method, mapped to hg38. However, a colleague reported the same error using a _D. melanogaster_ library and a custom `genomeAnnotation` and `geneAnnotation`.

**Comment by jgranja24** [comment]
Hi @boconnell89, for some reason you are getting fragments that span beyond the chromosome length. 

`all(dims >= dims.min) is not TRUE`

If I look at the log file it says : 

NTiles_TileMatrix_3_chr3: length = 1 #Number of Tiles
  chr3 
320080 

Chromosome Lengths: 
     chr1      chr2      chr3      chr4      chr5      chr6 
195471971 182113224 160039680 156508116 151834684 149736546 

This number can be derived - ceiling((160039680 + 1)/500) = 320080

MaxTile_TileMatrix_3_chr3: length = 1 #Max Tile in Fragments
[1] 447794

Since 447794 > 320080 this errors out the way you see it. I think there may be an error with your fragments for this to occur ie something where a fragment got misaligned etc. I am updating the function to where it only uses fragments within the chromosome sizes, so it will minimize this error. However, you should verify the fragment with the highest 'end' on chromosome 3 and see if this is true as well.

**Comment by boconnell89** [comment]
I think it's an issue with the generation of the fragments, as I checked my bam file, and nothing is mapping with massive insert sizes or off of chromosomes.

**Comment by jgranja24** [comment]
@boconnell89 do you have an example bam file that you can send us at archr.devs@gmail.com? I'd need to try it out in my hands to better diagnose this issue.

**Comment by rcorces** [comment]
@boconnell89 - still need help on this?

**Comment by wshands** [comment]
Hi, which branch is the above check in? I'd like to use that check; or I can insert it myself if you let me know where to add it. Thanks!

**Comment by rcorces** [comment]
`release_1.0.2`
https://github.com/GreenleafLab/ArchR/blob/0d77da238cbcf6f4fa0c8daac4cec7df34c63a44/R/MatrixTiles.R#L210

**Comment by wshands** [comment]
The branch release_1.0.2 fixed the issue for me.

**Comment by rcorces** [comment]
Great. Thanks for that feedback. I will go ahead and close this issue then.

**Comment by adler-sudo** [comment]
I still get the error with the release_1.0.2. Continuing to explore why this might be happening.
