### ISSUE TITLE
how to get a imputation gene score matrix

### ISSUE THREAD

**Issue by tianchen2019** [GreenleafLab/ArchR#642]
This is an issue template made by the developers of ArchR. You MUST follow these instructions.

Questions related to how to use ArchR or requests for new features should be posted in the Discussions forum (https://github.com/GreenleafLab/ArchR/discussions).

Before you submit this Bug Report please update ArchR to the latest stable version and make sure that this issue has not already been fixed in the latest release. ArchR is still in active development and we will fix problems as they arise. To update ArchR:

devtools::install_github("GreenleafLab/ArchR", ref="master", repos = BiocManager::repositories())

If your issue persists, then please submit this bug report.

PLEASE FILL OUT THE RELEVANT INFORMATION AND DELETE THE UNUSED PORTIONS OF THIS ISSUE TEMPLATE.

**Attach your log file**
ArchR has a built-in logging functionality for all complex functions. You MUST attach your log file (indicated in the console output) to this issue. Just drag and drop it here.

**Describe the bug**
i used getMatrixFromProject(b,useMatrix = "GeneScoreMatrix") to get gene score matrix,but i want to know how to get a imputation gene score matrix.

**To Reproduce**
To help us optimally address your issue, please try to reproduce this issue using the tutorial hematopoiesis dataset and provide us the command(s) to reproduce your bug. Our first question to you will be "can you reproduce this with the tutorial dataset" so please do this.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Do not screenshot code or text but embed this in markdown using triple-backticks.

**Session Info**
If you do not have a log file because the function that caused the error does not produce one, please paste the output of "sessionInfo()" here.

**Additional context**

**Comment by rcorces** [comment]
Hi @tianchen2019 - I am closing this issue because this is not a "bug". As noted in the instructions in the Issue Report, questions about usage or feature requests should be posted in the Discussions forum. You are welcome to open a discussion topic there.
https://github.com/GreenleafLab/ArchR/discussions

![image](https://user-images.githubusercontent.com/10343046/112160030-008d6d80-8ba7-11eb-91dd-361f124b0637.png)
