### ISSUE TITLE
14.1: Myeloid Trajectory - error with addTrajectory()

### ISSUE THREAD

**Issue by hugokitano** [GreenleafLab/ArchR#65]
I'm trying to apply Myeloid Trajectory with my own data, and am running into an error with addTrajectory(), and I've tried it with different combinations of clusters for the trajectory.

```
trajectory <- c(paste0("Cluster", c(6, 7, 8, 9, 10))) # I changed these to experiment, some error
trajectory
# [1] "Cluster6"  "Cluster7"  "Cluster8"  "Cluster9"  "Cluster10"

#First we need to create a Trajectory and add it to ArchRProj cellColData
projAll <- addTrajectory(ArchRProj = projAll, name = "MyeloidU", trajectory = trajectory, embedding = "UMAP", force = TRUE)
```

I get the following error and traceback:
```
Error in smooth.spline(x = initialTime, y = matFilter[names(initialTime),  : 
  'tol' must be strictly positive and finite
> traceback()
8: stop("'tol' must be strictly positive and finite")
7: smooth.spline(x = initialTime, y = matFilter[names(initialTime), 
       x], df = dof, spar = spar)
6: FUN(X[[i]], ...)
5: lapply(seq_len(ncol(matFilter)), function(x) {
       smooth.spline(x = initialTime, y = matFilter[names(initialTime), 
           x], df = dof, spar = spar)[[2]]
   })
4: eval(lhs, parent, parent)
3: eval(lhs, parent, parent)
2: lapply(seq_len(ncol(matFilter)), function(x) {
       smooth.spline(x = initialTime, y = matFilter[names(initialTime), 
           x], df = dof, spar = spar)[[2]]
   }) %>% Reduce("cbind", .) %>% data.frame()
1: addTrajectory(ArchRProj = projAll, name = "MyeloidU", trajectory = trajectory, 
       embedding = "UMAP", force = TRUE)
```

So first things first, I clarified that the clustering for the project has occurred:
```
table(projAll$Clusters)

  C1   C2   C3   C4   C5   C6   C7   C8   C9 
  66 3689 3382   15  147 4326 2506 2680 3682 
```
Another issue is we do not have yet scRNA data to integrate into our project, so lines of codes like `p2 <- plotEmbedding(ArchRProj = projAll, colorBy = "cellColData", name = "Clusters2", embedding = "UMAP")`, a few lines before, do not work yet.

From scouring online, the smooth.spline error happens when the datasets were too small. I have a feeling they could even be of size 0 here, but I don't know how exactly to check. Any idea for how to solve this problem? Thank you!

Hugo

**Comment by jgranja24** [comment]
Im going to close this let me know if you have further issues!
