### ISSUE TITLE
error with plotGroups (ridges and violin)

### ISSUE THREAD

**Issue by wuzhigui** [GreenleafLab/ArchR#654]
This is my project .
![image](https://user-images.githubusercontent.com/70992194/112609937-19bc4580-8e57-11eb-913d-2a67ae50aca5.png)
I followed  the steps online in the https://www.archrproject.com/bookdown/plotting-sample-statistics-from-an-archrproject.html.
The proj_8 is the subset of my raw project in which Enrichment is cut by `idxPass <- which(proj$TSSEnrichment >= 8)`.
When I ran the step to draw the statistics of my filtered proj , `Error in .validInput(input = ArchRProj, name = "ArchRProj", valid = c("ArchRProj")) :  Input value for 'ArchRProj' is not a archrproj, (ArchRProj = NULL) please supply valid input!` returned to me !
Please help me !
![image](https://user-images.githubusercontent.com/70992194/112610672-ec23cc00-8e57-11eb-8431-d5098b8f083a.png)
Further when  I just try the raw project ,this error arised again !

**Comment by rcorces** [comment]
> Error in .validInput(input = ArchRProj, name = "ArchRProj", valid = c("ArchRProj")) : Input value for 'ArchRProj' is not a archrproj, (ArchRProj = NULL) please supply valid input!

This is quite explicit. Whatever you are inputting as your `proj` variable is not an ArchRProject object.

**Comment by jgranja24** [comment]
Hi @wuzhigui you are showing the class for an object called 'proj_8' but you are plotting an object called 'proj'. My suspicion is that you are supplying nothing and thus its interpreting as NULL. Please supply 'proj_8' or a valid ArchRProject and it should work. The error prints the class if it's not an ArchRProject.
