### ISSUE TITLE
plot of TSS enrichment score shown only for x> = 2.5 and x<=5.0 

### ISSUE THREAD

**Issue by sumandeb** [GreenleafLab/ArchR#664]
I recently started using ArchR for some elementary data analysis and have a query. I executed the following command and the attached QC plot was created because of it. As you can see in the plot, the plot is getting cut at x=2.5. How to plot TTS ES that includes points below x=2.5 and above x=5 also
[XHP203-TSS_by_Unique_Frags.pdf](https://github.com/GreenleafLab/ArchR/files/6220506/XHP203-TSS_by_Unique_Frags.pdf)
[XHP203-TSS_by_Unique_Frags.pdf](https://github.com/GreenleafLab/ArchR/files/6220509/XHP203-TSS_by_Unique_Frags.pdf)

? The latter should be possible by putting maxFrags to a value higher than the default value of 10^5. Kindly advice.

ArrowFiles <- createArrowFiles(
  inputFiles = "fragments_XHP203.tsv.gz",
  sampleNames = "XHP203",
  minTSS = 0, #Dont set this too high because you can always increase later
  minFrags = 0,
  addTileMat = TRUE,
  addGeneScoreMat = TRUE
)

**Comment by rcorces** [comment]
`maxFrags` controls which cells are retained in the Arrow files, not which cells are plotted on the default plot output by `createArrowFiles()`. You are welcome to make this plot yourself using the data stored in `cellColData` but we do not provide a mechanism to change the defaults for `createArrowFiles()`.

see the `ggPoint()` function and the parameter `colorDensity`
