### ISSUE TITLE
addGeneScoreMatrix does not work properly when subThreading is FALSE

### ISSUE THREAD

**Issue by dagarfield** [GreenleafLab/ArchR#670]
Pretty simple bug:

`addGeneScoreMatrix(projSpurp_doubletRemoved_filtered2,
                   excludeChr = c("NC_001453.1"),
                   force = TRUE,
                   subThreading = FALSE
                  )`

Result:

> Error in addGeneScoreMatrix(projSpurp_doubletRemoved_filtered2, excludeChr = c("NC_001453.1"), : object 'inputFiles' not found
Traceback:

> 1. addGeneScoreMatrix(projSpurp_doubletRemoved_filtered2, excludeChr = c("NC_001453.1"), 
 .     force = TRUE, subThreading = FALSE)

Likely cause (from the function): 

`    if (subThreading) {
        h5disableFileLocking()
    }
    else {
        args$threads <- length(inputFiles)
    }`

Presumably `inputFiles` should be `ArrowFiles`?
inputFiles is not an argument to addGeneScoreMatrix.

**Comment by rcorces** [comment]
Thanks for reporting this!

**Comment by dagarfield** [comment]
No problem! Nice to report something not related to my stupid non-model system genome for once.....

**Comment by jgranja24** [comment]
@dagarfield thanks for pointing this out this is updated in the newest release.
