### ISSUE TITLE
Vierstra Matrix

### ISSUE THREAD

**Issue by erikla** [GreenleafLab/ArchR#675]
Hi,

Relating to a resolved issue [214](https://github.com/GreenleafLab/ArchR/issues/214).
It appears calling plotEmbedding() does not work with the provided motif names.  The names conflict with what is expected in ArchR:::.getMatrixValues() function.  Can you provide a suggestion or fix?

Thanks for the great package.

**Comment by rcorces** [comment]
can you provide a reproducible example with the tutorial dataset and the code and errors you receive?

**Comment by erikla** [comment]
A quick example:

# save the motifs
> system(paste("wget https://jeffgranja.s3.amazonaws.com/ArchR/Annotations/Vierstra-Human-Motifs.rds -O", > file.path(robj.dir,"Vierstra-Human-Motifs.rds")))

# read the motifs
> motifPWMs <- readRDS(file.path(robj.dir,"Vierstra-Human-Motifs.rds"))

# scan the motifs and add to project
> proj <- addMotifAnnotations(proj, motifPWMs = motifPWMs, name = "Vierstra", force = TRUE)
> proj <- addDeviationsMatrix(proj, peakAnnotation = "Vierstra", force = TRUE)

>   # choose a motif to plot on UMAP
>   dev <- getFeatures(proj, select = 'Arid5a_34#ARI5A:ARID:88:1', useMatrix = "VierstraMatrix")
>   (dev <- sort(grep("z:", dev, value = TRUE)) %>% gsub("z:","",.))
[1] "Arid5a_34#ARI5A:ARID:88:1"
>   p <- plotEmbedding(
+     ArchRProj = proj,
+     colorBy = "VierstraMatrix",
+     name = dev,
+     embedding = "UMAP",
+     plotAs = 'points',
+     size = 0.5,
+     imputeWeights = getImputeWeights(proj)
+   )
Getting ImputeWeights
ArchR logging to : ArchRLogs/ArchR-plotEmbedding-3ec6a39706466-Date-2021-04-13_Time-17-28-28.log
If there is an issue, please report to github with logFile!
2021-04-13 17:28:28 : Getting Matrix Values...
Error: FeatureName (ARID) does not exist! See getFeatures


Pretty sure the error is coming from .getMatrixValues

thanks,
e

**Comment by rcorces** [comment]
Thanks @erikla for the report. I think your original intuition is correct. `.getMatrixValues()` performs a string split on ":" which is used to identify "z:" or "deviations:" but is unfortunately also present in the Vierstra motif names. You can get around this by changing the motif names in the `PWMatrixList` object before performing `addMotifAnnotations()`. Note that the way you were manipulating the feature names (removing the "z:" etc.) is not the correct way to do it but I assume you tried that to get around the ":" split problem.

```
# read the motifs
motifPWMs <- readRDS("Vierstra-Human-Motifs.rds")

#Fix the names to remove :
names(motifPWMs) <- gsub(pattern = ":", replacement = "._.", x = names(motifPWMs))

# scan the motifs and add to project
projHeme5 <- addMotifAnnotations(projHeme5, motifPWMs = motifPWMs, name = "Vierstra", force = TRUE)
projHeme5 <- addDeviationsMatrix(projHeme5, peakAnnotation = "Vierstra", force = TRUE)

# choose a motif to plot on UMAP
dev <- getFeatures(projHeme5, select = 'Arid5a_34#ARI5A._.ARID._.88._.1', useMatrix = "VierstraMatrix")
dev <- grep("z:", dev, value = TRUE)
p <- plotEmbedding(
    ArchRProj = projHeme5,
    colorBy = "VierstraMatrix",
    name = dev,
    embedding = "UMAP")
```

@jgranja24 - you should fix that `rds` object on AWS to have something other than ":" in the name.

**Comment by erikla** [comment]
Thanks.

**Comment by rcorces** [comment]
Going to leave this open as a reminder for @jgranja24 to update the RDS object on AWS.

**Comment by rcorces** [comment]
I have fixed this in the process of incorporating the beta v2 Vierstra motifs.
see https://github.com/GreenleafLab/ArchR/pull/1385
and https://github.com/GreenleafLab/ArchR/discussions/1386
