### ISSUE TITLE
Creating a Custom ArchRGenome

### ISSUE THREAD

**Issue by wangyuu** [GreenleafLab/ArchR#682]
I have created a Btaurus ArchRGenome successfully as following:
> library(BSgenome.Btaurus.UCSC.bosTau9)
> library(TxDb.Btaurus.UCSC.bosTau9.refGene)
> library(org.Bt.eg.db)
> genomeAnnotation <- createGenomeAnnotation(genome = BSgenome.Btaurus.UCSC.bosTau9)
> geneAnnotation <- createGeneAnnotation(TxDb = TxDb.Btaurus.UCSC.bosTau9.refGene, OrgDb = org.Bt.eg.db)
> genomeAnnotation
List of length 3
names(3): genome chromSizes blacklist
> geneAnnotation
List of length 3
names(3): genes exons TSS

When  I tried to  create Arrow files and got an error,
> ArrowFiles <- createArrowFiles(inputFiles = inputFiles,sampleNames = names(inputFiles),filterTSS = 4,filterFrags = 1000,addTileMat = TRUE,addGeneScoreMat = TRUE)
filterFrags is no longer a valid input. Please use minFrags! Setting filterFrags value to minFrags!
filterTSS is no longer a valid input. Please use minTSS! Setting filterTSS value to minTSS!
Error in getGeneAnnotation() :
  getGeneAnnotation : ArchRPRoj is NULL and there is no genome set with addArchRGenome!

How can I resolve this problem?

**Comment by rcorces** [comment]
You must provide your `geneAnnotation` and `genomeAnnotation` to `createArrowFiles()`. See the function parameters:
https://www.archrproject.com/reference/createArrowFiles.html

Please close if this answers your question
