### ISSUE TITLE
issue in addPeak2GeneLinks

### ISSUE THREAD

**Issue by 1221li** [GreenleafLab/ArchR#700]
Dear,
I'm having some problems running 15.3 Peak2GeneLinkage with Archr.Here's a sample of the code I ran.I'm taking the  unmodified Seurat objects as input to the integration workflow in the eighth chapter,but I have a problem in chapter 15.

```
> projHeme3 <- addGeneIntegrationMatrix(ArchRProj = projIVO3,useMatrix = "GeneScoreMatrix",matrixName = "GeneIntegrationMatrix",reducedDims = "IterativeLSI",seRNA =embryo,addToArrow = FALSE, groupRNA ="seurat_clusters", nameCell = "predictedCell",nameGroup = "predictedGroup",nameScore = "predictedScore")
> projHeme4 <- addGroupCoverages(ArchRProj = projHeme3, groupBy = "predictedGroup")
> projHemeTmp <- addReproduciblePeakSet(ArchRProj = projHeme4,groupBy = "predictedGroup",peakMethod = "Tiles", method = "p")
> projHeme5 <- addPeakMatrix(projHemeTmp)
> projHeme6 <- addCoAccessibility(ArchRProj = projHeme5, reducedDims = "IterativeLSI")
> projHeme6 <- addPeak2GeneLinks(ArchRProj = projHeme5,useMatrix = "GeneIntegrationMatrix",reducedDims = "IterativeLSI")
ArchR logging to : ArchRLogs/ArchR-addPeak2GeneLinks-ac69428023a0-Date-2021-04-21_Time-09-39-38.log
If there is an issue, please report to github with logFile!
2021-04-21 09:39:38 : Getting Available Matrices, 0.005 mins elapsed.
Error in addPeak2GeneLinks(ArchRProj = projHeme5, useMatrix = "GeneIntegrationMatrix",  : 
  GeneIntegrationMatrix not in AvailableMatrices
> projHeme7 <- addPeak2GeneLinks(ArchRProj = projHeme6,useMatrix = "GeneIntegrationMatrix",reducedDims = "IterativeLSI")
ArchR logging to : ArchRLogs/ArchR-addPeak2GeneLinks-ac695a41835f-Date-2021-04-21_Time-09-57-58.log
If there is an issue, please report to github with logFile!
2021-04-21 09:57:59 : Getting Available Matrices, 0.006 mins elapsed.
Error in addPeak2GeneLinks(ArchRProj = projHeme6, useMatrix = "GeneIntegrationMatrix",  : 
  GeneIntegrationMatrix not in AvailableMatrices
```

I would like to know what causes this situation.I am looking forward to your reply!

**Comment by ChangliangWang** [comment]
GeneIntegrationMatrix not in AvailableMatrices.  You should add 'GeneIntegrationMatrix' to arrow files by setting the parameter 'addToArrow = TRUE' of 'addGeneIntegrationMatrix' function.

**Comment by 1221li** [comment]
Thank you for your answer.It's very useful for me.But I have new doubts.After I made it through 15.3, I realized that the 
Peak2GeneLinks part of the graph was missing.and then i try:

p2g <- getPeak2GeneLinks(ArchRProj = projHeme6,corCutOff = 0.45,resolution = 1,returnLoops = TRUE)
p2g
NULL
p <- plotPeak2GeneHeatmap(ArchRProj = projHeme6, groupBy = "predictedGroup")
Error in plotPeak2GeneHeatmap(ArchRProj = projHeme6, groupBy = "predictedGroup") :
No Peak2GeneLinks Found! Try addPeak2GeneLinks!

I got this error.
I did the Unconstrained Integration before.Is that the reason?
Anyway, I'm trying to do the Constrained Integration part, but maybe I made a mistake in defining groupList.
> projHeme3_2 <- addGeneIntegrationMatrix(ArchRProj = projIVO3,useMatrix = "GeneScoreMatrix",matrixName = "GeneIntegrationMatrix",reducedDims = "IterativeLSI",seRNA =embryo,addToArrow = TRUE, force = TRUE,groupList = groupList,groupRNA ="seurat_clusters", nameCell = "predictedCell",nameGroup = "predictedGroup",nameScore = "predictedScore")
ArchR logging to : ArchRLogs/ArchR-addGeneIntegrationMatrix-ac6963ecf914-Date-2021-04-21_Time-14-35-05.log
If there is an issue, please report to github with logFile!
2021-04-21 14:35:06 : Running Seurat's Integration Stuart* et al 2019, 0.007 mins elapsed.
Warning: The following arguments are not used: drop
2021-04-21 14:35:06 : Checking ATAC Input, 0.013 mins elapsed.
Error in addGeneIntegrationMatrix(ArchRProj = projIVO3, useMatrix = "GeneScoreMatrix",  : 
  Missing 520 cells. Found 0 overlapping cells from ArchRProj in groupList! Cannot have overlapping/missing cells in ATAC input, check 'groupList' argument!
> groupList
List of length 2
names(2): IVO1 IVO2


Could you help me find the error, please?I look forward to your answers to these two questions.thank you!

**Comment by ChangliangWang** [comment]
"p2g is NULL": I think, it might be associated with the cutoff you set. 
"Missing 520 cells": I think, you should make sure the 'groupList' covers the cells in your scATAC data.

**Comment by 1221li** [comment]
Thank you very much for your help. Now I have got the result I want.
