### ISSUE TITLE
Could I add a modified GeneIntegrationMatrix to arrow file?

### ISSUE THREAD

**Issue by ChangliangWang** [GreenleafLab/ArchR#701]
Dear ArchR developers,

I have got the 'GeneIntegrationMatrix ' using 'getMatrixFromProject' function and I have modified the matrix. I am wondering how to add my modified 'GeneIntegrationMatrix' to the arrow file and use the modified 'GeneIntegrationMatrix'  to do downstream analysis.

Thanks very much for your help.

Best regards,
Changliang.

**Comment by rcorces** [comment]
This is not currently a feature in ArchR though it is planned in the future.

We've migrated feature requests to the Discussions platform in GitHub so I am moving this issue to the "Ideas" section there.
