### ISSUE TITLE
Issue with BulkProjection and .loadUWOT

### ISSUE THREAD

**Issue by juliaed** [GreenleafLab/ArchR#706]
I am having problems using the projectBulkATAC function from the latest release.

My code is :
```
projected = projectBulkATAC(
   ArchRProj = proj3,
   seATAC = bulk_se,
   reducedDims = "IterativeLSIOnPeaks",
   embedding = "UMAPOnPeaks", threads =1,
   n = 250)
```

Console output : 
```
ArchR logging to : ArchRLogs/ArchR-projectBulkATAC-240c354cc1f6-Date-2021-04-22_Time-22-37-37.log
If there is an issue, please report to github with logFile!
2021-04-22 22:37:39 : Overlap Ratio of Reduced Dims Features = 1
2021-04-22 22:37:40 : Projecting Sample (1 of 2), 0.045 mins elapsed.
2021-04-22 22:37:41 : Projecting Sample (2 of 2), 0.072 mins elapsed.
Error in .loadUWOT(embedding$params$uwotModel, embedding$params$nc) : 
  unused argument (embedding$params$nc)
```
It seems the new `.loadUWOT` function from `Embedding.R` only takes one argument

``` #New Save UWOT
.loadUWOT <- function(file){
  tryCatch({
    uwot::load_uwot(file = file, verbose = TRUE)
  }, error = function(e){
    .loadUWOT_Deprecated(file = file, nDim = nDim) #backwards to previous version
  })
```

Whereas `projectBulkATAC.R`still calls it with the second argument `nDim` :
`umapModel <- .loadUWOT(embedding$params$uwotModel, embedding$params$nc)`

**Comment by rcorces** [comment]
hmmm. This is a backwards compatibility problem from a change in `uwot`. I think the actual problem is that the `.loadUWOT()` function definition should allow for passing of `nDim` still with a default value of `NULL`. Otherwise, users with old versions of `UWOT` wont be able to call `uwot::load_uwot`

@jgranja24 - can you confirm?

https://github.com/GreenleafLab/ArchR/blob/968e4421ce7187a8ac7ea1cf6077412126876d5f/R/Embedding.R#L256

**Comment by juliaed** [comment]
Thank you for your quick answer. It does work with  uwot_0.1.10  when I changed to
```.loadUWOT <- function(file, nDim = NULL){```

I did not try with other uwot versions though.

And thanks for the great package !

**Comment by rcorces** [comment]
Thanks @juliaed - I've gone ahead and made that change to the code base via https://github.com/GreenleafLab/ArchR/commit/bac49aef6ac74c1d1d049d4c12dc6ea1bf8cd25d
This is reflected in the current dev branch ("release_1.0.2")
