### ISSUE TITLE
Error: row names contain missing values

### ISSUE THREAD

**Issue by snigdha-a** [GreenleafLab/ArchR#712]
[ArchR-addReproduciblePeakSet-2bf124d61b4e9-Date-2021-04-24_Time-18-17-08.log](https://github.com/GreenleafLab/ArchR/files/6370851/ArchR-addReproduciblePeakSet-2bf124d61b4e9-Date-2021-04-24_Time-18-17-08.log)

**Describe the bug**

When I try to call peaks after subsetting the ArchRProject, I get the following error:
![Screen Shot 2021-04-24 at 6 19 49 PM](https://user-images.githubusercontent.com/59067635/115974304-aa0aaa80-a529-11eb-8315-0be27da79c1e.png)

**Expected behavior**
I wish to take an ArchrProject and subset using a list of cellNames. I then want to call peaks on just those cells.

**Screenshots**
Subset code:
``` projHeme1 <- readRDS("Save-ProjHeme1/Save-ArchR-Project.rds")
mono_cells <- scan('monocyte_groupcodes',what ='character', sep = "\n")
mono_cells <- intersect(mono_cells,projHeme1$cellNames) # some mono barcodes are not in archrProject
projHeme1 <- subsetArchRProject(
  ArchRProj = projHeme1,
  cells = mono_cells,
  outputDirectory = "ArchRSubset",
  dropCells = TRUE,
  logFile = NULL,
  threads = getArchRThreads(),
  force = TRUE
)
```
Peak calling code (which gives error in the screenshot above):
```
projHeme1 <- readRDS("ArchRSubset/Save-ArchR-Project.rds")
pathToMacs2 <- findMacs2()
projHeme1 <- addReproduciblePeakSet(
    ArchRProj = projHeme1,
    groupBy = "Cluster",
    pathToMacs2 = pathToMacs2,
    force=TRUE
)
```

**Comment by rcorces** [comment]
I cant be sure that this is your problem but you cannot load an ArchRProject like this:

> projHeme1 <- readRDS("ArchRSubset/Save-ArchR-Project.rds")

try using the `loadArchRProject()` function.

**Comment by snigdha-a** [comment]
Thanks for the tip. Tried that but it didn't make the error go away. Also I've used this command in the past. Does it cause any problems?
![Screen Shot 2021-04-24 at 8 08 55 PM](https://user-images.githubusercontent.com/59067635/115976138-e7c2ff80-a538-11eb-83ea-9219cba7b9d4.png)

**Comment by rcorces** [comment]
Reading in an ArchRProject object with `readRDS` is not an approved use. Feel free to browse the source code for `loadArchRProject()`. You'll find that it is doing a lot more than simply reading in the RDS file.

Please create a reproducible example (from scratch) with the tutorial data.

Also, it is helpful to us if you avoid pasting screenshots of text and use markdown syntax "```" to encase text blocks. This makes it possible to copy and paste text.

**Comment by snigdha-a** [comment]
I tried it with the tutorial data. Log file:
[ArchR-addReproduciblePeakSet-2c21f3c9ed19d-Date-2021-04-25_Time-00-10-28.log](https://github.com/GreenleafLab/ArchR/files/6371232/ArchR-addReproduciblePeakSet-2c21f3c9ed19d-Date-2021-04-25_Time-00-10-28.log)

The entire code:
```
addArchRThreads(threads = 6)
addArchRGenome("hg19")
inputFiles <- getTutorialData("Hematopoiesis")
ArrowFiles <- createArrowFiles(
  inputFiles = inputFiles,
  sampleNames = names(inputFiles),
  filterTSS = 4, #Dont set this too high because you can always increase later
  filterFrags = 1000, 
  addTileMat = TRUE,
  addGeneScoreMat = TRUE
)
projHeme1 <- ArchRProject(
  ArrowFiles = ArrowFiles, 
  outputDirectory = "HemeTutorial",
  copyArrows = TRUE #This is recommened so that if you modify the Arrow files you have an original copy for later usage.
)
saveArchRProject(ArchRProj = projHeme1, outputDirectory = "Tutorial-ArchR", load = FALSE)
```
```
pj1 <- loadArchRProject("Tutorial-ArchR",showLogo=FALSE)
pj1 <- addCellColData(ArchRProj = pj1, data = our_clusters[1:length(pj1$cellNames)], cells=pj1$cellNames, name = "Cluster")
pj1 <- addGroupCoverages(
  ArchRProj = pj1,
  groupBy = "Cluster", 
  force =FALSE
)
```
```
pj1 <- subsetArchRProject(
  ArchRProj = pj1,
  cells = sample(pj1$cellNames, 200),
  outputDirectory = "HemeTutorial1",
  dropCells = TRUE,
  logFile = NULL,
  threads = getArchRThreads(),
    force=TRUE
)
pathToMacs2 <- findMacs2()
pj1 <- addReproduciblePeakSet(
    ArchRProj = pj1,
    groupBy = "Cluster",
    pathToMacs2 = pathToMacs2,
    force=TRUE
)
pj1
```

Still the same error:
```
Error in data.frame(Group = names(coverageParams$cellGroups)[y], nCells = tableGroups[names(coverageParams$cellGroups)[y]], : row names contain missing values
Traceback:

1. addReproduciblePeakSet(ArchRProj = pj1, groupBy = "Cluster", 
 .     pathToMacs2 = pathToMacs2, force = TRUE)
2. lapply(seq_along(coverageParams$cellGroups), function(y) {
 .     x <- coverageParams$cellGroups[[y]]
 .     uniq <- unique(unlist(x))
 .     n <- lapply(x, length) %>% unlist %>% sum
 .     nmin <- lapply(x, length) %>% unlist %>% min
 .     nmax <- lapply(x, length) %>% unlist %>% max
 .     data.frame(Group = names(coverageParams$cellGroups)[y], nCells = tableGroups[names(coverageParams$cellGroups)[y]], 
 .         nCellsUsed = length(uniq), nReplicates = length(x), nMin = nmin, 
 .         nMax = nmax, maxPeaks = min(maxPeaks, length(uniq) * 
 .             peaksPerCell))
 . }) %>% Reduce("rbind", .)
3. Reduce("rbind", .)
4. lapply(seq_along(coverageParams$cellGroups), function(y) {
 .     x <- coverageParams$cellGroups[[y]]
 .     uniq <- unique(unlist(x))
 .     n <- lapply(x, length) %>% unlist %>% sum
 .     nmin <- lapply(x, length) %>% unlist %>% min
 .     nmax <- lapply(x, length) %>% unlist %>% max
 .     data.frame(Group = names(coverageParams$cellGroups)[y], nCells = tableGroups[names(coverageParams$cellGroups)[y]], 
 .         nCellsUsed = length(uniq), nReplicates = length(x), nMin = nmin, 
 .         nMax = nmax, maxPeaks = min(maxPeaks, length(uniq) * 
 .             peaksPerCell))
 . })
5. FUN(X[[i]], ...)
6. data.frame(Group = names(coverageParams$cellGroups)[y], nCells = tableGroups[names(coverageParams$cellGroups)[y]], 
 .     nCellsUsed = length(uniq), nReplicates = length(x), nMin = nmin, 
 .     nMax = nmax, maxPeaks = min(maxPeaks, length(uniq) * peaksPerCell))
7. stop("row names contain missing values")
```

**Comment by rcorces** [comment]
Sorry - your code is not a fully reproducible example because of your line:
```
pj1 <- addCellColData(ArchRProj = pj1, data = our_clusters[1:length(pj1$cellNames)], cells=pj1$cellNames, name = "Cluster")
```

If you think about what you are doing, you are creating group coverages on all cells, and then subsetting your project to a random set of 200 cells. Project subsetting (to my knowledge) does not subset the group coverages files and you should probably re-run `addGroupCoverages()` again on the subset. I think your error may be related to this.

Its also worth noting that this:
```
pj1 <- subsetArchRProject(
  ArchRProj = pj1,
  cells = sample(pj1$cellNames, 200),
  outputDirectory = "HemeTutorial1",
  dropCells = TRUE,
  logFile = NULL,
  threads = getArchRThreads(),
    force=TRUE
)
```
Seems very dangerous to me (creating a subset and storing it in the same variable name).
