### ISSUE TITLE
Error occurring when peaks calling using MACS2 

### ISSUE THREAD

**Issue by allenloong** [GreenleafLab/ArchR#714]
**Attach your log file**
[ArchR-addReproduciblePeakSet-8860532587015-Date-2021-04-26_Time-15-58-46.log](https://github.com/GreenleafLab/ArchR/files/6375327/ArchR-addReproduciblePeakSet-8860532587015-Date-2021-04-26_Time-15-58-46.log)

**Describe the bug**
An error occurring when peaks calling using MACS2. I've installed MACS2 using Conda and the path to the executable file for MACS2 was specified. However, an error occurred when I tried to call peaks by using MACS2. I checked the folder and there were files named as '*insertions.bed'.

**Comment by rcorces** [comment]
Related issue: https://github.com/GreenleafLab/ArchR/issues/239#issuecomment-656092828
This is likely some error related to conda. hopefully the solution in the previous issue helps.

**Comment by rcorces** [comment]
Closing. Feel free to comment again here or in #239 if you need additional help.
