### ISSUE TITLE
errors when running addReproduciblePeakSet with MACS2

### ISSUE THREAD

**Issue by elva0328** [GreenleafLab/ArchR#715]
errors when running addReproduciblePeakSet with MACS2, does anyone know how to deal with this problem?

details are whoen as below, and enclosed is the log file.

`> projHeme4 <- addReproduciblePeakSet(
+   ArchRProj = projHeme4, 
+   groupBy = "Clusters2", 
+   pathToMacs2 = pathToMacs2
+ )
ArchR logging to : ArchRLogs/ArchR-addReproduciblePeakSet-1196751c5417b-Date-2021-04-26_Time-18-05-32.log
If there is an issue, please report to github with logFile!
2021-04-26 18:05:32 : Peak Calling Parameters!, 0.004 mins elapsed.
                Group nCells nCellsUsed nReplicates nMin nMax maxPeaks
B                   B    431        425           2  172  253   150000
CD4.M           CD4.M    637        589           2   89  500   150000
CD4.N           CD4.N   1292        544           2   44  500   150000
CLP               CLP    388        388           2   92  296   150000
Erythroid   Erythroid    818        696           2  196  500   150000
GMP               GMP   1142        813           2  313  500   150000
Mono             Mono   2614       1000           2  500  500   150000
NK                 NK    860        784           2  284  500   150000
pDC               pDC    311        302           2  142  160   150000
PreB             PreB    349        349           2   40  309   150000
Progenitor Progenitor   1408        636           2  136  500   150000
2021-04-26 18:05:32 : Batching Peak Calls!, 0.004 mins elapsed.
2021-04-26 18:05:32 : Batch Execution w/ safelapply!, 0 mins elapsed.
Error in (function (..., threads = 1, preschedule = FALSE)  : 
Error Found Iteration 1 : 
	[1] "Error in data.table::fread(summitsFile, select = c(1, 2, 3, 5)) : \n  File '/Users/xyan4/Documents/working/Warapen/ArchR_code/HemeTutorial/PeakCalls/InsertionBeds/B._.scATAC_BMMC_R1-1_summits.bed' does not exist or is non-readable. getwd()=='/Us
	<simpleError in data.table::fread(summitsFile, select = c(1, 2, 3, 5)): File '/Users/xyan4/Documents/working/Warapen/ArchR_code/HemeTutorial/PeakCalls/InsertionBeds/B._.scATAC_BMMC_R1-1_summits.bed' does not exist or is non-readable. getwd()=='/Users
Error Found Iteration 2 : 
	[1] "Error in data.table::fread(summitsFile, select = c(1, 2, 3, 5)) : \n  File '/Users/xyan4/Documents/working/Warapen/ArchR_code/HemeTutorial/PeakCalls/InsertionBeds/B._.scATAC_PBMC_R1-2_summits.bed' does not exist or is non-readable. getwd()=='/Us
	<simpleError in data.table::fread(summitsFile, select = c(1, 2, 3, 5)): File '/Users/xyan4/Documents/working/Warapen/ArchR_code/HemeTutorial/PeakCalls/InsertionBeds/B._.scATAC_PB
In addition: Warning message:
In mclapply(..., mc.cores = threads, mc.preschedule = preschedule) :
  22 function calls resulted in an error
> `

[ArchR-addReproduciblePeakSet-1196751c5417b-Date-2021-04-26_Time-18-05-32.log](https://github.com/GreenleafLab/ArchR/files/6380884/ArchR-addReproduciblePeakSet-1196751c5417b-Date-2021-04-26_Time-18-05-32.log)

**Comment by rcorces** [comment]
related to https://github.com/GreenleafLab/ArchR/issues/239#issuecomment-656092828
Try the solution there. I imagine this is a problem with having MACS2 installed through conda?

**Comment by rcorces** [comment]
Closing but feel free to comment here or at #239 if you need additional help
