### ISSUE TITLE
Subscript out of bounds during constrained integration

### ISSUE THREAD

**Issue by RegnerM2015** [GreenleafLab/ArchR#717]
**Attach your log file**
Please find log file attached. 

**Describe the bug**
2021-04-27 16:20:49 : Block (72 of 76) : Seurat TransferData GeneMatrix, 86.711 mins elapsed.
2021-04-27 16:21:16 : Block (72 of 76) : Saving TransferAnchors Joint CCA, 87.162 mins elapsed.
2021-04-27 16:21:20 : Block (72 of 76) : Transferring Paired RNA to Temp File, 87.226 mins elapsed.
2021-04-27 16:21:56 : Block (72 of 76) : Completed Integration, 87.83 mins elapsed.
Error in .safelapply(seq_along(blockList), function(i) { :
Error Found Iteration 1 :
        [1] "Error in rD[colnames(seuratATAC), , drop = FALSE] : \n  subscript out of bounds\n"
        <simpleError in rD[colnames(seuratATAC), , drop = FALSE]: subscript out of bounds>
Error Found Iteration 2 :
        [1] "Error in rD[colnames(seuratATAC), , drop = FALSE] : \n  subscript out of bounds\n"
        <simpleError in rD[colnames(seuratATAC), , drop = FALSE]: subscript out of bounds>
Error Found Iteration 3 :
        [1] "Error in rD[colnames(seuratATAC), , drop = FALSE] : \n  subscript out of bounds\n"
        <simpleError in rD[colnames(seuratATAC), , drop = FALSE]: subscript out of bounds>
Error Found Iteration 4 :
        [1] "Error in rD[colnames(seuratATAC), , drop = FALSE] : \n  subscript out of bounds\n"
        <simpleError in rD[colnames(seuratATAC), , drop = FALSE]: subscript out of bounds>
Error Found Iteration 6 :
        [1] "Error in rD[colnames(seuratATAC), , drop = FALSE] : \n  subscript out of bounds\n"
        <simpleError in rD[colnames(seuratATAC), , drop = FALSE]: subscript out
Calls: addGeneIntegrationMatrix -> %>% -> Reduce -> .safelapply
In addition: Warning message:
In mclapply(..., mc.cores = threads, mc.preschedule = preschedule) :
  66 function calls resulted in an error

**To Reproduce**
I will attempt to reproduce this with the tutorial dataset.

[ArchR-addGeneIntegrationMatrix-142713276ca37-Date-2021-04-27_Time-14-52-51.log](https://github.com/GreenleafLab/ArchR/files/6387593/ArchR-addGeneIntegrationMatrix-142713276ca37-Date-2021-04-27_Time-14-52-51.log)

**Comment by RegnerM2015** [comment]
From the log File:
An object of class Seurat 
6 features across 126878 samples within 1 assay 
Active assay: RNA (6 features, 0 variable features)
 1 dimensional reduction calculated: umap


This is NOT expected, so I think this may be the source of the issue. When I print the Seurat object by itself:
An object of class Seurat 
28234 features across 126878 samples within 2 assays 
Active assay: RNA (26234 features, 2000 variable features)
 1 other assay present: integrated
 3 dimensional reductions calculated: pca, umap, harmony

**Comment by rcorces** [comment]
Not sure whats going on there.

`rD` is calculated by:
```rD <- getReducedDims(ArchRProj = ArchRProj, reducedDims = reducedDims, corCutOff = corCutOff, dimsToUse = dimsToUse)```

Maybe check that to see what the rownames of `rD` are?

**Comment by RegnerM2015** [comment]
The row names and column names look okay actually:

> rD <- getReducedDims(ArchRProj = proj, reducedDims = "IterativeLSI", corCutOff = 0.75, dimsToUse = 1:50)
> head(colnames(rD))
[1] "LSI1" "LSI2" "LSI3" "LSI4" "LSI5" "LSI6"
> head(rownames(rD))
[1] "HN49758L#CCTTGGTCATAGCAGG-1" "HN49758L#AACTGGTAGAAATTCG-1"
[3] "HN49758L#AACGGGACATGATCGT-1" "HN49758L#CACCTTGTCCATGACA-1"
[5] "HN49758L#TGAGCCGGTCCCTAAA-1" "HN49758L#TTGTTCAGTAGGTCTT-1"

**Comment by rcorces** [comment]
You can try stepping through the code on your end starting here:
https://github.com/GreenleafLab/ArchR/blob/968e4421ce7187a8ac7ea1cf6077412126876d5f/R/RNAIntegration.R#L399
which is eventually used to create `seuratATAC`.

Maybe you subsetted the project and some cells are unexpectedly missing? could be an error with subsetting?

**Comment by RegnerM2015** [comment]
Okay I try this next. 

Also, when I do QC on the initial ArchR project from the Arrow file, should I subset cells using this:

idxPass <- which(projHeme1$TSSEnrichment >= 8)
cellsPass <- projHeme1$cellNames[idxPass]
projHeme1[cellsPass, ]

Or use the function subsetArchRProject?

**Comment by rcorces** [comment]
I would use subsetArchRProject. I should make this more clear in the docs but we haven't pushed a docs update in forever.

**Comment by RegnerM2015** [comment]
Okay, moving forward I will use subsetArchRProject. I guess the only exception to this is using filterDoublets to automate the filtering of the project to remove doublets.

**Comment by rojinsafavi** [comment]
@RegnerM2015  Hello! did you figure out what the problem was? I am facing the same issue during the integration ...
