### ISSUE TITLE
addUMAP

### ISSUE THREAD

**Issue by wuzhigui** [GreenleafLab/ArchR#718]
Yes , this maybe  not an error but  I have no idea that why my Single-cell Embeddings after  `addUMAP` with ` reducedDims = "Harmony"`  seems like no good separation of the very clusters.
![image](https://user-images.githubusercontent.com/70992194/116360275-56060b80-a832-11eb-9a0b-392e83a91d0a.png)

While take a look at my IterativeLSI UMAP before addHarmony , everything seems great !
![image](https://user-images.githubusercontent.com/70992194/116360413-79c95180-a832-11eb-95aa-cbf139cc9d85.png)

So ,what can i do to optimize the UMAP after addHarmony  ?

**Comment by rcorces** [comment]
This is not a bug report or issue with ArchR. Please repost in Discussions. This is clearly described when submitting an issue.
![image](https://user-images.githubusercontent.com/10343046/116428620-ef64fb80-a7f9-11eb-8656-040cb8c8f9d5.png)
