### ISSUE TITLE
addArchRAnnotations error

### ISSUE THREAD

**Issue by strawberry789** [GreenleafLab/ArchR#720]
My command is: `projT1d_Tiles <- addArchRAnnotations(ArchRProj = projT1d_Tiles, collection = "EncodeTFBS")`

The error is: `Error in basename(url) : a character vector argument expected`

Here's my logfile:
[ArchR-addArchRAnnotations-3a18446c3178-Date-2021-04-29_Time-12-08-55.log](https://github.com/GreenleafLab/ArchR/files/6396289/ArchR-addArchRAnnotations-3a18446c3178-Date-2021-04-29_Time-12-08-55.log)

How should I resolve this?

Thank you.

**Comment by rcorces** [comment]
We do not provide any annotation support for non-standard genomes. You will have to create your own annotations.
