### ISSUE TITLE
Error in peakAnnoEnrichment

### ISSUE THREAD

**Issue by strawberry789** [GreenleafLab/ArchR#721]
This is my command after successfully used Macs2 to call peaks:

`enrichMotifs_Macs <- peakAnnoEnrichment(
    seMarker = markersPeaks_Macs2,
    ArchRProj = projT1d,
    peakAnnotation = "Motif",
    cutOff = "FDR <= 0.1 & Log2FC >= 0.5"
  )`

And this is the error:
`Error in getMatches(ArchRProj, peakAnnotation) :
  Name is not in peakAnnotation!`

Here's the log file:
[ArchR-peakAnnoEnrichment-3a18480f208c-Date-2021-04-29_Time-14-29-11.log](https://github.com/GreenleafLab/ArchR/files/6396708/ArchR-peakAnnoEnrichment-3a18480f208c-Date-2021-04-29_Time-14-29-11.log)

**Comment by strawberry789** [comment]
Do I need to apply `addMotifAnnotations` first before `peakAnnoEnrichment` for Motif enrichment in marker peaks as in Motif enrichment in differential peaks?

**Comment by rcorces** [comment]
We have limited bandwidth to address usage questions. Please read the manual in full. If you do not find the information you are looking for, see the function definitions, the paper methods, etc.
