### ISSUE TITLE
Arrow Files have different number of cells between ArchR 0.9.5 and ArchR 1.0.1

### ISSUE THREAD

**Issue by RegnerM2015** [GreenleafLab/ArchR#724]
Hi @rcorces  and @jgranja24 
**Attach your log file**
Please find two log files attached. One for 0.9.5 and one for 1.0.1.

**Describe the bug**
From the same fragments files, ArchR 1.0.1 produces 6 million+ barcodes in the Arrow Files while ArchR 0.9.5 produces only 800k+ barcodes.

ArchR 1.0.1: 
```
proj <- ArchRProject(
  ArrowFiles = ArrowFiles,
  outputDirectory = "All",
  copyArrows = T #This is recommened so that you maintain an unaltered copy for later usage.
 )
saveRDS(proj,"proj_prefilter_barcodes.rds")

proj_prefilter_barcodes <- readRDS("/datastore/nextgenout5/share/labs/francolab/scBreast_Proj/Full_Cohort_ATAC_2021/proj_prefilter_barcodes.rds")
dim(as.data.frame(proj_prefilter_barcodes@cellColData))
[1] 6645966      15
```

ArchR 0.9.5:
```
proj <- ArchRProject(
  ArrowFiles = ArrowFiles,
  outputDirectory = "All",
  copyArrows = T #This is recommened so that you maintain an unaltered copy for later usage.
)
saveRDS(proj@cellColData,"proj_prefilter_barcodes-meta.rds")

proj_prefilter_barcodes-meta <- readRDS("/datastore/nextgenout5/share/labs/francolab/scBreast_Proj/Full_Cohort_ATAC_2021_v0.9.5_GMM/proj_prefilter_barcodes-meta.rds")
dim(as.data.frame(`proj_prefilter_barcodes-meta`))
[1] 818442     15
```

[ArchR-createArrows-799b3c578bfe-Date-2021-04-25_Time-00-54-33.log](https://github.com/GreenleafLab/ArchR/files/6399956/ArchR-createArrows-799b3c578bfe-Date-2021-04-25_Time-00-54-33.log)
[ArchR-createArrows-123ec71cc7bc5-Date-2021-04-28_Time-16-10-26.log](https://github.com/GreenleafLab/ArchR/files/6399960/ArchR-createArrows-123ec71cc7bc5-Date-2021-04-28_Time-16-10-26.log)

**Comment by RegnerM2015** [comment]
Ah, it seems the following parameters made the difference between versions:

**Comment by rcorces** [comment]
yep - the handling of params and their defaults changed
