### ISSUE TITLE
addGeneIntegrationMatrix: Error in h5read(ArrowFile, paste0(subGroup, "/Info/FeatureDF"))

### ISSUE THREAD

**Issue by RegnerM2015** [GreenleafLab/ArchR#726]
[ArchR-addGeneIntegrationMatrix-136321827a23c-Date-2021-04-29_Time-21-26-02.log](https://github.com/GreenleafLab/ArchR/files/6402537/ArchR-addGeneIntegrationMatrix-136321827a23c-Date-2021-04-29_Time-21-26-02.log)
@rcorces and @jgranja24 

**Attach your log file**
The Log file is attached.

**Describe the bug**
It seems the Object 'ArchRGeneScore/Info/FeatureDF' does not exist in the HDF5 file.

```
ArchR logging to : ArchRLogs/ArchR-addGeneIntegrationMatrix-136321827a23c-Date-2021-04-29_Time-21-26-02.log
If there is an issue, please report to github with logFile!
2021-04-29 21:26:03 : Running Seurat's Integration Stuart* et al 2019, 0.026 mins elapsed.
Warning: The following arguments are not used: drop
2021-04-29 21:26:08 : Checking ATAC Input, 0.102 mins elapsed.
2021-04-29 21:26:08 : Checking RNA Input, 0.105 mins elapsed.
Error in h5read(ArrowFile, paste0(subGroup, "/Info/FeatureDF")) :
  Object 'ArchRGeneScore/Info/FeatureDF' does not exist in this HDF5 file.
Calls: addGeneIntegrationMatrix ... .getFeatureDF -> .helpFeatureDF -> DataFrame -> h5read
Execution halted
```
Thanks in advance!

**Comment by rcorces** [comment]
What is the result of `getAvailableMatrices()`? Do you actually have a matrix called "ArchRGeneScore" or is this a mistake and you meant to use "GeneScoreMatrix"?
You'll need to provide more information (always nice if end-users follow our issue template)

**Comment by RegnerM2015** [comment]
That was a mistake, I just misspecified the name of the gene score matrix. 

Thanks for the help!

**Comment by rcorces** [comment]
I feel like this should be caught more explicitly. If you try to run this function on a matrix that doesnt exist, it should give an error that is more intelligible. I've added a check for this via https://github.com/GreenleafLab/ArchR/commit/05d66f20abe6865a330c1409374d4ea33fdecdf5
