### ISSUE TITLE
createArrowFiles Error

### ISSUE THREAD

**Issue by spietrzak** [GreenleafLab/ArchR#727]
Previously, I have used ArchR successfully to analyze fragments.tsv.gz files from cellranger-atac outputs. However, I tried to filter out specific cell barcodes in the fragments files from some of my samples, and re-gunzip the file so that it is in the same format as before, just with specific cells removed. After downloading the fragments files onto my computer and beginning the ArchR run, I see an error in the createArrowFiles step, below:

`ArrowFiles <- createArrowFiles(
+   inputFiles = inputFiles,
+   sampleNames = names(inputFiles),
+   filterTSS = 4,
+   filterFrags = 1000, 
+   addTileMat = TRUE,
+   addGeneScoreMat = TRUE
+ )
Using GeneAnnotation set by addArchRGenome(Mm10)!
Using GeneAnnotation set by addArchRGenome(Mm10)!
ArchR logging to : ArchRLogs/ArchR-createArrows-30fe12b4f75f-Date-2021-04-30_Time-11-49-05.log
If there is an issue, please report to github with logFile!
2021-04-30 11:49:05 : Batch Execution w/ safelapply!, 0 mins elapsed.
2021-04-30 12:12:40 : createArrowFiles has encountered an error, checking if any ArrowFiles completed..
ArchR logging successful to : ArchRLogs/ArchR-createArrows-30fe12b4f75f-Date-2021-04-30_Time-11-49-05.log
Warning message:
In mclapply(..., mc.cores = threads, mc.preschedule = preschedule) :
  11 function calls resulted in an error`

Only the sample that was not affected by filtering out certain steps runs fine. I expanded and opened the fragments tsv files briefly in Excel, and they both appear to be formatted the same, so I'm not sure why it's not recognizing or running these fragments files. I have attached two of these tsv files (the MEF one was unaffected and runs successfully, and the FBS one had cells filtered out and does not run - I only included the first 100 rows so that they weren't too large to attach here). Could you let me know if there is something wrong with the filtered fragments file that is preventing it from running? Any help or advice would be greatly appreciated.
[Archive.zip](https://github.com/GreenleafLab/ArchR/files/6407214/Archive.zip)

**Comment by rcorces** [comment]
despite what the file suffix looks like, fragment files are not gzipped - they a bgzipped and tabix index.
https://support.10xgenomics.com/single-cell-atac/software/pipelines/latest/output/fragments
This is likely your issue.

**Comment by spietrzak** [comment]
That's strange, because I have also previously downsampled some fragments files and re-gunzipped them using the gzip command, and they ran successfully, but I can try bgzip instead. Do you know if there's an easy way to change them to this format or the command to convert tsv to bgzip files

**Comment by rcorces** [comment]
>  I have also previously downsampled some fragments files and re-gunzipped them using the gzip command, and they ran successfully

I dont think that is possible. As far as I know, tabix can only index bgzipped files. You can find information on how to use these tools at htslib:

http://www.htslib.org/doc/bgzip.html
http://www.htslib.org/doc/tabix.html

**Comment by rcorces** [comment]
Closing for now. If this has not solved your problem, feel free to post again in this issue and I will re-open.
