### ISSUE TITLE
Problem with 10x Multiome

### ISSUE THREAD

**Issue by Ping-lin14** [GreenleafLab/ArchR#730]
Hi

I'm following https://greenleaflab.github.io/ArchR_2020/Ex-Analyze-Multiome.html to try to multiome analysis.
However, I found some problems.
1, The `inputFiles <- getInputFiles("pbmc_10k")[1]` function cannot get the demonstration data.
2, Due to question 1, I started from the 10x website (https://www.10xgenomics.com/resources/datasets/pbmc-from-a-healthy-donor-granulocytes-removed-through-cell-sorting-10-k- 1.0.0) download the filtered feature barcode matrix  (HDF5) and ATAC per fragment information file(TSV.GZ). However, I received an error message when adding scRNA data to ArchRProject. The error is `No overlap found with scATAC!`

I am sure that the input data is from the same sample, and the demonstration data cannot be obtained, so I have no idea about this error.

**Comment by rcorces** [comment]
I'm not sure I can help without more information. Can you provide more information on what files you downloaded, where you put them, and show the code you are using.

You should create a directory called "pbmc_10k" which has your fragment file and filtered feature barcode matrix HDF file downloaded from 10x. This directory shouldnt have anything else in it.

**Comment by Ping-lin14** [comment]
First , the `inputFiles <- getInputFiles("pbmc_10k")[1]`  can indeed produce `inputFiles`.
But the content of inputFiles is displayed as NA, and no directory named `pbmc 10x` is created on my path.

[Here](https://drive.google.com/drive/folders/1qfQcQTCP-RKf54bLtUPj843dnp9gH2KA?usp=sharing
) is the 10x file I used.

code:
```
library(ArchR)

addArchRGenome("hg38")
addArchRThreads(threads = 20)

setwd("/home/pinglin/Multione/")

inputFiles <- getInputFiles("pbmc_10k")[1]
#inputFiles is displayed as NA

################################################################################
setwd("/home/pinglin/Multione/test/")
pbmc_atac <- "pbmc_granulocyte_sorted_10k_atac_fragments.tsv.gz"
ArrowFiles <- createArrowFiles(pbmc_atac, sampleNames = pbmc_atac, force = TRUE)
proj <- ArchRProject(ArrowFiles)

seRNA <- import10xFeatureMatrix(
  input = "pbmc_granulocyte_sorted_10k_filtered_feature_bc_matrix.h5",
  names = "pbmc_rna"
)

proj <- addGeneExpressionMatrix(input = proj, seRNA = seRNA, force = TRUE)
#No overlap found with scATAC!
```

**Comment by rcorces** [comment]
I've added additional instructions at the top of the multiome tutorial. Please follow these instructions.
https://greenleaflab.github.io/ArchR_2020/Ex-Analyze-Multiome.html

If this does not work for you, feel free to comment again here but I have validated that this works in my hands so I am closing this issue.

**Comment by Ping-lin14** [comment]
Hi
thank you very much for your help.
The question about the demonstration data has been resolved.
However, I still get the error message `No overlap found with scATAC!` when add scRNA data.

**Comment by rcorces** [comment]
I dont think this is possible if you follow the instructions that I provided exactly. If you would like further help, please show:
1. Exactly what files you downloaded - give me the md5sums
2. The directory structure of your working directory and the pbmc_10k subdirectory
3. The exact commands that you are using
4. The full error message
5. The log file
