### ISSUE TITLE
getGroupBW error

### ISSUE THREAD

**Issue by rojinsafavi** [GreenleafLab/ArchR#741]
when I run :
```getGroupBW(proj_s, groupBy = 'Sample', normMethod = "None",tileSize = 100)```

sometimes I get the following. It's weird since I put tileSize =100

```chr2	60382600	60382800	1```

**Comment by rcorces** [comment]
Can you create a reproducible example using the tutorial data?

**Comment by rojinsafavi** [comment]
I used the multiomics PBMC data, I'll try do it with the ArchR example as well

**Comment by rojinsafavi** [comment]
The result is the same, I read deeptools threads and it seems this is not an issue, it has to do with reducing the storage space
