### ISSUE TITLE
heatmap of the variable deviation scores of TF motifs 

### ISSUE THREAD

**Issue by wilfridricher** [GreenleafLab/ArchR#744]
Hello ArchR team,

We tried to produce a heatmap of the variable deviation scores of TF motifs obtained from ChromVAR Deviations Enrichment, but we faced some problems.

We have followed the following steps:

1. getMarkerFeatures() with the option useSeqnames="z" because MotifMatrix is a Sparse.Assays.Matrix  (as mention in the 13.1 section of the tutorial).

slct.res="res0.9"
markersMM.slctRes <- getMarkerFeatures(
ArchRProj = peakCalls_ it10_f5k_2x3, 
useMatrix = "MotifMatrix", 
groupBy = paste("Clusters",slct.res,sep="."),
bias = c("TSSEnrichment", "log10(nFrags)"),
useSeqnames="z",
testMethod = "wilcoxon")

2. markerHeatmap() to produce the heatmap.

heatmapGSmatrix <- plotMarkerHeatmap(
seMarker = markersMM.slctRes, 
#cutOff = "FDR <= 0.05 & Log2FC >= 0.2", 
#labelMarkers = markerGenes,
returnMatrix = FALSE,
transpose = FALSE)

At this moment, we obtained this message:

ArchR logging to: ArchRLogs/ArchR-getMarkerFeatures-2d0d9401a4a7d-Date-2021-04-20_Time-12-30-38.log
If there is an issue, please report to github with logFile!
2021-04-20 12:30:38 : Matching Known Biases, 0.001 mins elapsed.
###########
2021-04-20 12:30:50 : Completed Pairwise Tests, 0.203 mins elapsed.
###########
ArchR logging successful to : ArchRLogs/ArchR-getMarkerFeatures-2d0d9401a4a7d-Date-2021-04-20_Time-12-30-38.log

(The same happened when we used useSeqnames="deviations")

Please find the log files here.

Thank you very much for your help! 
We are fan of your tool! 

[ArchR-getMarkerFeatures-3b9023b721dc9-Date-2021-05-10_Time-12-02-11.log](https://github.com/GreenleafLab/ArchR/files/6453644/ArchR-getMarkerFeatures-3b9023b721dc9-Date-2021-05-10_Time-12-02-11.log)
[ArchR-plotMarkerHeatmap-3b9021cc5c29e-Date-2021-05-10_Time-12-02-27.log](https://github.com/GreenleafLab/ArchR/files/6453646/ArchR-plotMarkerHeatmap-3b9021cc5c29e-Date-2021-05-10_Time-12-02-27.log)

**Comment by rcorces** [comment]
Sorry - I'm not seeing an error here. Am I missing something?
The code you showed is not sufficient to produce a plot. you need to actually print the plot (for ex. using complex heatmap). see the manual - 
https://www.archrproject.com/bookdown/identifying-marker-genes.html

**Comment by wilfridricher** [comment]
Sorry, I forgot to write the error message following the function plotMarkerHeatmap(). And due to this error, I can't print the plot using the function Complexheatmap:draw().

Please find the error message:
> heatmapGSmatrix <- plotMarkerHeatmap(
+     seMarker = markersMM.slctRes, 
+     #  cutOff = "FDR <= 0.05 & Log2FC >= 0.2", 
+     #  labelMarkers = markerGenes,
+     returnMatrix = FALSE,
+     transpose = FALSE
+ )
ArchR logging to : ArchRLogs/ArchR-plotMarkerHeatmap-3ff622ccf9ca-Date-2021-05-11_Time-09-52-39.log
If there is an issue, please report to github with logFile!
Error in bS[[1]][, colnames(mat), drop = FALSE] : indice hors limites
De plus : Warning message:
In plotMarkerHeatmap(seMarker = markersMM.slctRes, returnMatrix = FALSE,  :
  production de NaN

(the logs are for the both functions)

**Comment by rcorces** [comment]
Are you able to reproduce this error using the tutorial data?

**Comment by wilfridricher** [comment]
Hello,
I used the same commands on the tutorial data.
I successed to produce this heatmap. I obtained the same warning message, but without the error message as you can see below:

heatmapMMmatrix <- plotMarkerHeatmap(
     seMarker = markersMM.slctRes, 
     returnMatrix = FALSE,
     transpose = FALSE
 )
ArchR logging to : ArchRLogs/ArchR-plotMarkerHeatmap-599fa5cc4fa7e-Date-2021-05-12_Time-15-48-56.log
If there is an issue, please report to github with logFile!
Identified 14 markers!
 [1] "MNT_20"     "HES5_98"    "ZNF740_209" "ZNF148_222" "ZBTB7C_265" "LIN54_297"  "PAX6_604"   "IRF5_631"   "IRF8_633"  
[10] "IRF2_634"   "IRF9_636"   "TBX5_781"   "TBX4_784"   "TBX20_790" 
Preparing Main Heatmap..
ArchR logging successful to : ArchRLogs/ArchR-plotMarkerHeatmap-599fa5cc4fa7e-Date-2021-05-12_Time-15-48-56.log
Warning message:
In plotMarkerHeatmap(seMarker = markersMM.slctRes, returnMatrix = FALSE,  :
  production de NaN

[MotifMatrix-Heatmap.res0.8.pdf](https://github.com/GreenleafLab/ArchR/files/6466570/MotifMatrix-Heatmap.res0.8.pdf)
[ArchR-plotMarkerHeatmap-599fa5cc4fa7e-Date-2021-05-12_Time-15-48-56.log](https://github.com/GreenleafLab/ArchR/files/6466571/ArchR-plotMarkerHeatmap-599fa5cc4fa7e-Date-2021-05-12_Time-15-48-56.log)
[ArchR-getMarkerFeatures-599facc30d46-Date-2021-05-12_Time-15-40-28.log](https://github.com/GreenleafLab/ArchR/files/6466572/ArchR-getMarkerFeatures-599facc30d46-Date-2021-05-12_Time-15-40-28.log)

**Comment by rcorces** [comment]
maybe something related to subsetting your project?

**Comment by wilfridricher** [comment]
I  haven't done some subsets of my project yet. :/

**Comment by rcorces** [comment]
what does this show for your data and for the tutorial data:
`as.matrix(SummarizedExperiment::assays(seMarker)[["Mean"]])`
where `seMarker` is "markersMM.slctRes" in your code

**Comment by wilfridricher** [comment]
please find the produced matrix in attachment (they are tsv files).
[tutorial.data.csv](https://github.com/GreenleafLab/ArchR/files/6467092/tutorial.data.csv)
[my.data.csv](https://github.com/GreenleafLab/ArchR/files/6467093/my.data.csv)

**Comment by rcorces** [comment]
I think your use of the function and the parameters is incorrect. Some of the default parameters are not appropriate for deviations etc (for ex. `log2norm`). Its hard for me to dissect your exact problem but this is not a bug in ArchR as far as I can tell. Please read the function documentation and make sure that you have elements in seMarker that actually pass the cutoffs you are setting.
