### ISSUE TITLE
addGeneIntegrationMatrix error 

### ISSUE THREAD

**Issue by Dragonlongzhilin** [GreenleafLab/ArchR#746]
In scRNA, I used the harmony to integrate 4 sample data.
The code is:
![image](https://user-images.githubusercontent.com/33304280/117986553-4f1be480-b36c-11eb-81ad-f6e3ec5bb906.png)
![image](https://user-images.githubusercontent.com/33304280/117986633-622eb480-b36c-11eb-90af-1ff71d881da3.png)
But when I annotated the scATAC data using this scRNA data, there was a error:
![image](https://user-images.githubusercontent.com/33304280/117986906-9f934200-b36c-11eb-92fd-712d072cabe5.png)
This variableFeatures exists and DefaultAssay is SCT (note: The scRNA variable is the same as data.merge ):
![image](https://user-images.githubusercontent.com/33304280/117987955-876ff280-b36d-11eb-911f-b71b8265a3d7.png)

The package version is:
![image](https://user-images.githubusercontent.com/33304280/117989221-b76bc580-b36e-11eb-883f-4c9c4597af4c.png)

**Comment by rcorces** [comment]
In the future, please dont paste screenshots. Paste the actual text using markdown codeblock syntax "```"
I dont know the answer to this but its clear that what you are providing ArchR is outside of the limits of what is expected. Presumably `Seurat::FindVariableFeatures` is failing on your RNA object here:
https://github.com/GreenleafLab/ArchR/blob/968e4421ce7187a8ac7ea1cf6077412126876d5f/R/RNAIntegration.R#L389

Maybe you need to change what you are passing to `nGenes`

**Comment by Dragonlongzhilin** [comment]
I am sorry for my irregular operation.
Indeed as you said,
`> Seurat::FindVariableFeatures(seRNA)
Error: SCT assay is comprised of multiple SCT models. To change the variable features, please set manually with VariableFeatures<-
`
If this is the case, does ArchR not apply standardized scRNA data using SCTranform?
Only applicable to the old seurat standardization process:NormalizeData，FindVariableFeatures， ScaleData

**Comment by rcorces** [comment]
Sorry - I havent kept up with changes to Seurat so I'm not sure how to answer this. If you want to step through the code and propose a solution on how to get ArchR to work with the newer Seurat standards, I'm happy to try to implement that.

**Comment by Dragonlongzhilin** [comment]
I only thought of a simple way to deal with it.
I noticed the original code of the addGeneIntegrationMatrix function：
`    .logDiffTime(sprintf("%s Identifying Variable Genes", prefix), tstart, verbose = verbose, logFile = logFile)
    subRNA <- FindVariableFeatures(object = subRNA, nfeatures = nGenes, verbose = FALSE)
    subRNA <- ScaleData(object = subRNA, verbose = FALSE)
    if(is.null(genesUse)){
      genesUse <- VariableFeatures(object = subRNA)
    }`
We only need to add a defaultAssay judgment option about seRNA.
`if(DefaultAssay(seRNA)=="SCT"){
genesUse  <- VariableFeatures(seRNA)
}`
This is just my simple idea, not sure if it is feasible in actual situation.

**Comment by rcorces** [comment]
Ok. I attempted to implement my interpretation of the correct fix in https://github.com/GreenleafLab/ArchR/commit/ed30ce163d9b9fe7838106cc626323f933ed94e6 (could be wrong). I did this on the `dev_SCTfix` branch. Can you install this via the command below and see if it works for you?

`devtools::install_github("GreenleafLab/ArchR", ref="dev_SCTfix", repos = BiocManager::repositories())

**Comment by Dragonlongzhilin** [comment]
ok, thanks, I will try it.

**Comment by Dragonlongzhilin** [comment]
ok, thanks, I will try it.

**Comment by rcorces** [comment]
@Dragonlongzhilin - Did this fix your issue? If so, I would like to merge the change into the primary dev branch so that it is propagated forward.

**Comment by rcorces** [comment]
@Dragonlongzhilin - please let us know if this fixed your issue.

**Comment by Dragonlongzhilin** [comment]
Sorry for taking so long to reply to you! The seurat team currently does not recommend the use of SCT assay to integrate scRNA-seq and scATAC-seq, So my suggestion is not appropriate at the moment.
Thank you for your kind help!

**Comment by rcorces** [comment]
Thanks for letting us know. I've deleted the `dev_SCTfix` branch in that case. Closing this issue for now.
