### ISSUE TITLE
Motif Enrichment analysis yielding Pvalue of 0 and Enrichment of NaN

### ISSUE THREAD

**Issue by Arinze-BioX** [GreenleafLab/ArchR#755]
Hello,
I am trying to use ArchR in analysing a small subcluster of cells that I have sampled from a larger cluster. This new set of clusters contain fewer than normal cells (between 90 and 500 cells in each cluster). All the cells have been drawn from 9 samples and some samples are not represented in some clusters (that is, there are clusters that contain no cells from certain samples). Thus, in running the addRproduciblePeakset function, I specify not to be sample-aware. 
Now I am trying to perform motif enrichment analysis to identify TFs whose otifs are enriched in each cluster. To do this, I tried both the Cisbp and the JASPAR2020 databases. However, in both cases, I get a summarized experiment as output from the peakAnnoEnrichment function with a list of TFs (I think) but the Assays columns are either all zeros (PVal, mlog10Padj) or NaN ("Enrichment"). 
Could you please help me understand what may be the problem and how to get around it?

**Comment by Arinze-BioX** [comment]
Funny, just after posting this, I realized what may be the problem and confirmed it. The problem was there were no peaks for the particular group of interest that meet the cutoffs. But I am still surprised I got any TFs at all from the enrichment analysis.

**Comment by rcorces** [comment]
Please note that Issues are reserved for Bug reports. Questions and feature request should be posted to Discussions.
