### ISSUE TITLE
Error in plotMarkerHeatmap

### ISSUE THREAD

**Issue by MaryGoAround** [GreenleafLab/ArchR#761]
Hello

I am trying to plot peaks called by macs2 but likely in the rownames of markersPeaks there is no gene name to plot and all are number

```
heatmapPeaks <- plotMarkerHeatmap(
  seMarker = markersPeaks, labelMarkers = rownames(markersPeaks),
  cutOff = "FDR <= 0.1 & Log2FC >= 0.5",
  transpose = TRUE
)
```
`[ArchR-plotMarkerHeatmap-736c57d5033a-Date-2021-05-17_Time-12-41-55.log](https://github.com/GreenleafLab/ArchR/files/6493575/ArchR-plotMarkerHeatmap-736c57d5033a-Date-2021-05-17_Time-12-41-55.log)`

I have attached my log file please can you have a look

**Comment by rcorces** [comment]
There is no bug here.
