### ISSUE TITLE
Adding multiple collections from JASPAR2020

### ISSUE THREAD

**Issue by jpblich** [GreenleafLab/ArchR#774]
Hi,

When running addMotifAnnotations to an ArchR project, is it possible to add both 'core' and 'unvalidated' collections from JASPAR2020 database? When I run:

Multiproj <- addMotifAnnotations(ArchRProj = Multiproj, motifSet = "JASPAR2020", collection = c("CORE", "UNVALIDATED"), name = "JASPAR", force = TRUE)

I get the error:

ArchR logging to : ArchRLogs/ArchR-addMotifAnnotations-30b51655d47-Date-2021-05-26_Time-08-11-55.log
If there is an issue, please report to github with logFile!
peakAnnotation name already exists! Overriding.
2021-05-26 08:11:55 : Gettting Motif Set, Species : Homo sapiens, 0.001 mins elapsed.
Error in match.arg(opts[["collection"]], c("CORE", "CNE", "PHYLOFACTS",  : 
  'arg' must be of length 1

The unvalidated collection contains many useful motifs that are not present in the core collection (or in the CISBP database).
Would be very grateful for any help.
Many thanks,
J

**Comment by rcorces** [comment]
Have you read through the function parameters?
https://www.archrproject.com/reference/addMotifAnnotations.html

`collection` points you to the documentation for `getMotifSet()` from `TFBSTools` which states that the argument should be a character vector of length 1.
https://www.rdocumentation.org/packages/TFBSTools/versions/1.10.3/topics/getMatrixSet

**Comment by jpblich** [comment]
Hi,

Thanks for your answer. I have read the function parameters and the documentation for geMatrixSet() and I understand that the error "'arg' must be of length 1" is expected if I try to add multiple collections in the way I illustrated. 

My question is whether there might be a workaround for this, or if not, whether adding multiple JASPAR collections is a feature that could be implemented in ArchR?

I've been able to add both core and unvalidated JASPAR2020 sets using the following code:

pwm_set1 <- getMatrixSet(x = JASPAR2020, opts = list(all_versions = FALSE, collection="CORE", matrixtype="PWM"))
pwm_set2 <- getMatrixSet(x = JASPAR2020, opts = list(all_versions = FALSE, collection="UNVALIDATED", matrixtype="PWM"))
pwm_set <- c(pwm_set1, pwm_set2)
Multiproj_DAY10 <- addMotifAnnotations(ArchRProj = Multiproj_DAY10, motifPWMs = pwm_set, name = "JASPAR", force = TRUE)

This works, but it results in all motifs having JASPAR motif IDs. This means that some of the functionality in ArchR doesn't work, as Motif IDs (which take the form MAxxxx.V) cannot be linked to gene names, and so ArhchR's integrative gene expression/motif analysis features don't work.

For example, when I run:

Multiproj_DAY10 <- addBgdPeaks(Multiproj_DAY10, force = TRUE)
Multiproj_DAY10 <- addDeviationsMatrix(
  ArchRProj = Multiproj_DAY10, 
  peakAnnotation = "JASPAR",
  force = TRUE)
Day_10.corGEM_MM <- correlateMatrices(
  ArchRProj = Multiproj_DAY10,
  useMatrix1 = "GeneExpressionMatrix",
  useMatrix2 = "JASPARMatrix",
  reducedDims = "LSI_Combined")

I get this error:

ArchR logging to : ArchRLogs/ArchR-correlateMatrices-30b20eb83fb-Date-2021-05-26_Time-07-59-52.log
If there is an issue, please report to github with logFile!
Error: Matching of useMatrix1 and useMatrix2 resulted in no mappings!

Adding motif annotations using the ArchR function as below results in motifs IDs that include gene names and thus can be linked to gene expression, however this only allows addition of one collection.

Multiproj <- addMotifAnnotations(ArchRProj = Multiproj, motifSet = "JASPAR2020", collection = "CORE", name = "JASPAR", force = TRUE)

Inability to add both core and unvalidated collections is a major stumbling block for me as some motifs I need are only present in the unvalidated JASPAR database.
If you can see any way to get round this I'd be very grateful.
Many thanks again,
J

**Comment by rcorces** [comment]
Maybe I'm mis-interpreting what you want to do. You can add as many motif annotations as you want but you must add them one at a time and give them different names. Of course, if your motif annotation doesnt contain the information required to match gene names, then you wont be able to do that. But, in theory, you could manually curate whatever motif annotation you want and pass it to `motifPWMs`. We view this as the "flexible" approach, enabling users to do whatever they want with motifs since it is beyond the scope of what we can manage to enable every desired application.

**Comment by jpblich** [comment]
My aim is to add both core and unvalidated JASPAR collections in a single Motif matrix, allowing integrative gene expression/motif analyses on both motifs sets together. In the end I was able to do this by concatenating both collections, converting JASPAR motif IDs to gene names, then adding as a custom motif annotation. This is the code I used in case anyone wants to do this in the future:

# Get a list of motif position frequency matrices from the JASPAR database
pwm_set1 <- getMatrixSet(x = JASPAR2020, opts = list(all_versions = FALSE, species = 9606, collection="CORE", matrixtype="PWM"))
pwm_set2 <- getMatrixSet(x = JASPAR2020, opts = list(all_versions = FALSE, species = 9606, collection="UNVALIDATED", matrixtype="PWM"))
pwm_set <- c(pwm_set1, pwm_set2)

names(pwm_set) <- name(pwm_set) #converts Motif IDs to gene names
pwm_set[duplicated(names(pwm_set)),] #identifies duplicates
names(pwm_set) <- make.unique(names(pwm_set)) #adds a unique suffix onto end of duplicates

Proj <- addMotifAnnotations(ArchRProj = Proj, motifPWMs = pwm_set, name = "JASPAR", force = TRUE)
Proj <- addDeviationsMatrix(ArchRProj = Proj, peakAnnotation = "JASPAR", force = TRUE)


Thanks for your help,
JP
