### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by agalianese** [GreenleafLab/ArchR#791]
<img width="865" alt="Screen Shot 2021-06-01 at 11 39 45 AM" src="https://user-images.githubusercontent.com/55033537/120351694-12d60700-c2ce-11eb-94ad-000218c6201a.png">

There's a type in Greenleaf in Chapter 13: ChromVAR Deviatons Enrichment with ArchR in the full manual.

**Comment by rcorces** [comment]
thanks
