### ISSUE TITLE
No "force" argument for projectBulkATAC

### ISSUE THREAD

**Issue by Zepeng-Mu** [GreenleafLab/ArchR#796]
Hello,
I'm trying to run the `projectBulkATAC ` function but got this error:

```
ArchR logging to : ArchRLogs/ArchR-projectBulkATAC-c7db40ab3d52-Date-2021-06-02_Time-19-42-47.log
If there is an issue, please report to github with logFile!
Error in if (force) { : argument is not interpretable as logical
```
It seems that there is a parameter force determining whether to force projection when the overlap is low between two data. But this `force` option is not defined anywhere else in the function.
https://github.com/GreenleafLab/ArchR/blob/968e4421ce7187a8ac7ea1cf6077412126876d5f/R/BulkProjection.R#L64
There seems no way to bypass this in the function run, so I cannot get the function running.
Thanks

**Comment by rcorces** [comment]
Thanks for reporting. I've added the force parameter to the function in the `release_1.0.2` branch via https://github.com/GreenleafLab/ArchR/commit/d4dd9aef9483febcf6758b311aff58a36f3bf541

Closing but feel free to comment here if this hasnt fixed the issue.
