### ISSUE TITLE
Heatmap for marker peaks and marker genes doesnt render

### ISSUE THREAD

**Issue by lsundaram** [GreenleafLab/ArchR#81]
Code :

markersPeaks <- markerFeatures(ArchRProj = proj, useMatrix = "PeakMatrix", groupBy = "Clusters")

#Visualize Markers as a heatmap
heatmapPeaks <- markerHeatmap(
  seMarker = markersPeaks, 
  cutOff = "FDR <= 0.1 & Log2FC >= 1"
)
plotPDF(heatmapPeaks, name = "Peak-Marker-Heatmap", width = 8, height = 12, ArchRProj = proj, addDOC = FALSE)

Error :
************************************************************
2020-04-22 15:54:46 : ERROR Found in .ArchRHeatmap for  
LogFile = ArchRLogs/ArchR-plotMarkerHeatmap-b7c95bbc52b7-Date-2020-04-22_Time-15-54-42.log

<simpleError in .logError(e, fn = ".ArchRHeatmap", info = "", errorList = errorList,     logFile = logFile): object 'e' not found>

************************************************************

Error in .logError(e, fn = ".ArchRHeatmap", info = "", errorList = errorList, : Exiting See Error Above
Traceback:

1. markerHeatmap(seMarker = markersPeaks, cutOff = "FDR <= 0.1 & Log2FC >= 1")
2. plotMarkerHeatmap(...)
3. tryCatch({
 .     .ArchRHeatmap(mat = mat, scale = FALSE, limits = c(min(mat), 
 .         max(mat)), color = pal, clusterCols = clusterCols, clusterRows = clusterRows, 
 .         labelRows = labelRows, labelCols = TRUE, customRowLabel = mn, 
 .         showColDendrogram = TRUE, draw = FALSE, name = paste0("Row Z-Scores\n", 
 .             nrow(mat), " features\n", metadata(seMarker)$Params$useMatrix))
 .     .logError(e, fn = ".ArchRHeatmap", info = "", errorList = errorList, 
 .         logFile = logFile)
 . }, error = function(e) {
 .     errorList <- list(mat = mat, scale = FALSE, limits = c(min(mat), 
 .         max(mat)), color = pal, clusterCols = clusterCols, clusterRows = clusterRows, 
 .         labelRows = labelRows, labelCols = TRUE, customRowLabel = mn, 
 .         showColDendrogram = TRUE, draw = FALSE, name = paste0("Row Z-Scores\n", 
 .             nrow(mat), " features\n", metadata(seMarker)$Params$useMatrix))
 .     .logError(e, fn = ".ArchRHeatmap", info = "", errorList = errorList, 
 .         logFile = logFile)
 . })
4. tryCatchList(expr, classes, parentenv, handlers)
5. tryCatchOne(expr, names, parentenv, handlers[[1L]])
6. value[[3L]](cond)
7. .logError(e, fn = ".ArchRHeatmap", info = "", errorList = errorList, 
 .     logFile = logFile)
8. stop("Exiting See Error Above")

**Comment by jgranja24** [comment]
this should now be fixed as it was a copy paste .logError thanks!
