### ISSUE TITLE
Error in created ArrowFile 

### ISSUE THREAD

**Issue by sneddonucsf** [GreenleafLab/ArchR#810]
[ArchR-createArrows-677d6113dd6b-Date-2021-06-07_Time-11-43-57.log](https://github.com/GreenleafLab/ArchR/files/6611410/ArchR-createArrows-677d6113dd6b-Date-2021-06-07_Time-11-43-57.log)

I encounter the error:
<simpleError in o__[f__]: only 0's may be mixed with negative subscripts>

when trying to create an ArrowFile with the following command: 
inputFiles = directory_to_fragment_files
ArrowFiles <- createArrowFiles(
  inputFiles = inputFiles,
  sampleNames = "10wpc_Epcam_1",
  filterTSS = 4, #Dont set this too high because you can always increase later
  filterFrags = 1000, 
  addTileMat = TRUE,
  addGeneScoreMat = TRUE
)

I do not get this error when creating the Arrow Files with the tutorial dataset, so I'm assuming it must be something with my input files? Any idea based off of the log what might be going wrong?

**Comment by rcorces** [comment]
nothing pops out at me. Can you try with more threads?

**Comment by sneddonucsf** [comment]
Unfortunately whenever I try it with more threads it crashes my R studio session, even though I have 64GB of RAM. I've tried with both 4 and 8 threads, and it crashed for both. Not sure what's going on. This is even with an empty R environment and plenty of memory to spare (according to Activity Monitor on my Mac)

**Comment by rcorces** [comment]
does the tutorial crash from Rstudio with multiple threads? If so, that sounds a little funky. If the tutorial runs fine and your own data doesnt, that sounds like an input problem. Was the fragments file generated by cellranger?

**Comment by sneddonucsf** [comment]
No, I was able to run through the Tutorial with 8 threads just fine. Correct, the fragments file was generated by CellRanger, seemed to look okay on the Web Summary

**Comment by rcorces** [comment]
Out of curiosity, when you say it crashes your Rstudio session, what does that mean? Often times, parallel operations in Rstudio fail to produce output and it can look like the program is hanging but the tmp folders are being populated with arrow file data.

**Comment by sneddonucsf** [comment]
I get this when R crashes:
<img width="536" alt="CZsnH" src="https://user-images.githubusercontent.com/12053091/121231283-14ab4780-c845-11eb-9343-f71e08295bf7.png">

A collaborator was able to create ArrowFiles with the same 10x input, so I am suspecting that something is wrong with my R Studio. I'll uninstall ArchR/dependencies and try again with a fresh re-install

**Comment by rcorces** [comment]
Yes - sounds like an environment-specific problem. Closing for now.
