### ISSUE TITLE
Errors in using getMarkerFeatures

### ISSUE THREAD

**Issue by beckybeckybecky** [GreenleafLab/ArchR#814]
2021-06-09 14:45:06 : Matching Known Biases, 0.014 mins elapsed.
Error in cor(estbgdP, obsbgdP) : incompatible dimensions
In addition: Warning messages:
1: In rbind(estbgd, obsbgd) :
  number of columns of result is not a multiple of vector length (arg 1)
2: In rbind(estbgdP, obsbgdP) :
  number of columns of result is not a multiple of vector length (arg 1)

**Comment by rcorces** [comment]
Sorry but this is not a proper bug report. We provide a very detailed template which shows up when you open a new issue. Please use it if you would like help.
