### ISSUE TITLE
Issue with running Estimated LSI

### ISSUE THREAD

**Issue by SaraD08** [GreenleafLab/ArchR#816]
Hi, I am just getting up and running with the ArchR tutorial and hematopoiesis dataset. I am hitting a missing log file issue similar to another issue found here but I have not been able to resolve it. I have a recent version of ArchR that I downloaded and installed within the last few weeks:
I ran the following to test out the Estimated LSI workflow.

projHeme2 <- addIterativeLSI(
    ArchRProj = projHeme2,
    useMatrix = "TileMatrix", 
    name = "EstimatedLSI", 
    iterations = 2, 
    clusterParams = list( #See Seurat::FindClusters
        resolution = c(0.2), 
        sampleCells = 10000, 
        n.start = 10
    ), 
    varFeatures = 25000, 
    dimsToUse = 1:30,
    sampleCellsFinal = 5000,
    projectCellsPre = TRUE
)

**Here is my error:**

2021-06-10 18:28:14 : ERROR Found in .LSIPartialMatrix for  
LogFile = ArchRLogs/ArchR-addIterativeLSI-19f641e6e1b0-Date-2021-06-10_Time-18-27-48.log

<simpleError in .logThis(sampledCellNames, "cellNames supplied", logFile = logFile): object 'logFile' not found>

************************************************************

Error in .logError(e, fn = ".LSIPartialMatrix", info = "", errorList = errorList,  : 
  Exiting See Error Above
[ArchR-addIterativeLSI-19f641e6e1b0-Date-2021-06-10_Time-18-27-48.log](https://github.com/GreenleafLab/ArchR/files/6633670/ArchR-addIterativeLSI-19f641e6e1b0-Date-2021-06-10_Time-18-27-48.log)

I have tried different sampleCellFinal values without any luck. Thank you in advance for your time and help with this issue.

**Comment by rcorces** [comment]
This was fixed a few months back via https://github.com/GreenleafLab/ArchR/commit/bcd72a20f2b2dd0fc800a77966c59f3fb623332c

Please install the current development version `release_1.0.2`

```devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.2", repos = BiocManager::repositories())```
