### ISSUE TITLE
15.4 Identification of Positive TF-Regulators

### ISSUE THREAD

**Issue by NinaJiangL** [GreenleafLab/ArchR#823]
Hi, I got an error after trying to identify Deviant TF motif using tutorial data 

code : seGroupMotif <- getGroupSE(ArchRProj = projHeme5, useMatrix = "MotifMatrix", groupBy = "Clusters2")

error : > seGroupMotif <- getGroupSE(ArchRProj = projHeme5, useMatrix = "MotifMatrix", groupBy = "Clusters2")
ArchR logging to : ArchRLogs\ArchR-getGroupSE-669a460fd4e4f-Date-2021-06-16_Time-21-35-06.log
If there is an issue, please report to github with logFile!
Error in h5read(ArrowFile, paste0(subGroup, "/Info/FeatureDF")) : 
  Object 'MotifMatrix/Info/FeatureDF' does not exist in this HDF5 file.

**Comment by rcorces** [comment]
Hard to provide much help without more information and your log file. When you open a new issue, a template is provided for you and we would appreciate it if users followed those template instructions.

Perhaps you skipped other prior steps, in particular `addDeviationsMatrix()`?
What happens when you type `getAvailableMatrices(projHeme5)`

**Comment by dandata123-tech** [comment]
my data shows there is no  correlationship between  MotifMatrix and GenesoreMatrix ,Is that ok ? or I miss something

**Comment by rcorces** [comment]
@dandata123-tech - please do not tack on unrelated questions to existing issues/discussion topics.

**Comment by dandata123-tech** [comment]
I supposed it is related .Sorry&nbsp;



发自我的iPhone


------------------ Original ------------------
From: Ryan Corces ***@***.***&gt;
Date: Sun,Jun 27,2021 9:21 PM
To: GreenleafLab/ArchR ***@***.***&gt;
Cc: Dan ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [GreenleafLab/ArchR] 15.4 Identification of Positive TF-Regulators (#823)





 
Closed #823.
