### ISSUE TITLE
addGeneIntegrationMatrix error

### ISSUE THREAD

**Issue by Dazcam** [GreenleafLab/ArchR#824]
I'm getting the following error when running the `addGeneIntegrationMatrix()` function:

```
<simpleError: Please set k.score to be smaller than the number of cells in query (593) and reference (27) objects.>
Error in .retryCatch({ : 
In addition: Warning messages:
1: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  pseudoinverse used at -1.4475
2: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  neighborhood radius 0.49324
3: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  reciprocal condition number  9.3475e-15
4: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  There are other near singularities as well. 0.090619
```

Here is my code:

```
fc.archR.3 <- addGeneIntegrationMatrix(
  ArchRProj = fc.archR.3, 
  useMatrix = "GeneScoreMatrix",
  matrixName = "GeneIntegrationMatrix",
  reducedDims = "IterativeLSI",
  seRNA = seurat.fc,
  addToArrow = FALSE, 
  groupList = groupList,
  groupRNA = "cellIDs",
  nameCell = "predictedCell_Co",
  nameGroup = "predictedGroup_Co",
  nameScore = "predictedScore_Co",
  dimsToUse = 1:30
)
```

And log:

[ArchR-addGeneIntegrationMatrix-2757a40be28-Date-2021-06-16_Time-20-11-14.log](https://github.com/GreenleafLab/ArchR/files/6665968/ArchR-addGeneIntegrationMatrix-2757a40be28-Date-2021-06-16_Time-20-11-14.log)

Is there a parameter I can tweak to remedy this? Is this issue thrown by Seurat?

Any help/advice you could offer would be greatly appreciated.

**Comment by rcorces** [comment]
This is an error thrown by Seurat. I would follow what the error says. You can pass additional params to `FindTransferAnchors` via the `...`
See the function docs.
https://www.archrproject.com/reference/addGeneIntegrationMatrix.html

**Comment by Dazcam** [comment]
Many Thanks for the swift response.

I tried `k.score=26` and `dimsToUse=26` to get this running, but the following error was thrown.

`<simpleError in irlba(A = mat3, nv = num.cc): max(nu, nv) must be strictly less than min(nrow(A), ncol(A))>`

This error suggests issue was with `num.cc`, which is not an available parameter in`FindTransferAnchors()`. I tried passing it to `...` in `addGeneIntegrationMatrix()` anyway but it didn't work.

`<simpleError in Seurat::FindTransferAnchors(reference = subRNA, query = seuratATAC,     reduction = reduction, features = genesUse, verbose = FALSE,     ...): unused argument (num.cc = 26)>`

It turns that `num.cc` is a parameter the `runCCA()` function that is buried inside `FindTransferAnchors()` and it is [fed directly](https://github.com/satijalab/seurat/blob/9b3892961c9e1bf418af3bbb1bc79950adb481d7/R/integration.R#L342) from the `dims()` parameter in `FindTransferAnchors()`.

I got this working by adding the 4 lines of code below, but I've not worked out if any of them are redundant yet.

```
fc.archR.3 <- addGeneIntegrationMatrix(
  ArchRProj = fc.archR.3, 
  useMatrix = "GeneScoreMatrix",
  matrixName = "GeneIntegrationMatrix",
  reducedDims = "IterativeLSI",
  seRNA = seurat.fc,
  addToArrow = FALSE, 
  groupList = groupList,
  groupRNA = "cellIDs",
  nameCell = "predictedCell_Co",
  nameGroup = "predictedGroup_Co",
  nameScore = "predictedScore_Co",
  dimsToUse = 1:26,
  k.score = 26,
  npcs = 26,
  dims = 1:26
  #num.cc = 26
)
 ```

A couple of things:

A: The gene integration matrix I'm feeding into  `addGeneIntegrationMatrix()` is 24919 X 14893 so it is not clear to me why I'm having this issue. This has only occurred with one of my samples so far. The GroupList subsets also have 

B: Should the `dimsToUse` parameter in `addGeneIntegrationMatrix()` also feed the `dims` parameter in `FindTransferAnchors()`?

C: The warning messages in the OP are still present after success, are these anything to worry about?

**Comment by rcorces** [comment]
> A: The gene integration matrix I'm feeding into addGeneIntegrationMatrix() is 24919 X 14893 so it is not clear to me why I'm having this issue. This has only occurred with one of my samples so far.

I wish I knew the answer. I've never encountered this issue.

> B: Should the dimsToUse parameter in addGeneIntegrationMatrix() also feed the dims parameter in FindTransferAnchors()?

No. `dimsToUse` is passed to a few different ArchR functions called from `addGeneIntegrationMatrix()`. You should be able to separately pass `dims` using `...` if you'd like.

> C: The warning messages in the OP are still present after success, are these anything to worry about?

These warnings come from Seurat and I dont feel qualified to tell you how it would affect things downstream. You can follow up with their developers if you wish.

**Comment by Dazcam** [comment]
No probs. Thanks for your feedback.
