### ISSUE TITLE
unable to run two or more 10x-multiome samples 

### ISSUE THREAD

**Issue by jfa01** [GreenleafLab/ArchR#825]
Hi Jeff , Ryan, Thanks for this great tool. 

Issue: To directly compare two (or more) related samples we need to run them together in ArchR. When this is attempted with the 10x-multiome pipeline ArchR is unable to find the overlap between the RNA and ATAC libraries per sample. (please check additional context). 

[ArchR-addGeneExpressionMatrix-1763d1bd6fece-Date-2021-06-16_Time-17-02-24.log](https://github.com/GreenleafLab/ArchR/files/6666638/ArchR-addGeneExpressionMatrix-1763d1bd6fece-Date-2021-06-16_Time-17-02-24.log)

**Additional context**
```
> inputFiles<-list.files(dir, '.tsv.gz$', full.names = T )
> names(inputFiles) <- c("HC","RTs")

> ArrowFiles <- createArrowFiles(inputFiles = inputFiles, force = TRUE)

> ArrowFiles
[1] "HC.arrow"  "RTs.arrow"

> proj1 <- ArchRProject(ArrowFiles)
> proj1

class: ArchRProject 
outputDirectory: /Users/.../ArchROutput 
samples(2): HC RTs
sampleColData names(1): ArrowFiles
cellColData names(13): Sample TSSEnrichment ... nDiFrags BlacklistRatio
...

> inputFiles2<-list.files(dir, '.h5$', full.names = T )
> names(inputFiles2) <- c("HC","RTs")

> seRNA <- import10xFeatureMatrix( input = inputFiles2)

Importing Feature Matrix 1 of 2
Importing Feature Matrix 2 of 2

> seRNA

     [,1] [,2]
[1,] ?    ?   


> proj1 <- addGeneExpressionMatrix(input = proj1, seRNA = seRNA, force = TRUE)

ArchR logging to : ArchRLogs/ArchR-addGeneExpressionMatrix-1763d1bd6fece-Date-2021-06-16_Time-17-02-24.log
If there is an issue, please report to github with logFile!
2021-06-16 17:02:24 : Overlap w/ scATAC = 0
Error in addGeneExpressionMatrix(input = proj1, seRNA = seRNA, force = TRUE) : 
  No overlap found with scATAC!
```

**Comment by rcorces** [comment]
as you've shown, your `seRNA` object is not correct.

**Comment by jfa01** [comment]
yes is the seRNA object, the input are file paths the expected to import the matrix, I don't have issue importing them separately. So the function import10xFeatureMatrix() is not creating the object when using two matrix. Is that working on your end? Thank you.

**Comment by hypercompetent** [comment]
You may need to load each matrix separately, then combine them.

Try: 
```
# Load each file
seRNA_list <- lapply(inputFiles2, import10xFeatureMatrix)
# Combine as a single seRNA
seRNA <- do.call(cbind, seRNA_list)
# Remove the list version to free up memory (if needed)
rm(seRNA_list)
```

**Comment by jfa01** [comment]
Thank you for the comment @hypercompetent , 

> seRNA <- do.call(cbind, seRNA_list)
Error in .cbind.SummarizedExperiment(args) : 
  '...' object ranges (rows) are not compatible

**Comment by jfa01** [comment]
solution: 

https://github.com/GreenleafLab/ArchR/issues/507#issuecomment-780709104
