### ISSUE TITLE
How to find the peak names/peak coordinates in the PeakMatrix?

### ISSUE THREAD

**Issue by RegnerM2015** [GreenleafLab/ArchR#832]
Hi @jgranja24 and @rcorces 

I am using ArchR 0.9.5 for reproducibility purposes, as I am currently in the process of peer review/revisions. 

**Describe the bug**
The order of peakname indicies between the PeakMatrix and getPeakSet() are inconsistent. 

I am trying to find the peak names or peak coordinates for the PeakMatrix. When I use getPeakSet(), the peak indices are NOT in the same order despite having the same number of peak indices:

```
peaks.mat <- getMatrixFromProject(atac,useMatrix = "PeakMatrix")
peaks <- getPeakSet(atac)

```
The dimensions are consistent but the order is not:
```
> length(peaks)
[1] 519525
> dim(peaks.mat)
[1] 519525  72507
> length(which(peaks.mat@elementMetadata$idx == peaks@elementMetadata$idx))
[1] 86173
```

How can I find the correct order of peak names? Thanks!

[ArchR-getMatrixFromProject-7057e9cfdbe-Date-2021-06-21_Time-16-14-49.log](https://github.com/GreenleafLab/ArchR/files/6689442/ArchR-getMatrixFromProject-7057e9cfdbe-Date-2021-06-21_Time-16-14-49.log)

**Comment by RegnerM2015** [comment]
@rcorces 

Did you mean to close this issue? If so, I apologize I could have done more to reproduce this issue using the tutorial dataset. I will try the tutorial dataset next. If I am missing something glaringly obvious, if you could point me in the right direction of the documentation, that would be greatly appreciated!

**Comment by rcorces** [comment]
I replied on your discussion topic instead.
