### ISSUE TITLE
determineOverlapCpp identify higher than expected overlap

### ISSUE THREAD

**Issue by Brawni** [GreenleafLab/ArchR#840]
Hello @archrdevs,

I was fiddling with the portion of code for generating the KNN groups on which co-accessibilty is calculated. As I'd like to generate KNN groups in a cluster aware fashion I'm rewriting some of that code for my analysis, essentially sampling seeds per cluster and not across all cells. I generate KNN groups with the function `.computeKNN` for the smallest cluster (which contains 97 cells) using only 2 seed cells and k of 40 cells and then pass it to  `determineOverlapCpp`  which marks one of the knn group to be overlapping above the threshold (overlapCutoff = 0.8). The overlap however doesn't pass the threshold, unless the overlap is calculated in a different way:

```
overlapCutoff = 0.8
i = 'C20' # cluster id
rD = getReducedDims (ArchRProj, reducedDims = reducedDims, corCutOff = corCutOff, dimsToUse = dimsToUse)
rD_group = rD[ArchRProj$cellNames [getCellColData(ArchRProj)[,group] == i],]    
idx = sample (seq_len(nrow(rD_group)), 2, replace = FALSE)
idx
[1] 49 22
knnObj = .computeKNN (data = rD_group, query = rD_group[idx,], k = 40)
> knnObj
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]   49   79   66   87   63    1   77   41   83    20    74    90    92    44
[2,]   22    9   43   37   10   81   17    5   86    21    13     2    58    18
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]    64    60    62    68    85    73    46    71    51    59    14    96
[2,]    67    40    88    91    54    70    82    97    12     7    42    15
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,]    28    52    65    39    19    45    11    95    80     3    27    53
[2,]    89    29    93    72     4    78    19    61    34     3    36    71
     [,39] [,40]
[1,]    15    89
[2,]    50    35
> determineOverlapCpp (knnObj, overlapCutoff)
[1]  0 -1

# determineOverlapCpp marks the second group to remove but the overlap between the two is lower than threshold
> length(intersect (knnObj[1,], knnObj[2,])) / 40 * 2        
[1] 0.25
```
Thanks a lot for your help!

**Comment by rcorces** [comment]
Sorry if I'm not following. You're saying there is a bug in `determineOverlappCpp()`?

**Comment by rcorces** [comment]
its written in C++ so its in the src directory:
https://github.com/GreenleafLab/ArchR/blob/master/src/KNN_Utils.cpp

**Comment by Brawni** [comment]
Thanks for the link but I have no idea of C++ though. It would be great if at some point you could double check this.
Thanks!

**Comment by Brawni** [comment]
ok I found the error, which was on my side, I changed the argument of that function accidentally but restoring at as it in the `addCoaccessibility` function works well now:
```
`determineOverlapCpp (knnObj, overlapCutoff * k )`
1] 0 0
```
Sorry for the misreport!
