### ISSUE TITLE
Differenet in IGV and ArchRBrowser

### ISSUE THREAD

**Issue by dandata123-tech** [GreenleafLab/ArchR#847]
HI,Greenleaf:
Your work is really brilliant.And really help me with my work.
I meet some trouble again and turn to your help.
First,I get peakAnnotation_markerList_MUT.df  and found that the Same Gene that the promotor peak rise and down stream gene decrease .So i use the function getGroupBW(motor, groupBy = "Sample") and get the bed file that announce LOG2FC in IGV ,here is the picture
![Screenshot from 2021-06-25 13-38-02](https://user-images.githubusercontent.com/71436326/123378533-78f93580-d5bf-11eb-8cc9-0347f20e85ea.png)
and when  i zoom in the area,it looks odd
![Screenshot from 2021-06-25 13-50-29](https://user-images.githubusercontent.com/71436326/123378616-94fcd700-d5bf-11eb-94e6-1894c9fa317a.png)
and here is the picture from our ArchRBrowser
![Screenshot from 2021-06-25 14-14-48](https://user-images.githubusercontent.com/71436326/123378772-c1185800-d5bf-11eb-99a6-e0d87a092265.png)
it seems normal .
I wonder why they are different
and there is a stupid question:why threre can be a gene that have both up peak and down peak.

Yours Dan
Looking for your reply.

**Comment by rcorces** [comment]
This is almost certainly due to differences in how you have applied binning and smoothing in the two visualizations
