### ISSUE TITLE
Continuing through after error ggplot for TSS by Frags

### ISSUE THREAD

**Issue by sanjeevRJMU1** [GreenleafLab/ArchR#85]
Hi,

Congrats and thank you for developing and sharing ArchR!

I'm running into an error very quickly using your tutorial dataset at createArrowFiles. copy/pasting lines in R studio as I run createArrowFiles:
Using GeneAnnotation set by addArchRGenome(Hg19)!
Using GeneAnnotation set by addArchRGenome(Hg19)!
ArchR logging to : ArchRLogs/ArchR-createArrows-38764dcec8f-Date-2020-04-29_Time-19-45-15.log
If there is an issue, please report to github with logFile!
2020-04-29 19:45:15 : Batch Execution w/ safelapply!, 0 mins elapsed.
2020-04-29 19:51:01 : createArrowFiles has encountered an error, checking if any ArrowFiles completed..
ArchR logging successful to : ArchRLogs/ArchR-createArrows-38764dcec8f-Date-2020-04-29_Time-19-45-15.log
Warning message:
In mclapply(..., mc.cores = threads, mc.preschedule = preschedule) :
  3 function calls resulted in an error
> ArrowFiles
character(0)

And this is with the latest install:
> devtools::install_github("GreenleafLab/ArchR", ref="master", repos = BiocManager::repositories())
Skipping install of 'ArchR' from a github remote, the SHA1 (c323e3c9) has not changed since last install.
  Use `force = TRUE` to force installation

When I look thru the logs, the error seems to be at the ggplot step for the TSS by frag. The frag size distribution plot comes out for all three datasets. Any help would be appreciated - thanks!!

[ArchR-createArrows-38764dcec8f-Date-2020-04-29_Time-19-45-15.log](https://github.com/GreenleafLab/ArchR/files/4555877/ArchR-createArrows-38764dcec8f-Date-2020-04-29_Time-19-45-15.log)

**Comment by jgranja24** [comment]
Do you have ggrastr installed? This is the most common reason that plot fails. Ive been thinking of adding maybe like a hex plot for this when there is no ggrastr installed.

It shouldnt error out there but maybe this is an rstudio problem. There is a trycatch statement that handles this but maybe the message part creates an error in rstudio.

Ill look into this further.

**Comment by sanjeevRJMU1** [comment]
i do have ggrastr, loaded it, but still no go... (sessionInfo in log, ggraster_0.1.7). Also, i tried to Rscript the lines in command line thru to the createArrowFiles step to avoid any Rstudio issues but still no go (log attached). im with you, not sure why a plotting issue is crashing the whole thing - it's computing the TSS enrichment, # cells and med frags just fine (19.9535/2454/3349.5, 16.72/3275/3178, 15.254/4932/2771, respectively)...

[ArchR-createArrows-ccb313f4fcd-Date-2020-04-29_Time-22-11-14.log](https://github.com/GreenleafLab/ArchR/files/4556300/ArchR-createArrows-ccb313f4fcd-Date-2020-04-29_Time-22-11-14.log)

**Comment by rcorces** [comment]
This still seems like a `ggrastr` issue. What version of the Cairo R package do you have installed?

**Comment by jgranja24** [comment]
Can you confirm cairo works with

`Cairo::Cairo(type='raster'); dev.off()`

**Comment by Eomesodermin** [comment]
Issue was fixed for me by installing "Cairo", "ggrastr", and "XQuartz". On a MacOS.

**Comment by sanjeevRJMU1** [comment]
Confirmed - issue resolved by installing Cairo and Xquartz! Thanks for the fast replies everyone.

**Comment by rcorces** [comment]
@jgranja24 - it looks like I inadvertently removed the instructions recommending XQuartz installation on macOS from the install instructions. I have added those back now. I know we have a solution coming for ggrastr but I think it might also be good to add `Cairo` as one of the packages that is installed via `installExtraPackages()` unless you want to completely support plot generation without rasterization.

**Comment by jgranja24** [comment]
Thanks for identifying this problem in the new version we are updating this will be better addressed. On loading ArchR it'll tell you whether Cairo is functional.
