### ISSUE TITLE
getGroupBW tileSize

### ISSUE THREAD

**Issue by gegenhu** [GreenleafLab/ArchR#853]
I want to generate 1 bp-resolution bigwig tracks for each cluster, using the getGroupBW function with tileSize = 1. However, setting tileSize to anything lower than ~25 caused the function to get stuck on the first cluster and not proceed.

`getGroupBW(ArchRProj = P14_archr_subset,
groupBy = "Cluster",
normMethod = "ReadsInTSS",
tileSize = 25,
ceiling = 4,
verbose = TRUE,
threads = 96,
logFile = createLogFile("getGroupBW")
)
ArchR logging to : ArchRLogs/ArchR-getGroupBW-6fb34d1b7995-Date-2021-06-28_Time-12-07-00.log
If there is an issue, please report to github with logFile!
2021-06-28 12:07:22 : BNSTp_Bnc2 (1 of 7) : Creating BigWig for Group, 0.373 mins elapsed.
2021-06-28 12:08:10 : BNSTp_Epsti1 (2 of 7) : Creating BigWig for Group, 1.168 mins elapsed.
2021-06-28 12:08:40 : BNSTp_Haus4 (3 of 7) : Creating BigWig for Group, 1.676 mins elapsed.
2021-06-28 12:09:20 : BNSTp_Nxph2 (4 of 7) : Creating BigWig for Group, 2.345 mins elapsed.
2021-06-28 12:09:54 : BNSTp_Tac2 (5 of 7) : Creating BigWig for Group, 2.906 mins elapsed.
2021-06-28 12:10:28 : BNSTpr_Esr2 (6 of 7) : Creating BigWig for Group, 3.467 mins elapsed.
2021-06-28 12:10:56 : BNSTpr_St18 (7 of 7) : Creating BigWig for Group, 3.942 mins elapsed.`
 

`getGroupBW(
ArchRProj = P14_archr_subset,
groupBy = "Cluster",
normMethod = "ReadsInTSS",
tileSize = 10,
ceiling = 4,
verbose = TRUE,
threads = 20,
logFile = createLogFile("getGroupBW")
)
ArchR logging to : ArchRLogs/ArchR-getGroupBW-6fb310c9934e-Date-2021-06-28_Time-11-44-18.log
If there is an issue, please report to github with logFile!
2021-06-28 11:45:25 : BNSTp_Bnc2 (1 of 7) : Creating BigWig for Group, 1.11 mins elapsed.`

**Comment by rcorces** [comment]
When you say "get stuck", what does that mean? Are you positive that nothing is happening? Are any temp files being written? I'm not sure we have ever tried 1-bp resolution exports. I just tried it with 1-bp tileSize and got:
```
> getGroupBW(ArchRProj = projHeme5, groupBy = "Clusters2", tileSize = 1)
ArchR logging to : ArchRLogs/ArchR-getGroupBW-365f52401875-Date-2021-06-28_Time-16-41-41.log
If there is an issue, please report to github with logFile!
Error in .Call2("solve_user_SEW0", start, end, width, PACKAGE = "IRanges") : 
  long vectors not supported yet: memory.c:3717
```

You might try to use a different approach. For example, single-base insertions are stored per-group in an HDF file within the GroupCoverages directory called <sample_name>.insertions.coverage.h5
https://github.com/GreenleafLab/ArchR/blob/968e4421ce7187a8ac7ea1cf6077412126876d5f/R/GroupCoverages.R#L260

**Comment by gegenhu** [comment]
Thanks for replying. When tileSize = 1, I receive the same error: 

```
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'restrict': long vectors not supported yet: memory.c:3788
```
When tileSize is set between ~2-25, the function does not proceed past "Creating BigWig for Group" for the first group after ~45 min of runtime. No temp files are generated in the GroupBigWigs directory. 

As an alternative strategy, I was actually thinking about subsetting the original fragments.tsv.gz file by cell barcode for each group, covert to BAM, and then generate single-bp bigwigs with deepTools bamCoverage, using the 'ReadsInTSS' as a custom scale factor. I'm not sure how 'ReadsInTSS', which is computed on a per-cell basis, is used to normalize coverage for the entire group of cells?

**Comment by rcorces** [comment]
> I'm not sure how 'ReadsInTSS', which is computed on a per-cell basis, is used to normalize coverage for the entire group of cells

It is summed across the cells in the group

**Comment by gegenhu** [comment]
Thanks!
