### ISSUE TITLE
 Matching of useMatrix1 and useMatrix2 resulted in no mappings

### ISSUE THREAD

**Issue by dandata123-tech** [GreenleafLab/ArchR#854]
Hi,greenleaf:
Your work is amazing and I use our ARCHR in all my scatac-seq
But when I do correlateMatrices,it shows:
Error: Matching of useMatrix1 and useMatrix2 resulted in no mappings! 
and the log is here:
[ArchR-addArchRAnnotations-135ee17f7894ce-Date-2021-06-23_Time-12-24-06.log](https://github.com/GreenleafLab/ArchR/files/6731213/ArchR-addArchRAnnotations-135ee17f7894ce-Date-2021-06-23_Time-12-24-06.log)
![Screenshot from 2021-06-29 14-38-48](https://user-images.githubusercontent.com/71436326/123749271-d1924080-d8e7-11eb-8888-ea2c05e7d552.png)
Is that ok with all my data that don't have the cor?

and here is my main data
**motor <- subsetArchRProject(proj, cells = getCellNames(proj)[proj$Clusters %in% c("C5")],outputDirectory = "/data2/xc/atac/outcome/motor/")
motor <- addMotifAnnotations(ArchRProj = motor, motifSet = "homer", name = "Motif_homer",force=TRUE)
motor <- addDeviationsMatrix(
  ArchRProj = motor, 
  peakAnnotation = "Motif_homer",
  force = TRUE
)
seGroupMotif <- getGroupSE(ArchRProj = motor, useMatrix = "Motif_homerMatrix", groupBy = "Sample")
seGroupMotif

seZ <- seGroupMotif[rowData(seGroupMotif)$seqnames=="z",]

rowData(seZ)$maxDelta <- lapply(seq_len(ncol(seZ)), function(x){
  rowMaxs(assay(seZ) - assay(seZ)[,x])
}) %>% Reduce("cbind", .) %>% rowMaxs
corGSM_MM <- correlateMatrices(
  ArchRProj = motor,
  useMatrix1 = "GeneScoreMatrix",
  useMatrix2 = "Motif_homerMatrix",
  reducedDims = "IterativeLSI"
)**

Looking fowards your reply and it means a lot for me.
Thank you!
Yours Dan

**Comment by rcorces** [comment]
were you hoping for a different answer than your original post on the same topic?
https://github.com/GreenleafLab/ArchR/issues/829

**Comment by dandata123-tech** [comment]
Sorry for ask the same question.
Is the&nbsp;phenomenon common for the Acac?I wonder if it is my code question or the data is that not so good.
When I first meet the question I thought it might own to data .But now I question myself.So I open the question.
&nbsp;Could you please give me some advice?thank you.


Yours Dan&nbsp;

发自我的iPhone


------------------ Original ------------------
From: Ryan Corces ***@***.***&gt;
Date: Tue,Jun 29,2021 10:25 PM
To: GreenleafLab/ArchR ***@***.***&gt;
Cc: Dan ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [GreenleafLab/ArchR]  Matching of useMatrix1 and useMatrix2 resulted in no mappings (#854)





 
were you hoping for a different answer than your original post on the same topic?
 #829

**Comment by rcorces** [comment]
Sorry but I already answered your question on the other thread.

**Comment by dandata123-tech** [comment]
I will learn harder and it’s really kind of you to reply me.thanks a lot&nbsp;



发自我的iPhone


------------------ Original ------------------
From: Ryan Corces ***@***.***&gt;
Date: Tue,Jun 29,2021 10:40 PM
To: GreenleafLab/ArchR ***@***.***&gt;
Cc: Dan ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [GreenleafLab/ArchR]  Matching of useMatrix1 and useMatrix2 resulted in no mappings (#854)





 
Sorry but I already answered your question on the other thread.
