### ISSUE TITLE
Identify positive TF regulators in single cluster sample

### ISSUE THREAD

**Issue by peggiechien** [GreenleafLab/ArchR#858]
Hello, I am wondering if it's possible to identify positive TF regulators and plot them on a volcano plot like in section 15.4 of a sample that only has one cluster? I've been trying to do this for one of my ArchR projects containing just one sample with one cluster/population of cells subsetted out from another ArchR project. I've been following the positive TF regulator tutorial for gene score matrix and there were several points where I ran into errors:

This:
``
rowData(seZ)$maxDelta <- lapply(seq_len(ncol(seZ)), function(x){
  rowMaxs(assay(seZ) - assay(seZ)[,x])
}) %>% Reduce("cbind", .) %>% rowMaxs
``
Led to this:
``
Error in rowMaxs(.) : 
  Argument 'dim.' must be an integer vector of length two.
``

This:
``
corGSM_MM$maxDelta <- rowData(seZ)[match(corGSM_MM$MotifMatrix_name, rowData(seZ)$name), "maxDelta"]
``
Led to this:
``
Error: subscript contains invalid names
``

As a result, when I look in the `corGSM_MM` object, no TFs are being identified as positive TF regulators.

Thank you!

**Comment by rcorces** [comment]
I'm not sure why this gives an error but from a biological standpoint I dont think you will have enough variation within a single cluster to identify such positive TF regulators. This requires variability which is inherently low in a single cluster. If you have more information I can try to understand why this gives an error but I'm not sure.
