### ISSUE TITLE
Docs: GSL dependency resolution on Linux systems

### ISSUE THREAD

**Issue by hypercompetent** [GreenleafLab/ArchR#86]
First: Thanks for putting out ArchR! I'm excited to test it out on our data! I hit a snag in installation that I thought other users might encounter. This was found on a Debian 9 system:

### If this is an issue with documentation that is absent/missing:

**Describe what material you feel should be explained**
Some dependencies of ArchR require the Gnu Scientific Library (GSL) to be installed. In particular, I hit an installation roadblock with DirichletMultinomial failing to install. The errors weren't exactly clear for this case, so it may be good to provide a brief documentation section to help users along if they encounter this.

GSL can be installed with:
```
wget http://gnu.mirror.constant.com/gsl/gsl-2.6.tar.gz
tar -xzvf gsl-2.6.tar.gz
cd gsl-2.6
./configure
make
sudo make install
```

On some systems, the GSL library location will have to be provided to R using:
```
ld_path <- paste(Sys.getenv("LD_LIBRARY_PATH"), "/usr/local/lib/", sep = ";")
Sys.setenv(LD_LIBRARY_PATH = ld_path)
``` 

ArchR and its dependencies should then be able to be installed as normal with:
```
devtools::install_github("GreenleafLab/ArchR", ref="master", repos = BiocManager::repositories())
```

**Where do you think this documentation would belong?**
This may belong in the "Known trouble spots for installation" section of the site at https://www.archrproject.com/ .

Cheers,
-Lucas

**Comment by rcorces** [comment]
Thanks for the thorough description and for using the template. I will add this to the install instructions with the next website release.

**Comment by jgranja24** [comment]
Awesome thanks for the information! 
Installation of packages is always tricky!
