### ISSUE TITLE
This function GeneIntegrationMatrix requires scATAC and  scRNA from same sample?

### ISSUE THREAD

**Issue by xiezhan** [GreenleafLab/ArchR#864]
This function, will integrate multiple subsets of scATAC cells
with a scRNA experiment, compute **_matched_** scRNA profiles and then
store this in each samples ArrowFile.

How to understand the "matched" scRNA profiles ?

thanks

**Comment by rcorces** [comment]
Please note that the Issues section is not meant for usage questions. Those belong in Discussions as clearly indicated when you try to open an issue:
![image](https://user-images.githubusercontent.com/10343046/124215763-8a53ad80-daa9-11eb-8a4b-3214834ee8a6.png)
I have migrated your post there.

matched just means from the same type of sample. it could be the exact same sample or it could be publicly available data from the same cell types / tissue type.
