### ISSUE TITLE
How to get scRNA data for integration with scATAC data?

### ISSUE THREAD

**Issue by xiezhan** [GreenleafLab/ArchR#869]
hi
in the manual of ArchR,the scRNA data wes provided directly.

https://jeffgranja.s3.amazonaws.com/ArchR/TestData/scRNA-Hematopoiesis-Granja-2019.rds"

What i want to know is how to get this data?in other words,i want to know the process to generate the data

I can't use scRNA' Seurat data for integration

Would you  tell me that?

thanks so much

**Comment by rcorces** [comment]
Please make sure to follow instructions. This is not a bug - it is a question and it belongs in the Discussions. This is clearly indicated when you open a new issue:
![image](https://user-images.githubusercontent.com/10343046/124486300-4e973d00-dd62-11eb-8e39-4912b88fae72.png)

The answer to your question is in the manual:
![image](https://user-images.githubusercontent.com/10343046/124486175-2dcee780-dd62-11eb-9db0-4af2bdfa233b.png)
