### ISSUE TITLE
Not able to read files to creat Arrov

### ISSUE THREAD

**Issue by CSBioAzim** [GreenleafLab/ArchR#87]
Hi,

I'm trying to read the fragment files to create ArrowFiles, but unfortunately ArchR is not able to read it.
Here is my try
```

> inputFiles<-c("/Volumes/G_Drive/scAL/ATAC/S111/fragments.tsv.gz")
> 
> ArrowFiles <- createArrowFiles(
+   inputFiles = inputFiles,
+   sampleNames = c("111"),
+   filterTSS = 4, #Dont set this too high because you can always increase later
+   filterFrags = 1000, 
+   addTileMat = TRUE,
+   addGeneScoreMat = TRUE
+ )
Using GeneAnnotation set by addArchRGenome(Hg19)!
Using GeneAnnotation set by addArchRGenome(Hg19)!
ArchR logging to : ArchRLogs/ArchR-createArrows-9d3a110ba5be-Date-2020-04-30_Time-17-06-20.log
If there is an issue, please report to github with logFile!
Error in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file 'ArchRLogs/ArchR-createArrows-9d3a110ba5be-Date-2020-04-30_Time-17-06-20.log': No such file or directory
```

**Comment by rcorces** [comment]
You appear to have some file access issues. ArchR does not appear to be able to read your fragments file nor write the log file. I dont think this is an ArchR issue. Have you run the tutorial, storing the fragment files in a similar location? What happens when you type
`list.files("/Volumes/G_Drive/scAL/ATAC/S111/")`

**Comment by CSBioAzim** [comment]
Thanks, files are there, but I have no idea why I'm not able to read or write.  Also, when I try

> inputFiles <- getTutorialData("Hematopoiesis")
> inputFiles
named character(0)
it doesn't download the tutorial files.

The files are there for my own data.
> list.files("/Volumes/G_Drive/scAL/ATAC/S111")
[1] "filtered_peak_bc_matrix.h5" "fragments.tsv.gz"          
[3] "fragments.tsv.gz.tbi"       "singlecell.csv"

Any idea what might be the problem? What do I need to check further?

**Comment by rcorces** [comment]
I'm not sure what the problem is but it certainly looks like a file access issue. Does the "G_Drive" in your path indicate that this is a mounted google drive? If so, can you try doing this in a different local file location?

**Comment by CSBioAzim** [comment]
I solved it.  Fortran (gfortran) and XQuartz were missing, and after installing them it resolved.

**Comment by rcorces** [comment]
ok. glad you figured it out and thanks for letting us know
