### ISSUE TITLE
positive TFs for a specific cluster

### ISSUE THREAD

**Issue by rojinsafavi** [GreenleafLab/ArchR#875]
Hello,

I am trying to find correlated TF-TF_accessibility correlation in each cluster independently. I tried the following 

```
corGIM_MM <- correlateMatrices(
    ArchRProj = projHeme2,
    useMatrix1 = "GeneIntegrationMatrix",
    useSeqnames1 = groupAcells,
    useSeqnames2 =  groupAcells,
    useMatrix2 = "MotifMatrix",
    reducedDims = "IterativeLSI", threads = 5
)
```

But the result does not change compared to when I use all the cells or when I use another subset of cells. I was wondering if I'm doing something wrong or if it's a bug?

**Comment by rcorces** [comment]
I'm not sure I understand. Perhaps you can create a reproducible example with the tutorial data to illustrate the problem.
