### ISSUE TITLE
problems in creating arrows using hybrid genome reference

### ISSUE THREAD

**Issue by skywalker51616** [GreenleafLab/ArchR#876]
Is it possible to analyze samples of two species (e.g. human and mouse), just like 10x supports a hybrid reference of hg38 and mm10? 

I tried to use customize genomeAnnotation using merged fasta files of hg38 and mm10, chromosome names changed to hg38_chr* and mm10_chr*, and geneAnnotation using gtf with chromosome names modified in the same way. However, I did not manage to create arrow files. 

[ArchR-createArrows-462515ac10d3d-Date-2021-07-08_Time-10-44-51.log](https://github.com/GreenleafLab/ArchR/files/6781182/ArchR-createArrows-462515ac10d3d-Date-2021-07-08_Time-10-44-51.log)

**Comment by skywalker51616** [comment]
library(GenomicFeatures)
library(ArchR)


#hg38_mm10_KG_txdb <- makeTxDbFromGFF(file='/data/bio-tianc/reference/hg38_mm10/hg38_mm10.knownGene.gtf')
#saveDb(hg38_mm10_KG_txdb, file="/data/bio-tianc/reference/hg38_mm10/hg38_mm10_KG_txdb.sqlite")


hg38_mm10_KG_txdb <- loadDb('hg38_mm10_KG_txdb.sqlite')
seqlevels(hg38_mm10_KG_txdb) <- c(paste("hg38_chr", c(1:22, "X", "Y", "M"), sep=''), paste("mm10_chr", c(1:19, "X", "Y", "M"), sep=''))

gene.ranges <- genes(hg38_mm10_KG_txdb); length(gene.ranges$gene_id)
tss.ranges <- resize(gene.ranges, 1, "start")
exon.ranges <- exons(hg38_mm10_KG_txdb)

geneAnnotation = createGeneAnnotation(
    TSS = tss.ranges,
    exons = exon.ranges,
    genes = gene.ranges
)



library(BSgenome.HsapMmus.UCSC.hg38mm10)
genomeAnnotation = createGenomeAnnotation(genome = BSgenome.HsapMmus.UCSC.hg38mm10, filter = F)











ArrowFiles <- createArrowFiles(
    inputFiles = '/scratch/2021-07-05/bio-tianc/BGI_scATAC/04_fragments/scATAC_droplet.hg38_mm10.fragments.tsv',
    sampleNames = 'BGI_scATAC',
    geneAnnotation = geneAnnotation,
    genomeAnnotation = genomeAnnotation,
    minTSS = 4,
    minFrags = 1000,
    addTileMat = TRUE,
    addGeneScoreMat = TRUE,
    excludeChr = c('hg38_chrM', 'hg38_chrY', 'mm10_chrM', 'mm10_chrY')
)

**Comment by rcorces** [comment]
I think in theory this is possible but we have not done this on our end.

We previously addressed a similar issue here - https://github.com/GreenleafLab/ArchR/issues/366
This workflow splits the reads up front (at the BAM file stage) and analyzes the species separately.

Please close if this answers your question.
