### ISSUE TITLE
If I don’t have the scRNA-seq data mentioned in Chapter 8, how can I perform downstream analysis?

### ISSUE THREAD

**Issue by woshiyangsi** [GreenleafLab/ArchR#883]
Hi guys,

Because I don’t have scRNA-seq data, I went directly from Chapter 7 to Chapter 9
(Chapter 9 Pseudo-bulk Replicates in ArchR)
But i got the error.

> projBMX3 <- addGroupCoverages(ArchRProj = projBMX2, groupBy = "Clusters2")
ArchR logging to : ArchRLogs/ArchR-addGroupCoverages-7a1e5fce3978-Date-2021-07-13_Time-09-35-31.log
If there is an issue, please report to github with logFile!
Error in value[[3L]](cond) : select Not Found in Colnames of cellColData:
Error: Problem with `mutate()` column `tmpNewCol123`.
ℹ `tmpNewCol123 = eval(parse(text = select[x]))`.
✖ can not found project 'Clusters2'

If I don’t have the scRNA-seq data mentioned in Chapter 8, how can I perform downstream analysis?

Looking forward your reply,
Siyu.

**Comment by rcorces** [comment]
The manual is meant to showcase how ArchR can be used, not a step-by-step copy-and-paste guide for you to use on your own data. You should read the manual and extrapolate to your own data.
