### ISSUE TITLE
Acquisition of gene expression matrix

### ISSUE THREAD

**Issue by 1221li** [GreenleafLab/ArchR#887]
Hello! First of all, thank you very much for the single-cell multi-omics technology you developed, which has provided great convenience for my data analysis。Then, I was recently troubled by the fact that I wanted to get a gene expression matrix for each of my clusters.In this expression matrix, row names are cluster and column names are genes.But I don't know how to extract this matrix.I want to use the extracted matrix to do a personalized heat map of gene expression.I hope you can help me answer my questions. Thank you very much.
In addition, I have a small question, that is, what are the meanings of Mean MeanDiff, AUC MeanBGD shown below
> assays(markersGS)
List of length 7
names(7): Log2FC Mean FDR Pval MeanDiff AUC MeanBGD

**Comment by rcorces** [comment]
`getMatrixFromProject()`

**Comment by 1221li** [comment]
Thank you for your answer.But I still have some questions.
projtwodata2_clu_5 <- addClusters(input =projdata2_lsi_5, reducedDims = "IterativeLSI")
table(projtwodata2_clu_5$Clusters)
projdata2_UAMP<- addUMAP(ArchRProj = projtwodata2_clu_5, reducedDims = "IterativeLSI")
> umap_2<-getMatrixFromProject(projdata2_UAMP)
> umap_2
class: SummarizedExperiment 
dim: 14103 1622 
metadata(0):
assays(1): GeneScoreMatrix
rownames: NULL
rowData names(6): seqnames start ... name idx
colnames(1622): IVO#CTCAGCTAGGAAACTT-2 IVO#CGTGGCATCGGCTATA-2 ...
  IVO#CTTAATCTCTGCCGAG-1 IVO#GATGATCCAAGCACTT-1
colData names(15): DoubletEnrichment DoubletScore ... Clusters BioNames
> write.csv(assays(umap_2)$GeneScoreMatrix,file="test.csv")
In the GenescoreMatrix I obtained, colnames are 1622 cells, and I want colname to be cluster and column name to be 14103 genes. Could you please tell me how I should operate

**Comment by rcorces** [comment]
Please note that questions about ArchR belong in the Discussions section and you have created an Issue which is only meant for bugs.

Also, your question appears to be how to transpose a matrix in R which is a basic R question and not related to ArchR. We do not have bandwidth to answer this type of question.
