### ISSUE TITLE
Error in doubScores

### ISSUE THREAD

**Issue by SaskiaFreytag** [GreenleafLab/ArchR#89]
Hi,

I downloaded ArchR today and tried to run it on some of 6 scATAC-seq (Cellranger output) files. While the creation of the arrow files did not pose any problems, the next step of detecting doublets ran into an error. This error was so severe that it ended up with me being possibly fork bombed (not sure about this, but I kept getting `bash fork retry: no child processes ` and had to ask the sys admin to delete my processes). 

I have attached my log files. I should probably mention that I installed ARchR in an anaconda environment. 

If you have any pointers, it would be much appreciated.
[ArchR-addDoubletScores-6def61bf62cb-Date-2020-05-01_Time-14-29-10.log](https://github.com/GreenleafLab/ArchR/files/4562946/ArchR-addDoubletScores-6def61bf62cb-Date-2020-05-01_Time-14-29-10.log)

**Comment by jgranja24** [comment]
the error in your log file reads as

> <simpleError in .requirePackage("Seurat", source = "cran"): Required package : Seurat is not installed/found!

by default ArchR uses Seurat for clustering. Im not sure of that fork bomb but the error is Seurat installation.

to install seurat see CRAN or try ArchR::installExtraPackages() as described
on the installation section of the website www.ArchRProject.com

**Comment by SaskiaFreytag** [comment]
Sorry send the wrong log file. I figures out that problem.
[ArchR-addDoubletScores-6def31472c2e-Date-2020-05-01_Time-15-22-39.log](https://github.com/GreenleafLab/ArchR/files/4562970/ArchR-addDoubletScores-6def31472c2e-Date-2020-05-01_Time-15-22-39.log)

**Comment by jgranja24** [comment]
Hmm can you try setting threads to 1. This will switch to lapply. This function isnt super parallel anyways so you wont experience to big of a slowdown.

**Comment by SaskiaFreytag** [comment]
Sure will give it a go.

**Comment by jgranja24** [comment]
Please let us know if this is resolved.

Best

jeff

**Comment by SaskiaFreytag** [comment]
Yep that fixed it.

**Comment by jgranja24** [comment]
Great, sometimes these parallelization issues are just finicky and thats why threads = 1 is always a great start to circumventing these issues. Closing this issue now.

Best

Jeff
