### ISSUE TITLE
Adding ColData results in error 

### ISSUE THREAD

**Issue by sneddonucsf** [GreenleafLab/ArchR#897]
Hello, 

I have created an ArchR project from a publicly available dataset and am trying to add cell type annotations from the authors supplementary files off of GEO. 

I've created the ArchR project with: 
```
proj <- ArchRProject(ArrowFiles = ArrowFiles, 
                       outputDirectory = outdir, 
                       copyArrows = FALSE)
``` 
which yields an object with 17,101 cells. I've then imported a data frame that has a two columns; one with cellular barcodes, and another with the cell type annotation. 

```
metadata <- as.data.frame(read.table("~./metadata.txt"))
```
with yields a DF with 15,298 entries (the originally authors did some filtering steps, so they have less cells). 

I'm now trying to add the cell type annotation to my ArchR project with the following: 
```
proj <- addCellColData(ArchRProj = proj, data = as.character(metadata$V4),
                            cells = as.character(metadata$V1), name = "CellType")
```
but I am getting the error: 
**Error in length(xi) <- max_len: cannot set length of non-(vector or list)**

In case it is at all important, the order of the cell names is not the same between the ArchR project and the metadata table, which is why I can't simply do proj$CellType = metadata$V4 (plus they're not the same length). 

Any idea how I might fix this? Thank you!

**Comment by rcorces** [comment]
but are the entries in `metadata$V1` actually cell names in the ArchRProject?
`length(which(as.character(metadata$V1) %in% getCellNames(proj)))`

**Comment by sneddonucsf** [comment]
length(which(as.character(metadata$V1) %in% getCellNames(proj)))

returns 15107, so it seems like most (but not all) are present

**Comment by rcorces** [comment]
I think you need to be careful about how you provide the metadata and not try to give ArchR cell names that arent present. I would clean up your metadata so that it only contains cells that are also present in the project.

Please close if you are able to solve.
