### ISSUE TITLE
addGroupCoverages Error.

### ISSUE THREAD

**Issue by tzhu-bio** [GreenleafLab/ArchR#927]
I used the custom genome with building a BSgenome object, but when I ran **addGroupCoverages**, I get the error.

It looks that **no genome** has found.

![image](https://user-images.githubusercontent.com/54537420/126748587-071d4054-ce3d-473e-a4b5-71bb89e65858.png)

[ArchR-addGroupCoverages-18181f6a8c3d-Date-2021-07-23_Time-15-03-58.log](https://github.com/GreenleafLab/ArchR/files/6867084/ArchR-addGroupCoverages-18181f6a8c3d-Date-2021-07-23_Time-15-03-58.log)

**Comment by rcorces** [comment]
ArchR cannot find your genome package. This means that the function linked below is failing, which likely means that your package is not installed in the same way that ArchR expects it to be installed. I think this could be because when one creates a custom BSgenome object, they dont also create and install a package. I'm surprised that this error has not come up before but I've never had the need to create a custom BSgenome. Does this interpretation sound right to you?

https://github.com/GreenleafLab/ArchR/blob/968e4421ce7187a8ac7ea1cf6077412126876d5f/R/HiddenUtils.R#L14

**Comment by rcorces** [comment]
I've removed the `requirePackage` statements in a new branch called `dev_customGenome`. Please test if this fixes your problem by installing this branch, restarting your R session, and reloading ArchR.
`devtools::install_github("GreenleafLab/ArchR", ref="master", repos = BiocManager::repositories())`
Please let me know if this works and I will merge the changes into the current dev branch `release_1.0.2`

**Comment by tzhu-bio** [comment]
> I've removed the `requirePackage` statements in a new branch called `dev_customGenome`. Please test if this fixes your problem by installing this branch, restarting your R session, and reloading ArchR.
> `devtools::install_github("GreenleafLab/ArchR", ref="master", repos = BiocManager::repositories())`
> Please let me know if this works and I will merge the changes into the current dev branch `release_1.0.2`

Thanks for your reply.

I did what you said, but it still reports an error.
[ArchR-addGroupCoverages-1a2de2cfe36f2-Date-2021-07-25_Time-11-32-44.log](https://github.com/GreenleafLab/ArchR/files/6873345/ArchR-addGroupCoverages-1a2de2cfe36f2-Date-2021-07-25_Time-11-32-44.log)

**Comment by rcorces** [comment]
I'm very sorry, my previous post had a typo. This is the correct install command:
`devtools::install_github("GreenleafLab/ArchR", ref="dev_customGenome", repos = BiocManager::repositories())`

Please test if this fixes your problem by installing this branch, restarting your R session, and reloading ArchR.

**Comment by rcorces** [comment]
@tzhu-bio - please confirm if this fix works for you

**Comment by tzhu-bio** [comment]
> @tzhu-bio - please confirm if this fix works for you

Sorry for the delay, it works now for me!

Thanks.

**Comment by tzhu-bio** [comment]
But I uesd **addReproduciblePeakSet** also get this error.

[ArchR-addReproduciblePeakSet-c8569b69b3d-Date-2021-07-28_Time-09-49-05.log](https://github.com/GreenleafLab/ArchR/files/6889793/ArchR-addReproduciblePeakSet-c8569b69b3d-Date-2021-07-28_Time-09-49-05.log)

**Comment by rcorces** [comment]
I dont see an error in your log file. Can you clarify what command you have used and what error you are receiving?

**Comment by tzhu-bio** [comment]
> I dont see an error in your log file. Can you clarify what command you have used and what error you are receiving?

![image](https://user-images.githubusercontent.com/54537420/127425738-d7c8fdc4-31be-4d50-be36-3095fba61f56.png)

**Comment by rcorces** [comment]
Thanks. I had missed that one (and one other). I've fixed those in the same branch. Please reinstall, restart R, reload ArchR and see if it works.
`devtools::install_github("GreenleafLab/ArchR", ref="dev_customGenome", repos = BiocManager::repositories())`

**Comment by tzhu-bio** [comment]
> Thanks. I had missed that one (and one other). I've fixed those in the same branch. Please reinstall, restart R, reload ArchR and see if it works.
> `devtools::install_github("GreenleafLab/ArchR", ref="dev_customGenome", repos = BiocManager::repositories())`

Thank you very much,  it works now for me

**Comment by rcorces** [comment]
Great! Thanks @tzhu-bio for confirming that works. I'm going to leave this issue open until we merge the changes into `release_1.0.2`.

This may be a lot to ask, but if you have time and would be willing, I think it would be very beneficial to other users to see how you have created a custom genome from scratch. We dont currently have these instructions in the user manual and have not had time to work through all of this ourselves. I would be happy to include this as a vignette in the next documentation release. If you're willing, you can either post it here or send us an email at archrdevs@gmail.com

**Comment by tzhu-bio** [comment]
> Great! Thanks @tzhu-bio for confirming that works. I'm going to leave this issue open until we merge the changes into `release_1.0.2`.
> 
> This may be a lot to ask, but if you have time and would be willing, I think it would be very beneficial to other users to see how you have created a custom genome from scratch. We dont currently have these instructions in the user manual and have not had time to work through all of this ourselves. I would be happy to include this as a vignette in the next documentation release. If you're willing, you can either post it here or send us an email at [archrdevs@gmail.com](mailto:archrdevs@gmail.com)

I create a custom BSgenome object from here (I don't think this is difficult): https://www.bioconductor.org/packages/devel/bioc/vignettes/BSgenome/inst/doc/BSgenomeForge.pdf

**Comment by tzhu-bio** [comment]
Sorry, I've got another error with **addMotifAnnotations**

[ArchR-addMotifAnnotations-14d8d3e5ffcdd-Date-2021-08-02_Time-10-22-08.log](https://github.com/GreenleafLab/ArchR/files/6914017/ArchR-addMotifAnnotations-14d8d3e5ffcdd-Date-2021-08-02_Time-10-22-08.log)

**Comment by tzhu-bio** [comment]
Sorry, I've got another similar error with **addMotifAnnotations**.

![image](https://user-images.githubusercontent.com/54537420/127796679-650d74f0-1c18-4aaa-a212-9eca5d244477.png)

[ArchR-addMotifAnnotations-14d8d3e5ffcdd-Date-2021-08-02_Time-10-22-08.log](https://github.com/GreenleafLab/ArchR/files/6914021/ArchR-addMotifAnnotations-14d8d3e5ffcdd-Date-2021-08-02_Time-10-22-08.log)

**Comment by rcorces** [comment]
Sorry that this keeps coming up. the search feature on GitHub is terrible and I apparently have not been able to find all of these instances. Feel free to keep posting them here if you find more. I fixed this one via https://github.com/GreenleafLab/ArchR/commit/8adea54390f1d6ce2e92370f9a09b8d8409683b3

You can reinstall the `dev_customGenome` branch.

**Comment by rcorces** [comment]
Closing for now. Feel free to comment here if you encounter any additional issues.
