### ISSUE TITLE
no fragments found in tutorial data after successful running 

### ISSUE THREAD

**Issue by afkm34** [GreenleafLab/ArchR#928]
**Attach your log file**
[ArchR-createArrows-3197ee21221-Date-2021-07-23_Time-09-58-11.log](https://github.com/GreenleafLab/ArchR/files/6869252/ArchR-createArrows-3197ee21221-Date-2021-07-23_Time-09-58-11.log)
ArchRLogs/ArchR-addIterativeLSI-31964a36de1-Date-2021-07-23_Time-09-33-50.log

**Describe the bug**
I was running ArchR successfully yesterday using my own data. Suddenly, an error was thrown despite having used the function multiple times that day, this time I was just using a different subset of the Seurat object to add to the integration matrix in addIntegrationMatrix . 
<simpleError in .getPartialMatrix(ArrowFiles = ArrowFiles, featureDF = featureDF,     useMatrix = useMatrix, cellNames = cellNames, doSampleCells = FALSE,     threads = threads, verbose = FALSE, logFile = logFile): Error not all cellNames found in partialMatrix>. I looked at the GitHub and installed the most recent version that supposedly fixed this bug (1.0.2), but the error has persisted. I noticed that other people had been able to get around the error by reuploading the arrow files from the start, however, the fragments that had been successfully creating arrow files resulted in the error "no fragments found". Upon also attempting to re run the tutorial data, which I have successfully run in the past, I am getting the same issue. 

**To Reproduce**
this was reproduced using the tutorial dataset 

**Session Info**
R version 4.1.0 (2021-05-18)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 11.3.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     

**Additional context**
This analysis is time sensitive so would love to be able to troubleshoot ASAP. I am relatively new to ArchR so please let me know if you need anything else.

**Comment by rcorces** [comment]
Sorry but this sounds like an environment-specific problem and something far beyond what I could help you troubleshoot. If you are unable to run the tutorial, then that is almost certainly an environment problem. Maybe you ran out of disk space or something weird.
