### ISSUE TITLE
Using addIterativeLSI with a PeakMatrix

### ISSUE THREAD

**Issue by rcorces** [GreenleafLab/ArchR#941]
### Discussed in https://github.com/GreenleafLab/ArchR/discussions/795

<div type='discussions-op-text'>

<sup>Originally posted by **skwalker** June  2, 2021</sup>
Hi!

Thanks for building such a great platform for analyzing scATAC-seq data ! I've been playing around with using different values for `ceiling` when running `addPeakMatrix` and seeing how they change the lower dimensionality space by running `addIterativeLSI` with `useMatrix = "PeakMatrix"`. I've found that changing the value for `ceiling`, while it certainly changes the values in the Peak Matrix, does not seem to affect the lower dimensionality space; for example, my UMAP plots are exactly the same when I use `ceiling=1` and `ceiling=30`, and in addition, the SVD matrix generated from the reduced dimensions is also unchanged.  It seems a little bizarre to me that this wouldn't change anything since the Peak Matrix is quite different in these two situations. Do you have any idea of why updating the PeakMatrix like this wouldn't actually change the lower dimensionality space ? It is definitely using the PeakMatrix, right? 

Thanks,
Sarah</div>

As noted in the linked discussion, `addIterativeLSI()` does not seem to give different results when using `PeakMatrix` input created from peak sets using different ceilings.

**Comment by rcorces** [comment]
To re-summarize the observed behavior - you can give ArchR two different `PeakMatrix` objects that are created using different ceiling parameters but ArchR creates `$matSVD` objects that are identical when running `addIterativeLSI()` on those different `PeakMatrix` objects.

@skwalker - I think its possible that all of this behavior is actually correct and is due to the parameters being given to `addIterativeLSI()`. In your reprex, ` firstSelection = top` and `binarize = TRUE`. Because the data is being binarized, I think the difference in `ceiling` is effectively ignored. When you go to later iterations of the LSI, you are using `selectionMethod = var` which would normally use the non-binarized matrix to select top variable features but your workflow just so happens to subset the total number of peaks to `25000` which also happens to be less than `varFeatures = 52004` so no subsetting of features is done and you're left with identical `SVD` results.

So I do not believe that this is a bug at all. Let me know if this makes sense. I have tested this on my end and confirmed that setting `varFeatures` to something less than the total features solves the problem.

Closing this issue for now but feel free to post here if you dont feel that this has been solved.

**Comment by skwalker** [comment]
Thanks for looking into this ! This make sense. However, I did actually play around with the `binarize=FALSE` parameter, but I was never able to get it to run successfully. I got an error that I couldn't use the `selectionMethod=var` and then when I changed it to `vmr` I got another error: `'rowMeansLog2' does not exist in this HDF5 file`. Have you run into that issue as well ?

**Comment by rcorces** [comment]
There are many arguments to `addIterativeLSI()` that have complex interactions, illustrated well by the odd behavior we discussed previously. If you want clarification on additional features, create a new issue using the provided issue template and give a reproducible example. For starters, you are forced to use `binarize = TRUE` when `firstSelection = top`

**Comment by chenc327** [comment]
acturally the same，I have searched many issuees provided previously. However I DONT get any idea about the resolution.
I use the iterative cluster method. I call peak based on the initial clusters then I TRY to use use addIterativeLSI based on peakMatrix and set the 'iterations' = 1,  firstSelection = "var". BUT I got error: 
```
Error in h5read(ArrowFiles[y], paste0(useMatrix, "/", seqx, "/rowMeansLog2")) : 
  Object 'PeakMatrix/chr1/rowMeansLog2' does not exist in this HDF5 file.
```
IS there any wrong with my choose?
my script like this:
```
proj <- addPeakMatrix(proj, binarize = FALSE, force = TRUE)
proj <- addIterativeLSI(
  ArchRProj = proj,
  clusterParams = list(resolution = c(6), sampleCells = 10000, maxClusters = 20, n.start = 10),
  useMatrix = "PeakMatrix",
  name = "IterativeLSI_peak",
  iterations = 1,
  firstSelection = "var",
  binarize = FALSE,
  selectionMethod = "var",
  varFeatures = 30000,
  force = TRUE,
  corCutOff=0.5,
  excludeChr = c("chrM", "chrY", "chrX"),
  seed = 12
)
```

**Comment by rcorces** [comment]
@chenc327 please open a new issue, following the provided template, and provide a reproducible example using the tutorial dataset
