### ISSUE TITLE
Gene Annotation Version?

### ISSUE THREAD

**Issue by kgj1234** [GreenleafLab/ArchR#944]
I was trying to match browser tracks from ArchR using the default mm10 genome browser with the UCSC mm10 genome browser. I noticed a large discrepancy in genome location for approximately 2% of genes. For example Nrg1 is placed at chr8 31818028-32009491 on the default mm10 and chr8 31814551-32884797 on the most recent update (after manually creating genome and gene annotations from the most recent BSgenome). Is this a version issue? Is there a list of genes that are most affected?

ArchR version is ArchR_1.0.1

**Comment by kgj1234** [comment]
Looks that version may be an isoform.

**Comment by rcorces** [comment]
The genes displayed on ArchR browser tracks are whatever is present in your `geneAnnotation`. So any mismatch that you see is because the `geneAnnotation` you are using is different from the gene annotation being used in the online browser.

**Comment by rcorces** [comment]
now clarified in function explanations via https://github.com/GreenleafLab/ArchR/commit/73a286707415c01f07394861ab606cfd187a2568
