### ISSUE TITLE
Can I change the color for plotEmbedding?

### ISSUE THREAD

**Issue by raphaela2018** [GreenleafLab/ArchR#947]
Hi, 

I've tried to change the color manually for plotEmbedding. 

library(RColorBrewer)
test1 = c(brewer.pal(name="Paired", n = 6))
p1 <- plotEmbedding(ArchRProj = projIGW5, colorBy = "cellColData", name = "celltypes", 
                    embedding = "UMAP", pal=test1) + ggtitle("UMAP")
ggAlignPlots(p1,type = "h")

This returns all gray. Can I know what I did wrong and how to change the color manually?

Thanks a lot!

**Comment by rcorces** [comment]
Please note that this is not an error or bug and should be posted in Discussions
![image](https://user-images.githubusercontent.com/10343046/127541120-e4ade963-6f6a-480a-bdc4-ac8f03b86394.png)

Please see the function parameter definitions for your answer.
https://www.archrproject.com/reference/plotEmbedding.html
![image](https://user-images.githubusercontent.com/10343046/127541018-df8b1392-1bff-40a2-860a-61cf3308337b.png)
