### ISSUE TITLE
plotMarkerHeatmap: Incompatibility of 'clusterCols=FALSE' and 'binaryClusterRows=TRUE' 

### ISSUE THREAD

**Issue by boberrey** [GreenleafLab/ArchR#948]
[ArchR-plotMarkerHeatmap-33aca73a407fc-Date-2021-07-29_Time-09-52-10.log](https://github.com/GreenleafLab/ArchR/files/6903732/ArchR-plotMarkerHeatmap-33aca73a407fc-Date-2021-07-29_Time-09-52-10.log)

**Describe the bug**
Already solved this for myself, but just wanted to let you guys know that there's a minor issue where plotMarkerHeatmap fails when you try and use both 'clusterCols=FALSE' and 'binaryClusterRows=TRUE'. This seems to be because ComplexHeatmap expects 'cluster_cols' to be "a logical value, a clustering function or a clustering object". When 'clusterCols' is set to FALSE, .binarySort() returns 'NULL' which causes ComplexHeatmap to choke and fail. 

The problem seems to be here in MarkerFeatures.R:
```R
if(binaryClusterRows){
  if(invert){
    bS <- .binarySort(-mat, lmat = passMat[rownames(mat), colnames(mat),drop=FALSE], clusterCols = clusterCols)
    mat <- -bS[[1]][,colnames(mat),drop=FALSE]
  }else{
    bS <- .binarySort(mat, lmat = passMat[rownames(mat), colnames(mat),drop=FALSE], clusterCols = clusterCols)
    mat <- bS[[1]][,colnames(mat),drop=FALSE]
  }
  clusterRows <- FALSE
  clusterCols <- bS[[2]]
}else{
  clusterRows <- TRUE
  clusterCols <- TRUE
}
```

An easy fix that worked for me:

```R
if(binaryClusterRows){
  if(invert){
    bS <- .binarySort(-mat, lmat = passMat[rownames(mat), colnames(mat),drop=FALSE], clusterCols = clusterCols)
    mat <- -bS[[1]][,colnames(mat),drop=FALSE]
  }else{
    bS <- .binarySort(mat, lmat = passMat[rownames(mat), colnames(mat),drop=FALSE], clusterCols = clusterCols)
    mat <- bS[[1]][,colnames(mat),drop=FALSE]
  }
  clusterRows <- FALSE
  if(clusterCols) clusterCols <- bS[[2]]
}else{
  clusterRows <- TRUE
  clusterCols <- TRUE
}
```

Thanks!

**Comment by rcorces** [comment]
Thanks for reporting. This does seem to be the safest fix since `.binarySort()` is also used in `plotEnrichHeatmap()` and the `NULL` value is actually used in a test:
https://github.com/GreenleafLab/ArchR/blob/968e4421ce7187a8ac7ea1cf6077412126876d5f/R/AnnotationPeaks.R#L1109

I've gone ahead and made your proposed change in `release_1.0.2` via https://github.com/GreenleafLab/ArchR/commit/17d613db4b847e978264d5a7dd275c081e36541b
