### ISSUE TITLE
Problems while installing ArchR

### ISSUE THREAD

**Issue by xxxcha** [GreenleafLab/ArchR#949]
Hi when I am installing ArchR on linux, and I met some problems when installing the package rhdf5lib.

Error in download.file(url, destfile, method, mode = "wb", ...) :
  download from 'https://bioconductor.org/packages/3.13/bioc/src/contrib/Rhdf5lib_1.14.2.tar.gz' failed
In addition: Warning messages:
1: In .inet_warning(msg) :
  downloaded length 1146192 != reported length 9991926
2: In .inet_warning(msg) :
  URL 'https://bioconductor.org/packages/3.13/bioc/src/contrib/Rhdf5lib_1.14.2.tar.gz': Timeout of 300 seconds was reached
Warning message:
In .inet_warning(msg) : download of package ‘Rhdf5lib’ failed

I tried many times and it always cannot fully download the package, so how to fix it?

**Comment by rcorces** [comment]
Since this is not an error related to the ArchR software itself, I'm closing this issue.

My advice would be to review the bioconductor instructions for package installation and post on a general bioconductor forum or similar.
https://www.bioconductor.org/install/

Sorry to not be of more help.

**Comment by xxxcha** [comment]
> Since this is not an error related to the ArchR software itself, I'm closing this issue.
> 
> My advice would be to review the bioconductor instructions for package installation and post on a general bioconductor forum or similar.
> https://www.bioconductor.org/install/
> 
> Sorry to not be of more help.

That's OK. Thanks a lot!
