### ISSUE TITLE
addIterativeLSI doesn't work without binarizing the data

### ISSUE THREAD

**Issue by skwalker** [GreenleafLab/ArchR#958]
**Attach your log file**

[ArchR-addIterativeLSI-397c734470674-Date-2021-08-04_Time-17-55-49.log](https://github.com/GreenleafLab/ArchR/files/6934607/ArchR-addIterativeLSI-397c734470674-Date-2021-08-04_Time-17-55-49.log)

**Describe the bug**

Setting the `binarize` parameter to `FALSE`  in `addIterativeLSI` throws an error:

```
Error in h5read(ArrowFiles[y], paste0(useMatrix, "/", seqx, "/rowMeansLog2")): Object 'TileMatrix/chr1/rowMeansLog2' does not exist in this HDF5 file.
Traceback:

1. addIterativeLSI(ArchRProj = proj, useMatrix = "TileMatrix", name = "IterativeLSICeiling", 
 .     iterations = 4, clusterParams = list(resolution = c(1.5), 
 .         sampleCells = 10000, n.start = 10, maxClusters = 25), 
 .     varFeatures = 25000, dimsToUse = 1:30, force = TRUE, LSIMethod = 2, 
 .     binarize = FALSE, selectionMethod = "vmr", firstSelection = "var")
2. .getRowVars(ArrowFiles = ArrowFiles, useMatrix = useMatrix, seqnames = chrToRun, 
 .     useLog2 = TRUE)
3. .safelapply(seq_along(featureDF), function(x) {
 .     o <- h5closeAll()
 .     seqx <- names(featureDF)[x]
 .     meanx <- matrix(NA, ncol = length(ArrowFiles), nrow = nrow(featureDF[[x]]))
 .     varx <- matrix(NA, ncol = length(ArrowFiles), nrow = nrow(featureDF[[x]]))
 .     for (y in seq_along(ArrowFiles)) {
 .         if (useLog2) {
 .             meanx[, y] <- h5read(ArrowFiles[y], paste0(useMatrix, 
 .                 "/", seqx, "/rowMeansLog2"))
 .             varx[, y] <- h5read(ArrowFiles[y], paste0(useMatrix, 
 .                 "/", seqx, "/rowVarsLog2"))
 .         }
 .         else {
 .             meanx[, y] <- h5read(ArrowFiles[y], paste0(useMatrix, 
 .                 "/", seqx, "/rowMeans"))
 .             varx[, y] <- h5read(ArrowFiles[y], paste0(useMatrix, 
 .                 "/", seqx, "/rowVars"))
 .         }
 .     }
 .     cbind(featureDF[[x]], DataFrame(.combineVariances(meanx, 
 .         varx, ns)))
 . }, threads = threads) %>% Reduce("rbind", .)
4. Reduce("rbind", .)
5. .safelapply(seq_along(featureDF), function(x) {
 .     o <- h5closeAll()
 .     seqx <- names(featureDF)[x]
 .     meanx <- matrix(NA, ncol = length(ArrowFiles), nrow = nrow(featureDF[[x]]))
 .     varx <- matrix(NA, ncol = length(ArrowFiles), nrow = nrow(featureDF[[x]]))
 .     for (y in seq_along(ArrowFiles)) {
 .         if (useLog2) {
 .             meanx[, y] <- h5read(ArrowFiles[y], paste0(useMatrix, 
 .                 "/", seqx, "/rowMeansLog2"))
 .             varx[, y] <- h5read(ArrowFiles[y], paste0(useMatrix, 
 .                 "/", seqx, "/rowVarsLog2"))
 .         }
 .         else {
 .             meanx[, y] <- h5read(ArrowFiles[y], paste0(useMatrix, 
 .                 "/", seqx, "/rowMeans"))
 .             varx[, y] <- h5read(ArrowFiles[y], paste0(useMatrix, 
 .                 "/", seqx, "/rowVars"))
 .         }
 .     }
 .     cbind(featureDF[[x]], DataFrame(.combineVariances(meanx, 
 .         varx, ns)))
 . }, threads = threads)
6. lapply(...)
7. FUN(X[[i]], ...)
8. h5read(ArrowFiles[y], paste0(useMatrix, "/", seqx, "/rowMeansLog2"))
9. stop("Object '", name, "' does not exist in this HDF5 file.")
```

**To Reproduce**

I have this issue with the tutorial dataset :

```
inputFiles <- getTutorialData("Hematopoiesis")

ArrowFiles <- createArrowFiles(
  inputFiles = inputFiles,
  sampleNames = names(inputFiles),
  filterTSS = 4, #Dont set this too high because you can always increase later
  filterFrags = 1000, 
  addTileMat = TRUE,
  addGeneScoreMat = TRUE
)

proj <- ArchRProject(
  ArrowFiles = ArrowFiles, 
  outputDirectory = "HemeTutorial",
  copyArrows = TRUE #This is recommened so that you maintain an unaltered copy for later usage.
)

proj <- addTileMatrix(proj, binarize=FALSE, force=TRUE)

proj<- addIterativeLSI(ArchRProj = proj, 
    useMatrix = "TileMatrix",
    name = "IterativeLSICeiling",
    iterations = 4,
    clusterParams = list( #See Seurat::FindClusters
        resolution = c(1.5),
        sampleCells = 10000,
        n.start = 10,
        maxClusters = 25
     ),
    varFeatures = 25000,
    dimsToUse = 1:30,
    force = TRUE,
    LSIMethod = 2,
    binarize = FALSE,
    selectionMethod = "vmr",                       
    # if not using binarized counts, must also use:
    firstSelection = "var"
 )
```

**Expected behavior**

I expected it to run without any errors (or with a helpful error message if it's a user error / I'm using some poor argument choices).

**Comment by rcorces** [comment]
I'm on vacation but nobody else will reply. I dont know why this happens but I think this is because you set `binarize = FALSE` on `addTileMatrix()` or because you are double-adding a tile matrix both during `createArrowFiles()` and after making your project.

**Comment by rcorces** [comment]
Hi @skwalker - any update to this?

**Comment by skwalker** [comment]
But I have to set `binarize` to FALSE when I add the tile matrix so that I don't have binarized counts.

And changing `addTileMat = TRUE`  in `createArrowFiles` still gives the same error message.

**Comment by rcorces** [comment]
As best I can tell, this is not a use case that we normally use. The problem occurs when you use `firstSelection = "var"` in conjunction with `useMatrix = "TileMatrix"`. That is not to say that it is an incorrect use case, just not one that has come up before.

When the TileMatrix is created and added to the Arrow files, HDF5 groups are not created for `rowMeansLog2` and `rowVarsLog2`
https://github.com/GreenleafLab/ArchR/blob/968e4421ce7187a8ac7ea1cf6077412126876d5f/R/MatrixTiles.R#L241

but these groups are expected in `addIterativeLSI()`
https://github.com/GreenleafLab/ArchR/blob/968e4421ce7187a8ac7ea1cf6077412126876d5f/R/IterativeLSI.R#L253
https://github.com/GreenleafLab/ArchR/blob/968e4421ce7187a8ac7ea1cf6077412126876d5f/R/ArrowRead.R#L958

I'm not sure what the downstream repercussions of this will be so I've made a patch in the branch `dev_tileMatrix` which is based on the `release_1.0.2` branch. You can try to install this branch, restart your R session, and re-make arrow files or re-add the tilematrix to your existing arrow files. Then re-run `addIterativeLSI()`.

`devtools::install_github("GreenleafLab/ArchR", ref="dev_tileMatrix", repos = BiocManager::repositories())`

Let me know if this works.

**Comment by rcorces** [comment]
@skwalker - any update on this?

**Comment by rcorces** [comment]
@skwalker - It would be very helpful if you could test the above fix to see if it works for you. Please let me know.

**Comment by rcorces** [comment]
Sorry for the delay in replying.

> One very minor thing is I got an unnecessary/redundant error while running addIterativeLSI on a matrix of binarized counts Please binarize data if using top selection for first iteration! Set binarize = TRUE! despite the data already being binarized.

I've fixed the error messaging here so that it does not ask you to binarize a matrix that is already binarized via https://github.com/GreenleafLab/ArchR/commit/d32148104a5ffe82bcd40b30c7493618df8ea74b

> Similarly, even though the matrix was binarized, I wasn't able to run getMatrixFromProject(proj, useMatrix="TileMatrix", binarize = FALSE), as I got an error about Matrix in Arrow is Binarized! Set binarize = TRUE to use matrix!> which seems a little strange from a user's perspective. I just wanted to make absolute sure that the max of my tile matrix was 1.

I think this is actually the correct behavior. Though perhaps a bit counterintuitive. Setting `binarize = FALSE` tells ArchR that you explicitly dont want to use a binarized matrix. So when it encounters a binarized matrix, it throws an error. Whether a matrix is binary or not is stored in the matrix class attribute in the HDF5 files.

```
> projHeme1 <- addTileMatrix(input = projHeme1, binarize = FALSE, force = TRUE)
ArchR logging to : ArchRLogs/ArchR-addTileMatrix-231c503ed082f7-Date-2021-11-10_Time-11-41-32.log
If there is an issue, please report to github with logFile!
2021-11-10 11:41:32 : Batch Execution w/ safelapply!, 0 mins elapsed.
> matClass <- h5read(getArrowFiles(ArchRProj = projHeme1)[1], paste0("TileMatrix","/Info/Class"))
> matClass
[1] "Sparse.Integer.Matrix"
> 
> projHeme1 <- addTileMatrix(input = projHeme1, binarize = TRUE, force = TRUE)
ArchR logging to : ArchRLogs/ArchR-addTileMatrix-231c50543ef762-Date-2021-11-10_Time-11-55-04.log
If there is an issue, please report to github with logFile!
2021-11-10 11:55:04 : Batch Execution w/ safelapply!, 0 mins elapsed.
> matClass <- h5read(getArrowFiles(ArchRProj = projHeme1)[1], paste0("TileMatrix","/Info/Class"))
> matClass
[1] "Sparse.Binary.Matrix"
```

I've merged these changes into `release_1.0.2` via https://github.com/GreenleafLab/ArchR/pull/1153
I'm going to close this but feel free to comment again below if anything comes up. Thanks for testing this!

**Comment by Puriney** [comment]
I am also hesitating in always setting`binarize=TRUE` option. In some human cancer types which have lots of copy number alterations, it is unfair to binarize those cancer genes having genomic amplification and ATAC signals. I am thinking `binarize=FALSE`. But the risk is some common genes having high ATAC signals would be different from the common genes with low ATAC signals. In `binarize=TRUE` mode, those two common genes are the same. 

In some blood cancer, `binarize=TRUE` seems good because they don't have many CNAs. 

p.s. You gave a  great explanation with codes. Very clear.
