### ISSUE TITLE
Differential peak analysis based on batch corrected cluster ID from Harmony

### ISSUE THREAD

**Issue by jinzhuangdou** [GreenleafLab/ArchR#963]
Hi ArchR team,

I merged multiple samples and performed integration analysis. Cells are still clusters by patient to the most part based on standard LSI. After harmony batch correction, the results seem reasonable. I know the batch-correction is implemented on the low-dimensional space.  When I perform downstream differential peak analysis, are the peaks batch-corrected or still derived from original profiles? In scRNA-seq data of Seurat, there is an imputed RNA after integration. Does ArchR use the same way for peak files? Many thanks.

**Comment by rcorces** [comment]
Usage questions belong in the Discussions forum. Issues are only for bug or error reports. This is stated clearly in the issue template - 
![image](https://user-images.githubusercontent.com/10343046/128543134-12cf6203-e9aa-4692-8072-e91f4115a525.png)

I'm converting your issue to a Discussion.
