### ISSUE TITLE
plotMarkerHeatmap not clustering "clusters" when "transpose = T"

### ISSUE THREAD

**Issue by Zepeng-Mu** [GreenleafLab/ArchR#965]
Hi,
I noticed when using `transpose=T` in `plotMarkerHeatmap`, the rows (which are groupBy but not feature now) seems not to be clustered. This is quite obvious when comparing to `transpose=F`. Is this an intended behavior?
I know there are parameters in the plotting function to control clustering of rows and columns, but row/column is switched after transposing, so I'm not sure whether those still works.

Thanks!

**Comment by rcorces** [comment]
It would be helpful if you include code and images based off the tutorial.

However, I imagine that the problem is that you are still using `clusterCols = TRUE` when using `transpose = TRUE`.

For example:
```
markersPeaks <- getMarkerFeatures(
  ArchRProj = projHeme5, 
  useMatrix = "PeakMatrix", 
  groupBy = "Clusters2",
  bias = c("TSSEnrichment", "log10(nFrags)"),
  testMethod = "wilcoxon"
)

heatmapPeaks <- plotMarkerHeatmap(
  seMarker = markersPeaks, 
  cutOff = "FDR <= 0.1 & Log2FC >= 0.5",
  clusterCols = FALSE,
  binaryClusterRows = TRUE,
  transpose = TRUE
)
```
![image](https://user-images.githubusercontent.com/10343046/128614235-89de729c-50c8-477c-aa99-ef5faeb6568d.png)

**Comment by rcorces** [comment]
make sure to upgrade to the latest version of `release_1.0.2` as well because there was a bug in this function that was recently addressed.
https://github.com/GreenleafLab/ArchR/issues/948

**Comment by Zepeng-Mu** [comment]
Hi,
I think that I'm using clusterCols = TRUE and transpose = TRUE at the same time is the reasons.
Thanks so much!
