### ISSUE TITLE
Pseudo time analysis for only one cell type from both dieases and healthy population? 

### ISSUE THREAD

**Issue by CSBioAzim** [GreenleafLab/ArchR#98]
Given a single cell data for a specific cell type A from both disease and healthy population. I was wondering would it be possible to do the pseudo time trajectory analysis for only cell type A?
This would help to see the dynamics of changes between different cellular states for one specific cell type as specific disease progresses.
Again, it's not about differentiation from cell type A to B, it's about inferring pseudotime of cellular state for cell type A when I have data combined from healthy and disease cases.

Thanks,
Azim

**Comment by rcorces** [comment]
Pseudo-time trajectories can be defined over any user-defined cell group. It is agnostic to all other information. You supply the names of the groups via `trajectory` and the name of the column from `cellColData` via `groupBy`. This is outlined in the documentation. It will help us greatly as developers if users thoroughly read the documentation and extrapolate to their own applications - this is why we wrote such extensive documentation up front.

https://www.archrproject.com/bookdown/myeloid-trajectory-monocyte-differentiation.html
