### ISSUE TITLE
getFootprints: Error: cannot mix "*" with other strand values

### ISSUE THREAD

**Issue by billzt** [GreenleafLab/ArchR#983]
```
> seTSS = getFootprints(
  ArchRProj = proj6samplesDR3,
  positions = GRangesList(TSS = getTSS(proj6samplesDR3)),
  groupBy = "Clusters",
  flank = 2000
)
ArchR logging to : ArchRLogs/ArchR-getFootprints-419054f18054-Date-2021-08-17_Time-10-21-21.log
If there is an issue, please report to github with logFile!
2021-08-17 10:21:21 : Computing Kmer Bias Table, 0.008 mins elapsed.
Error in .starfreeStrand(strand(names)) :
  cannot mix "*" with other strand values
```

[ArchR-getFootprints-419054f18054-Date-2021-08-17_Time-10-21-21.log](https://github.com/GreenleafLab/ArchR/files/6996629/ArchR-getFootprints-419054f18054-Date-2021-08-17_Time-10-21-21.log)

**Comment by rcorces** [comment]
This seems like the correct error message for this situation. It sounds like your TSS annotations are not all stranded and some use "*" for their strand which is not ok for this application. Is this true? If so, you will need to remove those TSS annotations. By definition, it seems like you cannot have a transcription start site without knowing which direction transcription proceeds in.

Closing for now but feel free to comment if you need further help.

**Comment by billzt** [comment]
Yes, finally I've found there were three TSSs with strand "*". How can I remove them without running the whole pipeline?

**Comment by rcorces** [comment]
You cant just subset the `GRanges` object corresponding to the result of `getTSS()` and pass it to `getFootprints()`?

**Comment by billzt** [comment]
After subsetting, it has been resolved.
