### ISSUE TITLE
questions  to install  ArchR

### ISSUE THREAD

**Issue by xiezhan** [GreenleafLab/ArchR#986]
> devtools::install_github("GreenleafLab/ArchR", ref="master", repos = BiocManager::repositories())
Downloading GitHub repo GreenleafLab/ArchR@master
Error: Failed to install 'ArchR' from GitHub:
  Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.

Could you give me  some  advices？

**Comment by rcorces** [comment]
I would imagine you do not have one of the dependencies listed under the installation instructions. Most likely this:

![image](https://user-images.githubusercontent.com/10343046/129743740-295df4a3-7abe-434b-8d7e-b4f973eaf6fa.png)

otherwise, I would try what the error message says to do.

**Comment by xiezhan** [comment]
this  work  for  me：

options(buildtools.check = function(action) TRUE )

**Comment by rcorces** [comment]
thanks for posting your solution!
