### ISSUE TITLE
Error in plotFragmentSizes

### ISSUE THREAD

**Issue by R-Krait** [GreenleafLab/ArchR#988]
[ArchR-plotFragmentSizes-2d3044aecc08d-Date-2021-08-18_Time-12-15-58.log](https://github.com/GreenleafLab/ArchR/files/7004308/ArchR-plotFragmentSizes-2d3044aecc08d-Date-2021-08-18_Time-12-15-58.log)
-> This is my log.

I performed plotFragmentSizes function by using my scATAC-seq data. However, I got this error message.

->
ArchR logging to : ArchRLogs/ArchR-plotFragmentSizes-2d3044aecc08d-Date-2021-08-18_Time-12-15-58.log
If there is an issue, please report to github with logFile!
Error in .safelapply(seq_along(uniqGroups), function(x) { : 
Error Found Iteration 1 : 
	[1] "Error in h(simpleError(msg, call)) : \n  error in evaluating the argument 'x' in selecting a method for function 'width': HDF5. File accessibility. Unable to open file.\n"
	<simpleError in h(simpleError(msg, call)): error in evaluating the argument 'x' in selecting a method for function 'width': HDF5. File accessibility. Unable to open file.>
Error Found Iteration 2 : 
	[1] "Error in h(simpleError(msg, call)) : \n  error in evaluating the argument 'x' in selecting a method for function 'width': HDF5. File accessibility. Unable to open file.\n"
	<simpleError in h(simpleError(msg, call)): error in evaluating the argument 'x' in selecting a method for function 'width': HDF5. File accessibility. Unable to open file.>
Error Found Iteration 3 : 
	[1] "Error in h(simpleError(msg, call)) : \n  error in evaluating the argument 'x' in selecting a method for function 'width': HDF5. File accessibility. Unable to open file.\n"
	<simpleError in h(simpleErro
In addition: Warning message:
In mclapply(..., mc.cores = threads, mc.preschedule = preschedule) :
  3 function calls resulted in an error

So I tried to find a solution. In the github, to solve this similar problem, Sys.setenv(HDF5_USE_FILE_LOCKING=FALSE) or h5disableFileLocking() can be used. But, I got the same error message again. What should I do to solve this problem? Thank you!

**Comment by rcorces** [comment]
One other user reported that this type of error is observed when permissions are not in place and that running R under sudo might help
https://github.com/GreenleafLab/ArchR/issues/972

**Comment by R-Krait** [comment]
Thank you! @rcorces I solved it by changing permission setting of .arrow files...!
