### ISSUE TITLE
An error occurred when the createArrowFiles  

### ISSUE THREAD

**Issue by bill0919** [GreenleafLab/ArchR#989]
I have a set of BAM files that I'm trying to merge and input to the ArchR.

`ArrowFiles <- createArrowFiles(
    inputFiles = 'scATAC_human_NEpith_noDup_noMT_MERGE.bam',
    sampleNames = 'NEpith',
    filterTSS = 4, 
    filterFrags = 1000,
    addTileMat = TRUE,
    addGeneScoreMat = TRUE
)`

However, an error occurred.

> ************************************************************

> 2021-08-18 19:39:00 : ERROR Found in .tmpToArrow for (NEpith : 1 of 1) 

> LogFile = ArchRLogs\ArchR-createArrows-5dc0760e75d0-Date-2021-08-18_Time-19-37-10.log

> <simpleError: Detected 2 or less cells (0 barcodes have greater than 50 fragments) in file!

>    Check inputs such as 'minFrags' or 'maxFrags' to keep cells! Exiting!

>

************************************************************

When I look at the BAM file contents, it seems that it does not have barcode information.

> D00829_0139_ACC51WANXX_PEdi_MB67-MB74:2:1114:17527:80767        163     chr1    10514   35      50M     =       10518   54      GAACTGTGCTCCGCCTTCAGAGTACCACCGAAATCTGTGCAGAGGACAAC      CBCCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFGGGF  MD:Z:50  XG:i:0  NM:i:0  XM:i:0  XN:i:0  XO:i:0  AS:i:0  XS:i:-15        YS:i:0  YT:Z:CP PG:Z:MarkDuplicates-19E18592

> D00829_0139_ACC51WANXX_PEdi_MB67-MB74:2:1114:17527:80767        83      chr1    10518   35      50M     =       10514   -54     TGTGCTCCGCCTTCAGAGTACCACCGAAATCTGTGCAGAGGACAACGCAG      GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGBBB@A  MD:Z:50  XG:i:0  NM:i:0  XM:i:0  XN:i:0  XO:i:0  AS:i:0  XS:i:-15        YS:i:0  YT:Z:CP PG:Z:MarkDuplicates-19E18592

> D00829_0139_ACC51WANXX_PEdi_MB67-MB74:2:1306:9729:13815 163     chr1    64595   30      50M     =       64632   87      CATGTATACATATGTAACTAACCTGCACATTGTGCACATGTACCCTAGAA      CCCCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG      MD:Z:50      XG:i:0  NM:i:0  XM:i:0  XN:i:0  XO:i:0  AS:i:0  XS:i:0  YS:i:0  YT:Z:CP PG:Z:MarkDuplicates-FB16E09

> D00829_0139_ACC51WANXX_PEdi_MB67-MB74:2:1306:9729:13815 83      chr1    64632   30      50M     =       64595   -87     ATGTACCCTAGAACTTAAAGTATAATAAAAAAAAATAGACTCTAGTACTC      CEGGGGGGGGGGGGFGGGGGGGGGGGGGGGGEGGGGGGGGGCGFF@0>3?      MD:Z:50      XG:i:0  NM:i:0  XM:i:0  XN:i:0  XO:i:0  AS:i:0  XS:i:-8 YS:i:0  YT:Z:CP PG:Z:MarkDuplicates-FB16E09

> D00829_0139_ACC51WANXX_PEdi_MB67-MB74:2:2216:4692:2332  99      chr1    134987  30      50M     =       135006  69      CCAAGAGGCTGCCGGAAGGGAAAAACAGGGCCTGGAATGGCCGACGTGAG      ?BB@BGEGGGGGGGGGGGGGGGGGGGGGGGFFGGGGGGGGGGGGGGGGGG      MD:Z:50      XG:i:0  NM:i:0  XM:i:0  XN:i:0  XO:i:0  AS:i:0  XS:i:-5 YS:i:0  YT:Z:CP PG:Z:MarkDuplicates-19E18592

> D00829_0139_ACC51WANXX_PEdi_MB67-MB74:2:2216:4692:2332  147     chr1    135006  30      50M     =       134987  -69     GAAAAACAGGGCCTGGAATGGCCGACGTGAGGAATGAGCTGGGCCTAAAG      GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFGGGGGGGGCCCCC      MD:Z:50      XG:i:0  NM:i:0  XM:i:0  XN:i:0  XO:i:0  AS:i:0  XS:i:-5 YS:i:0  YT:Z:CP PG:Z:MarkDuplicates-19E18592

> D00829_0139_ACC51WANXX_PEdi_MB67-MB74:2:2306:20796:20526        163     chr1    174391  30      50M     =       174396  55      TGGTGGTTCATGCCTGTAATTCCAACAGTTTGGGAGGCCAAGGCAGGCAG      CCCCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG  MD:Z:50  XG:i:0  NM:i:0  XM:i:0  XN:i:0  XO:i:0  AS:i:0  XS:i:-5 YS:i:0  YT:Z:CP PG:Z:MarkDuplicates-5B8600F3

> D00829_0139_ACC51WANXX_PEdi_MB67-MB74:2:2306:20796:20526        83      chr1    174396  30      50M     =       174391  -55     GTTCATGCCTGTAATTCCAACAGTTTGGGAGGCCAAGGCAGGCAGATAAC      GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGBB><3  MD:Z:50  XG:i:0  NM:i:0  XM:i:0  XN:i:0  XO:i:0  AS:i:0  XS:i:-5 YS:i:0  YT:Z:CP PG:Z:MarkDuplicates-5B8600F3

> D00829_0139_ACC51WANXX_PEdi_MB67-MB74:2:2106:1872:81343 163     chr1    244109  30      50M     =       244123  64      CTATAAACATGTAGCATTGTGATTAGGGCTGGTTCTCCTTCTAGAGATAT      BCCCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG      MD:Z:50      XG:i:0  NM:i:0  XM:i:0  XN:i:0  XO:i:0  AS:i:0  XS:i:-5 YS:i:0  YT:Z:CP PG:Z:MarkDuplicates-1F23889B

> D00829_0139_ACC51WANXX_PEdi_MB67-MB74:2:2106:1872:81343 83      chr1    244123  30      50M     =       244109  -64     CATTGTGATTAGGGCTGGTTCTCCTTCTAGAGATATGGTAGGATTGCAAT      GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFGGGGGGGBBB@B      MD:Z:50      XG:i:0  NM:i:0  XM:i:0  XN:i:0  XO:i:0  AS:i:0  XS:i:-5 YS:i:0  YT:Z:CP PG:Z:MarkDuplicates-1F23889B

I find that each BAM file represents the sequencing result of a cell, so how do I input it into the ArchR?

[ArchR-createArrows-5dc0760e75d0-Date-2021-08-18_Time-19-37-10.log](https://github.com/GreenleafLab/ArchR/files/7006996/ArchR-createArrows-5dc0760e75d0-Date-2021-08-18_Time-19-37-10.log)

Thanks for your help.

**Comment by rcorces** [comment]
ArchR requires your BAM file to have a field that corresponds to the cell barcode/ID. You'll have to figure out a way to make the correct BAM file format on your own. I would suggest posting to general forums like biostars.
