### ISSUE TITLE
plotFootprints must specify a real ArchRProj

### ISSUE THREAD

**Issue by hukai916** [GreenleafLab/ArchR#998]
This is simple, unlike what plotPDF does, plotFootprints won't accept "ArchRProj = NULL".
It basically lacks of:
    if (is.null(ArchRProj)) {
        outDir <- "Plots"
    }

**Comment by rcorces** [comment]
Thanks for reporting. I believe this is the fix you suggested. now implemented in branch `release_1.0.2` via https://github.com/GreenleafLab/ArchR/commit/cd8baa379a169642cd8ba9f71272aea65f8d130e
